module Whopsdk
  module Resources
    class AppBuilds
      def create: (
        attachment: Whopsdk::AppBuildCreateParams::Attachment,
        checksum: String,
        platform: Whopsdk::Models::app_build_platforms,
        ?app_id: String?,
        ?supported_app_view_types: ::Array[Whopsdk::Models::app_view_type]?,
        ?request_options: Whopsdk::request_opts
      ) -> Whopsdk::AppBuild

      def retrieve: (
        String id,
        ?request_options: Whopsdk::request_opts
      ) -> Whopsdk::AppBuild

      def list: (
        app_id: String,
        ?after: String?,
        ?before: String?,
        ?first: Integer?,
        ?last: Integer?,
        ?platform: Whopsdk::Models::app_build_platforms?,
        ?status: Whopsdk::Models::app_build_statuses?,
        ?request_options: Whopsdk::request_opts
      ) -> Whopsdk::Internal::CursorPage[Whopsdk::Models::AppBuildListResponse]

      def promote: (
        String id,
        ?request_options: Whopsdk::request_opts
      ) -> Whopsdk::AppBuild

      def initialize: (client: Whopsdk::Client) -> void
    end
  end
end
