module Whopsdk
  module Resources
    class Apps
      def create: (
        company_id: String,
        name: String,
        ?base_url: String?,
        ?request_options: Whopsdk::request_opts
      ) -> Whopsdk::App

      def retrieve: (
        String id,
        ?request_options: Whopsdk::request_opts
      ) -> Whopsdk::App

      def update: (
        String id,
        ?app_store_description: String?,
        ?base_url: String?,
        ?dashboard_path: String?,
        ?description: String?,
        ?discover_path: String?,
        ?experience_path: String?,
        ?icon: Whopsdk::AppUpdateParams::Icon?,
        ?name: String?,
        ?required_scopes: ::Array[Whopsdk::Models::AppUpdateParams::required_scope]?,
        ?status: Whopsdk::Models::app_statuses?,
        ?request_options: Whopsdk::request_opts
      ) -> Whopsdk::App

      def list: (
        ?after: String?,
        ?before: String?,
        ?company_id: String?,
        ?direction: Whopsdk::Models::direction?,
        ?first: Integer?,
        ?last: Integer?,
        ?order: Whopsdk::Models::AppListParams::order?,
        ?query: String?,
        ?verified_apps_only: bool?,
        ?view_type: Whopsdk::Models::AppListParams::view_type?,
        ?request_options: Whopsdk::request_opts
      ) -> Whopsdk::Internal::CursorPage[Whopsdk::Models::AppListResponse?]

      def initialize: (client: Whopsdk::Client) -> void
    end
  end
end
