module Whopsdk
  module Resources
    class Entries
      def retrieve: (
        String id,
        ?request_options: Whopsdk::request_opts
      ) -> Whopsdk::Entry

      def list: (
        company_id: String,
        ?after: String?,
        ?before: String?,
        ?direction: Whopsdk::Models::direction?,
        ?first: Integer?,
        ?last: Integer?,
        ?order: Whopsdk::Models::EntryListParams::order?,
        ?plan_ids: ::Array[String]?,
        ?product_ids: ::Array[String]?,
        ?statuses: ::Array[Whopsdk::Models::entry_status]?,
        ?request_options: Whopsdk::request_opts
      ) -> Whopsdk::Internal::CursorPage[Whopsdk::Models::EntryListResponse?]

      def approve: (
        String id,
        ?request_options: Whopsdk::request_opts
      ) -> Whopsdk::Models::EntryApproveResponse

      def deny: (
        String id,
        ?request_options: Whopsdk::request_opts
      ) -> Whopsdk::Entry

      def initialize: (client: Whopsdk::Client) -> void
    end
  end
end
