module Whopsdk
  module Resources
    class Invoices
      def create: (
        collection_method: Whopsdk::Models::collection_method?,
        company_id: String,
        due_date: Integer,
        plan: Whopsdk::InvoiceCreateParams::Plan,
        ?charge_buyer_fee: bool?,
        ?customer_name: String?,
        ?email_address: String?,
        ?member_id: String?,
        ?payment_token_id: String?,
        ?product: Whopsdk::InvoiceCreateParams::Product?,
        ?product_id: String?,
        ?request_options: Whopsdk::request_opts
      ) -> Whopsdk::Models::InvoiceCreateResponse?

      def retrieve: (
        String id,
        ?request_options: Whopsdk::request_opts
      ) -> Whopsdk::Invoice?

      def list: (
        company_id: String,
        ?after: String?,
        ?before: String?,
        ?direction: Whopsdk::Models::direction?,
        ?filters: Whopsdk::InvoiceListParams::Filters?,
        ?first: Integer?,
        ?last: Integer?,
        ?order: Whopsdk::Models::InvoiceListParams::order?,
        ?request_options: Whopsdk::request_opts
      ) -> Whopsdk::Internal::CursorPage[Whopsdk::InvoiceListItem?]

      def `void`: (String id, ?request_options: Whopsdk::request_opts) -> bool?

      def initialize: (client: Whopsdk::Client) -> void
    end
  end
end
