module Whopsdk
  module Resources
    class Messages
      def create: (
        content: String,
        ?attachments: ::Array[Whopsdk::MessageCreateParams::Attachment]?,
        ?channel_id: String?,
        ?experience_id: String?,
        ?poll: Whopsdk::MessageCreateParams::Poll?,
        ?request_options: Whopsdk::request_opts
      ) -> Whopsdk::Message

      def retrieve: (
        String id,
        ?request_options: Whopsdk::request_opts
      ) -> Whopsdk::Message

      def list: (
        channel_id: String,
        ?after: String?,
        ?before: String?,
        ?first: Integer?,
        ?last: Integer?,
        ?request_options: Whopsdk::request_opts
      ) -> Whopsdk::Internal::CursorPage[Whopsdk::Models::MessageListResponse]

      def initialize: (client: Whopsdk::Client) -> void
    end
  end
end
