module Whopsdk
  module Resources
    class Products
      def create: (
        company_id: String,
        title: String,
        ?access_pass_type: Whopsdk::Models::access_pass_type?,
        ?banner_image: Whopsdk::ProductCreateParams::BannerImage?,
        ?business_type: Whopsdk::Models::business_types?,
        ?collect_shipping_address: bool?,
        ?custom_cta: Whopsdk::Models::custom_cta?,
        ?custom_cta_url: String?,
        ?custom_statement_descriptor: String?,
        ?description: String?,
        ?experience_ids: ::Array[String]?,
        ?global_affiliate_percentage: Float?,
        ?global_affiliate_status: Whopsdk::Models::global_affiliate_status?,
        ?headline: String?,
        ?industry_type: Whopsdk::Models::industry_types?,
        ?member_affiliate_percentage: Float?,
        ?member_affiliate_status: Whopsdk::Models::global_affiliate_status?,
        ?plan_options: Whopsdk::ProductCreateParams::PlanOptions?,
        ?product_highlights: ::Array[Whopsdk::ProductCreateParams::ProductHighlight]?,
        ?product_tax_code_id: String?,
        ?redirect_purchase_url: String?,
        ?route: String?,
        ?visibility: Whopsdk::Models::visibility?,
        ?request_options: Whopsdk::request_opts
      ) -> Whopsdk::Product?

      def retrieve: (
        String id,
        ?request_options: Whopsdk::request_opts
      ) -> Whopsdk::Product?

      def update: (
        String id,
        ?banner_image: Whopsdk::ProductUpdateParams::BannerImage?,
        ?business_type: Whopsdk::Models::business_types?,
        ?collect_shipping_address: bool?,
        ?custom_cta: Whopsdk::Models::custom_cta?,
        ?custom_cta_url: String?,
        ?custom_statement_descriptor: String?,
        ?description: String?,
        ?global_affiliate_percentage: Float?,
        ?global_affiliate_status: Whopsdk::Models::global_affiliate_status?,
        ?headline: String?,
        ?industry_type: Whopsdk::Models::industry_types?,
        ?member_affiliate_percentage: Float?,
        ?member_affiliate_status: Whopsdk::Models::global_affiliate_status?,
        ?product_tax_code_id: String?,
        ?redirect_purchase_url: String?,
        ?route: String?,
        ?title: String?,
        ?visibility: Whopsdk::Models::visibility?,
        ?request_options: Whopsdk::request_opts
      ) -> Whopsdk::Product?

      def list: (
        company_id: String,
        ?after: String?,
        ?before: String?,
        ?direction: Whopsdk::Models::direction?,
        ?first: Integer?,
        ?last: Integer?,
        ?order: Whopsdk::Models::ProductListParams::order?,
        ?product_types: ::Array[Whopsdk::Models::access_pass_type?]?,
        ?visibilities: ::Array[Whopsdk::Models::visibility_filter?]?,
        ?request_options: Whopsdk::request_opts
      ) -> Whopsdk::Internal::CursorPage[Whopsdk::ProductListItem?]

      def delete: (String id, ?request_options: Whopsdk::request_opts) -> bool?

      def initialize: (client: Whopsdk::Client) -> void
    end
  end
end
