module Whopsdk
  module Resources
    class Reactions
      def create: (
        resource_id: String,
        ?emoji: String?,
        ?request_options: Whopsdk::request_opts
      ) -> Whopsdk::Reaction

      def retrieve: (
        String id,
        ?request_options: Whopsdk::request_opts
      ) -> Whopsdk::Reaction

      def list: (
        resource_id: String,
        ?after: String?,
        ?before: String?,
        ?first: Integer?,
        ?last: Integer?,
        ?request_options: Whopsdk::request_opts
      ) -> Whopsdk::Internal::CursorPage[Whopsdk::Models::ReactionListResponse]

      def initialize: (client: Whopsdk::Client) -> void
    end
  end
end
