module Whopsdk
  module Resources
    class SupportChannels
      def create: (
        company_id: String,
        user_id: String,
        ?request_options: Whopsdk::request_opts
      ) -> Whopsdk::SupportChannel

      def retrieve: (
        String id,
        ?request_options: Whopsdk::request_opts
      ) -> Whopsdk::SupportChannel

      def list: (
        company_id: String,
        ?after: String?,
        ?before: String?,
        ?direction: Whopsdk::Models::direction?,
        ?first: Integer?,
        ?last: Integer?,
        ?open_: bool?,
        ?order: Whopsdk::Models::SupportChannelListParams::order?,
        ?request_options: Whopsdk::request_opts
      ) -> Whopsdk::Internal::CursorPage[Whopsdk::Models::SupportChannelListResponse?]

      def initialize: (client: Whopsdk::Client) -> void
    end
  end
end
