module Whopsdk
  module Resources
    class Transfers
      def create: (
        amount: Float,
        currency: Whopsdk::Models::currency,
        destination_id: String,
        origin_id: String,
        ?idempotence_key: String?,
        ?notes: String?,
        ?request_options: Whopsdk::request_opts
      ) -> Whopsdk::Transfer

      def retrieve: (
        String id,
        ?request_options: Whopsdk::request_opts
      ) -> Whopsdk::Transfer

      def list: (
        ?after: String?,
        ?before: String?,
        ?destination_id: String?,
        ?direction: Whopsdk::Models::direction?,
        ?first: Integer?,
        ?last: Integer?,
        ?order: Whopsdk::Models::TransferListParams::order?,
        ?origin_id: String?,
        ?request_options: Whopsdk::request_opts
      ) -> Whopsdk::Internal::CursorPage[Whopsdk::Models::TransferListResponse?]

      def initialize: (client: Whopsdk::Client) -> void
    end
  end
end
