module Whopsdk
  module Resources
    class Webhooks
      def unwrap: (
        String payload
      ) -> (Whopsdk::InvoiceCreatedWebhookEvent
      | Whopsdk::InvoicePaidWebhookEvent
      | Whopsdk::InvoicePastDueWebhookEvent
      | Whopsdk::InvoiceVoidedWebhookEvent)

      def initialize: (client: Whopsdk::Client) -> void
    end
  end
end
