module Whopsdk
  class CourseLessonInteractionListParams = Whopsdk::Models::CourseLessonInteractionListParams

  class InvoiceCreateParams = Whopsdk::Models::InvoiceCreateParams

  class InvoiceListParams = Whopsdk::Models::InvoiceListParams
end
