module Whopsdk
  class AccessPassListParams = Whopsdk::Models::AccessPassListParams

  class AccessPassRetrieveParams = Whopsdk::Models::AccessPassRetrieveParams

  class CompanyRetrieveParams = Whopsdk::Models::CompanyRetrieveParams

  class CourseLessonInteractionListParams = Whopsdk::Models::CourseLessonInteractionListParams

  class CourseLessonInteractionRetrieveParams = Whopsdk::Models::CourseLessonInteractionRetrieveParams

  class InvoiceCreateParams = Whopsdk::Models::InvoiceCreateParams

  class InvoiceListParams = Whopsdk::Models::InvoiceListParams

  class InvoiceRetrieveParams = Whopsdk::Models::InvoiceRetrieveParams

  class InvoiceVoidParams = Whopsdk::Models::InvoiceVoidParams
end
