module WhopSDK
  module Models
    module Referrals
      module Businesses
        type earning_list_params =
          {
            id: String,
            after: String,
            before: String,
            created_after: String,
            created_before: String,
            direction: WhopSDK::Models::Referrals::Businesses::EarningListParams::direction,
            first: Integer,
            last: Integer,
            order: WhopSDK::Models::Referrals::Businesses::EarningListParams::order,
            status: WhopSDK::Models::Referrals::Businesses::EarningListParams::status
          }
          & WhopSDK::Internal::Type::request_parameters

        class EarningListParams < WhopSDK::Internal::Type::BaseModel
          extend WhopSDK::Internal::Type::RequestParameters::Converter
          include WhopSDK::Internal::Type::RequestParameters

          attr_accessor id: String

          attr_reader after: String?

          def after=: (String) -> String

          attr_reader before: String?

          def before=: (String) -> String

          attr_reader created_after: String?

          def created_after=: (String) -> String

          attr_reader created_before: String?

          def created_before=: (String) -> String

          attr_reader direction: WhopSDK::Models::Referrals::Businesses::EarningListParams::direction?

          def direction=: (
            WhopSDK::Models::Referrals::Businesses::EarningListParams::direction
          ) -> WhopSDK::Models::Referrals::Businesses::EarningListParams::direction

          attr_reader first: Integer?

          def first=: (Integer) -> Integer

          attr_reader last: Integer?

          def last=: (Integer) -> Integer

          attr_reader order: WhopSDK::Models::Referrals::Businesses::EarningListParams::order?

          def order=: (
            WhopSDK::Models::Referrals::Businesses::EarningListParams::order
          ) -> WhopSDK::Models::Referrals::Businesses::EarningListParams::order

          attr_reader status: WhopSDK::Models::Referrals::Businesses::EarningListParams::status?

          def status=: (
            WhopSDK::Models::Referrals::Businesses::EarningListParams::status
          ) -> WhopSDK::Models::Referrals::Businesses::EarningListParams::status

          def initialize: (
            id: String,
            ?after: String,
            ?before: String,
            ?created_after: String,
            ?created_before: String,
            ?direction: WhopSDK::Models::Referrals::Businesses::EarningListParams::direction,
            ?first: Integer,
            ?last: Integer,
            ?order: WhopSDK::Models::Referrals::Businesses::EarningListParams::order,
            ?status: WhopSDK::Models::Referrals::Businesses::EarningListParams::status,
            ?request_options: WhopSDK::request_opts
          ) -> void

          def to_hash: -> {
            id: String,
            after: String,
            before: String,
            created_after: String,
            created_before: String,
            direction: WhopSDK::Models::Referrals::Businesses::EarningListParams::direction,
            first: Integer,
            last: Integer,
            order: WhopSDK::Models::Referrals::Businesses::EarningListParams::order,
            status: WhopSDK::Models::Referrals::Businesses::EarningListParams::status,
            request_options: WhopSDK::RequestOptions
          }

          type direction = :asc | :desc

          module Direction
            extend WhopSDK::Internal::Type::Enum

            ASC: :asc
            DESC: :desc

            def self?.values: -> ::Array[WhopSDK::Models::Referrals::Businesses::EarningListParams::direction]
          end

          type order =
            :created_at | :commission_amount | :transaction_amount | :payout_at

          module Order
            extend WhopSDK::Internal::Type::Enum

            CREATED_AT: :created_at
            COMMISSION_AMOUNT: :commission_amount
            TRANSACTION_AMOUNT: :transaction_amount
            PAYOUT_AT: :payout_at

            def self?.values: -> ::Array[WhopSDK::Models::Referrals::Businesses::EarningListParams::order]
          end

          type status =
            :awaiting_settlement | :pending | :completed | :canceled | :reversed

          module Status
            extend WhopSDK::Internal::Type::Enum

            AWAITING_SETTLEMENT: :awaiting_settlement
            PENDING: :pending
            COMPLETED: :completed
            CANCELED: :canceled
            REVERSED: :reversed

            def self?.values: -> ::Array[WhopSDK::Models::Referrals::Businesses::EarningListParams::status]
          end
        end
      end
    end
  end
end
