# frozen_string_literal: true

module WhopSDK
  module Models
    # @see WhopSDK::Resources::AppBuilds#create
    class AppBuildCreateParams < WhopSDK::Internal::Type::BaseModel
      extend WhopSDK::Internal::Type::RequestParameters::Converter
      include WhopSDK::Internal::Type::RequestParameters

      # @!attribute attachment
      #   Input for an attachment
      #
      #   @return [WhopSDK::Models::AppBuildCreateParams::Attachment]
      required :attachment, -> { WhopSDK::AppBuildCreateParams::Attachment }

      # @!attribute checksum
      #   Checksum of the app build file. This is generated by the client and used to
      #   verify the integrity of the file that is submitted when un-packaged later on a
      #   device.
      #
      #   @return [String]
      required :checksum, String

      # @!attribute platform
      #   The platform of the app build (ios, android, web)
      #
      #   @return [Symbol, WhopSDK::Models::AppBuildPlatforms]
      required :platform, enum: -> { WhopSDK::AppBuildPlatforms }

      # @!attribute app_id
      #   The ID of the app to create a build for. By default the current app from the api
      #   key is used.
      #
      #   @return [String, nil]
      optional :app_id, String, nil?: true

      # @!attribute supported_app_view_types
      #   Supported app view types for the app build. A build can specify multiple view
      #   types, but should only specify ones that its code supports.
      #
      #   @return [Array<Symbol, WhopSDK::Models::AppViewType>, nil]
      optional :supported_app_view_types,
               -> { WhopSDK::Internal::Type::ArrayOf[enum: WhopSDK::AppViewType] },
               nil?: true

      # @!method initialize(attachment:, checksum:, platform:, app_id: nil, supported_app_view_types: nil, request_options: {})
      #   Some parameter documentations has been truncated, see
      #   {WhopSDK::Models::AppBuildCreateParams} for more details.
      #
      #   @param attachment [WhopSDK::Models::AppBuildCreateParams::Attachment] Input for an attachment
      #
      #   @param checksum [String] Checksum of the app build file. This is generated by the client and used to veri
      #
      #   @param platform [Symbol, WhopSDK::Models::AppBuildPlatforms] The platform of the app build (ios, android, web)
      #
      #   @param app_id [String, nil] The ID of the app to create a build for. By default the current app from the api
      #
      #   @param supported_app_view_types [Array<Symbol, WhopSDK::Models::AppViewType>, nil] Supported app view types for the app build. A build can specify multiple view ty
      #
      #   @param request_options [WhopSDK::RequestOptions, Hash{Symbol=>Object}]

      class Attachment < WhopSDK::Internal::Type::BaseModel
        # @!attribute id
        #   The ID of an existing attachment object. Use this when updating a resource and
        #   keeping a subset of the attachments. Don't use this unless you know what you're
        #   doing.
        #
        #   @return [String, nil]
        optional :id, String, nil?: true

        # @!attribute direct_upload_id
        #   This ID should be used the first time you upload an attachment. It is the ID of
        #   the direct upload that was created when uploading the file to S3 via the
        #   mediaDirectUpload mutation.
        #
        #   @return [String, nil]
        optional :direct_upload_id, String, nil?: true

        # @!method initialize(id: nil, direct_upload_id: nil)
        #   Some parameter documentations has been truncated, see
        #   {WhopSDK::Models::AppBuildCreateParams::Attachment} for more details.
        #
        #   Input for an attachment
        #
        #   @param id [String, nil] The ID of an existing attachment object. Use this when updating a resource and k
        #
        #   @param direct_upload_id [String, nil] This ID should be used the first time you upload an attachment. It is the ID of
      end
    end
  end
end
