# frozen_string_literal: true

module WhopSDK
  module Models
    # @see WhopSDK::Resources::AppBuilds#list
    class AppBuildListResponse < WhopSDK::Internal::Type::BaseModel
      # @!attribute id
      #   The unique identifier for the app build.
      #
      #   @return [String]
      required :id, String

      # @!attribute checksum
      #   A SHA-256 hash of the uploaded build file, generated by the client and used to
      #   verify file integrity.
      #
      #   @return [String]
      required :checksum, String

      # @!attribute created_at
      #   The datetime the app build was created.
      #
      #   @return [Time]
      required :created_at, Time

      # @!attribute file_url
      #   A URL to download the app build as a .zip archive.
      #
      #   @return [String]
      required :file_url, String

      # @!attribute is_production
      #   Whether this build is the currently active production build for its platform.
      #
      #   @return [Boolean]
      required :is_production, WhopSDK::Internal::Type::Boolean

      # @!attribute platform
      #   The target platform for this build.
      #
      #   @return [Symbol, WhopSDK::Models::AppBuildPlatforms]
      required :platform, enum: -> { WhopSDK::AppBuildPlatforms }

      # @!attribute review_message
      #   Feedback from the reviewer explaining why the build was rejected. Null if the
      #   build has not been reviewed or was approved.
      #
      #   @return [String, nil]
      required :review_message, String, nil?: true

      # @!attribute status
      #   The current review status of this build.
      #
      #   @return [Symbol, WhopSDK::Models::AppBuildStatuses]
      required :status, enum: -> { WhopSDK::AppBuildStatuses }

      # @!attribute supported_app_view_types
      #   The list of view types this build supports, as declared by the developer.
      #
      #   @return [Array<Symbol, WhopSDK::Models::AppViewType>]
      required :supported_app_view_types, -> { WhopSDK::Internal::Type::ArrayOf[enum: WhopSDK::AppViewType] }

      # @!method initialize(id:, checksum:, created_at:, file_url:, is_production:, platform:, review_message:, status:, supported_app_view_types:)
      #   Some parameter documentations has been truncated, see
      #   {WhopSDK::Models::AppBuildListResponse} for more details.
      #
      #   A versioned build artifact for a Whop React Native App, submitted for review and
      #   deployment to a specific platform.
      #
      #   @param id [String] The unique identifier for the app build.
      #
      #   @param checksum [String] A SHA-256 hash of the uploaded build file, generated by the client and used to v
      #
      #   @param created_at [Time] The datetime the app build was created.
      #
      #   @param file_url [String] A URL to download the app build as a .zip archive.
      #
      #   @param is_production [Boolean] Whether this build is the currently active production build for its platform.
      #
      #   @param platform [Symbol, WhopSDK::Models::AppBuildPlatforms] The target platform for this build.
      #
      #   @param review_message [String, nil] Feedback from the reviewer explaining why the build was rejected. Null if the bu
      #
      #   @param status [Symbol, WhopSDK::Models::AppBuildStatuses] The current review status of this build.
      #
      #   @param supported_app_view_types [Array<Symbol, WhopSDK::Models::AppViewType>] The list of view types this build supports, as declared by the developer.
    end
  end
end
