# frozen_string_literal: true

module WhopSDK
  module Models
    # @see WhopSDK::Resources::AppBuilds#create
    class AppBuildCreateParams < WhopSDK::Internal::Type::BaseModel
      extend WhopSDK::Internal::Type::RequestParameters::Converter
      include WhopSDK::Internal::Type::RequestParameters

      # @!attribute attachment
      #   Attachment input for the app build file. This should be an upload in .zip
      #   format. The zip should contain at least one main_js_bundle.hbc file and
      #   optionally an assets folder next to it.
      #
      #   @return [WhopSDK::Models::AppBuildCreateParams::Attachment::AttachmentInputWithDirectUploadID, WhopSDK::Models::AppBuildCreateParams::Attachment::AttachmentInputWithID]
      required :attachment, union: -> { WhopSDK::AppBuildCreateParams::Attachment }

      # @!attribute checksum
      #   Checksum of the app build file. This is generated by the client and used to
      #   verify the integrity of the file that is submitted when un-packaged later on a
      #   device.
      #
      #   @return [String]
      required :checksum, String

      # @!attribute platform
      #   The platform of the app build (ios, android, web)
      #
      #   @return [Symbol, WhopSDK::Models::AppBuildPlatforms]
      required :platform, enum: -> { WhopSDK::AppBuildPlatforms }

      # @!attribute ai_prompt_id
      #   The id of the ai prompt that created this build
      #
      #   @return [String, nil]
      optional :ai_prompt_id, String, nil?: true

      # @!attribute app_id
      #   The ID of the app to create a build for. By default the current app from the api
      #   key is used.
      #
      #   @return [String, nil]
      optional :app_id, String, nil?: true

      # @!attribute supported_app_view_types
      #   Supported app view types for the app build. A build can specify multiple view
      #   types, but should only specify ones that its code supports.
      #
      #   @return [Array<Symbol, WhopSDK::Models::AppViewType>, nil]
      optional :supported_app_view_types,
               -> { WhopSDK::Internal::Type::ArrayOf[enum: WhopSDK::AppViewType] },
               nil?: true

      # @!method initialize(attachment:, checksum:, platform:, ai_prompt_id: nil, app_id: nil, supported_app_view_types: nil, request_options: {})
      #   Some parameter documentations has been truncated, see
      #   {WhopSDK::Models::AppBuildCreateParams} for more details.
      #
      #   @param attachment [WhopSDK::Models::AppBuildCreateParams::Attachment::AttachmentInputWithDirectUploadID, WhopSDK::Models::AppBuildCreateParams::Attachment::AttachmentInputWithID] Attachment input for the app build file. This should be an upload in .zip format
      #
      #   @param checksum [String] Checksum of the app build file. This is generated by the client and used to veri
      #
      #   @param platform [Symbol, WhopSDK::Models::AppBuildPlatforms] The platform of the app build (ios, android, web)
      #
      #   @param ai_prompt_id [String, nil] The id of the ai prompt that created this build
      #
      #   @param app_id [String, nil] The ID of the app to create a build for. By default the current app from the api
      #
      #   @param supported_app_view_types [Array<Symbol, WhopSDK::Models::AppViewType>, nil] Supported app view types for the app build. A build can specify multiple view ty
      #
      #   @param request_options [WhopSDK::RequestOptions, Hash{Symbol=>Object}]

      # Attachment input for the app build file. This should be an upload in .zip
      # format. The zip should contain at least one main_js_bundle.hbc file and
      # optionally an assets folder next to it.
      module Attachment
        extend WhopSDK::Internal::Type::Union

        # Input for an attachment
        variant -> { WhopSDK::AppBuildCreateParams::Attachment::AttachmentInputWithDirectUploadID }

        # Input for an attachment
        variant -> { WhopSDK::AppBuildCreateParams::Attachment::AttachmentInputWithID }

        class AttachmentInputWithDirectUploadID < WhopSDK::Internal::Type::BaseModel
          # @!attribute direct_upload_id
          #   This ID should be used the first time you upload an attachment. It is the ID of
          #   the direct upload that was created when uploading the file to S3 via the
          #   mediaDirectUpload mutation.
          #
          #   @return [String]
          required :direct_upload_id, String

          # @!method initialize(direct_upload_id:)
          #   Some parameter documentations has been truncated, see
          #   {WhopSDK::Models::AppBuildCreateParams::Attachment::AttachmentInputWithDirectUploadID}
          #   for more details.
          #
          #   Input for an attachment
          #
          #   @param direct_upload_id [String] This ID should be used the first time you upload an attachment. It is the ID of
        end

        class AttachmentInputWithID < WhopSDK::Internal::Type::BaseModel
          # @!attribute id
          #   The ID of an existing attachment object. Use this when updating a resource and
          #   keeping a subset of the attachments. Don't use this unless you know what you're
          #   doing.
          #
          #   @return [String]
          required :id, String

          # @!method initialize(id:)
          #   Some parameter documentations has been truncated, see
          #   {WhopSDK::Models::AppBuildCreateParams::Attachment::AttachmentInputWithID} for
          #   more details.
          #
          #   Input for an attachment
          #
          #   @param id [String] The ID of an existing attachment object. Use this when updating a resource and k
        end

        # @!method self.variants
        #   @return [Array(WhopSDK::Models::AppBuildCreateParams::Attachment::AttachmentInputWithDirectUploadID, WhopSDK::Models::AppBuildCreateParams::Attachment::AttachmentInputWithID)]
      end
    end
  end
end
