# frozen_string_literal: true

module WhopSDK
  module Models
    # @see WhopSDK::Resources::AppBuilds#list
    class AppBuildListResponse < WhopSDK::Internal::Type::BaseModel
      # @!attribute id
      #   The unique identifier for the app build.
      #
      #   @return [String]
      required :id, String

      # @!attribute checksum
      #   This is generated by the client and used to verify the integrity of the file
      #   that is submitted. It is a SHA256 hash of the app build file.
      #
      #   @return [String]
      required :checksum, String

      # @!attribute created_at
      #   The datetime the app build was created.
      #
      #   @return [Time]
      required :created_at, Time

      # @!attribute file_url
      #   The URL to download the app build .zip file.
      #
      #   @return [String]
      required :file_url, String

      # @!attribute is_production
      #   Whether this app build is currently being used in production.
      #
      #   @return [Boolean]
      required :is_production, WhopSDK::Internal::Type::Boolean

      # @!attribute platform
      #   The platform of the app build (ios, android, web)
      #
      #   @return [Symbol, WhopSDK::Models::AppBuildPlatforms]
      required :platform, enum: -> { WhopSDK::AppBuildPlatforms }

      # @!attribute review_message
      #   The review message for the app build, if any. This is populated when the build
      #   is rejected and there is a reason specified by the reviewer.
      #
      #   @return [String, nil]
      required :review_message, String, nil?: true

      # @!attribute status
      #   The status of the app build (draft, approved, rejected, pending, etc)
      #
      #   @return [Symbol, WhopSDK::Models::AppBuildStatuses]
      required :status, enum: -> { WhopSDK::AppBuildStatuses }

      # @!attribute supported_app_view_types
      #   The supported app view types for the app build. These are the views that the
      #   developer has specified that this build supports.
      #
      #   @return [Array<Symbol, WhopSDK::Models::AppViewType>]
      required :supported_app_view_types, -> { WhopSDK::Internal::Type::ArrayOf[enum: WhopSDK::AppViewType] }

      # @!method initialize(id:, checksum:, created_at:, file_url:, is_production:, platform:, review_message:, status:, supported_app_view_types:)
      #   Some parameter documentations has been truncated, see
      #   {WhopSDK::Models::AppBuildListResponse} for more details.
      #
      #   An App Build object representing a build of an application
      #
      #   @param id [String] The unique identifier for the app build.
      #
      #   @param checksum [String] This is generated by the client and used to verify the integrity of the file tha
      #
      #   @param created_at [Time] The datetime the app build was created.
      #
      #   @param file_url [String] The URL to download the app build .zip file.
      #
      #   @param is_production [Boolean] Whether this app build is currently being used in production.
      #
      #   @param platform [Symbol, WhopSDK::Models::AppBuildPlatforms] The platform of the app build (ios, android, web)
      #
      #   @param review_message [String, nil] The review message for the app build, if any. This is populated when the build i
      #
      #   @param status [Symbol, WhopSDK::Models::AppBuildStatuses] The status of the app build (draft, approved, rejected, pending, etc)
      #
      #   @param supported_app_view_types [Array<Symbol, WhopSDK::Models::AppViewType>] The supported app view types for the app build. These are the views that the dev
    end
  end
end
