# frozen_string_literal: true

module WhopSDK
  module Models
    # @see WhopSDK::Resources::Invoices#create
    class InvoiceCreateResponse < WhopSDK::Internal::Type::BaseModel
      # @!attribute checkout_job_id
      #   The ID of the checkout job that was created for this invoice.
      #
      #   @return [String, nil]
      required :checkout_job_id, String, nil?: true

      # @!attribute invoice
      #   The invoice that was created for this invoice.
      #
      #   @return [WhopSDK::Models::Invoice]
      required :invoice, -> { WhopSDK::Invoice }

      # @!method initialize(checkout_job_id:, invoice:)
      #   Autogenerated return type of CreateInvoice.
      #
      #   @param checkout_job_id [String, nil] The ID of the checkout job that was created for this invoice.
      #
      #   @param invoice [WhopSDK::Models::Invoice] The invoice that was created for this invoice.
    end
  end
end
