# frozen_string_literal: true

module WhopSDK
  module Models
    # The different event types available
    module WebhookEvent
      extend WhopSDK::Internal::Type::Enum

      INVOICE_CREATED = :"invoice.created"
      INVOICE_MARKED_UNCOLLECTIBLE = :"invoice.marked_uncollectible"
      INVOICE_PAID = :"invoice.paid"
      INVOICE_PAST_DUE = :"invoice.past_due"
      INVOICE_VOIDED = :"invoice.voided"
      MEMBERSHIP_ACTIVATED = :"membership.activated"
      MEMBERSHIP_DEACTIVATED = :"membership.deactivated"
      MEMBERSHIP_TRIAL_ENDING_SOON = :"membership.trial_ending_soon"
      ENTRY_CREATED = :"entry.created"
      ENTRY_APPROVED = :"entry.approved"
      ENTRY_DENIED = :"entry.denied"
      ENTRY_DELETED = :"entry.deleted"
      EXPORT_COMPLETED = :"export.completed"
      EXPORT_FAILED = :"export.failed"
      SETUP_INTENT_REQUIRES_ACTION = :"setup_intent.requires_action"
      SETUP_INTENT_SUCCEEDED = :"setup_intent.succeeded"
      SETUP_INTENT_CANCELED = :"setup_intent.canceled"
      LEDGER_ACCOUNT_FUNDS_AVAILABLE = :"ledger_account.funds_available"
      SWAP_COMPLETED = :"swap.completed"
      DEPOSIT_SUCCEEDED = :"deposit.succeeded"
      TRANSFER_CREATED = :"transfer.created"
      TRANSFER_COMPLETED = :"transfer.completed"
      WITHDRAWAL_CREATED = :"withdrawal.created"
      WITHDRAWAL_UPDATED = :"withdrawal.updated"
      CARD_TRANSACTION_CREATED = :"card_transaction.created"
      CARD_TRANSACTION_UPDATED = :"card_transaction.updated"
      CARD_TRANSACTION_COMPLETED = :"card_transaction.completed"
      CARD_TRANSACTION_DECLINED = :"card_transaction.declined"
      CARD_TRANSACTION_REVERSED = :"card_transaction.reversed"
      CARD_CREATED = :"card.created"
      CARD_UPDATED = :"card.updated"
      CARD_FROZEN = :"card.frozen"
      CARD_CANCELED = :"card.canceled"
      CARD_APPLICATION_CREATED = :"card_application.created"
      CARD_APPLICATION_UPDATED = :"card_application.updated"
      CARD_APPLICATION_APPROVED = :"card_application.approved"
      CARD_APPLICATION_DENIED = :"card_application.denied"
      COURSE_LESSON_INTERACTION_COMPLETED = :"course_lesson_interaction.completed"
      PAYOUT_METHOD_CREATED = :"payout_method.created"
      VERIFICATION_SUCCEEDED = :"verification.succeeded"
      IDENTITY_PROFILE_APPROVED = :"identity_profile.approved"
      IDENTITY_PROFILE_REJECTED = :"identity_profile.rejected"
      IDENTITY_PROFILE_NEEDS_ACTION = :"identity_profile.needs_action"
      IDENTITY_PROFILE_UPDATED = :"identity_profile.updated"
      PAYOUT_ACCOUNT_STATUS_UPDATED = :"payout_account.status_updated"
      RESOLUTION_CENTER_CASE_CREATED = :"resolution_center_case.created"
      RESOLUTION_CENTER_CASE_UPDATED = :"resolution_center_case.updated"
      RESOLUTION_CENTER_CASE_DECIDED = :"resolution_center_case.decided"
      PRODUCT_CREATED = :"product.created"
      PRODUCT_UPDATED = :"product.updated"
      PRODUCT_DELETED = :"product.deleted"
      PRODUCT_PUBLISHED = :"product.published"
      PRODUCT_UNPUBLISHED = :"product.unpublished"
      PLAN_CREATED = :"plan.created"
      PLAN_UPDATED = :"plan.updated"
      PLAN_DELETED = :"plan.deleted"
      SHIPMENT_CREATED = :"shipment.created"
      SHIPMENT_UPDATED = :"shipment.updated"
      MEMBER_CREATED = :"member.created"
      AD_CAMPAIGN_PAYMENT_FAILED = :"ad_campaign.payment_failed"
      CHAT_MESSAGE_CREATED = :"chat.message.created"
      CHAT_REACTION_CREATED = :"chat.reaction.created"
      PAYMENT_CREATED = :"payment.created"
      PAYMENT_SUCCEEDED = :"payment.succeeded"
      PAYMENT_FAILED = :"payment.failed"
      PAYMENT_PENDING = :"payment.pending"
      DISPUTE_CREATED = :"dispute.created"
      DISPUTE_UPDATED = :"dispute.updated"
      REFUND_CREATED = :"refund.created"
      REFUND_UPDATED = :"refund.updated"
      DISPUTE_ALERT_CREATED = :"dispute_alert.created"
      MEMBERSHIP_CANCEL_AT_PERIOD_END_CHANGED = :"membership.cancel_at_period_end_changed"

      # @!method self.values
      #   @return [Array<Symbol>]
    end
  end
end
