module WhopSDK
  module Models
    module Payouts
      type method_list_params =
        {
          account_id: String,
          after: String,
          amount: Float,
          before: String,
          currency: String,
          first: Integer,
          include_available: bool,
          last: Integer,
          status: WhopSDK::Models::Payouts::MethodListParams::status,
          user_id: String
        }
        & WhopSDK::Internal::Type::request_parameters

      class MethodListParams < WhopSDK::Internal::Type::BaseModel
        extend WhopSDK::Internal::Type::RequestParameters::Converter
        include WhopSDK::Internal::Type::RequestParameters

        attr_reader account_id: String?

        def account_id=: (String) -> String

        attr_reader after: String?

        def after=: (String) -> String

        attr_reader amount: Float?

        def amount=: (Float) -> Float

        attr_reader before: String?

        def before=: (String) -> String

        attr_reader currency: String?

        def currency=: (String) -> String

        attr_reader first: Integer?

        def first=: (Integer) -> Integer

        attr_reader include_available: bool?

        def include_available=: (bool) -> bool

        attr_reader last: Integer?

        def last=: (Integer) -> Integer

        attr_reader status: WhopSDK::Models::Payouts::MethodListParams::status?

        def status=: (
          WhopSDK::Models::Payouts::MethodListParams::status
        ) -> WhopSDK::Models::Payouts::MethodListParams::status

        attr_reader user_id: String?

        def user_id=: (String) -> String

        def initialize: (
          ?account_id: String,
          ?after: String,
          ?amount: Float,
          ?before: String,
          ?currency: String,
          ?first: Integer,
          ?include_available: bool,
          ?last: Integer,
          ?status: WhopSDK::Models::Payouts::MethodListParams::status,
          ?user_id: String,
          ?request_options: WhopSDK::request_opts
        ) -> void

        def to_hash: -> {
          account_id: String,
          after: String,
          amount: Float,
          before: String,
          currency: String,
          first: Integer,
          include_available: bool,
          last: Integer,
          status: WhopSDK::Models::Payouts::MethodListParams::status,
          user_id: String,
          request_options: WhopSDK::RequestOptions
        }

        type status = :created | :active | :broken

        module Status
          extend WhopSDK::Internal::Type::Enum

          CREATED: :created
          ACTIVE: :active
          BROKEN: :broken

          def self?.values: -> ::Array[WhopSDK::Models::Payouts::MethodListParams::status]
        end
      end
    end
  end
end
