# typed: strong

module Whopsdk
  module Models
    class InvoiceCreateResponse < Whopsdk::Internal::Type::BaseModel
      OrHash =
        T.type_alias do
          T.any(
            Whopsdk::Models::InvoiceCreateResponse,
            Whopsdk::Internal::AnyHash
          )
        end

      # The ID of the checkout job that was created for this invoice.
      sig { returns(T.nilable(String)) }
      attr_accessor :checkout_job_id

      # A statement that defines an amount due by a customer.
      sig { returns(T.nilable(Whopsdk::Invoice)) }
      attr_reader :invoice

      sig { params(invoice: T.nilable(Whopsdk::Invoice::OrHash)).void }
      attr_writer :invoice

      # Autogenerated return type of CreateInvoice.
      sig do
        params(
          checkout_job_id: T.nilable(String),
          invoice: T.nilable(Whopsdk::Invoice::OrHash)
        ).returns(T.attached_class)
      end
      def self.new(
        # The ID of the checkout job that was created for this invoice.
        checkout_job_id:,
        # A statement that defines an amount due by a customer.
        invoice:
      )
      end

      sig do
        override.returns(
          {
            checkout_job_id: T.nilable(String),
            invoice: T.nilable(Whopsdk::Invoice)
          }
        )
      end
      def to_hash
      end
    end
  end
end
