module WhopSDK
  module Resources
    class Accounts
      class Preferences
        def retrieve: (
          String account_id,
          ?request_options: WhopSDK::request_opts
        ) -> WhopSDK::Models::Accounts::PreferenceRetrieveResponse

        def update: (
          String account_id,
          ?ads_payment_methods: WhopSDK::Accounts::PreferenceUpdateParams::AdsPaymentMethods,
          ?request_options: WhopSDK::request_opts
        ) -> WhopSDK::Models::Accounts::PreferenceUpdateResponse

        def initialize: (client: WhopSDK::Client) -> void
      end
    end
  end
end
