# typed: strong

module WhopSDK
  module Models
    class AppBuildListResponse < WhopSDK::Internal::Type::BaseModel
      OrHash =
        T.type_alias do
          T.any(
            WhopSDK::Models::AppBuildListResponse,
            WhopSDK::Internal::AnyHash
          )
        end

      # The unique identifier for the app build.
      sig { returns(String) }
      attr_accessor :id

      # A SHA-256 hash of the uploaded build file, generated by the client and used to
      # verify file integrity.
      sig { returns(String) }
      attr_accessor :checksum

      # The datetime the app build was created.
      sig { returns(Time) }
      attr_accessor :created_at

      # A URL to download the app build as a .zip archive.
      sig { returns(String) }
      attr_accessor :file_url

      # Whether this build is the currently active production build for its platform.
      sig { returns(T::Boolean) }
      attr_accessor :is_production

      # The target platform for this build.
      sig { returns(WhopSDK::AppBuildPlatforms::TaggedSymbol) }
      attr_accessor :platform

      # Feedback from the reviewer explaining why the build was rejected. Null if the
      # build has not been reviewed or was approved.
      sig { returns(T.nilable(String)) }
      attr_accessor :review_message

      # The current review status of this build.
      sig { returns(WhopSDK::AppBuildStatuses::TaggedSymbol) }
      attr_accessor :status

      # The list of view types this build supports, as declared by the developer.
      sig { returns(T::Array[WhopSDK::AppViewType::TaggedSymbol]) }
      attr_accessor :supported_app_view_types

      # A versioned build artifact for a Whop React Native App, submitted for review and
      # deployment to a specific platform.
      sig do
        params(
          id: String,
          checksum: String,
          created_at: Time,
          file_url: String,
          is_production: T::Boolean,
          platform: WhopSDK::AppBuildPlatforms::OrSymbol,
          review_message: T.nilable(String),
          status: WhopSDK::AppBuildStatuses::OrSymbol,
          supported_app_view_types: T::Array[WhopSDK::AppViewType::OrSymbol]
        ).returns(T.attached_class)
      end
      def self.new(
        # The unique identifier for the app build.
        id:,
        # A SHA-256 hash of the uploaded build file, generated by the client and used to
        # verify file integrity.
        checksum:,
        # The datetime the app build was created.
        created_at:,
        # A URL to download the app build as a .zip archive.
        file_url:,
        # Whether this build is the currently active production build for its platform.
        is_production:,
        # The target platform for this build.
        platform:,
        # Feedback from the reviewer explaining why the build was rejected. Null if the
        # build has not been reviewed or was approved.
        review_message:,
        # The current review status of this build.
        status:,
        # The list of view types this build supports, as declared by the developer.
        supported_app_view_types:
      )
      end

      sig do
        override.returns(
          {
            id: String,
            checksum: String,
            created_at: Time,
            file_url: String,
            is_production: T::Boolean,
            platform: WhopSDK::AppBuildPlatforms::TaggedSymbol,
            review_message: T.nilable(String),
            status: WhopSDK::AppBuildStatuses::TaggedSymbol,
            supported_app_view_types:
              T::Array[WhopSDK::AppViewType::TaggedSymbol]
          }
        )
      end
      def to_hash
      end
    end
  end
end
