# typed: strong

module WhopSDK
  module Models
    class CompanyTokenTransactionCreateParams < WhopSDK::Internal::Type::BaseModel
      extend WhopSDK::Internal::Type::RequestParameters::Converter
      include WhopSDK::Internal::Type::RequestParameters

      OrHash =
        T.type_alias do
          T.any(
            WhopSDK::CompanyTokenTransactionCreateParams,
            WhopSDK::Internal::AnyHash
          )
        end

      # Parameters for CreateCompanyTokenTransaction
      sig do
        returns(
          T.any(
            WhopSDK::CompanyTokenTransactionCreateParams::Body::CreateCompanyTokenTransactionInputTransactionTypeTransfer,
            WhopSDK::CompanyTokenTransactionCreateParams::Body::CreateCompanyTokenTransactionInputTransactionTypeAdd,
            WhopSDK::CompanyTokenTransactionCreateParams::Body::CreateCompanyTokenTransactionInputTransactionTypeSubtract
          )
        )
      end
      attr_accessor :body

      sig do
        params(
          body:
            T.any(
              WhopSDK::CompanyTokenTransactionCreateParams::Body::CreateCompanyTokenTransactionInputTransactionTypeTransfer::OrHash,
              WhopSDK::CompanyTokenTransactionCreateParams::Body::CreateCompanyTokenTransactionInputTransactionTypeAdd::OrHash,
              WhopSDK::CompanyTokenTransactionCreateParams::Body::CreateCompanyTokenTransactionInputTransactionTypeSubtract::OrHash
            ),
          request_options: WhopSDK::RequestOptions::OrHash
        ).returns(T.attached_class)
      end
      def self.new(
        # Parameters for CreateCompanyTokenTransaction
        body:,
        request_options: {}
      )
      end

      sig do
        override.returns(
          {
            body:
              T.any(
                WhopSDK::CompanyTokenTransactionCreateParams::Body::CreateCompanyTokenTransactionInputTransactionTypeTransfer,
                WhopSDK::CompanyTokenTransactionCreateParams::Body::CreateCompanyTokenTransactionInputTransactionTypeAdd,
                WhopSDK::CompanyTokenTransactionCreateParams::Body::CreateCompanyTokenTransactionInputTransactionTypeSubtract
              ),
            request_options: WhopSDK::RequestOptions
          }
        )
      end
      def to_hash
      end

      # Parameters for CreateCompanyTokenTransaction
      module Body
        extend WhopSDK::Internal::Type::Union

        Variants =
          T.type_alias do
            T.any(
              WhopSDK::CompanyTokenTransactionCreateParams::Body::CreateCompanyTokenTransactionInputTransactionTypeTransfer,
              WhopSDK::CompanyTokenTransactionCreateParams::Body::CreateCompanyTokenTransactionInputTransactionTypeAdd,
              WhopSDK::CompanyTokenTransactionCreateParams::Body::CreateCompanyTokenTransactionInputTransactionTypeSubtract
            )
          end

        class CreateCompanyTokenTransactionInputTransactionTypeTransfer < WhopSDK::Internal::Type::BaseModel
          OrHash =
            T.type_alias do
              T.any(
                WhopSDK::CompanyTokenTransactionCreateParams::Body::CreateCompanyTokenTransactionInputTransactionTypeTransfer,
                WhopSDK::Internal::AnyHash
              )
            end

          # The unique identifier of the company to create the transaction in, starting with
          # 'biz\_'.
          sig { returns(String) }
          attr_accessor :account_id

          # The positive number of tokens to transact. For example, 100.0 for 100 tokens.
          sig { returns(Float) }
          attr_accessor :amount

          # The unique identifier of the user receiving the tokens. Required when the
          # transaction type is 'transfer'.
          sig { returns(String) }
          attr_accessor :destination_user_id

          sig { returns(Symbol) }
          attr_accessor :transaction_type

          # The unique identifier of the user whose token balance will be affected, starting
          # with 'user\_'.
          sig { returns(String) }
          attr_accessor :user_id

          # A human-readable description of why the transaction was created.
          sig { returns(T.nilable(String)) }
          attr_accessor :description

          # A unique key to prevent duplicate transactions. Use a UUID or similar unique
          # string.
          sig { returns(T.nilable(String)) }
          attr_accessor :idempotency_key

          # Autogenerated input type of CreateCompanyTokenTransaction
          sig do
            params(
              account_id: String,
              amount: Float,
              destination_user_id: String,
              user_id: String,
              description: T.nilable(String),
              idempotency_key: T.nilable(String),
              transaction_type: Symbol
            ).returns(T.attached_class)
          end
          def self.new(
            # The unique identifier of the company to create the transaction in, starting with
            # 'biz\_'.
            account_id:,
            # The positive number of tokens to transact. For example, 100.0 for 100 tokens.
            amount:,
            # The unique identifier of the user receiving the tokens. Required when the
            # transaction type is 'transfer'.
            destination_user_id:,
            # The unique identifier of the user whose token balance will be affected, starting
            # with 'user\_'.
            user_id:,
            # A human-readable description of why the transaction was created.
            description: nil,
            # A unique key to prevent duplicate transactions. Use a UUID or similar unique
            # string.
            idempotency_key: nil,
            transaction_type: :transfer
          )
          end

          sig do
            override.returns(
              {
                account_id: String,
                amount: Float,
                destination_user_id: String,
                transaction_type: Symbol,
                user_id: String,
                description: T.nilable(String),
                idempotency_key: T.nilable(String)
              }
            )
          end
          def to_hash
          end
        end

        class CreateCompanyTokenTransactionInputTransactionTypeAdd < WhopSDK::Internal::Type::BaseModel
          OrHash =
            T.type_alias do
              T.any(
                WhopSDK::CompanyTokenTransactionCreateParams::Body::CreateCompanyTokenTransactionInputTransactionTypeAdd,
                WhopSDK::Internal::AnyHash
              )
            end

          # The unique identifier of the company to create the transaction in, starting with
          # 'biz\_'.
          sig { returns(String) }
          attr_accessor :account_id

          # The positive number of tokens to transact. For example, 100.0 for 100 tokens.
          sig { returns(Float) }
          attr_accessor :amount

          sig { returns(Symbol) }
          attr_accessor :transaction_type

          # The unique identifier of the user whose token balance will be affected, starting
          # with 'user\_'.
          sig { returns(String) }
          attr_accessor :user_id

          # A human-readable description of why the transaction was created.
          sig { returns(T.nilable(String)) }
          attr_accessor :description

          # A unique key to prevent duplicate transactions. Use a UUID or similar unique
          # string.
          sig { returns(T.nilable(String)) }
          attr_accessor :idempotency_key

          # Autogenerated input type of CreateCompanyTokenTransaction
          sig do
            params(
              account_id: String,
              amount: Float,
              user_id: String,
              description: T.nilable(String),
              idempotency_key: T.nilable(String),
              transaction_type: Symbol
            ).returns(T.attached_class)
          end
          def self.new(
            # The unique identifier of the company to create the transaction in, starting with
            # 'biz\_'.
            account_id:,
            # The positive number of tokens to transact. For example, 100.0 for 100 tokens.
            amount:,
            # The unique identifier of the user whose token balance will be affected, starting
            # with 'user\_'.
            user_id:,
            # A human-readable description of why the transaction was created.
            description: nil,
            # A unique key to prevent duplicate transactions. Use a UUID or similar unique
            # string.
            idempotency_key: nil,
            transaction_type: :add
          )
          end

          sig do
            override.returns(
              {
                account_id: String,
                amount: Float,
                transaction_type: Symbol,
                user_id: String,
                description: T.nilable(String),
                idempotency_key: T.nilable(String)
              }
            )
          end
          def to_hash
          end
        end

        class CreateCompanyTokenTransactionInputTransactionTypeSubtract < WhopSDK::Internal::Type::BaseModel
          OrHash =
            T.type_alias do
              T.any(
                WhopSDK::CompanyTokenTransactionCreateParams::Body::CreateCompanyTokenTransactionInputTransactionTypeSubtract,
                WhopSDK::Internal::AnyHash
              )
            end

          # The unique identifier of the company to create the transaction in, starting with
          # 'biz\_'.
          sig { returns(String) }
          attr_accessor :account_id

          # The positive number of tokens to transact. For example, 100.0 for 100 tokens.
          sig { returns(Float) }
          attr_accessor :amount

          sig { returns(Symbol) }
          attr_accessor :transaction_type

          # The unique identifier of the user whose token balance will be affected, starting
          # with 'user\_'.
          sig { returns(String) }
          attr_accessor :user_id

          # A human-readable description of why the transaction was created.
          sig { returns(T.nilable(String)) }
          attr_accessor :description

          # A unique key to prevent duplicate transactions. Use a UUID or similar unique
          # string.
          sig { returns(T.nilable(String)) }
          attr_accessor :idempotency_key

          # Autogenerated input type of CreateCompanyTokenTransaction
          sig do
            params(
              account_id: String,
              amount: Float,
              user_id: String,
              description: T.nilable(String),
              idempotency_key: T.nilable(String),
              transaction_type: Symbol
            ).returns(T.attached_class)
          end
          def self.new(
            # The unique identifier of the company to create the transaction in, starting with
            # 'biz\_'.
            account_id:,
            # The positive number of tokens to transact. For example, 100.0 for 100 tokens.
            amount:,
            # The unique identifier of the user whose token balance will be affected, starting
            # with 'user\_'.
            user_id:,
            # A human-readable description of why the transaction was created.
            description: nil,
            # A unique key to prevent duplicate transactions. Use a UUID or similar unique
            # string.
            idempotency_key: nil,
            transaction_type: :subtract
          )
          end

          sig do
            override.returns(
              {
                account_id: String,
                amount: Float,
                transaction_type: Symbol,
                user_id: String,
                description: T.nilable(String),
                idempotency_key: T.nilable(String)
              }
            )
          end
          def to_hash
          end
        end

        sig do
          override.returns(
            T::Array[
              WhopSDK::CompanyTokenTransactionCreateParams::Body::Variants
            ]
          )
        end
        def self.variants
        end
      end
    end
  end
end
