# typed: strong

module WhopSDK
  module Models
    # The available currencies on the platform
    module Currency
      extend WhopSDK::Internal::Type::Enum

      TaggedSymbol = T.type_alias { T.all(Symbol, WhopSDK::Currency) }
      OrSymbol = T.type_alias { T.any(Symbol, String) }

      USD = T.let(:usd, WhopSDK::Currency::TaggedSymbol)
      SGD = T.let(:sgd, WhopSDK::Currency::TaggedSymbol)
      INR = T.let(:inr, WhopSDK::Currency::TaggedSymbol)
      AUD = T.let(:aud, WhopSDK::Currency::TaggedSymbol)
      BRL = T.let(:brl, WhopSDK::Currency::TaggedSymbol)
      CAD = T.let(:cad, WhopSDK::Currency::TaggedSymbol)
      DKK = T.let(:dkk, WhopSDK::Currency::TaggedSymbol)
      EUR = T.let(:eur, WhopSDK::Currency::TaggedSymbol)
      NOK = T.let(:nok, WhopSDK::Currency::TaggedSymbol)
      GBP = T.let(:gbp, WhopSDK::Currency::TaggedSymbol)
      SEK = T.let(:sek, WhopSDK::Currency::TaggedSymbol)
      CHF = T.let(:chf, WhopSDK::Currency::TaggedSymbol)
      HKD = T.let(:hkd, WhopSDK::Currency::TaggedSymbol)
      HUF = T.let(:huf, WhopSDK::Currency::TaggedSymbol)
      JPY = T.let(:jpy, WhopSDK::Currency::TaggedSymbol)
      MXN = T.let(:mxn, WhopSDK::Currency::TaggedSymbol)
      MYR = T.let(:myr, WhopSDK::Currency::TaggedSymbol)
      PLN = T.let(:pln, WhopSDK::Currency::TaggedSymbol)
      CZK = T.let(:czk, WhopSDK::Currency::TaggedSymbol)
      NZD = T.let(:nzd, WhopSDK::Currency::TaggedSymbol)
      AED = T.let(:aed, WhopSDK::Currency::TaggedSymbol)
      ETH = T.let(:eth, WhopSDK::Currency::TaggedSymbol)
      APE = T.let(:ape, WhopSDK::Currency::TaggedSymbol)
      COP = T.let(:cop, WhopSDK::Currency::TaggedSymbol)
      RON = T.let(:ron, WhopSDK::Currency::TaggedSymbol)
      THB = T.let(:thb, WhopSDK::Currency::TaggedSymbol)
      BGN = T.let(:bgn, WhopSDK::Currency::TaggedSymbol)
      IDR = T.let(:idr, WhopSDK::Currency::TaggedSymbol)
      DOP = T.let(:dop, WhopSDK::Currency::TaggedSymbol)
      PHP = T.let(:php, WhopSDK::Currency::TaggedSymbol)
      TRY = T.let(:try, WhopSDK::Currency::TaggedSymbol)
      KRW = T.let(:krw, WhopSDK::Currency::TaggedSymbol)
      TWD = T.let(:twd, WhopSDK::Currency::TaggedSymbol)
      VND = T.let(:vnd, WhopSDK::Currency::TaggedSymbol)
      PKR = T.let(:pkr, WhopSDK::Currency::TaggedSymbol)
      CLP = T.let(:clp, WhopSDK::Currency::TaggedSymbol)
      UYU = T.let(:uyu, WhopSDK::Currency::TaggedSymbol)
      ARS = T.let(:ars, WhopSDK::Currency::TaggedSymbol)
      ZAR = T.let(:zar, WhopSDK::Currency::TaggedSymbol)
      DZD = T.let(:dzd, WhopSDK::Currency::TaggedSymbol)
      TND = T.let(:tnd, WhopSDK::Currency::TaggedSymbol)
      MAD = T.let(:mad, WhopSDK::Currency::TaggedSymbol)
      KES = T.let(:kes, WhopSDK::Currency::TaggedSymbol)
      KWD = T.let(:kwd, WhopSDK::Currency::TaggedSymbol)
      JOD = T.let(:jod, WhopSDK::Currency::TaggedSymbol)
      ALL = T.let(:all, WhopSDK::Currency::TaggedSymbol)
      XCD = T.let(:xcd, WhopSDK::Currency::TaggedSymbol)
      AMD = T.let(:amd, WhopSDK::Currency::TaggedSymbol)
      BSD = T.let(:bsd, WhopSDK::Currency::TaggedSymbol)
      BHD = T.let(:bhd, WhopSDK::Currency::TaggedSymbol)
      BOB = T.let(:bob, WhopSDK::Currency::TaggedSymbol)
      BAM = T.let(:bam, WhopSDK::Currency::TaggedSymbol)
      KHR = T.let(:khr, WhopSDK::Currency::TaggedSymbol)
      CRC = T.let(:crc, WhopSDK::Currency::TaggedSymbol)
      XOF = T.let(:xof, WhopSDK::Currency::TaggedSymbol)
      EGP = T.let(:egp, WhopSDK::Currency::TaggedSymbol)
      ETB = T.let(:etb, WhopSDK::Currency::TaggedSymbol)
      GMD = T.let(:gmd, WhopSDK::Currency::TaggedSymbol)
      GHS = T.let(:ghs, WhopSDK::Currency::TaggedSymbol)
      GTQ = T.let(:gtq, WhopSDK::Currency::TaggedSymbol)
      GYD = T.let(:gyd, WhopSDK::Currency::TaggedSymbol)
      ILS = T.let(:ils, WhopSDK::Currency::TaggedSymbol)
      JMD = T.let(:jmd, WhopSDK::Currency::TaggedSymbol)
      MOP = T.let(:mop, WhopSDK::Currency::TaggedSymbol)
      MGA = T.let(:mga, WhopSDK::Currency::TaggedSymbol)
      MUR = T.let(:mur, WhopSDK::Currency::TaggedSymbol)
      MDL = T.let(:mdl, WhopSDK::Currency::TaggedSymbol)
      MNT = T.let(:mnt, WhopSDK::Currency::TaggedSymbol)
      NAD = T.let(:nad, WhopSDK::Currency::TaggedSymbol)
      NGN = T.let(:ngn, WhopSDK::Currency::TaggedSymbol)
      MKD = T.let(:mkd, WhopSDK::Currency::TaggedSymbol)
      OMR = T.let(:omr, WhopSDK::Currency::TaggedSymbol)
      PYG = T.let(:pyg, WhopSDK::Currency::TaggedSymbol)
      PEN = T.let(:pen, WhopSDK::Currency::TaggedSymbol)
      QAR = T.let(:qar, WhopSDK::Currency::TaggedSymbol)
      RWF = T.let(:rwf, WhopSDK::Currency::TaggedSymbol)
      SAR = T.let(:sar, WhopSDK::Currency::TaggedSymbol)
      RSD = T.let(:rsd, WhopSDK::Currency::TaggedSymbol)
      LKR = T.let(:lkr, WhopSDK::Currency::TaggedSymbol)
      TZS = T.let(:tzs, WhopSDK::Currency::TaggedSymbol)
      TTD = T.let(:ttd, WhopSDK::Currency::TaggedSymbol)
      UZS = T.let(:uzs, WhopSDK::Currency::TaggedSymbol)
      RUB = T.let(:rub, WhopSDK::Currency::TaggedSymbol)
      BTC = T.let(:btc, WhopSDK::Currency::TaggedSymbol)
      CNY = T.let(:cny, WhopSDK::Currency::TaggedSymbol)
      USDT = T.let(:usdt, WhopSDK::Currency::TaggedSymbol)

      sig { override.returns(T::Array[WhopSDK::Currency::TaggedSymbol]) }
      def self.values
      end
    end
  end
end
