# typed: strong

module WhopSDK
  module Models
    # The type of tax identifier
    module TaxIdentifierType
      extend WhopSDK::Internal::Type::Enum

      TaggedSymbol = T.type_alias { T.all(Symbol, WhopSDK::TaxIdentifierType) }
      OrSymbol = T.type_alias { T.any(Symbol, String) }

      AD_NRT = T.let(:ad_nrt, WhopSDK::TaxIdentifierType::TaggedSymbol)
      AO_TIN = T.let(:ao_tin, WhopSDK::TaxIdentifierType::TaggedSymbol)
      AR_CUIT = T.let(:ar_cuit, WhopSDK::TaxIdentifierType::TaggedSymbol)
      AM_TIN = T.let(:am_tin, WhopSDK::TaxIdentifierType::TaggedSymbol)
      AW_TIN = T.let(:aw_tin, WhopSDK::TaxIdentifierType::TaggedSymbol)
      AU_ABN = T.let(:au_abn, WhopSDK::TaxIdentifierType::TaggedSymbol)
      AU_ARN = T.let(:au_arn, WhopSDK::TaxIdentifierType::TaggedSymbol)
      EU_VAT = T.let(:eu_vat, WhopSDK::TaxIdentifierType::TaggedSymbol)
      AZ_TIN = T.let(:az_tin, WhopSDK::TaxIdentifierType::TaggedSymbol)
      BS_TIN = T.let(:bs_tin, WhopSDK::TaxIdentifierType::TaggedSymbol)
      BH_VAT = T.let(:bh_vat, WhopSDK::TaxIdentifierType::TaggedSymbol)
      BD_BIN = T.let(:bd_bin, WhopSDK::TaxIdentifierType::TaggedSymbol)
      BB_TIN = T.let(:bb_tin, WhopSDK::TaxIdentifierType::TaggedSymbol)
      BY_TIN = T.let(:by_tin, WhopSDK::TaxIdentifierType::TaggedSymbol)
      BJ_IFU = T.let(:bj_ifu, WhopSDK::TaxIdentifierType::TaggedSymbol)
      BO_TIN = T.let(:bo_tin, WhopSDK::TaxIdentifierType::TaggedSymbol)
      BA_TIN = T.let(:ba_tin, WhopSDK::TaxIdentifierType::TaggedSymbol)
      BR_CNPJ = T.let(:br_cnpj, WhopSDK::TaxIdentifierType::TaggedSymbol)
      BR_CPF = T.let(:br_cpf, WhopSDK::TaxIdentifierType::TaggedSymbol)
      BG_UIC = T.let(:bg_uic, WhopSDK::TaxIdentifierType::TaggedSymbol)
      BF_IFU = T.let(:bf_ifu, WhopSDK::TaxIdentifierType::TaggedSymbol)
      KH_TIN = T.let(:kh_tin, WhopSDK::TaxIdentifierType::TaggedSymbol)
      CM_NIU = T.let(:cm_niu, WhopSDK::TaxIdentifierType::TaggedSymbol)
      CA_BN = T.let(:ca_bn, WhopSDK::TaxIdentifierType::TaggedSymbol)
      CA_GST_HST = T.let(:ca_gst_hst, WhopSDK::TaxIdentifierType::TaggedSymbol)
      CA_PST_BC = T.let(:ca_pst_bc, WhopSDK::TaxIdentifierType::TaggedSymbol)
      CA_PST_MB = T.let(:ca_pst_mb, WhopSDK::TaxIdentifierType::TaggedSymbol)
      CA_PST_SK = T.let(:ca_pst_sk, WhopSDK::TaxIdentifierType::TaggedSymbol)
      CA_QST = T.let(:ca_qst, WhopSDK::TaxIdentifierType::TaggedSymbol)
      CV_NIF = T.let(:cv_nif, WhopSDK::TaxIdentifierType::TaggedSymbol)
      CL_TIN = T.let(:cl_tin, WhopSDK::TaxIdentifierType::TaggedSymbol)
      CN_TIN = T.let(:cn_tin, WhopSDK::TaxIdentifierType::TaggedSymbol)
      CO_NIT = T.let(:co_nit, WhopSDK::TaxIdentifierType::TaggedSymbol)
      CD_NIF = T.let(:cd_nif, WhopSDK::TaxIdentifierType::TaggedSymbol)
      CR_TIN = T.let(:cr_tin, WhopSDK::TaxIdentifierType::TaggedSymbol)
      HR_OIB = T.let(:hr_oib, WhopSDK::TaxIdentifierType::TaggedSymbol)
      DO_RCN = T.let(:do_rcn, WhopSDK::TaxIdentifierType::TaggedSymbol)
      EC_RUC = T.let(:ec_ruc, WhopSDK::TaxIdentifierType::TaggedSymbol)
      EG_TIN = T.let(:eg_tin, WhopSDK::TaxIdentifierType::TaggedSymbol)
      SV_NIT = T.let(:sv_nit, WhopSDK::TaxIdentifierType::TaggedSymbol)
      ET_TIN = T.let(:et_tin, WhopSDK::TaxIdentifierType::TaggedSymbol)
      EU_OSS_VAT = T.let(:eu_oss_vat, WhopSDK::TaxIdentifierType::TaggedSymbol)
      GE_VAT = T.let(:ge_vat, WhopSDK::TaxIdentifierType::TaggedSymbol)
      DE_STN = T.let(:de_stn, WhopSDK::TaxIdentifierType::TaggedSymbol)
      GB_VAT = T.let(:gb_vat, WhopSDK::TaxIdentifierType::TaggedSymbol)
      GN_NIF = T.let(:gn_nif, WhopSDK::TaxIdentifierType::TaggedSymbol)
      HK_BR = T.let(:hk_br, WhopSDK::TaxIdentifierType::TaggedSymbol)
      HU_TIN = T.let(:hu_tin, WhopSDK::TaxIdentifierType::TaggedSymbol)
      IS_VAT = T.let(:is_vat, WhopSDK::TaxIdentifierType::TaggedSymbol)
      IN_GST = T.let(:in_gst, WhopSDK::TaxIdentifierType::TaggedSymbol)
      ID_NPWP = T.let(:id_npwp, WhopSDK::TaxIdentifierType::TaggedSymbol)
      IL_VAT = T.let(:il_vat, WhopSDK::TaxIdentifierType::TaggedSymbol)
      JP_CN = T.let(:jp_cn, WhopSDK::TaxIdentifierType::TaggedSymbol)
      JP_RN = T.let(:jp_rn, WhopSDK::TaxIdentifierType::TaggedSymbol)
      JP_TRN = T.let(:jp_trn, WhopSDK::TaxIdentifierType::TaggedSymbol)
      KZ_BIN = T.let(:kz_bin, WhopSDK::TaxIdentifierType::TaggedSymbol)
      KE_PIN = T.let(:ke_pin, WhopSDK::TaxIdentifierType::TaggedSymbol)
      KG_TIN = T.let(:kg_tin, WhopSDK::TaxIdentifierType::TaggedSymbol)
      LA_TIN = T.let(:la_tin, WhopSDK::TaxIdentifierType::TaggedSymbol)
      LI_UID = T.let(:li_uid, WhopSDK::TaxIdentifierType::TaggedSymbol)
      LI_VAT = T.let(:li_vat, WhopSDK::TaxIdentifierType::TaggedSymbol)
      MY_FRP = T.let(:my_frp, WhopSDK::TaxIdentifierType::TaggedSymbol)
      MY_ITN = T.let(:my_itn, WhopSDK::TaxIdentifierType::TaggedSymbol)
      MY_SST = T.let(:my_sst, WhopSDK::TaxIdentifierType::TaggedSymbol)
      MR_NIF = T.let(:mr_nif, WhopSDK::TaxIdentifierType::TaggedSymbol)
      MX_RFC = T.let(:mx_rfc, WhopSDK::TaxIdentifierType::TaggedSymbol)
      MD_VAT = T.let(:md_vat, WhopSDK::TaxIdentifierType::TaggedSymbol)
      ME_PIB = T.let(:me_pib, WhopSDK::TaxIdentifierType::TaggedSymbol)
      MA_VAT = T.let(:ma_vat, WhopSDK::TaxIdentifierType::TaggedSymbol)
      NP_PAN = T.let(:np_pan, WhopSDK::TaxIdentifierType::TaggedSymbol)
      NZ_GST = T.let(:nz_gst, WhopSDK::TaxIdentifierType::TaggedSymbol)
      NG_TIN = T.let(:ng_tin, WhopSDK::TaxIdentifierType::TaggedSymbol)
      MK_VAT = T.let(:mk_vat, WhopSDK::TaxIdentifierType::TaggedSymbol)
      NO_VAT = T.let(:no_vat, WhopSDK::TaxIdentifierType::TaggedSymbol)
      NO_VOEC = T.let(:no_voec, WhopSDK::TaxIdentifierType::TaggedSymbol)
      OM_VAT = T.let(:om_vat, WhopSDK::TaxIdentifierType::TaggedSymbol)
      PE_RUC = T.let(:pe_ruc, WhopSDK::TaxIdentifierType::TaggedSymbol)
      PH_TIN = T.let(:ph_tin, WhopSDK::TaxIdentifierType::TaggedSymbol)
      PL_NIP = T.let(:pl_nip, WhopSDK::TaxIdentifierType::TaggedSymbol)
      RO_TIN = T.let(:ro_tin, WhopSDK::TaxIdentifierType::TaggedSymbol)
      RU_INN = T.let(:ru_inn, WhopSDK::TaxIdentifierType::TaggedSymbol)
      RU_KPP = T.let(:ru_kpp, WhopSDK::TaxIdentifierType::TaggedSymbol)
      SA_VAT = T.let(:sa_vat, WhopSDK::TaxIdentifierType::TaggedSymbol)
      SN_NINEA = T.let(:sn_ninea, WhopSDK::TaxIdentifierType::TaggedSymbol)
      RS_PIB = T.let(:rs_pib, WhopSDK::TaxIdentifierType::TaggedSymbol)
      SG_GST = T.let(:sg_gst, WhopSDK::TaxIdentifierType::TaggedSymbol)
      SG_UEN = T.let(:sg_uen, WhopSDK::TaxIdentifierType::TaggedSymbol)
      SI_TIN = T.let(:si_tin, WhopSDK::TaxIdentifierType::TaggedSymbol)
      ZA_VAT = T.let(:za_vat, WhopSDK::TaxIdentifierType::TaggedSymbol)
      KR_BRN = T.let(:kr_brn, WhopSDK::TaxIdentifierType::TaggedSymbol)
      ES_CIF = T.let(:es_cif, WhopSDK::TaxIdentifierType::TaggedSymbol)
      CH_UID = T.let(:ch_uid, WhopSDK::TaxIdentifierType::TaggedSymbol)
      CH_VAT = T.let(:ch_vat, WhopSDK::TaxIdentifierType::TaggedSymbol)
      TW_VAT = T.let(:tw_vat, WhopSDK::TaxIdentifierType::TaggedSymbol)
      TJ_TIN = T.let(:tj_tin, WhopSDK::TaxIdentifierType::TaggedSymbol)
      TZ_VAT = T.let(:tz_vat, WhopSDK::TaxIdentifierType::TaggedSymbol)
      TH_VAT = T.let(:th_vat, WhopSDK::TaxIdentifierType::TaggedSymbol)
      TR_TIN = T.let(:tr_tin, WhopSDK::TaxIdentifierType::TaggedSymbol)
      UG_TIN = T.let(:ug_tin, WhopSDK::TaxIdentifierType::TaggedSymbol)
      UA_VAT = T.let(:ua_vat, WhopSDK::TaxIdentifierType::TaggedSymbol)
      AE_TRN = T.let(:ae_trn, WhopSDK::TaxIdentifierType::TaggedSymbol)
      US_EIN = T.let(:us_ein, WhopSDK::TaxIdentifierType::TaggedSymbol)
      UY_RUC = T.let(:uy_ruc, WhopSDK::TaxIdentifierType::TaggedSymbol)
      UZ_TIN = T.let(:uz_tin, WhopSDK::TaxIdentifierType::TaggedSymbol)
      UZ_VAT = T.let(:uz_vat, WhopSDK::TaxIdentifierType::TaggedSymbol)
      VE_RIF = T.let(:ve_rif, WhopSDK::TaxIdentifierType::TaggedSymbol)
      VN_TIN = T.let(:vn_tin, WhopSDK::TaxIdentifierType::TaggedSymbol)
      ZM_TIN = T.let(:zm_tin, WhopSDK::TaxIdentifierType::TaggedSymbol)
      ZW_TIN = T.let(:zw_tin, WhopSDK::TaxIdentifierType::TaggedSymbol)
      SR_FIN = T.let(:sr_fin, WhopSDK::TaxIdentifierType::TaggedSymbol)
      XI_VAT = T.let(:xi_vat, WhopSDK::TaxIdentifierType::TaggedSymbol)

      sig do
        override.returns(T::Array[WhopSDK::TaxIdentifierType::TaggedSymbol])
      end
      def self.values
      end
    end
  end
end
