module WhopSDK
  module Resources
    class Payouts
      class Methods
        def list: (
          ?account_id: String,
          ?after: String,
          ?amount: Float,
          ?before: String,
          ?currency: String,
          ?first: Integer,
          ?include_available: bool,
          ?last: Integer,
          ?status: WhopSDK::Models::Payouts::MethodListParams::status,
          ?user_id: String,
          ?request_options: WhopSDK::request_opts
        ) -> WhopSDK::Internal::CursorPage[WhopSDK::Models::Payouts::MethodListResponse]

        def initialize: (client: WhopSDK::Client) -> void
      end
    end
  end
end
