# frozen_string_literal: true

module Whop_sdk
  module SetupIntents
    module Types
      # Autogenerated input type of CreateSetupIntent
      class CreateSetupIntentsRequestConfirmationToken < Internal::Types::Model
        field :company_id, -> { String }, optional: false, nullable: false

        field :confirmation_token, -> { String }, optional: false, nullable: false

        field :currency, -> { Whop_sdk::Types::Currencies }, optional: true, nullable: false

        field :email, -> { String }, optional: true, nullable: false

        field :metadata, -> { Internal::Types::Hash[String, Object] }, optional: true, nullable: false

        field :return_url, -> { String }, optional: true, nullable: false
      end
    end
  end
end
