# frozen_string_literal: true

module Whop_sdk
  module CompanyTokenTransactions
    module Types
      # Autogenerated input type of CreateCompanyTokenTransaction
      class CreateCompanyTokenTransactionsRequestTransfer < Internal::Types::Model
        field :account_id, -> { String }, optional: false, nullable: false

        field :amount, -> { Integer }, optional: false, nullable: false

        field :description, -> { String }, optional: true, nullable: false

        field :destination_user_id, -> { String }, optional: false, nullable: false

        field :idempotency_key, -> { String }, optional: true, nullable: false

        field :user_id, -> { String }, optional: false, nullable: false
      end
    end
  end
end
