module WhopSDK
  module Models
    module Accounts
      type preference_update_params =
        {
          account_id: String,
          ads_payment_methods: WhopSDK::Accounts::PreferenceUpdateParams::AdsPaymentMethods
        }
        & WhopSDK::Internal::Type::request_parameters

      class PreferenceUpdateParams < WhopSDK::Internal::Type::BaseModel
        extend WhopSDK::Internal::Type::RequestParameters::Converter
        include WhopSDK::Internal::Type::RequestParameters

        attr_accessor account_id: String

        attr_reader ads_payment_methods: WhopSDK::Accounts::PreferenceUpdateParams::AdsPaymentMethods?

        def ads_payment_methods=: (
          WhopSDK::Accounts::PreferenceUpdateParams::AdsPaymentMethods
        ) -> WhopSDK::Accounts::PreferenceUpdateParams::AdsPaymentMethods

        def initialize: (
          account_id: String,
          ?ads_payment_methods: WhopSDK::Accounts::PreferenceUpdateParams::AdsPaymentMethods,
          ?request_options: WhopSDK::request_opts
        ) -> void

        def to_hash: -> {
          account_id: String,
          ads_payment_methods: WhopSDK::Accounts::PreferenceUpdateParams::AdsPaymentMethods,
          request_options: WhopSDK::RequestOptions
        }

        type ads_payment_methods =
          {
            primary: WhopSDK::Accounts::PreferenceUpdateParams::AdsPaymentMethods::Primary,
            backup: WhopSDK::Accounts::PreferenceUpdateParams::AdsPaymentMethods::Backup
          }

        class AdsPaymentMethods < WhopSDK::Internal::Type::BaseModel
          attr_accessor primary: WhopSDK::Accounts::PreferenceUpdateParams::AdsPaymentMethods::Primary

          attr_reader backup: WhopSDK::Accounts::PreferenceUpdateParams::AdsPaymentMethods::Backup?

          def backup=: (
            WhopSDK::Accounts::PreferenceUpdateParams::AdsPaymentMethods::Backup
          ) -> WhopSDK::Accounts::PreferenceUpdateParams::AdsPaymentMethods::Backup

          def initialize: (
            primary: WhopSDK::Accounts::PreferenceUpdateParams::AdsPaymentMethods::Primary,
            ?backup: WhopSDK::Accounts::PreferenceUpdateParams::AdsPaymentMethods::Backup
          ) -> void

          def to_hash: -> {
            primary: WhopSDK::Accounts::PreferenceUpdateParams::AdsPaymentMethods::Primary,
            backup: WhopSDK::Accounts::PreferenceUpdateParams::AdsPaymentMethods::Backup
          }

          type primary =
            {
              type: WhopSDK::Models::Accounts::PreferenceUpdateParams::AdsPaymentMethods::Primary::type_,
              id: String
            }

          class Primary < WhopSDK::Internal::Type::BaseModel
            attr_accessor type: WhopSDK::Models::Accounts::PreferenceUpdateParams::AdsPaymentMethods::Primary::type_

            attr_reader id: String?

            def id=: (String) -> String

            def initialize: (
              type: WhopSDK::Models::Accounts::PreferenceUpdateParams::AdsPaymentMethods::Primary::type_,
              ?id: String
            ) -> void

            def to_hash: -> {
              type: WhopSDK::Models::Accounts::PreferenceUpdateParams::AdsPaymentMethods::Primary::type_,
              id: String
            }

            type type_ = :platform_balance | :card

            module Type
              extend WhopSDK::Internal::Type::Enum

              PLATFORM_BALANCE: :platform_balance
              CARD: :card

              def self?.values: -> ::Array[WhopSDK::Models::Accounts::PreferenceUpdateParams::AdsPaymentMethods::Primary::type_]
            end
          end

          type backup =
            {
              type: WhopSDK::Models::Accounts::PreferenceUpdateParams::AdsPaymentMethods::Backup::type_,
              id: String
            }

          class Backup < WhopSDK::Internal::Type::BaseModel
            attr_accessor type: WhopSDK::Models::Accounts::PreferenceUpdateParams::AdsPaymentMethods::Backup::type_

            attr_reader id: String?

            def id=: (String) -> String

            def initialize: (
              type: WhopSDK::Models::Accounts::PreferenceUpdateParams::AdsPaymentMethods::Backup::type_,
              ?id: String
            ) -> void

            def to_hash: -> {
              type: WhopSDK::Models::Accounts::PreferenceUpdateParams::AdsPaymentMethods::Backup::type_,
              id: String
            }

            type type_ = :platform_balance | :card

            module Type
              extend WhopSDK::Internal::Type::Enum

              PLATFORM_BALANCE: :platform_balance
              CARD: :card

              def self?.values: -> ::Array[WhopSDK::Models::Accounts::PreferenceUpdateParams::AdsPaymentMethods::Backup::type_]
            end
          end
        end
      end
    end
  end
end
