module WhopSDK
  module Resources
    class Referrals
      class Partners
        def create: (
          ?request_options: WhopSDK::request_opts
        ) -> WhopSDK::Models::Referrals::PartnerCreateResponse

        def initialize: (client: WhopSDK::Client) -> void
      end
    end
  end
end
