module Whopsdk
  module Models
    type access_pass_list_response =
      {
        data: ::Array[Whopsdk::Models::AccessPassListResponse::Data?]?,
        page_info: Whopsdk::PageInfo
      }

    class AccessPassListResponse < Whopsdk::Internal::Type::BaseModel
      attr_accessor data: ::Array[Whopsdk::Models::AccessPassListResponse::Data?]?

      attr_accessor page_info: Whopsdk::PageInfo

      def initialize: (
        data: ::Array[Whopsdk::Models::AccessPassListResponse::Data?]?,
        page_info: Whopsdk::PageInfo
      ) -> void

      def to_hash: -> {
        data: ::Array[Whopsdk::Models::AccessPassListResponse::Data?]?,
        page_info: Whopsdk::PageInfo
      }

      type data =
        {
          id: String,
          business_type: Whopsdk::Models::business_types?,
          created_at: Integer,
          industry_type: Whopsdk::Models::industry_types?,
          member_count: Integer,
          published_reviews_count: Integer,
          route: String,
          title: String,
          updated_at: Integer,
          verified: bool
        }

      class Data < Whopsdk::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor business_type: Whopsdk::Models::business_types?

        attr_accessor created_at: Integer

        attr_accessor industry_type: Whopsdk::Models::industry_types?

        attr_accessor member_count: Integer

        attr_accessor published_reviews_count: Integer

        attr_accessor route: String

        attr_accessor title: String

        attr_accessor updated_at: Integer

        attr_accessor verified: bool

        def initialize: (
          id: String,
          business_type: Whopsdk::Models::business_types?,
          created_at: Integer,
          industry_type: Whopsdk::Models::industry_types?,
          member_count: Integer,
          published_reviews_count: Integer,
          route: String,
          title: String,
          updated_at: Integer,
          verified: bool
        ) -> void

        def to_hash: -> {
          id: String,
          business_type: Whopsdk::Models::business_types?,
          created_at: Integer,
          industry_type: Whopsdk::Models::industry_types?,
          member_count: Integer,
          published_reviews_count: Integer,
          route: String,
          title: String,
          updated_at: Integer,
          verified: bool
        }
      end
    end
  end
end
