module Whopsdk
  module Models
    type access_pass_type = :regular | :app | :experience_upsell | :api_only

    module AccessPassType
      extend Whopsdk::Internal::Type::Enum

      REGULAR: :regular
      APP: :app
      EXPERIENCE_UPSELL: :experience_upsell
      API_ONLY: :api_only

      def self?.values: -> ::Array[Whopsdk::Models::access_pass_type]
    end
  end
end
