module Whopsdk
  module Models
    type app_statuses = :live | :unlisted | :hidden

    module AppStatuses
      extend Whopsdk::Internal::Type::Enum

      LIVE: :live
      UNLISTED: :unlisted
      HIDDEN: :hidden

      def self?.values: -> ::Array[Whopsdk::Models::app_statuses]
    end
  end
end
