module Whopsdk
  module Models
    type app_build_list_params =
      {
        app_id: String,
        after: String?,
        before: String?,
        first: Integer?,
        last: Integer?,
        platform: Whopsdk::Models::app_build_platforms?,
        status: Whopsdk::Models::app_build_statuses?
      }
      & Whopsdk::Internal::Type::request_parameters

    class AppBuildListParams < Whopsdk::Internal::Type::BaseModel
      extend Whopsdk::Internal::Type::RequestParameters::Converter
      include Whopsdk::Internal::Type::RequestParameters

      attr_accessor app_id: String

      attr_accessor after: String?

      attr_accessor before: String?

      attr_accessor first: Integer?

      attr_accessor last: Integer?

      attr_accessor platform: Whopsdk::Models::app_build_platforms?

      attr_accessor status: Whopsdk::Models::app_build_statuses?

      def initialize: (
        app_id: String,
        ?after: String?,
        ?before: String?,
        ?first: Integer?,
        ?last: Integer?,
        ?platform: Whopsdk::Models::app_build_platforms?,
        ?status: Whopsdk::Models::app_build_statuses?,
        ?request_options: Whopsdk::request_opts
      ) -> void

      def to_hash: -> {
        app_id: String,
        after: String?,
        before: String?,
        first: Integer?,
        last: Integer?,
        platform: Whopsdk::Models::app_build_platforms?,
        status: Whopsdk::Models::app_build_statuses?,
        request_options: Whopsdk::RequestOptions
      }
    end
  end
end
