module Whopsdk
  module Models
    type checkout_configuration_list_params =
      {
        company_id: String,
        after: String?,
        before: String?,
        direction: Whopsdk::Models::direction?,
        first: Integer?,
        last: Integer?,
        plan_id: String?
      }
      & Whopsdk::Internal::Type::request_parameters

    class CheckoutConfigurationListParams < Whopsdk::Internal::Type::BaseModel
      extend Whopsdk::Internal::Type::RequestParameters::Converter
      include Whopsdk::Internal::Type::RequestParameters

      attr_accessor company_id: String

      attr_accessor after: String?

      attr_accessor before: String?

      attr_accessor direction: Whopsdk::Models::direction?

      attr_accessor first: Integer?

      attr_accessor last: Integer?

      attr_accessor plan_id: String?

      def initialize: (
        company_id: String,
        ?after: String?,
        ?before: String?,
        ?direction: Whopsdk::Models::direction?,
        ?first: Integer?,
        ?last: Integer?,
        ?plan_id: String?,
        ?request_options: Whopsdk::request_opts
      ) -> void

      def to_hash: -> {
        company_id: String,
        after: String?,
        before: String?,
        direction: Whopsdk::Models::direction?,
        first: Integer?,
        last: Integer?,
        plan_id: String?,
        request_options: Whopsdk::RequestOptions
      }
    end
  end
end
