module Whopsdk
  module Models
    type checkout_configuration =
      {
        id: String,
        affiliate_code: String,
        company_id: String,
        metadata: ::Hash[Symbol, top],
        plan: Whopsdk::CheckoutConfiguration::Plan,
        purchase_url: String,
        redirect_url: String
      }

    class CheckoutConfiguration < Whopsdk::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor affiliate_code: String

      attr_accessor company_id: String

      attr_accessor metadata: ::Hash[Symbol, top]

      attr_accessor plan: Whopsdk::CheckoutConfiguration::Plan

      attr_accessor purchase_url: String

      attr_accessor redirect_url: String

      def initialize: (
        id: String,
        affiliate_code: String,
        company_id: String,
        metadata: ::Hash[Symbol, top],
        plan: Whopsdk::CheckoutConfiguration::Plan,
        purchase_url: String,
        redirect_url: String
      ) -> void

      def to_hash: -> {
        id: String,
        affiliate_code: String,
        company_id: String,
        metadata: ::Hash[Symbol, top],
        plan: Whopsdk::CheckoutConfiguration::Plan,
        purchase_url: String,
        redirect_url: String
      }

      type plan =
        {
          id: String,
          billing_period: Integer?,
          currency: Whopsdk::Models::currency,
          expiration_days: Integer?,
          initial_price: Float,
          plan_type: Whopsdk::Models::plan_type,
          release_method: Whopsdk::Models::release_method,
          renewal_price: Float,
          trial_period_days: Integer?,
          visibility: Whopsdk::Models::visibility
        }

      class Plan < Whopsdk::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor billing_period: Integer?

        attr_accessor currency: Whopsdk::Models::currency

        attr_accessor expiration_days: Integer?

        attr_accessor initial_price: Float

        attr_accessor plan_type: Whopsdk::Models::plan_type

        attr_accessor release_method: Whopsdk::Models::release_method

        attr_accessor renewal_price: Float

        attr_accessor trial_period_days: Integer?

        attr_accessor visibility: Whopsdk::Models::visibility

        def initialize: (
          id: String,
          billing_period: Integer?,
          currency: Whopsdk::Models::currency,
          expiration_days: Integer?,
          initial_price: Float,
          plan_type: Whopsdk::Models::plan_type,
          release_method: Whopsdk::Models::release_method,
          renewal_price: Float,
          trial_period_days: Integer?,
          visibility: Whopsdk::Models::visibility
        ) -> void

        def to_hash: -> {
          id: String,
          billing_period: Integer?,
          currency: Whopsdk::Models::currency,
          expiration_days: Integer?,
          initial_price: Float,
          plan_type: Whopsdk::Models::plan_type,
          release_method: Whopsdk::Models::release_method,
          renewal_price: Float,
          trial_period_days: Integer?,
          visibility: Whopsdk::Models::visibility
        }
      end
    end
  end
end
