module Whopsdk
  module Models
    type course_lesson_interaction_list_response =
      {
        data: ::Array[Whopsdk::Models::CourseLessonInteractionListItem?]?,
        page_info: Whopsdk::PageInfo
      }

    class CourseLessonInteractionListResponse < Whopsdk::Internal::Type::BaseModel
      attr_accessor data: ::Array[Whopsdk::Models::CourseLessonInteractionListItem?]?

      attr_accessor page_info: Whopsdk::PageInfo

      def initialize: (
        data: ::Array[Whopsdk::Models::CourseLessonInteractionListItem?]?,
        page_info: Whopsdk::PageInfo
      ) -> void

      def to_hash: -> {
        data: ::Array[Whopsdk::Models::CourseLessonInteractionListItem?]?,
        page_info: Whopsdk::PageInfo
      }
    end
  end
end
