module Whopsdk
  module Models
    type entry_approve_response = { job_id: String }

    class EntryApproveResponse < Whopsdk::Internal::Type::BaseModel
      attr_accessor job_id: String

      def initialize: (job_id: String) -> void

      def to_hash: -> { job_id: String }
    end
  end
end
