module Whopsdk
  module Models
    type entry_list_params =
      {
        company_id: String,
        after: String?,
        before: String?,
        direction: Whopsdk::Models::direction?,
        first: Integer?,
        last: Integer?,
        order: Whopsdk::Models::EntryListParams::order?,
        plan_ids: ::Array[String]?,
        product_ids: ::Array[String]?,
        statuses: ::Array[Whopsdk::Models::entry_status?]?
      }
      & Whopsdk::Internal::Type::request_parameters

    class EntryListParams < Whopsdk::Internal::Type::BaseModel
      extend Whopsdk::Internal::Type::RequestParameters::Converter
      include Whopsdk::Internal::Type::RequestParameters

      attr_accessor company_id: String

      attr_accessor after: String?

      attr_accessor before: String?

      attr_accessor direction: Whopsdk::Models::direction?

      attr_accessor first: Integer?

      attr_accessor last: Integer?

      attr_accessor order: Whopsdk::Models::EntryListParams::order?

      attr_accessor plan_ids: ::Array[String]?

      attr_accessor product_ids: ::Array[String]?

      attr_accessor statuses: ::Array[Whopsdk::Models::entry_status?]?

      def initialize: (
        company_id: String,
        ?after: String?,
        ?before: String?,
        ?direction: Whopsdk::Models::direction?,
        ?first: Integer?,
        ?last: Integer?,
        ?order: Whopsdk::Models::EntryListParams::order?,
        ?plan_ids: ::Array[String]?,
        ?product_ids: ::Array[String]?,
        ?statuses: ::Array[Whopsdk::Models::entry_status?]?,
        ?request_options: Whopsdk::request_opts
      ) -> void

      def to_hash: -> {
        company_id: String,
        after: String?,
        before: String?,
        direction: Whopsdk::Models::direction?,
        first: Integer?,
        last: Integer?,
        order: Whopsdk::Models::EntryListParams::order?,
        plan_ids: ::Array[String]?,
        product_ids: ::Array[String]?,
        statuses: ::Array[Whopsdk::Models::entry_status?]?,
        request_options: Whopsdk::RequestOptions
      }

      type order = :id | :created_at

      module Order
        extend Whopsdk::Internal::Type::Enum

        ID: :id
        CREATED_AT: :created_at

        def self?.values: -> ::Array[Whopsdk::Models::EntryListParams::order]
      end
    end
  end
end
