module Whopsdk
  module Models
    type entry_list_response =
      {
        id: String,
        created_at: Integer?,
        plan: Whopsdk::Models::EntryListResponse::Plan?,
        product: Whopsdk::Models::EntryListResponse::Product?,
        status: Whopsdk::Models::entry_status?,
        user: Whopsdk::Models::EntryListResponse::User
      }

    class EntryListResponse < Whopsdk::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor created_at: Integer?

      attr_accessor plan: Whopsdk::Models::EntryListResponse::Plan?

      attr_accessor product: Whopsdk::Models::EntryListResponse::Product?

      attr_accessor status: Whopsdk::Models::entry_status?

      attr_accessor user: Whopsdk::Models::EntryListResponse::User

      def initialize: (
        id: String,
        created_at: Integer?,
        plan: Whopsdk::Models::EntryListResponse::Plan?,
        product: Whopsdk::Models::EntryListResponse::Product?,
        status: Whopsdk::Models::entry_status?,
        user: Whopsdk::Models::EntryListResponse::User
      ) -> void

      def to_hash: -> {
        id: String,
        created_at: Integer?,
        plan: Whopsdk::Models::EntryListResponse::Plan?,
        product: Whopsdk::Models::EntryListResponse::Product?,
        status: Whopsdk::Models::entry_status?,
        user: Whopsdk::Models::EntryListResponse::User
      }

      type plan = { id: String }

      class Plan < Whopsdk::Internal::Type::BaseModel
        attr_accessor id: String

        def initialize: (id: String) -> void

        def to_hash: -> { id: String }
      end

      type product = { id: String, title: String }

      class Product < Whopsdk::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor title: String

        def initialize: (id: String, title: String) -> void

        def to_hash: -> { id: String, title: String }
      end

      type user =
        { id: String, email: String?, name: String?, username: String }

      class User < Whopsdk::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor email: String?

        attr_accessor name: String?

        attr_accessor username: String

        def initialize: (
          id: String,
          email: String?,
          name: String?,
          username: String
        ) -> void

        def to_hash: -> {
          id: String,
          email: String?,
          name: String?,
          username: String
        }
      end
    end
  end
end
