module Whopsdk
  module Models
    type entry =
      {
        id: String,
        created_at: Integer?,
        custom_field_responses: ::Array[Whopsdk::Entry::CustomFieldResponse]?,
        plan: Whopsdk::Entry::Plan?,
        product: Whopsdk::Entry::Product?,
        status: Whopsdk::Models::entry_status,
        user: Whopsdk::Entry::User
      }

    class Entry < Whopsdk::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor created_at: Integer?

      attr_accessor custom_field_responses: ::Array[Whopsdk::Entry::CustomFieldResponse]?

      attr_accessor plan: Whopsdk::Entry::Plan?

      attr_accessor product: Whopsdk::Entry::Product?

      attr_accessor status: Whopsdk::Models::entry_status

      attr_accessor user: Whopsdk::Entry::User

      def initialize: (
        id: String,
        created_at: Integer?,
        custom_field_responses: ::Array[Whopsdk::Entry::CustomFieldResponse]?,
        plan: Whopsdk::Entry::Plan?,
        product: Whopsdk::Entry::Product?,
        status: Whopsdk::Models::entry_status,
        user: Whopsdk::Entry::User
      ) -> void

      def to_hash: -> {
        id: String,
        created_at: Integer?,
        custom_field_responses: ::Array[Whopsdk::Entry::CustomFieldResponse]?,
        plan: Whopsdk::Entry::Plan?,
        product: Whopsdk::Entry::Product?,
        status: Whopsdk::Models::entry_status,
        user: Whopsdk::Entry::User
      }

      type custom_field_response =
        { id: String, answer: String, question: String }

      class CustomFieldResponse < Whopsdk::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor answer: String

        attr_accessor question: String

        def initialize: (id: String, answer: String, question: String) -> void

        def to_hash: -> { id: String, answer: String, question: String }
      end

      type plan = { id: String }

      class Plan < Whopsdk::Internal::Type::BaseModel
        attr_accessor id: String

        def initialize: (id: String) -> void

        def to_hash: -> { id: String }
      end

      type product = { id: String, title: String }

      class Product < Whopsdk::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor title: String

        def initialize: (id: String, title: String) -> void

        def to_hash: -> { id: String, title: String }
      end

      type user =
        { id: String, email: String?, name: String?, username: String }

      class User < Whopsdk::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor email: String?

        attr_accessor name: String?

        attr_accessor username: String

        def initialize: (
          id: String,
          email: String?,
          name: String?,
          username: String
        ) -> void

        def to_hash: -> {
          id: String,
          email: String?,
          name: String?,
          username: String
        }
      end
    end
  end
end
