module Whopsdk
  module Models
    type experience_list_response =
      {
        id: String,
        app: Whopsdk::Models::ExperienceListResponse::App,
        company: Whopsdk::Models::ExperienceListResponse::Company,
        created_at: Integer,
        name: String,
        order: String?
      }

    class ExperienceListResponse < Whopsdk::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor app: Whopsdk::Models::ExperienceListResponse::App

      attr_accessor company: Whopsdk::Models::ExperienceListResponse::Company

      attr_accessor created_at: Integer

      attr_accessor name: String

      attr_accessor order: String?

      def initialize: (
        id: String,
        app: Whopsdk::Models::ExperienceListResponse::App,
        company: Whopsdk::Models::ExperienceListResponse::Company,
        created_at: Integer,
        name: String,
        order: String?
      ) -> void

      def to_hash: -> {
        id: String,
        app: Whopsdk::Models::ExperienceListResponse::App,
        company: Whopsdk::Models::ExperienceListResponse::Company,
        created_at: Integer,
        name: String,
        order: String?
      }

      type app = { id: String, name: String }

      class App < Whopsdk::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor name: String

        def initialize: (id: String, name: String) -> void

        def to_hash: -> { id: String, name: String }
      end

      type company = { id: String, route: String, title: String }

      class Company < Whopsdk::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor route: String

        attr_accessor title: String

        def initialize: (id: String, route: String, title: String) -> void

        def to_hash: -> { id: String, route: String, title: String }
      end
    end
  end
end
