module Whopsdk
  module Models
    type experience =
      {
        id: String,
        app: Whopsdk::Experience::App,
        company: Whopsdk::Experience::Company,
        created_at: Time,
        name: String,
        order: String?,
        products: ::Array[Whopsdk::Experience::Product]
      }

    class Experience < Whopsdk::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor app: Whopsdk::Experience::App

      attr_accessor company: Whopsdk::Experience::Company

      attr_accessor created_at: Time

      attr_accessor name: String

      attr_accessor order: String?

      attr_accessor products: ::Array[Whopsdk::Experience::Product]

      def initialize: (
        id: String,
        app: Whopsdk::Experience::App,
        company: Whopsdk::Experience::Company,
        created_at: Time,
        name: String,
        order: String?,
        products: ::Array[Whopsdk::Experience::Product]
      ) -> void

      def to_hash: -> {
        id: String,
        app: Whopsdk::Experience::App,
        company: Whopsdk::Experience::Company,
        created_at: Time,
        name: String,
        order: String?,
        products: ::Array[Whopsdk::Experience::Product]
      }

      type app = { id: String, name: String }

      class App < Whopsdk::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor name: String

        def initialize: (id: String, name: String) -> void

        def to_hash: -> { id: String, name: String }
      end

      type company = { id: String, route: String, title: String }

      class Company < Whopsdk::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor route: String

        attr_accessor title: String

        def initialize: (id: String, route: String, title: String) -> void

        def to_hash: -> { id: String, route: String, title: String }
      end

      type product = { id: String, route: String, title: String }

      class Product < Whopsdk::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor route: String

        attr_accessor title: String

        def initialize: (id: String, route: String, title: String) -> void

        def to_hash: -> { id: String, route: String, title: String }
      end
    end
  end
end
