module Whopsdk
  module Models
    type forum_post_list_params =
      {
        experience_id: String,
        after: String?,
        before: String?,
        first: Integer?,
        last: Integer?,
        parent_id: String?,
        pinned: bool?
      }
      & Whopsdk::Internal::Type::request_parameters

    class ForumPostListParams < Whopsdk::Internal::Type::BaseModel
      extend Whopsdk::Internal::Type::RequestParameters::Converter
      include Whopsdk::Internal::Type::RequestParameters

      attr_accessor experience_id: String

      attr_accessor after: String?

      attr_accessor before: String?

      attr_accessor first: Integer?

      attr_accessor last: Integer?

      attr_accessor parent_id: String?

      attr_accessor pinned: bool?

      def initialize: (
        experience_id: String,
        ?after: String?,
        ?before: String?,
        ?first: Integer?,
        ?last: Integer?,
        ?parent_id: String?,
        ?pinned: bool?,
        ?request_options: Whopsdk::request_opts
      ) -> void

      def to_hash: -> {
        experience_id: String,
        after: String?,
        before: String?,
        first: Integer?,
        last: Integer?,
        parent_id: String?,
        pinned: bool?,
        request_options: Whopsdk::RequestOptions
      }
    end
  end
end
