module Whopsdk
  module Models
    type global_affiliate_status = :enabled | :disabled

    module GlobalAffiliateStatus
      extend Whopsdk::Internal::Type::Enum

      ENABLED: :enabled
      DISABLED: :disabled

      def self?.values: -> ::Array[Whopsdk::Models::global_affiliate_status]
    end
  end
end
