module Whopsdk
  module Models
    type invoice_void_params =
      { client_mutation_id: String? }
      & Whopsdk::Internal::Type::request_parameters

    class InvoiceVoidParams < Whopsdk::Internal::Type::BaseModel
      extend Whopsdk::Internal::Type::RequestParameters::Converter
      include Whopsdk::Internal::Type::RequestParameters

      attr_accessor client_mutation_id: String?

      def initialize: (
        ?client_mutation_id: String?,
        ?request_options: Whopsdk::request_opts
      ) -> void

      def to_hash: -> {
        client_mutation_id: String?,
        request_options: Whopsdk::RequestOptions
      }
    end
  end
end
