module Whopsdk
  module Models
    type invoice_create_params =
      {
        collection_method: Whopsdk::Models::collection_method?,
        company_id: String,
        due_date: Integer,
        plan: Whopsdk::InvoiceCreateParams::Plan,
        charge_buyer_fee: bool?,
        customer_name: String?,
        email_address: String?,
        member_id: String?,
        payment_token_id: String?,
        product: Whopsdk::InvoiceCreateParams::Product?,
        product_id: String?
      }
      & Whopsdk::Internal::Type::request_parameters

    class InvoiceCreateParams < Whopsdk::Internal::Type::BaseModel
      extend Whopsdk::Internal::Type::RequestParameters::Converter
      include Whopsdk::Internal::Type::RequestParameters

      attr_accessor collection_method: Whopsdk::Models::collection_method?

      attr_accessor company_id: String

      attr_accessor due_date: Integer

      attr_accessor plan: Whopsdk::InvoiceCreateParams::Plan

      attr_accessor charge_buyer_fee: bool?

      attr_accessor customer_name: String?

      attr_accessor email_address: String?

      attr_accessor member_id: String?

      attr_accessor payment_token_id: String?

      attr_accessor product: Whopsdk::InvoiceCreateParams::Product?

      attr_accessor product_id: String?

      def initialize: (
        collection_method: Whopsdk::Models::collection_method?,
        company_id: String,
        due_date: Integer,
        plan: Whopsdk::InvoiceCreateParams::Plan,
        ?charge_buyer_fee: bool?,
        ?customer_name: String?,
        ?email_address: String?,
        ?member_id: String?,
        ?payment_token_id: String?,
        ?product: Whopsdk::InvoiceCreateParams::Product?,
        ?product_id: String?,
        ?request_options: Whopsdk::request_opts
      ) -> void

      def to_hash: -> {
        collection_method: Whopsdk::Models::collection_method?,
        company_id: String,
        due_date: Integer,
        plan: Whopsdk::InvoiceCreateParams::Plan,
        charge_buyer_fee: bool?,
        customer_name: String?,
        email_address: String?,
        member_id: String?,
        payment_token_id: String?,
        product: Whopsdk::InvoiceCreateParams::Product?,
        product_id: String?,
        request_options: Whopsdk::RequestOptions
      }

      type plan =
        {
          ach_payments: bool?,
          base_currency: Whopsdk::Models::currency?,
          billing_period: Integer?,
          card_payments: bool?,
          coinbase_commerce_accepted: bool?,
          custom_fields: ::Array[Whopsdk::InvoiceCreateParams::Plan::CustomField]?,
          description: String?,
          expiration_days: Integer?,
          initial_price: Float?,
          internal_notes: String?,
          offer_cancel_discount: bool?,
          paypal_accepted: bool?,
          plan_type: Whopsdk::Models::plan_type?,
          platform_balance_accepted: bool?,
          redirect_url: String?,
          release_method: Whopsdk::Models::release_method?,
          release_method_settings: Whopsdk::InvoiceCreateParams::Plan::ReleaseMethodSettings?,
          renewal_price: Float?,
          split_pay_required_payments: Integer?,
          splitit_accepted: bool?,
          stock: Integer?,
          trial_period_days: Integer?,
          unlimited_stock: bool?,
          visibility: Whopsdk::Models::visibility?
        }

      class Plan < Whopsdk::Internal::Type::BaseModel
        attr_accessor ach_payments: bool?

        attr_accessor base_currency: Whopsdk::Models::currency?

        attr_accessor billing_period: Integer?

        attr_accessor card_payments: bool?

        attr_accessor coinbase_commerce_accepted: bool?

        attr_accessor custom_fields: ::Array[Whopsdk::InvoiceCreateParams::Plan::CustomField]?

        attr_accessor description: String?

        attr_accessor expiration_days: Integer?

        attr_accessor initial_price: Float?

        attr_accessor internal_notes: String?

        attr_accessor offer_cancel_discount: bool?

        attr_accessor paypal_accepted: bool?

        attr_accessor plan_type: Whopsdk::Models::plan_type?

        attr_accessor platform_balance_accepted: bool?

        attr_accessor redirect_url: String?

        attr_accessor release_method: Whopsdk::Models::release_method?

        attr_accessor release_method_settings: Whopsdk::InvoiceCreateParams::Plan::ReleaseMethodSettings?

        attr_accessor renewal_price: Float?

        attr_accessor split_pay_required_payments: Integer?

        attr_accessor splitit_accepted: bool?

        attr_accessor stock: Integer?

        attr_accessor trial_period_days: Integer?

        attr_accessor unlimited_stock: bool?

        attr_accessor visibility: Whopsdk::Models::visibility?

        def initialize: (
          ?ach_payments: bool?,
          ?base_currency: Whopsdk::Models::currency?,
          ?billing_period: Integer?,
          ?card_payments: bool?,
          ?coinbase_commerce_accepted: bool?,
          ?custom_fields: ::Array[Whopsdk::InvoiceCreateParams::Plan::CustomField]?,
          ?description: String?,
          ?expiration_days: Integer?,
          ?initial_price: Float?,
          ?internal_notes: String?,
          ?offer_cancel_discount: bool?,
          ?paypal_accepted: bool?,
          ?plan_type: Whopsdk::Models::plan_type?,
          ?platform_balance_accepted: bool?,
          ?redirect_url: String?,
          ?release_method: Whopsdk::Models::release_method?,
          ?release_method_settings: Whopsdk::InvoiceCreateParams::Plan::ReleaseMethodSettings?,
          ?renewal_price: Float?,
          ?split_pay_required_payments: Integer?,
          ?splitit_accepted: bool?,
          ?stock: Integer?,
          ?trial_period_days: Integer?,
          ?unlimited_stock: bool?,
          ?visibility: Whopsdk::Models::visibility?
        ) -> void

        def to_hash: -> {
          ach_payments: bool?,
          base_currency: Whopsdk::Models::currency?,
          billing_period: Integer?,
          card_payments: bool?,
          coinbase_commerce_accepted: bool?,
          custom_fields: ::Array[Whopsdk::InvoiceCreateParams::Plan::CustomField]?,
          description: String?,
          expiration_days: Integer?,
          initial_price: Float?,
          internal_notes: String?,
          offer_cancel_discount: bool?,
          paypal_accepted: bool?,
          plan_type: Whopsdk::Models::plan_type?,
          platform_balance_accepted: bool?,
          redirect_url: String?,
          release_method: Whopsdk::Models::release_method?,
          release_method_settings: Whopsdk::InvoiceCreateParams::Plan::ReleaseMethodSettings?,
          renewal_price: Float?,
          split_pay_required_payments: Integer?,
          splitit_accepted: bool?,
          stock: Integer?,
          trial_period_days: Integer?,
          unlimited_stock: bool?,
          visibility: Whopsdk::Models::visibility?
        }

        type custom_field =
          {
            field_type: Whopsdk::Models::InvoiceCreateParams::Plan::CustomField::field_type?,
            name: String,
            id: String?,
            order: Integer?,
            placeholder: String?,
            required: bool?
          }

        class CustomField < Whopsdk::Internal::Type::BaseModel
          attr_accessor field_type: Whopsdk::Models::InvoiceCreateParams::Plan::CustomField::field_type?

          attr_accessor name: String

          attr_accessor id: String?

          attr_accessor order: Integer?

          attr_accessor placeholder: String?

          attr_accessor required: bool?

          def initialize: (
            field_type: Whopsdk::Models::InvoiceCreateParams::Plan::CustomField::field_type?,
            name: String,
            ?id: String?,
            ?order: Integer?,
            ?placeholder: String?,
            ?required: bool?
          ) -> void

          def to_hash: -> {
            field_type: Whopsdk::Models::InvoiceCreateParams::Plan::CustomField::field_type?,
            name: String,
            id: String?,
            order: Integer?,
            placeholder: String?,
            required: bool?
          }

          type field_type = :text

          module FieldType
            extend Whopsdk::Internal::Type::Enum

            TEXT: :text

            def self?.values: -> ::Array[Whopsdk::Models::InvoiceCreateParams::Plan::CustomField::field_type]
          end
        end

        type release_method_settings =
          {
            expires_at: Integer?,
            max_entries: Integer?,
            nft_weighted_entries: bool?,
            starts_at: Integer?
          }

        class ReleaseMethodSettings < Whopsdk::Internal::Type::BaseModel
          attr_accessor expires_at: Integer?

          attr_accessor max_entries: Integer?

          attr_accessor nft_weighted_entries: bool?

          attr_accessor starts_at: Integer?

          def initialize: (
            ?expires_at: Integer?,
            ?max_entries: Integer?,
            ?nft_weighted_entries: bool?,
            ?starts_at: Integer?
          ) -> void

          def to_hash: -> {
            expires_at: Integer?,
            max_entries: Integer?,
            nft_weighted_entries: bool?,
            starts_at: Integer?
          }
        end
      end

      type product = { title: String, product_tax_code_id: String? }

      class Product < Whopsdk::Internal::Type::BaseModel
        attr_accessor title: String

        attr_accessor product_tax_code_id: String?

        def initialize: (title: String, ?product_tax_code_id: String?) -> void

        def to_hash: -> { title: String, product_tax_code_id: String? }
      end
    end
  end
end
