module Whopsdk
  module Models
    type invoice_voided_webhook_event =
      {
        id: String,
        api_version: :v1,
        created_at: String,
        data: Whopsdk::Invoice,
        type: :"invoice.voided"
      }

    class InvoiceVoidedWebhookEvent < Whopsdk::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor api_version: :v1

      attr_accessor created_at: String

      attr_accessor data: Whopsdk::Invoice

      attr_accessor type: :"invoice.voided"

      def initialize: (
        id: String,
        created_at: String,
        data: Whopsdk::Invoice,
        ?api_version: :v1,
        ?type: :"invoice.voided"
      ) -> void

      def to_hash: -> {
        id: String,
        api_version: :v1,
        created_at: String,
        data: Whopsdk::Invoice,
        type: :"invoice.voided"
      }
    end
  end
end
