module Whopsdk
  module Models
    type invoice_created_webhook_event =
      {
        id: String,
        api_version: :v1,
        data: Whopsdk::Invoice,
        timestamp: Time,
        type: :"invoice.created"
      }

    class InvoiceCreatedWebhookEvent < Whopsdk::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor api_version: :v1

      attr_accessor data: Whopsdk::Invoice

      attr_accessor timestamp: Time

      attr_accessor type: :"invoice.created"

      def initialize: (
        id: String,
        data: Whopsdk::Invoice,
        timestamp: Time,
        ?api_version: :v1,
        ?type: :"invoice.created"
      ) -> void

      def to_hash: -> {
        id: String,
        api_version: :v1,
        data: Whopsdk::Invoice,
        timestamp: Time,
        type: :"invoice.created"
      }
    end
  end
end
