module Whopsdk
  module Models
    type invoice_created_webhook_event =
      {
        id: String,
        api_version: Whopsdk::Models::InvoiceCreatedWebhookEvent::api_version,
        created_at: String,
        data: Whopsdk::Invoice?,
        type: Whopsdk::Models::InvoiceCreatedWebhookEvent::type_
      }

    class InvoiceCreatedWebhookEvent < Whopsdk::Internal::Type::BaseModel
      attr_reader id: String?

      def id=: (String) -> String

      attr_reader api_version: Whopsdk::Models::InvoiceCreatedWebhookEvent::api_version?

      def api_version=: (
        Whopsdk::Models::InvoiceCreatedWebhookEvent::api_version
      ) -> Whopsdk::Models::InvoiceCreatedWebhookEvent::api_version

      attr_reader created_at: String?

      def created_at=: (String) -> String

      attr_accessor data: Whopsdk::Invoice?

      attr_reader type: Whopsdk::Models::InvoiceCreatedWebhookEvent::type_?

      def type=: (
        Whopsdk::Models::InvoiceCreatedWebhookEvent::type_
      ) -> Whopsdk::Models::InvoiceCreatedWebhookEvent::type_

      def initialize: (
        ?id: String,
        ?api_version: Whopsdk::Models::InvoiceCreatedWebhookEvent::api_version,
        ?created_at: String,
        ?data: Whopsdk::Invoice?,
        ?type: Whopsdk::Models::InvoiceCreatedWebhookEvent::type_
      ) -> void

      def to_hash: -> {
        id: String,
        api_version: Whopsdk::Models::InvoiceCreatedWebhookEvent::api_version,
        created_at: String,
        data: Whopsdk::Invoice?,
        type: Whopsdk::Models::InvoiceCreatedWebhookEvent::type_
      }

      type api_version = :v1

      module APIVersion
        extend Whopsdk::Internal::Type::Enum

        V1: :v1

        def self?.values: -> ::Array[Whopsdk::Models::InvoiceCreatedWebhookEvent::api_version]
      end

      type type_ = :"invoice.created"

      module Type
        extend Whopsdk::Internal::Type::Enum

        INVOICE_CREATED: :"invoice.created"

        def self?.values: -> ::Array[Whopsdk::Models::InvoiceCreatedWebhookEvent::type_]
      end
    end
  end
end
