module Whopsdk
  module Models
    type invoice_list_response =
      {
        data: ::Array[Whopsdk::Models::InvoiceListItem?]?,
        page_info: Whopsdk::PageInfo
      }

    class InvoiceListResponse < Whopsdk::Internal::Type::BaseModel
      attr_accessor data: ::Array[Whopsdk::Models::InvoiceListItem?]?

      attr_accessor page_info: Whopsdk::PageInfo

      def initialize: (
        data: ::Array[Whopsdk::Models::InvoiceListItem?]?,
        page_info: Whopsdk::PageInfo
      ) -> void

      def to_hash: -> {
        data: ::Array[Whopsdk::Models::InvoiceListItem?]?,
        page_info: Whopsdk::PageInfo
      }
    end
  end
end
