module Whopsdk
  module Models
    type invoice_list_params =
      {
        company_id: String,
        after: String?,
        before: String?,
        direction: Whopsdk::Models::direction?,
        filters: Whopsdk::InvoiceListParams::Filters?,
        first: Integer?,
        last: Integer?,
        order: Whopsdk::Models::InvoiceListParams::order?
      }
      & Whopsdk::Internal::Type::request_parameters

    class InvoiceListParams < Whopsdk::Internal::Type::BaseModel
      extend Whopsdk::Internal::Type::RequestParameters::Converter
      include Whopsdk::Internal::Type::RequestParameters

      attr_accessor company_id: String

      attr_accessor after: String?

      attr_accessor before: String?

      attr_accessor direction: Whopsdk::Models::direction?

      attr_accessor filters: Whopsdk::InvoiceListParams::Filters?

      attr_accessor first: Integer?

      attr_accessor last: Integer?

      attr_accessor order: Whopsdk::Models::InvoiceListParams::order?

      def initialize: (
        company_id: String,
        ?after: String?,
        ?before: String?,
        ?direction: Whopsdk::Models::direction?,
        ?filters: Whopsdk::InvoiceListParams::Filters?,
        ?first: Integer?,
        ?last: Integer?,
        ?order: Whopsdk::Models::InvoiceListParams::order?,
        ?request_options: Whopsdk::request_opts
      ) -> void

      def to_hash: -> {
        company_id: String,
        after: String?,
        before: String?,
        direction: Whopsdk::Models::direction?,
        filters: Whopsdk::InvoiceListParams::Filters?,
        first: Integer?,
        last: Integer?,
        order: Whopsdk::Models::InvoiceListParams::order?,
        request_options: Whopsdk::RequestOptions
      }

      type filters =
        {
          access_pass_ids: ::Array[String]?,
          collection_methods: ::Array[Whopsdk::Models::collection_method?]?,
          statuses: ::Array[Whopsdk::Models::invoice_status?]?
        }

      class Filters < Whopsdk::Internal::Type::BaseModel
        attr_accessor access_pass_ids: ::Array[String]?

        attr_accessor collection_methods: ::Array[Whopsdk::Models::collection_method?]?

        attr_accessor statuses: ::Array[Whopsdk::Models::invoice_status?]?

        def initialize: (
          ?access_pass_ids: ::Array[String]?,
          ?collection_methods: ::Array[Whopsdk::Models::collection_method?]?,
          ?statuses: ::Array[Whopsdk::Models::invoice_status?]?
        ) -> void

        def to_hash: -> {
          access_pass_ids: ::Array[String]?,
          collection_methods: ::Array[Whopsdk::Models::collection_method?]?,
          statuses: ::Array[Whopsdk::Models::invoice_status?]?
        }
      end

      type order = :id | :created_at | :due_date

      module Order
        extend Whopsdk::Internal::Type::Enum

        ID: :id
        CREATED_AT: :created_at
        DUE_DATE: :due_date

        def self?.values: -> ::Array[Whopsdk::Models::InvoiceListParams::order]
      end
    end
  end
end
