module Whopsdk
  module Models
    type membership_pause_params =
      { void_payments: bool? } & Whopsdk::Internal::Type::request_parameters

    class MembershipPauseParams < Whopsdk::Internal::Type::BaseModel
      extend Whopsdk::Internal::Type::RequestParameters::Converter
      include Whopsdk::Internal::Type::RequestParameters

      attr_accessor void_payments: bool?

      def initialize: (
        ?void_payments: bool?,
        ?request_options: Whopsdk::request_opts
      ) -> void

      def to_hash: -> {
        void_payments: bool?,
        request_options: Whopsdk::RequestOptions
      }
    end
  end
end
