module Whopsdk
  module Models
    type message_create_params =
      {
        channel_id: String,
        content: String,
        attachments: ::Array[Whopsdk::MessageCreateParams::Attachment]?,
        poll: Whopsdk::MessageCreateParams::Poll?
      }
      & Whopsdk::Internal::Type::request_parameters

    class MessageCreateParams < Whopsdk::Internal::Type::BaseModel
      extend Whopsdk::Internal::Type::RequestParameters::Converter
      include Whopsdk::Internal::Type::RequestParameters

      attr_accessor channel_id: String

      attr_accessor content: String

      attr_accessor attachments: ::Array[Whopsdk::MessageCreateParams::Attachment]?

      attr_accessor poll: Whopsdk::MessageCreateParams::Poll?

      def initialize: (
        channel_id: String,
        content: String,
        ?attachments: ::Array[Whopsdk::MessageCreateParams::Attachment]?,
        ?poll: Whopsdk::MessageCreateParams::Poll?,
        ?request_options: Whopsdk::request_opts
      ) -> void

      def to_hash: -> {
        channel_id: String,
        content: String,
        attachments: ::Array[Whopsdk::MessageCreateParams::Attachment]?,
        poll: Whopsdk::MessageCreateParams::Poll?,
        request_options: Whopsdk::RequestOptions
      }

      type attachment = { id: String?, direct_upload_id: String? }

      class Attachment < Whopsdk::Internal::Type::BaseModel
        attr_accessor id: String?

        attr_accessor direct_upload_id: String?

        def initialize: (?id: String?, ?direct_upload_id: String?) -> void

        def to_hash: -> { id: String?, direct_upload_id: String? }
      end

      type poll =
        { options: ::Array[Whopsdk::MessageCreateParams::Poll::Option] }

      class Poll < Whopsdk::Internal::Type::BaseModel
        attr_accessor options: ::Array[Whopsdk::MessageCreateParams::Poll::Option]

        def initialize: (
          options: ::Array[Whopsdk::MessageCreateParams::Poll::Option]
        ) -> void

        def to_hash: -> {
          options: ::Array[Whopsdk::MessageCreateParams::Poll::Option]
        }

        type option = { id: String, text: String }

        class Option < Whopsdk::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor text: String

          def initialize: (id: String, text: String) -> void

          def to_hash: -> { id: String, text: String }
        end
      end
    end
  end
end
