module Whopsdk
  module Models
    type payment_list_response =
      {
        id: String,
        amount_after_fees: Float,
        auto_refunded: bool,
        billing_address: Whopsdk::Models::PaymentListResponse::BillingAddress?,
        billing_reason: String?,
        card_brand: String?,
        :card_last4 => String?,
        company: Whopsdk::Models::PaymentListResponse::Company?,
        created_at: Integer,
        currency: Whopsdk::Models::currency?,
        dispute_alerted_at: Integer?,
        failure_message: String?,
        last_payment_attempt: Integer?,
        membership: Whopsdk::Models::PaymentListResponse::Membership?,
        paid_at: Integer?,
        payment_method_type: String?,
        plan: Whopsdk::Models::PaymentListResponse::Plan?,
        product: Whopsdk::Models::PaymentListResponse::Product?,
        promo_code: Whopsdk::Models::PaymentListResponse::PromoCode?,
        refundable: bool,
        refunded_amount: Float?,
        refunded_at: Integer?,
        retryable: bool,
        status: Whopsdk::Models::receipt_status?,
        substatus: Whopsdk::Models::friendly_receipt_status,
        subtotal: Float?,
        total: Float?,
        usd_total: Float?,
        user: Whopsdk::Models::PaymentListResponse::User?
      }

    class PaymentListResponse < Whopsdk::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor amount_after_fees: Float

      attr_accessor auto_refunded: bool

      attr_accessor billing_address: Whopsdk::Models::PaymentListResponse::BillingAddress?

      attr_accessor billing_reason: String?

      attr_accessor card_brand: String?

      attr_accessor card_last4: String?

      attr_accessor company: Whopsdk::Models::PaymentListResponse::Company?

      attr_accessor created_at: Integer

      attr_accessor currency: Whopsdk::Models::currency?

      attr_accessor dispute_alerted_at: Integer?

      attr_accessor failure_message: String?

      attr_accessor last_payment_attempt: Integer?

      attr_accessor membership: Whopsdk::Models::PaymentListResponse::Membership?

      attr_accessor paid_at: Integer?

      attr_accessor payment_method_type: String?

      attr_accessor plan: Whopsdk::Models::PaymentListResponse::Plan?

      attr_accessor product: Whopsdk::Models::PaymentListResponse::Product?

      attr_accessor promo_code: Whopsdk::Models::PaymentListResponse::PromoCode?

      attr_accessor refundable: bool

      attr_accessor refunded_amount: Float?

      attr_accessor refunded_at: Integer?

      attr_accessor retryable: bool

      attr_accessor status: Whopsdk::Models::receipt_status?

      attr_accessor substatus: Whopsdk::Models::friendly_receipt_status

      attr_accessor subtotal: Float?

      attr_accessor total: Float?

      attr_accessor usd_total: Float?

      attr_accessor user: Whopsdk::Models::PaymentListResponse::User?

      def initialize: (
        id: String,
        amount_after_fees: Float,
        auto_refunded: bool,
        billing_address: Whopsdk::Models::PaymentListResponse::BillingAddress?,
        billing_reason: String?,
        card_brand: String?,
        card_last4: String?,
        company: Whopsdk::Models::PaymentListResponse::Company?,
        created_at: Integer,
        currency: Whopsdk::Models::currency?,
        dispute_alerted_at: Integer?,
        failure_message: String?,
        last_payment_attempt: Integer?,
        membership: Whopsdk::Models::PaymentListResponse::Membership?,
        paid_at: Integer?,
        payment_method_type: String?,
        plan: Whopsdk::Models::PaymentListResponse::Plan?,
        product: Whopsdk::Models::PaymentListResponse::Product?,
        promo_code: Whopsdk::Models::PaymentListResponse::PromoCode?,
        refundable: bool,
        refunded_amount: Float?,
        refunded_at: Integer?,
        retryable: bool,
        status: Whopsdk::Models::receipt_status?,
        substatus: Whopsdk::Models::friendly_receipt_status,
        subtotal: Float?,
        total: Float?,
        usd_total: Float?,
        user: Whopsdk::Models::PaymentListResponse::User?
      ) -> void

      def to_hash: -> {
        id: String,
        amount_after_fees: Float,
        auto_refunded: bool,
        billing_address: Whopsdk::Models::PaymentListResponse::BillingAddress?,
        billing_reason: String?,
        card_brand: String?,
        :card_last4 => String?,
        company: Whopsdk::Models::PaymentListResponse::Company?,
        created_at: Integer,
        currency: Whopsdk::Models::currency?,
        dispute_alerted_at: Integer?,
        failure_message: String?,
        last_payment_attempt: Integer?,
        membership: Whopsdk::Models::PaymentListResponse::Membership?,
        paid_at: Integer?,
        payment_method_type: String?,
        plan: Whopsdk::Models::PaymentListResponse::Plan?,
        product: Whopsdk::Models::PaymentListResponse::Product?,
        promo_code: Whopsdk::Models::PaymentListResponse::PromoCode?,
        refundable: bool,
        refunded_amount: Float?,
        refunded_at: Integer?,
        retryable: bool,
        status: Whopsdk::Models::receipt_status?,
        substatus: Whopsdk::Models::friendly_receipt_status,
        subtotal: Float?,
        total: Float?,
        usd_total: Float?,
        user: Whopsdk::Models::PaymentListResponse::User?
      }

      type billing_address =
        {
          city: String?,
          country: String?,
          :line1 => String?,
          :line2 => String?,
          name: String?,
          postal_code: String?,
          state: String?
        }

      class BillingAddress < Whopsdk::Internal::Type::BaseModel
        attr_accessor city: String?

        attr_accessor country: String?

        attr_accessor line1: String?

        attr_accessor line2: String?

        attr_accessor name: String?

        attr_accessor postal_code: String?

        attr_accessor state: String?

        def initialize: (
          city: String?,
          country: String?,
          line1: String?,
          line2: String?,
          name: String?,
          postal_code: String?,
          state: String?
        ) -> void

        def to_hash: -> {
          city: String?,
          country: String?,
          :line1 => String?,
          :line2 => String?,
          name: String?,
          postal_code: String?,
          state: String?
        }
      end

      type company = { id: String, route: String, title: String }

      class Company < Whopsdk::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor route: String

        attr_accessor title: String

        def initialize: (id: String, route: String, title: String) -> void

        def to_hash: -> { id: String, route: String, title: String }
      end

      type membership =
        { id: String, status: Whopsdk::Models::membership_status }

      class Membership < Whopsdk::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor status: Whopsdk::Models::membership_status

        def initialize: (
          id: String,
          status: Whopsdk::Models::membership_status
        ) -> void

        def to_hash: -> {
          id: String,
          status: Whopsdk::Models::membership_status
        }
      end

      type plan = { id: String }

      class Plan < Whopsdk::Internal::Type::BaseModel
        attr_accessor id: String

        def initialize: (id: String) -> void

        def to_hash: -> { id: String }
      end

      type product = { id: String, route: String, title: String }

      class Product < Whopsdk::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor route: String

        attr_accessor title: String

        def initialize: (id: String, route: String, title: String) -> void

        def to_hash: -> { id: String, route: String, title: String }
      end

      type promo_code =
        {
          id: String,
          amount_off: Float,
          base_currency: Whopsdk::Models::currency,
          code: String?,
          number_of_intervals: Integer?,
          promo_type: Whopsdk::Models::promo_type
        }

      class PromoCode < Whopsdk::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor amount_off: Float

        attr_accessor base_currency: Whopsdk::Models::currency

        attr_accessor code: String?

        attr_accessor number_of_intervals: Integer?

        attr_accessor promo_type: Whopsdk::Models::promo_type

        def initialize: (
          id: String,
          amount_off: Float,
          base_currency: Whopsdk::Models::currency,
          code: String?,
          number_of_intervals: Integer?,
          promo_type: Whopsdk::Models::promo_type
        ) -> void

        def to_hash: -> {
          id: String,
          amount_off: Float,
          base_currency: Whopsdk::Models::currency,
          code: String?,
          number_of_intervals: Integer?,
          promo_type: Whopsdk::Models::promo_type
        }
      end

      type user =
        { id: String, email: String?, name: String?, username: String }

      class User < Whopsdk::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor email: String?

        attr_accessor name: String?

        attr_accessor username: String

        def initialize: (
          id: String,
          email: String?,
          name: String?,
          username: String
        ) -> void

        def to_hash: -> {
          id: String,
          email: String?,
          name: String?,
          username: String
        }
      end
    end
  end
end
