module Whopsdk
  module Models
    type plan_create_params =
      {
        company_id: String,
        product_id: String,
        billing_period: Integer?,
        currency: Whopsdk::Models::currency?,
        custom_fields: ::Array[Whopsdk::PlanCreateParams::CustomField]?,
        description: String?,
        expiration_days: Integer?,
        initial_price: Float?,
        internal_notes: String?,
        override_tax_type: Whopsdk::Models::tax_type?,
        plan_type: Whopsdk::Models::plan_type?,
        release_method: Whopsdk::Models::release_method?,
        renewal_price: Float?,
        trial_period_days: Integer?,
        visibility: Whopsdk::Models::visibility?
      }
      & Whopsdk::Internal::Type::request_parameters

    class PlanCreateParams < Whopsdk::Internal::Type::BaseModel
      extend Whopsdk::Internal::Type::RequestParameters::Converter
      include Whopsdk::Internal::Type::RequestParameters

      attr_accessor company_id: String

      attr_accessor product_id: String

      attr_accessor billing_period: Integer?

      attr_accessor currency: Whopsdk::Models::currency?

      attr_accessor custom_fields: ::Array[Whopsdk::PlanCreateParams::CustomField]?

      attr_accessor description: String?

      attr_accessor expiration_days: Integer?

      attr_accessor initial_price: Float?

      attr_accessor internal_notes: String?

      attr_accessor override_tax_type: Whopsdk::Models::tax_type?

      attr_accessor plan_type: Whopsdk::Models::plan_type?

      attr_accessor release_method: Whopsdk::Models::release_method?

      attr_accessor renewal_price: Float?

      attr_accessor trial_period_days: Integer?

      attr_accessor visibility: Whopsdk::Models::visibility?

      def initialize: (
        company_id: String,
        product_id: String,
        ?billing_period: Integer?,
        ?currency: Whopsdk::Models::currency?,
        ?custom_fields: ::Array[Whopsdk::PlanCreateParams::CustomField]?,
        ?description: String?,
        ?expiration_days: Integer?,
        ?initial_price: Float?,
        ?internal_notes: String?,
        ?override_tax_type: Whopsdk::Models::tax_type?,
        ?plan_type: Whopsdk::Models::plan_type?,
        ?release_method: Whopsdk::Models::release_method?,
        ?renewal_price: Float?,
        ?trial_period_days: Integer?,
        ?visibility: Whopsdk::Models::visibility?,
        ?request_options: Whopsdk::request_opts
      ) -> void

      def to_hash: -> {
        company_id: String,
        product_id: String,
        billing_period: Integer?,
        currency: Whopsdk::Models::currency?,
        custom_fields: ::Array[Whopsdk::PlanCreateParams::CustomField]?,
        description: String?,
        expiration_days: Integer?,
        initial_price: Float?,
        internal_notes: String?,
        override_tax_type: Whopsdk::Models::tax_type?,
        plan_type: Whopsdk::Models::plan_type?,
        release_method: Whopsdk::Models::release_method?,
        renewal_price: Float?,
        trial_period_days: Integer?,
        visibility: Whopsdk::Models::visibility?,
        request_options: Whopsdk::RequestOptions
      }

      type custom_field =
        {
          field_type: Whopsdk::Models::PlanCreateParams::CustomField::field_type?,
          name: String,
          id: String?,
          order: Integer?,
          placeholder: String?,
          required: bool?
        }

      class CustomField < Whopsdk::Internal::Type::BaseModel
        attr_accessor field_type: Whopsdk::Models::PlanCreateParams::CustomField::field_type?

        attr_accessor name: String

        attr_accessor id: String?

        attr_accessor order: Integer?

        attr_accessor placeholder: String?

        attr_accessor required: bool?

        def initialize: (
          field_type: Whopsdk::Models::PlanCreateParams::CustomField::field_type?,
          name: String,
          ?id: String?,
          ?order: Integer?,
          ?placeholder: String?,
          ?required: bool?
        ) -> void

        def to_hash: -> {
          field_type: Whopsdk::Models::PlanCreateParams::CustomField::field_type?,
          name: String,
          id: String?,
          order: Integer?,
          placeholder: String?,
          required: bool?
        }

        type field_type = :text

        module FieldType
          extend Whopsdk::Internal::Type::Enum

          TEXT: :text

          def self?.values: -> ::Array[Whopsdk::Models::PlanCreateParams::CustomField::field_type]
        end
      end
    end
  end
end
