module Whopsdk
  module Models
    type plan_list_response =
      {
        id: String,
        billing_period: Integer?,
        company: Whopsdk::Models::PlanListResponse::Company?,
        created_at: Integer,
        currency: Whopsdk::Models::currency,
        description: String?,
        expiration_days: Integer?,
        initial_price: Float,
        internal_notes: String?,
        invoice: Whopsdk::Models::PlanListResponse::Invoice?,
        member_count: Integer?,
        plan_type: Whopsdk::Models::plan_type,
        product: Whopsdk::Models::PlanListResponse::Product?,
        purchase_link: String,
        release_method: Whopsdk::Models::release_method,
        renewal_price: Float,
        trial_period_days: Integer?,
        updated_at: Integer,
        visibility: Whopsdk::Models::visibility
      }

    class PlanListResponse < Whopsdk::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor billing_period: Integer?

      attr_accessor company: Whopsdk::Models::PlanListResponse::Company?

      attr_accessor created_at: Integer

      attr_accessor currency: Whopsdk::Models::currency

      attr_accessor description: String?

      attr_accessor expiration_days: Integer?

      attr_accessor initial_price: Float

      attr_accessor internal_notes: String?

      attr_accessor invoice: Whopsdk::Models::PlanListResponse::Invoice?

      attr_accessor member_count: Integer?

      attr_accessor plan_type: Whopsdk::Models::plan_type

      attr_accessor product: Whopsdk::Models::PlanListResponse::Product?

      attr_accessor purchase_link: String

      attr_accessor release_method: Whopsdk::Models::release_method

      attr_accessor renewal_price: Float

      attr_accessor trial_period_days: Integer?

      attr_accessor updated_at: Integer

      attr_accessor visibility: Whopsdk::Models::visibility

      def initialize: (
        id: String,
        billing_period: Integer?,
        company: Whopsdk::Models::PlanListResponse::Company?,
        created_at: Integer,
        currency: Whopsdk::Models::currency,
        description: String?,
        expiration_days: Integer?,
        initial_price: Float,
        internal_notes: String?,
        invoice: Whopsdk::Models::PlanListResponse::Invoice?,
        member_count: Integer?,
        plan_type: Whopsdk::Models::plan_type,
        product: Whopsdk::Models::PlanListResponse::Product?,
        purchase_link: String,
        release_method: Whopsdk::Models::release_method,
        renewal_price: Float,
        trial_period_days: Integer?,
        updated_at: Integer,
        visibility: Whopsdk::Models::visibility
      ) -> void

      def to_hash: -> {
        id: String,
        billing_period: Integer?,
        company: Whopsdk::Models::PlanListResponse::Company?,
        created_at: Integer,
        currency: Whopsdk::Models::currency,
        description: String?,
        expiration_days: Integer?,
        initial_price: Float,
        internal_notes: String?,
        invoice: Whopsdk::Models::PlanListResponse::Invoice?,
        member_count: Integer?,
        plan_type: Whopsdk::Models::plan_type,
        product: Whopsdk::Models::PlanListResponse::Product?,
        purchase_link: String,
        release_method: Whopsdk::Models::release_method,
        renewal_price: Float,
        trial_period_days: Integer?,
        updated_at: Integer,
        visibility: Whopsdk::Models::visibility
      }

      type company = { id: String, title: String }

      class Company < Whopsdk::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor title: String

        def initialize: (id: String, title: String) -> void

        def to_hash: -> { id: String, title: String }
      end

      type invoice = { id: String }

      class Invoice < Whopsdk::Internal::Type::BaseModel
        attr_accessor id: String

        def initialize: (id: String) -> void

        def to_hash: -> { id: String }
      end

      type product = { id: String, title: String }

      class Product < Whopsdk::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor title: String

        def initialize: (id: String, title: String) -> void

        def to_hash: -> { id: String, title: String }
      end
    end
  end
end
