module Whopsdk
  module Models
    type product_list_params =
      {
        company_id: String,
        after: String?,
        before: String?,
        direction: Whopsdk::Models::ProductListParams::direction?,
        first: Integer?,
        last: Integer?,
        order: Whopsdk::Models::ProductListParams::order?,
        product_types: ::Array[Whopsdk::Models::ProductListParams::product_type?]?,
        visibilities: ::Array[Whopsdk::Models::ProductListParams::visibility?]?
      }
      & Whopsdk::Internal::Type::request_parameters

    class ProductListParams < Whopsdk::Internal::Type::BaseModel
      extend Whopsdk::Internal::Type::RequestParameters::Converter
      include Whopsdk::Internal::Type::RequestParameters

      attr_accessor company_id: String

      attr_accessor after: String?

      attr_accessor before: String?

      attr_accessor direction: Whopsdk::Models::ProductListParams::direction?

      attr_accessor first: Integer?

      attr_accessor last: Integer?

      attr_accessor order: Whopsdk::Models::ProductListParams::order?

      attr_accessor product_types: ::Array[Whopsdk::Models::ProductListParams::product_type?]?

      attr_accessor visibilities: ::Array[Whopsdk::Models::ProductListParams::visibility?]?

      def initialize: (
        company_id: String,
        ?after: String?,
        ?before: String?,
        ?direction: Whopsdk::Models::ProductListParams::direction?,
        ?first: Integer?,
        ?last: Integer?,
        ?order: Whopsdk::Models::ProductListParams::order?,
        ?product_types: ::Array[Whopsdk::Models::ProductListParams::product_type?]?,
        ?visibilities: ::Array[Whopsdk::Models::ProductListParams::visibility?]?,
        ?request_options: Whopsdk::request_opts
      ) -> void

      def to_hash: -> {
        company_id: String,
        after: String?,
        before: String?,
        direction: Whopsdk::Models::ProductListParams::direction?,
        first: Integer?,
        last: Integer?,
        order: Whopsdk::Models::ProductListParams::order?,
        product_types: ::Array[Whopsdk::Models::ProductListParams::product_type?]?,
        visibilities: ::Array[Whopsdk::Models::ProductListParams::visibility?]?,
        request_options: Whopsdk::RequestOptions
      }

      type direction = :asc | :desc

      module Direction
        extend Whopsdk::Internal::Type::Enum

        ASC: :asc
        DESC: :desc

        def self?.values: -> ::Array[Whopsdk::Models::ProductListParams::direction]
      end

      type order =
        :active_memberships_count | :created_at | :usd_gmv | :usd_gmv_30_days

      module Order
        extend Whopsdk::Internal::Type::Enum

        ACTIVE_MEMBERSHIPS_COUNT: :active_memberships_count
        CREATED_AT: :created_at
        USD_GMV: :usd_gmv
        USD_GMV_30_DAYS: :usd_gmv_30_days

        def self?.values: -> ::Array[Whopsdk::Models::ProductListParams::order]
      end

      type product_type = :regular | :app | :experience_upsell | :api_only

      module ProductType
        extend Whopsdk::Internal::Type::Enum

        REGULAR: :regular
        APP: :app
        EXPERIENCE_UPSELL: :experience_upsell
        API_ONLY: :api_only

        def self?.values: -> ::Array[Whopsdk::Models::ProductListParams::product_type]
      end

      type visibility =
        :visible
        | :hidden
        | :archived
        | :quick_link
        | :all
        | :not_quick_link
        | :not_archived

      module Visibility
        extend Whopsdk::Internal::Type::Enum

        VISIBLE: :visible
        HIDDEN: :hidden
        ARCHIVED: :archived
        QUICK_LINK: :quick_link
        ALL: :all
        NOT_QUICK_LINK: :not_quick_link
        NOT_ARCHIVED: :not_archived

        def self?.values: -> ::Array[Whopsdk::Models::ProductListParams::visibility]
      end
    end
  end
end
