module Whopsdk
  module Models
    type product_create_params =
      {
        company_id: String,
        title: String,
        access_pass_type: Whopsdk::Models::access_pass_type?,
        banner_image: Whopsdk::ProductCreateParams::BannerImage?,
        business_type: Whopsdk::Models::business_types?,
        custom_cta: Whopsdk::Models::custom_cta?,
        custom_cta_url: String?,
        custom_statement_descriptor: String?,
        description: String?,
        experience_ids: ::Array[String]?,
        global_affiliate_percentage: Float?,
        global_affiliate_status: Whopsdk::Models::global_affiliate_status?,
        headline: String?,
        industry_type: Whopsdk::Models::industry_types?,
        member_affiliate_percentage: Float?,
        member_affiliate_status: Whopsdk::Models::global_affiliate_status?,
        plan_options: Whopsdk::ProductCreateParams::PlanOptions?,
        product_highlights: ::Array[Whopsdk::ProductCreateParams::ProductHighlight]?,
        product_tax_code_id: String?,
        redirect_purchase_url: String?,
        route: String?,
        visibility: Whopsdk::Models::visibility?
      }
      & Whopsdk::Internal::Type::request_parameters

    class ProductCreateParams < Whopsdk::Internal::Type::BaseModel
      extend Whopsdk::Internal::Type::RequestParameters::Converter
      include Whopsdk::Internal::Type::RequestParameters

      attr_accessor company_id: String

      attr_accessor title: String

      attr_accessor access_pass_type: Whopsdk::Models::access_pass_type?

      attr_accessor banner_image: Whopsdk::ProductCreateParams::BannerImage?

      attr_accessor business_type: Whopsdk::Models::business_types?

      attr_accessor custom_cta: Whopsdk::Models::custom_cta?

      attr_accessor custom_cta_url: String?

      attr_accessor custom_statement_descriptor: String?

      attr_accessor description: String?

      attr_accessor experience_ids: ::Array[String]?

      attr_accessor global_affiliate_percentage: Float?

      attr_accessor global_affiliate_status: Whopsdk::Models::global_affiliate_status?

      attr_accessor headline: String?

      attr_accessor industry_type: Whopsdk::Models::industry_types?

      attr_accessor member_affiliate_percentage: Float?

      attr_accessor member_affiliate_status: Whopsdk::Models::global_affiliate_status?

      attr_accessor plan_options: Whopsdk::ProductCreateParams::PlanOptions?

      attr_accessor product_highlights: ::Array[Whopsdk::ProductCreateParams::ProductHighlight]?

      attr_accessor product_tax_code_id: String?

      attr_accessor redirect_purchase_url: String?

      attr_accessor route: String?

      attr_accessor visibility: Whopsdk::Models::visibility?

      def initialize: (
        company_id: String,
        title: String,
        ?access_pass_type: Whopsdk::Models::access_pass_type?,
        ?banner_image: Whopsdk::ProductCreateParams::BannerImage?,
        ?business_type: Whopsdk::Models::business_types?,
        ?custom_cta: Whopsdk::Models::custom_cta?,
        ?custom_cta_url: String?,
        ?custom_statement_descriptor: String?,
        ?description: String?,
        ?experience_ids: ::Array[String]?,
        ?global_affiliate_percentage: Float?,
        ?global_affiliate_status: Whopsdk::Models::global_affiliate_status?,
        ?headline: String?,
        ?industry_type: Whopsdk::Models::industry_types?,
        ?member_affiliate_percentage: Float?,
        ?member_affiliate_status: Whopsdk::Models::global_affiliate_status?,
        ?plan_options: Whopsdk::ProductCreateParams::PlanOptions?,
        ?product_highlights: ::Array[Whopsdk::ProductCreateParams::ProductHighlight]?,
        ?product_tax_code_id: String?,
        ?redirect_purchase_url: String?,
        ?route: String?,
        ?visibility: Whopsdk::Models::visibility?,
        ?request_options: Whopsdk::request_opts
      ) -> void

      def to_hash: -> {
        company_id: String,
        title: String,
        access_pass_type: Whopsdk::Models::access_pass_type?,
        banner_image: Whopsdk::ProductCreateParams::BannerImage?,
        business_type: Whopsdk::Models::business_types?,
        custom_cta: Whopsdk::Models::custom_cta?,
        custom_cta_url: String?,
        custom_statement_descriptor: String?,
        description: String?,
        experience_ids: ::Array[String]?,
        global_affiliate_percentage: Float?,
        global_affiliate_status: Whopsdk::Models::global_affiliate_status?,
        headline: String?,
        industry_type: Whopsdk::Models::industry_types?,
        member_affiliate_percentage: Float?,
        member_affiliate_status: Whopsdk::Models::global_affiliate_status?,
        plan_options: Whopsdk::ProductCreateParams::PlanOptions?,
        product_highlights: ::Array[Whopsdk::ProductCreateParams::ProductHighlight]?,
        product_tax_code_id: String?,
        redirect_purchase_url: String?,
        route: String?,
        visibility: Whopsdk::Models::visibility?,
        request_options: Whopsdk::RequestOptions
      }

      type banner_image = { id: String?, direct_upload_id: String? }

      class BannerImage < Whopsdk::Internal::Type::BaseModel
        attr_accessor id: String?

        attr_accessor direct_upload_id: String?

        def initialize: (?id: String?, ?direct_upload_id: String?) -> void

        def to_hash: -> { id: String?, direct_upload_id: String? }
      end

      type plan_options =
        {
          base_currency: Whopsdk::Models::currency?,
          billing_period: Integer?,
          custom_fields: ::Array[Whopsdk::ProductCreateParams::PlanOptions::CustomField]?,
          initial_price: Float?,
          plan_type: Whopsdk::Models::plan_type?,
          release_method: Whopsdk::Models::release_method?,
          renewal_price: Float?,
          visibility: Whopsdk::Models::visibility?
        }

      class PlanOptions < Whopsdk::Internal::Type::BaseModel
        attr_accessor base_currency: Whopsdk::Models::currency?

        attr_accessor billing_period: Integer?

        attr_accessor custom_fields: ::Array[Whopsdk::ProductCreateParams::PlanOptions::CustomField]?

        attr_accessor initial_price: Float?

        attr_accessor plan_type: Whopsdk::Models::plan_type?

        attr_accessor release_method: Whopsdk::Models::release_method?

        attr_accessor renewal_price: Float?

        attr_accessor visibility: Whopsdk::Models::visibility?

        def initialize: (
          ?base_currency: Whopsdk::Models::currency?,
          ?billing_period: Integer?,
          ?custom_fields: ::Array[Whopsdk::ProductCreateParams::PlanOptions::CustomField]?,
          ?initial_price: Float?,
          ?plan_type: Whopsdk::Models::plan_type?,
          ?release_method: Whopsdk::Models::release_method?,
          ?renewal_price: Float?,
          ?visibility: Whopsdk::Models::visibility?
        ) -> void

        def to_hash: -> {
          base_currency: Whopsdk::Models::currency?,
          billing_period: Integer?,
          custom_fields: ::Array[Whopsdk::ProductCreateParams::PlanOptions::CustomField]?,
          initial_price: Float?,
          plan_type: Whopsdk::Models::plan_type?,
          release_method: Whopsdk::Models::release_method?,
          renewal_price: Float?,
          visibility: Whopsdk::Models::visibility?
        }

        type custom_field =
          {
            field_type: Whopsdk::Models::ProductCreateParams::PlanOptions::CustomField::field_type?,
            name: String,
            id: String?,
            order: Integer?,
            placeholder: String?,
            required: bool?
          }

        class CustomField < Whopsdk::Internal::Type::BaseModel
          attr_accessor field_type: Whopsdk::Models::ProductCreateParams::PlanOptions::CustomField::field_type?

          attr_accessor name: String

          attr_accessor id: String?

          attr_accessor order: Integer?

          attr_accessor placeholder: String?

          attr_accessor required: bool?

          def initialize: (
            field_type: Whopsdk::Models::ProductCreateParams::PlanOptions::CustomField::field_type?,
            name: String,
            ?id: String?,
            ?order: Integer?,
            ?placeholder: String?,
            ?required: bool?
          ) -> void

          def to_hash: -> {
            field_type: Whopsdk::Models::ProductCreateParams::PlanOptions::CustomField::field_type?,
            name: String,
            id: String?,
            order: Integer?,
            placeholder: String?,
            required: bool?
          }

          type field_type = :text

          module FieldType
            extend Whopsdk::Internal::Type::Enum

            TEXT: :text

            def self?.values: -> ::Array[Whopsdk::Models::ProductCreateParams::PlanOptions::CustomField::field_type]
          end
        end
      end

      type product_highlight =
        {
          content: String,
          highlight_type: Whopsdk::Models::ProductCreateParams::ProductHighlight::highlight_type?,
          title: String?
        }

      class ProductHighlight < Whopsdk::Internal::Type::BaseModel
        attr_accessor content: String

        attr_accessor highlight_type: Whopsdk::Models::ProductCreateParams::ProductHighlight::highlight_type?

        attr_accessor title: String?

        def initialize: (
          content: String,
          highlight_type: Whopsdk::Models::ProductCreateParams::ProductHighlight::highlight_type?,
          ?title: String?
        ) -> void

        def to_hash: -> {
          content: String,
          highlight_type: Whopsdk::Models::ProductCreateParams::ProductHighlight::highlight_type?,
          title: String?
        }

        type highlight_type =
          :qualification | :benefit | :who_this_is_for | :pricing_feature

        module HighlightType
          extend Whopsdk::Internal::Type::Enum

          QUALIFICATION: :qualification
          BENEFIT: :benefit
          WHO_THIS_IS_FOR: :who_this_is_for
          PRICING_FEATURE: :pricing_feature

          def self?.values: -> ::Array[Whopsdk::Models::ProductCreateParams::ProductHighlight::highlight_type]
        end
      end
    end
  end
end
