module Whopsdk
  module Models
    type promo_type = :percentage | :flat_amount

    module PromoType
      extend Whopsdk::Internal::Type::Enum

      PERCENTAGE: :percentage
      FLAT_AMOUNT: :flat_amount

      def self?.values: -> ::Array[Whopsdk::Models::promo_type]
    end
  end
end
