module Whopsdk
  module Models
    type reaction_list_params =
      {
        resource_id: String,
        after: String?,
        before: String?,
        first: Integer?,
        last: Integer?
      }
      & Whopsdk::Internal::Type::request_parameters

    class ReactionListParams < Whopsdk::Internal::Type::BaseModel
      extend Whopsdk::Internal::Type::RequestParameters::Converter
      include Whopsdk::Internal::Type::RequestParameters

      attr_accessor resource_id: String

      attr_accessor after: String?

      attr_accessor before: String?

      attr_accessor first: Integer?

      attr_accessor last: Integer?

      def initialize: (
        resource_id: String,
        ?after: String?,
        ?before: String?,
        ?first: Integer?,
        ?last: Integer?,
        ?request_options: Whopsdk::request_opts
      ) -> void

      def to_hash: -> {
        resource_id: String,
        after: String?,
        before: String?,
        first: Integer?,
        last: Integer?,
        request_options: Whopsdk::RequestOptions
      }
    end
  end
end
