module Whopsdk
  module Models
    type release_method = :buy_now | :waitlist

    module ReleaseMethod
      extend Whopsdk::Internal::Type::Enum

      BUY_NOW: :buy_now
      WAITLIST: :waitlist

      def self?.values: -> ::Array[Whopsdk::Models::release_method]
    end
  end
end
