module Whopsdk
  module Models
    type support_channel_retrieve_params =
      {  } & Whopsdk::Internal::Type::request_parameters

    class SupportChannelRetrieveParams < Whopsdk::Internal::Type::BaseModel
      extend Whopsdk::Internal::Type::RequestParameters::Converter
      include Whopsdk::Internal::Type::RequestParameters

      def initialize: (?request_options: Whopsdk::request_opts) -> void

      def to_hash: -> { request_options: Whopsdk::RequestOptions }
    end
  end
end
