module Whopsdk
  module Models
    type transfer =
      {
        id: String,
        amount: Float,
        created_at: Time,
        currency: Whopsdk::Models::currency,
        destination: Whopsdk::Models::Transfer::destination?,
        destination_ledger_account_id: String,
        fee_amount: Float?,
        notes: String?,
        origin: Whopsdk::Models::Transfer::origin?,
        origin_ledger_account_id: String
      }

    class Transfer < Whopsdk::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor amount: Float

      attr_accessor created_at: Time

      attr_accessor currency: Whopsdk::Models::currency

      attr_accessor destination: Whopsdk::Models::Transfer::destination?

      attr_accessor destination_ledger_account_id: String

      attr_accessor fee_amount: Float?

      attr_accessor notes: String?

      attr_accessor origin: Whopsdk::Models::Transfer::origin?

      attr_accessor origin_ledger_account_id: String

      def initialize: (
        id: String,
        amount: Float,
        created_at: Time,
        currency: Whopsdk::Models::currency,
        destination: Whopsdk::Models::Transfer::destination?,
        destination_ledger_account_id: String,
        fee_amount: Float?,
        notes: String?,
        origin: Whopsdk::Models::Transfer::origin?,
        origin_ledger_account_id: String
      ) -> void

      def to_hash: -> {
        id: String,
        amount: Float,
        created_at: Time,
        currency: Whopsdk::Models::currency,
        destination: Whopsdk::Models::Transfer::destination?,
        destination_ledger_account_id: String,
        fee_amount: Float?,
        notes: String?,
        origin: Whopsdk::Models::Transfer::origin?,
        origin_ledger_account_id: String
      }

      type destination =
        (Whopsdk::Transfer::Destination::User
        | Whopsdk::Transfer::Destination::Company)?

      module Destination
        extend Whopsdk::Internal::Type::Union

        type user =
          { id: String, name: String?, typename: :User, username: String }

        class User < Whopsdk::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor name: String?

          attr_accessor typename: :User

          attr_accessor username: String

          def initialize: (
            id: String,
            name: String?,
            username: String,
            ?typename: :User
          ) -> void

          def to_hash: -> {
            id: String,
            name: String?,
            typename: :User,
            username: String
          }
        end

        type company =
          { id: String, route: String, title: String, typename: :Company }

        class Company < Whopsdk::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor route: String

          attr_accessor title: String

          attr_accessor typename: :Company

          def initialize: (
            id: String,
            route: String,
            title: String,
            ?typename: :Company
          ) -> void

          def to_hash: -> {
            id: String,
            route: String,
            title: String,
            typename: :Company
          }
        end

        def self?.variants: -> ::Array[Whopsdk::Models::Transfer::destination]
      end

      type origin =
        (Whopsdk::Transfer::Origin::User | Whopsdk::Transfer::Origin::Company)?

      module Origin
        extend Whopsdk::Internal::Type::Union

        type user =
          { id: String, name: String?, typename: :User, username: String }

        class User < Whopsdk::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor name: String?

          attr_accessor typename: :User

          attr_accessor username: String

          def initialize: (
            id: String,
            name: String?,
            username: String,
            ?typename: :User
          ) -> void

          def to_hash: -> {
            id: String,
            name: String?,
            typename: :User,
            username: String
          }
        end

        type company =
          { id: String, route: String, title: String, typename: :Company }

        class Company < Whopsdk::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor route: String

          attr_accessor title: String

          attr_accessor typename: :Company

          def initialize: (
            id: String,
            route: String,
            title: String,
            ?typename: :Company
          ) -> void

          def to_hash: -> {
            id: String,
            route: String,
            title: String,
            typename: :Company
          }
        end

        def self?.variants: -> ::Array[Whopsdk::Models::Transfer::origin]
      end
    end
  end
end
