module Whopsdk
  module Models
    type unwrap_webhook_event =
      Whopsdk::InvoiceCreatedWebhookEvent
      | Whopsdk::InvoicePaidWebhookEvent
      | Whopsdk::InvoicePastDueWebhookEvent
      | Whopsdk::InvoiceVoidedWebhookEvent

    module UnwrapWebhookEvent
      extend Whopsdk::Internal::Type::Union

      def self?.variants: -> ::Array[Whopsdk::Models::unwrap_webhook_event]
    end
  end
end
