module Whopsdk
  module Models
    type user_check_access_params =
      { id: String } & Whopsdk::Internal::Type::request_parameters

    class UserCheckAccessParams < Whopsdk::Internal::Type::BaseModel
      extend Whopsdk::Internal::Type::RequestParameters::Converter
      include Whopsdk::Internal::Type::RequestParameters

      attr_accessor id: String

      def initialize: (
        id: String,
        ?request_options: Whopsdk::request_opts
      ) -> void

      def to_hash: -> { id: String, request_options: Whopsdk::RequestOptions }
    end
  end
end
