module WhopSDK
  module Models
    module AffiliateOverrideRoles = Affiliates::AffiliateOverrideRoles

    module Affiliates
      type affiliate_override_roles = :standard | :rev_share

      module AffiliateOverrideRoles
        extend WhopSDK::Internal::Type::Enum

        STANDARD: :standard
        REV_SHARE: :rev_share

        def self?.values: -> ::Array[WhopSDK::Models::Affiliates::affiliate_override_roles]
      end
    end
  end
end
