module WhopSDK
  module Models
    module Affiliates
      type override_list_params =
        {
          id: String,
          after: String,
          before: String,
          first: Integer,
          last: Integer,
          override_type: WhopSDK::Models::Affiliates::affiliate_override_roles
        }
        & WhopSDK::Internal::Type::request_parameters

      class OverrideListParams < WhopSDK::Internal::Type::BaseModel
        extend WhopSDK::Internal::Type::RequestParameters::Converter
        include WhopSDK::Internal::Type::RequestParameters

        attr_accessor id: String

        attr_reader after: String?

        def after=: (String) -> String

        attr_reader before: String?

        def before=: (String) -> String

        attr_reader first: Integer?

        def first=: (Integer) -> Integer

        attr_reader last: Integer?

        def last=: (Integer) -> Integer

        attr_reader override_type: WhopSDK::Models::Affiliates::affiliate_override_roles?

        def override_type=: (
          WhopSDK::Models::Affiliates::affiliate_override_roles
        ) -> WhopSDK::Models::Affiliates::affiliate_override_roles

        def initialize: (
          id: String,
          ?after: String,
          ?before: String,
          ?first: Integer,
          ?last: Integer,
          ?override_type: WhopSDK::Models::Affiliates::affiliate_override_roles,
          ?request_options: WhopSDK::request_opts
        ) -> void

        def to_hash: -> {
          id: String,
          after: String,
          before: String,
          first: Integer,
          last: Integer,
          override_type: WhopSDK::Models::Affiliates::affiliate_override_roles,
          request_options: WhopSDK::RequestOptions
        }
      end
    end
  end
end
