# frozen_string_literal: true

module Whop_sdk
  module Payments
    module Types
      # Autogenerated input type of CreatePayment
      class CreatePaymentsRequestThree < Internal::Types::Model
        field :company_id, -> { String }, optional: false, nullable: false

        field :email, -> { String }, optional: true, nullable: false

        field :member_id, -> { String }, optional: false, nullable: false

        field :metadata, -> { Internal::Types::Hash[String, Object] }, optional: true, nullable: false

        field :payment_method_id, -> { String }, optional: true, nullable: false

        field :plan_id, -> { String }, optional: false, nullable: false

        field :promo_code_id, -> { String }, optional: true, nullable: false

        field :return_url, -> { String }, optional: true, nullable: false
      end
    end
  end
end
