# frozen_string_literal: true

module Whopsdk
  module Models
    # @see Whopsdk::Resources::Invoices#create
    class InvoiceCreateResponse < Whopsdk::Internal::Type::BaseModel
      # @!attribute checkout_job_id
      #   The ID of the checkout job that was created for this invoice.
      #
      #   @return [String, nil]
      required :checkout_job_id, String, nil?: true

      # @!attribute invoice
      #   A statement that defines an amount due by a customer.
      #
      #   @return [Whopsdk::Models::Invoice, nil]
      required :invoice, -> { Whopsdk::Invoice }, nil?: true

      # @!method initialize(checkout_job_id:, invoice:)
      #   Autogenerated return type of CreateInvoice.
      #
      #   @param checkout_job_id [String, nil] The ID of the checkout job that was created for this invoice.
      #
      #   @param invoice [Whopsdk::Models::Invoice, nil] A statement that defines an amount due by a customer.
    end
  end
end
