# frozen_string_literal: true

module Whopsdk
  module Models
    # @see Whopsdk::Resources::Invoices#create
    class InvoiceCreateResponse < Whopsdk::Internal::Type::BaseModel
      # @!attribute checkout_job_id
      #   The ID of the checkout job that was created for this invoice.
      #
      #   @return [String, nil]
      required :checkout_job_id, String, nil?: true

      # @!attribute invoice
      #   A statement that defines an amount due by a customer.
      #
      #   @return [Whopsdk::Models::InvoiceCreateResponse::Invoice, nil]
      required :invoice, -> { Whopsdk::Models::InvoiceCreateResponse::Invoice }, nil?: true

      # @!method initialize(checkout_job_id:, invoice:)
      #   Autogenerated return type of CreateInvoice.
      #
      #   @param checkout_job_id [String, nil] The ID of the checkout job that was created for this invoice.
      #
      #   @param invoice [Whopsdk::Models::InvoiceCreateResponse::Invoice, nil] A statement that defines an amount due by a customer.

      # @see Whopsdk::Models::InvoiceCreateResponse#invoice
      class Invoice < Whopsdk::Internal::Type::BaseModel
        # @!attribute id
        #   The ID of the invoice.
        #
        #   @return [String]
        required :id, String

        # @!attribute created_at
        #   The date the invoice was created.
        #
        #   @return [Integer]
        required :created_at, Integer

        # @!attribute current_plan
        #   The plan that the invoice was created for.
        #
        #   @return [Whopsdk::Models::InvoiceCreateResponse::Invoice::CurrentPlan]
        required :current_plan, -> { Whopsdk::Models::InvoiceCreateResponse::Invoice::CurrentPlan }

        # @!attribute due_date
        #   The date the invoice is due.
        #
        #   @return [Integer, nil]
        required :due_date, Integer, nil?: true

        # @!attribute email_address
        #   The email address that the invoice was created for.
        #
        #   @return [String, nil]
        required :email_address, String, nil?: true

        # @!attribute fetch_invoice_token
        #   The token to fetch the invoice.
        #
        #   @return [String]
        required :fetch_invoice_token, String

        # @!attribute number
        #   The number of the invoice.
        #
        #   @return [String]
        required :number, String

        # @!attribute status
        #   The status of the invoice.
        #
        #   @return [Symbol, Whopsdk::Models::InvoiceCreateResponse::Invoice::Status, nil]
        required :status, enum: -> { Whopsdk::Models::InvoiceCreateResponse::Invoice::Status }, nil?: true

        # @!attribute user
        #   The user that the invoice was created for.
        #
        #   @return [Whopsdk::Models::InvoiceCreateResponse::Invoice::User, nil]
        required :user, -> { Whopsdk::Models::InvoiceCreateResponse::Invoice::User }, nil?: true

        # @!method initialize(id:, created_at:, current_plan:, due_date:, email_address:, fetch_invoice_token:, number:, status:, user:)
        #   A statement that defines an amount due by a customer.
        #
        #   @param id [String] The ID of the invoice.
        #
        #   @param created_at [Integer] The date the invoice was created.
        #
        #   @param current_plan [Whopsdk::Models::InvoiceCreateResponse::Invoice::CurrentPlan] The plan that the invoice was created for.
        #
        #   @param due_date [Integer, nil] The date the invoice is due.
        #
        #   @param email_address [String, nil] The email address that the invoice was created for.
        #
        #   @param fetch_invoice_token [String] The token to fetch the invoice.
        #
        #   @param number [String] The number of the invoice.
        #
        #   @param status [Symbol, Whopsdk::Models::InvoiceCreateResponse::Invoice::Status, nil] The status of the invoice.
        #
        #   @param user [Whopsdk::Models::InvoiceCreateResponse::Invoice::User, nil] The user that the invoice was created for.

        # @see Whopsdk::Models::InvoiceCreateResponse::Invoice#current_plan
        class CurrentPlan < Whopsdk::Internal::Type::BaseModel
          # @!attribute id
          #   The internal ID of the plan.
          #
          #   @return [String]
          required :id, String

          # @!attribute currency
          #   The respective currency identifier for the plan.
          #
          #   @return [Symbol, Whopsdk::Models::InvoiceCreateResponse::Invoice::CurrentPlan::Currency, nil]
          required :currency,
                   enum: -> { Whopsdk::Models::InvoiceCreateResponse::Invoice::CurrentPlan::Currency },
                   nil?: true

          # @!attribute formatted_price
          #   The formatted price (including currency) for the plan.
          #
          #   @return [String]
          required :formatted_price, String

          # @!method initialize(id:, currency:, formatted_price:)
          #   The plan that the invoice was created for.
          #
          #   @param id [String] The internal ID of the plan.
          #
          #   @param currency [Symbol, Whopsdk::Models::InvoiceCreateResponse::Invoice::CurrentPlan::Currency, nil] The respective currency identifier for the plan.
          #
          #   @param formatted_price [String] The formatted price (including currency) for the plan.

          # The respective currency identifier for the plan.
          #
          # @see Whopsdk::Models::InvoiceCreateResponse::Invoice::CurrentPlan#currency
          module Currency
            extend Whopsdk::Internal::Type::Enum

            USD = :usd
            SGD = :sgd
            INR = :inr
            AUD = :aud
            BRL = :brl
            CAD = :cad
            DKK = :dkk
            EUR = :eur
            NOK = :nok
            GBP = :gbp
            SEK = :sek
            CHF = :chf
            HKD = :hkd
            HUF = :huf
            JPY = :jpy
            MXN = :mxn
            MYR = :myr
            PLN = :pln
            CZK = :czk
            NZD = :nzd
            AED = :aed
            ETH = :eth
            APE = :ape
            COP = :cop
            RON = :ron
            THB = :thb
            BGN = :bgn
            IDR = :idr
            DOP = :dop
            PHP = :php
            TRY = :try
            KRW = :krw
            TWD = :twd
            VND = :vnd
            PKR = :pkr
            CLP = :clp
            UYU = :uyu
            ARS = :ars
            ZAR = :zar
            DZD = :dzd
            TND = :tnd
            MAD = :mad
            KES = :kes
            KWD = :kwd
            JOD = :jod
            ALL = :all
            XCD = :xcd
            AMD = :amd
            BSD = :bsd
            BHD = :bhd
            BOB = :bob
            BAM = :bam
            KHR = :khr
            CRC = :crc
            XOF = :xof
            EGP = :egp
            ETB = :etb
            GMD = :gmd
            GHS = :ghs
            GTQ = :gtq
            GYD = :gyd
            ILS = :ils
            JMD = :jmd
            MOP = :mop
            MGA = :mga
            MUR = :mur
            MDL = :mdl
            MNT = :mnt
            NAD = :nad
            NGN = :ngn
            MKD = :mkd
            OMR = :omr
            PYG = :pyg
            PEN = :pen
            QAR = :qar
            RWF = :rwf
            SAR = :sar
            RSD = :rsd
            LKR = :lkr
            TZS = :tzs
            TTD = :ttd
            UZS = :uzs
            RUB = :rub
            BTC = :btc

            # @!method self.values
            #   @return [Array<Symbol>]
          end
        end

        # The status of the invoice.
        #
        # @see Whopsdk::Models::InvoiceCreateResponse::Invoice#status
        module Status
          extend Whopsdk::Internal::Type::Enum

          OPEN = :open
          PAID = :paid
          PAST_DUE = :past_due
          VOID = :void

          # @!method self.values
          #   @return [Array<Symbol>]
        end

        # @see Whopsdk::Models::InvoiceCreateResponse::Invoice#user
        class User < Whopsdk::Internal::Type::BaseModel
          # @!attribute id
          #   The internal ID of the user.
          #
          #   @return [String]
          required :id, String

          # @!attribute name
          #   The name of the user from their Whop account.
          #
          #   @return [String, nil]
          required :name, String, nil?: true

          # @!attribute username
          #   The username of the user from their Whop account.
          #
          #   @return [String]
          required :username, String

          # @!method initialize(id:, name:, username:)
          #   The user that the invoice was created for.
          #
          #   @param id [String] The internal ID of the user.
          #
          #   @param name [String, nil] The name of the user from their Whop account.
          #
          #   @param username [String] The username of the user from their Whop account.
        end
      end
    end
  end
end
