# frozen_string_literal: true

module Whopsdk
  module Models
    # @see Whopsdk::Resources::Products#create
    class ProductCreateParams < Whopsdk::Internal::Type::BaseModel
      extend Whopsdk::Internal::Type::RequestParameters::Converter
      include Whopsdk::Internal::Type::RequestParameters

      # @!attribute company_id
      #   The ID of the company to create the access pass for.
      #
      #   @return [String]
      required :company_id, String

      # @!attribute title
      #   The title of the access pass.
      #
      #   @return [String]
      required :title, String

      # @!attribute access_pass_type
      #   The different types an access pass can be.
      #
      #   @return [Symbol, Whopsdk::Models::AccessPassType, nil]
      optional :access_pass_type, enum: -> { Whopsdk::AccessPassType }, nil?: true

      # @!attribute banner_image
      #   A banner image for the access pass in png, jpeg format
      #
      #   @return [Whopsdk::Models::ProductCreateParams::BannerImage, nil]
      optional :banner_image, -> { Whopsdk::ProductCreateParams::BannerImage }, nil?: true

      # @!attribute business_type
      #   The different business types a company can be.
      #
      #   @return [Symbol, Whopsdk::Models::BusinessTypes, nil]
      optional :business_type, enum: -> { Whopsdk::BusinessTypes }, nil?: true

      # @!attribute collect_shipping_address
      #   Whether or not to collect shipping information at checkout from the customer.
      #
      #   @return [Boolean, nil]
      optional :collect_shipping_address, Whopsdk::Internal::Type::Boolean, nil?: true

      # @!attribute custom_cta
      #   The different types of custom CTAs that can be selected.
      #
      #   @return [Symbol, Whopsdk::Models::CustomCta, nil]
      optional :custom_cta, enum: -> { Whopsdk::CustomCta }, nil?: true

      # @!attribute custom_cta_url
      #   The custom call to action URL for the access pass.
      #
      #   @return [String, nil]
      optional :custom_cta_url, String, nil?: true

      # @!attribute custom_statement_descriptor
      #   The custom statement descriptor for the access pass i.e. WHOP\*SPORTS, must be
      #   between 5 and 22 characters, contain at least one letter, and not contain any of
      #   the following characters: <, >, \, ', "
      #
      #   @return [String, nil]
      optional :custom_statement_descriptor, String, nil?: true

      # @!attribute description
      #   A written description of the access pass.
      #
      #   @return [String, nil]
      optional :description, String, nil?: true

      # @!attribute experience_ids
      #   An array of experience IDs that this pass has
      #
      #   @return [Array<String>, nil]
      optional :experience_ids, Whopsdk::Internal::Type::ArrayOf[String], nil?: true

      # @!attribute global_affiliate_percentage
      #   The percentage of the revenue that goes to the global affiliate program.
      #
      #   @return [Float, nil]
      optional :global_affiliate_percentage, Float, nil?: true

      # @!attribute global_affiliate_status
      #   The different statuses of the global affiliate program for an access pass.
      #
      #   @return [Symbol, Whopsdk::Models::GlobalAffiliateStatus, nil]
      optional :global_affiliate_status, enum: -> { Whopsdk::GlobalAffiliateStatus }, nil?: true

      # @!attribute headline
      #   The headline of the access pass.
      #
      #   @return [String, nil]
      optional :headline, String, nil?: true

      # @!attribute industry_type
      #   The different industry types a company can be in.
      #
      #   @return [Symbol, Whopsdk::Models::IndustryTypes, nil]
      optional :industry_type, enum: -> { Whopsdk::IndustryTypes }, nil?: true

      # @!attribute member_affiliate_percentage
      #   The percentage of the revenue that goes to the member affiliate program.
      #
      #   @return [Float, nil]
      optional :member_affiliate_percentage, Float, nil?: true

      # @!attribute member_affiliate_status
      #   The different statuses of the global affiliate program for an access pass.
      #
      #   @return [Symbol, Whopsdk::Models::GlobalAffiliateStatus, nil]
      optional :member_affiliate_status, enum: -> { Whopsdk::GlobalAffiliateStatus }, nil?: true

      # @!attribute plan_options
      #   The details to assign an autogenerated plan.
      #
      #   @return [Whopsdk::Models::ProductCreateParams::PlanOptions, nil]
      optional :plan_options, -> { Whopsdk::ProductCreateParams::PlanOptions }, nil?: true

      # @!attribute product_highlights
      #   The product highlights for the access pass.
      #
      #   @return [Array<Whopsdk::Models::ProductCreateParams::ProductHighlight>, nil]
      optional :product_highlights,
               -> { Whopsdk::Internal::Type::ArrayOf[Whopsdk::ProductCreateParams::ProductHighlight] },
               nil?: true

      # @!attribute product_tax_code_id
      #   The ID of the product tax code to apply to this access pass.
      #
      #   @return [String, nil]
      optional :product_tax_code_id, String, nil?: true

      # @!attribute redirect_purchase_url
      #   The URL to redirect the customer to after a purchase.
      #
      #   @return [String, nil]
      optional :redirect_purchase_url, String, nil?: true

      # @!attribute route
      #   The route of the access pass.
      #
      #   @return [String, nil]
      optional :route, String, nil?: true

      # @!attribute visibility
      #   Visibility of a resource
      #
      #   @return [Symbol, Whopsdk::Models::Visibility, nil]
      optional :visibility, enum: -> { Whopsdk::Visibility }, nil?: true

      # @!method initialize(company_id:, title:, access_pass_type: nil, banner_image: nil, business_type: nil, collect_shipping_address: nil, custom_cta: nil, custom_cta_url: nil, custom_statement_descriptor: nil, description: nil, experience_ids: nil, global_affiliate_percentage: nil, global_affiliate_status: nil, headline: nil, industry_type: nil, member_affiliate_percentage: nil, member_affiliate_status: nil, plan_options: nil, product_highlights: nil, product_tax_code_id: nil, redirect_purchase_url: nil, route: nil, visibility: nil, request_options: {})
      #   Some parameter documentations has been truncated, see
      #   {Whopsdk::Models::ProductCreateParams} for more details.
      #
      #   @param company_id [String] The ID of the company to create the access pass for.
      #
      #   @param title [String] The title of the access pass.
      #
      #   @param access_pass_type [Symbol, Whopsdk::Models::AccessPassType, nil] The different types an access pass can be.
      #
      #   @param banner_image [Whopsdk::Models::ProductCreateParams::BannerImage, nil] A banner image for the access pass in png, jpeg format
      #
      #   @param business_type [Symbol, Whopsdk::Models::BusinessTypes, nil] The different business types a company can be.
      #
      #   @param collect_shipping_address [Boolean, nil] Whether or not to collect shipping information at checkout from the customer.
      #
      #   @param custom_cta [Symbol, Whopsdk::Models::CustomCta, nil] The different types of custom CTAs that can be selected.
      #
      #   @param custom_cta_url [String, nil] The custom call to action URL for the access pass.
      #
      #   @param custom_statement_descriptor [String, nil] The custom statement descriptor for the access pass i.e. WHOP\*SPORTS, must be
      #   be
      #
      #   @param description [String, nil] A written description of the access pass.
      #
      #   @param experience_ids [Array<String>, nil] An array of experience IDs that this pass has
      #
      #   @param global_affiliate_percentage [Float, nil] The percentage of the revenue that goes to the global affiliate program.
      #
      #   @param global_affiliate_status [Symbol, Whopsdk::Models::GlobalAffiliateStatus, nil] The different statuses of the global affiliate program for an access pass.
      #
      #   @param headline [String, nil] The headline of the access pass.
      #
      #   @param industry_type [Symbol, Whopsdk::Models::IndustryTypes, nil] The different industry types a company can be in.
      #
      #   @param member_affiliate_percentage [Float, nil] The percentage of the revenue that goes to the member affiliate program.
      #
      #   @param member_affiliate_status [Symbol, Whopsdk::Models::GlobalAffiliateStatus, nil] The different statuses of the global affiliate program for an access pass.
      #
      #   @param plan_options [Whopsdk::Models::ProductCreateParams::PlanOptions, nil] The details to assign an autogenerated plan.
      #
      #   @param product_highlights [Array<Whopsdk::Models::ProductCreateParams::ProductHighlight>, nil] The product highlights for the access pass.
      #
      #   @param product_tax_code_id [String, nil] The ID of the product tax code to apply to this access pass.
      #
      #   @param redirect_purchase_url [String, nil] The URL to redirect the customer to after a purchase.
      #
      #   @param route [String, nil] The route of the access pass.
      #
      #   @param visibility [Symbol, Whopsdk::Models::Visibility, nil] Visibility of a resource
      #
      #   @param request_options [Whopsdk::RequestOptions, Hash{Symbol=>Object}]

      class BannerImage < Whopsdk::Internal::Type::BaseModel
        # @!attribute id
        #   The ID of an existing attachment object. Use this when updating a resource and
        #   keeping a subset of the attachments. Don't use this unless you know what you're
        #   doing.
        #
        #   @return [String, nil]
        optional :id, String, nil?: true

        # @!attribute direct_upload_id
        #   This ID should be used the first time you upload an attachment. It is the ID of
        #   the direct upload that was created when uploading the file to S3 via the
        #   mediaDirectUpload mutation.
        #
        #   @return [String, nil]
        optional :direct_upload_id, String, nil?: true

        # @!method initialize(id: nil, direct_upload_id: nil)
        #   Some parameter documentations has been truncated, see
        #   {Whopsdk::Models::ProductCreateParams::BannerImage} for more details.
        #
        #   A banner image for the access pass in png, jpeg format
        #
        #   @param id [String, nil] The ID of an existing attachment object. Use this when updating a resource and k
        #
        #   @param direct_upload_id [String, nil] This ID should be used the first time you upload an attachment. It is the ID of
      end

      class PlanOptions < Whopsdk::Internal::Type::BaseModel
        # @!attribute base_currency
        #   The available currencies on the platform
        #
        #   @return [Symbol, Whopsdk::Models::Currency, nil]
        optional :base_currency, enum: -> { Whopsdk::Currency }, nil?: true

        # @!attribute billing_period
        #   The interval at which the plan charges (renewal plans).
        #
        #   @return [Integer, nil]
        optional :billing_period, Integer, nil?: true

        # @!attribute custom_fields
        #   An array of custom field objects.
        #
        #   @return [Array<Whopsdk::Models::ProductCreateParams::PlanOptions::CustomField>, nil]
        optional :custom_fields,
                 -> {
                   Whopsdk::Internal::Type::ArrayOf[Whopsdk::ProductCreateParams::PlanOptions::CustomField]
                 },
                 nil?: true

        # @!attribute initial_price
        #   An additional amount charged upon first purchase.
        #
        #   @return [Float, nil]
        optional :initial_price, Float, nil?: true

        # @!attribute plan_type
        #   The type of plan that can be attached to an access pass
        #
        #   @return [Symbol, Whopsdk::Models::PlanType, nil]
        optional :plan_type, enum: -> { Whopsdk::PlanType }, nil?: true

        # @!attribute release_method
        #   The methods of how a plan can be released.
        #
        #   @return [Symbol, Whopsdk::Models::ReleaseMethod, nil]
        optional :release_method, enum: -> { Whopsdk::ReleaseMethod }, nil?: true

        # @!attribute renewal_price
        #   The amount the customer is charged every billing period.
        #
        #   @return [Float, nil]
        optional :renewal_price, Float, nil?: true

        # @!attribute visibility
        #   Visibility of a resource
        #
        #   @return [Symbol, Whopsdk::Models::Visibility, nil]
        optional :visibility, enum: -> { Whopsdk::Visibility }, nil?: true

        # @!method initialize(base_currency: nil, billing_period: nil, custom_fields: nil, initial_price: nil, plan_type: nil, release_method: nil, renewal_price: nil, visibility: nil)
        #   The details to assign an autogenerated plan.
        #
        #   @param base_currency [Symbol, Whopsdk::Models::Currency, nil] The available currencies on the platform
        #
        #   @param billing_period [Integer, nil] The interval at which the plan charges (renewal plans).
        #
        #   @param custom_fields [Array<Whopsdk::Models::ProductCreateParams::PlanOptions::CustomField>, nil] An array of custom field objects.
        #
        #   @param initial_price [Float, nil] An additional amount charged upon first purchase.
        #
        #   @param plan_type [Symbol, Whopsdk::Models::PlanType, nil] The type of plan that can be attached to an access pass
        #
        #   @param release_method [Symbol, Whopsdk::Models::ReleaseMethod, nil] The methods of how a plan can be released.
        #
        #   @param renewal_price [Float, nil] The amount the customer is charged every billing period.
        #
        #   @param visibility [Symbol, Whopsdk::Models::Visibility, nil] Visibility of a resource

        class CustomField < Whopsdk::Internal::Type::BaseModel
          # @!attribute field_type
          #   The type of the custom field.
          #
          #   @return [Symbol, Whopsdk::Models::ProductCreateParams::PlanOptions::CustomField::FieldType, nil]
          required :field_type,
                   enum: -> { Whopsdk::ProductCreateParams::PlanOptions::CustomField::FieldType },
                   nil?: true

          # @!attribute name
          #   The name of the custom field.
          #
          #   @return [String]
          required :name, String

          # @!attribute id
          #   The ID of the custom field (if being updated)
          #
          #   @return [String, nil]
          optional :id, String, nil?: true

          # @!attribute order
          #   The order of the field.
          #
          #   @return [Integer, nil]
          optional :order, Integer, nil?: true

          # @!attribute placeholder
          #   The placeholder value of the field.
          #
          #   @return [String, nil]
          optional :placeholder, String, nil?: true

          # @!attribute required
          #   Whether or not the field is required.
          #
          #   @return [Boolean, nil]
          optional :required, Whopsdk::Internal::Type::Boolean, nil?: true

          # @!method initialize(field_type:, name:, id: nil, order: nil, placeholder: nil, required: nil)
          #   @param field_type [Symbol, Whopsdk::Models::ProductCreateParams::PlanOptions::CustomField::FieldType, nil] The type of the custom field.
          #
          #   @param name [String] The name of the custom field.
          #
          #   @param id [String, nil] The ID of the custom field (if being updated)
          #
          #   @param order [Integer, nil] The order of the field.
          #
          #   @param placeholder [String, nil] The placeholder value of the field.
          #
          #   @param required [Boolean, nil] Whether or not the field is required.

          # The type of the custom field.
          #
          # @see Whopsdk::Models::ProductCreateParams::PlanOptions::CustomField#field_type
          module FieldType
            extend Whopsdk::Internal::Type::Enum

            TEXT = :text

            # @!method self.values
            #   @return [Array<Symbol>]
          end
        end
      end

      class ProductHighlight < Whopsdk::Internal::Type::BaseModel
        # @!attribute content
        #   Text to display to describe the product highlight (max length 250 for
        #   qualification or benefits, 170 for who this is for, 140 for pricing features).
        #
        #   @return [String]
        required :content, String

        # @!attribute highlight_type
        #   Types of product highlight
        #
        #   @return [Symbol, Whopsdk::Models::ProductCreateParams::ProductHighlight::HighlightType, nil]
        required :highlight_type,
                 enum: -> { Whopsdk::ProductCreateParams::ProductHighlight::HighlightType },
                 nil?: true

        # @!attribute title
        #   The title of the product highlight, if applicable.
        #
        #   @return [String, nil]
        optional :title, String, nil?: true

        # @!method initialize(content:, highlight_type:, title: nil)
        #   Some parameter documentations has been truncated, see
        #   {Whopsdk::Models::ProductCreateParams::ProductHighlight} for more details.
        #
        #   Input for creating a product highlight
        #
        #   @param content [String] Text to display to describe the product highlight (max length 250 for qualificat
        #
        #   @param highlight_type [Symbol, Whopsdk::Models::ProductCreateParams::ProductHighlight::HighlightType, nil] Types of product highlight
        #
        #   @param title [String, nil] The title of the product highlight, if applicable.

        # Types of product highlight
        #
        # @see Whopsdk::Models::ProductCreateParams::ProductHighlight#highlight_type
        module HighlightType
          extend Whopsdk::Internal::Type::Enum

          QUALIFICATION = :qualification
          BENEFIT = :benefit
          WHO_THIS_IS_FOR = :who_this_is_for
          PRICING_FEATURE = :pricing_feature

          # @!method self.values
          #   @return [Array<Symbol>]
        end
      end
    end
  end
end
