# frozen_string_literal: true

module WhopSDK
  module Resources
    class Products
      # Some parameter documentations has been truncated, see
      # {WhopSDK::Models::ProductCreateParams} for more details.
      #
      # Creates a new Product
      #
      # Required permissions:
      #
      # - `access_pass:create`
      # - `access_pass:basic:read`
      #
      # @overload create(company_id:, title:, business_type: nil, collect_shipping_address: nil, custom_cta: nil, custom_cta_url: nil, custom_statement_descriptor: nil, description: nil, experience_ids: nil, global_affiliate_percentage: nil, global_affiliate_status: nil, headline: nil, industry_type: nil, member_affiliate_percentage: nil, member_affiliate_status: nil, plan_options: nil, product_highlights: nil, product_tax_code_id: nil, redirect_purchase_url: nil, route: nil, visibility: nil, request_options: {})
      #
      # @param company_id [String] The ID of the company to create the product for.
      #
      # @param title [String] The title of the product.
      #
      # @param business_type [Symbol, WhopSDK::Models::BusinessTypes, nil] The different business types a company can be.
      #
      # @param collect_shipping_address [Boolean, nil] Whether or not to collect shipping information at checkout from the customer.
      #
      # @param custom_cta [Symbol, WhopSDK::Models::CustomCta, nil] The different types of custom CTAs that can be selected.
      #
      # @param custom_cta_url [String, nil] The custom call to action URL for the product.
      #
      # @param custom_statement_descriptor [String, nil] The custom statement descriptor for the product i.e. WHOP\*SPORTS, must be
      # betwee
      #
      # @param description [String, nil] A written description of the product.
      #
      # @param experience_ids [Array<String>, nil] An array of experience IDs that this pass has
      #
      # @param global_affiliate_percentage [Float, nil] The percentage of the revenue that goes to the global affiliate program.
      #
      # @param global_affiliate_status [Symbol, WhopSDK::Models::GlobalAffiliateStatus, nil] The different statuses of the global affiliate program for a product.
      #
      # @param headline [String, nil] The headline of the product.
      #
      # @param industry_type [Symbol, WhopSDK::Models::IndustryTypes, nil] The different industry types a company can be in.
      #
      # @param member_affiliate_percentage [Float, nil] The percentage of the revenue that goes to the member affiliate program.
      #
      # @param member_affiliate_status [Symbol, WhopSDK::Models::GlobalAffiliateStatus, nil] The different statuses of the global affiliate program for a product.
      #
      # @param plan_options [WhopSDK::Models::ProductCreateParams::PlanOptions, nil] The details to assign an autogenerated plan.
      #
      # @param product_highlights [Array<WhopSDK::Models::ProductCreateParams::ProductHighlight>, nil] The product highlights for the product.
      #
      # @param product_tax_code_id [String, nil] The ID of the product tax code to apply to this product.
      #
      # @param redirect_purchase_url [String, nil] The URL to redirect the customer to after a purchase.
      #
      # @param route [String, nil] The route of the product.
      #
      # @param visibility [Symbol, WhopSDK::Models::Visibility, nil] Visibility of a resource
      #
      # @param request_options [WhopSDK::RequestOptions, Hash{Symbol=>Object}, nil]
      #
      # @return [WhopSDK::Models::Product]
      #
      # @see WhopSDK::Models::ProductCreateParams
      def create(params)
        parsed, options = WhopSDK::ProductCreateParams.dump_request(params)
        @client.request(
          method: :post,
          path: "products",
          body: parsed,
          model: WhopSDK::Product,
          options: options
        )
      end

      # Retrieves a product by ID or route
      #
      # Required permissions:
      #
      # - `access_pass:basic:read`
      #
      # @overload retrieve(id, request_options: {})
      #
      # @param id [String] The ID or route of the product
      #
      # @param request_options [WhopSDK::RequestOptions, Hash{Symbol=>Object}, nil]
      #
      # @return [WhopSDK::Models::Product]
      #
      # @see WhopSDK::Models::ProductRetrieveParams
      def retrieve(id, params = {})
        @client.request(
          method: :get,
          path: ["products/%1$s", id],
          model: WhopSDK::Product,
          options: params[:request_options]
        )
      end

      # Some parameter documentations has been truncated, see
      # {WhopSDK::Models::ProductUpdateParams} for more details.
      #
      # Updates an existing Product
      #
      # Required permissions:
      #
      # - `access_pass:update`
      # - `access_pass:basic:read`
      #
      # @overload update(id, business_type: nil, collect_shipping_address: nil, custom_cta: nil, custom_cta_url: nil, custom_statement_descriptor: nil, description: nil, global_affiliate_percentage: nil, global_affiliate_status: nil, headline: nil, industry_type: nil, member_affiliate_percentage: nil, member_affiliate_status: nil, product_tax_code_id: nil, redirect_purchase_url: nil, route: nil, store_page_config: nil, title: nil, visibility: nil, request_options: {})
      #
      # @param id [String] The ID (tag) of the product
      #
      # @param business_type [Symbol, WhopSDK::Models::BusinessTypes, nil] The different business types a company can be.
      #
      # @param collect_shipping_address [Boolean, nil] Whether or not to collect shipping information at checkout from the customer.
      #
      # @param custom_cta [Symbol, WhopSDK::Models::CustomCta, nil] The different types of custom CTAs that can be selected.
      #
      # @param custom_cta_url [String, nil] The custom call to action URL for the product.
      #
      # @param custom_statement_descriptor [String, nil] The custom statement descriptor for the product i.e. WHOP\*SPORTS, must be
      # betwee
      #
      # @param description [String, nil] A written description of the product.
      #
      # @param global_affiliate_percentage [Float, nil] The percentage of the revenue that goes to the global affiliate program.
      #
      # @param global_affiliate_status [Symbol, WhopSDK::Models::GlobalAffiliateStatus, nil] The different statuses of the global affiliate program for a product.
      #
      # @param headline [String, nil] The headline of the product.
      #
      # @param industry_type [Symbol, WhopSDK::Models::IndustryTypes, nil] The different industry types a company can be in.
      #
      # @param member_affiliate_percentage [Float, nil] The percentage of the revenue that goes to the member affiliate program.
      #
      # @param member_affiliate_status [Symbol, WhopSDK::Models::GlobalAffiliateStatus, nil] The different statuses of the global affiliate program for a product.
      #
      # @param product_tax_code_id [String, nil] The ID of the product tax code to apply to this product.
      #
      # @param redirect_purchase_url [String, nil] The URL to redirect the customer to after a purchase.
      #
      # @param route [String, nil] The route of the product.
      #
      # @param store_page_config [WhopSDK::Models::ProductUpdateParams::StorePageConfig, nil] Configuration for a product on the company's store page.
      #
      # @param title [String, nil] The title of the product.
      #
      # @param visibility [Symbol, WhopSDK::Models::Visibility, nil] Visibility of a resource
      #
      # @param request_options [WhopSDK::RequestOptions, Hash{Symbol=>Object}, nil]
      #
      # @return [WhopSDK::Models::Product]
      #
      # @see WhopSDK::Models::ProductUpdateParams
      def update(id, params = {})
        parsed, options = WhopSDK::ProductUpdateParams.dump_request(params)
        @client.request(
          method: :patch,
          path: ["products/%1$s", id],
          body: parsed,
          model: WhopSDK::Product,
          options: options
        )
      end

      # Lists products for a company
      #
      # Required permissions:
      #
      # - `access_pass:basic:read`
      #
      # @overload list(company_id:, after: nil, before: nil, direction: nil, first: nil, last: nil, order: nil, product_types: nil, visibilities: nil, request_options: {})
      #
      # @param company_id [String] The ID of the company to filter products by
      #
      # @param after [String, nil] Returns the elements in the list that come after the specified cursor.
      #
      # @param before [String, nil] Returns the elements in the list that come before the specified cursor.
      #
      # @param direction [Symbol, WhopSDK::Models::Direction, nil] The direction of the sort.
      #
      # @param first [Integer, nil] Returns the first _n_ elements from the list.
      #
      # @param last [Integer, nil] Returns the last _n_ elements from the list.
      #
      # @param order [Symbol, WhopSDK::Models::ProductListParams::Order, nil] The ways a relation of AccessPasses can be ordered
      #
      # @param product_types [Array<Symbol, WhopSDK::Models::AccessPassType>, nil] The type of products to filter by
      #
      # @param visibilities [Array<Symbol, WhopSDK::Models::VisibilityFilter>, nil] The visibility of the products to filter by
      #
      # @param request_options [WhopSDK::RequestOptions, Hash{Symbol=>Object}, nil]
      #
      # @return [WhopSDK::Internal::CursorPage<WhopSDK::Models::ProductListItem>]
      #
      # @see WhopSDK::Models::ProductListParams
      def list(params)
        parsed, options = WhopSDK::ProductListParams.dump_request(params)
        @client.request(
          method: :get,
          path: "products",
          query: parsed,
          page: WhopSDK::Internal::CursorPage,
          model: WhopSDK::ProductListItem,
          options: options
        )
      end

      # Deletes an existing Product
      #
      # Required permissions:
      #
      # - `access_pass:delete`
      #
      # @overload delete(id, request_options: {})
      #
      # @param id [String] The internal ID (tag) of the product to delete.
      #
      # @param request_options [WhopSDK::RequestOptions, Hash{Symbol=>Object}, nil]
      #
      # @return [Boolean]
      #
      # @see WhopSDK::Models::ProductDeleteParams
      def delete(id, params = {})
        @client.request(
          method: :delete,
          path: ["products/%1$s", id],
          model: WhopSDK::Internal::Type::Boolean,
          options: params[:request_options]
        )
      end

      # @api private
      #
      # @param client [WhopSDK::Client]
      def initialize(client:)
        @client = client
      end
    end
  end
end
