# frozen_string_literal: true

module WhopSDK
  module Models
    module Affiliates
      # @see WhopSDK::Resources::Affiliates::Overrides#create
      class OverrideCreateParams < WhopSDK::Internal::Type::BaseModel
        extend WhopSDK::Internal::Type::RequestParameters::Converter
        include WhopSDK::Internal::Type::RequestParameters

        # @!attribute id
        #
        #   @return [String]
        required :id, String

        # @!attribute body
        #   Parameters for CreateAffiliateOverride
        #
        #   @return [WhopSDK::Models::Affiliates::OverrideCreateParams::Body::CreateAffiliateOverrideInputOverrideTypeStandard, WhopSDK::Models::Affiliates::OverrideCreateParams::Body::CreateAffiliateOverrideInputOverrideTypeRevShare]
        required :body, union: -> { WhopSDK::Affiliates::OverrideCreateParams::Body }

        # @!method initialize(id:, body:, request_options: {})
        #   @param id [String]
        #
        #   @param body [WhopSDK::Models::Affiliates::OverrideCreateParams::Body::CreateAffiliateOverrideInputOverrideTypeStandard, WhopSDK::Models::Affiliates::OverrideCreateParams::Body::CreateAffiliateOverrideInputOverrideTypeRevShare] Parameters for CreateAffiliateOverride
        #
        #   @param request_options [WhopSDK::RequestOptions, Hash{Symbol=>Object}]

        # Parameters for CreateAffiliateOverride
        module Body
          extend WhopSDK::Internal::Type::Union

          # Autogenerated input type of CreateAffiliateOverride
          variant -> { WhopSDK::Affiliates::OverrideCreateParams::Body::CreateAffiliateOverrideInputOverrideTypeStandard }

          # Autogenerated input type of CreateAffiliateOverride
          variant -> { WhopSDK::Affiliates::OverrideCreateParams::Body::CreateAffiliateOverrideInputOverrideTypeRevShare }

          class CreateAffiliateOverrideInputOverrideTypeStandard < WhopSDK::Internal::Type::BaseModel
            # @!attribute id
            #   The affiliate ID.
            #
            #   @return [String]
            required :id, String

            # @!attribute commission_value
            #   The commission value (percentage 1-100 or flat fee).
            #
            #   @return [Float]
            required :commission_value, Float

            # @!attribute override_type
            #
            #   @return [Symbol, :standard]
            required :override_type, const: :standard

            # @!attribute plan_id
            #   The plan ID (required for standard overrides).
            #
            #   @return [String]
            required :plan_id, String

            # @!attribute applies_to_payments
            #   Whether the affiliate commission applies to the first payment or all payments
            #
            #   @return [Symbol, WhopSDK::Models::Affiliates::AffiliateAppliesToPayments, nil]
            optional :applies_to_payments,
                     enum: -> {
                       WhopSDK::Affiliates::AffiliateAppliesToPayments
                     },
                     nil?: true

            # @!attribute commission_type
            #   The types of payouts an affiliate can have
            #
            #   @return [Symbol, WhopSDK::Models::Affiliates::AffiliatePayoutTypes, nil]
            optional :commission_type, enum: -> { WhopSDK::Affiliates::AffiliatePayoutTypes }, nil?: true

            # @!method initialize(id:, commission_value:, plan_id:, applies_to_payments: nil, commission_type: nil, override_type: :standard)
            #   Autogenerated input type of CreateAffiliateOverride
            #
            #   @param id [String] The affiliate ID.
            #
            #   @param commission_value [Float] The commission value (percentage 1-100 or flat fee).
            #
            #   @param plan_id [String] The plan ID (required for standard overrides).
            #
            #   @param applies_to_payments [Symbol, WhopSDK::Models::Affiliates::AffiliateAppliesToPayments, nil] Whether the affiliate commission applies to the first payment or all payments
            #
            #   @param commission_type [Symbol, WhopSDK::Models::Affiliates::AffiliatePayoutTypes, nil] The types of payouts an affiliate can have
            #
            #   @param override_type [Symbol, :standard]
          end

          class CreateAffiliateOverrideInputOverrideTypeRevShare < WhopSDK::Internal::Type::BaseModel
            # @!attribute id
            #   The affiliate ID.
            #
            #   @return [String]
            required :id, String

            # @!attribute commission_value
            #   The commission value (percentage 1-100 or flat fee).
            #
            #   @return [Float]
            required :commission_value, Float

            # @!attribute override_type
            #
            #   @return [Symbol, :rev_share]
            required :override_type, const: :rev_share

            # @!attribute commission_type
            #   The types of payouts an affiliate can have
            #
            #   @return [Symbol, WhopSDK::Models::Affiliates::AffiliatePayoutTypes, nil]
            optional :commission_type, enum: -> { WhopSDK::Affiliates::AffiliatePayoutTypes }, nil?: true

            # @!attribute product_id
            #   The product ID (for rev-share overrides, omit for company-wide).
            #
            #   @return [String, nil]
            optional :product_id, String, nil?: true

            # @!attribute revenue_basis
            #   The calculation method for affiliate rev-share percentages
            #
            #   @return [Symbol, WhopSDK::Models::Affiliates::AffiliateRevenueBases, nil]
            optional :revenue_basis, enum: -> { WhopSDK::Affiliates::AffiliateRevenueBases }, nil?: true

            # @!method initialize(id:, commission_value:, commission_type: nil, product_id: nil, revenue_basis: nil, override_type: :rev_share)
            #   Autogenerated input type of CreateAffiliateOverride
            #
            #   @param id [String] The affiliate ID.
            #
            #   @param commission_value [Float] The commission value (percentage 1-100 or flat fee).
            #
            #   @param commission_type [Symbol, WhopSDK::Models::Affiliates::AffiliatePayoutTypes, nil] The types of payouts an affiliate can have
            #
            #   @param product_id [String, nil] The product ID (for rev-share overrides, omit for company-wide).
            #
            #   @param revenue_basis [Symbol, WhopSDK::Models::Affiliates::AffiliateRevenueBases, nil] The calculation method for affiliate rev-share percentages
            #
            #   @param override_type [Symbol, :rev_share]
          end

          # @!method self.variants
          #   @return [Array(WhopSDK::Models::Affiliates::OverrideCreateParams::Body::CreateAffiliateOverrideInputOverrideTypeStandard, WhopSDK::Models::Affiliates::OverrideCreateParams::Body::CreateAffiliateOverrideInputOverrideTypeRevShare)]
        end
      end
    end
  end
end
