module WhopSDK
  module Resources
    class AccessTokens
      def create: (
        ?company_id: String?,
        ?expires_at: Time?,
        ?scoped_actions: ::Array[String]?,
        ?user_id: String?,
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::Models::AccessTokenCreateResponse

      def initialize: (client: WhopSDK::Client) -> void
    end
  end
end
