module WhopSDK
  module Resources
    class Accounts
      def create: (
        ?email: String,
        ?metadata: ::Hash[Symbol, top],
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::Account

      def retrieve: (
        String account_id,
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::Account

      def update: (
        String account_id,
        ?affiliate_application_required: bool,
        ?affiliate_instructions: String?,
        ?banner_image: ::Hash[Symbol, top]?,
        ?business_type: String?,
        ?country: String?,
        ?description: String?,
        ?featured_affiliate_product_id: String?,
        ?home_preferences: ::Array[String],
        ?industry_group: String?,
        ?industry_type: String?,
        ?invoice_prefix: String?,
        ?logo: ::Hash[Symbol, top]?,
        ?metadata: ::Hash[Symbol, top],
        ?onboarding_type: String?,
        ?opengraph_image: ::Hash[Symbol, top]?,
        ?opengraph_image_variant: String?,
        ?other_business_description: String?,
        ?other_industry_description: String?,
        ?require_2fa: bool,
        ?route: String?,
        ?send_customer_emails: bool,
        ?show_joined_whops: bool,
        ?show_reviews_dtc: bool,
        ?show_user_directory: bool,
        ?social_links: ::Array[::Hash[Symbol, top]],
        ?store_page_config: ::Hash[Symbol, top]?,
        ?target_audience: String?,
        ?title: String?,
        ?use_logo_as_opengraph_image_fallback: bool,
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::Account

      def list: (
        ?page: Integer,
        ?per: Integer,
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::Models::AccountListResponse

      def me: (?request_options: WhopSDK::request_opts) -> WhopSDK::Account

      def initialize: (client: WhopSDK::Client) -> void
    end
  end
end
