module WhopSDK
  module Resources
    class AIChats
      def create: (
        ?title: String?,
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::AIChat

      def retrieve: (
        String id,
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::AIChat

      def update: (
        String id,
        ?current_company_id: String?,
        ?title: String?,
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::AIChat

      def list: (
        ?after: String?,
        ?before: String?,
        ?first: Integer?,
        ?last: Integer?,
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::Internal::CursorPage[WhopSDK::Models::AIChatListResponse]

      def delete: (String id, ?request_options: WhopSDK::request_opts) -> bool

      def initialize: (client: WhopSDK::Client) -> void
    end
  end
end
