module WhopSDK
  module Resources
    class AppBuilds
      def create: (
        attachment: WhopSDK::AppBuildCreateParams::Attachment,
        checksum: String,
        platform: WhopSDK::Models::AppBuildCreateParams::platform,
        ?ai_prompt_id: String,
        ?app_id: String,
        ?source_attachment: WhopSDK::AppBuildCreateParams::SourceAttachment,
        ?supported_app_view_types: ::Array[WhopSDK::Models::AppBuildCreateParams::supported_app_view_type],
        ?api_version_date: String,
        ?idempotency_key: String,
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::AppBuild

      def retrieve: (
        String id,
        ?api_version_date: String,
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::AppBuild

      def list: (
        app_id: String,
        ?after: String,
        ?before: String,
        ?created_after: WhopSDK::Models::AppBuildListParams::created_after,
        ?created_before: WhopSDK::Models::AppBuildListParams::created_before,
        ?first: Integer,
        ?last: Integer,
        ?platform: WhopSDK::Models::AppBuildListParams::platform,
        ?status: WhopSDK::Models::AppBuildListParams::status,
        ?api_version_date: String,
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::Internal::CursorPage[WhopSDK::AppBuild]

      def promote: (
        String id,
        ?api_version_date: String,
        ?idempotency_key: String,
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::AppBuild

      def initialize: (client: WhopSDK::Client) -> void
    end
  end
end
