module WhopSDK
  module Resources
    class AuthorizedUsers
      def retrieve: (
        String id,
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::Models::AuthorizedUserRetrieveResponse

      def list: (
        company_id: String,
        ?after: String?,
        ?before: String?,
        ?created_after: Time?,
        ?created_before: Time?,
        ?first: Integer?,
        ?last: Integer?,
        ?role: WhopSDK::Models::authorized_user_roles?,
        ?user_id: String?,
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::Internal::CursorPage[WhopSDK::Models::AuthorizedUserListResponse]

      def initialize: (client: WhopSDK::Client) -> void
    end
  end
end
