module WhopSDK
  module Resources
    class Cards
      def create: (
        ?account_id: String,
        ?assigned_user_id: String,
        ?name: String,
        ?spend_limit: Float,
        ?spend_limit_frequency: WhopSDK::Models::CardCreateParams::spend_limit_frequency,
        ?transaction_limit: Float,
        ?user_id: String,
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::Models::CardCreateResponse

      def retrieve: (
        String card_id,
        ?account_id: String,
        ?user_id: String,
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::Models::CardRetrieveResponse

      def update: (
        String card_id,
        ?account_id: String,
        ?billing: WhopSDK::CardUpdateParams::Billing,
        ?canceled: bool,
        ?frozen: bool,
        ?name: String,
        ?pin: String,
        ?remove_limit: bool,
        ?spend_limit: Float,
        ?spend_limit_frequency: WhopSDK::Models::CardUpdateParams::spend_limit_frequency,
        ?transaction_limit: Float,
        ?user_id: String,
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::Models::CardUpdateResponse

      def list: (
        ?account_id: String,
        ?user_id: String,
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::Models::CardListResponse

      def initialize: (client: WhopSDK::Client) -> void
    end
  end
end
