module WhopSDK
  module Resources
    class Cards
      def create: (
        account_id: String,
        ?name: String,
        ?spend_limit: String,
        ?spend_limit_frequency: WhopSDK::Models::CardCreateParams::spend_limit_frequency,
        ?transaction_limit: String,
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::Card

      def retrieve: (
        String id,
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::Card

      def update: (
        String id,
        ?name: String,
        ?spend_limit: String,
        ?spend_limit_frequency: WhopSDK::Models::CardUpdateParams::spend_limit_frequency,
        ?transaction_limit: String,
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::Card

      def list: (
        account_id: String,
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::Models::CardListResponse

      def balance: (
        String id,
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::CardAccountBalance

      def card_transactions: (
        String id,
        ?created_after: String,
        ?created_before: String,
        ?page: Integer,
        ?per: Integer,
        ?status: WhopSDK::Models::CardCardTransactionsParams::status,
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::CardTransactionList

      def cashback: (
        String id,
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::CardCashback

      def create_dispute: (
        String id,
        dispute_type: WhopSDK::Models::CardCreateDisputeParams::dispute_type,
        text_evidence: String,
        transaction_id: String,
        ?dispute_amount_cents: Integer,
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::CardDispute

      def create_dispute_attachment: (
        String dispute_id,
        id: String,
        attachment: WhopSDK::CardCreateDisputeAttachmentParams::Attachment,
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::CardDispute

      def daily_spend: (
        String id,
        ?timezone: String,
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::CardDailySpend

      def deactivate: (
        String id,
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::Card

      def deposit_address: (
        String id,
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::CardDepositAddress

      def freeze_: (
        String id,
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::Card

      def transactions: (
        account_id: String,
        ?card_id: String,
        ?created_after: String,
        ?created_before: String,
        ?page: Integer,
        ?per: Integer,
        ?status: WhopSDK::Models::CardTransactionsParams::status,
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::CardTransactionList

      def unfreeze: (
        String id,
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::Card

      def initialize: (client: WhopSDK::Client) -> void
    end
  end
end
