module WhopSDK
  module Resources
    class CheckoutConfigurations
      def create: (
        plan: WhopSDK::CheckoutConfigurationCreateParams::Plan,
        plan_id: String,
        company_id: String,
        ?affiliate_code: String?,
        ?currency: WhopSDK::Models::currency?,
        ?metadata: ::Hash[Symbol, top]?,
        ?payment_method_configuration: WhopSDK::CheckoutConfigurationCreateParams::PaymentMethodConfiguration?,
        ?redirect_url: String?,
        ?source_url: String?,
        ?mode: :setup,
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::CheckoutConfiguration

      def retrieve: (
        String id,
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::CheckoutConfiguration

      def list: (
        company_id: String,
        ?after: String?,
        ?before: String?,
        ?created_after: Time?,
        ?created_before: Time?,
        ?direction: WhopSDK::Models::direction?,
        ?first: Integer?,
        ?last: Integer?,
        ?plan_id: String?,
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::Internal::CursorPage[WhopSDK::Models::CheckoutConfigurationListResponse]

      def initialize: (client: WhopSDK::Client) -> void
    end
  end
end
