module WhopSDK
  module Resources
    class CompanyTokenTransactions
      def create: (
        amount: Float,
        company_id: String,
        destination_user_id: String,
        user_id: String,
        ?description: String?,
        ?idempotency_key: String?,
        ?transaction_type: :subtract,
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::CompanyTokenTransaction

      def retrieve: (
        String id,
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::CompanyTokenTransaction

      def list: (
        company_id: String,
        ?after: String?,
        ?before: String?,
        ?first: Integer?,
        ?last: Integer?,
        ?transaction_type: WhopSDK::Models::bot_token_transaction_types?,
        ?user_id: String?,
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::Internal::CursorPage[WhopSDK::Models::CompanyTokenTransactionListResponse]

      def initialize: (client: WhopSDK::Client) -> void
    end
  end
end
