module WhopSDK
  module Resources
    class Companies
      def create: (
        title: String,
        ?business_type: WhopSDK::Models::business_types?,
        ?description: String?,
        ?email: String?,
        ?industry_group: WhopSDK::Models::industry_groups?,
        ?industry_type: WhopSDK::Models::industry_types?,
        ?logo: WhopSDK::CompanyCreateParams::Logo?,
        ?metadata: ::Hash[Symbol, top]?,
        ?parent_company_id: String?,
        ?send_customer_emails: bool?,
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::Company

      def retrieve: (
        String id,
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::Company

      def update: (
        String id,
        ?banner_image: WhopSDK::CompanyUpdateParams::BannerImage?,
        ?business_type: WhopSDK::Models::business_types?,
        ?description: String?,
        ?industry_group: WhopSDK::Models::industry_groups?,
        ?industry_type: WhopSDK::Models::industry_types?,
        ?logo: WhopSDK::CompanyUpdateParams::Logo?,
        ?route: String?,
        ?send_customer_emails: bool?,
        ?target_audience: String?,
        ?title: String?,
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::Company

      def list: (
        ?after: String?,
        ?before: String?,
        ?created_after: Time?,
        ?created_before: Time?,
        ?direction: WhopSDK::Models::direction?,
        ?first: Integer?,
        ?last: Integer?,
        ?parent_company_id: String?,
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::Internal::CursorPage[WhopSDK::Models::CompanyListResponse]

      def initialize: (client: WhopSDK::Client) -> void
    end
  end
end
