module WhopSDK
  module Resources
    class CourseLessons
      def create: (
        chapter_id: String,
        lesson_type: WhopSDK::Models::lesson_types,
        ?content: String?,
        ?days_from_course_start_until_unlock: Integer?,
        ?embed_id: String?,
        ?embed_type: WhopSDK::Models::embed_type?,
        ?thumbnail: WhopSDK::Models::CourseLessonCreateParams::thumbnail?,
        ?title: String?,
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::Lesson

      def retrieve: (
        String id,
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::Lesson

      def update: (
        String id,
        ?assessment_completion_requirement: WhopSDK::CourseLessonUpdateParams::AssessmentCompletionRequirement?,
        ?assessment_questions: ::Array[WhopSDK::CourseLessonUpdateParams::AssessmentQuestion]?,
        ?attachments: ::Array[WhopSDK::Models::CourseLessonUpdateParams::attachment]?,
        ?content: String?,
        ?days_from_course_start_until_unlock: Integer?,
        ?embed_id: String?,
        ?embed_type: WhopSDK::Models::embed_type?,
        ?lesson_type: WhopSDK::Models::lesson_types?,
        ?main_pdf: WhopSDK::Models::CourseLessonUpdateParams::main_pdf?,
        ?max_attempts: Integer?,
        ?mux_asset_id: String?,
        ?thumbnail: WhopSDK::Models::CourseLessonUpdateParams::thumbnail?,
        ?title: String?,
        ?visibility: WhopSDK::Models::lesson_visibilities?,
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::Lesson

      def list: (
        ?after: String?,
        ?before: String?,
        ?chapter_id: String?,
        ?course_id: String?,
        ?first: Integer?,
        ?last: Integer?,
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::Internal::CursorPage[WhopSDK::Models::CourseLessonListResponse]

      def delete: (String id, ?request_options: WhopSDK::request_opts) -> bool

      def mark_as_completed: (
        String lesson_id,
        ?request_options: WhopSDK::request_opts
      ) -> bool

      def start: (
        String lesson_id,
        ?request_options: WhopSDK::request_opts
      ) -> bool

      def submit_assessment: (
        String lesson_id,
        answers: ::Array[WhopSDK::CourseLessonSubmitAssessmentParams::Answer],
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::Models::CourseLessonSubmitAssessmentResponse

      def initialize: (client: WhopSDK::Client) -> void
    end
  end
end
