module WhopSDK
  module Resources
    class CourseStudents
      def retrieve: (
        String id,
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::Models::CourseStudentRetrieveResponse

      def list: (
        course_id: String,
        ?after: String?,
        ?before: String?,
        ?first: Integer?,
        ?keyword: String?,
        ?last: Integer?,
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::Internal::CursorPage[WhopSDK::Models::CourseStudentListResponse]

      def initialize: (client: WhopSDK::Client) -> void
    end
  end
end
