module WhopSDK
  module Resources
    class Deposits
      def create: (
        destination: WhopSDK::Models::DepositCreateParams::destination,
        ?amount: Float,
        ?metadata: ::Hash[Symbol, top],
        ?network: String?,
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::Models::DepositCreateResponse

      def list: (
        account_id: String,
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::Models::DepositListResponse

      def initialize: (client: WhopSDK::Client) -> void
    end
  end
end
