module WhopSDK
  module Resources
    class Disputes
      def retrieve: (
        String id,
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::Dispute

      def list: (
        company_id: String,
        ?after: String?,
        ?before: String?,
        ?created_after: Time?,
        ?created_before: Time?,
        ?direction: WhopSDK::Models::direction?,
        ?first: Integer?,
        ?last: Integer?,
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::Internal::CursorPage[WhopSDK::Models::DisputeListResponse]

      def submit_evidence: (
        String id,
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::Dispute

      def update_evidence: (
        String id,
        ?access_activity_log: String?,
        ?billing_address: String?,
        ?cancellation_policy_attachment: WhopSDK::DisputeUpdateEvidenceParams::CancellationPolicyAttachment?,
        ?cancellation_policy_disclosure: String?,
        ?customer_communication_attachment: WhopSDK::DisputeUpdateEvidenceParams::CustomerCommunicationAttachment?,
        ?customer_email_address: String?,
        ?customer_name: String?,
        ?notes: String?,
        ?product_description: String?,
        ?refund_policy_attachment: WhopSDK::DisputeUpdateEvidenceParams::RefundPolicyAttachment?,
        ?refund_policy_disclosure: String?,
        ?refund_refusal_explanation: String?,
        ?service_date: String?,
        ?uncategorized_attachment: WhopSDK::DisputeUpdateEvidenceParams::UncategorizedAttachment?,
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::Dispute

      def initialize: (client: WhopSDK::Client) -> void
    end
  end
end
