module WhopSDK
  module Resources
    class DisputeAlerts
      def retrieve: (
        String id,
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::Models::DisputeAlertRetrieveResponse

      def list: (
        company_id: String,
        ?after: String?,
        ?before: String?,
        ?created_after: Time?,
        ?created_before: Time?,
        ?direction: WhopSDK::Models::direction?,
        ?first: Integer?,
        ?last: Integer?,
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::Internal::CursorPage[WhopSDK::Models::DisputeAlertListResponse]

      def initialize: (client: WhopSDK::Client) -> void
    end
  end
end
