module WhopSDK
  module Resources
    class DmMembers
      def create: (
        channel_id: String,
        user_id: String,
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::DmMember

      def retrieve: (
        String id,
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::DmMember

      def update: (
        String id,
        ?notification_preference: WhopSDK::Models::dm_feed_member_notification_preferences?,
        ?status: WhopSDK::Models::dm_feed_member_statuses?,
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::DmMember

      def list: (
        channel_id: String,
        ?after: String?,
        ?before: String?,
        ?first: Integer?,
        ?last: Integer?,
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::Internal::CursorPage[WhopSDK::Models::DmMemberListResponse]

      def delete: (String id, ?request_options: WhopSDK::request_opts) -> bool

      def initialize: (client: WhopSDK::Client) -> void
    end
  end
end
