module WhopSDK
  module Resources
    class Experiences
      def create: (
        app_id: String,
        company_id: String,
        ?name: String?,
        ?section_id: String?,
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::Experience

      def retrieve: (
        String id,
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::Experience

      def update: (
        String id,
        ?access_level: WhopSDK::Models::ExperienceUpdateParams::access_level?,
        ?logo: WhopSDK::ExperienceUpdateParams::Logo,
        ?name: String?,
        ?order: String?,
        ?section_id: String?,
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::Experience

      def list: (
        company_id: String,
        ?after: String?,
        ?app_id: String?,
        ?before: String?,
        ?first: Integer?,
        ?last: Integer?,
        ?product_id: String?,
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::Internal::CursorPage[WhopSDK::Models::ExperienceListResponse]

      def delete: (String id, ?request_options: WhopSDK::request_opts) -> bool

      def attach: (
        String id,
        product_id: String,
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::Experience

      def detach: (
        String id,
        product_id: String,
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::Experience

      def duplicate: (
        String id,
        ?name: String?,
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::Experience

      def initialize: (client: WhopSDK::Client) -> void
    end
  end
end
