module WhopSDK
  module Resources
    class Invoices
      def create: (
        body: WhopSDK::Models::InvoiceCreateParams::body,
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::Invoice

      def retrieve: (
        String id,
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::Invoice

      def update: (
        String id,
        ?automatically_finalizes_at: Time?,
        ?billing_address: WhopSDK::InvoiceUpdateParams::BillingAddress?,
        ?charge_buyer_fee: bool?,
        ?collection_method: WhopSDK::Models::collection_method?,
        ?customer_name: String?,
        ?due_date: Time?,
        ?email_address: String?,
        ?line_items: ::Array[WhopSDK::InvoiceUpdateParams::LineItem]?,
        ?mailing_address_id: String?,
        ?member_id: String?,
        ?payment_method_id: String?,
        ?plan: WhopSDK::InvoiceUpdateParams::Plan?,
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::Invoice

      def list: (
        ?after: String?,
        ?before: String?,
        ?collection_methods: ::Array[WhopSDK::Models::collection_method]?,
        ?company_id: String?,
        ?created_after: Time?,
        ?created_before: Time?,
        ?direction: WhopSDK::Models::direction?,
        ?first: Integer?,
        ?last: Integer?,
        ?order: WhopSDK::Models::InvoiceListParams::order?,
        ?product_ids: ::Array[String]?,
        ?statuses: ::Array[WhopSDK::Models::invoice_status]?,
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::Internal::CursorPage[WhopSDK::InvoiceListItem]

      def delete: (String id, ?request_options: WhopSDK::request_opts) -> bool

      def mark_paid: (
        String id,
        ?request_options: WhopSDK::request_opts
      ) -> bool

      def mark_uncollectible: (
        String id,
        ?request_options: WhopSDK::request_opts
      ) -> bool

      def `void`: (String id, ?request_options: WhopSDK::request_opts) -> bool

      def initialize: (client: WhopSDK::Client) -> void
    end
  end
end
