module WhopSDK
  module Resources
    class Notifications
      def create: (
        body: WhopSDK::Models::NotificationCreateParams::body,
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::Models::NotificationCreateResponse

      def initialize: (client: WhopSDK::Client) -> void
    end
  end
end
