module WhopSDK
  module Resources
    class PaymentMethods
      def retrieve: (
        String id,
        member_id: String,
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::Models::payment_method_retrieve_response

      def list: (
        member_id: String,
        ?after: String?,
        ?before: String?,
        ?created_after: Time?,
        ?created_before: Time?,
        ?direction: WhopSDK::Models::direction?,
        ?first: Integer?,
        ?last: Integer?,
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::Internal::CursorPage[WhopSDK::Models::payment_method_list_response]

      def initialize: (client: WhopSDK::Client) -> void
    end
  end
end
