module WhopSDK
  module Resources
    class Payments
      def create: (
        account_id: String,
        plan_id: String,
        ?capture: bool?,
        ?confirmation_token: String?,
        ?email: String?,
        ?member_id: String?,
        ?metadata: ::Hash[Symbol, String]?,
        ?payment_method_id: String?,
        ?promo_code_id: String?,
        ?return_url: String?,
        ?api_version_date: String,
        ?idempotency_key: String,
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::Payment

      def retrieve: (
        String id,
        ?api_version_date: String,
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::Payment

      def list: (
        ?account_id: String,
        ?after: String,
        ?before: String,
        ?billing_reason: WhopSDK::Models::PaymentListParams::billing_reason,
        ?created_after: Time,
        ?created_before: Time,
        ?currency: String,
        ?direction: WhopSDK::Models::PaymentListParams::direction,
        ?first: Integer,
        ?last: Integer,
        ?member_id: String,
        ?membership_id: String,
        ?order: WhopSDK::Models::PaymentListParams::order,
        ?plan_id: String,
        ?product_id: String,
        ?query: String,
        ?status: WhopSDK::Models::PaymentListParams::status,
        ?user_id: String,
        ?api_version_date: String,
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::Internal::CursorPage[WhopSDK::Payment]

      def list_fees: (
        String id,
        ?api_version_date: String,
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::Models::PaymentListFeesResponse

      def refund: (
        String id,
        ?partial_amount: Float?,
        ?api_version_date: String,
        ?idempotency_key: String,
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::Payment

      def retry_: (
        String id,
        ?api_version_date: String,
        ?idempotency_key: String,
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::Payment

      def `void`: (
        String id,
        ?api_version_date: String,
        ?idempotency_key: String,
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::Payment

      def initialize: (client: WhopSDK::Client) -> void
    end
  end
end
