module WhopSDK
  module Resources
    class Payouts
      attr_reader methods_: WhopSDK::Resources::Payouts::Methods

      def create: (
        account_id: String,
        amount: Float,
        payout_method_id: String,
        ?currency: String,
        ?idempotency_key: String,
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::Models::PayoutCreateResponse

      def list: (
        ?account_id: String,
        ?after: String,
        ?before: String,
        ?currency: String,
        ?first: Integer,
        ?last: Integer,
        ?user_id: String,
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::Internal::CursorPage[WhopSDK::Models::PayoutListResponse]

      def initialize: (client: WhopSDK::Client) -> void
    end
  end
end
