module WhopSDK
  module Resources
    class People
      def retrieve: (
        String person_id,
        ?account_id: String,
        ?from: Integer,
        ?to: Integer,
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::Models::PersonRetrieveResponse

      def list: (
        ?account_id: String,
        ?after: String,
        ?before: String,
        ?direction: WhopSDK::Models::PersonListParams::direction,
        ?filters: String,
        ?first: Integer,
        ?from: Integer,
        ?sort: String,
        ?to: Integer,
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::Internal::CursorPage[WhopSDK::Models::PersonListResponse]

      def initialize: (client: WhopSDK::Client) -> void
    end
  end
end
