module WhopSDK
  module Resources
    class Plans
      def create: (
        company_id: String,
        product_id: String,
        ?billing_period: Integer?,
        ?currency: WhopSDK::Models::currency?,
        ?custom_fields: ::Array[WhopSDK::PlanCreateParams::CustomField]?,
        ?description: String?,
        ?expiration_days: Integer?,
        ?image: WhopSDK::PlanCreateParams::Image?,
        ?initial_price: Float?,
        ?internal_notes: String?,
        ?override_tax_type: WhopSDK::Models::tax_type?,
        ?plan_type: WhopSDK::Models::plan_type?,
        ?release_method: WhopSDK::Models::release_method?,
        ?renewal_price: Float?,
        ?strike_through_initial_price: Float?,
        ?strike_through_renewal_price: Float?,
        ?title: String?,
        ?trial_period_days: Integer?,
        ?visibility: WhopSDK::Models::visibility?,
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::Plan

      def retrieve: (
        String id,
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::Plan

      def update: (
        String id,
        ?billing_period: Integer?,
        ?currency: WhopSDK::Models::currency?,
        ?custom_fields: ::Array[WhopSDK::PlanUpdateParams::CustomField]?,
        ?description: String?,
        ?expiration_days: Integer?,
        ?image: WhopSDK::PlanUpdateParams::Image?,
        ?initial_price: Float?,
        ?internal_notes: String?,
        ?offer_cancel_discount: bool?,
        ?override_tax_type: WhopSDK::Models::tax_type?,
        ?renewal_price: Float?,
        ?strike_through_initial_price: Float?,
        ?strike_through_renewal_price: Float?,
        ?title: String?,
        ?trial_period_days: Integer?,
        ?visibility: WhopSDK::Models::visibility?,
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::Plan

      def list: (
        company_id: String,
        ?after: String?,
        ?before: String?,
        ?direction: WhopSDK::Models::direction?,
        ?first: Integer?,
        ?last: Integer?,
        ?order: WhopSDK::Models::PlanListParams::order?,
        ?plan_types: ::Array[WhopSDK::Models::plan_type]?,
        ?product_ids: ::Array[String]?,
        ?release_methods: ::Array[WhopSDK::Models::release_method]?,
        ?visibilities: ::Array[WhopSDK::Models::visibility_filter]?,
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::Internal::CursorPage[WhopSDK::Models::PlanListResponse]

      def delete: (String id, ?request_options: WhopSDK::request_opts) -> bool

      def initialize: (client: WhopSDK::Client) -> void
    end
  end
end
