module WhopSDK
  module Resources
    class Referrals
      attr_reader businesses: WhopSDK::Resources::Referrals::Businesses

      attr_reader partners: WhopSDK::Resources::Referrals::Partners

      def referred_users: (
        ?after: String,
        ?before: String,
        ?first: Integer,
        ?has_businesses: bool,
        ?has_earning_businesses: bool,
        ?last: Integer,
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::Models::ReferralReferredUsersResponse

      def initialize: (client: WhopSDK::Client) -> void
    end
  end
end
