module WhopSDK
  module Resources
    class Stats
      def retrieve: (
        String metric,
        from: Date,
        to: Date,
        ?access_level: String,
        ?account_id: String,
        ?ad_campaign_ids: ::Array[String],
        ?ad_group_ids: ::Array[String],
        ?ad_ids: ::Array[String],
        ?breakdown_by: String,
        ?card_network: String,
        ?category: String,
        ?convert_to: String,
        ?currency: String,
        ?fee_type: String,
        ?interval: WhopSDK::Models::StatRetrieveParams::interval,
        ?most_recent_action: String,
        ?payment_method: String,
        ?product: String,
        ?referred_user_id: String,
        ?segment: String,
        ?snapshot_window: WhopSDK::Models::StatRetrieveParams::snapshot_window,
        ?source: String,
        ?status: String,
        ?time_zone: String,
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::Models::StatRetrieveResponse

      def list: (
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::Models::StatListResponse

      def initialize: (client: WhopSDK::Client) -> void
    end
  end
end
