module WhopSDK
  module Resources
    class Verifications
      def retrieve: (
        String id,
        ?api_version_date: String,
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::Models::VerificationRetrieveResponse

      def list: (
        account_id: String,
        ?direction: WhopSDK::Models::VerificationListParams::direction,
        ?order: WhopSDK::Models::VerificationListParams::order,
        ?api_version_date: String,
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::Models::VerificationListResponse

      def initialize: (client: WhopSDK::Client) -> void
    end
  end
end
