module WhopSDK
  module Resources
    class Wallets
      def list: (
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::Models::WalletListResponse

      def balance: (
        account_id: String,
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::Models::WalletBalanceResponse

      def deposit_address: (
        account_id: String,
        ?asset: String,
        ?network: WhopSDK::Models::WalletDepositAddressParams::network,
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::Models::WalletDepositAddressResponse

      def send_: (
        account_id: String,
        amount: String,
        to: String,
        ?request_options: WhopSDK::request_opts
      ) -> WhopSDK::Models::WalletSendResponse

      def initialize: (client: WhopSDK::Client) -> void
    end
  end
end
