module WhopSDK
  module Resources
    class Webhooks
      def unwrap: (
        String payload
      ) -> (WhopSDK::InvoiceCreatedWebhookEvent
      | WhopSDK::InvoicePaidWebhookEvent
      | WhopSDK::InvoicePastDueWebhookEvent
      | WhopSDK::InvoiceVoidedWebhookEvent
      | WhopSDK::MembershipActivatedWebhookEvent
      | WhopSDK::MembershipDeactivatedWebhookEvent
      | WhopSDK::EntryCreatedWebhookEvent
      | WhopSDK::EntryApprovedWebhookEvent
      | WhopSDK::EntryDeniedWebhookEvent
      | WhopSDK::EntryDeletedWebhookEvent
      | WhopSDK::CourseLessonInteractionCompletedWebhookEvent
      | WhopSDK::PaymentSucceededWebhookEvent
      | WhopSDK::PaymentFailedWebhookEvent
      | WhopSDK::PaymentPendingWebhookEvent)

      def initialize: (client: WhopSDK::Client) -> void
    end
  end
end
