module WhopSDK
  module Resources
    class Webhooks
      def unwrap: (
        String payload
      ) -> (WhopSDK::InvoiceCreatedWebhookEvent
      | WhopSDK::InvoicePaidWebhookEvent
      | WhopSDK::InvoicePastDueWebhookEvent
      | WhopSDK::InvoiceVoidedWebhookEvent
      | WhopSDK::MembershipActivatedWebhookEvent
      | WhopSDK::MembershipDeactivatedWebhookEvent
      | WhopSDK::EntryCreatedWebhookEvent
      | WhopSDK::EntryApprovedWebhookEvent
      | WhopSDK::EntryDeniedWebhookEvent
      | WhopSDK::EntryDeletedWebhookEvent
      | WhopSDK::SetupIntentRequiresActionWebhookEvent
      | WhopSDK::SetupIntentSucceededWebhookEvent
      | WhopSDK::SetupIntentCanceledWebhookEvent
      | WhopSDK::WithdrawalCreatedWebhookEvent
      | WhopSDK::WithdrawalUpdatedWebhookEvent
      | WhopSDK::CourseLessonInteractionCompletedWebhookEvent
      | WhopSDK::PayoutMethodCreatedWebhookEvent
      | WhopSDK::VerificationSucceededWebhookEvent
      | WhopSDK::PaymentCreatedWebhookEvent
      | WhopSDK::PaymentSucceededWebhookEvent
      | WhopSDK::PaymentFailedWebhookEvent
      | WhopSDK::PaymentPendingWebhookEvent
      | WhopSDK::DisputeCreatedWebhookEvent
      | WhopSDK::DisputeUpdatedWebhookEvent
      | WhopSDK::RefundCreatedWebhookEvent
      | WhopSDK::RefundUpdatedWebhookEvent
      | WhopSDK::MembershipCancelAtPeriodEndChangedWebhookEvent)

      def initialize: (client: WhopSDK::Client) -> void
    end
  end
end
