# frozen_string_literal: true

module Whop_sdk
  module Affiliates
    module Overrides
      module Types
        # Autogenerated input type of CreateAffiliateOverride
        class CreateOverridesRequestBodyRevShare < Internal::Types::Model
          field :commission_type, -> { Whop_sdk::Types::AffiliatePayoutTypes }, optional: true, nullable: false

          field :commission_value, -> { Integer }, optional: false, nullable: false

          field :id, -> { String }, optional: false, nullable: false

          field :product_id, -> { String }, optional: true, nullable: false

          field :revenue_basis, -> { Whop_sdk::Types::AffiliateRevenueBases }, optional: true, nullable: false
        end
      end
    end
  end
end
