# frozen_string_literal: true

module Whop_sdk
  module Affiliates
    module Overrides
      module Types
        # Autogenerated input type of CreateAffiliateOverride
        class CreateOverridesRequestBodyStandard < Internal::Types::Model
          field :applies_to_payments, -> { Whop_sdk::Types::AffiliateAppliesToPayments }, optional: true, nullable: false

          field :commission_type, -> { Whop_sdk::Types::AffiliatePayoutTypes }, optional: true, nullable: false

          field :commission_value, -> { Integer }, optional: false, nullable: false

          field :id, -> { String }, optional: false, nullable: false

          field :plan_id, -> { String }, optional: false, nullable: false
        end
      end
    end
  end
end
