# frozen_string_literal: true

module Whop_sdk
  module Invoices
    module Types
      # Autogenerated input type of CreateInvoice
      class CreateInvoicesRequestProductID < Internal::Types::Model
        field :account_id, -> { String }, optional: false, nullable: false

        field :automatically_finalizes_at, -> { String }, optional: true, nullable: false

        field :billing_address, -> { Whop_sdk::Invoices::Types::CreateInvoicesRequestProductIDBillingAddress }, optional: true, nullable: false

        field :charge_buyer_fee, -> { Internal::Types::Boolean }, optional: true, nullable: false

        field :collection_method, -> { Whop_sdk::Types::InvoiceCollectionMethods }, optional: false, nullable: false

        field :customer_name, -> { String }, optional: true, nullable: false

        field :due_date, -> { String }, optional: true, nullable: false

        field :email_address, -> { String }, optional: true, nullable: false

        field :line_items, -> { Internal::Types::Array[Whop_sdk::Invoices::Types::CreateInvoicesRequestProductIDLineItemsItem] }, optional: true, nullable: false

        field :mailing_address_id, -> { String }, optional: true, nullable: false

        field :member_id, -> { String }, optional: true, nullable: false

        field :payment_method_id, -> { String }, optional: true, nullable: false

        field :payment_token_id, -> { String }, optional: true, nullable: false

        field :plan, -> { Whop_sdk::Invoices::Types::CreateInvoicesRequestProductIDPlan }, optional: false, nullable: false

        field :product_id, -> { String }, optional: false, nullable: false

        field :save_as_draft, -> { Internal::Types::Boolean }, optional: true, nullable: false

        field :subscription_billing_anchor_at, -> { String }, optional: true, nullable: false
      end
    end
  end
end
