# frozen_string_literal: true

module Whop_sdk
  module Types
    module PayoutErrorCodes
      extend Whop_sdk::Internal::Types::Enum

      ACCOUNT_CLOSED = "account_closed"
      ACCOUNT_DOES_NOT_EXIST = "account_does_not_exist"
      ACCOUNT_INFORMATION_INVALID = "account_information_invalid"
      ACCOUNT_NUMBER_INVALID_REGION = "account_number_invalid_region"
      ACCOUNT_FROZEN = "account_frozen"
      ACCOUNT_LOOKUP_FAILED = "account_lookup_failed"
      ACCOUNT_NOT_FOUND = "account_not_found"
      AMOUNT_OUT_OF_BOUNDS = "amount_out_of_bounds"
      ATTRIBUTES_NOT_VALIDATED = "attributes_not_validated"
      B2B_PAYMENTS_PROHIBITED = "b2b_payments_prohibited"
      BANK_STATEMENT_REQUIRED = "bank_statement_required"
      COMPLIANCE_REVIEW = "compliance_review"
      CURRENCY_NOT_SUPPORTED = "currency_not_supported"
      DEPOSIT_CANCELED = "deposit_canceled"
      DEPOSIT_FAILED = "deposit_failed"
      DEPOSIT_REJECTED = "deposit_rejected"
      DESTINATION_UNAVAILABLE = "destination_unavailable"
      EXCEEDED_ACCOUNT_LIMIT = "exceeded_account_limit"
      EXPIRED_QUOTE = "expired_quote"
      GENERIC_PAYOUT_ERROR = "generic_payout_error"
      JUNK_FAILURE_REASON = "junk_failure_reason"
      TECHNICAL_PROBLEM = "technical_problem"
      PROVIDER_TEMPORARILY_UNAVAILABLE = "provider_temporarily_unavailable"
      PROVIDER_VALIDATION_FAILED = "provider_validation_failed"
      IDENTIFICATION_NUMBER_INVALID = "identification_number_invalid"
      INVALID_ACCOUNT_NUMBER = "invalid_account_number"
      INVALID_BANK_CODE = "invalid_bank_code"
      INVALID_BENEFICIARY = "invalid_beneficiary"
      INVALID_MAILING_ADDRESS = "invalid_mailing_address"
      INVALID_BRANCH_NUMBER = "invalid_branch_number"
      INVALID_BRANCH_CODE = "invalid_branch_code"
      INVALID_PHONE_NUMBER = "invalid_phone_number"
      INVALID_ROUTING_NUMBER = "invalid_routing_number"
      INVALID_SWIFT_CODE = "invalid_swift_code"
      INVALID_COMPANY_DETAILS = "invalid_company_details"
      MANUAL_CANCELATION = "manual_cancelation"
      MISC_ERROR = "misc_error"
      MISSING_CITY_AND_COUNTRY = "missing_city_and_country"
      MISSING_PHONE_NUMBER = "missing_phone_number"
      MISSING_REMITTANCE_INFO = "missing_remittance_info"
      PAYEE_NAME_INVALID = "payee_name_invalid"
      BENEFICIARY_NAME_MISMATCH = "beneficiary_name_mismatch"
      RECEIVING_ACCOUNT_LOCKED = "receiving_account_locked"
      REJECTED_BY_COMPLIANCE = "rejected_by_compliance"
      RTP_NOT_SUPPORTED = "rtp_not_supported"
      NON_TRANSACTION_ACCOUNT = "non_transaction_account"
      SOURCE_TOKEN_INSUFFICIENT_FUNDS = "source_token_insufficient_funds"
      SSN_INVALID = "ssn_invalid"
      WALLET_SCREENSHOT_REQUIRED = "wallet_screenshot_required"
      UNSUPPORTED_REGION = "unsupported_region"
      PAYOUT_PROVIDER_TIMEOUT = "payout_provider_timeout"
    end
  end
end
