module WhopSDK
  module Models
    type account_financing_approved_webhook_event =
      {
        id: String,
        api_version: :v1,
        api_version_date: String?,
        data: WhopSDK::AccountFinancingApprovedWebhookEvent::Data,
        timestamp: Time,
        type: :"account.financing_approved",
        account_id: String?,
        previous_attributes: top
      }

    class AccountFinancingApprovedWebhookEvent < WhopSDK::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor api_version: :v1

      attr_accessor api_version_date: String?

      attr_accessor data: WhopSDK::AccountFinancingApprovedWebhookEvent::Data

      attr_accessor timestamp: Time

      attr_accessor type: :"account.financing_approved"

      attr_accessor account_id: String?

      attr_reader previous_attributes: top?

      def previous_attributes=: (top) -> top

      def initialize: (
        id: String,
        api_version_date: String?,
        data: WhopSDK::AccountFinancingApprovedWebhookEvent::Data,
        timestamp: Time,
        ?account_id: String?,
        ?previous_attributes: top,
        ?api_version: :v1,
        ?type: :"account.financing_approved"
      ) -> void

      def to_hash: -> {
        id: String,
        api_version: :v1,
        api_version_date: String?,
        data: WhopSDK::AccountFinancingApprovedWebhookEvent::Data,
        timestamp: Time,
        type: :"account.financing_approved",
        account_id: String?,
        previous_attributes: top
      }

      type data =
        {
          id: String,
          balances: ::Array[WhopSDK::AccountFinancingApprovedWebhookEvent::Data::Balance],
          banner_image_url: String?,
          business_address: top?,
          business_name: String?,
          business_type: String?,
          can_transfer_pending_balance_to_children: bool,
          capabilities: WhopSDK::AccountFinancingApprovedWebhookEvent::Data::Capabilities?,
          cards: WhopSDK::AccountFinancingApprovedWebhookEvent::Data::Cards?,
          collect_vat_id: bool,
          company_formation: WhopSDK::AccountFinancingApprovedWebhookEvent::Data::CompanyFormation,
          country: String?,
          created_at: String,
          description: String?,
          economic_intelligence: bool,
          email: String?,
          eula: WhopSDK::AccountFinancingApprovedWebhookEvent::Data::Eula?,
          home_preferences: ::Array[WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::home_preference],
          industry_group: String?,
          industry_type: String?,
          invoice_prefix: String?,
          logo_url: String?,
          metadata: top,
          onboarding_type: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::onboarding_type?,
          opengraph_image_url: String?,
          opengraph_image_variant: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::opengraph_image_variant?,
          other_business_description: String?,
          other_industry_description: String?,
          owner: WhopSDK::AccountFinancingApprovedWebhookEvent::Data::Owner,
          parent_account: WhopSDK::AccountFinancingApprovedWebhookEvent::Data::ParentAccount?,
          payment_controls: WhopSDK::AccountFinancingApprovedWebhookEvent::Data::PaymentControls?,
          privacy_policy: WhopSDK::AccountFinancingApprovedWebhookEvent::Data::PrivacyPolicy?,
          product_tax_code: top?,
          recommended_actions: ::Array[WhopSDK::AccountFinancingApprovedWebhookEvent::Data::RecommendedAction]?,
          :require_2fa => bool,
          required_actions: ::Array[WhopSDK::AccountFinancingApprovedWebhookEvent::Data::RequiredAction]?,
          return_policy: WhopSDK::AccountFinancingApprovedWebhookEvent::Data::ReturnPolicy?,
          route: String,
          send_customer_emails: bool,
          show_joined_whops: bool,
          show_reviews_dtc: bool,
          show_user_directory: bool,
          social_links: ::Array[WhopSDK::AccountFinancingApprovedWebhookEvent::Data::SocialLink],
          stablecoin_rails: bool,
          status: String?,
          status_reason: String?,
          store_page_config: WhopSDK::AccountFinancingApprovedWebhookEvent::Data::StorePageConfig,
          target_audience: String?,
          tax_collection_enabled_states: ::Array[String],
          tax_identifiers: ::Array[WhopSDK::AccountFinancingApprovedWebhookEvent::Data::TaxIdentifier],
          tax_remitted_by: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::tax_remitted_by?,
          tax_type: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::tax_type?,
          terms_of_service: WhopSDK::AccountFinancingApprovedWebhookEvent::Data::TermsOfService?,
          three_ds_level: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::three_ds_level?,
          title: String,
          total_earned_usd: Float?,
          total_usd: String?,
          use_logo_as_opengraph_image_fallback: bool,
          verification: top,
          volume_usd: Float?,
          wallet: WhopSDK::AccountFinancingApprovedWebhookEvent::Data::Wallet?
        }

      class Data < WhopSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor balances: ::Array[WhopSDK::AccountFinancingApprovedWebhookEvent::Data::Balance]

        attr_accessor banner_image_url: String?

        attr_accessor business_address: top?

        attr_accessor business_name: String?

        attr_accessor business_type: String?

        attr_accessor can_transfer_pending_balance_to_children: bool

        attr_accessor capabilities: WhopSDK::AccountFinancingApprovedWebhookEvent::Data::Capabilities?

        attr_accessor cards: WhopSDK::AccountFinancingApprovedWebhookEvent::Data::Cards?

        attr_accessor collect_vat_id: bool

        attr_accessor company_formation: WhopSDK::AccountFinancingApprovedWebhookEvent::Data::CompanyFormation

        attr_accessor country: String?

        attr_accessor created_at: String

        attr_accessor description: String?

        attr_accessor economic_intelligence: bool

        attr_accessor email: String?

        attr_accessor eula: WhopSDK::AccountFinancingApprovedWebhookEvent::Data::Eula?

        attr_accessor home_preferences: ::Array[WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::home_preference]

        attr_accessor industry_group: String?

        attr_accessor industry_type: String?

        attr_accessor invoice_prefix: String?

        attr_accessor logo_url: String?

        attr_accessor metadata: top

        attr_accessor onboarding_type: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::onboarding_type?

        attr_accessor opengraph_image_url: String?

        attr_accessor opengraph_image_variant: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::opengraph_image_variant?

        attr_accessor other_business_description: String?

        attr_accessor other_industry_description: String?

        attr_accessor owner: WhopSDK::AccountFinancingApprovedWebhookEvent::Data::Owner

        attr_accessor parent_account: WhopSDK::AccountFinancingApprovedWebhookEvent::Data::ParentAccount?

        attr_accessor payment_controls: WhopSDK::AccountFinancingApprovedWebhookEvent::Data::PaymentControls?

        attr_accessor privacy_policy: WhopSDK::AccountFinancingApprovedWebhookEvent::Data::PrivacyPolicy?

        attr_accessor product_tax_code: top?

        attr_accessor recommended_actions: ::Array[WhopSDK::AccountFinancingApprovedWebhookEvent::Data::RecommendedAction]?

        attr_accessor require_2fa: bool

        attr_accessor required_actions: ::Array[WhopSDK::AccountFinancingApprovedWebhookEvent::Data::RequiredAction]?

        attr_accessor return_policy: WhopSDK::AccountFinancingApprovedWebhookEvent::Data::ReturnPolicy?

        attr_accessor route: String

        attr_accessor send_customer_emails: bool

        attr_accessor show_joined_whops: bool

        attr_accessor show_reviews_dtc: bool

        attr_accessor show_user_directory: bool

        attr_accessor social_links: ::Array[WhopSDK::AccountFinancingApprovedWebhookEvent::Data::SocialLink]

        attr_accessor stablecoin_rails: bool

        attr_accessor status: String?

        attr_accessor status_reason: String?

        attr_accessor store_page_config: WhopSDK::AccountFinancingApprovedWebhookEvent::Data::StorePageConfig

        attr_accessor target_audience: String?

        attr_accessor tax_collection_enabled_states: ::Array[String]

        attr_accessor tax_identifiers: ::Array[WhopSDK::AccountFinancingApprovedWebhookEvent::Data::TaxIdentifier]

        attr_accessor tax_remitted_by: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::tax_remitted_by?

        attr_accessor tax_type: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::tax_type?

        attr_accessor terms_of_service: WhopSDK::AccountFinancingApprovedWebhookEvent::Data::TermsOfService?

        attr_accessor three_ds_level: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::three_ds_level?

        attr_accessor title: String

        attr_accessor total_earned_usd: Float?

        attr_accessor total_usd: String?

        attr_accessor use_logo_as_opengraph_image_fallback: bool

        attr_accessor verification: top

        attr_accessor volume_usd: Float?

        attr_accessor wallet: WhopSDK::AccountFinancingApprovedWebhookEvent::Data::Wallet?

        def initialize: (
          id: String,
          balances: ::Array[WhopSDK::AccountFinancingApprovedWebhookEvent::Data::Balance],
          banner_image_url: String?,
          business_address: top?,
          business_name: String?,
          business_type: String?,
          can_transfer_pending_balance_to_children: bool,
          capabilities: WhopSDK::AccountFinancingApprovedWebhookEvent::Data::Capabilities?,
          cards: WhopSDK::AccountFinancingApprovedWebhookEvent::Data::Cards?,
          collect_vat_id: bool,
          company_formation: WhopSDK::AccountFinancingApprovedWebhookEvent::Data::CompanyFormation,
          country: String?,
          created_at: String,
          description: String?,
          economic_intelligence: bool,
          email: String?,
          eula: WhopSDK::AccountFinancingApprovedWebhookEvent::Data::Eula?,
          home_preferences: ::Array[WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::home_preference],
          industry_group: String?,
          industry_type: String?,
          invoice_prefix: String?,
          logo_url: String?,
          metadata: top,
          onboarding_type: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::onboarding_type?,
          opengraph_image_url: String?,
          opengraph_image_variant: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::opengraph_image_variant?,
          other_business_description: String?,
          other_industry_description: String?,
          owner: WhopSDK::AccountFinancingApprovedWebhookEvent::Data::Owner,
          parent_account: WhopSDK::AccountFinancingApprovedWebhookEvent::Data::ParentAccount?,
          payment_controls: WhopSDK::AccountFinancingApprovedWebhookEvent::Data::PaymentControls?,
          privacy_policy: WhopSDK::AccountFinancingApprovedWebhookEvent::Data::PrivacyPolicy?,
          product_tax_code: top?,
          recommended_actions: ::Array[WhopSDK::AccountFinancingApprovedWebhookEvent::Data::RecommendedAction]?,
          require_2fa: bool,
          required_actions: ::Array[WhopSDK::AccountFinancingApprovedWebhookEvent::Data::RequiredAction]?,
          return_policy: WhopSDK::AccountFinancingApprovedWebhookEvent::Data::ReturnPolicy?,
          route: String,
          send_customer_emails: bool,
          show_joined_whops: bool,
          show_reviews_dtc: bool,
          show_user_directory: bool,
          social_links: ::Array[WhopSDK::AccountFinancingApprovedWebhookEvent::Data::SocialLink],
          stablecoin_rails: bool,
          status: String?,
          status_reason: String?,
          store_page_config: WhopSDK::AccountFinancingApprovedWebhookEvent::Data::StorePageConfig,
          target_audience: String?,
          tax_collection_enabled_states: ::Array[String],
          tax_identifiers: ::Array[WhopSDK::AccountFinancingApprovedWebhookEvent::Data::TaxIdentifier],
          tax_remitted_by: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::tax_remitted_by?,
          tax_type: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::tax_type?,
          terms_of_service: WhopSDK::AccountFinancingApprovedWebhookEvent::Data::TermsOfService?,
          three_ds_level: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::three_ds_level?,
          title: String,
          total_earned_usd: Float?,
          total_usd: String?,
          use_logo_as_opengraph_image_fallback: bool,
          verification: top,
          volume_usd: Float?,
          wallet: WhopSDK::AccountFinancingApprovedWebhookEvent::Data::Wallet?
        ) -> void

        def to_hash: -> {
          id: String,
          balances: ::Array[WhopSDK::AccountFinancingApprovedWebhookEvent::Data::Balance],
          banner_image_url: String?,
          business_address: top?,
          business_name: String?,
          business_type: String?,
          can_transfer_pending_balance_to_children: bool,
          capabilities: WhopSDK::AccountFinancingApprovedWebhookEvent::Data::Capabilities?,
          cards: WhopSDK::AccountFinancingApprovedWebhookEvent::Data::Cards?,
          collect_vat_id: bool,
          company_formation: WhopSDK::AccountFinancingApprovedWebhookEvent::Data::CompanyFormation,
          country: String?,
          created_at: String,
          description: String?,
          economic_intelligence: bool,
          email: String?,
          eula: WhopSDK::AccountFinancingApprovedWebhookEvent::Data::Eula?,
          home_preferences: ::Array[WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::home_preference],
          industry_group: String?,
          industry_type: String?,
          invoice_prefix: String?,
          logo_url: String?,
          metadata: top,
          onboarding_type: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::onboarding_type?,
          opengraph_image_url: String?,
          opengraph_image_variant: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::opengraph_image_variant?,
          other_business_description: String?,
          other_industry_description: String?,
          owner: WhopSDK::AccountFinancingApprovedWebhookEvent::Data::Owner,
          parent_account: WhopSDK::AccountFinancingApprovedWebhookEvent::Data::ParentAccount?,
          payment_controls: WhopSDK::AccountFinancingApprovedWebhookEvent::Data::PaymentControls?,
          privacy_policy: WhopSDK::AccountFinancingApprovedWebhookEvent::Data::PrivacyPolicy?,
          product_tax_code: top?,
          recommended_actions: ::Array[WhopSDK::AccountFinancingApprovedWebhookEvent::Data::RecommendedAction]?,
          :require_2fa => bool,
          required_actions: ::Array[WhopSDK::AccountFinancingApprovedWebhookEvent::Data::RequiredAction]?,
          return_policy: WhopSDK::AccountFinancingApprovedWebhookEvent::Data::ReturnPolicy?,
          route: String,
          send_customer_emails: bool,
          show_joined_whops: bool,
          show_reviews_dtc: bool,
          show_user_directory: bool,
          social_links: ::Array[WhopSDK::AccountFinancingApprovedWebhookEvent::Data::SocialLink],
          stablecoin_rails: bool,
          status: String?,
          status_reason: String?,
          store_page_config: WhopSDK::AccountFinancingApprovedWebhookEvent::Data::StorePageConfig,
          target_audience: String?,
          tax_collection_enabled_states: ::Array[String],
          tax_identifiers: ::Array[WhopSDK::AccountFinancingApprovedWebhookEvent::Data::TaxIdentifier],
          tax_remitted_by: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::tax_remitted_by?,
          tax_type: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::tax_type?,
          terms_of_service: WhopSDK::AccountFinancingApprovedWebhookEvent::Data::TermsOfService?,
          three_ds_level: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::three_ds_level?,
          title: String,
          total_earned_usd: Float?,
          total_usd: String?,
          use_logo_as_opengraph_image_fallback: bool,
          verification: top,
          volume_usd: Float?,
          wallet: WhopSDK::AccountFinancingApprovedWebhookEvent::Data::Wallet?
        }

        type balance =
          {
            balance: String,
            breakdown: WhopSDK::AccountFinancingApprovedWebhookEvent::Data::Balance::Breakdown,
            icon_url: String?,
            name: String,
            price_usd: Float?,
            symbol: String,
            value_usd: String?
          }

        class Balance < WhopSDK::Internal::Type::BaseModel
          attr_accessor balance: String

          attr_accessor breakdown: WhopSDK::AccountFinancingApprovedWebhookEvent::Data::Balance::Breakdown

          attr_accessor icon_url: String?

          attr_accessor name: String

          attr_accessor price_usd: Float?

          attr_accessor symbol: String

          attr_accessor value_usd: String?

          def initialize: (
            balance: String,
            breakdown: WhopSDK::AccountFinancingApprovedWebhookEvent::Data::Balance::Breakdown,
            icon_url: String?,
            name: String,
            price_usd: Float?,
            symbol: String,
            value_usd: String?
          ) -> void

          def to_hash: -> {
            balance: String,
            breakdown: WhopSDK::AccountFinancingApprovedWebhookEvent::Data::Balance::Breakdown,
            icon_url: String?,
            name: String,
            price_usd: Float?,
            symbol: String,
            value_usd: String?
          }

          type breakdown =
            {
              available: String,
              in_transit: String,
              pending: String,
              pending_settlements: ::Array[WhopSDK::AccountFinancingApprovedWebhookEvent::Data::Balance::Breakdown::PendingSettlement],
              reserve: String
            }

          class Breakdown < WhopSDK::Internal::Type::BaseModel
            attr_accessor available: String

            attr_accessor in_transit: String

            attr_accessor pending: String

            attr_accessor pending_settlements: ::Array[WhopSDK::AccountFinancingApprovedWebhookEvent::Data::Balance::Breakdown::PendingSettlement]

            attr_accessor reserve: String

            def initialize: (
              available: String,
              in_transit: String,
              pending: String,
              pending_settlements: ::Array[WhopSDK::AccountFinancingApprovedWebhookEvent::Data::Balance::Breakdown::PendingSettlement],
              reserve: String
            ) -> void

            def to_hash: -> {
              available: String,
              in_transit: String,
              pending: String,
              pending_settlements: ::Array[WhopSDK::AccountFinancingApprovedWebhookEvent::Data::Balance::Breakdown::PendingSettlement],
              reserve: String
            }

            type pending_settlement = { amount: String, date: String }

            class PendingSettlement < WhopSDK::Internal::Type::BaseModel
              attr_accessor amount: String

              attr_accessor date: String

              def initialize: (amount: String, date: String) -> void

              def to_hash: -> { amount: String, date: String }
            end
          end
        end

        type capabilities =
          {
            accept_bank_payments: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::Capabilities::accept_bank_payments,
            accept_bnpl_payments: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::Capabilities::accept_bnpl_payments,
            accept_card_payments: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::Capabilities::accept_card_payments,
            bank_deposit: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::Capabilities::bank_deposit,
            card_deposit: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::Capabilities::card_deposit,
            card_issuing: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::Capabilities::card_issuing,
            crypto_deposit: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::Capabilities::crypto_deposit,
            crypto_payout: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::Capabilities::crypto_payout,
            instant_payout: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::Capabilities::instant_payout,
            run_ads: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::Capabilities::run_ads,
            standard_payout: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::Capabilities::standard_payout,
            transfer: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::Capabilities::transfer
          }

        class Capabilities < WhopSDK::Internal::Type::BaseModel
          attr_accessor accept_bank_payments: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::Capabilities::accept_bank_payments

          attr_accessor accept_bnpl_payments: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::Capabilities::accept_bnpl_payments

          attr_accessor accept_card_payments: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::Capabilities::accept_card_payments

          attr_accessor bank_deposit: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::Capabilities::bank_deposit

          attr_accessor card_deposit: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::Capabilities::card_deposit

          attr_accessor card_issuing: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::Capabilities::card_issuing

          attr_accessor crypto_deposit: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::Capabilities::crypto_deposit

          attr_accessor crypto_payout: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::Capabilities::crypto_payout

          attr_accessor instant_payout: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::Capabilities::instant_payout

          attr_accessor run_ads: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::Capabilities::run_ads

          attr_accessor standard_payout: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::Capabilities::standard_payout

          attr_accessor transfer: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::Capabilities::transfer

          def initialize: (
            accept_bank_payments: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::Capabilities::accept_bank_payments,
            accept_bnpl_payments: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::Capabilities::accept_bnpl_payments,
            accept_card_payments: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::Capabilities::accept_card_payments,
            bank_deposit: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::Capabilities::bank_deposit,
            card_deposit: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::Capabilities::card_deposit,
            card_issuing: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::Capabilities::card_issuing,
            crypto_deposit: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::Capabilities::crypto_deposit,
            crypto_payout: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::Capabilities::crypto_payout,
            instant_payout: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::Capabilities::instant_payout,
            run_ads: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::Capabilities::run_ads,
            standard_payout: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::Capabilities::standard_payout,
            transfer: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::Capabilities::transfer
          ) -> void

          def to_hash: -> {
            accept_bank_payments: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::Capabilities::accept_bank_payments,
            accept_bnpl_payments: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::Capabilities::accept_bnpl_payments,
            accept_card_payments: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::Capabilities::accept_card_payments,
            bank_deposit: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::Capabilities::bank_deposit,
            card_deposit: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::Capabilities::card_deposit,
            card_issuing: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::Capabilities::card_issuing,
            crypto_deposit: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::Capabilities::crypto_deposit,
            crypto_payout: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::Capabilities::crypto_payout,
            instant_payout: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::Capabilities::instant_payout,
            run_ads: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::Capabilities::run_ads,
            standard_payout: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::Capabilities::standard_payout,
            transfer: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::Capabilities::transfer
          }

          type accept_bank_payments = :active | :inactive | :pending

          module AcceptBankPayments
            extend WhopSDK::Internal::Type::Enum

            ACTIVE: :active
            INACTIVE: :inactive
            PENDING: :pending

            def self?.values: -> ::Array[WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::Capabilities::accept_bank_payments]
          end

          type accept_bnpl_payments = :active | :inactive | :pending

          module AcceptBnplPayments
            extend WhopSDK::Internal::Type::Enum

            ACTIVE: :active
            INACTIVE: :inactive
            PENDING: :pending

            def self?.values: -> ::Array[WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::Capabilities::accept_bnpl_payments]
          end

          type accept_card_payments = :active | :inactive | :pending

          module AcceptCardPayments
            extend WhopSDK::Internal::Type::Enum

            ACTIVE: :active
            INACTIVE: :inactive
            PENDING: :pending

            def self?.values: -> ::Array[WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::Capabilities::accept_card_payments]
          end

          type bank_deposit = :active | :inactive | :pending

          module BankDeposit
            extend WhopSDK::Internal::Type::Enum

            ACTIVE: :active
            INACTIVE: :inactive
            PENDING: :pending

            def self?.values: -> ::Array[WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::Capabilities::bank_deposit]
          end

          type card_deposit = :active | :inactive | :pending

          module CardDeposit
            extend WhopSDK::Internal::Type::Enum

            ACTIVE: :active
            INACTIVE: :inactive
            PENDING: :pending

            def self?.values: -> ::Array[WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::Capabilities::card_deposit]
          end

          type card_issuing = :active | :inactive | :pending

          module CardIssuing
            extend WhopSDK::Internal::Type::Enum

            ACTIVE: :active
            INACTIVE: :inactive
            PENDING: :pending

            def self?.values: -> ::Array[WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::Capabilities::card_issuing]
          end

          type crypto_deposit = :active | :inactive | :pending

          module CryptoDeposit
            extend WhopSDK::Internal::Type::Enum

            ACTIVE: :active
            INACTIVE: :inactive
            PENDING: :pending

            def self?.values: -> ::Array[WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::Capabilities::crypto_deposit]
          end

          type crypto_payout = :active | :inactive | :pending

          module CryptoPayout
            extend WhopSDK::Internal::Type::Enum

            ACTIVE: :active
            INACTIVE: :inactive
            PENDING: :pending

            def self?.values: -> ::Array[WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::Capabilities::crypto_payout]
          end

          type instant_payout = :active | :inactive | :pending

          module InstantPayout
            extend WhopSDK::Internal::Type::Enum

            ACTIVE: :active
            INACTIVE: :inactive
            PENDING: :pending

            def self?.values: -> ::Array[WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::Capabilities::instant_payout]
          end

          type run_ads = :active | :inactive | :pending

          module RunAds
            extend WhopSDK::Internal::Type::Enum

            ACTIVE: :active
            INACTIVE: :inactive
            PENDING: :pending

            def self?.values: -> ::Array[WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::Capabilities::run_ads]
          end

          type standard_payout = :active | :inactive | :pending

          module StandardPayout
            extend WhopSDK::Internal::Type::Enum

            ACTIVE: :active
            INACTIVE: :inactive
            PENDING: :pending

            def self?.values: -> ::Array[WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::Capabilities::standard_payout]
          end

          type transfer = :active | :inactive | :pending

          module Transfer
            extend WhopSDK::Internal::Type::Enum

            ACTIVE: :active
            INACTIVE: :inactive
            PENDING: :pending

            def self?.values: -> ::Array[WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::Capabilities::transfer]
          end
        end

        type cards =
          {
            kind: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::Cards::kind?,
            status: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::Cards::status
          }

        class Cards < WhopSDK::Internal::Type::BaseModel
          attr_accessor kind: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::Cards::kind?

          attr_accessor status: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::Cards::status

          def initialize: (
            kind: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::Cards::kind?,
            status: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::Cards::status
          ) -> void

          def to_hash: -> {
            kind: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::Cards::kind?,
            status: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::Cards::status
          }

          type kind = :individual | :business

          module Kind
            extend WhopSDK::Internal::Type::Enum

            INDIVIDUAL: :individual
            BUSINESS: :business

            def self?.values: -> ::Array[WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::Cards::kind]
          end

          type status =
            :approved
            | :pending
            | :manual_review
            | :denied
            | :locked
            | :canceled
            | :needs_verification
            | :needs_information

          module Status
            extend WhopSDK::Internal::Type::Enum

            APPROVED: :approved
            PENDING: :pending
            MANUAL_REVIEW: :manual_review
            DENIED: :denied
            LOCKED: :locked
            CANCELED: :canceled
            NEEDS_VERIFICATION: :needs_verification
            NEEDS_INFORMATION: :needs_information

            def self?.values: -> ::Array[WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::Cards::status]
          end
        end

        type company_formation =
          {
            documents: ::Array[WhopSDK::AccountFinancingApprovedWebhookEvent::Data::CompanyFormation::Document],
            ein_registered: bool,
            legal_name: String?,
            signatures: WhopSDK::AccountFinancingApprovedWebhookEvent::Data::CompanyFormation::Signatures,
            state_registered: bool,
            status: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::CompanyFormation::status
          }

        class CompanyFormation < WhopSDK::Internal::Type::BaseModel
          attr_reader documents: ::Array[WhopSDK::AccountFinancingApprovedWebhookEvent::Data::CompanyFormation::Document]?

          def documents=: (
            ::Array[WhopSDK::AccountFinancingApprovedWebhookEvent::Data::CompanyFormation::Document]
          ) -> ::Array[WhopSDK::AccountFinancingApprovedWebhookEvent::Data::CompanyFormation::Document]

          attr_reader ein_registered: bool?

          def ein_registered=: (bool) -> bool

          attr_accessor legal_name: String?

          attr_reader signatures: WhopSDK::AccountFinancingApprovedWebhookEvent::Data::CompanyFormation::Signatures?

          def signatures=: (
            WhopSDK::AccountFinancingApprovedWebhookEvent::Data::CompanyFormation::Signatures
          ) -> WhopSDK::AccountFinancingApprovedWebhookEvent::Data::CompanyFormation::Signatures

          attr_reader state_registered: bool?

          def state_registered=: (bool) -> bool

          attr_reader status: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::CompanyFormation::status?

          def status=: (
            WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::CompanyFormation::status
          ) -> WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::CompanyFormation::status

          def initialize: (
            ?documents: ::Array[WhopSDK::AccountFinancingApprovedWebhookEvent::Data::CompanyFormation::Document],
            ?ein_registered: bool,
            ?legal_name: String?,
            ?signatures: WhopSDK::AccountFinancingApprovedWebhookEvent::Data::CompanyFormation::Signatures,
            ?state_registered: bool,
            ?status: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::CompanyFormation::status
          ) -> void

          def to_hash: -> {
            documents: ::Array[WhopSDK::AccountFinancingApprovedWebhookEvent::Data::CompanyFormation::Document],
            ein_registered: bool,
            legal_name: String?,
            signatures: WhopSDK::AccountFinancingApprovedWebhookEvent::Data::CompanyFormation::Signatures,
            state_registered: bool,
            status: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::CompanyFormation::status
          }

          type document =
            { id: String, name: String, type: String, url: String }

          class Document < WhopSDK::Internal::Type::BaseModel
            attr_accessor id: String

            attr_accessor name: String

            attr_accessor type: String

            attr_accessor url: String

            def initialize: (
              id: String,
              name: String,
              type: String,
              url: String
            ) -> void

            def to_hash: -> {
              id: String,
              name: String,
              type: String,
              url: String
            }
          end

          type signatures =
            {
              :form8821 => WhopSDK::AccountFinancingApprovedWebhookEvent::Data::CompanyFormation::Signatures::Form8821,
              :ss4 => WhopSDK::AccountFinancingApprovedWebhookEvent::Data::CompanyFormation::Signatures::Ss4
            }

          class Signatures < WhopSDK::Internal::Type::BaseModel
            attr_reader form8821: WhopSDK::AccountFinancingApprovedWebhookEvent::Data::CompanyFormation::Signatures::Form8821?

            def form8821=: (
              WhopSDK::AccountFinancingApprovedWebhookEvent::Data::CompanyFormation::Signatures::Form8821
            ) -> WhopSDK::AccountFinancingApprovedWebhookEvent::Data::CompanyFormation::Signatures::Form8821

            attr_reader ss4: WhopSDK::AccountFinancingApprovedWebhookEvent::Data::CompanyFormation::Signatures::Ss4?

            def ss4=: (
              WhopSDK::AccountFinancingApprovedWebhookEvent::Data::CompanyFormation::Signatures::Ss4
            ) -> WhopSDK::AccountFinancingApprovedWebhookEvent::Data::CompanyFormation::Signatures::Ss4

            def initialize: (
              ?form8821: WhopSDK::AccountFinancingApprovedWebhookEvent::Data::CompanyFormation::Signatures::Form8821,
              ?ss4: WhopSDK::AccountFinancingApprovedWebhookEvent::Data::CompanyFormation::Signatures::Ss4
            ) -> void

            def to_hash: -> {
              :form8821 => WhopSDK::AccountFinancingApprovedWebhookEvent::Data::CompanyFormation::Signatures::Form8821,
              :ss4 => WhopSDK::AccountFinancingApprovedWebhookEvent::Data::CompanyFormation::Signatures::Ss4
            }

            type form8821 =
              {
                status: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::CompanyFormation::Signatures::Form8821::status,
                expires_at: String,
                url: String
              }

            class Form8821 < WhopSDK::Internal::Type::BaseModel
              attr_accessor status: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::CompanyFormation::Signatures::Form8821::status

              attr_reader expires_at: String?

              def expires_at=: (String) -> String

              attr_reader url: String?

              def url=: (String) -> String

              def initialize: (
                status: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::CompanyFormation::Signatures::Form8821::status,
                ?expires_at: String,
                ?url: String
              ) -> void

              def to_hash: -> {
                status: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::CompanyFormation::Signatures::Form8821::status,
                expires_at: String,
                url: String
              }

              type status = :pending | :unknown

              module Status
                extend WhopSDK::Internal::Type::Enum

                PENDING: :pending
                UNKNOWN: :unknown

                def self?.values: -> ::Array[WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::CompanyFormation::Signatures::Form8821::status]
              end
            end

            type ss4 =
              {
                status: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::CompanyFormation::Signatures::Ss4::status,
                expires_at: String,
                url: String
              }

            class Ss4 < WhopSDK::Internal::Type::BaseModel
              attr_accessor status: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::CompanyFormation::Signatures::Ss4::status

              attr_reader expires_at: String?

              def expires_at=: (String) -> String

              attr_reader url: String?

              def url=: (String) -> String

              def initialize: (
                status: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::CompanyFormation::Signatures::Ss4::status,
                ?expires_at: String,
                ?url: String
              ) -> void

              def to_hash: -> {
                status: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::CompanyFormation::Signatures::Ss4::status,
                expires_at: String,
                url: String
              }

              type status = :pending | :unknown

              module Status
                extend WhopSDK::Internal::Type::Enum

                PENDING: :pending
                UNKNOWN: :unknown

                def self?.values: -> ::Array[WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::CompanyFormation::Signatures::Ss4::status]
              end
            end
          end

          type status = :draft | :processing | :filed | :rejected | :completed

          module Status
            extend WhopSDK::Internal::Type::Enum

            DRAFT: :draft
            PROCESSING: :processing
            FILED: :filed
            REJECTED: :rejected
            COMPLETED: :completed

            def self?.values: -> ::Array[WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::CompanyFormation::status]
          end
        end

        type eula =
          {
            id: String,
            content_type: String?,
            created_at: String,
            filename: String?,
            object: String,
            size: Integer?,
            upload_status: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::Eula::upload_status,
            url: String?,
            visibility: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::Eula::visibility,
            multipart_chunk_size: Integer?,
            multipart_upload_id: String?,
            multipart_upload_urls: ::Array[WhopSDK::AccountFinancingApprovedWebhookEvent::Data::Eula::MultipartUploadURL]?,
            upload_headers: top,
            upload_url: String?
          }

        class Eula < WhopSDK::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor content_type: String?

          attr_accessor created_at: String

          attr_accessor filename: String?

          attr_accessor object: String

          attr_accessor size: Integer?

          attr_accessor upload_status: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::Eula::upload_status

          attr_accessor url: String?

          attr_accessor visibility: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::Eula::visibility

          attr_accessor multipart_chunk_size: Integer?

          attr_accessor multipart_upload_id: String?

          attr_accessor multipart_upload_urls: ::Array[WhopSDK::AccountFinancingApprovedWebhookEvent::Data::Eula::MultipartUploadURL]?

          attr_reader upload_headers: top?

          def upload_headers=: (top) -> top

          attr_accessor upload_url: String?

          def initialize: (
            id: String,
            content_type: String?,
            created_at: String,
            filename: String?,
            object: String,
            size: Integer?,
            upload_status: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::Eula::upload_status,
            url: String?,
            visibility: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::Eula::visibility,
            ?multipart_chunk_size: Integer?,
            ?multipart_upload_id: String?,
            ?multipart_upload_urls: ::Array[WhopSDK::AccountFinancingApprovedWebhookEvent::Data::Eula::MultipartUploadURL]?,
            ?upload_headers: top,
            ?upload_url: String?
          ) -> void

          def to_hash: -> {
            id: String,
            content_type: String?,
            created_at: String,
            filename: String?,
            object: String,
            size: Integer?,
            upload_status: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::Eula::upload_status,
            url: String?,
            visibility: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::Eula::visibility,
            multipart_chunk_size: Integer?,
            multipart_upload_id: String?,
            multipart_upload_urls: ::Array[WhopSDK::AccountFinancingApprovedWebhookEvent::Data::Eula::MultipartUploadURL]?,
            upload_headers: top,
            upload_url: String?
          }

          type upload_status = :pending | :processing | :ready | :failed

          module UploadStatus
            extend WhopSDK::Internal::Type::Enum

            PENDING: :pending
            PROCESSING: :processing
            READY: :ready
            FAILED: :failed

            def self?.values: -> ::Array[WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::Eula::upload_status]
          end

          type visibility = :public | :private

          module Visibility
            extend WhopSDK::Internal::Type::Enum

            PUBLIC: :public
            PRIVATE: :private

            def self?.values: -> ::Array[WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::Eula::visibility]
          end

          type multipart_upload_url = { part_number: Integer, url: String }

          class MultipartUploadURL < WhopSDK::Internal::Type::BaseModel
            attr_accessor part_number: Integer

            attr_accessor url: String

            def initialize: (part_number: Integer, url: String) -> void

            def to_hash: -> { part_number: Integer, url: String }
          end
        end

        type home_preference = :hide_member_count | :hide_members_card

        module HomePreference
          extend WhopSDK::Internal::Type::Enum

          HIDE_MEMBER_COUNT: :hide_member_count
          HIDE_MEMBERS_CARD: :hide_members_card

          def self?.values: -> ::Array[WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::home_preference]
        end

        type onboarding_type = :platform | :seller

        module OnboardingType
          extend WhopSDK::Internal::Type::Enum

          PLATFORM: :platform
          SELLER: :seller

          def self?.values: -> ::Array[WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::onboarding_type]
        end

        type opengraph_image_variant = :white | :black | :orange

        module OpengraphImageVariant
          extend WhopSDK::Internal::Type::Enum

          WHITE: :white
          BLACK: :black
          ORANGE: :orange

          def self?.values: -> ::Array[WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::opengraph_image_variant]
        end

        type owner =
          {
            id: String,
            name: String?,
            profile_picture: WhopSDK::AccountFinancingApprovedWebhookEvent::Data::Owner::ProfilePicture,
            username: String
          }

        class Owner < WhopSDK::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor name: String?

          attr_accessor profile_picture: WhopSDK::AccountFinancingApprovedWebhookEvent::Data::Owner::ProfilePicture

          attr_accessor username: String

          def initialize: (
            id: String,
            name: String?,
            profile_picture: WhopSDK::AccountFinancingApprovedWebhookEvent::Data::Owner::ProfilePicture,
            username: String
          ) -> void

          def to_hash: -> {
            id: String,
            name: String?,
            profile_picture: WhopSDK::AccountFinancingApprovedWebhookEvent::Data::Owner::ProfilePicture,
            username: String
          }

          type profile_picture = { url: String }

          class ProfilePicture < WhopSDK::Internal::Type::BaseModel
            attr_accessor url: String

            def initialize: (url: String) -> void

            def to_hash: -> { url: String }
          end
        end

        type parent_account =
          {
            id: String,
            logo_url: String?,
            route: String,
            title: String,
            fees: ::Hash[Symbol, WhopSDK::AccountFinancingApprovedWebhookEvent::Data::ParentAccount::Fee]
          }

        class ParentAccount < WhopSDK::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor logo_url: String?

          attr_accessor route: String

          attr_accessor title: String

          attr_reader fees: ::Hash[Symbol, WhopSDK::AccountFinancingApprovedWebhookEvent::Data::ParentAccount::Fee]?

          def fees=: (
            ::Hash[Symbol, WhopSDK::AccountFinancingApprovedWebhookEvent::Data::ParentAccount::Fee]
          ) -> ::Hash[Symbol, WhopSDK::AccountFinancingApprovedWebhookEvent::Data::ParentAccount::Fee]

          def initialize: (
            id: String,
            logo_url: String?,
            route: String,
            title: String,
            ?fees: ::Hash[Symbol, WhopSDK::AccountFinancingApprovedWebhookEvent::Data::ParentAccount::Fee]
          ) -> void

          def to_hash: -> {
            id: String,
            logo_url: String?,
            route: String,
            title: String,
            fees: ::Hash[Symbol, WhopSDK::AccountFinancingApprovedWebhookEvent::Data::ParentAccount::Fee]
          }

          type fee = { fixed_fee_usd: Float, percentage_fee: Float }

          class Fee < WhopSDK::Internal::Type::BaseModel
            attr_accessor fixed_fee_usd: Float

            attr_accessor percentage_fee: Float

            def initialize: (
              fixed_fee_usd: Float,
              percentage_fee: Float
            ) -> void

            def to_hash: -> { fixed_fee_usd: Float, percentage_fee: Float }
          end
        end

        type payment_controls =
          {
            dispute_alert_auto_refund: WhopSDK::AccountFinancingApprovedWebhookEvent::Data::PaymentControls::DisputeAlertAutoRefund,
            dispute_alert_fee_usd: Float?,
            :enforce_3ds => bool,
            financing_disabled: bool,
            high_risk_processing_fee_percentage: Float,
            pending_auto_topup_fee_percentage: Float,
            pending_balance_delay_days: Integer,
            reserve: WhopSDK::AccountFinancingApprovedWebhookEvent::Data::PaymentControls::Reserve,
            resolution_center_auto_refund: WhopSDK::AccountFinancingApprovedWebhookEvent::Data::PaymentControls::ResolutionCenterAutoRefund,
            restricted_payment_methods: ::Array[WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::PaymentControls::restricted_payment_method],
            undated_pending_reason: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::PaymentControls::undated_pending_reason?,
            withdrawal_schedule: WhopSDK::AccountFinancingApprovedWebhookEvent::Data::PaymentControls::WithdrawalSchedule
          }

        class PaymentControls < WhopSDK::Internal::Type::BaseModel
          attr_accessor dispute_alert_auto_refund: WhopSDK::AccountFinancingApprovedWebhookEvent::Data::PaymentControls::DisputeAlertAutoRefund

          attr_accessor dispute_alert_fee_usd: Float?

          attr_accessor enforce_3ds: bool

          attr_accessor financing_disabled: bool

          attr_accessor high_risk_processing_fee_percentage: Float

          attr_accessor pending_auto_topup_fee_percentage: Float

          attr_accessor pending_balance_delay_days: Integer

          attr_accessor reserve: WhopSDK::AccountFinancingApprovedWebhookEvent::Data::PaymentControls::Reserve

          attr_accessor resolution_center_auto_refund: WhopSDK::AccountFinancingApprovedWebhookEvent::Data::PaymentControls::ResolutionCenterAutoRefund

          attr_accessor restricted_payment_methods: ::Array[WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::PaymentControls::restricted_payment_method]

          attr_accessor undated_pending_reason: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::PaymentControls::undated_pending_reason?

          attr_accessor withdrawal_schedule: WhopSDK::AccountFinancingApprovedWebhookEvent::Data::PaymentControls::WithdrawalSchedule

          def initialize: (
            dispute_alert_auto_refund: WhopSDK::AccountFinancingApprovedWebhookEvent::Data::PaymentControls::DisputeAlertAutoRefund,
            dispute_alert_fee_usd: Float?,
            enforce_3ds: bool,
            financing_disabled: bool,
            high_risk_processing_fee_percentage: Float,
            pending_auto_topup_fee_percentage: Float,
            pending_balance_delay_days: Integer,
            reserve: WhopSDK::AccountFinancingApprovedWebhookEvent::Data::PaymentControls::Reserve,
            resolution_center_auto_refund: WhopSDK::AccountFinancingApprovedWebhookEvent::Data::PaymentControls::ResolutionCenterAutoRefund,
            restricted_payment_methods: ::Array[WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::PaymentControls::restricted_payment_method],
            undated_pending_reason: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::PaymentControls::undated_pending_reason?,
            withdrawal_schedule: WhopSDK::AccountFinancingApprovedWebhookEvent::Data::PaymentControls::WithdrawalSchedule
          ) -> void

          def to_hash: -> {
            dispute_alert_auto_refund: WhopSDK::AccountFinancingApprovedWebhookEvent::Data::PaymentControls::DisputeAlertAutoRefund,
            dispute_alert_fee_usd: Float?,
            :enforce_3ds => bool,
            financing_disabled: bool,
            high_risk_processing_fee_percentage: Float,
            pending_auto_topup_fee_percentage: Float,
            pending_balance_delay_days: Integer,
            reserve: WhopSDK::AccountFinancingApprovedWebhookEvent::Data::PaymentControls::Reserve,
            resolution_center_auto_refund: WhopSDK::AccountFinancingApprovedWebhookEvent::Data::PaymentControls::ResolutionCenterAutoRefund,
            restricted_payment_methods: ::Array[WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::PaymentControls::restricted_payment_method],
            undated_pending_reason: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::PaymentControls::undated_pending_reason?,
            withdrawal_schedule: WhopSDK::AccountFinancingApprovedWebhookEvent::Data::PaymentControls::WithdrawalSchedule
          }

          type dispute_alert_auto_refund =
            { locked: bool, threshold_usd: Float? }

          class DisputeAlertAutoRefund < WhopSDK::Internal::Type::BaseModel
            attr_accessor locked: bool

            attr_accessor threshold_usd: Float?

            def initialize: (locked: bool, threshold_usd: Float?) -> void

            def to_hash: -> { locked: bool, threshold_usd: Float? }
          end

          type reserve = { hold_period_days: Integer, percentage: Float? }

          class Reserve < WhopSDK::Internal::Type::BaseModel
            attr_accessor hold_period_days: Integer

            attr_accessor percentage: Float?

            def initialize: (
              hold_period_days: Integer,
              percentage: Float?
            ) -> void

            def to_hash: -> { hold_period_days: Integer, percentage: Float? }
          end

          type resolution_center_auto_refund =
            {
              card_threshold_usd: Float?,
              financing_threshold_usd: Float?,
              locked: bool,
              paypal_threshold_usd: Float?
            }

          class ResolutionCenterAutoRefund < WhopSDK::Internal::Type::BaseModel
            attr_accessor card_threshold_usd: Float?

            attr_accessor financing_threshold_usd: Float?

            attr_accessor locked: bool

            attr_accessor paypal_threshold_usd: Float?

            def initialize: (
              card_threshold_usd: Float?,
              financing_threshold_usd: Float?,
              locked: bool,
              paypal_threshold_usd: Float?
            ) -> void

            def to_hash: -> {
              card_threshold_usd: Float?,
              financing_threshold_usd: Float?,
              locked: bool,
              paypal_threshold_usd: Float?
            }
          end

          type restricted_payment_method =
            :card_visa
            | :card_mastercard
            | :card_american_express
            | :card_discover_global_network

          module RestrictedPaymentMethod
            extend WhopSDK::Internal::Type::Enum

            CARD_VISA: :card_visa
            CARD_MASTERCARD: :card_mastercard
            CARD_AMERICAN_EXPRESS: :card_american_express
            CARD_DISCOVER_GLOBAL_NETWORK: :card_discover_global_network

            def self?.values: -> ::Array[WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::PaymentControls::restricted_payment_method]
          end

          type undated_pending_reason =
            :kyc_incomplete
            | :pending_information_request
            | :withdrawals_disabled

          module UndatedPendingReason
            extend WhopSDK::Internal::Type::Enum

            KYC_INCOMPLETE: :kyc_incomplete
            PENDING_INFORMATION_REQUEST: :pending_information_request
            WITHDRAWALS_DISABLED: :withdrawals_disabled

            def self?.values: -> ::Array[WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::PaymentControls::undated_pending_reason]
          end

          type withdrawal_schedule =
            {
              day: Integer?,
              frequency: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::PaymentControls::WithdrawalSchedule::frequency,
              next_payout_date: String?
            }

          class WithdrawalSchedule < WhopSDK::Internal::Type::BaseModel
            attr_accessor day: Integer?

            attr_accessor frequency: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::PaymentControls::WithdrawalSchedule::frequency

            attr_accessor next_payout_date: String?

            def initialize: (
              day: Integer?,
              frequency: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::PaymentControls::WithdrawalSchedule::frequency,
              next_payout_date: String?
            ) -> void

            def to_hash: -> {
              day: Integer?,
              frequency: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::PaymentControls::WithdrawalSchedule::frequency,
              next_payout_date: String?
            }

            type frequency = :manual | :daily | :weekly | :monthly

            module Frequency
              extend WhopSDK::Internal::Type::Enum

              MANUAL: :manual
              DAILY: :daily
              WEEKLY: :weekly
              MONTHLY: :monthly

              def self?.values: -> ::Array[WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::PaymentControls::WithdrawalSchedule::frequency]
            end
          end
        end

        type privacy_policy =
          {
            id: String,
            content_type: String?,
            created_at: String,
            filename: String?,
            object: String,
            size: Integer?,
            upload_status: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::PrivacyPolicy::upload_status,
            url: String?,
            visibility: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::PrivacyPolicy::visibility,
            multipart_chunk_size: Integer?,
            multipart_upload_id: String?,
            multipart_upload_urls: ::Array[WhopSDK::AccountFinancingApprovedWebhookEvent::Data::PrivacyPolicy::MultipartUploadURL]?,
            upload_headers: top,
            upload_url: String?
          }

        class PrivacyPolicy < WhopSDK::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor content_type: String?

          attr_accessor created_at: String

          attr_accessor filename: String?

          attr_accessor object: String

          attr_accessor size: Integer?

          attr_accessor upload_status: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::PrivacyPolicy::upload_status

          attr_accessor url: String?

          attr_accessor visibility: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::PrivacyPolicy::visibility

          attr_accessor multipart_chunk_size: Integer?

          attr_accessor multipart_upload_id: String?

          attr_accessor multipart_upload_urls: ::Array[WhopSDK::AccountFinancingApprovedWebhookEvent::Data::PrivacyPolicy::MultipartUploadURL]?

          attr_reader upload_headers: top?

          def upload_headers=: (top) -> top

          attr_accessor upload_url: String?

          def initialize: (
            id: String,
            content_type: String?,
            created_at: String,
            filename: String?,
            object: String,
            size: Integer?,
            upload_status: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::PrivacyPolicy::upload_status,
            url: String?,
            visibility: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::PrivacyPolicy::visibility,
            ?multipart_chunk_size: Integer?,
            ?multipart_upload_id: String?,
            ?multipart_upload_urls: ::Array[WhopSDK::AccountFinancingApprovedWebhookEvent::Data::PrivacyPolicy::MultipartUploadURL]?,
            ?upload_headers: top,
            ?upload_url: String?
          ) -> void

          def to_hash: -> {
            id: String,
            content_type: String?,
            created_at: String,
            filename: String?,
            object: String,
            size: Integer?,
            upload_status: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::PrivacyPolicy::upload_status,
            url: String?,
            visibility: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::PrivacyPolicy::visibility,
            multipart_chunk_size: Integer?,
            multipart_upload_id: String?,
            multipart_upload_urls: ::Array[WhopSDK::AccountFinancingApprovedWebhookEvent::Data::PrivacyPolicy::MultipartUploadURL]?,
            upload_headers: top,
            upload_url: String?
          }

          type upload_status = :pending | :processing | :ready | :failed

          module UploadStatus
            extend WhopSDK::Internal::Type::Enum

            PENDING: :pending
            PROCESSING: :processing
            READY: :ready
            FAILED: :failed

            def self?.values: -> ::Array[WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::PrivacyPolicy::upload_status]
          end

          type visibility = :public | :private

          module Visibility
            extend WhopSDK::Internal::Type::Enum

            PUBLIC: :public
            PRIVATE: :private

            def self?.values: -> ::Array[WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::PrivacyPolicy::visibility]
          end

          type multipart_upload_url = { part_number: Integer, url: String }

          class MultipartUploadURL < WhopSDK::Internal::Type::BaseModel
            attr_accessor part_number: Integer

            attr_accessor url: String

            def initialize: (part_number: Integer, url: String) -> void

            def to_hash: -> { part_number: Integer, url: String }
          end
        end

        type recommended_action =
          {
            action: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::RecommendedAction::action,
            blocked_capabilities: ::Array[String],
            cta: String,
            cta_label: String,
            description: String,
            icon_url: String?,
            impact_score: Integer?,
            reasoning: String?,
            status: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::RecommendedAction::status,
            title: String
          }

        class RecommendedAction < WhopSDK::Internal::Type::BaseModel
          attr_accessor action: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::RecommendedAction::action

          attr_accessor blocked_capabilities: ::Array[String]

          attr_accessor cta: String

          attr_accessor cta_label: String

          attr_accessor description: String

          attr_accessor icon_url: String?

          attr_accessor impact_score: Integer?

          attr_accessor reasoning: String?

          attr_accessor status: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::RecommendedAction::status

          attr_accessor title: String

          def initialize: (
            action: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::RecommendedAction::action,
            blocked_capabilities: ::Array[String],
            cta: String,
            cta_label: String,
            description: String,
            icon_url: String?,
            impact_score: Integer?,
            reasoning: String?,
            status: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::RecommendedAction::status,
            title: String
          ) -> void

          def to_hash: -> {
            action: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::RecommendedAction::action,
            blocked_capabilities: ::Array[String],
            cta: String,
            cta_label: String,
            description: String,
            icon_url: String?,
            impact_score: Integer?,
            reasoning: String?,
            status: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::RecommendedAction::status,
            title: String
          }

          type action =
            :theme_business
            | :create_product
            | :create_plan
            | :verify_identity
            | :connect_affiliate_program
            | :create_promotion
            | :migrate_from_stripe
            | :accept_first_payment
            | :launch_first_ad
            | :launch_draft_campaign
            | :increase_ad_budget
            | :refresh_ad_creatives
            | :fix_ad_billing
            | :exclude_customers_from_ads
            | :retarget_abandoned_checkouts
            | :fix_funnel_dropoff
            | :invite_team_member
            | :enable_tax_collection
            | :create_card
            | :apply_for_financing

          module Action
            extend WhopSDK::Internal::Type::Enum

            THEME_BUSINESS: :theme_business
            CREATE_PRODUCT: :create_product
            CREATE_PLAN: :create_plan
            VERIFY_IDENTITY: :verify_identity
            CONNECT_AFFILIATE_PROGRAM: :connect_affiliate_program
            CREATE_PROMOTION: :create_promotion
            MIGRATE_FROM_STRIPE: :migrate_from_stripe
            ACCEPT_FIRST_PAYMENT: :accept_first_payment
            LAUNCH_FIRST_AD: :launch_first_ad
            LAUNCH_DRAFT_CAMPAIGN: :launch_draft_campaign
            INCREASE_AD_BUDGET: :increase_ad_budget
            REFRESH_AD_CREATIVES: :refresh_ad_creatives
            FIX_AD_BILLING: :fix_ad_billing
            EXCLUDE_CUSTOMERS_FROM_ADS: :exclude_customers_from_ads
            RETARGET_ABANDONED_CHECKOUTS: :retarget_abandoned_checkouts
            FIX_FUNNEL_DROPOFF: :fix_funnel_dropoff
            INVITE_TEAM_MEMBER: :invite_team_member
            ENABLE_TAX_COLLECTION: :enable_tax_collection
            CREATE_CARD: :create_card
            APPLY_FOR_FINANCING: :apply_for_financing

            def self?.values: -> ::Array[WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::RecommendedAction::action]
          end

          type status = :optional

          module Status
            extend WhopSDK::Internal::Type::Enum

            OPTIONAL: :optional

            def self?.values: -> ::Array[WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::RecommendedAction::status]
          end
        end

        type required_action =
          {
            action: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::RequiredAction::action,
            blocked_capabilities: ::Array[String],
            cta: String?,
            cta_label: String,
            description: String,
            icon_url: String?,
            status: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::RequiredAction::status,
            title: String
          }

        class RequiredAction < WhopSDK::Internal::Type::BaseModel
          attr_accessor action: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::RequiredAction::action

          attr_accessor blocked_capabilities: ::Array[String]

          attr_accessor cta: String?

          attr_accessor cta_label: String

          attr_accessor description: String

          attr_accessor icon_url: String?

          attr_accessor status: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::RequiredAction::status

          attr_accessor title: String

          def initialize: (
            action: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::RequiredAction::action,
            blocked_capabilities: ::Array[String],
            cta: String?,
            cta_label: String,
            description: String,
            icon_url: String?,
            status: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::RequiredAction::status,
            title: String
          ) -> void

          def to_hash: -> {
            action: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::RequiredAction::action,
            blocked_capabilities: ::Array[String],
            cta: String?,
            cta_label: String,
            description: String,
            icon_url: String?,
            status: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::RequiredAction::status,
            title: String
          }

          type action =
            :deposit_funds
            | :accept_airwallex_terms
            | :submit_information_request
            | :update_automatic_withdrawal_method
            | :reauthorize_payout_methods
            | :update_payout_profile
            | :card_usage_review
            | :verify_identity
            | :sign_formation_documents
            | :connect_fulfillment_tracker
            | :setup_apple_pay_domains
            | :configure_tax_remitter
            | :add_vat_registration

          module Action
            extend WhopSDK::Internal::Type::Enum

            DEPOSIT_FUNDS: :deposit_funds
            ACCEPT_AIRWALLEX_TERMS: :accept_airwallex_terms
            SUBMIT_INFORMATION_REQUEST: :submit_information_request
            UPDATE_AUTOMATIC_WITHDRAWAL_METHOD: :update_automatic_withdrawal_method
            REAUTHORIZE_PAYOUT_METHODS: :reauthorize_payout_methods
            UPDATE_PAYOUT_PROFILE: :update_payout_profile
            CARD_USAGE_REVIEW: :card_usage_review
            VERIFY_IDENTITY: :verify_identity
            SIGN_FORMATION_DOCUMENTS: :sign_formation_documents
            CONNECT_FULFILLMENT_TRACKER: :connect_fulfillment_tracker
            SETUP_APPLE_PAY_DOMAINS: :setup_apple_pay_domains
            CONFIGURE_TAX_REMITTER: :configure_tax_remitter
            ADD_VAT_REGISTRATION: :add_vat_registration

            def self?.values: -> ::Array[WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::RequiredAction::action]
          end

          type status = :required | :pending

          module Status
            extend WhopSDK::Internal::Type::Enum

            REQUIRED: :required
            PENDING: :pending

            def self?.values: -> ::Array[WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::RequiredAction::status]
          end
        end

        type return_policy =
          {
            id: String,
            content_type: String?,
            created_at: String,
            filename: String?,
            object: String,
            size: Integer?,
            upload_status: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::ReturnPolicy::upload_status,
            url: String?,
            visibility: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::ReturnPolicy::visibility,
            multipart_chunk_size: Integer?,
            multipart_upload_id: String?,
            multipart_upload_urls: ::Array[WhopSDK::AccountFinancingApprovedWebhookEvent::Data::ReturnPolicy::MultipartUploadURL]?,
            upload_headers: top,
            upload_url: String?
          }

        class ReturnPolicy < WhopSDK::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor content_type: String?

          attr_accessor created_at: String

          attr_accessor filename: String?

          attr_accessor object: String

          attr_accessor size: Integer?

          attr_accessor upload_status: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::ReturnPolicy::upload_status

          attr_accessor url: String?

          attr_accessor visibility: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::ReturnPolicy::visibility

          attr_accessor multipart_chunk_size: Integer?

          attr_accessor multipart_upload_id: String?

          attr_accessor multipart_upload_urls: ::Array[WhopSDK::AccountFinancingApprovedWebhookEvent::Data::ReturnPolicy::MultipartUploadURL]?

          attr_reader upload_headers: top?

          def upload_headers=: (top) -> top

          attr_accessor upload_url: String?

          def initialize: (
            id: String,
            content_type: String?,
            created_at: String,
            filename: String?,
            object: String,
            size: Integer?,
            upload_status: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::ReturnPolicy::upload_status,
            url: String?,
            visibility: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::ReturnPolicy::visibility,
            ?multipart_chunk_size: Integer?,
            ?multipart_upload_id: String?,
            ?multipart_upload_urls: ::Array[WhopSDK::AccountFinancingApprovedWebhookEvent::Data::ReturnPolicy::MultipartUploadURL]?,
            ?upload_headers: top,
            ?upload_url: String?
          ) -> void

          def to_hash: -> {
            id: String,
            content_type: String?,
            created_at: String,
            filename: String?,
            object: String,
            size: Integer?,
            upload_status: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::ReturnPolicy::upload_status,
            url: String?,
            visibility: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::ReturnPolicy::visibility,
            multipart_chunk_size: Integer?,
            multipart_upload_id: String?,
            multipart_upload_urls: ::Array[WhopSDK::AccountFinancingApprovedWebhookEvent::Data::ReturnPolicy::MultipartUploadURL]?,
            upload_headers: top,
            upload_url: String?
          }

          type upload_status = :pending | :processing | :ready | :failed

          module UploadStatus
            extend WhopSDK::Internal::Type::Enum

            PENDING: :pending
            PROCESSING: :processing
            READY: :ready
            FAILED: :failed

            def self?.values: -> ::Array[WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::ReturnPolicy::upload_status]
          end

          type visibility = :public | :private

          module Visibility
            extend WhopSDK::Internal::Type::Enum

            PUBLIC: :public
            PRIVATE: :private

            def self?.values: -> ::Array[WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::ReturnPolicy::visibility]
          end

          type multipart_upload_url = { part_number: Integer, url: String }

          class MultipartUploadURL < WhopSDK::Internal::Type::BaseModel
            attr_accessor part_number: Integer

            attr_accessor url: String

            def initialize: (part_number: Integer, url: String) -> void

            def to_hash: -> { part_number: Integer, url: String }
          end
        end

        type social_link =
          {
            id: String,
            title: String?,
            url: String,
            website: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::SocialLink::website
          }

        class SocialLink < WhopSDK::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor title: String?

          attr_accessor url: String

          attr_accessor website: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::SocialLink::website

          def initialize: (
            id: String,
            title: String?,
            url: String,
            website: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::SocialLink::website
          ) -> void

          def to_hash: -> {
            id: String,
            title: String?,
            url: String,
            website: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::SocialLink::website
          }

          type website =
            :x
            | :instagram
            | :facebook
            | :tiktok
            | :youtube
            | :linkedin
            | :twitch
            | :website
            | :custom

          module Website
            extend WhopSDK::Internal::Type::Enum

            X: :x
            INSTAGRAM: :instagram
            FACEBOOK: :facebook
            TIKTOK: :tiktok
            YOUTUBE: :youtube
            LINKEDIN: :linkedin
            TWITCH: :twitch
            WEBSITE: :website
            CUSTOM: :custom

            def self?.values: -> ::Array[WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::SocialLink::website]
          end
        end

        type store_page_config =
          {
            accent_color: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::StorePageConfig::accent_color?,
            layout: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::StorePageConfig::layout?,
            profile_variant: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::StorePageConfig::profile_variant?,
            whop_affiliate_link: bool
          }

        class StorePageConfig < WhopSDK::Internal::Type::BaseModel
          attr_accessor accent_color: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::StorePageConfig::accent_color?

          attr_accessor layout: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::StorePageConfig::layout?

          attr_accessor profile_variant: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::StorePageConfig::profile_variant?

          attr_accessor whop_affiliate_link: bool

          def initialize: (
            accent_color: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::StorePageConfig::accent_color?,
            layout: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::StorePageConfig::layout?,
            profile_variant: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::StorePageConfig::profile_variant?,
            whop_affiliate_link: bool
          ) -> void

          def to_hash: -> {
            accent_color: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::StorePageConfig::accent_color?,
            layout: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::StorePageConfig::layout?,
            profile_variant: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::StorePageConfig::profile_variant?,
            whop_affiliate_link: bool
          }

          type accent_color =
            :ruby
            | :tomato
            | :red
            | :crimson
            | :pink
            | :plum
            | :purple
            | :violet
            | :iris
            | :cyan
            | :teal
            | :jade
            | :green
            | :grass
            | :brown
            | :blue
            | :orange
            | :indigo
            | :sky
            | :mint
            | :yellow
            | :amber
            | :lime
            | :lemon
            | :magenta
            | :gold
            | :bronze
            | :gray

          module AccentColor
            extend WhopSDK::Internal::Type::Enum

            RUBY: :ruby
            TOMATO: :tomato
            RED: :red
            CRIMSON: :crimson
            PINK: :pink
            PLUM: :plum
            PURPLE: :purple
            VIOLET: :violet
            IRIS: :iris
            CYAN: :cyan
            TEAL: :teal
            JADE: :jade
            GREEN: :green
            GRASS: :grass
            BROWN: :brown
            BLUE: :blue
            ORANGE: :orange
            INDIGO: :indigo
            SKY: :sky
            MINT: :mint
            YELLOW: :yellow
            AMBER: :amber
            LIME: :lime
            LEMON: :lemon
            MAGENTA: :magenta
            GOLD: :gold
            BRONZE: :bronze
            GRAY: :gray

            def self?.values: -> ::Array[WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::StorePageConfig::accent_color]
          end

          type layout = :featured | :compact

          module Layout
            extend WhopSDK::Internal::Type::Enum

            FEATURED: :featured
            COMPACT: :compact

            def self?.values: -> ::Array[WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::StorePageConfig::layout]
          end

          type profile_variant = :personal | :business

          module ProfileVariant
            extend WhopSDK::Internal::Type::Enum

            PERSONAL: :personal
            BUSINESS: :business

            def self?.values: -> ::Array[WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::StorePageConfig::profile_variant]
          end
        end

        type tax_identifier =
          {
            id: String,
            tax_id_type: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::TaxIdentifier::tax_id_type,
            tax_id_value: String
          }

        class TaxIdentifier < WhopSDK::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor tax_id_type: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::TaxIdentifier::tax_id_type

          attr_accessor tax_id_value: String

          def initialize: (
            id: String,
            tax_id_type: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::TaxIdentifier::tax_id_type,
            tax_id_value: String
          ) -> void

          def to_hash: -> {
            id: String,
            tax_id_type: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::TaxIdentifier::tax_id_type,
            tax_id_value: String
          }

          type tax_id_type =
            :ad_nrt
            | :ao_tin
            | :ar_cuit
            | :al_tin
            | :am_tin
            | :aw_tin
            | :au_abn
            | :au_arn
            | :eu_vat
            | :az_tin
            | :bs_tin
            | :bh_vat
            | :bd_bin
            | :bb_tin
            | :by_tin
            | :bj_ifu
            | :bo_tin
            | :ba_tin
            | :br_cnpj
            | :br_cpf
            | :bg_uic
            | :bf_ifu
            | :kh_tin
            | :cm_niu
            | :ca_bn
            | :ca_gst_hst
            | :ca_pst_bc
            | :ca_pst_mb
            | :ca_pst_sk
            | :ca_qst
            | :cv_nif
            | :cl_tin
            | :cn_tin
            | :co_nit
            | :cd_nif
            | :cr_tin
            | :hr_oib
            | :do_rcn
            | :ec_ruc
            | :eg_tin
            | :sv_nit
            | :et_tin
            | :eu_oss_vat
            | :ge_vat
            | :gh_tin
            | :de_stn
            | :gb_vat
            | :gn_nif
            | :hk_br
            | :hu_tin
            | :is_vat
            | :in_gst
            | :id_npwp
            | :il_vat
            | :jp_cn
            | :jp_rn
            | :jp_trn
            | :kz_bin
            | :ke_pin
            | :kg_tin
            | :la_tin
            | :li_uid
            | :li_vat
            | :my_frp
            | :my_itn
            | :my_sst
            | :mr_nif
            | :mx_rfc
            | :md_vat
            | :me_pib
            | :ma_vat
            | :np_pan
            | :nz_gst
            | :ng_tin
            | :mk_vat
            | :no_vat
            | :no_voec
            | :om_vat
            | :pe_ruc
            | :ph_tin
            | :pl_nip
            | :ro_tin
            | :ru_inn
            | :ru_kpp
            | :sa_vat
            | :sn_ninea
            | :rs_pib
            | :sg_gst
            | :sg_uen
            | :si_tin
            | :za_vat
            | :kr_brn
            | :es_cif
            | :ch_uid
            | :ch_vat
            | :tw_vat
            | :tj_tin
            | :tz_vat
            | :th_vat
            | :tr_tin
            | :ug_tin
            | :ua_vat
            | :ae_trn
            | :us_ein
            | :uy_ruc
            | :uz_tin
            | :uz_vat
            | :ve_rif
            | :vn_tin
            | :zm_tin
            | :zw_tin
            | :sr_fin
            | :xi_vat

          module TaxIDType
            extend WhopSDK::Internal::Type::Enum

            AD_NRT: :ad_nrt
            AO_TIN: :ao_tin
            AR_CUIT: :ar_cuit
            AL_TIN: :al_tin
            AM_TIN: :am_tin
            AW_TIN: :aw_tin
            AU_ABN: :au_abn
            AU_ARN: :au_arn
            EU_VAT: :eu_vat
            AZ_TIN: :az_tin
            BS_TIN: :bs_tin
            BH_VAT: :bh_vat
            BD_BIN: :bd_bin
            BB_TIN: :bb_tin
            BY_TIN: :by_tin
            BJ_IFU: :bj_ifu
            BO_TIN: :bo_tin
            BA_TIN: :ba_tin
            BR_CNPJ: :br_cnpj
            BR_CPF: :br_cpf
            BG_UIC: :bg_uic
            BF_IFU: :bf_ifu
            KH_TIN: :kh_tin
            CM_NIU: :cm_niu
            CA_BN: :ca_bn
            CA_GST_HST: :ca_gst_hst
            CA_PST_BC: :ca_pst_bc
            CA_PST_MB: :ca_pst_mb
            CA_PST_SK: :ca_pst_sk
            CA_QST: :ca_qst
            CV_NIF: :cv_nif
            CL_TIN: :cl_tin
            CN_TIN: :cn_tin
            CO_NIT: :co_nit
            CD_NIF: :cd_nif
            CR_TIN: :cr_tin
            HR_OIB: :hr_oib
            DO_RCN: :do_rcn
            EC_RUC: :ec_ruc
            EG_TIN: :eg_tin
            SV_NIT: :sv_nit
            ET_TIN: :et_tin
            EU_OSS_VAT: :eu_oss_vat
            GE_VAT: :ge_vat
            GH_TIN: :gh_tin
            DE_STN: :de_stn
            GB_VAT: :gb_vat
            GN_NIF: :gn_nif
            HK_BR: :hk_br
            HU_TIN: :hu_tin
            IS_VAT: :is_vat
            IN_GST: :in_gst
            ID_NPWP: :id_npwp
            IL_VAT: :il_vat
            JP_CN: :jp_cn
            JP_RN: :jp_rn
            JP_TRN: :jp_trn
            KZ_BIN: :kz_bin
            KE_PIN: :ke_pin
            KG_TIN: :kg_tin
            LA_TIN: :la_tin
            LI_UID: :li_uid
            LI_VAT: :li_vat
            MY_FRP: :my_frp
            MY_ITN: :my_itn
            MY_SST: :my_sst
            MR_NIF: :mr_nif
            MX_RFC: :mx_rfc
            MD_VAT: :md_vat
            ME_PIB: :me_pib
            MA_VAT: :ma_vat
            NP_PAN: :np_pan
            NZ_GST: :nz_gst
            NG_TIN: :ng_tin
            MK_VAT: :mk_vat
            NO_VAT: :no_vat
            NO_VOEC: :no_voec
            OM_VAT: :om_vat
            PE_RUC: :pe_ruc
            PH_TIN: :ph_tin
            PL_NIP: :pl_nip
            RO_TIN: :ro_tin
            RU_INN: :ru_inn
            RU_KPP: :ru_kpp
            SA_VAT: :sa_vat
            SN_NINEA: :sn_ninea
            RS_PIB: :rs_pib
            SG_GST: :sg_gst
            SG_UEN: :sg_uen
            SI_TIN: :si_tin
            ZA_VAT: :za_vat
            KR_BRN: :kr_brn
            ES_CIF: :es_cif
            CH_UID: :ch_uid
            CH_VAT: :ch_vat
            TW_VAT: :tw_vat
            TJ_TIN: :tj_tin
            TZ_VAT: :tz_vat
            TH_VAT: :th_vat
            TR_TIN: :tr_tin
            UG_TIN: :ug_tin
            UA_VAT: :ua_vat
            AE_TRN: :ae_trn
            US_EIN: :us_ein
            UY_RUC: :uy_ruc
            UZ_TIN: :uz_tin
            UZ_VAT: :uz_vat
            VE_RIF: :ve_rif
            VN_TIN: :vn_tin
            ZM_TIN: :zm_tin
            ZW_TIN: :zw_tin
            SR_FIN: :sr_fin
            XI_VAT: :xi_vat

            def self?.values: -> ::Array[WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::TaxIdentifier::tax_id_type]
          end
        end

        type tax_remitted_by = :whop | :self | :none

        module TaxRemittedBy
          extend WhopSDK::Internal::Type::Enum

          WHOP: :whop
          SELF: :self
          NONE: :none

          def self?.values: -> ::Array[WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::tax_remitted_by]
        end

        type tax_type = :inclusive | :exclusive

        module TaxType
          extend WhopSDK::Internal::Type::Enum

          INCLUSIVE: :inclusive
          EXCLUSIVE: :exclusive

          def self?.values: -> ::Array[WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::tax_type]
        end

        type terms_of_service =
          {
            id: String,
            content_type: String?,
            created_at: String,
            filename: String?,
            object: String,
            size: Integer?,
            upload_status: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::TermsOfService::upload_status,
            url: String?,
            visibility: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::TermsOfService::visibility,
            multipart_chunk_size: Integer?,
            multipart_upload_id: String?,
            multipart_upload_urls: ::Array[WhopSDK::AccountFinancingApprovedWebhookEvent::Data::TermsOfService::MultipartUploadURL]?,
            upload_headers: top,
            upload_url: String?
          }

        class TermsOfService < WhopSDK::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor content_type: String?

          attr_accessor created_at: String

          attr_accessor filename: String?

          attr_accessor object: String

          attr_accessor size: Integer?

          attr_accessor upload_status: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::TermsOfService::upload_status

          attr_accessor url: String?

          attr_accessor visibility: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::TermsOfService::visibility

          attr_accessor multipart_chunk_size: Integer?

          attr_accessor multipart_upload_id: String?

          attr_accessor multipart_upload_urls: ::Array[WhopSDK::AccountFinancingApprovedWebhookEvent::Data::TermsOfService::MultipartUploadURL]?

          attr_reader upload_headers: top?

          def upload_headers=: (top) -> top

          attr_accessor upload_url: String?

          def initialize: (
            id: String,
            content_type: String?,
            created_at: String,
            filename: String?,
            object: String,
            size: Integer?,
            upload_status: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::TermsOfService::upload_status,
            url: String?,
            visibility: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::TermsOfService::visibility,
            ?multipart_chunk_size: Integer?,
            ?multipart_upload_id: String?,
            ?multipart_upload_urls: ::Array[WhopSDK::AccountFinancingApprovedWebhookEvent::Data::TermsOfService::MultipartUploadURL]?,
            ?upload_headers: top,
            ?upload_url: String?
          ) -> void

          def to_hash: -> {
            id: String,
            content_type: String?,
            created_at: String,
            filename: String?,
            object: String,
            size: Integer?,
            upload_status: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::TermsOfService::upload_status,
            url: String?,
            visibility: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::TermsOfService::visibility,
            multipart_chunk_size: Integer?,
            multipart_upload_id: String?,
            multipart_upload_urls: ::Array[WhopSDK::AccountFinancingApprovedWebhookEvent::Data::TermsOfService::MultipartUploadURL]?,
            upload_headers: top,
            upload_url: String?
          }

          type upload_status = :pending | :processing | :ready | :failed

          module UploadStatus
            extend WhopSDK::Internal::Type::Enum

            PENDING: :pending
            PROCESSING: :processing
            READY: :ready
            FAILED: :failed

            def self?.values: -> ::Array[WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::TermsOfService::upload_status]
          end

          type visibility = :public | :private

          module Visibility
            extend WhopSDK::Internal::Type::Enum

            PUBLIC: :public
            PRIVATE: :private

            def self?.values: -> ::Array[WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::TermsOfService::visibility]
          end

          type multipart_upload_url = { part_number: Integer, url: String }

          class MultipartUploadURL < WhopSDK::Internal::Type::BaseModel
            attr_accessor part_number: Integer

            attr_accessor url: String

            def initialize: (part_number: Integer, url: String) -> void

            def to_hash: -> { part_number: Integer, url: String }
          end
        end

        type three_ds_level = :mandate_challenge

        module ThreeDSLevel
          extend WhopSDK::Internal::Type::Enum

          MANDATE_CHALLENGE: :mandate_challenge

          def self?.values: -> ::Array[WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::three_ds_level]
        end

        type wallet =
          {
            id: String,
            address: String,
            network: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::Wallet::network
          }

        class Wallet < WhopSDK::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor address: String

          attr_accessor network: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::Wallet::network

          def initialize: (
            id: String,
            address: String,
            network: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::Wallet::network
          ) -> void

          def to_hash: -> {
            id: String,
            address: String,
            network: WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::Wallet::network
          }

          type network = :solana | :ethereum | :bitcoin

          module Network
            extend WhopSDK::Internal::Type::Enum

            SOLANA: :solana
            ETHEREUM: :ethereum
            BITCOIN: :bitcoin

            def self?.values: -> ::Array[WhopSDK::Models::AccountFinancingApprovedWebhookEvent::Data::Wallet::network]
          end
        end
      end
    end
  end
end
