module WhopSDK
  module Models
    type ad =
      {
        id: String,
        ad_campaign: WhopSDK::Ad::AdCampaign,
        ad_group: WhopSDK::Ad::AdGroup,
        clicks: Integer,
        cost_per_lead: Float?,
        cost_per_purchase: Float?,
        cost_per_result: Float?,
        cpc: Float,
        cpm: Float,
        created_at: Time,
        ctr: Float,
        frequency: Float?,
        impressions: Integer,
        issues: ::Array[WhopSDK::Ad::Issue],
        leads: Integer,
        platform: WhopSDK::Models::ad_campaign_platform,
        purchase_value: Float,
        purchases: Integer,
        reach: Integer,
        roas: Float,
        spend: Float,
        spend_currency: WhopSDK::Models::currency?,
        status: WhopSDK::Models::external_ad_status,
        title: String?,
        unique_ctr: Float?,
        updated_at: Time
      }

    class Ad < WhopSDK::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor ad_campaign: WhopSDK::Ad::AdCampaign

      attr_accessor ad_group: WhopSDK::Ad::AdGroup

      attr_accessor clicks: Integer

      attr_accessor cost_per_lead: Float?

      attr_accessor cost_per_purchase: Float?

      attr_accessor cost_per_result: Float?

      attr_accessor cpc: Float

      attr_accessor cpm: Float

      attr_accessor created_at: Time

      attr_accessor ctr: Float

      attr_accessor frequency: Float?

      attr_accessor impressions: Integer

      attr_accessor issues: ::Array[WhopSDK::Ad::Issue]

      attr_accessor leads: Integer

      attr_accessor platform: WhopSDK::Models::ad_campaign_platform

      attr_accessor purchase_value: Float

      attr_accessor purchases: Integer

      attr_accessor reach: Integer

      attr_accessor roas: Float

      attr_accessor spend: Float

      attr_accessor spend_currency: WhopSDK::Models::currency?

      attr_accessor status: WhopSDK::Models::external_ad_status

      attr_accessor title: String?

      attr_accessor unique_ctr: Float?

      attr_accessor updated_at: Time

      def initialize: (
        id: String,
        ad_campaign: WhopSDK::Ad::AdCampaign,
        ad_group: WhopSDK::Ad::AdGroup,
        clicks: Integer,
        cost_per_lead: Float?,
        cost_per_purchase: Float?,
        cost_per_result: Float?,
        cpc: Float,
        cpm: Float,
        created_at: Time,
        ctr: Float,
        frequency: Float?,
        impressions: Integer,
        issues: ::Array[WhopSDK::Ad::Issue],
        leads: Integer,
        platform: WhopSDK::Models::ad_campaign_platform,
        purchase_value: Float,
        purchases: Integer,
        reach: Integer,
        roas: Float,
        spend: Float,
        spend_currency: WhopSDK::Models::currency?,
        status: WhopSDK::Models::external_ad_status,
        title: String?,
        unique_ctr: Float?,
        updated_at: Time
      ) -> void

      def to_hash: -> {
        id: String,
        ad_campaign: WhopSDK::Ad::AdCampaign,
        ad_group: WhopSDK::Ad::AdGroup,
        clicks: Integer,
        cost_per_lead: Float?,
        cost_per_purchase: Float?,
        cost_per_result: Float?,
        cpc: Float,
        cpm: Float,
        created_at: Time,
        ctr: Float,
        frequency: Float?,
        impressions: Integer,
        issues: ::Array[WhopSDK::Ad::Issue],
        leads: Integer,
        platform: WhopSDK::Models::ad_campaign_platform,
        purchase_value: Float,
        purchases: Integer,
        reach: Integer,
        roas: Float,
        spend: Float,
        spend_currency: WhopSDK::Models::currency?,
        status: WhopSDK::Models::external_ad_status,
        title: String?,
        unique_ctr: Float?,
        updated_at: Time
      }

      type ad_campaign = { id: String }

      class AdCampaign < WhopSDK::Internal::Type::BaseModel
        attr_accessor id: String

        def initialize: (id: String) -> void

        def to_hash: -> { id: String }
      end

      type ad_group = { id: String }

      class AdGroup < WhopSDK::Internal::Type::BaseModel
        attr_accessor id: String

        def initialize: (id: String) -> void

        def to_hash: -> { id: String }
      end

      type issue =
        {
          created_at: Time,
          error_code: String?,
          error_message: String?,
          error_summary: String,
          resolution_status: WhopSDK::Models::Ad::Issue::resolution_status,
          resource_id: String?,
          resource_type: String
        }

      class Issue < WhopSDK::Internal::Type::BaseModel
        attr_accessor created_at: Time

        attr_accessor error_code: String?

        attr_accessor error_message: String?

        attr_accessor error_summary: String

        attr_accessor resolution_status: WhopSDK::Models::Ad::Issue::resolution_status

        attr_accessor resource_id: String?

        attr_accessor resource_type: String

        def initialize: (
          created_at: Time,
          error_code: String?,
          error_message: String?,
          error_summary: String,
          resolution_status: WhopSDK::Models::Ad::Issue::resolution_status,
          resource_id: String?,
          resource_type: String
        ) -> void

        def to_hash: -> {
          created_at: Time,
          error_code: String?,
          error_message: String?,
          error_summary: String,
          resolution_status: WhopSDK::Models::Ad::Issue::resolution_status,
          resource_id: String?,
          resource_type: String
        }

        type resolution_status = :open | :resolved | :acknowledged

        module ResolutionStatus
          extend WhopSDK::Internal::Type::Enum

          OPEN: :open
          RESOLVED: :resolved
          ACKNOWLEDGED: :acknowledged

          def self?.values: -> ::Array[WhopSDK::Models::Ad::Issue::resolution_status]
        end
      end
    end
  end
end
