module WhopSDK
  module Models
    type ad_campaign_create_params =
      {
        objective: WhopSDK::Models::AdCampaignCreateParams::objective,
        platform: WhopSDK::Models::AdCampaignCreateParams::platform,
        title: String,
        account_id: String,
        bid_type: WhopSDK::Models::AdCampaignCreateParams::bid_type,
        budget_amount: Float,
        budget_optimization: WhopSDK::Models::AdCampaignCreateParams::budget_optimization,
        budget_type: WhopSDK::Models::AdCampaignCreateParams::budget_type,
        desired_cost_per_result: Float,
        ends_at: String,
        special_ad_categories: ::Array[WhopSDK::Models::AdCampaignCreateParams::special_ad_category],
        starts_at: String
      }
      & WhopSDK::Internal::Type::request_parameters

    class AdCampaignCreateParams < WhopSDK::Internal::Type::BaseModel
      extend WhopSDK::Internal::Type::RequestParameters::Converter
      include WhopSDK::Internal::Type::RequestParameters

      attr_accessor objective: WhopSDK::Models::AdCampaignCreateParams::objective

      attr_accessor platform: WhopSDK::Models::AdCampaignCreateParams::platform

      attr_accessor title: String

      attr_reader account_id: String?

      def account_id=: (String) -> String

      attr_reader bid_type: WhopSDK::Models::AdCampaignCreateParams::bid_type?

      def bid_type=: (
        WhopSDK::Models::AdCampaignCreateParams::bid_type
      ) -> WhopSDK::Models::AdCampaignCreateParams::bid_type

      attr_reader budget_amount: Float?

      def budget_amount=: (Float) -> Float

      attr_reader budget_optimization: WhopSDK::Models::AdCampaignCreateParams::budget_optimization?

      def budget_optimization=: (
        WhopSDK::Models::AdCampaignCreateParams::budget_optimization
      ) -> WhopSDK::Models::AdCampaignCreateParams::budget_optimization

      attr_reader budget_type: WhopSDK::Models::AdCampaignCreateParams::budget_type?

      def budget_type=: (
        WhopSDK::Models::AdCampaignCreateParams::budget_type
      ) -> WhopSDK::Models::AdCampaignCreateParams::budget_type

      attr_reader desired_cost_per_result: Float?

      def desired_cost_per_result=: (Float) -> Float

      attr_reader ends_at: String?

      def ends_at=: (String) -> String

      attr_reader special_ad_categories: ::Array[WhopSDK::Models::AdCampaignCreateParams::special_ad_category]?

      def special_ad_categories=: (
        ::Array[WhopSDK::Models::AdCampaignCreateParams::special_ad_category]
      ) -> ::Array[WhopSDK::Models::AdCampaignCreateParams::special_ad_category]

      attr_reader starts_at: String?

      def starts_at=: (String) -> String

      def initialize: (
        objective: WhopSDK::Models::AdCampaignCreateParams::objective,
        platform: WhopSDK::Models::AdCampaignCreateParams::platform,
        title: String,
        ?account_id: String,
        ?bid_type: WhopSDK::Models::AdCampaignCreateParams::bid_type,
        ?budget_amount: Float,
        ?budget_optimization: WhopSDK::Models::AdCampaignCreateParams::budget_optimization,
        ?budget_type: WhopSDK::Models::AdCampaignCreateParams::budget_type,
        ?desired_cost_per_result: Float,
        ?ends_at: String,
        ?special_ad_categories: ::Array[WhopSDK::Models::AdCampaignCreateParams::special_ad_category],
        ?starts_at: String,
        ?request_options: WhopSDK::request_opts
      ) -> void

      def to_hash: -> {
        objective: WhopSDK::Models::AdCampaignCreateParams::objective,
        platform: WhopSDK::Models::AdCampaignCreateParams::platform,
        title: String,
        account_id: String,
        bid_type: WhopSDK::Models::AdCampaignCreateParams::bid_type,
        budget_amount: Float,
        budget_optimization: WhopSDK::Models::AdCampaignCreateParams::budget_optimization,
        budget_type: WhopSDK::Models::AdCampaignCreateParams::budget_type,
        desired_cost_per_result: Float,
        ends_at: String,
        special_ad_categories: ::Array[WhopSDK::Models::AdCampaignCreateParams::special_ad_category],
        starts_at: String,
        request_options: WhopSDK::RequestOptions
      }

      type objective = :awareness | :traffic | :engagement | :leads | :sales

      module Objective
        extend WhopSDK::Internal::Type::Enum

        AWARENESS: :awareness
        TRAFFIC: :traffic
        ENGAGEMENT: :engagement
        LEADS: :leads
        SALES: :sales

        def self?.values: -> ::Array[WhopSDK::Models::AdCampaignCreateParams::objective]
      end

      type platform = :meta

      module Platform
        extend WhopSDK::Internal::Type::Enum

        META: :meta

        def self?.values: -> ::Array[WhopSDK::Models::AdCampaignCreateParams::platform]
      end

      type bid_type = :minimum_cost | :average_target | :maximum_target

      module BidType
        extend WhopSDK::Internal::Type::Enum

        MINIMUM_COST: :minimum_cost
        AVERAGE_TARGET: :average_target
        MAXIMUM_TARGET: :maximum_target

        def self?.values: -> ::Array[WhopSDK::Models::AdCampaignCreateParams::bid_type]
      end

      type budget_optimization = :ad_campaign | :ad_group

      module BudgetOptimization
        extend WhopSDK::Internal::Type::Enum

        AD_CAMPAIGN: :ad_campaign
        AD_GROUP: :ad_group

        def self?.values: -> ::Array[WhopSDK::Models::AdCampaignCreateParams::budget_optimization]
      end

      type budget_type = :daily | :lifetime

      module BudgetType
        extend WhopSDK::Internal::Type::Enum

        DAILY: :daily
        LIFETIME: :lifetime

        def self?.values: -> ::Array[WhopSDK::Models::AdCampaignCreateParams::budget_type]
      end

      type special_ad_category =
        :housing | :employment | :financial_products | :politics

      module SpecialAdCategory
        extend WhopSDK::Internal::Type::Enum

        HOUSING: :housing
        EMPLOYMENT: :employment
        FINANCIAL_PRODUCTS: :financial_products
        POLITICS: :politics

        def self?.values: -> ::Array[WhopSDK::Models::AdCampaignCreateParams::special_ad_category]
      end
    end
  end
end
