module WhopSDK
  module Models
    type ad_campaign_update_params =
      {
        id: String,
        bid_type: WhopSDK::Models::AdCampaignUpdateParams::bid_type,
        budget_amount: Float,
        budget_optimization: WhopSDK::Models::AdCampaignUpdateParams::budget_optimization,
        ends_at: String,
        starts_at: String,
        status: WhopSDK::Models::AdCampaignUpdateParams::status,
        title: String
      }
      & WhopSDK::Internal::Type::request_parameters

    class AdCampaignUpdateParams < WhopSDK::Internal::Type::BaseModel
      extend WhopSDK::Internal::Type::RequestParameters::Converter
      include WhopSDK::Internal::Type::RequestParameters

      attr_accessor id: String

      attr_reader bid_type: WhopSDK::Models::AdCampaignUpdateParams::bid_type?

      def bid_type=: (
        WhopSDK::Models::AdCampaignUpdateParams::bid_type
      ) -> WhopSDK::Models::AdCampaignUpdateParams::bid_type

      attr_reader budget_amount: Float?

      def budget_amount=: (Float) -> Float

      attr_reader budget_optimization: WhopSDK::Models::AdCampaignUpdateParams::budget_optimization?

      def budget_optimization=: (
        WhopSDK::Models::AdCampaignUpdateParams::budget_optimization
      ) -> WhopSDK::Models::AdCampaignUpdateParams::budget_optimization

      attr_reader ends_at: String?

      def ends_at=: (String) -> String

      attr_reader starts_at: String?

      def starts_at=: (String) -> String

      attr_reader status: WhopSDK::Models::AdCampaignUpdateParams::status?

      def status=: (
        WhopSDK::Models::AdCampaignUpdateParams::status
      ) -> WhopSDK::Models::AdCampaignUpdateParams::status

      attr_reader title: String?

      def title=: (String) -> String

      def initialize: (
        id: String,
        ?bid_type: WhopSDK::Models::AdCampaignUpdateParams::bid_type,
        ?budget_amount: Float,
        ?budget_optimization: WhopSDK::Models::AdCampaignUpdateParams::budget_optimization,
        ?ends_at: String,
        ?starts_at: String,
        ?status: WhopSDK::Models::AdCampaignUpdateParams::status,
        ?title: String,
        ?request_options: WhopSDK::request_opts
      ) -> void

      def to_hash: -> {
        id: String,
        bid_type: WhopSDK::Models::AdCampaignUpdateParams::bid_type,
        budget_amount: Float,
        budget_optimization: WhopSDK::Models::AdCampaignUpdateParams::budget_optimization,
        ends_at: String,
        starts_at: String,
        status: WhopSDK::Models::AdCampaignUpdateParams::status,
        title: String,
        request_options: WhopSDK::RequestOptions
      }

      type bid_type = :minimum_cost | :average_target | :maximum_target

      module BidType
        extend WhopSDK::Internal::Type::Enum

        MINIMUM_COST: :minimum_cost
        AVERAGE_TARGET: :average_target
        MAXIMUM_TARGET: :maximum_target

        def self?.values: -> ::Array[WhopSDK::Models::AdCampaignUpdateParams::bid_type]
      end

      type budget_optimization = :ad_campaign | :ad_group

      module BudgetOptimization
        extend WhopSDK::Internal::Type::Enum

        AD_CAMPAIGN: :ad_campaign
        AD_GROUP: :ad_group

        def self?.values: -> ::Array[WhopSDK::Models::AdCampaignUpdateParams::budget_optimization]
      end

      type status = :active

      module Status
        extend WhopSDK::Internal::Type::Enum

        ACTIVE: :active

        def self?.values: -> ::Array[WhopSDK::Models::AdCampaignUpdateParams::status]
      end
    end
  end
end
