module WhopSDK
  module Models
    type ad_campaign =
      {
        id: String,
        added_to_cart_value: Float,
        added_to_carts: Float,
        budget_amount: Float?,
        budget_optimization: WhopSDK::Models::AdCampaign::budget_optimization?,
        budget_type: WhopSDK::Models::AdCampaign::budget_type?,
        click_through_rate: Float,
        clicks: Float,
        completed_registration_value: Float,
        completed_registrations: Float,
        contact_value: Float,
        contacts: Float,
        cost_per_added_to_cart: Float?,
        cost_per_click: Float,
        cost_per_completed_registration: Float?,
        cost_per_contact: Float?,
        cost_per_lead: Float?,
        cost_per_mille: Float,
        cost_per_purchase: Float?,
        cost_per_result: Float?,
        cost_per_schedule: Float?,
        cost_per_submitted_application: Float?,
        cost_per_unique_click: Float?,
        cost_per_viewed_content: Float?,
        created_at: String,
        custom_conversions: Float,
        custom_event_counts: top,
        custom_event_values: top,
        delivery_status: WhopSDK::Models::AdCampaign::delivery_status,
        frequency: Float?,
        impressions: Float,
        issues: ::Array[WhopSDK::AdCampaign::Issue],
        lead_value: Float,
        leads: Float,
        link_clicks: Float,
        objective: WhopSDK::Models::AdCampaign::objective?,
        optimization_goal: String?,
        platform: WhopSDK::Models::AdCampaign::platform,
        purchase_value: Float,
        purchases: Float,
        reach: Float,
        result_event: WhopSDK::Models::AdCampaign::result_event?,
        result_event_name: String?,
        results: Float?,
        return_on_ad_spend: Float,
        schedule_value: Float,
        schedules: Float,
        special_ad_categories: ::Array[WhopSDK::Models::AdCampaign::special_ad_category],
        spend: Float,
        spend_currency: String?,
        status: WhopSDK::Models::AdCampaign::status,
        submitted_application_value: Float,
        submitted_applications: Float,
        title: String,
        unique_click_through_rate: Float?,
        unique_clicks: Float,
        updated_at: String,
        viewed_content_value: Float,
        viewed_contents: Float,
        bid_type: WhopSDK::Models::AdCampaign::bid_type?
      }

    class AdCampaign < WhopSDK::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor added_to_cart_value: Float

      attr_accessor added_to_carts: Float

      attr_accessor budget_amount: Float?

      attr_accessor budget_optimization: WhopSDK::Models::AdCampaign::budget_optimization?

      attr_accessor budget_type: WhopSDK::Models::AdCampaign::budget_type?

      attr_accessor click_through_rate: Float

      attr_accessor clicks: Float

      attr_accessor completed_registration_value: Float

      attr_accessor completed_registrations: Float

      attr_accessor contact_value: Float

      attr_accessor contacts: Float

      attr_accessor cost_per_added_to_cart: Float?

      attr_accessor cost_per_click: Float

      attr_accessor cost_per_completed_registration: Float?

      attr_accessor cost_per_contact: Float?

      attr_accessor cost_per_lead: Float?

      attr_accessor cost_per_mille: Float

      attr_accessor cost_per_purchase: Float?

      attr_accessor cost_per_result: Float?

      attr_accessor cost_per_schedule: Float?

      attr_accessor cost_per_submitted_application: Float?

      attr_accessor cost_per_unique_click: Float?

      attr_accessor cost_per_viewed_content: Float?

      attr_accessor created_at: String

      attr_accessor custom_conversions: Float

      attr_accessor custom_event_counts: top

      attr_accessor custom_event_values: top

      attr_accessor delivery_status: WhopSDK::Models::AdCampaign::delivery_status

      attr_accessor frequency: Float?

      attr_accessor impressions: Float

      attr_accessor issues: ::Array[WhopSDK::AdCampaign::Issue]

      attr_accessor lead_value: Float

      attr_accessor leads: Float

      attr_accessor link_clicks: Float

      attr_accessor objective: WhopSDK::Models::AdCampaign::objective?

      attr_accessor optimization_goal: String?

      attr_accessor platform: WhopSDK::Models::AdCampaign::platform

      attr_accessor purchase_value: Float

      attr_accessor purchases: Float

      attr_accessor reach: Float

      attr_accessor result_event: WhopSDK::Models::AdCampaign::result_event?

      attr_accessor result_event_name: String?

      attr_accessor results: Float?

      attr_accessor return_on_ad_spend: Float

      attr_accessor schedule_value: Float

      attr_accessor schedules: Float

      attr_accessor special_ad_categories: ::Array[WhopSDK::Models::AdCampaign::special_ad_category]

      attr_accessor spend: Float

      attr_accessor spend_currency: String?

      attr_accessor status: WhopSDK::Models::AdCampaign::status

      attr_accessor submitted_application_value: Float

      attr_accessor submitted_applications: Float

      attr_accessor title: String

      attr_accessor unique_click_through_rate: Float?

      attr_accessor unique_clicks: Float

      attr_accessor updated_at: String

      attr_accessor viewed_content_value: Float

      attr_accessor viewed_contents: Float

      attr_accessor bid_type: WhopSDK::Models::AdCampaign::bid_type?

      def initialize: (
        id: String,
        added_to_cart_value: Float,
        added_to_carts: Float,
        budget_amount: Float?,
        budget_optimization: WhopSDK::Models::AdCampaign::budget_optimization?,
        budget_type: WhopSDK::Models::AdCampaign::budget_type?,
        click_through_rate: Float,
        clicks: Float,
        completed_registration_value: Float,
        completed_registrations: Float,
        contact_value: Float,
        contacts: Float,
        cost_per_added_to_cart: Float?,
        cost_per_click: Float,
        cost_per_completed_registration: Float?,
        cost_per_contact: Float?,
        cost_per_lead: Float?,
        cost_per_mille: Float,
        cost_per_purchase: Float?,
        cost_per_result: Float?,
        cost_per_schedule: Float?,
        cost_per_submitted_application: Float?,
        cost_per_unique_click: Float?,
        cost_per_viewed_content: Float?,
        created_at: String,
        custom_conversions: Float,
        custom_event_counts: top,
        custom_event_values: top,
        delivery_status: WhopSDK::Models::AdCampaign::delivery_status,
        frequency: Float?,
        impressions: Float,
        issues: ::Array[WhopSDK::AdCampaign::Issue],
        lead_value: Float,
        leads: Float,
        link_clicks: Float,
        objective: WhopSDK::Models::AdCampaign::objective?,
        optimization_goal: String?,
        platform: WhopSDK::Models::AdCampaign::platform,
        purchase_value: Float,
        purchases: Float,
        reach: Float,
        result_event: WhopSDK::Models::AdCampaign::result_event?,
        result_event_name: String?,
        results: Float?,
        return_on_ad_spend: Float,
        schedule_value: Float,
        schedules: Float,
        special_ad_categories: ::Array[WhopSDK::Models::AdCampaign::special_ad_category],
        spend: Float,
        spend_currency: String?,
        status: WhopSDK::Models::AdCampaign::status,
        submitted_application_value: Float,
        submitted_applications: Float,
        title: String,
        unique_click_through_rate: Float?,
        unique_clicks: Float,
        updated_at: String,
        viewed_content_value: Float,
        viewed_contents: Float,
        ?bid_type: WhopSDK::Models::AdCampaign::bid_type?
      ) -> void

      def to_hash: -> {
        id: String,
        added_to_cart_value: Float,
        added_to_carts: Float,
        budget_amount: Float?,
        budget_optimization: WhopSDK::Models::AdCampaign::budget_optimization?,
        budget_type: WhopSDK::Models::AdCampaign::budget_type?,
        click_through_rate: Float,
        clicks: Float,
        completed_registration_value: Float,
        completed_registrations: Float,
        contact_value: Float,
        contacts: Float,
        cost_per_added_to_cart: Float?,
        cost_per_click: Float,
        cost_per_completed_registration: Float?,
        cost_per_contact: Float?,
        cost_per_lead: Float?,
        cost_per_mille: Float,
        cost_per_purchase: Float?,
        cost_per_result: Float?,
        cost_per_schedule: Float?,
        cost_per_submitted_application: Float?,
        cost_per_unique_click: Float?,
        cost_per_viewed_content: Float?,
        created_at: String,
        custom_conversions: Float,
        custom_event_counts: top,
        custom_event_values: top,
        delivery_status: WhopSDK::Models::AdCampaign::delivery_status,
        frequency: Float?,
        impressions: Float,
        issues: ::Array[WhopSDK::AdCampaign::Issue],
        lead_value: Float,
        leads: Float,
        link_clicks: Float,
        objective: WhopSDK::Models::AdCampaign::objective?,
        optimization_goal: String?,
        platform: WhopSDK::Models::AdCampaign::platform,
        purchase_value: Float,
        purchases: Float,
        reach: Float,
        result_event: WhopSDK::Models::AdCampaign::result_event?,
        result_event_name: String?,
        results: Float?,
        return_on_ad_spend: Float,
        schedule_value: Float,
        schedules: Float,
        special_ad_categories: ::Array[WhopSDK::Models::AdCampaign::special_ad_category],
        spend: Float,
        spend_currency: String?,
        status: WhopSDK::Models::AdCampaign::status,
        submitted_application_value: Float,
        submitted_applications: Float,
        title: String,
        unique_click_through_rate: Float?,
        unique_clicks: Float,
        updated_at: String,
        viewed_content_value: Float,
        viewed_contents: Float,
        bid_type: WhopSDK::Models::AdCampaign::bid_type?
      }

      type budget_optimization = :ad_campaign | :ad_group

      module BudgetOptimization
        extend WhopSDK::Internal::Type::Enum

        AD_CAMPAIGN: :ad_campaign
        AD_GROUP: :ad_group

        def self?.values: -> ::Array[WhopSDK::Models::AdCampaign::budget_optimization]
      end

      type budget_type = :daily | :lifetime

      module BudgetType
        extend WhopSDK::Internal::Type::Enum

        DAILY: :daily
        LIFETIME: :lifetime

        def self?.values: -> ::Array[WhopSDK::Models::AdCampaign::budget_type]
      end

      type delivery_status =
        :payment_failed
        | :all_ads_rejected
        | :draft
        | :no_ad_groups
        | :no_ads
        | :paused
        | :processing
        | :issues
        | :scheduled
        | :completed
        | :ad_groups_off
        | :active

      module DeliveryStatus
        extend WhopSDK::Internal::Type::Enum

        PAYMENT_FAILED: :payment_failed
        ALL_ADS_REJECTED: :all_ads_rejected
        DRAFT: :draft
        NO_AD_GROUPS: :no_ad_groups
        NO_ADS: :no_ads
        PAUSED: :paused
        PROCESSING: :processing
        ISSUES: :issues
        SCHEDULED: :scheduled
        COMPLETED: :completed
        AD_GROUPS_OFF: :ad_groups_off
        ACTIVE: :active

        def self?.values: -> ::Array[WhopSDK::Models::AdCampaign::delivery_status]
      end

      type issue =
        {
          id: String,
          message: String,
          resource_id: String?,
          resource_type: WhopSDK::Models::AdCampaign::Issue::resource_type
        }

      class Issue < WhopSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor message: String

        attr_accessor resource_id: String?

        attr_accessor resource_type: WhopSDK::Models::AdCampaign::Issue::resource_type

        def initialize: (
          id: String,
          message: String,
          resource_id: String?,
          resource_type: WhopSDK::Models::AdCampaign::Issue::resource_type
        ) -> void

        def to_hash: -> {
          id: String,
          message: String,
          resource_id: String?,
          resource_type: WhopSDK::Models::AdCampaign::Issue::resource_type
        }

        type resource_type = :ad_campaign | :ad_group | :ad

        module ResourceType
          extend WhopSDK::Internal::Type::Enum

          AD_CAMPAIGN: :ad_campaign
          AD_GROUP: :ad_group
          AD: :ad

          def self?.values: -> ::Array[WhopSDK::Models::AdCampaign::Issue::resource_type]
        end
      end

      type objective = :awareness | :traffic | :engagement | :leads | :sales

      module Objective
        extend WhopSDK::Internal::Type::Enum

        AWARENESS: :awareness
        TRAFFIC: :traffic
        ENGAGEMENT: :engagement
        LEADS: :leads
        SALES: :sales

        def self?.values: -> ::Array[WhopSDK::Models::AdCampaign::objective]
      end

      type platform = :meta | :tiktok

      module Platform
        extend WhopSDK::Internal::Type::Enum

        META: :meta
        TIKTOK: :tiktok

        def self?.values: -> ::Array[WhopSDK::Models::AdCampaign::platform]
      end

      type result_event =
        :purchase
        | :lead
        | :schedule
        | :submit_application
        | :contact
        | :complete_registration
        | :view_content
        | :add_to_cart
        | :custom
        | :messaging_conversation

      module ResultEvent
        extend WhopSDK::Internal::Type::Enum

        PURCHASE: :purchase
        LEAD: :lead
        SCHEDULE: :schedule
        SUBMIT_APPLICATION: :submit_application
        CONTACT: :contact
        COMPLETE_REGISTRATION: :complete_registration
        VIEW_CONTENT: :view_content
        ADD_TO_CART: :add_to_cart
        CUSTOM: :custom
        MESSAGING_CONVERSATION: :messaging_conversation

        def self?.values: -> ::Array[WhopSDK::Models::AdCampaign::result_event]
      end

      type special_ad_category =
        :housing | :employment | :financial_products | :politics

      module SpecialAdCategory
        extend WhopSDK::Internal::Type::Enum

        HOUSING: :housing
        EMPLOYMENT: :employment
        FINANCIAL_PRODUCTS: :financial_products
        POLITICS: :politics

        def self?.values: -> ::Array[WhopSDK::Models::AdCampaign::special_ad_category]
      end

      type status =
        :active
        | :paused
        | :inactive
        | :stale
        | :pending_refund
        | :payment_failed
        | :draft
        | :in_review
        | :flagged
        | :importing
        | :imported
        | :duplicating

      module Status
        extend WhopSDK::Internal::Type::Enum

        ACTIVE: :active
        PAUSED: :paused
        INACTIVE: :inactive
        STALE: :stale
        PENDING_REFUND: :pending_refund
        PAYMENT_FAILED: :payment_failed
        DRAFT: :draft
        IN_REVIEW: :in_review
        FLAGGED: :flagged
        IMPORTING: :importing
        IMPORTED: :imported
        DUPLICATING: :duplicating

        def self?.values: -> ::Array[WhopSDK::Models::AdCampaign::status]
      end

      type bid_type = :minimum_cost | :average_target | :maximum_target

      module BidType
        extend WhopSDK::Internal::Type::Enum

        MINIMUM_COST: :minimum_cost
        AVERAGE_TARGET: :average_target
        MAXIMUM_TARGET: :maximum_target

        def self?.values: -> ::Array[WhopSDK::Models::AdCampaign::bid_type]
      end
    end
  end
end
