module WhopSDK
  module Models
    type ad_campaign_payment_failed_webhook_event =
      {
        id: String,
        api_version: :v1,
        api_version_date: String?,
        data: WhopSDK::AdCampaignPaymentFailedWebhookEvent::Data,
        timestamp: Time,
        type: :"ad_campaign.payment_failed",
        account_id: String?,
        previous_attributes: top
      }

    class AdCampaignPaymentFailedWebhookEvent < WhopSDK::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor api_version: :v1

      attr_accessor api_version_date: String?

      attr_accessor data: WhopSDK::AdCampaignPaymentFailedWebhookEvent::Data

      attr_accessor timestamp: Time

      attr_accessor type: :"ad_campaign.payment_failed"

      attr_accessor account_id: String?

      attr_reader previous_attributes: top?

      def previous_attributes=: (top) -> top

      def initialize: (
        id: String,
        api_version_date: String?,
        data: WhopSDK::AdCampaignPaymentFailedWebhookEvent::Data,
        timestamp: Time,
        ?account_id: String?,
        ?previous_attributes: top,
        ?api_version: :v1,
        ?type: :"ad_campaign.payment_failed"
      ) -> void

      def to_hash: -> {
        id: String,
        api_version: :v1,
        api_version_date: String?,
        data: WhopSDK::AdCampaignPaymentFailedWebhookEvent::Data,
        timestamp: Time,
        type: :"ad_campaign.payment_failed",
        account_id: String?,
        previous_attributes: top
      }

      type data =
        {
          id: String,
          budget_amount: Float?,
          budget_optimization: WhopSDK::Models::AdCampaignPaymentFailedWebhookEvent::Data::budget_optimization?,
          budget_type: WhopSDK::Models::AdCampaignPaymentFailedWebhookEvent::Data::budget_type?,
          created_at: String,
          delivery_status: WhopSDK::Models::AdCampaignPaymentFailedWebhookEvent::Data::delivery_status,
          issues: ::Array[WhopSDK::AdCampaignPaymentFailedWebhookEvent::Data::Issue],
          objective: WhopSDK::Models::AdCampaignPaymentFailedWebhookEvent::Data::objective?,
          optimization_goal: String?,
          platform: WhopSDK::Models::AdCampaignPaymentFailedWebhookEvent::Data::platform,
          special_ad_categories: ::Array[WhopSDK::Models::AdCampaignPaymentFailedWebhookEvent::Data::special_ad_category],
          status: WhopSDK::Models::AdCampaignPaymentFailedWebhookEvent::Data::status,
          title: String,
          updated_at: String,
          bid_type: WhopSDK::Models::AdCampaignPaymentFailedWebhookEvent::Data::bid_type?
        }

      class Data < WhopSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor budget_amount: Float?

        attr_accessor budget_optimization: WhopSDK::Models::AdCampaignPaymentFailedWebhookEvent::Data::budget_optimization?

        attr_accessor budget_type: WhopSDK::Models::AdCampaignPaymentFailedWebhookEvent::Data::budget_type?

        attr_accessor created_at: String

        attr_accessor delivery_status: WhopSDK::Models::AdCampaignPaymentFailedWebhookEvent::Data::delivery_status

        attr_accessor issues: ::Array[WhopSDK::AdCampaignPaymentFailedWebhookEvent::Data::Issue]

        attr_accessor objective: WhopSDK::Models::AdCampaignPaymentFailedWebhookEvent::Data::objective?

        attr_accessor optimization_goal: String?

        attr_accessor platform: WhopSDK::Models::AdCampaignPaymentFailedWebhookEvent::Data::platform

        attr_accessor special_ad_categories: ::Array[WhopSDK::Models::AdCampaignPaymentFailedWebhookEvent::Data::special_ad_category]

        attr_accessor status: WhopSDK::Models::AdCampaignPaymentFailedWebhookEvent::Data::status

        attr_accessor title: String

        attr_accessor updated_at: String

        attr_accessor bid_type: WhopSDK::Models::AdCampaignPaymentFailedWebhookEvent::Data::bid_type?

        def initialize: (
          id: String,
          budget_amount: Float?,
          budget_optimization: WhopSDK::Models::AdCampaignPaymentFailedWebhookEvent::Data::budget_optimization?,
          budget_type: WhopSDK::Models::AdCampaignPaymentFailedWebhookEvent::Data::budget_type?,
          created_at: String,
          delivery_status: WhopSDK::Models::AdCampaignPaymentFailedWebhookEvent::Data::delivery_status,
          issues: ::Array[WhopSDK::AdCampaignPaymentFailedWebhookEvent::Data::Issue],
          objective: WhopSDK::Models::AdCampaignPaymentFailedWebhookEvent::Data::objective?,
          optimization_goal: String?,
          platform: WhopSDK::Models::AdCampaignPaymentFailedWebhookEvent::Data::platform,
          special_ad_categories: ::Array[WhopSDK::Models::AdCampaignPaymentFailedWebhookEvent::Data::special_ad_category],
          status: WhopSDK::Models::AdCampaignPaymentFailedWebhookEvent::Data::status,
          title: String,
          updated_at: String,
          ?bid_type: WhopSDK::Models::AdCampaignPaymentFailedWebhookEvent::Data::bid_type?
        ) -> void

        def to_hash: -> {
          id: String,
          budget_amount: Float?,
          budget_optimization: WhopSDK::Models::AdCampaignPaymentFailedWebhookEvent::Data::budget_optimization?,
          budget_type: WhopSDK::Models::AdCampaignPaymentFailedWebhookEvent::Data::budget_type?,
          created_at: String,
          delivery_status: WhopSDK::Models::AdCampaignPaymentFailedWebhookEvent::Data::delivery_status,
          issues: ::Array[WhopSDK::AdCampaignPaymentFailedWebhookEvent::Data::Issue],
          objective: WhopSDK::Models::AdCampaignPaymentFailedWebhookEvent::Data::objective?,
          optimization_goal: String?,
          platform: WhopSDK::Models::AdCampaignPaymentFailedWebhookEvent::Data::platform,
          special_ad_categories: ::Array[WhopSDK::Models::AdCampaignPaymentFailedWebhookEvent::Data::special_ad_category],
          status: WhopSDK::Models::AdCampaignPaymentFailedWebhookEvent::Data::status,
          title: String,
          updated_at: String,
          bid_type: WhopSDK::Models::AdCampaignPaymentFailedWebhookEvent::Data::bid_type?
        }

        type budget_optimization = :ad_campaign | :ad_group

        module BudgetOptimization
          extend WhopSDK::Internal::Type::Enum

          AD_CAMPAIGN: :ad_campaign
          AD_GROUP: :ad_group

          def self?.values: -> ::Array[WhopSDK::Models::AdCampaignPaymentFailedWebhookEvent::Data::budget_optimization]
        end

        type budget_type = :daily | :lifetime

        module BudgetType
          extend WhopSDK::Internal::Type::Enum

          DAILY: :daily
          LIFETIME: :lifetime

          def self?.values: -> ::Array[WhopSDK::Models::AdCampaignPaymentFailedWebhookEvent::Data::budget_type]
        end

        type delivery_status =
          :payment_failed
          | :in_appeal
          | :all_ads_rejected
          | :draft
          | :no_ad_groups
          | :no_ads
          | :paused
          | :processing
          | :issues
          | :scheduled
          | :completed
          | :ad_groups_off
          | :active

        module DeliveryStatus
          extend WhopSDK::Internal::Type::Enum

          PAYMENT_FAILED: :payment_failed
          IN_APPEAL: :in_appeal
          ALL_ADS_REJECTED: :all_ads_rejected
          DRAFT: :draft
          NO_AD_GROUPS: :no_ad_groups
          NO_ADS: :no_ads
          PAUSED: :paused
          PROCESSING: :processing
          ISSUES: :issues
          SCHEDULED: :scheduled
          COMPLETED: :completed
          AD_GROUPS_OFF: :ad_groups_off
          ACTIVE: :active

          def self?.values: -> ::Array[WhopSDK::Models::AdCampaignPaymentFailedWebhookEvent::Data::delivery_status]
        end

        type issue =
          {
            id: String,
            message: String,
            resource_id: String?,
            resource_type: WhopSDK::Models::AdCampaignPaymentFailedWebhookEvent::Data::Issue::resource_type
          }

        class Issue < WhopSDK::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor message: String

          attr_accessor resource_id: String?

          attr_accessor resource_type: WhopSDK::Models::AdCampaignPaymentFailedWebhookEvent::Data::Issue::resource_type

          def initialize: (
            id: String,
            message: String,
            resource_id: String?,
            resource_type: WhopSDK::Models::AdCampaignPaymentFailedWebhookEvent::Data::Issue::resource_type
          ) -> void

          def to_hash: -> {
            id: String,
            message: String,
            resource_id: String?,
            resource_type: WhopSDK::Models::AdCampaignPaymentFailedWebhookEvent::Data::Issue::resource_type
          }

          type resource_type = :ad_campaign | :ad_group | :ad

          module ResourceType
            extend WhopSDK::Internal::Type::Enum

            AD_CAMPAIGN: :ad_campaign
            AD_GROUP: :ad_group
            AD: :ad

            def self?.values: -> ::Array[WhopSDK::Models::AdCampaignPaymentFailedWebhookEvent::Data::Issue::resource_type]
          end
        end

        type objective = :awareness | :traffic | :engagement | :leads | :sales

        module Objective
          extend WhopSDK::Internal::Type::Enum

          AWARENESS: :awareness
          TRAFFIC: :traffic
          ENGAGEMENT: :engagement
          LEADS: :leads
          SALES: :sales

          def self?.values: -> ::Array[WhopSDK::Models::AdCampaignPaymentFailedWebhookEvent::Data::objective]
        end

        type platform = :meta | :tiktok

        module Platform
          extend WhopSDK::Internal::Type::Enum

          META: :meta
          TIKTOK: :tiktok

          def self?.values: -> ::Array[WhopSDK::Models::AdCampaignPaymentFailedWebhookEvent::Data::platform]
        end

        type special_ad_category =
          :housing | :employment | :financial_products | :politics

        module SpecialAdCategory
          extend WhopSDK::Internal::Type::Enum

          HOUSING: :housing
          EMPLOYMENT: :employment
          FINANCIAL_PRODUCTS: :financial_products
          POLITICS: :politics

          def self?.values: -> ::Array[WhopSDK::Models::AdCampaignPaymentFailedWebhookEvent::Data::special_ad_category]
        end

        type status =
          :active
          | :paused
          | :inactive
          | :stale
          | :pending_refund
          | :payment_failed
          | :draft
          | :in_review
          | :flagged
          | :importing
          | :imported
          | :duplicating

        module Status
          extend WhopSDK::Internal::Type::Enum

          ACTIVE: :active
          PAUSED: :paused
          INACTIVE: :inactive
          STALE: :stale
          PENDING_REFUND: :pending_refund
          PAYMENT_FAILED: :payment_failed
          DRAFT: :draft
          IN_REVIEW: :in_review
          FLAGGED: :flagged
          IMPORTING: :importing
          IMPORTED: :imported
          DUPLICATING: :duplicating

          def self?.values: -> ::Array[WhopSDK::Models::AdCampaignPaymentFailedWebhookEvent::Data::status]
        end

        type bid_type = :minimum_cost | :average_target | :maximum_target

        module BidType
          extend WhopSDK::Internal::Type::Enum

          MINIMUM_COST: :minimum_cost
          AVERAGE_TARGET: :average_target
          MAXIMUM_TARGET: :maximum_target

          def self?.values: -> ::Array[WhopSDK::Models::AdCampaignPaymentFailedWebhookEvent::Data::bid_type]
        end
      end
    end
  end
end
