module WhopSDK
  module Models
    type ad_group_list_params =
      {
        ad_campaign_id: String?,
        ad_campaign_ids: ::Array[String]?,
        after: String?,
        before: String?,
        campaign_id: String?,
        company_id: String?,
        created_after: Time?,
        created_before: Time?,
        first: Integer?,
        last: Integer?,
        query: String?,
        stats_from: Time?,
        stats_to: Time?,
        status: WhopSDK::Models::ad_group_status?
      }
      & WhopSDK::Internal::Type::request_parameters

    class AdGroupListParams < WhopSDK::Internal::Type::BaseModel
      extend WhopSDK::Internal::Type::RequestParameters::Converter
      include WhopSDK::Internal::Type::RequestParameters

      attr_accessor ad_campaign_id: String?

      attr_accessor ad_campaign_ids: ::Array[String]?

      attr_accessor after: String?

      attr_accessor before: String?

      attr_accessor campaign_id: String?

      attr_accessor company_id: String?

      attr_accessor created_after: Time?

      attr_accessor created_before: Time?

      attr_accessor first: Integer?

      attr_accessor last: Integer?

      attr_accessor query: String?

      attr_accessor stats_from: Time?

      attr_accessor stats_to: Time?

      attr_accessor status: WhopSDK::Models::ad_group_status?

      def initialize: (
        ?ad_campaign_id: String?,
        ?ad_campaign_ids: ::Array[String]?,
        ?after: String?,
        ?before: String?,
        ?campaign_id: String?,
        ?company_id: String?,
        ?created_after: Time?,
        ?created_before: Time?,
        ?first: Integer?,
        ?last: Integer?,
        ?query: String?,
        ?stats_from: Time?,
        ?stats_to: Time?,
        ?status: WhopSDK::Models::ad_group_status?,
        ?request_options: WhopSDK::request_opts
      ) -> void

      def to_hash: -> {
        ad_campaign_id: String?,
        ad_campaign_ids: ::Array[String]?,
        after: String?,
        before: String?,
        campaign_id: String?,
        company_id: String?,
        created_after: Time?,
        created_before: Time?,
        first: Integer?,
        last: Integer?,
        query: String?,
        stats_from: Time?,
        stats_to: Time?,
        status: WhopSDK::Models::ad_group_status?,
        request_options: WhopSDK::RequestOptions
      }
    end
  end
end
