module WhopSDK
  module Models
    type ad_group_update_params =
      { id: String, budget: Float?, title: String? }
      & WhopSDK::Internal::Type::request_parameters

    class AdGroupUpdateParams < WhopSDK::Internal::Type::BaseModel
      extend WhopSDK::Internal::Type::RequestParameters::Converter
      include WhopSDK::Internal::Type::RequestParameters

      attr_accessor id: String

      attr_accessor budget: Float?

      attr_accessor title: String?

      def initialize: (
        id: String,
        ?budget: Float?,
        ?title: String?,
        ?request_options: WhopSDK::request_opts
      ) -> void

      def to_hash: -> {
        id: String,
        budget: Float?,
        title: String?,
        request_options: WhopSDK::RequestOptions
      }
    end
  end
end
