module WhopSDK
  module Models
    type ad_group =
      {
        id: String,
        ad_campaign: WhopSDK::AdGroup::AdCampaign,
        budget: Float?,
        budget_type: WhopSDK::Models::ad_budget_type?,
        created_at: Time,
        platform: WhopSDK::Models::ad_campaign_platform,
        status: WhopSDK::Models::ad_group_status,
        title: String?,
        updated_at: Time
      }

    class AdGroup < WhopSDK::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor ad_campaign: WhopSDK::AdGroup::AdCampaign

      attr_accessor budget: Float?

      attr_accessor budget_type: WhopSDK::Models::ad_budget_type?

      attr_accessor created_at: Time

      attr_accessor platform: WhopSDK::Models::ad_campaign_platform

      attr_accessor status: WhopSDK::Models::ad_group_status

      attr_accessor title: String?

      attr_accessor updated_at: Time

      def initialize: (
        id: String,
        ad_campaign: WhopSDK::AdGroup::AdCampaign,
        budget: Float?,
        budget_type: WhopSDK::Models::ad_budget_type?,
        created_at: Time,
        platform: WhopSDK::Models::ad_campaign_platform,
        status: WhopSDK::Models::ad_group_status,
        title: String?,
        updated_at: Time
      ) -> void

      def to_hash: -> {
        id: String,
        ad_campaign: WhopSDK::AdGroup::AdCampaign,
        budget: Float?,
        budget_type: WhopSDK::Models::ad_budget_type?,
        created_at: Time,
        platform: WhopSDK::Models::ad_campaign_platform,
        status: WhopSDK::Models::ad_group_status,
        title: String?,
        updated_at: Time
      }

      type ad_campaign = { id: String }

      class AdCampaign < WhopSDK::Internal::Type::BaseModel
        attr_accessor id: String

        def initialize: (id: String) -> void

        def to_hash: -> { id: String }
      end
    end
  end
end
