module WhopSDK
  module Models
    type ad_group_retrieve_response =
      {
        id: String,
        ad_campaign: WhopSDK::Models::AdGroupRetrieveResponse::AdCampaign,
        budget: Float?,
        budget_type: WhopSDK::Models::AdGroupRetrieveResponse::budget_type?,
        created_at: Time,
        platform: WhopSDK::Models::AdGroupRetrieveResponse::platform,
        status: WhopSDK::Models::AdGroupRetrieveResponse::status,
        title: String?,
        updated_at: Time
      }

    class AdGroupRetrieveResponse < WhopSDK::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor ad_campaign: WhopSDK::Models::AdGroupRetrieveResponse::AdCampaign

      attr_accessor budget: Float?

      attr_accessor budget_type: WhopSDK::Models::AdGroupRetrieveResponse::budget_type?

      attr_accessor created_at: Time

      attr_accessor platform: WhopSDK::Models::AdGroupRetrieveResponse::platform

      attr_accessor status: WhopSDK::Models::AdGroupRetrieveResponse::status

      attr_accessor title: String?

      attr_accessor updated_at: Time

      def initialize: (
        id: String,
        ad_campaign: WhopSDK::Models::AdGroupRetrieveResponse::AdCampaign,
        budget: Float?,
        budget_type: WhopSDK::Models::AdGroupRetrieveResponse::budget_type?,
        created_at: Time,
        platform: WhopSDK::Models::AdGroupRetrieveResponse::platform,
        status: WhopSDK::Models::AdGroupRetrieveResponse::status,
        title: String?,
        updated_at: Time
      ) -> void

      def to_hash: -> {
        id: String,
        ad_campaign: WhopSDK::Models::AdGroupRetrieveResponse::AdCampaign,
        budget: Float?,
        budget_type: WhopSDK::Models::AdGroupRetrieveResponse::budget_type?,
        created_at: Time,
        platform: WhopSDK::Models::AdGroupRetrieveResponse::platform,
        status: WhopSDK::Models::AdGroupRetrieveResponse::status,
        title: String?,
        updated_at: Time
      }

      type ad_campaign = { id: String }

      class AdCampaign < WhopSDK::Internal::Type::BaseModel
        attr_accessor id: String

        def initialize: (id: String) -> void

        def to_hash: -> { id: String }
      end

      type budget_type = :daily | :lifetime

      module BudgetType
        extend WhopSDK::Internal::Type::Enum

        DAILY: :daily
        LIFETIME: :lifetime

        def self?.values: -> ::Array[WhopSDK::Models::AdGroupRetrieveResponse::budget_type]
      end

      type platform = :meta | :tiktok

      module Platform
        extend WhopSDK::Internal::Type::Enum

        META: :meta
        TIKTOK: :tiktok

        def self?.values: -> ::Array[WhopSDK::Models::AdGroupRetrieveResponse::platform]
      end

      type status =
        :active | :paused | :inactive | :in_review | :rejected | :flagged

      module Status
        extend WhopSDK::Internal::Type::Enum

        ACTIVE: :active
        PAUSED: :paused
        INACTIVE: :inactive
        IN_REVIEW: :in_review
        REJECTED: :rejected
        FLAGGED: :flagged

        def self?.values: -> ::Array[WhopSDK::Models::AdGroupRetrieveResponse::status]
      end
    end
  end
end
