module WhopSDK
  module Models
    type ad_list_response =
      {
        id: String,
        created_at: Time,
        platform: WhopSDK::Models::ad_campaign_platform,
        status: WhopSDK::Models::external_ad_status,
        title: String?,
        updated_at: Time
      }

    class AdListResponse < WhopSDK::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor created_at: Time

      attr_accessor platform: WhopSDK::Models::ad_campaign_platform

      attr_accessor status: WhopSDK::Models::external_ad_status

      attr_accessor title: String?

      attr_accessor updated_at: Time

      def initialize: (
        id: String,
        created_at: Time,
        platform: WhopSDK::Models::ad_campaign_platform,
        status: WhopSDK::Models::external_ad_status,
        title: String?,
        updated_at: Time
      ) -> void

      def to_hash: -> {
        id: String,
        created_at: Time,
        platform: WhopSDK::Models::ad_campaign_platform,
        status: WhopSDK::Models::external_ad_status,
        title: String?,
        updated_at: Time
      }
    end
  end
end
