module WhopSDK
  module Models
    type ad_list_params =
      {
        ad_campaign_id: String?,
        ad_campaign_ids: ::Array[String]?,
        ad_group_id: String?,
        ad_group_ids: ::Array[String]?,
        after: String?,
        before: String?,
        campaign_id: String?,
        company_id: String?,
        created_after: Time?,
        created_before: Time?,
        direction: WhopSDK::Models::direction?,
        first: Integer?,
        last: Integer?,
        order: WhopSDK::Models::AdListParams::order?,
        order_by: WhopSDK::Models::AdListParams::order_by?,
        order_direction: WhopSDK::Models::direction?,
        query: String?,
        stats_from: Time?,
        stats_to: Time?,
        status: WhopSDK::Models::external_ad_status?
      }
      & WhopSDK::Internal::Type::request_parameters

    class AdListParams < WhopSDK::Internal::Type::BaseModel
      extend WhopSDK::Internal::Type::RequestParameters::Converter
      include WhopSDK::Internal::Type::RequestParameters

      attr_accessor ad_campaign_id: String?

      attr_accessor ad_campaign_ids: ::Array[String]?

      attr_accessor ad_group_id: String?

      attr_accessor ad_group_ids: ::Array[String]?

      attr_accessor after: String?

      attr_accessor before: String?

      attr_accessor campaign_id: String?

      attr_accessor company_id: String?

      attr_accessor created_after: Time?

      attr_accessor created_before: Time?

      attr_accessor direction: WhopSDK::Models::direction?

      attr_accessor first: Integer?

      attr_accessor last: Integer?

      attr_accessor order: WhopSDK::Models::AdListParams::order?

      attr_accessor order_by: WhopSDK::Models::AdListParams::order_by?

      attr_accessor order_direction: WhopSDK::Models::direction?

      attr_accessor query: String?

      attr_accessor stats_from: Time?

      attr_accessor stats_to: Time?

      attr_accessor status: WhopSDK::Models::external_ad_status?

      def initialize: (
        ?ad_campaign_id: String?,
        ?ad_campaign_ids: ::Array[String]?,
        ?ad_group_id: String?,
        ?ad_group_ids: ::Array[String]?,
        ?after: String?,
        ?before: String?,
        ?campaign_id: String?,
        ?company_id: String?,
        ?created_after: Time?,
        ?created_before: Time?,
        ?direction: WhopSDK::Models::direction?,
        ?first: Integer?,
        ?last: Integer?,
        ?order: WhopSDK::Models::AdListParams::order?,
        ?order_by: WhopSDK::Models::AdListParams::order_by?,
        ?order_direction: WhopSDK::Models::direction?,
        ?query: String?,
        ?stats_from: Time?,
        ?stats_to: Time?,
        ?status: WhopSDK::Models::external_ad_status?,
        ?request_options: WhopSDK::request_opts
      ) -> void

      def to_hash: -> {
        ad_campaign_id: String?,
        ad_campaign_ids: ::Array[String]?,
        ad_group_id: String?,
        ad_group_ids: ::Array[String]?,
        after: String?,
        before: String?,
        campaign_id: String?,
        company_id: String?,
        created_after: Time?,
        created_before: Time?,
        direction: WhopSDK::Models::direction?,
        first: Integer?,
        last: Integer?,
        order: WhopSDK::Models::AdListParams::order?,
        order_by: WhopSDK::Models::AdListParams::order_by?,
        order_direction: WhopSDK::Models::direction?,
        query: String?,
        stats_from: Time?,
        stats_to: Time?,
        status: WhopSDK::Models::external_ad_status?,
        request_options: WhopSDK::RequestOptions
      }

      type order =
        :created_at
        | :spend
        | :impressions
        | :clicks
        | :reach
        | :unique_clicks
        | :results
        | :click_through_rate
        | :cost_per_click
        | :cost_per_mille
        | :cost_per_result
        | :frequency
        | :return_on_ad_spend

      module Order
        extend WhopSDK::Internal::Type::Enum

        CREATED_AT: :created_at
        SPEND: :spend
        IMPRESSIONS: :impressions
        CLICKS: :clicks
        REACH: :reach
        UNIQUE_CLICKS: :unique_clicks
        RESULTS: :results
        CLICK_THROUGH_RATE: :click_through_rate
        COST_PER_CLICK: :cost_per_click
        COST_PER_MILLE: :cost_per_mille
        COST_PER_RESULT: :cost_per_result
        FREQUENCY: :frequency
        RETURN_ON_AD_SPEND: :return_on_ad_spend

        def self?.values: -> ::Array[WhopSDK::Models::AdListParams::order]
      end

      type order_by = :spend | :return_on_ad_spend | :roas

      module OrderBy
        extend WhopSDK::Internal::Type::Enum

        SPEND: :spend
        RETURN_ON_AD_SPEND: :return_on_ad_spend
        ROAS: :roas

        def self?.values: -> ::Array[WhopSDK::Models::AdListParams::order_by]
      end
    end
  end
end
