module WhopSDK
  module Models
    type ad_list_params =
      {
        ad_group_id: String?,
        after: String?,
        before: String?,
        campaign_id: String?,
        company_id: String?,
        created_after: Time?,
        created_before: Time?,
        first: Integer?,
        last: Integer?,
        status: WhopSDK::Models::external_ad_status?
      }
      & WhopSDK::Internal::Type::request_parameters

    class AdListParams < WhopSDK::Internal::Type::BaseModel
      extend WhopSDK::Internal::Type::RequestParameters::Converter
      include WhopSDK::Internal::Type::RequestParameters

      attr_accessor ad_group_id: String?

      attr_accessor after: String?

      attr_accessor before: String?

      attr_accessor campaign_id: String?

      attr_accessor company_id: String?

      attr_accessor created_after: Time?

      attr_accessor created_before: Time?

      attr_accessor first: Integer?

      attr_accessor last: Integer?

      attr_accessor status: WhopSDK::Models::external_ad_status?

      def initialize: (
        ?ad_group_id: String?,
        ?after: String?,
        ?before: String?,
        ?campaign_id: String?,
        ?company_id: String?,
        ?created_after: Time?,
        ?created_before: Time?,
        ?first: Integer?,
        ?last: Integer?,
        ?status: WhopSDK::Models::external_ad_status?,
        ?request_options: WhopSDK::request_opts
      ) -> void

      def to_hash: -> {
        ad_group_id: String?,
        after: String?,
        before: String?,
        campaign_id: String?,
        company_id: String?,
        created_after: Time?,
        created_before: Time?,
        first: Integer?,
        last: Integer?,
        status: WhopSDK::Models::external_ad_status?,
        request_options: WhopSDK::RequestOptions
      }
    end
  end
end
