module WhopSDK
  module Models
    type ad_report_retrieve_params =
      {
        from: Time,
        to: Time,
        ad_campaign_id: String?,
        ad_group_id: String?,
        ad_id: String?,
        breakdown: WhopSDK::Models::AdReportRetrieveParams::breakdown?,
        currency: String?
      }
      & WhopSDK::Internal::Type::request_parameters

    class AdReportRetrieveParams < WhopSDK::Internal::Type::BaseModel
      extend WhopSDK::Internal::Type::RequestParameters::Converter
      include WhopSDK::Internal::Type::RequestParameters

      attr_accessor from: Time

      attr_accessor to: Time

      attr_accessor ad_campaign_id: String?

      attr_accessor ad_group_id: String?

      attr_accessor ad_id: String?

      attr_accessor breakdown: WhopSDK::Models::AdReportRetrieveParams::breakdown?

      attr_accessor currency: String?

      def initialize: (
        from: Time,
        to: Time,
        ?ad_campaign_id: String?,
        ?ad_group_id: String?,
        ?ad_id: String?,
        ?breakdown: WhopSDK::Models::AdReportRetrieveParams::breakdown?,
        ?currency: String?,
        ?request_options: WhopSDK::request_opts
      ) -> void

      def to_hash: -> {
        from: Time,
        to: Time,
        ad_campaign_id: String?,
        ad_group_id: String?,
        ad_id: String?,
        breakdown: WhopSDK::Models::AdReportRetrieveParams::breakdown?,
        currency: String?,
        request_options: WhopSDK::RequestOptions
      }

      type breakdown = :daily | :hourly

      module Breakdown
        extend WhopSDK::Internal::Type::Enum

        DAILY: :daily
        HOURLY: :hourly

        def self?.values: -> ::Array[WhopSDK::Models::AdReportRetrieveParams::breakdown]
      end
    end
  end
end
