module WhopSDK
  module Models
    type ad_report_retrieve_params =
      {
        from: Time,
        to: Time,
        ad_campaign_id: String?,
        ad_group_id: String?,
        ad_id: String?,
        breakdown: WhopSDK::Models::AdReportRetrieveParams::breakdown?,
        company_id: String?,
        currency: String?,
        granularity: WhopSDK::Models::granularities?
      }
      & WhopSDK::Internal::Type::request_parameters

    class AdReportRetrieveParams < WhopSDK::Internal::Type::BaseModel
      extend WhopSDK::Internal::Type::RequestParameters::Converter
      include WhopSDK::Internal::Type::RequestParameters

      attr_accessor from: Time

      attr_accessor to: Time

      attr_accessor ad_campaign_id: String?

      attr_accessor ad_group_id: String?

      attr_accessor ad_id: String?

      attr_accessor breakdown: WhopSDK::Models::AdReportRetrieveParams::breakdown?

      attr_accessor company_id: String?

      attr_accessor currency: String?

      attr_accessor granularity: WhopSDK::Models::granularities?

      def initialize: (
        from: Time,
        to: Time,
        ?ad_campaign_id: String?,
        ?ad_group_id: String?,
        ?ad_id: String?,
        ?breakdown: WhopSDK::Models::AdReportRetrieveParams::breakdown?,
        ?company_id: String?,
        ?currency: String?,
        ?granularity: WhopSDK::Models::granularities?,
        ?request_options: WhopSDK::request_opts
      ) -> void

      def to_hash: -> {
        from: Time,
        to: Time,
        ad_campaign_id: String?,
        ad_group_id: String?,
        ad_id: String?,
        breakdown: WhopSDK::Models::AdReportRetrieveParams::breakdown?,
        company_id: String?,
        currency: String?,
        granularity: WhopSDK::Models::granularities?,
        request_options: WhopSDK::RequestOptions
      }

      type breakdown = :campaign | :ad_group | :ad

      module Breakdown
        extend WhopSDK::Internal::Type::Enum

        CAMPAIGN: :campaign
        AD_GROUP: :ad_group
        AD: :ad

        def self?.values: -> ::Array[WhopSDK::Models::AdReportRetrieveParams::breakdown]
      end
    end
  end
end
