module WhopSDK
  module Models
    type ad_retrieve_params =
      { id: String, stats_from: String, stats_to: String, time_zone: String }
      & WhopSDK::Internal::Type::request_parameters

    class AdRetrieveParams < WhopSDK::Internal::Type::BaseModel
      extend WhopSDK::Internal::Type::RequestParameters::Converter
      include WhopSDK::Internal::Type::RequestParameters

      attr_accessor id: String

      attr_reader stats_from: String?

      def stats_from=: (String) -> String

      attr_reader stats_to: String?

      def stats_to=: (String) -> String

      attr_reader time_zone: String?

      def time_zone=: (String) -> String

      def initialize: (
        id: String,
        ?stats_from: String,
        ?stats_to: String,
        ?time_zone: String,
        ?request_options: WhopSDK::request_opts
      ) -> void

      def to_hash: -> {
        id: String,
        stats_from: String,
        stats_to: String,
        time_zone: String,
        request_options: WhopSDK::RequestOptions
      }
    end
  end
end
