module WhopSDK
  module Models
    type ad_retrieve_response =
      {
        id: String,
        ad_campaign: WhopSDK::Models::AdRetrieveResponse::AdCampaign,
        ad_group: WhopSDK::Models::AdRetrieveResponse::AdGroup,
        created_at: Time,
        platform: WhopSDK::Models::AdRetrieveResponse::platform,
        status: WhopSDK::Models::AdRetrieveResponse::status,
        title: String?,
        updated_at: Time
      }

    class AdRetrieveResponse < WhopSDK::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor ad_campaign: WhopSDK::Models::AdRetrieveResponse::AdCampaign

      attr_accessor ad_group: WhopSDK::Models::AdRetrieveResponse::AdGroup

      attr_accessor created_at: Time

      attr_accessor platform: WhopSDK::Models::AdRetrieveResponse::platform

      attr_accessor status: WhopSDK::Models::AdRetrieveResponse::status

      attr_accessor title: String?

      attr_accessor updated_at: Time

      def initialize: (
        id: String,
        ad_campaign: WhopSDK::Models::AdRetrieveResponse::AdCampaign,
        ad_group: WhopSDK::Models::AdRetrieveResponse::AdGroup,
        created_at: Time,
        platform: WhopSDK::Models::AdRetrieveResponse::platform,
        status: WhopSDK::Models::AdRetrieveResponse::status,
        title: String?,
        updated_at: Time
      ) -> void

      def to_hash: -> {
        id: String,
        ad_campaign: WhopSDK::Models::AdRetrieveResponse::AdCampaign,
        ad_group: WhopSDK::Models::AdRetrieveResponse::AdGroup,
        created_at: Time,
        platform: WhopSDK::Models::AdRetrieveResponse::platform,
        status: WhopSDK::Models::AdRetrieveResponse::status,
        title: String?,
        updated_at: Time
      }

      type ad_campaign = { id: String }

      class AdCampaign < WhopSDK::Internal::Type::BaseModel
        attr_accessor id: String

        def initialize: (id: String) -> void

        def to_hash: -> { id: String }
      end

      type ad_group = { id: String }

      class AdGroup < WhopSDK::Internal::Type::BaseModel
        attr_accessor id: String

        def initialize: (id: String) -> void

        def to_hash: -> { id: String }
      end

      type platform = :meta | :tiktok

      module Platform
        extend WhopSDK::Internal::Type::Enum

        META: :meta
        TIKTOK: :tiktok

        def self?.values: -> ::Array[WhopSDK::Models::AdRetrieveResponse::platform]
      end

      type status =
        :active | :paused | :inactive | :in_review | :rejected | :flagged

      module Status
        extend WhopSDK::Internal::Type::Enum

        ACTIVE: :active
        PAUSED: :paused
        INACTIVE: :inactive
        IN_REVIEW: :in_review
        REJECTED: :rejected
        FLAGGED: :flagged

        def self?.values: -> ::Array[WhopSDK::Models::AdRetrieveResponse::status]
      end
    end
  end
end
