module WhopSDK
  module Models
    type ai_chat_update_params =
      {
        id: String,
        current_company_id: String?,
        notification_preference: WhopSDK::Models::notification_preferences?,
        title: String?
      }
      & WhopSDK::Internal::Type::request_parameters

    class AIChatUpdateParams < WhopSDK::Internal::Type::BaseModel
      extend WhopSDK::Internal::Type::RequestParameters::Converter
      include WhopSDK::Internal::Type::RequestParameters

      attr_accessor id: String

      attr_accessor current_company_id: String?

      attr_accessor notification_preference: WhopSDK::Models::notification_preferences?

      attr_accessor title: String?

      def initialize: (
        id: String,
        ?current_company_id: String?,
        ?notification_preference: WhopSDK::Models::notification_preferences?,
        ?title: String?,
        ?request_options: WhopSDK::request_opts
      ) -> void

      def to_hash: -> {
        id: String,
        current_company_id: String?,
        notification_preference: WhopSDK::Models::notification_preferences?,
        title: String?,
        request_options: WhopSDK::RequestOptions
      }
    end
  end
end
