module WhopSDK
  module Models
    type ai_chat_create_params =
      {
        message_text: String,
        current_company_id: String?,
        message_attachments: ::Array[WhopSDK::AIChatCreateParams::MessageAttachment]?,
        message_source: WhopSDK::Models::AIChatCreateParams::message_source?,
        title: String?
      }
      & WhopSDK::Internal::Type::request_parameters

    class AIChatCreateParams < WhopSDK::Internal::Type::BaseModel
      extend WhopSDK::Internal::Type::RequestParameters::Converter
      include WhopSDK::Internal::Type::RequestParameters

      attr_accessor message_text: String

      attr_accessor current_company_id: String?

      attr_accessor message_attachments: ::Array[WhopSDK::AIChatCreateParams::MessageAttachment]?

      attr_accessor message_source: WhopSDK::Models::AIChatCreateParams::message_source?

      attr_accessor title: String?

      def initialize: (
        message_text: String,
        ?current_company_id: String?,
        ?message_attachments: ::Array[WhopSDK::AIChatCreateParams::MessageAttachment]?,
        ?message_source: WhopSDK::Models::AIChatCreateParams::message_source?,
        ?title: String?,
        ?request_options: WhopSDK::request_opts
      ) -> void

      def to_hash: -> {
        message_text: String,
        current_company_id: String?,
        message_attachments: ::Array[WhopSDK::AIChatCreateParams::MessageAttachment]?,
        message_source: WhopSDK::Models::AIChatCreateParams::message_source?,
        title: String?,
        request_options: WhopSDK::RequestOptions
      }

      type message_attachment = { id: String }

      class MessageAttachment < WhopSDK::Internal::Type::BaseModel
        attr_accessor id: String

        def initialize: (id: String) -> void

        def to_hash: -> { id: String }
      end

      type message_source = :manual | :suggestion | :link

      module MessageSource
        extend WhopSDK::Internal::Type::Enum

        MANUAL: :manual
        SUGGESTION: :suggestion
        LINK: :link

        def self?.values: -> ::Array[WhopSDK::Models::AIChatCreateParams::message_source]
      end
    end
  end
end
