module WhopSDK
  module Models
    type ai_chat_create_params =
      { title: String? } & WhopSDK::Internal::Type::request_parameters

    class AIChatCreateParams < WhopSDK::Internal::Type::BaseModel
      extend WhopSDK::Internal::Type::RequestParameters::Converter
      include WhopSDK::Internal::Type::RequestParameters

      attr_accessor title: String?

      def initialize: (
        ?title: String?,
        ?request_options: WhopSDK::request_opts
      ) -> void

      def to_hash: -> {
        title: String?,
        request_options: WhopSDK::RequestOptions
      }
    end
  end
end
