module WhopSDK
  module Models
    type ai_chat_update_params =
      {
        id: String,
        current_company_id: String?,
        notification_preference: WhopSDK::Models::AIChatUpdateParams::notification_preference?,
        title: String?
      }
      & WhopSDK::Internal::Type::request_parameters

    class AIChatUpdateParams < WhopSDK::Internal::Type::BaseModel
      extend WhopSDK::Internal::Type::RequestParameters::Converter
      include WhopSDK::Internal::Type::RequestParameters

      attr_accessor id: String

      attr_accessor current_company_id: String?

      attr_accessor notification_preference: WhopSDK::Models::AIChatUpdateParams::notification_preference?

      attr_accessor title: String?

      def initialize: (
        id: String,
        ?current_company_id: String?,
        ?notification_preference: WhopSDK::Models::AIChatUpdateParams::notification_preference?,
        ?title: String?,
        ?request_options: WhopSDK::request_opts
      ) -> void

      def to_hash: -> {
        id: String,
        current_company_id: String?,
        notification_preference: WhopSDK::Models::AIChatUpdateParams::notification_preference?,
        title: String?,
        request_options: WhopSDK::RequestOptions
      }

      type notification_preference = :all | :none

      module NotificationPreference
        extend WhopSDK::Internal::Type::Enum

        ALL: :all
        NONE: :none

        def self?.values: -> ::Array[WhopSDK::Models::AIChatUpdateParams::notification_preference]
      end
    end
  end
end
