module WhopSDK
  module Models
    type ai_chat_list_params =
      {
        after: String,
        agent_identifier: WhopSDK::Models::AIChatListParams::agent_identifier,
        before: String,
        first: Integer,
        last: Integer,
        only_active_crons: bool
      }
      & WhopSDK::Internal::Type::request_parameters

    class AIChatListParams < WhopSDK::Internal::Type::BaseModel
      extend WhopSDK::Internal::Type::RequestParameters::Converter
      include WhopSDK::Internal::Type::RequestParameters

      attr_reader after: String?

      def after=: (String) -> String

      attr_reader agent_identifier: WhopSDK::Models::AIChatListParams::agent_identifier?

      def agent_identifier=: (
        WhopSDK::Models::AIChatListParams::agent_identifier
      ) -> WhopSDK::Models::AIChatListParams::agent_identifier

      attr_reader before: String?

      def before=: (String) -> String

      attr_reader first: Integer?

      def first=: (Integer) -> Integer

      attr_reader last: Integer?

      def last=: (Integer) -> Integer

      attr_reader only_active_crons: bool?

      def only_active_crons=: (bool) -> bool

      def initialize: (
        ?after: String,
        ?agent_identifier: WhopSDK::Models::AIChatListParams::agent_identifier,
        ?before: String,
        ?first: Integer,
        ?last: Integer,
        ?only_active_crons: bool,
        ?request_options: WhopSDK::request_opts
      ) -> void

      def to_hash: -> {
        after: String,
        agent_identifier: WhopSDK::Models::AIChatListParams::agent_identifier,
        before: String,
        first: Integer,
        last: Integer,
        only_active_crons: bool,
        request_options: WhopSDK::RequestOptions
      }

      type agent_identifier = :general | :support

      module AgentIdentifier
        extend WhopSDK::Internal::Type::Enum

        GENERAL: :general
        SUPPORT: :support

        def self?.values: -> ::Array[WhopSDK::Models::AIChatListParams::agent_identifier]
      end
    end
  end
end
