module WhopSDK
  module Models
    type app_update_params =
      {
        app_store_description: String?,
        app_type: WhopSDK::Models::app_type?,
        base_url: String?,
        dashboard_path: String?,
        description: String?,
        discover_path: String?,
        experience_path: String?,
        icon: WhopSDK::Models::AppUpdateParams::icon?,
        name: String?,
        required_scopes: ::Array[WhopSDK::Models::AppUpdateParams::required_scope]?,
        status: WhopSDK::Models::app_statuses?
      }
      & WhopSDK::Internal::Type::request_parameters

    class AppUpdateParams < WhopSDK::Internal::Type::BaseModel
      extend WhopSDK::Internal::Type::RequestParameters::Converter
      include WhopSDK::Internal::Type::RequestParameters

      attr_accessor app_store_description: String?

      attr_accessor app_type: WhopSDK::Models::app_type?

      attr_accessor base_url: String?

      attr_accessor dashboard_path: String?

      attr_accessor description: String?

      attr_accessor discover_path: String?

      attr_accessor experience_path: String?

      attr_accessor icon: WhopSDK::Models::AppUpdateParams::icon?

      attr_accessor name: String?

      attr_accessor required_scopes: ::Array[WhopSDK::Models::AppUpdateParams::required_scope]?

      attr_accessor status: WhopSDK::Models::app_statuses?

      def initialize: (
        ?app_store_description: String?,
        ?app_type: WhopSDK::Models::app_type?,
        ?base_url: String?,
        ?dashboard_path: String?,
        ?description: String?,
        ?discover_path: String?,
        ?experience_path: String?,
        ?icon: WhopSDK::Models::AppUpdateParams::icon?,
        ?name: String?,
        ?required_scopes: ::Array[WhopSDK::Models::AppUpdateParams::required_scope]?,
        ?status: WhopSDK::Models::app_statuses?,
        ?request_options: WhopSDK::request_opts
      ) -> void

      def to_hash: -> {
        app_store_description: String?,
        app_type: WhopSDK::Models::app_type?,
        base_url: String?,
        dashboard_path: String?,
        description: String?,
        discover_path: String?,
        experience_path: String?,
        icon: WhopSDK::Models::AppUpdateParams::icon?,
        name: String?,
        required_scopes: ::Array[WhopSDK::Models::AppUpdateParams::required_scope]?,
        status: WhopSDK::Models::app_statuses?,
        request_options: WhopSDK::RequestOptions
      }

      type icon =
        WhopSDK::AppUpdateParams::Icon::AttachmentInputWithDirectUploadID
        | WhopSDK::AppUpdateParams::Icon::AttachmentInputWithID

      module Icon
        extend WhopSDK::Internal::Type::Union

        type attachment_input_with_direct_upload_id =
          { direct_upload_id: String }

        class AttachmentInputWithDirectUploadID < WhopSDK::Internal::Type::BaseModel
          attr_accessor direct_upload_id: String

          def initialize: (direct_upload_id: String) -> void

          def to_hash: -> { direct_upload_id: String }
        end

        type attachment_input_with_id = { id: String }

        class AttachmentInputWithID < WhopSDK::Internal::Type::BaseModel
          attr_accessor id: String

          def initialize: (id: String) -> void

          def to_hash: -> { id: String }
        end

        def self?.variants: -> ::Array[WhopSDK::Models::AppUpdateParams::icon]
      end

      type required_scope = :read_user

      module RequiredScope
        extend WhopSDK::Internal::Type::Enum

        READ_USER: :read_user

        def self?.values: -> ::Array[WhopSDK::Models::AppUpdateParams::required_scope]
      end
    end
  end
end
