module WhopSDK
  module Models
    type app_list_params =
      {
        account_id: String,
        after: String,
        app_type: WhopSDK::Models::AppListParams::app_type,
        before: String,
        direction: WhopSDK::Models::AppListParams::direction,
        first: Integer,
        last: Integer,
        order: WhopSDK::Models::AppListParams::order,
        query: String,
        recommended: bool,
        verified: bool,
        verified_apps_only: bool,
        view_type: WhopSDK::Models::AppListParams::view_type,
        api_version_date: String
      }
      & WhopSDK::Internal::Type::request_parameters

    class AppListParams < WhopSDK::Internal::Type::BaseModel
      extend WhopSDK::Internal::Type::RequestParameters::Converter
      include WhopSDK::Internal::Type::RequestParameters

      attr_reader account_id: String?

      def account_id=: (String) -> String

      attr_reader after: String?

      def after=: (String) -> String

      attr_reader app_type: WhopSDK::Models::AppListParams::app_type?

      def app_type=: (
        WhopSDK::Models::AppListParams::app_type
      ) -> WhopSDK::Models::AppListParams::app_type

      attr_reader before: String?

      def before=: (String) -> String

      attr_reader direction: WhopSDK::Models::AppListParams::direction?

      def direction=: (
        WhopSDK::Models::AppListParams::direction
      ) -> WhopSDK::Models::AppListParams::direction

      attr_reader first: Integer?

      def first=: (Integer) -> Integer

      attr_reader last: Integer?

      def last=: (Integer) -> Integer

      attr_reader order: WhopSDK::Models::AppListParams::order?

      def order=: (
        WhopSDK::Models::AppListParams::order
      ) -> WhopSDK::Models::AppListParams::order

      attr_reader query: String?

      def query=: (String) -> String

      attr_reader recommended: bool?

      def recommended=: (bool) -> bool

      attr_reader verified: bool?

      def verified=: (bool) -> bool

      attr_reader verified_apps_only: bool?

      def verified_apps_only=: (bool) -> bool

      attr_reader view_type: WhopSDK::Models::AppListParams::view_type?

      def view_type=: (
        WhopSDK::Models::AppListParams::view_type
      ) -> WhopSDK::Models::AppListParams::view_type

      attr_reader api_version_date: String?

      def api_version_date=: (String) -> String

      def initialize: (
        ?account_id: String,
        ?after: String,
        ?app_type: WhopSDK::Models::AppListParams::app_type,
        ?before: String,
        ?direction: WhopSDK::Models::AppListParams::direction,
        ?first: Integer,
        ?last: Integer,
        ?order: WhopSDK::Models::AppListParams::order,
        ?query: String,
        ?recommended: bool,
        ?verified: bool,
        ?verified_apps_only: bool,
        ?view_type: WhopSDK::Models::AppListParams::view_type,
        ?api_version_date: String,
        ?request_options: WhopSDK::request_opts
      ) -> void

      def to_hash: -> {
        account_id: String,
        after: String,
        app_type: WhopSDK::Models::AppListParams::app_type,
        before: String,
        direction: WhopSDK::Models::AppListParams::direction,
        first: Integer,
        last: Integer,
        order: WhopSDK::Models::AppListParams::order,
        query: String,
        recommended: bool,
        verified: bool,
        verified_apps_only: bool,
        view_type: WhopSDK::Models::AppListParams::view_type,
        api_version_date: String,
        request_options: WhopSDK::RequestOptions
      }

      type app_type = :b2b_app | :b2c_app | :company_app | :component | :website

      module AppType
        extend WhopSDK::Internal::Type::Enum

        B2B_APP: :b2b_app
        B2C_APP: :b2c_app
        COMPANY_APP: :company_app
        COMPONENT: :component
        WEBSITE: :website

        def self?.values: -> ::Array[WhopSDK::Models::AppListParams::app_type]
      end

      type direction = :asc | :desc

      module Direction
        extend WhopSDK::Internal::Type::Enum

        ASC: :asc
        DESC: :desc

        def self?.values: -> ::Array[WhopSDK::Models::AppListParams::direction]
      end

      type order =
        :created_at
        | :discoverable_at
        | :template_usage
        | :total_installs_last_30_days
        | :total_installs_last_7_days

      module Order
        extend WhopSDK::Internal::Type::Enum

        CREATED_AT: :created_at
        DISCOVERABLE_AT: :discoverable_at
        TEMPLATE_USAGE: :template_usage
        TOTAL_INSTALLS_LAST_30_DAYS: :total_installs_last_30_days
        TOTAL_INSTALLS_LAST_7_DAYS: :total_installs_last_7_days

        def self?.values: -> ::Array[WhopSDK::Models::AppListParams::order]
      end

      type view_type =
        :hub | :discover | :dash | :dashboard | :analytics | :skills | :openapi

      module ViewType
        extend WhopSDK::Internal::Type::Enum

        HUB: :hub
        DISCOVER: :discover
        DASH: :dash
        DASHBOARD: :dashboard
        ANALYTICS: :analytics
        SKILLS: :skills
        OPENAPI: :openapi

        def self?.values: -> ::Array[WhopSDK::Models::AppListParams::view_type]
      end
    end
  end
end
