module WhopSDK
  module Models
    type app_create_params =
      {
        company_id: String,
        name: String,
        base_url: String?,
        icon: WhopSDK::AppCreateParams::Icon?,
        redirect_uris: ::Array[String]?
      }
      & WhopSDK::Internal::Type::request_parameters

    class AppCreateParams < WhopSDK::Internal::Type::BaseModel
      extend WhopSDK::Internal::Type::RequestParameters::Converter
      include WhopSDK::Internal::Type::RequestParameters

      attr_accessor company_id: String

      attr_accessor name: String

      attr_accessor base_url: String?

      attr_accessor icon: WhopSDK::AppCreateParams::Icon?

      attr_accessor redirect_uris: ::Array[String]?

      def initialize: (
        company_id: String,
        name: String,
        ?base_url: String?,
        ?icon: WhopSDK::AppCreateParams::Icon?,
        ?redirect_uris: ::Array[String]?,
        ?request_options: WhopSDK::request_opts
      ) -> void

      def to_hash: -> {
        company_id: String,
        name: String,
        base_url: String?,
        icon: WhopSDK::AppCreateParams::Icon?,
        redirect_uris: ::Array[String]?,
        request_options: WhopSDK::RequestOptions
      }

      type icon = { id: String }

      class Icon < WhopSDK::Internal::Type::BaseModel
        attr_accessor id: String

        def initialize: (id: String) -> void

        def to_hash: -> { id: String }
      end
    end
  end
end
