module WhopSDK
  module Models
    type app_build_list_response =
      {
        id: String,
        checksum: String,
        created_at: Time,
        file_url: String,
        is_production: bool,
        platform: WhopSDK::Models::app_build_platforms,
        review_message: String?,
        status: WhopSDK::Models::app_build_statuses,
        supported_app_view_types: ::Array[WhopSDK::Models::app_view_type]
      }

    class AppBuildListResponse < WhopSDK::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor checksum: String

      attr_accessor created_at: Time

      attr_accessor file_url: String

      attr_accessor is_production: bool

      attr_accessor platform: WhopSDK::Models::app_build_platforms

      attr_accessor review_message: String?

      attr_accessor status: WhopSDK::Models::app_build_statuses

      attr_accessor supported_app_view_types: ::Array[WhopSDK::Models::app_view_type]

      def initialize: (
        id: String,
        checksum: String,
        created_at: Time,
        file_url: String,
        is_production: bool,
        platform: WhopSDK::Models::app_build_platforms,
        review_message: String?,
        status: WhopSDK::Models::app_build_statuses,
        supported_app_view_types: ::Array[WhopSDK::Models::app_view_type]
      ) -> void

      def to_hash: -> {
        id: String,
        checksum: String,
        created_at: Time,
        file_url: String,
        is_production: bool,
        platform: WhopSDK::Models::app_build_platforms,
        review_message: String?,
        status: WhopSDK::Models::app_build_statuses,
        supported_app_view_types: ::Array[WhopSDK::Models::app_view_type]
      }
    end
  end
end
