module WhopSDK
  module Models
    type app_build_list_params =
      {
        app_id: String,
        after: String,
        before: String,
        created_after: WhopSDK::Models::AppBuildListParams::created_after,
        created_before: WhopSDK::Models::AppBuildListParams::created_before,
        first: Integer,
        last: Integer,
        platform: WhopSDK::Models::AppBuildListParams::platform,
        status: WhopSDK::Models::AppBuildListParams::status,
        api_version_date: String
      }
      & WhopSDK::Internal::Type::request_parameters

    class AppBuildListParams < WhopSDK::Internal::Type::BaseModel
      extend WhopSDK::Internal::Type::RequestParameters::Converter
      include WhopSDK::Internal::Type::RequestParameters

      attr_accessor app_id: String

      attr_reader after: String?

      def after=: (String) -> String

      attr_reader before: String?

      def before=: (String) -> String

      attr_reader created_after: WhopSDK::Models::AppBuildListParams::created_after?

      def created_after=: (
        WhopSDK::Models::AppBuildListParams::created_after
      ) -> WhopSDK::Models::AppBuildListParams::created_after

      attr_reader created_before: WhopSDK::Models::AppBuildListParams::created_before?

      def created_before=: (
        WhopSDK::Models::AppBuildListParams::created_before
      ) -> WhopSDK::Models::AppBuildListParams::created_before

      attr_reader first: Integer?

      def first=: (Integer) -> Integer

      attr_reader last: Integer?

      def last=: (Integer) -> Integer

      attr_reader platform: WhopSDK::Models::AppBuildListParams::platform?

      def platform=: (
        WhopSDK::Models::AppBuildListParams::platform
      ) -> WhopSDK::Models::AppBuildListParams::platform

      attr_reader status: WhopSDK::Models::AppBuildListParams::status?

      def status=: (
        WhopSDK::Models::AppBuildListParams::status
      ) -> WhopSDK::Models::AppBuildListParams::status

      attr_reader api_version_date: String?

      def api_version_date=: (String) -> String

      def initialize: (
        app_id: String,
        ?after: String,
        ?before: String,
        ?created_after: WhopSDK::Models::AppBuildListParams::created_after,
        ?created_before: WhopSDK::Models::AppBuildListParams::created_before,
        ?first: Integer,
        ?last: Integer,
        ?platform: WhopSDK::Models::AppBuildListParams::platform,
        ?status: WhopSDK::Models::AppBuildListParams::status,
        ?api_version_date: String,
        ?request_options: WhopSDK::request_opts
      ) -> void

      def to_hash: -> {
        app_id: String,
        after: String,
        before: String,
        created_after: WhopSDK::Models::AppBuildListParams::created_after,
        created_before: WhopSDK::Models::AppBuildListParams::created_before,
        first: Integer,
        last: Integer,
        platform: WhopSDK::Models::AppBuildListParams::platform,
        status: WhopSDK::Models::AppBuildListParams::status,
        api_version_date: String,
        request_options: WhopSDK::RequestOptions
      }

      type created_after = Integer | String

      module CreatedAfter
        extend WhopSDK::Internal::Type::Union

        def self?.variants: -> ::Array[WhopSDK::Models::AppBuildListParams::created_after]
      end

      type created_before = Integer | String

      module CreatedBefore
        extend WhopSDK::Internal::Type::Union

        def self?.variants: -> ::Array[WhopSDK::Models::AppBuildListParams::created_before]
      end

      type platform = :ios | :android | :web

      module Platform
        extend WhopSDK::Internal::Type::Enum

        IOS: :ios
        ANDROID: :android
        WEB: :web

        def self?.values: -> ::Array[WhopSDK::Models::AppBuildListParams::platform]
      end

      type status = :draft | :pending | :approved | :rejected

      module Status
        extend WhopSDK::Internal::Type::Enum

        DRAFT: :draft
        PENDING: :pending
        APPROVED: :approved
        REJECTED: :rejected

        def self?.values: -> ::Array[WhopSDK::Models::AppBuildListParams::status]
      end
    end
  end
end
