module WhopSDK
  module Models
    type app_list_response =
      {
        id: String,
        base_url: String?,
        company: WhopSDK::Models::AppListResponse::Company,
        creator: WhopSDK::Models::AppListResponse::Creator,
        dashboard_path: String?,
        description: String?,
        discover_path: String?,
        domain_id: String,
        experience_path: String?,
        icon: WhopSDK::Models::AppListResponse::Icon?,
        name: String,
        status: WhopSDK::Models::app_statuses,
        verified: bool
      }

    class AppListResponse < WhopSDK::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor base_url: String?

      attr_accessor company: WhopSDK::Models::AppListResponse::Company

      attr_accessor creator: WhopSDK::Models::AppListResponse::Creator

      attr_accessor dashboard_path: String?

      attr_accessor description: String?

      attr_accessor discover_path: String?

      attr_accessor domain_id: String

      attr_accessor experience_path: String?

      attr_accessor icon: WhopSDK::Models::AppListResponse::Icon?

      attr_accessor name: String

      attr_accessor status: WhopSDK::Models::app_statuses

      attr_accessor verified: bool

      def initialize: (
        id: String,
        base_url: String?,
        company: WhopSDK::Models::AppListResponse::Company,
        creator: WhopSDK::Models::AppListResponse::Creator,
        dashboard_path: String?,
        description: String?,
        discover_path: String?,
        domain_id: String,
        experience_path: String?,
        icon: WhopSDK::Models::AppListResponse::Icon?,
        name: String,
        status: WhopSDK::Models::app_statuses,
        verified: bool
      ) -> void

      def to_hash: -> {
        id: String,
        base_url: String?,
        company: WhopSDK::Models::AppListResponse::Company,
        creator: WhopSDK::Models::AppListResponse::Creator,
        dashboard_path: String?,
        description: String?,
        discover_path: String?,
        domain_id: String,
        experience_path: String?,
        icon: WhopSDK::Models::AppListResponse::Icon?,
        name: String,
        status: WhopSDK::Models::app_statuses,
        verified: bool
      }

      type company = { id: String, title: String }

      class Company < WhopSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor title: String

        def initialize: (id: String, title: String) -> void

        def to_hash: -> { id: String, title: String }
      end

      type creator = { id: String, name: String?, username: String }

      class Creator < WhopSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor name: String?

        attr_accessor username: String

        def initialize: (id: String, name: String?, username: String) -> void

        def to_hash: -> { id: String, name: String?, username: String }
      end

      type icon = { url: String? }

      class Icon < WhopSDK::Internal::Type::BaseModel
        attr_accessor url: String?

        def initialize: (url: String?) -> void

        def to_hash: -> { url: String? }
      end
    end
  end
end
