module WhopSDK
  module Models
    type app_type = :b2b_app | :b2c_app | :company_app | :component

    module AppType
      extend WhopSDK::Internal::Type::Enum

      B2B_APP: :b2b_app
      B2C_APP: :b2c_app
      COMPANY_APP: :company_app
      COMPONENT: :component

      def self?.values: -> ::Array[WhopSDK::Models::app_type]
    end
  end
end
