module WhopSDK
  module Models
    type app_build_list_params =
      {
        app_id: String,
        after: String?,
        before: String?,
        created_after: Time?,
        created_before: Time?,
        first: Integer?,
        last: Integer?,
        platform: WhopSDK::Models::app_build_platforms?,
        status: WhopSDK::Models::app_build_statuses?
      }
      & WhopSDK::Internal::Type::request_parameters

    class AppBuildListParams < WhopSDK::Internal::Type::BaseModel
      extend WhopSDK::Internal::Type::RequestParameters::Converter
      include WhopSDK::Internal::Type::RequestParameters

      attr_accessor app_id: String

      attr_accessor after: String?

      attr_accessor before: String?

      attr_accessor created_after: Time?

      attr_accessor created_before: Time?

      attr_accessor first: Integer?

      attr_accessor last: Integer?

      attr_accessor platform: WhopSDK::Models::app_build_platforms?

      attr_accessor status: WhopSDK::Models::app_build_statuses?

      def initialize: (
        app_id: String,
        ?after: String?,
        ?before: String?,
        ?created_after: Time?,
        ?created_before: Time?,
        ?first: Integer?,
        ?last: Integer?,
        ?platform: WhopSDK::Models::app_build_platforms?,
        ?status: WhopSDK::Models::app_build_statuses?,
        ?request_options: WhopSDK::request_opts
      ) -> void

      def to_hash: -> {
        app_id: String,
        after: String?,
        before: String?,
        created_after: Time?,
        created_before: Time?,
        first: Integer?,
        last: Integer?,
        platform: WhopSDK::Models::app_build_platforms?,
        status: WhopSDK::Models::app_build_statuses?,
        request_options: WhopSDK::RequestOptions
      }
    end
  end
end
