module WhopSDK
  module Models
    type app_view_type =
      :hub | :discover | :dash | :dashboard | :analytics | :skills | :openapi

    module AppViewType
      extend WhopSDK::Internal::Type::Enum

      HUB: :hub
      DISCOVER: :discover
      DASH: :dash
      DASHBOARD: :dashboard
      ANALYTICS: :analytics
      SKILLS: :skills
      OPENAPI: :openapi

      def self?.values: -> ::Array[WhopSDK::Models::app_view_type]
    end
  end
end
