module WhopSDK
  module Models
    type authorized_user_create_params =
      {
        account_id: String,
        role: WhopSDK::Models::AuthorizedUserCreateParams::role,
        user_id: String,
        elevation: WhopSDK::AuthorizedUserCreateParams::Elevation?,
        send_emails: bool?
      }
      & WhopSDK::Internal::Type::request_parameters

    class AuthorizedUserCreateParams < WhopSDK::Internal::Type::BaseModel
      extend WhopSDK::Internal::Type::RequestParameters::Converter
      include WhopSDK::Internal::Type::RequestParameters

      attr_accessor account_id: String

      attr_accessor role: WhopSDK::Models::AuthorizedUserCreateParams::role

      attr_accessor user_id: String

      attr_accessor elevation: WhopSDK::AuthorizedUserCreateParams::Elevation?

      attr_accessor send_emails: bool?

      def initialize: (
        account_id: String,
        role: WhopSDK::Models::AuthorizedUserCreateParams::role,
        user_id: String,
        ?elevation: WhopSDK::AuthorizedUserCreateParams::Elevation?,
        ?send_emails: bool?,
        ?request_options: WhopSDK::request_opts
      ) -> void

      def to_hash: -> {
        account_id: String,
        role: WhopSDK::Models::AuthorizedUserCreateParams::role,
        user_id: String,
        elevation: WhopSDK::AuthorizedUserCreateParams::Elevation?,
        send_emails: bool?,
        request_options: WhopSDK::RequestOptions
      }

      type role = :owner | :admin | :sales_manager | :moderator | :advertiser

      module Role
        extend WhopSDK::Internal::Type::Enum

        OWNER: :owner
        ADMIN: :admin
        SALES_MANAGER: :sales_manager
        MODERATOR: :moderator
        ADVERTISER: :advertiser

        def self?.values: -> ::Array[WhopSDK::Models::AuthorizedUserCreateParams::role]
      end

      type elevation =
        {
          authenticator_data: String?,
          client_data_json: String?,
          credential_id: String?,
          email_code: String?,
          signature: String?,
          totp_code: String?,
          use_finance_session: bool?
        }

      class Elevation < WhopSDK::Internal::Type::BaseModel
        attr_accessor authenticator_data: String?

        attr_accessor client_data_json: String?

        attr_accessor credential_id: String?

        attr_accessor email_code: String?

        attr_accessor signature: String?

        attr_accessor totp_code: String?

        attr_accessor use_finance_session: bool?

        def initialize: (
          ?authenticator_data: String?,
          ?client_data_json: String?,
          ?credential_id: String?,
          ?email_code: String?,
          ?signature: String?,
          ?totp_code: String?,
          ?use_finance_session: bool?
        ) -> void

        def to_hash: -> {
          authenticator_data: String?,
          client_data_json: String?,
          credential_id: String?,
          email_code: String?,
          signature: String?,
          totp_code: String?,
          use_finance_session: bool?
        }
      end
    end
  end
end
