module WhopSDK
  module Models
    type bounty_list_params =
      {
        after: String,
        before: String,
        direction: WhopSDK::Models::direction,
        experience_id: String,
        first: Integer,
        last: Integer,
        status: WhopSDK::Models::BountyListParams::status
      }
      & WhopSDK::Internal::Type::request_parameters

    class BountyListParams < WhopSDK::Internal::Type::BaseModel
      extend WhopSDK::Internal::Type::RequestParameters::Converter
      include WhopSDK::Internal::Type::RequestParameters

      attr_reader after: String?

      def after=: (String) -> String

      attr_reader before: String?

      def before=: (String) -> String

      attr_reader direction: WhopSDK::Models::direction?

      def direction=: (WhopSDK::Models::direction) -> WhopSDK::Models::direction

      attr_reader experience_id: String?

      def experience_id=: (String) -> String

      attr_reader first: Integer?

      def first=: (Integer) -> Integer

      attr_reader last: Integer?

      def last=: (Integer) -> Integer

      attr_reader status: WhopSDK::Models::BountyListParams::status?

      def status=: (
        WhopSDK::Models::BountyListParams::status
      ) -> WhopSDK::Models::BountyListParams::status

      def initialize: (
        ?after: String,
        ?before: String,
        ?direction: WhopSDK::Models::direction,
        ?experience_id: String,
        ?first: Integer,
        ?last: Integer,
        ?status: WhopSDK::Models::BountyListParams::status,
        ?request_options: WhopSDK::request_opts
      ) -> void

      def to_hash: -> {
        after: String,
        before: String,
        direction: WhopSDK::Models::direction,
        experience_id: String,
        first: Integer,
        last: Integer,
        status: WhopSDK::Models::BountyListParams::status,
        request_options: WhopSDK::RequestOptions
      }

      type status = :published | :archived | :scheduled

      module Status
        extend WhopSDK::Internal::Type::Enum

        PUBLISHED: :published
        ARCHIVED: :archived
        SCHEDULED: :scheduled

        def self?.values: -> ::Array[WhopSDK::Models::BountyListParams::status]
      end
    end
  end
end
