module WhopSDK
  module Models
    type bounty_create_response =
      {
        id: String,
        accepted_deliverable_types: ::Array[WhopSDK::Models::BountyCreateResponse::accepted_deliverable_type],
        accepted_submissions_count: Integer,
        accepted_submissions_limit: Integer,
        accepted_submissions_per_user_limit: Integer,
        active_proof_livestream_feeds: ::Array[WhopSDK::Models::BountyCreateResponse::ActiveProofLivestreamFeed],
        affiliate_share_amount: Float,
        allowed_country_codes: ::Array[String],
        awaiting_review_submissions_count: Integer,
        budget_amount: Float,
        business_goal_type: WhopSDK::Models::BountyCreateResponse::business_goal_type?,
        cancel_requested_at: String?,
        capture_spec: WhopSDK::Models::BountyCreateResponse::CaptureSpec?,
        created_at: String,
        currency: WhopSDK::Models::BountyCreateResponse::currency,
        denied_submissions_count: Integer,
        description: String,
        discussion_experience_id: String?,
        discussion_feed_id: String?,
        discussion_post_id: String?,
        experience_id: String?,
        funding_account: WhopSDK::Models::BountyCreateResponse::FundingAccount?,
        gross_paid_out_amount: Float,
        gross_reward_amount: Float,
        hosting_account: WhopSDK::Models::BountyCreateResponse::HostingAccount?,
        min_total_verified_duration_seconds: Integer?,
        net_reward_amount: Float,
        poster: WhopSDK::Models::BountyCreateResponse::Poster,
        scheduled_frequency: WhopSDK::Models::BountyCreateResponse::scheduled_frequency?,
        scheduled_publish_at: String?,
        spots_remaining: Integer,
        status: WhopSDK::Models::BountyCreateResponse::status,
        submissions_closed_at: String?,
        title: String,
        unresolved_submissions_count: Integer,
        updated_at: String,
        viewer_accepted_submissions_count: Integer
      }

    class BountyCreateResponse < WhopSDK::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor accepted_deliverable_types: ::Array[WhopSDK::Models::BountyCreateResponse::accepted_deliverable_type]

      attr_accessor accepted_submissions_count: Integer

      attr_accessor accepted_submissions_limit: Integer

      attr_accessor accepted_submissions_per_user_limit: Integer

      attr_accessor active_proof_livestream_feeds: ::Array[WhopSDK::Models::BountyCreateResponse::ActiveProofLivestreamFeed]

      attr_accessor affiliate_share_amount: Float

      attr_accessor allowed_country_codes: ::Array[String]

      attr_accessor awaiting_review_submissions_count: Integer

      attr_accessor budget_amount: Float

      attr_accessor business_goal_type: WhopSDK::Models::BountyCreateResponse::business_goal_type?

      attr_accessor cancel_requested_at: String?

      attr_accessor capture_spec: WhopSDK::Models::BountyCreateResponse::CaptureSpec?

      attr_accessor created_at: String

      attr_accessor currency: WhopSDK::Models::BountyCreateResponse::currency

      attr_accessor denied_submissions_count: Integer

      attr_accessor description: String

      attr_accessor discussion_experience_id: String?

      attr_accessor discussion_feed_id: String?

      attr_accessor discussion_post_id: String?

      attr_accessor experience_id: String?

      attr_accessor funding_account: WhopSDK::Models::BountyCreateResponse::FundingAccount?

      attr_accessor gross_paid_out_amount: Float

      attr_accessor gross_reward_amount: Float

      attr_accessor hosting_account: WhopSDK::Models::BountyCreateResponse::HostingAccount?

      attr_accessor min_total_verified_duration_seconds: Integer?

      attr_accessor net_reward_amount: Float

      attr_accessor poster: WhopSDK::Models::BountyCreateResponse::Poster

      attr_accessor scheduled_frequency: WhopSDK::Models::BountyCreateResponse::scheduled_frequency?

      attr_accessor scheduled_publish_at: String?

      attr_accessor spots_remaining: Integer

      attr_accessor status: WhopSDK::Models::BountyCreateResponse::status

      attr_accessor submissions_closed_at: String?

      attr_accessor title: String

      attr_accessor unresolved_submissions_count: Integer

      attr_accessor updated_at: String

      attr_accessor viewer_accepted_submissions_count: Integer

      def initialize: (
        id: String,
        accepted_deliverable_types: ::Array[WhopSDK::Models::BountyCreateResponse::accepted_deliverable_type],
        accepted_submissions_count: Integer,
        accepted_submissions_limit: Integer,
        accepted_submissions_per_user_limit: Integer,
        active_proof_livestream_feeds: ::Array[WhopSDK::Models::BountyCreateResponse::ActiveProofLivestreamFeed],
        affiliate_share_amount: Float,
        allowed_country_codes: ::Array[String],
        awaiting_review_submissions_count: Integer,
        budget_amount: Float,
        business_goal_type: WhopSDK::Models::BountyCreateResponse::business_goal_type?,
        cancel_requested_at: String?,
        capture_spec: WhopSDK::Models::BountyCreateResponse::CaptureSpec?,
        created_at: String,
        currency: WhopSDK::Models::BountyCreateResponse::currency,
        denied_submissions_count: Integer,
        description: String,
        discussion_experience_id: String?,
        discussion_feed_id: String?,
        discussion_post_id: String?,
        experience_id: String?,
        funding_account: WhopSDK::Models::BountyCreateResponse::FundingAccount?,
        gross_paid_out_amount: Float,
        gross_reward_amount: Float,
        hosting_account: WhopSDK::Models::BountyCreateResponse::HostingAccount?,
        min_total_verified_duration_seconds: Integer?,
        net_reward_amount: Float,
        poster: WhopSDK::Models::BountyCreateResponse::Poster,
        scheduled_frequency: WhopSDK::Models::BountyCreateResponse::scheduled_frequency?,
        scheduled_publish_at: String?,
        spots_remaining: Integer,
        status: WhopSDK::Models::BountyCreateResponse::status,
        submissions_closed_at: String?,
        title: String,
        unresolved_submissions_count: Integer,
        updated_at: String,
        viewer_accepted_submissions_count: Integer
      ) -> void

      def to_hash: -> {
        id: String,
        accepted_deliverable_types: ::Array[WhopSDK::Models::BountyCreateResponse::accepted_deliverable_type],
        accepted_submissions_count: Integer,
        accepted_submissions_limit: Integer,
        accepted_submissions_per_user_limit: Integer,
        active_proof_livestream_feeds: ::Array[WhopSDK::Models::BountyCreateResponse::ActiveProofLivestreamFeed],
        affiliate_share_amount: Float,
        allowed_country_codes: ::Array[String],
        awaiting_review_submissions_count: Integer,
        budget_amount: Float,
        business_goal_type: WhopSDK::Models::BountyCreateResponse::business_goal_type?,
        cancel_requested_at: String?,
        capture_spec: WhopSDK::Models::BountyCreateResponse::CaptureSpec?,
        created_at: String,
        currency: WhopSDK::Models::BountyCreateResponse::currency,
        denied_submissions_count: Integer,
        description: String,
        discussion_experience_id: String?,
        discussion_feed_id: String?,
        discussion_post_id: String?,
        experience_id: String?,
        funding_account: WhopSDK::Models::BountyCreateResponse::FundingAccount?,
        gross_paid_out_amount: Float,
        gross_reward_amount: Float,
        hosting_account: WhopSDK::Models::BountyCreateResponse::HostingAccount?,
        min_total_verified_duration_seconds: Integer?,
        net_reward_amount: Float,
        poster: WhopSDK::Models::BountyCreateResponse::Poster,
        scheduled_frequency: WhopSDK::Models::BountyCreateResponse::scheduled_frequency?,
        scheduled_publish_at: String?,
        spots_remaining: Integer,
        status: WhopSDK::Models::BountyCreateResponse::status,
        submissions_closed_at: String?,
        title: String,
        unresolved_submissions_count: Integer,
        updated_at: String,
        viewer_accepted_submissions_count: Integer
      }

      type accepted_deliverable_type = :content_url | :media | :data_capture

      module AcceptedDeliverableType
        extend WhopSDK::Internal::Type::Enum

        CONTENT_URL: :content_url
        MEDIA: :media
        DATA_CAPTURE: :data_capture

        def self?.values: -> ::Array[WhopSDK::Models::BountyCreateResponse::accepted_deliverable_type]
      end

      type active_proof_livestream_feed =
        {
          id: String,
          host: WhopSDK::Models::BountyCreateResponse::ActiveProofLivestreamFeed::Host?,
          title: String
        }

      class ActiveProofLivestreamFeed < WhopSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor host: WhopSDK::Models::BountyCreateResponse::ActiveProofLivestreamFeed::Host?

        attr_accessor title: String

        def initialize: (
          id: String,
          host: WhopSDK::Models::BountyCreateResponse::ActiveProofLivestreamFeed::Host?,
          title: String
        ) -> void

        def to_hash: -> {
          id: String,
          host: WhopSDK::Models::BountyCreateResponse::ActiveProofLivestreamFeed::Host?,
          title: String
        }

        type host =
          {
            id: String,
            name: String?,
            profile_picture: WhopSDK::Models::BountyCreateResponse::ActiveProofLivestreamFeed::Host::ProfilePicture,
            username: String
          }

        class Host < WhopSDK::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor name: String?

          attr_accessor profile_picture: WhopSDK::Models::BountyCreateResponse::ActiveProofLivestreamFeed::Host::ProfilePicture

          attr_accessor username: String

          def initialize: (
            id: String,
            name: String?,
            profile_picture: WhopSDK::Models::BountyCreateResponse::ActiveProofLivestreamFeed::Host::ProfilePicture,
            username: String
          ) -> void

          def to_hash: -> {
            id: String,
            name: String?,
            profile_picture: WhopSDK::Models::BountyCreateResponse::ActiveProofLivestreamFeed::Host::ProfilePicture,
            username: String
          }

          type profile_picture = { url: String }

          class ProfilePicture < WhopSDK::Internal::Type::BaseModel
            attr_accessor url: String

            def initialize: (url: String) -> void

            def to_hash: -> { url: String }
          end
        end
      end

      type business_goal_type =
        :clipping
        | :post_engagement
        | :owned_account_growth
        | :ugc_content
        | :local_activation
        | :data_capture
        | :other

      module BusinessGoalType
        extend WhopSDK::Internal::Type::Enum

        CLIPPING: :clipping
        POST_ENGAGEMENT: :post_engagement
        OWNED_ACCOUNT_GROWTH: :owned_account_growth
        UGC_CONTENT: :ugc_content
        LOCAL_ACTIVATION: :local_activation
        DATA_CAPTURE: :data_capture
        OTHER: :other

        def self?.values: -> ::Array[WhopSDK::Models::BountyCreateResponse::business_goal_type]
      end

      type capture_spec =
        {
          filename_pattern: String,
          imu: WhopSDK::Models::BountyCreateResponse::CaptureSpec::Imu,
          manifest_schema_version: Integer,
          min_clip_duration_seconds: Integer,
          min_total_verified_duration_seconds: Integer,
          required_metadata_fields: ::Array[String],
          single_continuous_take: bool,
          video: WhopSDK::Models::BountyCreateResponse::CaptureSpec::Video
        }

      class CaptureSpec < WhopSDK::Internal::Type::BaseModel
        attr_accessor filename_pattern: String

        attr_accessor imu: WhopSDK::Models::BountyCreateResponse::CaptureSpec::Imu

        attr_accessor manifest_schema_version: Integer

        attr_accessor min_clip_duration_seconds: Integer

        attr_accessor min_total_verified_duration_seconds: Integer

        attr_accessor required_metadata_fields: ::Array[String]

        attr_accessor single_continuous_take: bool

        attr_accessor video: WhopSDK::Models::BountyCreateResponse::CaptureSpec::Video

        def initialize: (
          filename_pattern: String,
          imu: WhopSDK::Models::BountyCreateResponse::CaptureSpec::Imu,
          manifest_schema_version: Integer,
          min_clip_duration_seconds: Integer,
          min_total_verified_duration_seconds: Integer,
          required_metadata_fields: ::Array[String],
          single_continuous_take: bool,
          video: WhopSDK::Models::BountyCreateResponse::CaptureSpec::Video
        ) -> void

        def to_hash: -> {
          filename_pattern: String,
          imu: WhopSDK::Models::BountyCreateResponse::CaptureSpec::Imu,
          manifest_schema_version: Integer,
          min_clip_duration_seconds: Integer,
          min_total_verified_duration_seconds: Integer,
          required_metadata_fields: ::Array[String],
          single_continuous_take: bool,
          video: WhopSDK::Models::BountyCreateResponse::CaptureSpec::Video
        }

        type imu =
          {
            device_motion_units: String,
            magnetometer_units: String,
            min_rate_hz: Float,
            target_rate_hz: Integer,
            warmup_min_rate_hz: Float,
            warmup_ns: Integer
          }

        class Imu < WhopSDK::Internal::Type::BaseModel
          attr_accessor device_motion_units: String

          attr_accessor magnetometer_units: String

          attr_accessor min_rate_hz: Float

          attr_accessor target_rate_hz: Integer

          attr_accessor warmup_min_rate_hz: Float

          attr_accessor warmup_ns: Integer

          def initialize: (
            device_motion_units: String,
            magnetometer_units: String,
            min_rate_hz: Float,
            target_rate_hz: Integer,
            warmup_min_rate_hz: Float,
            warmup_ns: Integer
          ) -> void

          def to_hash: -> {
            device_motion_units: String,
            magnetometer_units: String,
            min_rate_hz: Float,
            target_rate_hz: Integer,
            warmup_min_rate_hz: Float,
            warmup_ns: Integer
          }
        end

        type video =
          {
            bitrate_ceiling_mbps: Integer,
            bitrate_floor_mbps: Integer,
            bitrate_target_mbps: Integer,
            camera_lens: String,
            codecs: ::Array[String],
            embed_camera_metadata: bool,
            fps: Integer,
            frame_gap_tolerance_ms: Integer,
            height: Integer,
            min_fov_degrees: Integer,
            orientation: String,
            preferred_fov_degrees: Integer,
            stabilization_mode: WhopSDK::Models::BountyCreateResponse::CaptureSpec::Video::stabilization_mode,
            stabilization_required: bool,
            width: Integer
          }

        class Video < WhopSDK::Internal::Type::BaseModel
          attr_accessor bitrate_ceiling_mbps: Integer

          attr_accessor bitrate_floor_mbps: Integer

          attr_accessor bitrate_target_mbps: Integer

          attr_accessor camera_lens: String

          attr_accessor codecs: ::Array[String]

          attr_accessor embed_camera_metadata: bool

          attr_accessor fps: Integer

          attr_accessor frame_gap_tolerance_ms: Integer

          attr_accessor height: Integer

          attr_accessor min_fov_degrees: Integer

          attr_accessor orientation: String

          attr_accessor preferred_fov_degrees: Integer

          attr_accessor stabilization_mode: WhopSDK::Models::BountyCreateResponse::CaptureSpec::Video::stabilization_mode

          attr_accessor stabilization_required: bool

          attr_accessor width: Integer

          def initialize: (
            bitrate_ceiling_mbps: Integer,
            bitrate_floor_mbps: Integer,
            bitrate_target_mbps: Integer,
            camera_lens: String,
            codecs: ::Array[String],
            embed_camera_metadata: bool,
            fps: Integer,
            frame_gap_tolerance_ms: Integer,
            height: Integer,
            min_fov_degrees: Integer,
            orientation: String,
            preferred_fov_degrees: Integer,
            stabilization_mode: WhopSDK::Models::BountyCreateResponse::CaptureSpec::Video::stabilization_mode,
            stabilization_required: bool,
            width: Integer
          ) -> void

          def to_hash: -> {
            bitrate_ceiling_mbps: Integer,
            bitrate_floor_mbps: Integer,
            bitrate_target_mbps: Integer,
            camera_lens: String,
            codecs: ::Array[String],
            embed_camera_metadata: bool,
            fps: Integer,
            frame_gap_tolerance_ms: Integer,
            height: Integer,
            min_fov_degrees: Integer,
            orientation: String,
            preferred_fov_degrees: Integer,
            stabilization_mode: WhopSDK::Models::BountyCreateResponse::CaptureSpec::Video::stabilization_mode,
            stabilization_required: bool,
            width: Integer
          }

          type stabilization_mode = :off | :on | :any

          module StabilizationMode
            extend WhopSDK::Internal::Type::Enum

            OFF: :off
            ON: :on
            ANY: :any

            def self?.values: -> ::Array[WhopSDK::Models::BountyCreateResponse::CaptureSpec::Video::stabilization_mode]
          end
        end
      end

      type currency =
        :usd
        | :sgd
        | :inr
        | :aud
        | :brl
        | :cad
        | :dkk
        | :eur
        | :nok
        | :gbp
        | :sek
        | :chf
        | :hkd
        | :huf
        | :jpy
        | :mxn
        | :myr
        | :pln
        | :czk
        | :nzd
        | :aed
        | :cop
        | :ron
        | :thb
        | :bgn
        | :idr
        | :dop
        | :php
        | :try
        | :krw
        | :twd
        | :vnd
        | :pkr
        | :clp
        | :uyu
        | :ars
        | :zar
        | :dzd
        | :tnd
        | :mad
        | :kes
        | :kwd
        | :jod
        | :all
        | :xcd
        | :amd
        | :bsd
        | :bhd
        | :bob
        | :bam
        | :khr
        | :crc
        | :xof
        | :egp
        | :etb
        | :gmd
        | :ghs
        | :gtq
        | :gyd
        | :ils
        | :jmd
        | :mop
        | :mga
        | :mur
        | :mdl
        | :mnt
        | :nad
        | :ngn
        | :mkd
        | :omr
        | :pyg
        | :pen
        | :qar
        | :rwf
        | :sar
        | :rsd
        | :lkr
        | :tzs
        | :ttd
        | :uzs
        | :rub
        | :cny
        | :kzt
        | :awg

      module Currency
        extend WhopSDK::Internal::Type::Enum

        USD: :usd
        SGD: :sgd
        INR: :inr
        AUD: :aud
        BRL: :brl
        CAD: :cad
        DKK: :dkk
        EUR: :eur
        NOK: :nok
        GBP: :gbp
        SEK: :sek
        CHF: :chf
        HKD: :hkd
        HUF: :huf
        JPY: :jpy
        MXN: :mxn
        MYR: :myr
        PLN: :pln
        CZK: :czk
        NZD: :nzd
        AED: :aed
        COP: :cop
        RON: :ron
        THB: :thb
        BGN: :bgn
        IDR: :idr
        DOP: :dop
        PHP: :php
        TRY: :try
        KRW: :krw
        TWD: :twd
        VND: :vnd
        PKR: :pkr
        CLP: :clp
        UYU: :uyu
        ARS: :ars
        ZAR: :zar
        DZD: :dzd
        TND: :tnd
        MAD: :mad
        KES: :kes
        KWD: :kwd
        JOD: :jod
        ALL: :all
        XCD: :xcd
        AMD: :amd
        BSD: :bsd
        BHD: :bhd
        BOB: :bob
        BAM: :bam
        KHR: :khr
        CRC: :crc
        XOF: :xof
        EGP: :egp
        ETB: :etb
        GMD: :gmd
        GHS: :ghs
        GTQ: :gtq
        GYD: :gyd
        ILS: :ils
        JMD: :jmd
        MOP: :mop
        MGA: :mga
        MUR: :mur
        MDL: :mdl
        MNT: :mnt
        NAD: :nad
        NGN: :ngn
        MKD: :mkd
        OMR: :omr
        PYG: :pyg
        PEN: :pen
        QAR: :qar
        RWF: :rwf
        SAR: :sar
        RSD: :rsd
        LKR: :lkr
        TZS: :tzs
        TTD: :ttd
        UZS: :uzs
        RUB: :rub
        CNY: :cny
        KZT: :kzt
        AWG: :awg

        def self?.values: -> ::Array[WhopSDK::Models::BountyCreateResponse::currency]
      end

      type funding_account = { id: String, title: String }

      class FundingAccount < WhopSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor title: String

        def initialize: (id: String, title: String) -> void

        def to_hash: -> { id: String, title: String }
      end

      type hosting_account =
        { id: String, logo_url: String?, route: String, title: String }

      class HostingAccount < WhopSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor logo_url: String?

        attr_accessor route: String

        attr_accessor title: String

        def initialize: (
          id: String,
          logo_url: String?,
          route: String,
          title: String
        ) -> void

        def to_hash: -> {
          id: String,
          logo_url: String?,
          route: String,
          title: String
        }
      end

      type poster =
        {
          id: String,
          name: String?,
          profile_picture: WhopSDK::Models::BountyCreateResponse::Poster::ProfilePicture,
          username: String
        }

      class Poster < WhopSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor name: String?

        attr_accessor profile_picture: WhopSDK::Models::BountyCreateResponse::Poster::ProfilePicture

        attr_accessor username: String

        def initialize: (
          id: String,
          name: String?,
          profile_picture: WhopSDK::Models::BountyCreateResponse::Poster::ProfilePicture,
          username: String
        ) -> void

        def to_hash: -> {
          id: String,
          name: String?,
          profile_picture: WhopSDK::Models::BountyCreateResponse::Poster::ProfilePicture,
          username: String
        }

        type profile_picture = { url: String }

        class ProfilePicture < WhopSDK::Internal::Type::BaseModel
          attr_accessor url: String

          def initialize: (url: String) -> void

          def to_hash: -> { url: String }
        end
      end

      type scheduled_frequency = :once | :hourly | :daily | :weekly | :monthly

      module ScheduledFrequency
        extend WhopSDK::Internal::Type::Enum

        ONCE: :once
        HOURLY: :hourly
        DAILY: :daily
        WEEKLY: :weekly
        MONTHLY: :monthly

        def self?.values: -> ::Array[WhopSDK::Models::BountyCreateResponse::scheduled_frequency]
      end

      type status = :scheduled | :open | :closed | :completed | :canceled

      module Status
        extend WhopSDK::Internal::Type::Enum

        SCHEDULED: :scheduled
        OPEN: :open
        CLOSED: :closed
        COMPLETED: :completed
        CANCELED: :canceled

        def self?.values: -> ::Array[WhopSDK::Models::BountyCreateResponse::status]
      end
    end
  end
end
