module WhopSDK
  module Models
    type bounty_create_params =
      {
        base_unit_amount: Float,
        currency: WhopSDK::Models::currency,
        description: String,
        title: String,
        accepted_submissions_limit: Integer?,
        allowed_country_codes: ::Array[String]?,
        business_goal_type: WhopSDK::Models::BountyCreateParams::business_goal_type?,
        experience_id: String?,
        origin_account_id: String?,
        post_markdown_content: String?,
        post_title: String?
      }
      & WhopSDK::Internal::Type::request_parameters

    class BountyCreateParams < WhopSDK::Internal::Type::BaseModel
      extend WhopSDK::Internal::Type::RequestParameters::Converter
      include WhopSDK::Internal::Type::RequestParameters

      attr_accessor base_unit_amount: Float

      attr_accessor currency: WhopSDK::Models::currency

      attr_accessor description: String

      attr_accessor title: String

      attr_accessor accepted_submissions_limit: Integer?

      attr_accessor allowed_country_codes: ::Array[String]?

      attr_accessor business_goal_type: WhopSDK::Models::BountyCreateParams::business_goal_type?

      attr_accessor experience_id: String?

      attr_accessor origin_account_id: String?

      attr_accessor post_markdown_content: String?

      attr_accessor post_title: String?

      def initialize: (
        base_unit_amount: Float,
        currency: WhopSDK::Models::currency,
        description: String,
        title: String,
        ?accepted_submissions_limit: Integer?,
        ?allowed_country_codes: ::Array[String]?,
        ?business_goal_type: WhopSDK::Models::BountyCreateParams::business_goal_type?,
        ?experience_id: String?,
        ?origin_account_id: String?,
        ?post_markdown_content: String?,
        ?post_title: String?,
        ?request_options: WhopSDK::request_opts
      ) -> void

      def to_hash: -> {
        base_unit_amount: Float,
        currency: WhopSDK::Models::currency,
        description: String,
        title: String,
        accepted_submissions_limit: Integer?,
        allowed_country_codes: ::Array[String]?,
        business_goal_type: WhopSDK::Models::BountyCreateParams::business_goal_type?,
        experience_id: String?,
        origin_account_id: String?,
        post_markdown_content: String?,
        post_title: String?,
        request_options: WhopSDK::RequestOptions
      }

      type business_goal_type =
        :clipping
        | :post_engagement
        | :owned_account_growth
        | :ugc_content
        | :local_activation
        | :other

      module BusinessGoalType
        extend WhopSDK::Internal::Type::Enum

        CLIPPING: :clipping
        POST_ENGAGEMENT: :post_engagement
        OWNED_ACCOUNT_GROWTH: :owned_account_growth
        UGC_CONTENT: :ugc_content
        LOCAL_ACTIVATION: :local_activation
        OTHER: :other

        def self?.values: -> ::Array[WhopSDK::Models::BountyCreateParams::business_goal_type]
      end
    end
  end
end
