module WhopSDK
  module Models
    type card_list_params =
      { account_id: String } & WhopSDK::Internal::Type::request_parameters

    class CardListParams < WhopSDK::Internal::Type::BaseModel
      extend WhopSDK::Internal::Type::RequestParameters::Converter
      include WhopSDK::Internal::Type::RequestParameters

      attr_accessor account_id: String

      def initialize: (
        account_id: String,
        ?request_options: WhopSDK::request_opts
      ) -> void

      def to_hash: -> {
        account_id: String,
        request_options: WhopSDK::RequestOptions
      }
    end
  end
end
