module WhopSDK
  module Models
    type card_create_params =
      {
        account_id: String,
        assigned_user_id: String,
        name: String,
        spend_limit: Float,
        spend_limit_frequency: WhopSDK::Models::CardCreateParams::spend_limit_frequency,
        transaction_limit: Float,
        user_id: String
      }
      & WhopSDK::Internal::Type::request_parameters

    class CardCreateParams < WhopSDK::Internal::Type::BaseModel
      extend WhopSDK::Internal::Type::RequestParameters::Converter
      include WhopSDK::Internal::Type::RequestParameters

      attr_reader account_id: String?

      def account_id=: (String) -> String

      attr_reader assigned_user_id: String?

      def assigned_user_id=: (String) -> String

      attr_reader name: String?

      def name=: (String) -> String

      attr_reader spend_limit: Float?

      def spend_limit=: (Float) -> Float

      attr_reader spend_limit_frequency: WhopSDK::Models::CardCreateParams::spend_limit_frequency?

      def spend_limit_frequency=: (
        WhopSDK::Models::CardCreateParams::spend_limit_frequency
      ) -> WhopSDK::Models::CardCreateParams::spend_limit_frequency

      attr_reader transaction_limit: Float?

      def transaction_limit=: (Float) -> Float

      attr_reader user_id: String?

      def user_id=: (String) -> String

      def initialize: (
        ?account_id: String,
        ?assigned_user_id: String,
        ?name: String,
        ?spend_limit: Float,
        ?spend_limit_frequency: WhopSDK::Models::CardCreateParams::spend_limit_frequency,
        ?transaction_limit: Float,
        ?user_id: String,
        ?request_options: WhopSDK::request_opts
      ) -> void

      def to_hash: -> {
        account_id: String,
        assigned_user_id: String,
        name: String,
        spend_limit: Float,
        spend_limit_frequency: WhopSDK::Models::CardCreateParams::spend_limit_frequency,
        transaction_limit: Float,
        user_id: String,
        request_options: WhopSDK::RequestOptions
      }

      type spend_limit_frequency = :daily | :weekly | :monthly | :one_time

      module SpendLimitFrequency
        extend WhopSDK::Internal::Type::Enum

        DAILY: :daily
        WEEKLY: :weekly
        MONTHLY: :monthly
        ONE_TIME: :one_time

        def self?.values: -> ::Array[WhopSDK::Models::CardCreateParams::spend_limit_frequency]
      end
    end
  end
end
