module WhopSDK
  module Models
    type card_brands =
      :mastercard
      | :visa
      | :amex
      | :discover
      | :unionpay
      | :jcb
      | :diners
      | :link
      | :troy
      | :visadankort
      | :visabancontact
      | :china_union_pay
      | :rupay
      | :jcbrupay
      | :elo
      | :maestro
      | :tarjeta_naranja
      | :cirrus
      | :nspk_mir
      | :verve
      | :ebt
      | :private_label
      | :local_brand
      | :uatp
      | :wexcard
      | :uzcard
      | :meeza
      | :hrg_store_card
      | :girocard
      | :fuel_card
      | :dankort
      | :carnet
      | :atm_card
      | :china_union_payuzcard
      | :codensa
      | :cabal
      | :hipercard
      | :unknown

    module CardBrands
      extend WhopSDK::Internal::Type::Enum

      MASTERCARD: :mastercard
      VISA: :visa
      AMEX: :amex
      DISCOVER: :discover
      UNIONPAY: :unionpay
      JCB: :jcb
      DINERS: :diners
      LINK: :link
      TROY: :troy
      VISADANKORT: :visadankort
      VISABANCONTACT: :visabancontact
      CHINA_UNION_PAY: :china_union_pay
      RUPAY: :rupay
      JCBRUPAY: :jcbrupay
      ELO: :elo
      MAESTRO: :maestro
      TARJETA_NARANJA: :tarjeta_naranja
      CIRRUS: :cirrus
      NSPK_MIR: :nspk_mir
      VERVE: :verve
      EBT: :ebt
      PRIVATE_LABEL: :private_label
      LOCAL_BRAND: :local_brand
      UATP: :uatp
      WEXCARD: :wexcard
      UZCARD: :uzcard
      MEEZA: :meeza
      HRG_STORE_CARD: :hrg_store_card
      GIROCARD: :girocard
      FUEL_CARD: :fuel_card
      DANKORT: :dankort
      CARNET: :carnet
      ATM_CARD: :atm_card
      CHINA_UNION_PAYUZCARD: :china_union_payuzcard
      CODENSA: :codensa
      CABAL: :cabal
      HIPERCARD: :hipercard
      UNKNOWN: :unknown

      def self?.values: -> ::Array[WhopSDK::Models::card_brands]
    end
  end
end
