module WhopSDK
  module Models
    type card_secrets =
      {
        cvc: String,
        object: WhopSDK::Models::CardSecrets::object,
        pan: String,
        name_on_card: String?
      }

    class CardSecrets < WhopSDK::Internal::Type::BaseModel
      attr_accessor cvc: String

      attr_accessor object: WhopSDK::Models::CardSecrets::object

      attr_accessor pan: String

      attr_accessor name_on_card: String?

      def initialize: (
        cvc: String,
        object: WhopSDK::Models::CardSecrets::object,
        pan: String,
        ?name_on_card: String?
      ) -> void

      def to_hash: -> {
        cvc: String,
        object: WhopSDK::Models::CardSecrets::object,
        pan: String,
        name_on_card: String?
      }

      type object = :card_secrets

      module Object
        extend WhopSDK::Internal::Type::Enum

        CARD_SECRETS: :card_secrets

        def self?.values: -> ::Array[WhopSDK::Models::CardSecrets::object]
      end
    end
  end
end
