module WhopSDK
  module Models
    type checkout_configuration_list_params =
      {
        account_id: String,
        after: String,
        created_after: String,
        created_before: String,
        direction: WhopSDK::Models::CheckoutConfigurationListParams::direction,
        first: Integer,
        order: WhopSDK::Models::CheckoutConfigurationListParams::order,
        plan_id: String,
        api_version_date: String
      }
      & WhopSDK::Internal::Type::request_parameters

    class CheckoutConfigurationListParams < WhopSDK::Internal::Type::BaseModel
      extend WhopSDK::Internal::Type::RequestParameters::Converter
      include WhopSDK::Internal::Type::RequestParameters

      attr_accessor account_id: String

      attr_reader after: String?

      def after=: (String) -> String

      attr_reader created_after: String?

      def created_after=: (String) -> String

      attr_reader created_before: String?

      def created_before=: (String) -> String

      attr_reader direction: WhopSDK::Models::CheckoutConfigurationListParams::direction?

      def direction=: (
        WhopSDK::Models::CheckoutConfigurationListParams::direction
      ) -> WhopSDK::Models::CheckoutConfigurationListParams::direction

      attr_reader first: Integer?

      def first=: (Integer) -> Integer

      attr_reader order: WhopSDK::Models::CheckoutConfigurationListParams::order?

      def order=: (
        WhopSDK::Models::CheckoutConfigurationListParams::order
      ) -> WhopSDK::Models::CheckoutConfigurationListParams::order

      attr_reader plan_id: String?

      def plan_id=: (String) -> String

      attr_reader api_version_date: String?

      def api_version_date=: (String) -> String

      def initialize: (
        account_id: String,
        ?after: String,
        ?created_after: String,
        ?created_before: String,
        ?direction: WhopSDK::Models::CheckoutConfigurationListParams::direction,
        ?first: Integer,
        ?order: WhopSDK::Models::CheckoutConfigurationListParams::order,
        ?plan_id: String,
        ?api_version_date: String,
        ?request_options: WhopSDK::request_opts
      ) -> void

      def to_hash: -> {
        account_id: String,
        after: String,
        created_after: String,
        created_before: String,
        direction: WhopSDK::Models::CheckoutConfigurationListParams::direction,
        first: Integer,
        order: WhopSDK::Models::CheckoutConfigurationListParams::order,
        plan_id: String,
        api_version_date: String,
        request_options: WhopSDK::RequestOptions
      }

      type direction = :asc | :desc

      module Direction
        extend WhopSDK::Internal::Type::Enum

        ASC: :asc
        DESC: :desc

        def self?.values: -> ::Array[WhopSDK::Models::CheckoutConfigurationListParams::direction]
      end

      type order = :created_at

      module Order
        extend WhopSDK::Internal::Type::Enum

        CREATED_AT: :created_at

        def self?.values: -> ::Array[WhopSDK::Models::CheckoutConfigurationListParams::order]
      end
    end
  end
end
