module WhopSDK
  module Models
    type checkout_configuration_create_params =
      {
        affiliate_code: String?,
        company_id: String,
        currency: String?,
        metadata: top?,
        mode: WhopSDK::Models::CheckoutConfigurationCreateParams::mode,
        payment_method_configuration: WhopSDK::CheckoutConfigurationCreateParams::PaymentMethodConfiguration?,
        plan: WhopSDK::CheckoutConfigurationCreateParams::Plan?,
        plan_id: String?,
        redirect_url: String?,
        three_ds_level: String?
      }
      & WhopSDK::Internal::Type::request_parameters

    class CheckoutConfigurationCreateParams < WhopSDK::Internal::Type::BaseModel
      extend WhopSDK::Internal::Type::RequestParameters::Converter
      include WhopSDK::Internal::Type::RequestParameters

      attr_accessor affiliate_code: String?

      attr_reader company_id: String?

      def company_id=: (String) -> String

      attr_accessor currency: String?

      attr_accessor metadata: top?

      attr_reader mode: WhopSDK::Models::CheckoutConfigurationCreateParams::mode?

      def mode=: (
        WhopSDK::Models::CheckoutConfigurationCreateParams::mode
      ) -> WhopSDK::Models::CheckoutConfigurationCreateParams::mode

      attr_accessor payment_method_configuration: WhopSDK::CheckoutConfigurationCreateParams::PaymentMethodConfiguration?

      attr_accessor plan: WhopSDK::CheckoutConfigurationCreateParams::Plan?

      attr_accessor plan_id: String?

      attr_accessor redirect_url: String?

      attr_accessor three_ds_level: String?

      def initialize: (
        ?affiliate_code: String?,
        ?company_id: String,
        ?currency: String?,
        ?metadata: top?,
        ?mode: WhopSDK::Models::CheckoutConfigurationCreateParams::mode,
        ?payment_method_configuration: WhopSDK::CheckoutConfigurationCreateParams::PaymentMethodConfiguration?,
        ?plan: WhopSDK::CheckoutConfigurationCreateParams::Plan?,
        ?plan_id: String?,
        ?redirect_url: String?,
        ?three_ds_level: String?,
        ?request_options: WhopSDK::request_opts
      ) -> void

      def to_hash: -> {
        affiliate_code: String?,
        company_id: String,
        currency: String?,
        metadata: top?,
        mode: WhopSDK::Models::CheckoutConfigurationCreateParams::mode,
        payment_method_configuration: WhopSDK::CheckoutConfigurationCreateParams::PaymentMethodConfiguration?,
        plan: WhopSDK::CheckoutConfigurationCreateParams::Plan?,
        plan_id: String?,
        redirect_url: String?,
        three_ds_level: String?,
        request_options: WhopSDK::RequestOptions
      }

      type mode = :payment | :setup

      module Mode
        extend WhopSDK::Internal::Type::Enum

        PAYMENT: :payment
        SETUP: :setup

        def self?.values: -> ::Array[WhopSDK::Models::CheckoutConfigurationCreateParams::mode]
      end

      type payment_method_configuration =
        {
          disabled: ::Array[String],
          enabled: ::Array[String],
          include_platform_defaults: bool
        }

      class PaymentMethodConfiguration < WhopSDK::Internal::Type::BaseModel
        attr_reader disabled: ::Array[String]?

        def disabled=: (::Array[String]) -> ::Array[String]

        attr_reader enabled: ::Array[String]?

        def enabled=: (::Array[String]) -> ::Array[String]

        attr_reader include_platform_defaults: bool?

        def include_platform_defaults=: (bool) -> bool

        def initialize: (
          ?disabled: ::Array[String],
          ?enabled: ::Array[String],
          ?include_platform_defaults: bool
        ) -> void

        def to_hash: -> {
          disabled: ::Array[String],
          enabled: ::Array[String],
          include_platform_defaults: bool
        }
      end

      type plan =
        {
          billing_period: Integer?,
          company_id: String?,
          currency: String?,
          description: String?,
          expiration_days: Integer?,
          force_create_new_plan: bool?,
          initial_price: Float?,
          metadata: top?,
          override_tax_type: String?,
          payment_method_configuration: WhopSDK::CheckoutConfigurationCreateParams::Plan::PaymentMethodConfiguration?,
          plan_type: String?,
          product_id: String?,
          release_method: String?,
          renewal_price: Float?,
          stock: Integer?,
          title: String?,
          trial_period_days: Integer?,
          unlimited_stock: bool?,
          visibility: String?
        }

      class Plan < WhopSDK::Internal::Type::BaseModel
        attr_accessor billing_period: Integer?

        attr_accessor company_id: String?

        attr_accessor currency: String?

        attr_accessor description: String?

        attr_accessor expiration_days: Integer?

        attr_accessor force_create_new_plan: bool?

        attr_accessor initial_price: Float?

        attr_accessor metadata: top?

        attr_accessor override_tax_type: String?

        attr_accessor payment_method_configuration: WhopSDK::CheckoutConfigurationCreateParams::Plan::PaymentMethodConfiguration?

        attr_accessor plan_type: String?

        attr_accessor product_id: String?

        attr_accessor release_method: String?

        attr_accessor renewal_price: Float?

        attr_accessor stock: Integer?

        attr_accessor title: String?

        attr_accessor trial_period_days: Integer?

        attr_accessor unlimited_stock: bool?

        attr_accessor visibility: String?

        def initialize: (
          ?billing_period: Integer?,
          ?company_id: String?,
          ?currency: String?,
          ?description: String?,
          ?expiration_days: Integer?,
          ?force_create_new_plan: bool?,
          ?initial_price: Float?,
          ?metadata: top?,
          ?override_tax_type: String?,
          ?payment_method_configuration: WhopSDK::CheckoutConfigurationCreateParams::Plan::PaymentMethodConfiguration?,
          ?plan_type: String?,
          ?product_id: String?,
          ?release_method: String?,
          ?renewal_price: Float?,
          ?stock: Integer?,
          ?title: String?,
          ?trial_period_days: Integer?,
          ?unlimited_stock: bool?,
          ?visibility: String?
        ) -> void

        def to_hash: -> {
          billing_period: Integer?,
          company_id: String?,
          currency: String?,
          description: String?,
          expiration_days: Integer?,
          force_create_new_plan: bool?,
          initial_price: Float?,
          metadata: top?,
          override_tax_type: String?,
          payment_method_configuration: WhopSDK::CheckoutConfigurationCreateParams::Plan::PaymentMethodConfiguration?,
          plan_type: String?,
          product_id: String?,
          release_method: String?,
          renewal_price: Float?,
          stock: Integer?,
          title: String?,
          trial_period_days: Integer?,
          unlimited_stock: bool?,
          visibility: String?
        }

        type payment_method_configuration =
          {
            disabled: ::Array[String],
            enabled: ::Array[String],
            include_platform_defaults: bool
          }

        class PaymentMethodConfiguration < WhopSDK::Internal::Type::BaseModel
          attr_reader disabled: ::Array[String]?

          def disabled=: (::Array[String]) -> ::Array[String]

          attr_reader enabled: ::Array[String]?

          def enabled=: (::Array[String]) -> ::Array[String]

          attr_reader include_platform_defaults: bool?

          def include_platform_defaults=: (bool) -> bool

          def initialize: (
            ?disabled: ::Array[String],
            ?enabled: ::Array[String],
            ?include_platform_defaults: bool
          ) -> void

          def to_hash: -> {
            disabled: ::Array[String],
            enabled: ::Array[String],
            include_platform_defaults: bool
          }
        end
      end
    end
  end
end
