module WhopSDK
  module Models
    type checkout_configuration_create_params =
      {
        plan: WhopSDK::CheckoutConfigurationCreateParams::Plan,
        affiliate_code: String?,
        metadata: ::Hash[Symbol, top]?,
        redirect_url: String?,
        plan_id: String
      }
      & WhopSDK::Internal::Type::request_parameters

    class CheckoutConfigurationCreateParams < WhopSDK::Internal::Type::BaseModel
      extend WhopSDK::Internal::Type::RequestParameters::Converter
      include WhopSDK::Internal::Type::RequestParameters

      attr_accessor plan: WhopSDK::CheckoutConfigurationCreateParams::Plan

      attr_accessor affiliate_code: String?

      attr_accessor metadata: ::Hash[Symbol, top]?

      attr_accessor redirect_url: String?

      attr_accessor plan_id: String

      def initialize: (
        plan: WhopSDK::CheckoutConfigurationCreateParams::Plan,
        plan_id: String,
        ?affiliate_code: String?,
        ?metadata: ::Hash[Symbol, top]?,
        ?redirect_url: String?,
        ?request_options: WhopSDK::request_opts
      ) -> void

      def to_hash: -> {
        plan: WhopSDK::CheckoutConfigurationCreateParams::Plan,
        affiliate_code: String?,
        metadata: ::Hash[Symbol, top]?,
        redirect_url: String?,
        plan_id: String,
        request_options: WhopSDK::RequestOptions
      }

      type plan =
        {
          company_id: String,
          billing_period: Integer?,
          currency: WhopSDK::Models::currency?,
          custom_fields: ::Array[WhopSDK::CheckoutConfigurationCreateParams::Plan::CustomField]?,
          description: String?,
          expiration_days: Integer?,
          force_create_new_plan: bool?,
          image: WhopSDK::Models::CheckoutConfigurationCreateParams::Plan::image?,
          initial_price: Float?,
          internal_notes: String?,
          override_tax_type: WhopSDK::Models::tax_type?,
          payment_method_configuration: WhopSDK::CheckoutConfigurationCreateParams::Plan::PaymentMethodConfiguration?,
          plan_type: WhopSDK::Models::plan_type?,
          product: WhopSDK::CheckoutConfigurationCreateParams::Plan::Product?,
          product_id: String?,
          release_method: WhopSDK::Models::release_method?,
          renewal_price: Float?,
          title: String?,
          trial_period_days: Integer?,
          visibility: WhopSDK::Models::visibility?
        }

      class Plan < WhopSDK::Internal::Type::BaseModel
        attr_accessor company_id: String

        attr_accessor billing_period: Integer?

        attr_accessor currency: WhopSDK::Models::currency?

        attr_accessor custom_fields: ::Array[WhopSDK::CheckoutConfigurationCreateParams::Plan::CustomField]?

        attr_accessor description: String?

        attr_accessor expiration_days: Integer?

        attr_accessor force_create_new_plan: bool?

        attr_accessor image: WhopSDK::Models::CheckoutConfigurationCreateParams::Plan::image?

        attr_accessor initial_price: Float?

        attr_accessor internal_notes: String?

        attr_accessor override_tax_type: WhopSDK::Models::tax_type?

        attr_accessor payment_method_configuration: WhopSDK::CheckoutConfigurationCreateParams::Plan::PaymentMethodConfiguration?

        attr_accessor plan_type: WhopSDK::Models::plan_type?

        attr_accessor product: WhopSDK::CheckoutConfigurationCreateParams::Plan::Product?

        attr_accessor product_id: String?

        attr_accessor release_method: WhopSDK::Models::release_method?

        attr_accessor renewal_price: Float?

        attr_accessor title: String?

        attr_accessor trial_period_days: Integer?

        attr_accessor visibility: WhopSDK::Models::visibility?

        def initialize: (
          company_id: String,
          ?billing_period: Integer?,
          ?currency: WhopSDK::Models::currency?,
          ?custom_fields: ::Array[WhopSDK::CheckoutConfigurationCreateParams::Plan::CustomField]?,
          ?description: String?,
          ?expiration_days: Integer?,
          ?force_create_new_plan: bool?,
          ?image: WhopSDK::Models::CheckoutConfigurationCreateParams::Plan::image?,
          ?initial_price: Float?,
          ?internal_notes: String?,
          ?override_tax_type: WhopSDK::Models::tax_type?,
          ?payment_method_configuration: WhopSDK::CheckoutConfigurationCreateParams::Plan::PaymentMethodConfiguration?,
          ?plan_type: WhopSDK::Models::plan_type?,
          ?product: WhopSDK::CheckoutConfigurationCreateParams::Plan::Product?,
          ?product_id: String?,
          ?release_method: WhopSDK::Models::release_method?,
          ?renewal_price: Float?,
          ?title: String?,
          ?trial_period_days: Integer?,
          ?visibility: WhopSDK::Models::visibility?
        ) -> void

        def to_hash: -> {
          company_id: String,
          billing_period: Integer?,
          currency: WhopSDK::Models::currency?,
          custom_fields: ::Array[WhopSDK::CheckoutConfigurationCreateParams::Plan::CustomField]?,
          description: String?,
          expiration_days: Integer?,
          force_create_new_plan: bool?,
          image: WhopSDK::Models::CheckoutConfigurationCreateParams::Plan::image?,
          initial_price: Float?,
          internal_notes: String?,
          override_tax_type: WhopSDK::Models::tax_type?,
          payment_method_configuration: WhopSDK::CheckoutConfigurationCreateParams::Plan::PaymentMethodConfiguration?,
          plan_type: WhopSDK::Models::plan_type?,
          product: WhopSDK::CheckoutConfigurationCreateParams::Plan::Product?,
          product_id: String?,
          release_method: WhopSDK::Models::release_method?,
          renewal_price: Float?,
          title: String?,
          trial_period_days: Integer?,
          visibility: WhopSDK::Models::visibility?
        }

        type custom_field =
          {
            field_type: :text,
            name: String,
            id: String?,
            order: Integer?,
            placeholder: String?,
            required: bool?
          }

        class CustomField < WhopSDK::Internal::Type::BaseModel
          attr_accessor field_type: :text

          attr_accessor name: String

          attr_accessor id: String?

          attr_accessor order: Integer?

          attr_accessor placeholder: String?

          attr_accessor required: bool?

          def initialize: (
            name: String,
            ?id: String?,
            ?order: Integer?,
            ?placeholder: String?,
            ?required: bool?,
            ?field_type: :text
          ) -> void

          def to_hash: -> {
            field_type: :text,
            name: String,
            id: String?,
            order: Integer?,
            placeholder: String?,
            required: bool?
          }
        end

        type image =
          WhopSDK::CheckoutConfigurationCreateParams::Plan::Image::DirectUploadID
          | WhopSDK::CheckoutConfigurationCreateParams::Plan::Image::ID

        module Image
          extend WhopSDK::Internal::Type::Union

          type direct_upload_id = { direct_upload_id: String }

          class DirectUploadID < WhopSDK::Internal::Type::BaseModel
            attr_accessor direct_upload_id: String

            def initialize: (direct_upload_id: String) -> void

            def to_hash: -> { direct_upload_id: String }
          end

          type id = { id: String }

          class ID < WhopSDK::Internal::Type::BaseModel
            attr_accessor id: String

            def initialize: (id: String) -> void

            def to_hash: -> { id: String }
          end

          def self?.variants: -> ::Array[WhopSDK::Models::CheckoutConfigurationCreateParams::Plan::image]
        end

        type payment_method_configuration =
          {
            disabled: ::Array[WhopSDK::Models::payment_method_types],
            enabled: ::Array[WhopSDK::Models::payment_method_types],
            include_platform_defaults: bool
          }

        class PaymentMethodConfiguration < WhopSDK::Internal::Type::BaseModel
          attr_accessor disabled: ::Array[WhopSDK::Models::payment_method_types]

          attr_accessor enabled: ::Array[WhopSDK::Models::payment_method_types]

          attr_accessor include_platform_defaults: bool

          def initialize: (
            disabled: ::Array[WhopSDK::Models::payment_method_types],
            enabled: ::Array[WhopSDK::Models::payment_method_types],
            include_platform_defaults: bool
          ) -> void

          def to_hash: -> {
            disabled: ::Array[WhopSDK::Models::payment_method_types],
            enabled: ::Array[WhopSDK::Models::payment_method_types],
            include_platform_defaults: bool
          }
        end

        type product =
          {
            external_identifier: String,
            title: String,
            business_type: WhopSDK::Models::business_types?,
            collect_shipping_address: bool?,
            custom_statement_descriptor: String?,
            description: String?,
            global_affiliate_percentage: Float?,
            global_affiliate_status: WhopSDK::Models::global_affiliate_status?,
            headline: String?,
            industry_type: WhopSDK::Models::industry_types?,
            product_tax_code_id: String?,
            redirect_purchase_url: String?,
            route: String?,
            visibility: WhopSDK::Models::visibility?
          }

        class Product < WhopSDK::Internal::Type::BaseModel
          attr_accessor external_identifier: String

          attr_accessor title: String

          attr_accessor business_type: WhopSDK::Models::business_types?

          attr_accessor collect_shipping_address: bool?

          attr_accessor custom_statement_descriptor: String?

          attr_accessor description: String?

          attr_accessor global_affiliate_percentage: Float?

          attr_accessor global_affiliate_status: WhopSDK::Models::global_affiliate_status?

          attr_accessor headline: String?

          attr_accessor industry_type: WhopSDK::Models::industry_types?

          attr_accessor product_tax_code_id: String?

          attr_accessor redirect_purchase_url: String?

          attr_accessor route: String?

          attr_accessor visibility: WhopSDK::Models::visibility?

          def initialize: (
            external_identifier: String,
            title: String,
            ?business_type: WhopSDK::Models::business_types?,
            ?collect_shipping_address: bool?,
            ?custom_statement_descriptor: String?,
            ?description: String?,
            ?global_affiliate_percentage: Float?,
            ?global_affiliate_status: WhopSDK::Models::global_affiliate_status?,
            ?headline: String?,
            ?industry_type: WhopSDK::Models::industry_types?,
            ?product_tax_code_id: String?,
            ?redirect_purchase_url: String?,
            ?route: String?,
            ?visibility: WhopSDK::Models::visibility?
          ) -> void

          def to_hash: -> {
            external_identifier: String,
            title: String,
            business_type: WhopSDK::Models::business_types?,
            collect_shipping_address: bool?,
            custom_statement_descriptor: String?,
            description: String?,
            global_affiliate_percentage: Float?,
            global_affiliate_status: WhopSDK::Models::global_affiliate_status?,
            headline: String?,
            industry_type: WhopSDK::Models::industry_types?,
            product_tax_code_id: String?,
            redirect_purchase_url: String?,
            route: String?,
            visibility: WhopSDK::Models::visibility?
          }
        end
      end
    end
  end
end
