module WhopSDK
  module Models
    type checkout_configuration_create_params =
      {
        account_id: String,
        affiliate_code: String?,
        currency: String?,
        metadata: top?,
        mode: WhopSDK::Models::CheckoutConfigurationCreateParams::mode,
        payment_method_configuration: WhopSDK::CheckoutConfigurationCreateParams::PaymentMethodConfiguration?,
        plan: WhopSDK::CheckoutConfigurationCreateParams::Plan?,
        plan_id: String?,
        redirect_url: String?,
        three_ds_level: WhopSDK::Models::CheckoutConfigurationCreateParams::three_ds_level?,
        api_version_date: String,
        idempotency_key: String
      }
      & WhopSDK::Internal::Type::request_parameters

    class CheckoutConfigurationCreateParams < WhopSDK::Internal::Type::BaseModel
      extend WhopSDK::Internal::Type::RequestParameters::Converter
      include WhopSDK::Internal::Type::RequestParameters

      attr_reader account_id: String?

      def account_id=: (String) -> String

      attr_accessor affiliate_code: String?

      attr_accessor currency: String?

      attr_accessor metadata: top?

      attr_reader mode: WhopSDK::Models::CheckoutConfigurationCreateParams::mode?

      def mode=: (
        WhopSDK::Models::CheckoutConfigurationCreateParams::mode
      ) -> WhopSDK::Models::CheckoutConfigurationCreateParams::mode

      attr_accessor payment_method_configuration: WhopSDK::CheckoutConfigurationCreateParams::PaymentMethodConfiguration?

      attr_accessor plan: WhopSDK::CheckoutConfigurationCreateParams::Plan?

      attr_accessor plan_id: String?

      attr_accessor redirect_url: String?

      attr_accessor three_ds_level: WhopSDK::Models::CheckoutConfigurationCreateParams::three_ds_level?

      attr_reader api_version_date: String?

      def api_version_date=: (String) -> String

      attr_reader idempotency_key: String?

      def idempotency_key=: (String) -> String

      def initialize: (
        ?account_id: String,
        ?affiliate_code: String?,
        ?currency: String?,
        ?metadata: top?,
        ?mode: WhopSDK::Models::CheckoutConfigurationCreateParams::mode,
        ?payment_method_configuration: WhopSDK::CheckoutConfigurationCreateParams::PaymentMethodConfiguration?,
        ?plan: WhopSDK::CheckoutConfigurationCreateParams::Plan?,
        ?plan_id: String?,
        ?redirect_url: String?,
        ?three_ds_level: WhopSDK::Models::CheckoutConfigurationCreateParams::three_ds_level?,
        ?api_version_date: String,
        ?idempotency_key: String,
        ?request_options: WhopSDK::request_opts
      ) -> void

      def to_hash: -> {
        account_id: String,
        affiliate_code: String?,
        currency: String?,
        metadata: top?,
        mode: WhopSDK::Models::CheckoutConfigurationCreateParams::mode,
        payment_method_configuration: WhopSDK::CheckoutConfigurationCreateParams::PaymentMethodConfiguration?,
        plan: WhopSDK::CheckoutConfigurationCreateParams::Plan?,
        plan_id: String?,
        redirect_url: String?,
        three_ds_level: WhopSDK::Models::CheckoutConfigurationCreateParams::three_ds_level?,
        api_version_date: String,
        idempotency_key: String,
        request_options: WhopSDK::RequestOptions
      }

      type mode = :payment | :setup

      module Mode
        extend WhopSDK::Internal::Type::Enum

        PAYMENT: :payment
        SETUP: :setup

        def self?.values: -> ::Array[WhopSDK::Models::CheckoutConfigurationCreateParams::mode]
      end

      type payment_method_configuration =
        {
          disabled: ::Array[WhopSDK::Models::payment_method_types],
          enabled: ::Array[WhopSDK::Models::payment_method_types],
          include_platform_defaults: bool
        }

      class PaymentMethodConfiguration < WhopSDK::Internal::Type::BaseModel
        attr_reader disabled: ::Array[WhopSDK::Models::payment_method_types]?

        def disabled=: (
          ::Array[WhopSDK::Models::payment_method_types]
        ) -> ::Array[WhopSDK::Models::payment_method_types]

        attr_reader enabled: ::Array[WhopSDK::Models::payment_method_types]?

        def enabled=: (
          ::Array[WhopSDK::Models::payment_method_types]
        ) -> ::Array[WhopSDK::Models::payment_method_types]

        attr_reader include_platform_defaults: bool?

        def include_platform_defaults=: (bool) -> bool

        def initialize: (
          ?disabled: ::Array[WhopSDK::Models::payment_method_types],
          ?enabled: ::Array[WhopSDK::Models::payment_method_types],
          ?include_platform_defaults: bool
        ) -> void

        def to_hash: -> {
          disabled: ::Array[WhopSDK::Models::payment_method_types],
          enabled: ::Array[WhopSDK::Models::payment_method_types],
          include_platform_defaults: bool
        }
      end

      type plan =
        {
          account_id: String?,
          billing_period: Integer?,
          currency: String?,
          description: String?,
          expiration_days: Integer?,
          force_create_new_plan: bool?,
          initial_price: Float?,
          metadata: top?,
          override_tax_type: String?,
          payment_method_configuration: WhopSDK::CheckoutConfigurationCreateParams::Plan::PaymentMethodConfiguration?,
          plan_type: WhopSDK::Models::CheckoutConfigurationCreateParams::Plan::plan_type?,
          product_id: String?,
          release_method: WhopSDK::Models::CheckoutConfigurationCreateParams::Plan::release_method?,
          renewal_price: Float?,
          stock: Integer?,
          three_ds_level: WhopSDK::Models::CheckoutConfigurationCreateParams::Plan::three_ds_level?,
          title: String?,
          trial_period_days: Integer?,
          unlimited_stock: bool?,
          visibility: WhopSDK::Models::CheckoutConfigurationCreateParams::Plan::visibility?
        }

      class Plan < WhopSDK::Internal::Type::BaseModel
        attr_accessor account_id: String?

        attr_accessor billing_period: Integer?

        attr_accessor currency: String?

        attr_accessor description: String?

        attr_accessor expiration_days: Integer?

        attr_accessor force_create_new_plan: bool?

        attr_accessor initial_price: Float?

        attr_accessor metadata: top?

        attr_accessor override_tax_type: String?

        attr_accessor payment_method_configuration: WhopSDK::CheckoutConfigurationCreateParams::Plan::PaymentMethodConfiguration?

        attr_accessor plan_type: WhopSDK::Models::CheckoutConfigurationCreateParams::Plan::plan_type?

        attr_accessor product_id: String?

        attr_accessor release_method: WhopSDK::Models::CheckoutConfigurationCreateParams::Plan::release_method?

        attr_accessor renewal_price: Float?

        attr_accessor stock: Integer?

        attr_accessor three_ds_level: WhopSDK::Models::CheckoutConfigurationCreateParams::Plan::three_ds_level?

        attr_accessor title: String?

        attr_accessor trial_period_days: Integer?

        attr_accessor unlimited_stock: bool?

        attr_accessor visibility: WhopSDK::Models::CheckoutConfigurationCreateParams::Plan::visibility?

        def initialize: (
          ?account_id: String?,
          ?billing_period: Integer?,
          ?currency: String?,
          ?description: String?,
          ?expiration_days: Integer?,
          ?force_create_new_plan: bool?,
          ?initial_price: Float?,
          ?metadata: top?,
          ?override_tax_type: String?,
          ?payment_method_configuration: WhopSDK::CheckoutConfigurationCreateParams::Plan::PaymentMethodConfiguration?,
          ?plan_type: WhopSDK::Models::CheckoutConfigurationCreateParams::Plan::plan_type?,
          ?product_id: String?,
          ?release_method: WhopSDK::Models::CheckoutConfigurationCreateParams::Plan::release_method?,
          ?renewal_price: Float?,
          ?stock: Integer?,
          ?three_ds_level: WhopSDK::Models::CheckoutConfigurationCreateParams::Plan::three_ds_level?,
          ?title: String?,
          ?trial_period_days: Integer?,
          ?unlimited_stock: bool?,
          ?visibility: WhopSDK::Models::CheckoutConfigurationCreateParams::Plan::visibility?
        ) -> void

        def to_hash: -> {
          account_id: String?,
          billing_period: Integer?,
          currency: String?,
          description: String?,
          expiration_days: Integer?,
          force_create_new_plan: bool?,
          initial_price: Float?,
          metadata: top?,
          override_tax_type: String?,
          payment_method_configuration: WhopSDK::CheckoutConfigurationCreateParams::Plan::PaymentMethodConfiguration?,
          plan_type: WhopSDK::Models::CheckoutConfigurationCreateParams::Plan::plan_type?,
          product_id: String?,
          release_method: WhopSDK::Models::CheckoutConfigurationCreateParams::Plan::release_method?,
          renewal_price: Float?,
          stock: Integer?,
          three_ds_level: WhopSDK::Models::CheckoutConfigurationCreateParams::Plan::three_ds_level?,
          title: String?,
          trial_period_days: Integer?,
          unlimited_stock: bool?,
          visibility: WhopSDK::Models::CheckoutConfigurationCreateParams::Plan::visibility?
        }

        type payment_method_configuration =
          {
            disabled: ::Array[WhopSDK::Models::payment_method_types],
            enabled: ::Array[WhopSDK::Models::payment_method_types],
            include_platform_defaults: bool
          }

        class PaymentMethodConfiguration < WhopSDK::Internal::Type::BaseModel
          attr_reader disabled: ::Array[WhopSDK::Models::payment_method_types]?

          def disabled=: (
            ::Array[WhopSDK::Models::payment_method_types]
          ) -> ::Array[WhopSDK::Models::payment_method_types]

          attr_reader enabled: ::Array[WhopSDK::Models::payment_method_types]?

          def enabled=: (
            ::Array[WhopSDK::Models::payment_method_types]
          ) -> ::Array[WhopSDK::Models::payment_method_types]

          attr_reader include_platform_defaults: bool?

          def include_platform_defaults=: (bool) -> bool

          def initialize: (
            ?disabled: ::Array[WhopSDK::Models::payment_method_types],
            ?enabled: ::Array[WhopSDK::Models::payment_method_types],
            ?include_platform_defaults: bool
          ) -> void

          def to_hash: -> {
            disabled: ::Array[WhopSDK::Models::payment_method_types],
            enabled: ::Array[WhopSDK::Models::payment_method_types],
            include_platform_defaults: bool
          }
        end

        type plan_type = :renewal | :one_time

        module PlanType
          extend WhopSDK::Internal::Type::Enum

          RENEWAL: :renewal
          ONE_TIME: :one_time

          def self?.values: -> ::Array[WhopSDK::Models::CheckoutConfigurationCreateParams::Plan::plan_type]
        end

        type release_method = :buy_now | :waitlist

        module ReleaseMethod
          extend WhopSDK::Internal::Type::Enum

          BUY_NOW: :buy_now
          WAITLIST: :waitlist

          def self?.values: -> ::Array[WhopSDK::Models::CheckoutConfigurationCreateParams::Plan::release_method]
        end

        type three_ds_level = :mandate_challenge | :frictionless

        module ThreeDSLevel
          extend WhopSDK::Internal::Type::Enum

          MANDATE_CHALLENGE: :mandate_challenge
          FRICTIONLESS: :frictionless

          def self?.values: -> ::Array[WhopSDK::Models::CheckoutConfigurationCreateParams::Plan::three_ds_level]
        end

        type visibility = :visible | :hidden | :archived | :quick_link

        module Visibility
          extend WhopSDK::Internal::Type::Enum

          VISIBLE: :visible
          HIDDEN: :hidden
          ARCHIVED: :archived
          QUICK_LINK: :quick_link

          def self?.values: -> ::Array[WhopSDK::Models::CheckoutConfigurationCreateParams::Plan::visibility]
        end
      end

      type three_ds_level = :mandate_challenge | :frictionless

      module ThreeDSLevel
        extend WhopSDK::Internal::Type::Enum

        MANDATE_CHALLENGE: :mandate_challenge
        FRICTIONLESS: :frictionless

        def self?.values: -> ::Array[WhopSDK::Models::CheckoutConfigurationCreateParams::three_ds_level]
      end
    end
  end
end
