module WhopSDK
  module Models
    type checkout_configuration =
      {
        id: String,
        affiliate_code: String?,
        company_id: String,
        currency: WhopSDK::Models::currency?,
        metadata: ::Hash[Symbol, top]?,
        mode: WhopSDK::Models::checkout_modes,
        payment_method_configuration: WhopSDK::CheckoutConfiguration::PaymentMethodConfiguration?,
        plan: WhopSDK::CheckoutConfiguration::Plan?,
        purchase_url: String,
        redirect_url: String?
      }

    class CheckoutConfiguration < WhopSDK::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor affiliate_code: String?

      attr_accessor company_id: String

      attr_accessor currency: WhopSDK::Models::currency?

      attr_accessor metadata: ::Hash[Symbol, top]?

      attr_accessor mode: WhopSDK::Models::checkout_modes

      attr_accessor payment_method_configuration: WhopSDK::CheckoutConfiguration::PaymentMethodConfiguration?

      attr_accessor plan: WhopSDK::CheckoutConfiguration::Plan?

      attr_accessor purchase_url: String

      attr_accessor redirect_url: String?

      def initialize: (
        id: String,
        affiliate_code: String?,
        company_id: String,
        currency: WhopSDK::Models::currency?,
        metadata: ::Hash[Symbol, top]?,
        mode: WhopSDK::Models::checkout_modes,
        payment_method_configuration: WhopSDK::CheckoutConfiguration::PaymentMethodConfiguration?,
        plan: WhopSDK::CheckoutConfiguration::Plan?,
        purchase_url: String,
        redirect_url: String?
      ) -> void

      def to_hash: -> {
        id: String,
        affiliate_code: String?,
        company_id: String,
        currency: WhopSDK::Models::currency?,
        metadata: ::Hash[Symbol, top]?,
        mode: WhopSDK::Models::checkout_modes,
        payment_method_configuration: WhopSDK::CheckoutConfiguration::PaymentMethodConfiguration?,
        plan: WhopSDK::CheckoutConfiguration::Plan?,
        purchase_url: String,
        redirect_url: String?
      }

      type payment_method_configuration =
        {
          disabled: ::Array[WhopSDK::Models::payment_method_types],
          enabled: ::Array[WhopSDK::Models::payment_method_types],
          include_platform_defaults: bool
        }

      class PaymentMethodConfiguration < WhopSDK::Internal::Type::BaseModel
        attr_accessor disabled: ::Array[WhopSDK::Models::payment_method_types]

        attr_accessor enabled: ::Array[WhopSDK::Models::payment_method_types]

        attr_accessor include_platform_defaults: bool

        def initialize: (
          disabled: ::Array[WhopSDK::Models::payment_method_types],
          enabled: ::Array[WhopSDK::Models::payment_method_types],
          include_platform_defaults: bool
        ) -> void

        def to_hash: -> {
          disabled: ::Array[WhopSDK::Models::payment_method_types],
          enabled: ::Array[WhopSDK::Models::payment_method_types],
          include_platform_defaults: bool
        }
      end

      type plan =
        {
          id: String,
          billing_period: Integer?,
          currency: WhopSDK::Models::currency,
          expiration_days: Integer?,
          initial_price: Float,
          plan_type: WhopSDK::Models::plan_type,
          release_method: WhopSDK::Models::release_method,
          renewal_price: Float,
          trial_period_days: Integer?,
          visibility: WhopSDK::Models::visibility
        }

      class Plan < WhopSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor billing_period: Integer?

        attr_accessor currency: WhopSDK::Models::currency

        attr_accessor expiration_days: Integer?

        attr_accessor initial_price: Float

        attr_accessor plan_type: WhopSDK::Models::plan_type

        attr_accessor release_method: WhopSDK::Models::release_method

        attr_accessor renewal_price: Float

        attr_accessor trial_period_days: Integer?

        attr_accessor visibility: WhopSDK::Models::visibility

        def initialize: (
          id: String,
          billing_period: Integer?,
          currency: WhopSDK::Models::currency,
          expiration_days: Integer?,
          initial_price: Float,
          plan_type: WhopSDK::Models::plan_type,
          release_method: WhopSDK::Models::release_method,
          renewal_price: Float,
          trial_period_days: Integer?,
          visibility: WhopSDK::Models::visibility
        ) -> void

        def to_hash: -> {
          id: String,
          billing_period: Integer?,
          currency: WhopSDK::Models::currency,
          expiration_days: Integer?,
          initial_price: Float,
          plan_type: WhopSDK::Models::plan_type,
          release_method: WhopSDK::Models::release_method,
          renewal_price: Float,
          trial_period_days: Integer?,
          visibility: WhopSDK::Models::visibility
        }
      end
    end
  end
end
