module WhopSDK
  module Models
    type company_list_response =
      {
        id: String,
        business_type: WhopSDK::Models::business_types?,
        created_at: Time,
        description: String?,
        industry_type: WhopSDK::Models::industry_types?,
        logo: WhopSDK::Models::CompanyListResponse::Logo?,
        member_count: Integer,
        metadata: ::Hash[Symbol, top]?,
        owner_user: WhopSDK::Models::CompanyListResponse::OwnerUser,
        published_reviews_count: Integer,
        route: String,
        title: String,
        updated_at: Time,
        verified: bool
      }

    class CompanyListResponse < WhopSDK::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor business_type: WhopSDK::Models::business_types?

      attr_accessor created_at: Time

      attr_accessor description: String?

      attr_accessor industry_type: WhopSDK::Models::industry_types?

      attr_accessor logo: WhopSDK::Models::CompanyListResponse::Logo?

      attr_accessor member_count: Integer

      attr_accessor metadata: ::Hash[Symbol, top]?

      attr_accessor owner_user: WhopSDK::Models::CompanyListResponse::OwnerUser

      attr_accessor published_reviews_count: Integer

      attr_accessor route: String

      attr_accessor title: String

      attr_accessor updated_at: Time

      attr_accessor verified: bool

      def initialize: (
        id: String,
        business_type: WhopSDK::Models::business_types?,
        created_at: Time,
        description: String?,
        industry_type: WhopSDK::Models::industry_types?,
        logo: WhopSDK::Models::CompanyListResponse::Logo?,
        member_count: Integer,
        metadata: ::Hash[Symbol, top]?,
        owner_user: WhopSDK::Models::CompanyListResponse::OwnerUser,
        published_reviews_count: Integer,
        route: String,
        title: String,
        updated_at: Time,
        verified: bool
      ) -> void

      def to_hash: -> {
        id: String,
        business_type: WhopSDK::Models::business_types?,
        created_at: Time,
        description: String?,
        industry_type: WhopSDK::Models::industry_types?,
        logo: WhopSDK::Models::CompanyListResponse::Logo?,
        member_count: Integer,
        metadata: ::Hash[Symbol, top]?,
        owner_user: WhopSDK::Models::CompanyListResponse::OwnerUser,
        published_reviews_count: Integer,
        route: String,
        title: String,
        updated_at: Time,
        verified: bool
      }

      type logo = { url: String? }

      class Logo < WhopSDK::Internal::Type::BaseModel
        attr_accessor url: String?

        def initialize: (url: String?) -> void

        def to_hash: -> { url: String? }
      end

      type owner_user = { id: String, name: String?, username: String }

      class OwnerUser < WhopSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor name: String?

        attr_accessor username: String

        def initialize: (id: String, name: String?, username: String) -> void

        def to_hash: -> { id: String, name: String?, username: String }
      end
    end
  end
end
