module WhopSDK
  module Models
    type company_create_params =
      {
        title: String,
        business_type: WhopSDK::Models::business_types?,
        description: String?,
        email: String?,
        industry_type: WhopSDK::Models::industry_types?,
        logo: WhopSDK::CompanyCreateParams::Logo?,
        metadata: ::Hash[Symbol, top]?,
        parent_company_id: String?,
        send_customer_emails: bool?
      }
      & WhopSDK::Internal::Type::request_parameters

    class CompanyCreateParams < WhopSDK::Internal::Type::BaseModel
      extend WhopSDK::Internal::Type::RequestParameters::Converter
      include WhopSDK::Internal::Type::RequestParameters

      attr_accessor title: String

      attr_accessor business_type: WhopSDK::Models::business_types?

      attr_accessor description: String?

      attr_accessor email: String?

      attr_accessor industry_type: WhopSDK::Models::industry_types?

      attr_accessor logo: WhopSDK::CompanyCreateParams::Logo?

      attr_accessor metadata: ::Hash[Symbol, top]?

      attr_accessor parent_company_id: String?

      attr_accessor send_customer_emails: bool?

      def initialize: (
        title: String,
        ?business_type: WhopSDK::Models::business_types?,
        ?description: String?,
        ?email: String?,
        ?industry_type: WhopSDK::Models::industry_types?,
        ?logo: WhopSDK::CompanyCreateParams::Logo?,
        ?metadata: ::Hash[Symbol, top]?,
        ?parent_company_id: String?,
        ?send_customer_emails: bool?,
        ?request_options: WhopSDK::request_opts
      ) -> void

      def to_hash: -> {
        title: String,
        business_type: WhopSDK::Models::business_types?,
        description: String?,
        email: String?,
        industry_type: WhopSDK::Models::industry_types?,
        logo: WhopSDK::CompanyCreateParams::Logo?,
        metadata: ::Hash[Symbol, top]?,
        parent_company_id: String?,
        send_customer_emails: bool?,
        request_options: WhopSDK::RequestOptions
      }

      type logo = { id: String }

      class Logo < WhopSDK::Internal::Type::BaseModel
        attr_accessor id: String

        def initialize: (id: String) -> void

        def to_hash: -> { id: String }
      end
    end
  end
end
