module WhopSDK
  module Models
    type company_create_params =
      {
        title: String,
        country: WhopSDK::Models::CompanyCreateParams::country?,
        description: String?,
        email: String?,
        logo: WhopSDK::CompanyCreateParams::Logo?,
        metadata: ::Hash[Symbol, top]?,
        parent_company_id: String?,
        send_customer_emails: bool?
      }
      & WhopSDK::Internal::Type::request_parameters

    class CompanyCreateParams < WhopSDK::Internal::Type::BaseModel
      extend WhopSDK::Internal::Type::RequestParameters::Converter
      include WhopSDK::Internal::Type::RequestParameters

      attr_accessor title: String

      attr_accessor country: WhopSDK::Models::CompanyCreateParams::country?

      attr_accessor description: String?

      attr_accessor email: String?

      attr_accessor logo: WhopSDK::CompanyCreateParams::Logo?

      attr_accessor metadata: ::Hash[Symbol, top]?

      attr_accessor parent_company_id: String?

      attr_accessor send_customer_emails: bool?

      def initialize: (
        title: String,
        ?country: WhopSDK::Models::CompanyCreateParams::country?,
        ?description: String?,
        ?email: String?,
        ?logo: WhopSDK::CompanyCreateParams::Logo?,
        ?metadata: ::Hash[Symbol, top]?,
        ?parent_company_id: String?,
        ?send_customer_emails: bool?,
        ?request_options: WhopSDK::request_opts
      ) -> void

      def to_hash: -> {
        title: String,
        country: WhopSDK::Models::CompanyCreateParams::country?,
        description: String?,
        email: String?,
        logo: WhopSDK::CompanyCreateParams::Logo?,
        metadata: ::Hash[Symbol, top]?,
        parent_company_id: String?,
        send_customer_emails: bool?,
        request_options: WhopSDK::RequestOptions
      }

      type country =
        :us
        | :ca
        | :gb
        | :ab
        | :af
        | :al
        | :dz
        | :as
        | :ad
        | :ao
        | :ai
        | :aq
        | :ag
        | :ar
        | :am
        | :aw
        | :au
        | :at
        | :az
        | :bs
        | :bh
        | :bd
        | :bb
        | :by
        | :be
        | :bz
        | :bj
        | :bm
        | :bt
        | :bo
        | :ba
        | :bw
        | :br
        | :io
        | :vg
        | :bn
        | :bg
        | :bf
        | :bi
        | :kh
        | :cm
        | :cv
        | :ky
        | :cf
        | :td
        | :cl
        | :cn
        | :cx
        | :cc
        | :co
        | :km
        | :cg
        | :ck
        | :cr
        | :ci
        | :hr
        | :cu
        | :cw
        | :cy
        | :cz
        | :cd
        | :dk
        | :dj
        | :dm
        | :do
        | :ec
        | :eg
        | :sv
        | :gq
        | :ee
        | :et
        | :fk
        | :fo
        | :fj
        | :fi
        | :fr
        | :gf
        | :pf
        | :ga
        | :gm
        | :ge
        | :de
        | :gh
        | :gi
        | :gr
        | :gl
        | :gd
        | :gp
        | :gu
        | :gt
        | :gg
        | :gn
        | :gw
        | :gy
        | :ht
        | :hn
        | :hk
        | :hu
        | :is
        | :in
        | :id
        | :iq
        | :ie
        | :im
        | :il
        | :it
        | :jm
        | :sj
        | :jp
        | :je
        | :jo
        | :kz
        | :ke
        | :ki
        | :xk
        | :kw
        | :kg
        | :la
        | :lv
        | :lb
        | :ls
        | :lr
        | :ly
        | :li
        | :lt
        | :lu
        | :mo
        | :mk
        | :mg
        | :mw
        | :my
        | :mv
        | :ml
        | :mt
        | :mh
        | :mq
        | :mr
        | :mu
        | :yt
        | :mx
        | :fm
        | :md
        | :mc
        | :mn
        | :me
        | :ms
        | :ma
        | :mz
        | :mm
        | :na
        | :nr
        | :np
        | :nl
        | :an
        | :nc
        | :nz
        | :ni
        | :ne
        | :ng
        | :nu
        | :mp
        | :no
        | :om
        | :pk
        | :pw
        | :ps
        | :pa
        | :pg
        | :py
        | :pe
        | :ph
        | :pn
        | :pl
        | :pt
        | :pr
        | :qa
        | :re
        | :ro
        | :ru
        | :rw
        | :bl
        | :sh
        | :kn
        | :lc
        | :mf
        | :pm
        | :vc
        | :ws
        | :sm
        | :st
        | :sa
        | :sn
        | :rs
        | :sc
        | :sl
        | :sg
        | :sx
        | :sk
        | :si
        | :sb
        | :so
        | :za
        | :kr
        | :ss
        | :es
        | :lk
        | :sd
        | :sr
        | :sz
        | :se
        | :ch
        | :tw
        | :tj
        | :tz
        | :th
        | :tl
        | :tg
        | :tk
        | :to
        | :tt
        | :tn
        | :tr
        | :tm
        | :tc
        | :tv
        | :vi
        | :ug
        | :ua
        | :ae
        | :um
        | :uy
        | :uz
        | :vu
        | :va
        | :ve
        | :vn
        | :wf
        | :eh
        | :ye
        | :zm
        | :zw
        | :sy

      module Country
        extend WhopSDK::Internal::Type::Enum

        US: :us
        CA: :ca
        GB: :gb
        AB: :ab
        AF: :af
        AL: :al
        DZ: :dz
        AS: :as
        AD: :ad
        AO: :ao
        AI: :ai
        AQ: :aq
        AG: :ag
        AR: :ar
        AM: :am
        AW: :aw
        AU: :au
        AT: :at
        AZ: :az
        BS: :bs
        BH: :bh
        BD: :bd
        BB: :bb
        BY: :by
        BE: :be
        BZ: :bz
        BJ: :bj
        BM: :bm
        BT: :bt
        BO: :bo
        BA: :ba
        BW: :bw
        BR: :br
        IO: :io
        VG: :vg
        BN: :bn
        BG: :bg
        BF: :bf
        BI: :bi
        KH: :kh
        CM: :cm
        CV: :cv
        KY: :ky
        CF: :cf
        TD: :td
        CL: :cl
        CN: :cn
        CX: :cx
        CC: :cc
        CO: :co
        KM: :km
        CG: :cg
        CK: :ck
        CR: :cr
        CI: :ci
        HR: :hr
        CU: :cu
        CW: :cw
        CY: :cy
        CZ: :cz
        CD: :cd
        DK: :dk
        DJ: :dj
        DM: :dm
        DO: :do
        EC: :ec
        EG: :eg
        SV: :sv
        GQ: :gq
        EE: :ee
        ET: :et
        FK: :fk
        FO: :fo
        FJ: :fj
        FI: :fi
        FR: :fr
        GF: :gf
        PF: :pf
        GA: :ga
        GM: :gm
        GE: :ge
        DE: :de
        GH: :gh
        GI: :gi
        GR: :gr
        GL: :gl
        GD: :gd
        GP: :gp
        GU: :gu
        GT: :gt
        GG: :gg
        GN: :gn
        GW: :gw
        GY: :gy
        HT: :ht
        HN: :hn
        HK: :hk
        HU: :hu
        IS: :is
        IN: :in
        ID: :id
        IQ: :iq
        IE: :ie
        IM: :im
        IL: :il
        IT: :it
        JM: :jm
        SJ: :sj
        JP: :jp
        JE: :je
        JO: :jo
        KZ: :kz
        KE: :ke
        KI: :ki
        XK: :xk
        KW: :kw
        KG: :kg
        LA: :la
        LV: :lv
        LB: :lb
        LS: :ls
        LR: :lr
        LY: :ly
        LI: :li
        LT: :lt
        LU: :lu
        MO: :mo
        MK: :mk
        MG: :mg
        MW: :mw
        MY: :my
        MV: :mv
        ML: :ml
        MT: :mt
        MH: :mh
        MQ: :mq
        MR: :mr
        MU: :mu
        YT: :yt
        MX: :mx
        FM: :fm
        MD: :md
        MC: :mc
        MN: :mn
        ME: :me
        MS: :ms
        MA: :ma
        MZ: :mz
        MM: :mm
        NA: :na
        NR: :nr
        NP: :np
        NL: :nl
        AN: :an
        NC: :nc
        NZ: :nz
        NI: :ni
        NE: :ne
        NG: :ng
        NU: :nu
        MP: :mp
        NO: :no
        OM: :om
        PK: :pk
        PW: :pw
        PS: :ps
        PA: :pa
        PG: :pg
        PY: :py
        PE: :pe
        PH: :ph
        PN: :pn
        PL: :pl
        PT: :pt
        PR: :pr
        QA: :qa
        RE: :re
        RO: :ro
        RU: :ru
        RW: :rw
        BL: :bl
        SH: :sh
        KN: :kn
        LC: :lc
        MF: :mf
        PM: :pm
        VC: :vc
        WS: :ws
        SM: :sm
        ST: :st
        SA: :sa
        SN: :sn
        RS: :rs
        SC: :sc
        SL: :sl
        SG: :sg
        SX: :sx
        SK: :sk
        SI: :si
        SB: :sb
        SO: :so
        ZA: :za
        KR: :kr
        SS: :ss
        ES: :es
        LK: :lk
        SD: :sd
        SR: :sr
        SZ: :sz
        SE: :se
        CH: :ch
        TW: :tw
        TJ: :tj
        TZ: :tz
        TH: :th
        TL: :tl
        TG: :tg
        TK: :tk
        TO: :to
        TT: :tt
        TN: :tn
        TR: :tr
        TM: :tm
        TC: :tc
        TV: :tv
        VI: :vi
        UG: :ug
        UA: :ua
        AE: :ae
        UM: :um
        UY: :uy
        UZ: :uz
        VU: :vu
        VA: :va
        VE: :ve
        VN: :vn
        WF: :wf
        EH: :eh
        YE: :ye
        ZM: :zm
        ZW: :zw
        SY: :sy

        def self?.values: -> ::Array[WhopSDK::Models::CompanyCreateParams::country]
      end

      type logo = { id: String }

      class Logo < WhopSDK::Internal::Type::BaseModel
        attr_accessor id: String

        def initialize: (id: String) -> void

        def to_hash: -> { id: String }
      end
    end
  end
end
