module WhopSDK
  module Models
    type course_update_params =
      {
        certificate_after_completion_enabled: bool?,
        chapters: ::Array[WhopSDK::CourseUpdateParams::Chapter]?,
        cover_image: String?,
        description: String?,
        language: WhopSDK::Models::languages?,
        order: String?,
        require_completing_lessons_in_order: bool?,
        tagline: String?,
        thumbnail: WhopSDK::Models::CourseUpdateParams::thumbnail?,
        title: String?,
        visibility: WhopSDK::Models::CourseUpdateParams::visibility?
      }
      & WhopSDK::Internal::Type::request_parameters

    class CourseUpdateParams < WhopSDK::Internal::Type::BaseModel
      extend WhopSDK::Internal::Type::RequestParameters::Converter
      include WhopSDK::Internal::Type::RequestParameters

      attr_accessor certificate_after_completion_enabled: bool?

      attr_accessor chapters: ::Array[WhopSDK::CourseUpdateParams::Chapter]?

      attr_accessor cover_image: String?

      attr_accessor description: String?

      attr_accessor language: WhopSDK::Models::languages?

      attr_accessor order: String?

      attr_accessor require_completing_lessons_in_order: bool?

      attr_accessor tagline: String?

      attr_accessor thumbnail: WhopSDK::Models::CourseUpdateParams::thumbnail?

      attr_accessor title: String?

      attr_accessor visibility: WhopSDK::Models::CourseUpdateParams::visibility?

      def initialize: (
        ?certificate_after_completion_enabled: bool?,
        ?chapters: ::Array[WhopSDK::CourseUpdateParams::Chapter]?,
        ?cover_image: String?,
        ?description: String?,
        ?language: WhopSDK::Models::languages?,
        ?order: String?,
        ?require_completing_lessons_in_order: bool?,
        ?tagline: String?,
        ?thumbnail: WhopSDK::Models::CourseUpdateParams::thumbnail?,
        ?title: String?,
        ?visibility: WhopSDK::Models::CourseUpdateParams::visibility?,
        ?request_options: WhopSDK::request_opts
      ) -> void

      def to_hash: -> {
        certificate_after_completion_enabled: bool?,
        chapters: ::Array[WhopSDK::CourseUpdateParams::Chapter]?,
        cover_image: String?,
        description: String?,
        language: WhopSDK::Models::languages?,
        order: String?,
        require_completing_lessons_in_order: bool?,
        tagline: String?,
        thumbnail: WhopSDK::Models::CourseUpdateParams::thumbnail?,
        title: String?,
        visibility: WhopSDK::Models::CourseUpdateParams::visibility?,
        request_options: WhopSDK::RequestOptions
      }

      type chapter =
        {
          id: String,
          order: Integer,
          title: String,
          lessons: ::Array[WhopSDK::CourseUpdateParams::Chapter::Lesson]?
        }

      class Chapter < WhopSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor order: Integer

        attr_accessor title: String

        attr_accessor lessons: ::Array[WhopSDK::CourseUpdateParams::Chapter::Lesson]?

        def initialize: (
          id: String,
          order: Integer,
          title: String,
          ?lessons: ::Array[WhopSDK::CourseUpdateParams::Chapter::Lesson]?
        ) -> void

        def to_hash: -> {
          id: String,
          order: Integer,
          title: String,
          lessons: ::Array[WhopSDK::CourseUpdateParams::Chapter::Lesson]?
        }

        type lesson =
          { id: String, chapter_id: String, order: Integer, title: String }

        class Lesson < WhopSDK::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor chapter_id: String

          attr_accessor order: Integer

          attr_accessor title: String

          def initialize: (
            id: String,
            chapter_id: String,
            order: Integer,
            title: String
          ) -> void

          def to_hash: -> {
            id: String,
            chapter_id: String,
            order: Integer,
            title: String
          }
        end
      end

      type thumbnail =
        WhopSDK::CourseUpdateParams::Thumbnail::AttachmentInputWithDirectUploadID
        | WhopSDK::CourseUpdateParams::Thumbnail::AttachmentInputWithID

      module Thumbnail
        extend WhopSDK::Internal::Type::Union

        type attachment_input_with_direct_upload_id =
          { direct_upload_id: String }

        class AttachmentInputWithDirectUploadID < WhopSDK::Internal::Type::BaseModel
          attr_accessor direct_upload_id: String

          def initialize: (direct_upload_id: String) -> void

          def to_hash: -> { direct_upload_id: String }
        end

        type attachment_input_with_id = { id: String }

        class AttachmentInputWithID < WhopSDK::Internal::Type::BaseModel
          attr_accessor id: String

          def initialize: (id: String) -> void

          def to_hash: -> { id: String }
        end

        def self?.variants: -> ::Array[WhopSDK::Models::CourseUpdateParams::thumbnail]
      end

      type visibility = :visible | :hidden

      module Visibility
        extend WhopSDK::Internal::Type::Enum

        VISIBLE: :visible
        HIDDEN: :hidden

        def self?.values: -> ::Array[WhopSDK::Models::CourseUpdateParams::visibility]
      end
    end
  end
end
