module WhopSDK
  module Models
    type course_list_params =
      {
        after: String,
        before: String,
        company_id: String,
        experience_id: String,
        first: Integer,
        last: Integer
      }
      & WhopSDK::Internal::Type::request_parameters

    class CourseListParams < WhopSDK::Internal::Type::BaseModel
      extend WhopSDK::Internal::Type::RequestParameters::Converter
      include WhopSDK::Internal::Type::RequestParameters

      attr_reader after: String?

      def after=: (String) -> String

      attr_reader before: String?

      def before=: (String) -> String

      attr_reader company_id: String?

      def company_id=: (String) -> String

      attr_reader experience_id: String?

      def experience_id=: (String) -> String

      attr_reader first: Integer?

      def first=: (Integer) -> Integer

      attr_reader last: Integer?

      def last=: (Integer) -> Integer

      def initialize: (
        ?after: String,
        ?before: String,
        ?company_id: String,
        ?experience_id: String,
        ?first: Integer,
        ?last: Integer,
        ?request_options: WhopSDK::request_opts
      ) -> void

      def to_hash: -> {
        after: String,
        before: String,
        company_id: String,
        experience_id: String,
        first: Integer,
        last: Integer,
        request_options: WhopSDK::RequestOptions
      }
    end
  end
end
