module WhopSDK
  module Models
    type course_lesson_mark_as_completed_params =
      { lesson_id: String } & WhopSDK::Internal::Type::request_parameters

    class CourseLessonMarkAsCompletedParams < WhopSDK::Internal::Type::BaseModel
      extend WhopSDK::Internal::Type::RequestParameters::Converter
      include WhopSDK::Internal::Type::RequestParameters

      attr_accessor lesson_id: String

      def initialize: (
        lesson_id: String,
        ?request_options: WhopSDK::request_opts
      ) -> void

      def to_hash: -> {
        lesson_id: String,
        request_options: WhopSDK::RequestOptions
      }
    end
  end
end
