module WhopSDK
  module Models
    type course_lesson_interaction_list_item =
      {
        id: String,
        completed: bool,
        created_at: Time,
        lesson: WhopSDK::CourseLessonInteractionListItem::Lesson,
        user: WhopSDK::CourseLessonInteractionListItem::User
      }

    class CourseLessonInteractionListItem < WhopSDK::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor completed: bool

      attr_accessor created_at: Time

      attr_accessor lesson: WhopSDK::CourseLessonInteractionListItem::Lesson

      attr_accessor user: WhopSDK::CourseLessonInteractionListItem::User

      def initialize: (
        id: String,
        completed: bool,
        created_at: Time,
        lesson: WhopSDK::CourseLessonInteractionListItem::Lesson,
        user: WhopSDK::CourseLessonInteractionListItem::User
      ) -> void

      def to_hash: -> {
        id: String,
        completed: bool,
        created_at: Time,
        lesson: WhopSDK::CourseLessonInteractionListItem::Lesson,
        user: WhopSDK::CourseLessonInteractionListItem::User
      }

      type lesson =
        {
          id: String,
          chapter: WhopSDK::CourseLessonInteractionListItem::Lesson::Chapter,
          title: String
        }

      class Lesson < WhopSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor chapter: WhopSDK::CourseLessonInteractionListItem::Lesson::Chapter

        attr_accessor title: String

        def initialize: (
          id: String,
          chapter: WhopSDK::CourseLessonInteractionListItem::Lesson::Chapter,
          title: String
        ) -> void

        def to_hash: -> {
          id: String,
          chapter: WhopSDK::CourseLessonInteractionListItem::Lesson::Chapter,
          title: String
        }

        type chapter = { id: String }

        class Chapter < WhopSDK::Internal::Type::BaseModel
          attr_accessor id: String

          def initialize: (id: String) -> void

          def to_hash: -> { id: String }
        end
      end

      type user = { id: String, name: String?, username: String }

      class User < WhopSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor name: String?

        attr_accessor username: String

        def initialize: (id: String, name: String?, username: String) -> void

        def to_hash: -> { id: String, name: String?, username: String }
      end
    end
  end
end
