module WhopSDK
  module Models
    type course_lesson_list_response =
      {
        id: String,
        content: String?,
        days_from_course_start_until_unlock: Integer?,
        embed_id: String?,
        embed_type: WhopSDK::Models::embed_type?,
        lesson_type: WhopSDK::Models::lesson_types,
        order: Integer,
        thumbnail: WhopSDK::Models::CourseLessonListResponse::Thumbnail?,
        title: String,
        visibility: WhopSDK::Models::lesson_visibilities
      }

    class CourseLessonListResponse < WhopSDK::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor content: String?

      attr_accessor days_from_course_start_until_unlock: Integer?

      attr_accessor embed_id: String?

      attr_accessor embed_type: WhopSDK::Models::embed_type?

      attr_accessor lesson_type: WhopSDK::Models::lesson_types

      attr_accessor order: Integer

      attr_accessor thumbnail: WhopSDK::Models::CourseLessonListResponse::Thumbnail?

      attr_accessor title: String

      attr_accessor visibility: WhopSDK::Models::lesson_visibilities

      def initialize: (
        id: String,
        content: String?,
        days_from_course_start_until_unlock: Integer?,
        embed_id: String?,
        embed_type: WhopSDK::Models::embed_type?,
        lesson_type: WhopSDK::Models::lesson_types,
        order: Integer,
        thumbnail: WhopSDK::Models::CourseLessonListResponse::Thumbnail?,
        title: String,
        visibility: WhopSDK::Models::lesson_visibilities
      ) -> void

      def to_hash: -> {
        id: String,
        content: String?,
        days_from_course_start_until_unlock: Integer?,
        embed_id: String?,
        embed_type: WhopSDK::Models::embed_type?,
        lesson_type: WhopSDK::Models::lesson_types,
        order: Integer,
        thumbnail: WhopSDK::Models::CourseLessonListResponse::Thumbnail?,
        title: String,
        visibility: WhopSDK::Models::lesson_visibilities
      }

      type thumbnail = { url: String? }

      class Thumbnail < WhopSDK::Internal::Type::BaseModel
        attr_accessor url: String?

        def initialize: (url: String?) -> void

        def to_hash: -> { url: String? }
      end
    end
  end
end
