module WhopSDK
  module Models
    type course =
      {
        id: String,
        certificate_after_completion_enabled: bool?,
        chapters: ::Array[WhopSDK::Course::Chapter],
        description: String?,
        language: WhopSDK::Models::languages,
        require_completing_lessons_in_order: bool,
        tagline: String?,
        thumbnail: WhopSDK::Course::Thumbnail?,
        title: String?
      }

    class Course < WhopSDK::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor certificate_after_completion_enabled: bool?

      attr_accessor chapters: ::Array[WhopSDK::Course::Chapter]

      attr_accessor description: String?

      attr_accessor language: WhopSDK::Models::languages

      attr_accessor require_completing_lessons_in_order: bool

      attr_accessor tagline: String?

      attr_accessor thumbnail: WhopSDK::Course::Thumbnail?

      attr_accessor title: String?

      def initialize: (
        id: String,
        certificate_after_completion_enabled: bool?,
        chapters: ::Array[WhopSDK::Course::Chapter],
        description: String?,
        language: WhopSDK::Models::languages,
        require_completing_lessons_in_order: bool,
        tagline: String?,
        thumbnail: WhopSDK::Course::Thumbnail?,
        title: String?
      ) -> void

      def to_hash: -> {
        id: String,
        certificate_after_completion_enabled: bool?,
        chapters: ::Array[WhopSDK::Course::Chapter],
        description: String?,
        language: WhopSDK::Models::languages,
        require_completing_lessons_in_order: bool,
        tagline: String?,
        thumbnail: WhopSDK::Course::Thumbnail?,
        title: String?
      }

      type chapter =
        {
          id: String,
          lessons: ::Array[WhopSDK::Course::Chapter::Lesson],
          order: Integer,
          title: String
        }

      class Chapter < WhopSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor lessons: ::Array[WhopSDK::Course::Chapter::Lesson]

        attr_accessor order: Integer

        attr_accessor title: String

        def initialize: (
          id: String,
          lessons: ::Array[WhopSDK::Course::Chapter::Lesson],
          order: Integer,
          title: String
        ) -> void

        def to_hash: -> {
          id: String,
          lessons: ::Array[WhopSDK::Course::Chapter::Lesson],
          order: Integer,
          title: String
        }

        type lesson =
          {
            id: String,
            lesson_type: WhopSDK::Models::lesson_types,
            order: Integer,
            title: String
          }

        class Lesson < WhopSDK::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor lesson_type: WhopSDK::Models::lesson_types

          attr_accessor order: Integer

          attr_accessor title: String

          def initialize: (
            id: String,
            lesson_type: WhopSDK::Models::lesson_types,
            order: Integer,
            title: String
          ) -> void

          def to_hash: -> {
            id: String,
            lesson_type: WhopSDK::Models::lesson_types,
            order: Integer,
            title: String
          }
        end
      end

      type thumbnail =
        {
          id: String,
          content_type: String?,
          filename: String?,
          optimized_url: String?,
          source_url: String?
        }

      class Thumbnail < WhopSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor content_type: String?

        attr_accessor filename: String?

        attr_accessor optimized_url: String?

        attr_accessor source_url: String?

        def initialize: (
          id: String,
          content_type: String?,
          filename: String?,
          optimized_url: String?,
          source_url: String?
        ) -> void

        def to_hash: -> {
          id: String,
          content_type: String?,
          filename: String?,
          optimized_url: String?,
          source_url: String?
        }
      end
    end
  end
end
