module WhopSDK
  module Models
    type course_student_list_params =
      {
        course_id: String,
        after: String,
        before: String,
        first: Integer,
        keyword: String,
        last: Integer
      }
      & WhopSDK::Internal::Type::request_parameters

    class CourseStudentListParams < WhopSDK::Internal::Type::BaseModel
      extend WhopSDK::Internal::Type::RequestParameters::Converter
      include WhopSDK::Internal::Type::RequestParameters

      attr_accessor course_id: String

      attr_reader after: String?

      def after=: (String) -> String

      attr_reader before: String?

      def before=: (String) -> String

      attr_reader first: Integer?

      def first=: (Integer) -> Integer

      attr_reader keyword: String?

      def keyword=: (String) -> String

      attr_reader last: Integer?

      def last=: (Integer) -> Integer

      def initialize: (
        course_id: String,
        ?after: String,
        ?before: String,
        ?first: Integer,
        ?keyword: String,
        ?last: Integer,
        ?request_options: WhopSDK::request_opts
      ) -> void

      def to_hash: -> {
        course_id: String,
        after: String,
        before: String,
        first: Integer,
        keyword: String,
        last: Integer,
        request_options: WhopSDK::RequestOptions
      }
    end
  end
end
