module WhopSDK
  module Models
    type currency =
      :usd
      | :sgd
      | :inr
      | :aud
      | :brl
      | :cad
      | :dkk
      | :eur
      | :nok
      | :gbp
      | :sek
      | :chf
      | :hkd
      | :huf
      | :jpy
      | :mxn
      | :myr
      | :pln
      | :czk
      | :nzd
      | :aed
      | :eth
      | :ape
      | :cop
      | :ron
      | :thb
      | :bgn
      | :idr
      | :dop
      | :php
      | :try
      | :krw
      | :twd
      | :vnd
      | :pkr
      | :clp
      | :uyu
      | :ars
      | :zar
      | :dzd
      | :tnd
      | :mad
      | :kes
      | :kwd
      | :jod
      | :all
      | :xcd
      | :amd
      | :bsd
      | :bhd
      | :bob
      | :bam
      | :khr
      | :crc
      | :xof
      | :egp
      | :etb
      | :gmd
      | :ghs
      | :gtq
      | :gyd
      | :ils
      | :jmd
      | :mop
      | :mga
      | :mur
      | :mdl
      | :mnt
      | :nad
      | :ngn
      | :mkd
      | :omr
      | :pyg
      | :pen
      | :qar
      | :rwf
      | :sar
      | :rsd
      | :lkr
      | :tzs
      | :ttd
      | :uzs
      | :rub
      | :btc
      | :cny

    module Currency
      extend WhopSDK::Internal::Type::Enum

      USD: :usd
      SGD: :sgd
      INR: :inr
      AUD: :aud
      BRL: :brl
      CAD: :cad
      DKK: :dkk
      EUR: :eur
      NOK: :nok
      GBP: :gbp
      SEK: :sek
      CHF: :chf
      HKD: :hkd
      HUF: :huf
      JPY: :jpy
      MXN: :mxn
      MYR: :myr
      PLN: :pln
      CZK: :czk
      NZD: :nzd
      AED: :aed
      ETH: :eth
      APE: :ape
      COP: :cop
      RON: :ron
      THB: :thb
      BGN: :bgn
      IDR: :idr
      DOP: :dop
      PHP: :php
      TRY: :try
      KRW: :krw
      TWD: :twd
      VND: :vnd
      PKR: :pkr
      CLP: :clp
      UYU: :uyu
      ARS: :ars
      ZAR: :zar
      DZD: :dzd
      TND: :tnd
      MAD: :mad
      KES: :kes
      KWD: :kwd
      JOD: :jod
      ALL: :all
      XCD: :xcd
      AMD: :amd
      BSD: :bsd
      BHD: :bhd
      BOB: :bob
      BAM: :bam
      KHR: :khr
      CRC: :crc
      XOF: :xof
      EGP: :egp
      ETB: :etb
      GMD: :gmd
      GHS: :ghs
      GTQ: :gtq
      GYD: :gyd
      ILS: :ils
      JMD: :jmd
      MOP: :mop
      MGA: :mga
      MUR: :mur
      MDL: :mdl
      MNT: :mnt
      NAD: :nad
      NGN: :ngn
      MKD: :mkd
      OMR: :omr
      PYG: :pyg
      PEN: :pen
      QAR: :qar
      RWF: :rwf
      SAR: :sar
      RSD: :rsd
      LKR: :lkr
      TZS: :tzs
      TTD: :ttd
      UZS: :uzs
      RUB: :rub
      BTC: :btc
      CNY: :cny

      def self?.values: -> ::Array[WhopSDK::Models::currency]
    end
  end
end
