module WhopSDK
  module Models
    type deposit_list_response =
      {
        account_id: String,
        bank: ::Array[WhopSDK::Models::DepositListResponse::Bank],
        object: WhopSDK::Models::DepositListResponse::object
      }

    class DepositListResponse < WhopSDK::Internal::Type::BaseModel
      attr_accessor account_id: String

      attr_accessor bank: ::Array[WhopSDK::Models::DepositListResponse::Bank]

      attr_accessor object: WhopSDK::Models::DepositListResponse::object

      def initialize: (
        account_id: String,
        bank: ::Array[WhopSDK::Models::DepositListResponse::Bank],
        object: WhopSDK::Models::DepositListResponse::object
      ) -> void

      def to_hash: -> {
        account_id: String,
        bank: ::Array[WhopSDK::Models::DepositListResponse::Bank],
        object: WhopSDK::Models::DepositListResponse::object
      }

      type bank =
        {
          id: String,
          created_at: Time,
          destination_amount: String?,
          destination_currency: String?,
          source_amount: String,
          source_currency: String,
          status: String
        }

      class Bank < WhopSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor created_at: Time

        attr_accessor destination_amount: String?

        attr_accessor destination_currency: String?

        attr_accessor source_amount: String

        attr_accessor source_currency: String

        attr_accessor status: String

        def initialize: (
          id: String,
          created_at: Time,
          destination_amount: String?,
          destination_currency: String?,
          source_amount: String,
          source_currency: String,
          status: String
        ) -> void

        def to_hash: -> {
          id: String,
          created_at: Time,
          destination_amount: String?,
          destination_currency: String?,
          source_amount: String,
          source_currency: String,
          status: String
        }
      end

      type object = :deposits

      module Object
        extend WhopSDK::Internal::Type::Enum

        DEPOSITS: :deposits

        def self?.values: -> ::Array[WhopSDK::Models::DepositListResponse::object]
      end
    end
  end
end
