module WhopSDK
  module Models
    type dispute_list_params =
      {
        account_id: String,
        after: String,
        before: String,
        created_after: String,
        created_before: String,
        currency: String,
        direction: WhopSDK::Models::DisputeListParams::direction,
        first: Integer,
        last: Integer,
        order: WhopSDK::Models::DisputeListParams::order,
        status: ::Array[WhopSDK::Models::DisputeListParams::status],
        api_version_date: String
      }
      & WhopSDK::Internal::Type::request_parameters

    class DisputeListParams < WhopSDK::Internal::Type::BaseModel
      extend WhopSDK::Internal::Type::RequestParameters::Converter
      include WhopSDK::Internal::Type::RequestParameters

      attr_reader account_id: String?

      def account_id=: (String) -> String

      attr_reader after: String?

      def after=: (String) -> String

      attr_reader before: String?

      def before=: (String) -> String

      attr_reader created_after: String?

      def created_after=: (String) -> String

      attr_reader created_before: String?

      def created_before=: (String) -> String

      attr_reader currency: String?

      def currency=: (String) -> String

      attr_reader direction: WhopSDK::Models::DisputeListParams::direction?

      def direction=: (
        WhopSDK::Models::DisputeListParams::direction
      ) -> WhopSDK::Models::DisputeListParams::direction

      attr_reader first: Integer?

      def first=: (Integer) -> Integer

      attr_reader last: Integer?

      def last=: (Integer) -> Integer

      attr_reader order: WhopSDK::Models::DisputeListParams::order?

      def order=: (
        WhopSDK::Models::DisputeListParams::order
      ) -> WhopSDK::Models::DisputeListParams::order

      attr_reader status: ::Array[WhopSDK::Models::DisputeListParams::status]?

      def status=: (
        ::Array[WhopSDK::Models::DisputeListParams::status]
      ) -> ::Array[WhopSDK::Models::DisputeListParams::status]

      attr_reader api_version_date: String?

      def api_version_date=: (String) -> String

      def initialize: (
        ?account_id: String,
        ?after: String,
        ?before: String,
        ?created_after: String,
        ?created_before: String,
        ?currency: String,
        ?direction: WhopSDK::Models::DisputeListParams::direction,
        ?first: Integer,
        ?last: Integer,
        ?order: WhopSDK::Models::DisputeListParams::order,
        ?status: ::Array[WhopSDK::Models::DisputeListParams::status],
        ?api_version_date: String,
        ?request_options: WhopSDK::request_opts
      ) -> void

      def to_hash: -> {
        account_id: String,
        after: String,
        before: String,
        created_after: String,
        created_before: String,
        currency: String,
        direction: WhopSDK::Models::DisputeListParams::direction,
        first: Integer,
        last: Integer,
        order: WhopSDK::Models::DisputeListParams::order,
        status: ::Array[WhopSDK::Models::DisputeListParams::status],
        api_version_date: String,
        request_options: WhopSDK::RequestOptions
      }

      type direction = :asc | :desc

      module Direction
        extend WhopSDK::Internal::Type::Enum

        ASC: :asc
        DESC: :desc

        def self?.values: -> ::Array[WhopSDK::Models::DisputeListParams::direction]
      end

      type order = :created_at | :amount | :evidence_due_at

      module Order
        extend WhopSDK::Internal::Type::Enum

        CREATED_AT: :created_at
        AMOUNT: :amount
        EVIDENCE_DUE_AT: :evidence_due_at

        def self?.values: -> ::Array[WhopSDK::Models::DisputeListParams::order]
      end

      type status = :needs_response | :under_review | :won | :lost | :closed

      module Status
        extend WhopSDK::Internal::Type::Enum

        NEEDS_RESPONSE: :needs_response
        UNDER_REVIEW: :under_review
        WON: :won
        LOST: :lost
        CLOSED: :closed

        def self?.values: -> ::Array[WhopSDK::Models::DisputeListParams::status]
      end
    end
  end
end
