module WhopSDK
  module Models
    type dispute_list_response =
      {
        id: String,
        amount: Float,
        company: WhopSDK::Models::DisputeListResponse::Company?,
        created_at: Time?,
        currency: WhopSDK::Models::currency,
        editable: bool?,
        needs_response_by: Time?,
        payment: WhopSDK::Models::DisputeListResponse::Payment?,
        plan: WhopSDK::Models::DisputeListResponse::Plan?,
        product: WhopSDK::Models::DisputeListResponse::Product?,
        reason: String?,
        reason_code: String?,
        status: WhopSDK::Models::dispute_statuses,
        visa_rdr: bool
      }

    class DisputeListResponse < WhopSDK::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor amount: Float

      attr_accessor company: WhopSDK::Models::DisputeListResponse::Company?

      attr_accessor created_at: Time?

      attr_accessor currency: WhopSDK::Models::currency

      attr_accessor editable: bool?

      attr_accessor needs_response_by: Time?

      attr_accessor payment: WhopSDK::Models::DisputeListResponse::Payment?

      attr_accessor plan: WhopSDK::Models::DisputeListResponse::Plan?

      attr_accessor product: WhopSDK::Models::DisputeListResponse::Product?

      attr_accessor reason: String?

      attr_accessor reason_code: String?

      attr_accessor status: WhopSDK::Models::dispute_statuses

      attr_accessor visa_rdr: bool

      def initialize: (
        id: String,
        amount: Float,
        company: WhopSDK::Models::DisputeListResponse::Company?,
        created_at: Time?,
        currency: WhopSDK::Models::currency,
        editable: bool?,
        needs_response_by: Time?,
        payment: WhopSDK::Models::DisputeListResponse::Payment?,
        plan: WhopSDK::Models::DisputeListResponse::Plan?,
        product: WhopSDK::Models::DisputeListResponse::Product?,
        reason: String?,
        reason_code: String?,
        status: WhopSDK::Models::dispute_statuses,
        visa_rdr: bool
      ) -> void

      def to_hash: -> {
        id: String,
        amount: Float,
        company: WhopSDK::Models::DisputeListResponse::Company?,
        created_at: Time?,
        currency: WhopSDK::Models::currency,
        editable: bool?,
        needs_response_by: Time?,
        payment: WhopSDK::Models::DisputeListResponse::Payment?,
        plan: WhopSDK::Models::DisputeListResponse::Plan?,
        product: WhopSDK::Models::DisputeListResponse::Product?,
        reason: String?,
        reason_code: String?,
        status: WhopSDK::Models::dispute_statuses,
        visa_rdr: bool
      }

      type company = { id: String, title: String }

      class Company < WhopSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor title: String

        def initialize: (id: String, title: String) -> void

        def to_hash: -> { id: String, title: String }
      end

      type payment =
        {
          id: String,
          payment_instrument: WhopSDK::Models::DisputeListResponse::Payment::PaymentInstrument?
        }

      class Payment < WhopSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor payment_instrument: WhopSDK::Models::DisputeListResponse::Payment::PaymentInstrument?

        def initialize: (
          id: String,
          payment_instrument: WhopSDK::Models::DisputeListResponse::Payment::PaymentInstrument?
        ) -> void

        def to_hash: -> {
          id: String,
          payment_instrument: WhopSDK::Models::DisputeListResponse::Payment::PaymentInstrument?
        }

        type payment_instrument =
          {
            display_name: String,
            icons: WhopSDK::Models::DisputeListResponse::Payment::PaymentInstrument::Icons,
            installment_count: Integer?,
            payment_method_type: String
          }

        class PaymentInstrument < WhopSDK::Internal::Type::BaseModel
          attr_accessor display_name: String

          attr_accessor icons: WhopSDK::Models::DisputeListResponse::Payment::PaymentInstrument::Icons

          attr_accessor installment_count: Integer?

          attr_accessor payment_method_type: String

          def initialize: (
            display_name: String,
            icons: WhopSDK::Models::DisputeListResponse::Payment::PaymentInstrument::Icons,
            installment_count: Integer?,
            payment_method_type: String
          ) -> void

          def to_hash: -> {
            display_name: String,
            icons: WhopSDK::Models::DisputeListResponse::Payment::PaymentInstrument::Icons,
            installment_count: Integer?,
            payment_method_type: String
          }

          type icons =
            {
              square: WhopSDK::Models::DisputeListResponse::Payment::PaymentInstrument::Icons::Square
            }

          class Icons < WhopSDK::Internal::Type::BaseModel
            attr_accessor square: WhopSDK::Models::DisputeListResponse::Payment::PaymentInstrument::Icons::Square

            def initialize: (
              square: WhopSDK::Models::DisputeListResponse::Payment::PaymentInstrument::Icons::Square
            ) -> void

            def to_hash: -> {
              square: WhopSDK::Models::DisputeListResponse::Payment::PaymentInstrument::Icons::Square
            }

            type square =
              {
                dark: WhopSDK::Models::DisputeListResponse::Payment::PaymentInstrument::Icons::Square::Dark,
                light: WhopSDK::Models::DisputeListResponse::Payment::PaymentInstrument::Icons::Square::Light
              }

            class Square < WhopSDK::Internal::Type::BaseModel
              attr_accessor dark: WhopSDK::Models::DisputeListResponse::Payment::PaymentInstrument::Icons::Square::Dark

              attr_accessor light: WhopSDK::Models::DisputeListResponse::Payment::PaymentInstrument::Icons::Square::Light

              def initialize: (
                dark: WhopSDK::Models::DisputeListResponse::Payment::PaymentInstrument::Icons::Square::Dark,
                light: WhopSDK::Models::DisputeListResponse::Payment::PaymentInstrument::Icons::Square::Light
              ) -> void

              def to_hash: -> {
                dark: WhopSDK::Models::DisputeListResponse::Payment::PaymentInstrument::Icons::Square::Dark,
                light: WhopSDK::Models::DisputeListResponse::Payment::PaymentInstrument::Icons::Square::Light
              }

              type dark = { svg: String }

              class Dark < WhopSDK::Internal::Type::BaseModel
                attr_accessor svg: String

                def initialize: (svg: String) -> void

                def to_hash: -> { svg: String }
              end

              type light = { svg: String }

              class Light < WhopSDK::Internal::Type::BaseModel
                attr_accessor svg: String

                def initialize: (svg: String) -> void

                def to_hash: -> { svg: String }
              end
            end
          end
        end
      end

      type plan = { id: String }

      class Plan < WhopSDK::Internal::Type::BaseModel
        attr_accessor id: String

        def initialize: (id: String) -> void

        def to_hash: -> { id: String }
      end

      type product = { id: String, title: String }

      class Product < WhopSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor title: String

        def initialize: (id: String, title: String) -> void

        def to_hash: -> { id: String, title: String }
      end
    end
  end
end
