module WhopSDK
  module Models
    type dispute_update_evidence_params =
      {
        access_activity_log: String?,
        billing_address: String?,
        cancellation_policy_attachment: WhopSDK::Models::DisputeUpdateEvidenceParams::cancellation_policy_attachment?,
        cancellation_policy_disclosure: String?,
        customer_communication_attachment: WhopSDK::Models::DisputeUpdateEvidenceParams::customer_communication_attachment?,
        customer_email_address: String?,
        customer_name: String?,
        notes: String?,
        product_description: String?,
        refund_policy_attachment: WhopSDK::Models::DisputeUpdateEvidenceParams::refund_policy_attachment?,
        refund_policy_disclosure: String?,
        refund_refusal_explanation: String?,
        service_date: String?,
        uncategorized_attachment: WhopSDK::Models::DisputeUpdateEvidenceParams::uncategorized_attachment?
      }
      & WhopSDK::Internal::Type::request_parameters

    class DisputeUpdateEvidenceParams < WhopSDK::Internal::Type::BaseModel
      extend WhopSDK::Internal::Type::RequestParameters::Converter
      include WhopSDK::Internal::Type::RequestParameters

      attr_accessor access_activity_log: String?

      attr_accessor billing_address: String?

      attr_accessor cancellation_policy_attachment: WhopSDK::Models::DisputeUpdateEvidenceParams::cancellation_policy_attachment?

      attr_accessor cancellation_policy_disclosure: String?

      attr_accessor customer_communication_attachment: WhopSDK::Models::DisputeUpdateEvidenceParams::customer_communication_attachment?

      attr_accessor customer_email_address: String?

      attr_accessor customer_name: String?

      attr_accessor notes: String?

      attr_accessor product_description: String?

      attr_accessor refund_policy_attachment: WhopSDK::Models::DisputeUpdateEvidenceParams::refund_policy_attachment?

      attr_accessor refund_policy_disclosure: String?

      attr_accessor refund_refusal_explanation: String?

      attr_accessor service_date: String?

      attr_accessor uncategorized_attachment: WhopSDK::Models::DisputeUpdateEvidenceParams::uncategorized_attachment?

      def initialize: (
        ?access_activity_log: String?,
        ?billing_address: String?,
        ?cancellation_policy_attachment: WhopSDK::Models::DisputeUpdateEvidenceParams::cancellation_policy_attachment?,
        ?cancellation_policy_disclosure: String?,
        ?customer_communication_attachment: WhopSDK::Models::DisputeUpdateEvidenceParams::customer_communication_attachment?,
        ?customer_email_address: String?,
        ?customer_name: String?,
        ?notes: String?,
        ?product_description: String?,
        ?refund_policy_attachment: WhopSDK::Models::DisputeUpdateEvidenceParams::refund_policy_attachment?,
        ?refund_policy_disclosure: String?,
        ?refund_refusal_explanation: String?,
        ?service_date: String?,
        ?uncategorized_attachment: WhopSDK::Models::DisputeUpdateEvidenceParams::uncategorized_attachment?,
        ?request_options: WhopSDK::request_opts
      ) -> void

      def to_hash: -> {
        access_activity_log: String?,
        billing_address: String?,
        cancellation_policy_attachment: WhopSDK::Models::DisputeUpdateEvidenceParams::cancellation_policy_attachment?,
        cancellation_policy_disclosure: String?,
        customer_communication_attachment: WhopSDK::Models::DisputeUpdateEvidenceParams::customer_communication_attachment?,
        customer_email_address: String?,
        customer_name: String?,
        notes: String?,
        product_description: String?,
        refund_policy_attachment: WhopSDK::Models::DisputeUpdateEvidenceParams::refund_policy_attachment?,
        refund_policy_disclosure: String?,
        refund_refusal_explanation: String?,
        service_date: String?,
        uncategorized_attachment: WhopSDK::Models::DisputeUpdateEvidenceParams::uncategorized_attachment?,
        request_options: WhopSDK::RequestOptions
      }

      type cancellation_policy_attachment =
        WhopSDK::DisputeUpdateEvidenceParams::CancellationPolicyAttachment::AttachmentInputWithDirectUploadID
        | WhopSDK::DisputeUpdateEvidenceParams::CancellationPolicyAttachment::AttachmentInputWithID

      module CancellationPolicyAttachment
        extend WhopSDK::Internal::Type::Union

        type attachment_input_with_direct_upload_id =
          { direct_upload_id: String }

        class AttachmentInputWithDirectUploadID < WhopSDK::Internal::Type::BaseModel
          attr_accessor direct_upload_id: String

          def initialize: (direct_upload_id: String) -> void

          def to_hash: -> { direct_upload_id: String }
        end

        type attachment_input_with_id = { id: String }

        class AttachmentInputWithID < WhopSDK::Internal::Type::BaseModel
          attr_accessor id: String

          def initialize: (id: String) -> void

          def to_hash: -> { id: String }
        end

        def self?.variants: -> ::Array[WhopSDK::Models::DisputeUpdateEvidenceParams::cancellation_policy_attachment]
      end

      type customer_communication_attachment =
        WhopSDK::DisputeUpdateEvidenceParams::CustomerCommunicationAttachment::AttachmentInputWithDirectUploadID
        | WhopSDK::DisputeUpdateEvidenceParams::CustomerCommunicationAttachment::AttachmentInputWithID

      module CustomerCommunicationAttachment
        extend WhopSDK::Internal::Type::Union

        type attachment_input_with_direct_upload_id =
          { direct_upload_id: String }

        class AttachmentInputWithDirectUploadID < WhopSDK::Internal::Type::BaseModel
          attr_accessor direct_upload_id: String

          def initialize: (direct_upload_id: String) -> void

          def to_hash: -> { direct_upload_id: String }
        end

        type attachment_input_with_id = { id: String }

        class AttachmentInputWithID < WhopSDK::Internal::Type::BaseModel
          attr_accessor id: String

          def initialize: (id: String) -> void

          def to_hash: -> { id: String }
        end

        def self?.variants: -> ::Array[WhopSDK::Models::DisputeUpdateEvidenceParams::customer_communication_attachment]
      end

      type refund_policy_attachment =
        WhopSDK::DisputeUpdateEvidenceParams::RefundPolicyAttachment::AttachmentInputWithDirectUploadID
        | WhopSDK::DisputeUpdateEvidenceParams::RefundPolicyAttachment::AttachmentInputWithID

      module RefundPolicyAttachment
        extend WhopSDK::Internal::Type::Union

        type attachment_input_with_direct_upload_id =
          { direct_upload_id: String }

        class AttachmentInputWithDirectUploadID < WhopSDK::Internal::Type::BaseModel
          attr_accessor direct_upload_id: String

          def initialize: (direct_upload_id: String) -> void

          def to_hash: -> { direct_upload_id: String }
        end

        type attachment_input_with_id = { id: String }

        class AttachmentInputWithID < WhopSDK::Internal::Type::BaseModel
          attr_accessor id: String

          def initialize: (id: String) -> void

          def to_hash: -> { id: String }
        end

        def self?.variants: -> ::Array[WhopSDK::Models::DisputeUpdateEvidenceParams::refund_policy_attachment]
      end

      type uncategorized_attachment =
        WhopSDK::DisputeUpdateEvidenceParams::UncategorizedAttachment::AttachmentInputWithDirectUploadID
        | WhopSDK::DisputeUpdateEvidenceParams::UncategorizedAttachment::AttachmentInputWithID

      module UncategorizedAttachment
        extend WhopSDK::Internal::Type::Union

        type attachment_input_with_direct_upload_id =
          { direct_upload_id: String }

        class AttachmentInputWithDirectUploadID < WhopSDK::Internal::Type::BaseModel
          attr_accessor direct_upload_id: String

          def initialize: (direct_upload_id: String) -> void

          def to_hash: -> { direct_upload_id: String }
        end

        type attachment_input_with_id = { id: String }

        class AttachmentInputWithID < WhopSDK::Internal::Type::BaseModel
          attr_accessor id: String

          def initialize: (id: String) -> void

          def to_hash: -> { id: String }
        end

        def self?.variants: -> ::Array[WhopSDK::Models::DisputeUpdateEvidenceParams::uncategorized_attachment]
      end
    end
  end
end
