module WhopSDK
  module Models
    type dispute_alert_list_response =
      {
        id: String,
        account_id: String?,
        actionable: bool,
        amount: Float,
        card_brand: String?,
        created_at: String,
        currency: String,
        fee_charged: bool,
        issuer: String?,
        not_actionable_reason: WhopSDK::Models::DisputeAlertListResponse::not_actionable_reason?,
        payment_id: String?,
        product_id: String?,
        reported_at: String,
        transaction_at: String?,
        type: WhopSDK::Models::DisputeAlertListResponse::type_,
        updated_at: String
      }

    class DisputeAlertListResponse < WhopSDK::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor account_id: String?

      attr_accessor actionable: bool

      attr_accessor amount: Float

      attr_accessor card_brand: String?

      attr_accessor created_at: String

      attr_accessor currency: String

      attr_accessor fee_charged: bool

      attr_accessor issuer: String?

      attr_accessor not_actionable_reason: WhopSDK::Models::DisputeAlertListResponse::not_actionable_reason?

      attr_accessor payment_id: String?

      attr_accessor product_id: String?

      attr_accessor reported_at: String

      attr_accessor transaction_at: String?

      attr_accessor type: WhopSDK::Models::DisputeAlertListResponse::type_

      attr_accessor updated_at: String

      def initialize: (
        id: String,
        account_id: String?,
        actionable: bool,
        amount: Float,
        card_brand: String?,
        created_at: String,
        currency: String,
        fee_charged: bool,
        issuer: String?,
        not_actionable_reason: WhopSDK::Models::DisputeAlertListResponse::not_actionable_reason?,
        payment_id: String?,
        product_id: String?,
        reported_at: String,
        transaction_at: String?,
        type: WhopSDK::Models::DisputeAlertListResponse::type_,
        updated_at: String
      ) -> void

      def to_hash: -> {
        id: String,
        account_id: String?,
        actionable: bool,
        amount: Float,
        card_brand: String?,
        created_at: String,
        currency: String,
        fee_charged: bool,
        issuer: String?,
        not_actionable_reason: WhopSDK::Models::DisputeAlertListResponse::not_actionable_reason?,
        payment_id: String?,
        product_id: String?,
        reported_at: String,
        transaction_at: String?,
        type: WhopSDK::Models::DisputeAlertListResponse::type_,
        updated_at: String
      }

      type not_actionable_reason =
        :network_resolved
        | :payment_unmatched
        | :payment_not_captured
        | :payment_disputed
        | :payment_refunded

      module NotActionableReason
        extend WhopSDK::Internal::Type::Enum

        NETWORK_RESOLVED: :network_resolved
        PAYMENT_UNMATCHED: :payment_unmatched
        PAYMENT_NOT_CAPTURED: :payment_not_captured
        PAYMENT_DISPUTED: :payment_disputed
        PAYMENT_REFUNDED: :payment_refunded

        def self?.values: -> ::Array[WhopSDK::Models::DisputeAlertListResponse::not_actionable_reason]
      end

      type type_ =
        :early_fraud_warning | :dispute_alert | :rapid_dispute_resolution

      module Type
        extend WhopSDK::Internal::Type::Enum

        EARLY_FRAUD_WARNING: :early_fraud_warning
        DISPUTE_ALERT: :dispute_alert
        RAPID_DISPUTE_RESOLUTION: :rapid_dispute_resolution

        def self?.values: -> ::Array[WhopSDK::Models::DisputeAlertListResponse::type_]
      end
    end
  end
end
