module WhopSDK
  module Models
    type dispute =
      {
        id: String,
        access_activity_log: String?,
        amount: Float,
        billing_address: String?,
        cancellation_policy_attachment: WhopSDK::Dispute::CancellationPolicyAttachment?,
        cancellation_policy_disclosure: String?,
        company: WhopSDK::Dispute::Company?,
        created_at: Time?,
        currency: WhopSDK::Models::currency,
        customer_communication_attachment: WhopSDK::Dispute::CustomerCommunicationAttachment?,
        customer_email_address: String?,
        customer_name: String?,
        editable: bool?,
        needs_response_by: Time?,
        notes: String?,
        payment: WhopSDK::Dispute::Payment?,
        plan: WhopSDK::Dispute::Plan?,
        product: WhopSDK::Dispute::Product?,
        product_description: String?,
        reason: String?,
        refund_policy_attachment: WhopSDK::Dispute::RefundPolicyAttachment?,
        refund_policy_disclosure: String?,
        refund_refusal_explanation: String?,
        service_date: String?,
        status: WhopSDK::Models::dispute_statuses,
        uncategorized_attachment: WhopSDK::Dispute::UncategorizedAttachment?,
        visa_rdr: bool
      }

    class Dispute < WhopSDK::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor access_activity_log: String?

      attr_accessor amount: Float

      attr_accessor billing_address: String?

      attr_accessor cancellation_policy_attachment: WhopSDK::Dispute::CancellationPolicyAttachment?

      attr_accessor cancellation_policy_disclosure: String?

      attr_accessor company: WhopSDK::Dispute::Company?

      attr_accessor created_at: Time?

      attr_accessor currency: WhopSDK::Models::currency

      attr_accessor customer_communication_attachment: WhopSDK::Dispute::CustomerCommunicationAttachment?

      attr_accessor customer_email_address: String?

      attr_accessor customer_name: String?

      attr_accessor editable: bool?

      attr_accessor needs_response_by: Time?

      attr_accessor notes: String?

      attr_accessor payment: WhopSDK::Dispute::Payment?

      attr_accessor plan: WhopSDK::Dispute::Plan?

      attr_accessor product: WhopSDK::Dispute::Product?

      attr_accessor product_description: String?

      attr_accessor reason: String?

      attr_accessor refund_policy_attachment: WhopSDK::Dispute::RefundPolicyAttachment?

      attr_accessor refund_policy_disclosure: String?

      attr_accessor refund_refusal_explanation: String?

      attr_accessor service_date: String?

      attr_accessor status: WhopSDK::Models::dispute_statuses

      attr_accessor uncategorized_attachment: WhopSDK::Dispute::UncategorizedAttachment?

      attr_accessor visa_rdr: bool

      def initialize: (
        id: String,
        access_activity_log: String?,
        amount: Float,
        billing_address: String?,
        cancellation_policy_attachment: WhopSDK::Dispute::CancellationPolicyAttachment?,
        cancellation_policy_disclosure: String?,
        company: WhopSDK::Dispute::Company?,
        created_at: Time?,
        currency: WhopSDK::Models::currency,
        customer_communication_attachment: WhopSDK::Dispute::CustomerCommunicationAttachment?,
        customer_email_address: String?,
        customer_name: String?,
        editable: bool?,
        needs_response_by: Time?,
        notes: String?,
        payment: WhopSDK::Dispute::Payment?,
        plan: WhopSDK::Dispute::Plan?,
        product: WhopSDK::Dispute::Product?,
        product_description: String?,
        reason: String?,
        refund_policy_attachment: WhopSDK::Dispute::RefundPolicyAttachment?,
        refund_policy_disclosure: String?,
        refund_refusal_explanation: String?,
        service_date: String?,
        status: WhopSDK::Models::dispute_statuses,
        uncategorized_attachment: WhopSDK::Dispute::UncategorizedAttachment?,
        visa_rdr: bool
      ) -> void

      def to_hash: -> {
        id: String,
        access_activity_log: String?,
        amount: Float,
        billing_address: String?,
        cancellation_policy_attachment: WhopSDK::Dispute::CancellationPolicyAttachment?,
        cancellation_policy_disclosure: String?,
        company: WhopSDK::Dispute::Company?,
        created_at: Time?,
        currency: WhopSDK::Models::currency,
        customer_communication_attachment: WhopSDK::Dispute::CustomerCommunicationAttachment?,
        customer_email_address: String?,
        customer_name: String?,
        editable: bool?,
        needs_response_by: Time?,
        notes: String?,
        payment: WhopSDK::Dispute::Payment?,
        plan: WhopSDK::Dispute::Plan?,
        product: WhopSDK::Dispute::Product?,
        product_description: String?,
        reason: String?,
        refund_policy_attachment: WhopSDK::Dispute::RefundPolicyAttachment?,
        refund_policy_disclosure: String?,
        refund_refusal_explanation: String?,
        service_date: String?,
        status: WhopSDK::Models::dispute_statuses,
        uncategorized_attachment: WhopSDK::Dispute::UncategorizedAttachment?,
        visa_rdr: bool
      }

      type cancellation_policy_attachment =
        { id: String, content_type: String?, filename: String?, url: String? }

      class CancellationPolicyAttachment < WhopSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor content_type: String?

        attr_accessor filename: String?

        attr_accessor url: String?

        def initialize: (
          id: String,
          content_type: String?,
          filename: String?,
          url: String?
        ) -> void

        def to_hash: -> {
          id: String,
          content_type: String?,
          filename: String?,
          url: String?
        }
      end

      type company = { id: String, title: String }

      class Company < WhopSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor title: String

        def initialize: (id: String, title: String) -> void

        def to_hash: -> { id: String, title: String }
      end

      type customer_communication_attachment =
        { id: String, content_type: String?, filename: String?, url: String? }

      class CustomerCommunicationAttachment < WhopSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor content_type: String?

        attr_accessor filename: String?

        attr_accessor url: String?

        def initialize: (
          id: String,
          content_type: String?,
          filename: String?,
          url: String?
        ) -> void

        def to_hash: -> {
          id: String,
          content_type: String?,
          filename: String?,
          url: String?
        }
      end

      type payment =
        {
          id: String,
          billing_reason: WhopSDK::Models::billing_reasons?,
          card_brand: WhopSDK::Models::card_brands?,
          :card_last4 => String?,
          created_at: Time,
          currency: WhopSDK::Models::currency?,
          dispute_alerted_at: Time?,
          member: WhopSDK::Dispute::Payment::Member?,
          membership: WhopSDK::Dispute::Payment::Membership?,
          paid_at: Time?,
          payment_method_type: WhopSDK::Models::payment_method_types?,
          subtotal: Float?,
          total: Float?,
          usd_total: Float?,
          user: WhopSDK::Dispute::Payment::User?
        }

      class Payment < WhopSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor billing_reason: WhopSDK::Models::billing_reasons?

        attr_accessor card_brand: WhopSDK::Models::card_brands?

        attr_accessor card_last4: String?

        attr_accessor created_at: Time

        attr_accessor currency: WhopSDK::Models::currency?

        attr_accessor dispute_alerted_at: Time?

        attr_accessor member: WhopSDK::Dispute::Payment::Member?

        attr_accessor membership: WhopSDK::Dispute::Payment::Membership?

        attr_accessor paid_at: Time?

        attr_accessor payment_method_type: WhopSDK::Models::payment_method_types?

        attr_accessor subtotal: Float?

        attr_accessor total: Float?

        attr_accessor usd_total: Float?

        attr_accessor user: WhopSDK::Dispute::Payment::User?

        def initialize: (
          id: String,
          billing_reason: WhopSDK::Models::billing_reasons?,
          card_brand: WhopSDK::Models::card_brands?,
          card_last4: String?,
          created_at: Time,
          currency: WhopSDK::Models::currency?,
          dispute_alerted_at: Time?,
          member: WhopSDK::Dispute::Payment::Member?,
          membership: WhopSDK::Dispute::Payment::Membership?,
          paid_at: Time?,
          payment_method_type: WhopSDK::Models::payment_method_types?,
          subtotal: Float?,
          total: Float?,
          usd_total: Float?,
          user: WhopSDK::Dispute::Payment::User?
        ) -> void

        def to_hash: -> {
          id: String,
          billing_reason: WhopSDK::Models::billing_reasons?,
          card_brand: WhopSDK::Models::card_brands?,
          :card_last4 => String?,
          created_at: Time,
          currency: WhopSDK::Models::currency?,
          dispute_alerted_at: Time?,
          member: WhopSDK::Dispute::Payment::Member?,
          membership: WhopSDK::Dispute::Payment::Membership?,
          paid_at: Time?,
          payment_method_type: WhopSDK::Models::payment_method_types?,
          subtotal: Float?,
          total: Float?,
          usd_total: Float?,
          user: WhopSDK::Dispute::Payment::User?
        }

        type member = { id: String, phone: String? }

        class Member < WhopSDK::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor phone: String?

          def initialize: (id: String, phone: String?) -> void

          def to_hash: -> { id: String, phone: String? }
        end

        type membership =
          { id: String, status: WhopSDK::Models::membership_status }

        class Membership < WhopSDK::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor status: WhopSDK::Models::membership_status

          def initialize: (
            id: String,
            status: WhopSDK::Models::membership_status
          ) -> void

          def to_hash: -> {
            id: String,
            status: WhopSDK::Models::membership_status
          }
        end

        type user =
          { id: String, email: String?, name: String?, username: String }

        class User < WhopSDK::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor email: String?

          attr_accessor name: String?

          attr_accessor username: String

          def initialize: (
            id: String,
            email: String?,
            name: String?,
            username: String
          ) -> void

          def to_hash: -> {
            id: String,
            email: String?,
            name: String?,
            username: String
          }
        end
      end

      type plan = { id: String }

      class Plan < WhopSDK::Internal::Type::BaseModel
        attr_accessor id: String

        def initialize: (id: String) -> void

        def to_hash: -> { id: String }
      end

      type product = { id: String, title: String }

      class Product < WhopSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor title: String

        def initialize: (id: String, title: String) -> void

        def to_hash: -> { id: String, title: String }
      end

      type refund_policy_attachment =
        { id: String, content_type: String?, filename: String?, url: String? }

      class RefundPolicyAttachment < WhopSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor content_type: String?

        attr_accessor filename: String?

        attr_accessor url: String?

        def initialize: (
          id: String,
          content_type: String?,
          filename: String?,
          url: String?
        ) -> void

        def to_hash: -> {
          id: String,
          content_type: String?,
          filename: String?,
          url: String?
        }
      end

      type uncategorized_attachment =
        { id: String, content_type: String?, filename: String?, url: String? }

      class UncategorizedAttachment < WhopSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor content_type: String?

        attr_accessor filename: String?

        attr_accessor url: String?

        def initialize: (
          id: String,
          content_type: String?,
          filename: String?,
          url: String?
        ) -> void

        def to_hash: -> {
          id: String,
          content_type: String?,
          filename: String?,
          url: String?
        }
      end
    end
  end
end
