module WhopSDK
  module Models
    type dm_member_update_response =
      {
        id: String,
        channel_id: String,
        last_viewed_at: String?,
        notification_preference: WhopSDK::Models::DmMemberUpdateResponse::notification_preference,
        status: WhopSDK::Models::DmMemberUpdateResponse::status,
        user_id: String
      }

    class DmMemberUpdateResponse < WhopSDK::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor channel_id: String

      attr_accessor last_viewed_at: String?

      attr_accessor notification_preference: WhopSDK::Models::DmMemberUpdateResponse::notification_preference

      attr_accessor status: WhopSDK::Models::DmMemberUpdateResponse::status

      attr_accessor user_id: String

      def initialize: (
        id: String,
        channel_id: String,
        last_viewed_at: String?,
        notification_preference: WhopSDK::Models::DmMemberUpdateResponse::notification_preference,
        status: WhopSDK::Models::DmMemberUpdateResponse::status,
        user_id: String
      ) -> void

      def to_hash: -> {
        id: String,
        channel_id: String,
        last_viewed_at: String?,
        notification_preference: WhopSDK::Models::DmMemberUpdateResponse::notification_preference,
        status: WhopSDK::Models::DmMemberUpdateResponse::status,
        user_id: String
      }

      type notification_preference = :all | :mentions | :none

      module NotificationPreference
        extend WhopSDK::Internal::Type::Enum

        ALL: :all
        MENTIONS: :mentions
        NONE: :none

        def self?.values: -> ::Array[WhopSDK::Models::DmMemberUpdateResponse::notification_preference]
      end

      type status = :requested | :accepted | :hidden | :closed | :archived

      module Status
        extend WhopSDK::Internal::Type::Enum

        REQUESTED: :requested
        ACCEPTED: :accepted
        HIDDEN: :hidden
        CLOSED: :closed
        ARCHIVED: :archived

        def self?.values: -> ::Array[WhopSDK::Models::DmMemberUpdateResponse::status]
      end
    end
  end
end
