module WhopSDK
  module Models
    type dm_member_list_response =
      {
        id: String,
        channel_id: String,
        last_viewed_at: String?,
        status: WhopSDK::Models::dm_feed_member_statuses,
        user_id: String
      }

    class DmMemberListResponse < WhopSDK::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor channel_id: String

      attr_accessor last_viewed_at: String?

      attr_accessor status: WhopSDK::Models::dm_feed_member_statuses

      attr_accessor user_id: String

      def initialize: (
        id: String,
        channel_id: String,
        last_viewed_at: String?,
        status: WhopSDK::Models::dm_feed_member_statuses,
        user_id: String
      ) -> void

      def to_hash: -> {
        id: String,
        channel_id: String,
        last_viewed_at: String?,
        status: WhopSDK::Models::dm_feed_member_statuses,
        user_id: String
      }
    end
  end
end
