module WhopSDK
  module Models
    type dm_member_update_params =
      {
        notification_preference: WhopSDK::Models::dm_feed_member_notification_preferences?,
        status: WhopSDK::Models::dm_feed_member_statuses?
      }
      & WhopSDK::Internal::Type::request_parameters

    class DmMemberUpdateParams < WhopSDK::Internal::Type::BaseModel
      extend WhopSDK::Internal::Type::RequestParameters::Converter
      include WhopSDK::Internal::Type::RequestParameters

      attr_accessor notification_preference: WhopSDK::Models::dm_feed_member_notification_preferences?

      attr_accessor status: WhopSDK::Models::dm_feed_member_statuses?

      def initialize: (
        ?notification_preference: WhopSDK::Models::dm_feed_member_notification_preferences?,
        ?status: WhopSDK::Models::dm_feed_member_statuses?,
        ?request_options: WhopSDK::request_opts
      ) -> void

      def to_hash: -> {
        notification_preference: WhopSDK::Models::dm_feed_member_notification_preferences?,
        status: WhopSDK::Models::dm_feed_member_statuses?,
        request_options: WhopSDK::RequestOptions
      }
    end
  end
end
