module WhopSDK
  module Models
    type dm_member_update_params =
      {
        notification_preference: WhopSDK::Models::DmMemberUpdateParams::notification_preference?,
        status: WhopSDK::Models::DmMemberUpdateParams::status?
      }
      & WhopSDK::Internal::Type::request_parameters

    class DmMemberUpdateParams < WhopSDK::Internal::Type::BaseModel
      extend WhopSDK::Internal::Type::RequestParameters::Converter
      include WhopSDK::Internal::Type::RequestParameters

      attr_accessor notification_preference: WhopSDK::Models::DmMemberUpdateParams::notification_preference?

      attr_accessor status: WhopSDK::Models::DmMemberUpdateParams::status?

      def initialize: (
        ?notification_preference: WhopSDK::Models::DmMemberUpdateParams::notification_preference?,
        ?status: WhopSDK::Models::DmMemberUpdateParams::status?,
        ?request_options: WhopSDK::request_opts
      ) -> void

      def to_hash: -> {
        notification_preference: WhopSDK::Models::DmMemberUpdateParams::notification_preference?,
        status: WhopSDK::Models::DmMemberUpdateParams::status?,
        request_options: WhopSDK::RequestOptions
      }

      type notification_preference = :all | :mentions | :none

      module NotificationPreference
        extend WhopSDK::Internal::Type::Enum

        ALL: :all
        MENTIONS: :mentions
        NONE: :none

        def self?.values: -> ::Array[WhopSDK::Models::DmMemberUpdateParams::notification_preference]
      end

      type status = :requested | :accepted | :hidden | :closed | :archived

      module Status
        extend WhopSDK::Internal::Type::Enum

        REQUESTED: :requested
        ACCEPTED: :accepted
        HIDDEN: :hidden
        CLOSED: :closed
        ARCHIVED: :archived

        def self?.values: -> ::Array[WhopSDK::Models::DmMemberUpdateParams::status]
      end
    end
  end
end
