module WhopSDK
  module Models
    type experience_create_params =
      {
        account_id: String,
        app_id: String,
        is_public: bool?,
        logo: WhopSDK::ExperienceCreateParams::Logo?,
        name: String?,
        notifications_enabled: bool?,
        section_id: String?
      }
      & WhopSDK::Internal::Type::request_parameters

    class ExperienceCreateParams < WhopSDK::Internal::Type::BaseModel
      extend WhopSDK::Internal::Type::RequestParameters::Converter
      include WhopSDK::Internal::Type::RequestParameters

      attr_accessor account_id: String

      attr_accessor app_id: String

      attr_accessor is_public: bool?

      attr_accessor logo: WhopSDK::ExperienceCreateParams::Logo?

      attr_accessor name: String?

      attr_accessor notifications_enabled: bool?

      attr_accessor section_id: String?

      def initialize: (
        account_id: String,
        app_id: String,
        ?is_public: bool?,
        ?logo: WhopSDK::ExperienceCreateParams::Logo?,
        ?name: String?,
        ?notifications_enabled: bool?,
        ?section_id: String?,
        ?request_options: WhopSDK::request_opts
      ) -> void

      def to_hash: -> {
        account_id: String,
        app_id: String,
        is_public: bool?,
        logo: WhopSDK::ExperienceCreateParams::Logo?,
        name: String?,
        notifications_enabled: bool?,
        section_id: String?,
        request_options: WhopSDK::RequestOptions
      }

      type logo = { id: String }

      class Logo < WhopSDK::Internal::Type::BaseModel
        attr_accessor id: String

        def initialize: (id: String) -> void

        def to_hash: -> { id: String }
      end
    end
  end
end
