module WhopSDK
  module Models
    type experience_create_params =
      { app_id: String, company_id: String, name: String?, section_id: String? }
      & WhopSDK::Internal::Type::request_parameters

    class ExperienceCreateParams < WhopSDK::Internal::Type::BaseModel
      extend WhopSDK::Internal::Type::RequestParameters::Converter
      include WhopSDK::Internal::Type::RequestParameters

      attr_accessor app_id: String

      attr_accessor company_id: String

      attr_accessor name: String?

      attr_accessor section_id: String?

      def initialize: (
        app_id: String,
        company_id: String,
        ?name: String?,
        ?section_id: String?,
        ?request_options: WhopSDK::request_opts
      ) -> void

      def to_hash: -> {
        app_id: String,
        company_id: String,
        name: String?,
        section_id: String?,
        request_options: WhopSDK::RequestOptions
      }
    end
  end
end
