module WhopSDK
  module Models
    type experience_update_params =
      {
        access_level: WhopSDK::Models::ExperienceUpdateParams::access_level?,
        is_public: bool?,
        logo: WhopSDK::Models::ExperienceUpdateParams::logo?,
        name: String?,
        order: String?,
        section_id: String?
      }
      & WhopSDK::Internal::Type::request_parameters

    class ExperienceUpdateParams < WhopSDK::Internal::Type::BaseModel
      extend WhopSDK::Internal::Type::RequestParameters::Converter
      include WhopSDK::Internal::Type::RequestParameters

      attr_accessor access_level: WhopSDK::Models::ExperienceUpdateParams::access_level?

      attr_accessor is_public: bool?

      attr_accessor logo: WhopSDK::Models::ExperienceUpdateParams::logo?

      attr_accessor name: String?

      attr_accessor order: String?

      attr_accessor section_id: String?

      def initialize: (
        ?access_level: WhopSDK::Models::ExperienceUpdateParams::access_level?,
        ?is_public: bool?,
        ?logo: WhopSDK::Models::ExperienceUpdateParams::logo?,
        ?name: String?,
        ?order: String?,
        ?section_id: String?,
        ?request_options: WhopSDK::request_opts
      ) -> void

      def to_hash: -> {
        access_level: WhopSDK::Models::ExperienceUpdateParams::access_level?,
        is_public: bool?,
        logo: WhopSDK::Models::ExperienceUpdateParams::logo?,
        name: String?,
        order: String?,
        section_id: String?,
        request_options: WhopSDK::RequestOptions
      }

      type access_level = :public | :private

      module AccessLevel
        extend WhopSDK::Internal::Type::Enum

        PUBLIC: :public
        PRIVATE: :private

        def self?.values: -> ::Array[WhopSDK::Models::ExperienceUpdateParams::access_level]
      end

      type logo =
        WhopSDK::ExperienceUpdateParams::Logo::AttachmentInputWithDirectUploadID
        | WhopSDK::ExperienceUpdateParams::Logo::AttachmentInputWithID

      module Logo
        extend WhopSDK::Internal::Type::Union

        type attachment_input_with_direct_upload_id =
          { direct_upload_id: String }

        class AttachmentInputWithDirectUploadID < WhopSDK::Internal::Type::BaseModel
          attr_accessor direct_upload_id: String

          def initialize: (direct_upload_id: String) -> void

          def to_hash: -> { direct_upload_id: String }
        end

        type attachment_input_with_id = { id: String }

        class AttachmentInputWithID < WhopSDK::Internal::Type::BaseModel
          attr_accessor id: String

          def initialize: (id: String) -> void

          def to_hash: -> { id: String }
        end

        def self?.variants: -> ::Array[WhopSDK::Models::ExperienceUpdateParams::logo]
      end
    end
  end
end
