module WhopSDK
  module Models
    type experience =
      {
        id: String,
        app: WhopSDK::Experience::App,
        company: WhopSDK::Experience::Company,
        created_at: Time,
        image: WhopSDK::Experience::Image?,
        name: String,
        order: String?,
        products: ::Array[WhopSDK::Experience::Product]
      }

    class Experience < WhopSDK::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor app: WhopSDK::Experience::App

      attr_accessor company: WhopSDK::Experience::Company

      attr_accessor created_at: Time

      attr_accessor image: WhopSDK::Experience::Image?

      attr_accessor name: String

      attr_accessor order: String?

      attr_accessor products: ::Array[WhopSDK::Experience::Product]

      def initialize: (
        id: String,
        app: WhopSDK::Experience::App,
        company: WhopSDK::Experience::Company,
        created_at: Time,
        image: WhopSDK::Experience::Image?,
        name: String,
        order: String?,
        products: ::Array[WhopSDK::Experience::Product]
      ) -> void

      def to_hash: -> {
        id: String,
        app: WhopSDK::Experience::App,
        company: WhopSDK::Experience::Company,
        created_at: Time,
        image: WhopSDK::Experience::Image?,
        name: String,
        order: String?,
        products: ::Array[WhopSDK::Experience::Product]
      }

      type app =
        { id: String, icon: WhopSDK::Experience::App::Icon?, name: String }

      class App < WhopSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor icon: WhopSDK::Experience::App::Icon?

        attr_accessor name: String

        def initialize: (
          id: String,
          icon: WhopSDK::Experience::App::Icon?,
          name: String
        ) -> void

        def to_hash: -> {
          id: String,
          icon: WhopSDK::Experience::App::Icon?,
          name: String
        }

        type icon = { url: String? }

        class Icon < WhopSDK::Internal::Type::BaseModel
          attr_accessor url: String?

          def initialize: (url: String?) -> void

          def to_hash: -> { url: String? }
        end
      end

      type company = { id: String, route: String, title: String }

      class Company < WhopSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor route: String

        attr_accessor title: String

        def initialize: (id: String, route: String, title: String) -> void

        def to_hash: -> { id: String, route: String, title: String }
      end

      type image = { url: String? }

      class Image < WhopSDK::Internal::Type::BaseModel
        attr_accessor url: String?

        def initialize: (url: String?) -> void

        def to_hash: -> { url: String? }
      end

      type product = { id: String, route: String, title: String }

      class Product < WhopSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor route: String

        attr_accessor title: String

        def initialize: (id: String, route: String, title: String) -> void

        def to_hash: -> { id: String, route: String, title: String }
      end
    end
  end
end
