module WhopSDK
  module Models
    type fee_markup_type =
      :crypto_withdrawal_markup
      | :rtp_withdrawal_markup
      | :next_day_bank_withdrawal_markup
      | :bank_wire_withdrawal_markup
      | :digital_wallet_withdrawal_markup

    module FeeMarkupType
      extend WhopSDK::Internal::Type::Enum

      CRYPTO_WITHDRAWAL_MARKUP: :crypto_withdrawal_markup
      RTP_WITHDRAWAL_MARKUP: :rtp_withdrawal_markup
      NEXT_DAY_BANK_WITHDRAWAL_MARKUP: :next_day_bank_withdrawal_markup
      BANK_WIRE_WITHDRAWAL_MARKUP: :bank_wire_withdrawal_markup
      DIGITAL_WALLET_WITHDRAWAL_MARKUP: :digital_wallet_withdrawal_markup

      def self?.values: -> ::Array[WhopSDK::Models::fee_markup_type]
    end
  end
end
