module WhopSDK
  module Models
    type file_create_params =
      { filename: String, visibility: WhopSDK::Models::file_visibility? }
      & WhopSDK::Internal::Type::request_parameters

    class FileCreateParams < WhopSDK::Internal::Type::BaseModel
      extend WhopSDK::Internal::Type::RequestParameters::Converter
      include WhopSDK::Internal::Type::RequestParameters

      attr_accessor filename: String

      attr_accessor visibility: WhopSDK::Models::file_visibility?

      def initialize: (
        filename: String,
        ?visibility: WhopSDK::Models::file_visibility?,
        ?request_options: WhopSDK::request_opts
      ) -> void

      def to_hash: -> {
        filename: String,
        visibility: WhopSDK::Models::file_visibility?,
        request_options: WhopSDK::RequestOptions
      }
    end
  end
end
