module WhopSDK
  module Models
    type file_retrieve_response =
      {
        id: String,
        content_type: String?,
        filename: String?,
        size: String?,
        upload_status: WhopSDK::Models::FileRetrieveResponse::upload_status,
        url: String?
      }

    class FileRetrieveResponse < WhopSDK::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor content_type: String?

      attr_accessor filename: String?

      attr_accessor size: String?

      attr_accessor upload_status: WhopSDK::Models::FileRetrieveResponse::upload_status

      attr_accessor url: String?

      def initialize: (
        id: String,
        content_type: String?,
        filename: String?,
        size: String?,
        upload_status: WhopSDK::Models::FileRetrieveResponse::upload_status,
        url: String?
      ) -> void

      def to_hash: -> {
        id: String,
        content_type: String?,
        filename: String?,
        size: String?,
        upload_status: WhopSDK::Models::FileRetrieveResponse::upload_status,
        url: String?
      }

      type upload_status = :pending | :processing | :ready | :failed

      module UploadStatus
        extend WhopSDK::Internal::Type::Enum

        PENDING: :pending
        PROCESSING: :processing
        READY: :ready
        FAILED: :failed

        def self?.values: -> ::Array[WhopSDK::Models::FileRetrieveResponse::upload_status]
      end
    end
  end
end
