module WhopSDK
  module Models
    type forum_post_create_params =
      {
        experience_id: String,
        attachments: ::Array[WhopSDK::Models::ForumPostCreateParams::attachment]?,
        content: String?,
        is_mention: bool?,
        parent_id: String?,
        paywall_amount: Float?,
        paywall_currency: WhopSDK::Models::currency?,
        pinned: bool?,
        poll: WhopSDK::ForumPostCreateParams::Poll?,
        title: String?
      }
      & WhopSDK::Internal::Type::request_parameters

    class ForumPostCreateParams < WhopSDK::Internal::Type::BaseModel
      extend WhopSDK::Internal::Type::RequestParameters::Converter
      include WhopSDK::Internal::Type::RequestParameters

      attr_accessor experience_id: String

      attr_accessor attachments: ::Array[WhopSDK::Models::ForumPostCreateParams::attachment]?

      attr_accessor content: String?

      attr_accessor is_mention: bool?

      attr_accessor parent_id: String?

      attr_accessor paywall_amount: Float?

      attr_accessor paywall_currency: WhopSDK::Models::currency?

      attr_accessor pinned: bool?

      attr_accessor poll: WhopSDK::ForumPostCreateParams::Poll?

      attr_accessor title: String?

      def initialize: (
        experience_id: String,
        ?attachments: ::Array[WhopSDK::Models::ForumPostCreateParams::attachment]?,
        ?content: String?,
        ?is_mention: bool?,
        ?parent_id: String?,
        ?paywall_amount: Float?,
        ?paywall_currency: WhopSDK::Models::currency?,
        ?pinned: bool?,
        ?poll: WhopSDK::ForumPostCreateParams::Poll?,
        ?title: String?,
        ?request_options: WhopSDK::request_opts
      ) -> void

      def to_hash: -> {
        experience_id: String,
        attachments: ::Array[WhopSDK::Models::ForumPostCreateParams::attachment]?,
        content: String?,
        is_mention: bool?,
        parent_id: String?,
        paywall_amount: Float?,
        paywall_currency: WhopSDK::Models::currency?,
        pinned: bool?,
        poll: WhopSDK::ForumPostCreateParams::Poll?,
        title: String?,
        request_options: WhopSDK::RequestOptions
      }

      type attachment =
        WhopSDK::ForumPostCreateParams::Attachment::DirectUploadID
        | WhopSDK::ForumPostCreateParams::Attachment::ID

      module Attachment
        extend WhopSDK::Internal::Type::Union

        type direct_upload_id = { direct_upload_id: String }

        class DirectUploadID < WhopSDK::Internal::Type::BaseModel
          attr_accessor direct_upload_id: String

          def initialize: (direct_upload_id: String) -> void

          def to_hash: -> { direct_upload_id: String }
        end

        type id = { id: String }

        class ID < WhopSDK::Internal::Type::BaseModel
          attr_accessor id: String

          def initialize: (id: String) -> void

          def to_hash: -> { id: String }
        end

        def self?.variants: -> ::Array[WhopSDK::Models::ForumPostCreateParams::attachment]
      end

      type poll =
        { options: ::Array[WhopSDK::ForumPostCreateParams::Poll::Option] }

      class Poll < WhopSDK::Internal::Type::BaseModel
        attr_accessor options: ::Array[WhopSDK::ForumPostCreateParams::Poll::Option]

        def initialize: (
          options: ::Array[WhopSDK::ForumPostCreateParams::Poll::Option]
        ) -> void

        def to_hash: -> {
          options: ::Array[WhopSDK::ForumPostCreateParams::Poll::Option]
        }

        type option = { id: String, text: String }

        class Option < WhopSDK::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor text: String

          def initialize: (id: String, text: String) -> void

          def to_hash: -> { id: String, text: String }
        end
      end
    end
  end
end
