module WhopSDK
  module Models
    type friendly_receipt_status =
      :drafted
      | :succeeded
      | :incomplete
      | :refunded
      | :price_too_low
      | :uncollectible
      | :canceled
      | :partially_refunded
      | :failed
      | :open_dispute
      | :past_due
      | :auto_refunded
      | :dispute_warning
      | :unresolved
      | :open_resolution
      | :pending
      | :dispute_needs_response
      | :dispute_warning_needs_response
      | :dispute_under_review
      | :dispute_warning_under_review
      | :dispute_lost
      | :dispute_won
      | :dispute_closed
      | :dispute_warning_closed

    module FriendlyReceiptStatus
      extend WhopSDK::Internal::Type::Enum

      DRAFTED: :drafted
      SUCCEEDED: :succeeded
      INCOMPLETE: :incomplete
      REFUNDED: :refunded
      PRICE_TOO_LOW: :price_too_low
      UNCOLLECTIBLE: :uncollectible
      CANCELED: :canceled
      PARTIALLY_REFUNDED: :partially_refunded
      FAILED: :failed
      OPEN_DISPUTE: :open_dispute
      PAST_DUE: :past_due
      AUTO_REFUNDED: :auto_refunded
      DISPUTE_WARNING: :dispute_warning
      UNRESOLVED: :unresolved
      OPEN_RESOLUTION: :open_resolution
      PENDING: :pending
      DISPUTE_NEEDS_RESPONSE: :dispute_needs_response
      DISPUTE_WARNING_NEEDS_RESPONSE: :dispute_warning_needs_response
      DISPUTE_UNDER_REVIEW: :dispute_under_review
      DISPUTE_WARNING_UNDER_REVIEW: :dispute_warning_under_review
      DISPUTE_LOST: :dispute_lost
      DISPUTE_WON: :dispute_won
      DISPUTE_CLOSED: :dispute_closed
      DISPUTE_WARNING_CLOSED: :dispute_warning_closed

      def self?.values: -> ::Array[WhopSDK::Models::friendly_receipt_status]
    end
  end
end
