module WhopSDK
  module Models
    type granularities = :hourly | :daily | :weekly | :monthly

    module Granularities
      extend WhopSDK::Internal::Type::Enum

      HOURLY: :hourly
      DAILY: :daily
      WEEKLY: :weekly
      MONTHLY: :monthly

      def self?.values: -> ::Array[WhopSDK::Models::granularities]
    end
  end
end
