module WhopSDK
  module Models
    type identity_profile_list_params =
      {
        after: String?,
        before: String?,
        company_id: String?,
        first: Integer?,
        last: Integer?,
        profile_type: WhopSDK::Models::identity_profile_kind?,
        status: WhopSDK::Models::identity_profile_status?
      }
      & WhopSDK::Internal::Type::request_parameters

    class IdentityProfileListParams < WhopSDK::Internal::Type::BaseModel
      extend WhopSDK::Internal::Type::RequestParameters::Converter
      include WhopSDK::Internal::Type::RequestParameters

      attr_accessor after: String?

      attr_accessor before: String?

      attr_accessor company_id: String?

      attr_accessor first: Integer?

      attr_accessor last: Integer?

      attr_accessor profile_type: WhopSDK::Models::identity_profile_kind?

      attr_accessor status: WhopSDK::Models::identity_profile_status?

      def initialize: (
        ?after: String?,
        ?before: String?,
        ?company_id: String?,
        ?first: Integer?,
        ?last: Integer?,
        ?profile_type: WhopSDK::Models::identity_profile_kind?,
        ?status: WhopSDK::Models::identity_profile_status?,
        ?request_options: WhopSDK::request_opts
      ) -> void

      def to_hash: -> {
        after: String?,
        before: String?,
        company_id: String?,
        first: Integer?,
        last: Integer?,
        profile_type: WhopSDK::Models::identity_profile_kind?,
        status: WhopSDK::Models::identity_profile_status?,
        request_options: WhopSDK::RequestOptions
      }
    end
  end
end
