module WhopSDK
  module Models
    type identity_profile_updated_webhook_event =
      {
        id: String,
        api_version: :v1,
        data: WhopSDK::IdentityProfileUpdatedWebhookEvent::Data,
        timestamp: Time,
        type: :"identity_profile.updated",
        company_id: String?
      }

    class IdentityProfileUpdatedWebhookEvent < WhopSDK::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor api_version: :v1

      attr_accessor data: WhopSDK::IdentityProfileUpdatedWebhookEvent::Data

      attr_accessor timestamp: Time

      attr_accessor type: :"identity_profile.updated"

      attr_accessor company_id: String?

      def initialize: (
        id: String,
        data: WhopSDK::IdentityProfileUpdatedWebhookEvent::Data,
        timestamp: Time,
        ?company_id: String?,
        ?api_version: :v1,
        ?type: :"identity_profile.updated"
      ) -> void

      def to_hash: -> {
        id: String,
        api_version: :v1,
        data: WhopSDK::IdentityProfileUpdatedWebhookEvent::Data,
        timestamp: Time,
        type: :"identity_profile.updated",
        company_id: String?
      }

      type data =
        {
          id: String,
          business_address: WhopSDK::IdentityProfileUpdatedWebhookEvent::Data::BusinessAddress?,
          business_name: String?,
          business_structure: String?,
          country: String?,
          created_at: Time,
          date_of_birth: String?,
          email: String?,
          first_name: String?,
          last_name: String?,
          linked_companies: ::Array[WhopSDK::IdentityProfileUpdatedWebhookEvent::Data::LinkedCompany],
          personal_address: WhopSDK::IdentityProfileUpdatedWebhookEvent::Data::PersonalAddress?,
          phone: String?,
          profile_type: String,
          status: WhopSDK::Models::IdentityProfileUpdatedWebhookEvent::Data::status,
          updated_at: Time,
          verifications: ::Array[WhopSDK::IdentityProfileUpdatedWebhookEvent::Data::Verification]
        }

      class Data < WhopSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor business_address: WhopSDK::IdentityProfileUpdatedWebhookEvent::Data::BusinessAddress?

        attr_accessor business_name: String?

        attr_accessor business_structure: String?

        attr_accessor country: String?

        attr_accessor created_at: Time

        attr_accessor date_of_birth: String?

        attr_accessor email: String?

        attr_accessor first_name: String?

        attr_accessor last_name: String?

        attr_accessor linked_companies: ::Array[WhopSDK::IdentityProfileUpdatedWebhookEvent::Data::LinkedCompany]

        attr_accessor personal_address: WhopSDK::IdentityProfileUpdatedWebhookEvent::Data::PersonalAddress?

        attr_accessor phone: String?

        attr_accessor profile_type: String

        attr_accessor status: WhopSDK::Models::IdentityProfileUpdatedWebhookEvent::Data::status

        attr_accessor updated_at: Time

        attr_accessor verifications: ::Array[WhopSDK::IdentityProfileUpdatedWebhookEvent::Data::Verification]

        def initialize: (
          id: String,
          business_address: WhopSDK::IdentityProfileUpdatedWebhookEvent::Data::BusinessAddress?,
          business_name: String?,
          business_structure: String?,
          country: String?,
          created_at: Time,
          date_of_birth: String?,
          email: String?,
          first_name: String?,
          last_name: String?,
          linked_companies: ::Array[WhopSDK::IdentityProfileUpdatedWebhookEvent::Data::LinkedCompany],
          personal_address: WhopSDK::IdentityProfileUpdatedWebhookEvent::Data::PersonalAddress?,
          phone: String?,
          profile_type: String,
          status: WhopSDK::Models::IdentityProfileUpdatedWebhookEvent::Data::status,
          updated_at: Time,
          verifications: ::Array[WhopSDK::IdentityProfileUpdatedWebhookEvent::Data::Verification]
        ) -> void

        def to_hash: -> {
          id: String,
          business_address: WhopSDK::IdentityProfileUpdatedWebhookEvent::Data::BusinessAddress?,
          business_name: String?,
          business_structure: String?,
          country: String?,
          created_at: Time,
          date_of_birth: String?,
          email: String?,
          first_name: String?,
          last_name: String?,
          linked_companies: ::Array[WhopSDK::IdentityProfileUpdatedWebhookEvent::Data::LinkedCompany],
          personal_address: WhopSDK::IdentityProfileUpdatedWebhookEvent::Data::PersonalAddress?,
          phone: String?,
          profile_type: String,
          status: WhopSDK::Models::IdentityProfileUpdatedWebhookEvent::Data::status,
          updated_at: Time,
          verifications: ::Array[WhopSDK::IdentityProfileUpdatedWebhookEvent::Data::Verification]
        }

        type business_address =
          {
            city: String?,
            country: String?,
            :line1 => String?,
            :line2 => String?,
            postal_code: String?,
            state: String?
          }

        class BusinessAddress < WhopSDK::Internal::Type::BaseModel
          attr_accessor city: String?

          attr_accessor country: String?

          attr_accessor line1: String?

          attr_accessor line2: String?

          attr_accessor postal_code: String?

          attr_accessor state: String?

          def initialize: (
            city: String?,
            country: String?,
            line1: String?,
            line2: String?,
            postal_code: String?,
            state: String?
          ) -> void

          def to_hash: -> {
            city: String?,
            country: String?,
            :line1 => String?,
            :line2 => String?,
            postal_code: String?,
            state: String?
          }
        end

        type linked_company = { id: String, title: String }

        class LinkedCompany < WhopSDK::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor title: String

          def initialize: (id: String, title: String) -> void

          def to_hash: -> { id: String, title: String }
        end

        type personal_address =
          {
            city: String?,
            country: String?,
            :line1 => String?,
            :line2 => String?,
            postal_code: String?,
            state: String?
          }

        class PersonalAddress < WhopSDK::Internal::Type::BaseModel
          attr_accessor city: String?

          attr_accessor country: String?

          attr_accessor line1: String?

          attr_accessor line2: String?

          attr_accessor postal_code: String?

          attr_accessor state: String?

          def initialize: (
            city: String?,
            country: String?,
            line1: String?,
            line2: String?,
            postal_code: String?,
            state: String?
          ) -> void

          def to_hash: -> {
            city: String?,
            country: String?,
            :line1 => String?,
            :line2 => String?,
            postal_code: String?,
            state: String?
          }
        end

        type status = :not_started | :pending | :approved | :rejected

        module Status
          extend WhopSDK::Internal::Type::Enum

          NOT_STARTED: :not_started
          PENDING: :pending
          APPROVED: :approved
          REJECTED: :rejected

          def self?.values: -> ::Array[WhopSDK::Models::IdentityProfileUpdatedWebhookEvent::Data::status]
        end

        type verification =
          {
            id: String,
            created_at: Time,
            last_error_code: WhopSDK::Models::IdentityProfileUpdatedWebhookEvent::Data::Verification::last_error_code?,
            last_error_reason: String?,
            session_url: String?,
            status: WhopSDK::Models::IdentityProfileUpdatedWebhookEvent::Data::Verification::status
          }

        class Verification < WhopSDK::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor created_at: Time

          attr_accessor last_error_code: WhopSDK::Models::IdentityProfileUpdatedWebhookEvent::Data::Verification::last_error_code?

          attr_accessor last_error_reason: String?

          attr_accessor session_url: String?

          attr_accessor status: WhopSDK::Models::IdentityProfileUpdatedWebhookEvent::Data::Verification::status

          def initialize: (
            id: String,
            created_at: Time,
            last_error_code: WhopSDK::Models::IdentityProfileUpdatedWebhookEvent::Data::Verification::last_error_code?,
            last_error_reason: String?,
            session_url: String?,
            status: WhopSDK::Models::IdentityProfileUpdatedWebhookEvent::Data::Verification::status
          ) -> void

          def to_hash: -> {
            id: String,
            created_at: Time,
            last_error_code: WhopSDK::Models::IdentityProfileUpdatedWebhookEvent::Data::Verification::last_error_code?,
            last_error_reason: String?,
            session_url: String?,
            status: WhopSDK::Models::IdentityProfileUpdatedWebhookEvent::Data::Verification::status
          }

          type last_error_code =
            :abandoned
            | :consent_declined
            | :country_not_supported
            | :device_not_supported
            | :document_expired
            | :document_type_not_supported
            | :document_unverified_other
            | :email_unverified_other
            | :email_verification_declined
            | :id_number_insufficient_document_data
            | :id_number_mismatch
            | :id_number_unverified_other
            | :phone_unverified_other
            | :phone_verification_declined
            | :selfie_document_missing_photo
            | :selfie_face_mismatch
            | :selfie_manipulated
            | :selfie_unverified_other
            | :under_supported_age

          module LastErrorCode
            extend WhopSDK::Internal::Type::Enum

            ABANDONED: :abandoned
            CONSENT_DECLINED: :consent_declined
            COUNTRY_NOT_SUPPORTED: :country_not_supported
            DEVICE_NOT_SUPPORTED: :device_not_supported
            DOCUMENT_EXPIRED: :document_expired
            DOCUMENT_TYPE_NOT_SUPPORTED: :document_type_not_supported
            DOCUMENT_UNVERIFIED_OTHER: :document_unverified_other
            EMAIL_UNVERIFIED_OTHER: :email_unverified_other
            EMAIL_VERIFICATION_DECLINED: :email_verification_declined
            ID_NUMBER_INSUFFICIENT_DOCUMENT_DATA: :id_number_insufficient_document_data
            ID_NUMBER_MISMATCH: :id_number_mismatch
            ID_NUMBER_UNVERIFIED_OTHER: :id_number_unverified_other
            PHONE_UNVERIFIED_OTHER: :phone_unverified_other
            PHONE_VERIFICATION_DECLINED: :phone_verification_declined
            SELFIE_DOCUMENT_MISSING_PHOTO: :selfie_document_missing_photo
            SELFIE_FACE_MISMATCH: :selfie_face_mismatch
            SELFIE_MANIPULATED: :selfie_manipulated
            SELFIE_UNVERIFIED_OTHER: :selfie_unverified_other
            UNDER_SUPPORTED_AGE: :under_supported_age

            def self?.values: -> ::Array[WhopSDK::Models::IdentityProfileUpdatedWebhookEvent::Data::Verification::last_error_code]
          end

          type status =
            :requires_input
            | :processing
            | :verified
            | :canceled
            | :created
            | :started
            | :submitted
            | :approved
            | :declined
            | :resubmission_requested
            | :expired
            | :abandoned
            | :review
            | :action_required

          module Status
            extend WhopSDK::Internal::Type::Enum

            REQUIRES_INPUT: :requires_input
            PROCESSING: :processing
            VERIFIED: :verified
            CANCELED: :canceled
            CREATED: :created
            STARTED: :started
            SUBMITTED: :submitted
            APPROVED: :approved
            DECLINED: :declined
            RESUBMISSION_REQUESTED: :resubmission_requested
            EXPIRED: :expired
            ABANDONED: :abandoned
            REVIEW: :review
            ACTION_REQUIRED: :action_required

            def self?.values: -> ::Array[WhopSDK::Models::IdentityProfileUpdatedWebhookEvent::Data::Verification::status]
          end
        end
      end
    end
  end
end
