module WhopSDK
  module Models
    type identity_profile_create_response =
      {
        id: String,
        created_at: Time,
        last_error_code: WhopSDK::Models::verification_error_code?,
        last_error_reason: String?,
        session_url: String?,
        status: WhopSDK::Models::verification_status
      }

    class IdentityProfileCreateResponse < WhopSDK::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor created_at: Time

      attr_accessor last_error_code: WhopSDK::Models::verification_error_code?

      attr_accessor last_error_reason: String?

      attr_accessor session_url: String?

      attr_accessor status: WhopSDK::Models::verification_status

      def initialize: (
        id: String,
        created_at: Time,
        last_error_code: WhopSDK::Models::verification_error_code?,
        last_error_reason: String?,
        session_url: String?,
        status: WhopSDK::Models::verification_status
      ) -> void

      def to_hash: -> {
        id: String,
        created_at: Time,
        last_error_code: WhopSDK::Models::verification_error_code?,
        last_error_reason: String?,
        session_url: String?,
        status: WhopSDK::Models::verification_status
      }
    end
  end
end
