module WhopSDK
  module Models
    type invoice_status = :open | :paid | :past_due | :void

    module InvoiceStatus
      extend WhopSDK::Internal::Type::Enum

      OPEN: :open
      PAID: :paid
      PAST_DUE: :past_due
      VOID: :void

      def self?.values: -> ::Array[WhopSDK::Models::invoice_status]
    end
  end
end
