module WhopSDK
  module Models
    type languages =
      :en
      | :es
      | :it
      | :pt
      | :de
      | :fr
      | :pl
      | :ru
      | :nl
      | :ca
      | :tr
      | :sv
      | :uk
      | :no
      | :fi
      | :sk
      | :el
      | :cs
      | :hr
      | :da
      | :ro
      | :bg

    module Languages
      extend WhopSDK::Internal::Type::Enum

      EN: :en
      ES: :es
      IT: :it
      PT: :pt
      DE: :de
      FR: :fr
      PL: :pl
      RU: :ru
      NL: :nl
      CA: :ca
      TR: :tr
      SV: :sv
      UK: :uk
      NO: :no
      FI: :fi
      SK: :sk
      EL: :el
      CS: :cs
      HR: :hr
      DA: :da
      RO: :ro
      BG: :bg

      def self?.values: -> ::Array[WhopSDK::Models::languages]
    end
  end
end
