module WhopSDK
  module Models
    type lead_list_params =
      {
        account_id: String,
        after: String,
        before: String,
        created_after: Time,
        created_before: Time,
        first: Integer,
        last: Integer,
        product_ids: ::Array[String]
      }
      & WhopSDK::Internal::Type::request_parameters

    class LeadListParams < WhopSDK::Internal::Type::BaseModel
      extend WhopSDK::Internal::Type::RequestParameters::Converter
      include WhopSDK::Internal::Type::RequestParameters

      attr_accessor account_id: String

      attr_reader after: String?

      def after=: (String) -> String

      attr_reader before: String?

      def before=: (String) -> String

      attr_reader created_after: Time?

      def created_after=: (Time) -> Time

      attr_reader created_before: Time?

      def created_before=: (Time) -> Time

      attr_reader first: Integer?

      def first=: (Integer) -> Integer

      attr_reader last: Integer?

      def last=: (Integer) -> Integer

      attr_reader product_ids: ::Array[String]?

      def product_ids=: (::Array[String]) -> ::Array[String]

      def initialize: (
        account_id: String,
        ?after: String,
        ?before: String,
        ?created_after: Time,
        ?created_before: Time,
        ?first: Integer,
        ?last: Integer,
        ?product_ids: ::Array[String],
        ?request_options: WhopSDK::request_opts
      ) -> void

      def to_hash: -> {
        account_id: String,
        after: String,
        before: String,
        created_after: Time,
        created_before: Time,
        first: Integer,
        last: Integer,
        product_ids: ::Array[String],
        request_options: WhopSDK::RequestOptions
      }
    end
  end
end
