module WhopSDK
  module Models
    type ledger_account_retrieve_response =
      {
        id: String,
        balances: ::Array[WhopSDK::Models::LedgerAccountRetrieveResponse::Balance],
        ledger_account_audit_status: WhopSDK::Models::LedgerAccountRetrieveResponse::ledger_account_audit_status?,
        ledger_type: WhopSDK::Models::LedgerAccountRetrieveResponse::ledger_type,
        owner: WhopSDK::Models::LedgerAccountRetrieveResponse::owner?,
        payments_approval_status: WhopSDK::Models::LedgerAccountRetrieveResponse::payments_approval_status?,
        payout_account_details: WhopSDK::Models::LedgerAccountRetrieveResponse::PayoutAccountDetails?,
        transfer_fee: Float?
      }

    class LedgerAccountRetrieveResponse < WhopSDK::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor balances: ::Array[WhopSDK::Models::LedgerAccountRetrieveResponse::Balance]

      attr_accessor ledger_account_audit_status: WhopSDK::Models::LedgerAccountRetrieveResponse::ledger_account_audit_status?

      attr_accessor ledger_type: WhopSDK::Models::LedgerAccountRetrieveResponse::ledger_type

      attr_accessor owner: WhopSDK::Models::LedgerAccountRetrieveResponse::owner?

      attr_accessor payments_approval_status: WhopSDK::Models::LedgerAccountRetrieveResponse::payments_approval_status?

      attr_accessor payout_account_details: WhopSDK::Models::LedgerAccountRetrieveResponse::PayoutAccountDetails?

      attr_accessor transfer_fee: Float?

      def initialize: (
        id: String,
        balances: ::Array[WhopSDK::Models::LedgerAccountRetrieveResponse::Balance],
        ledger_account_audit_status: WhopSDK::Models::LedgerAccountRetrieveResponse::ledger_account_audit_status?,
        ledger_type: WhopSDK::Models::LedgerAccountRetrieveResponse::ledger_type,
        owner: WhopSDK::Models::LedgerAccountRetrieveResponse::owner?,
        payments_approval_status: WhopSDK::Models::LedgerAccountRetrieveResponse::payments_approval_status?,
        payout_account_details: WhopSDK::Models::LedgerAccountRetrieveResponse::PayoutAccountDetails?,
        transfer_fee: Float?
      ) -> void

      def to_hash: -> {
        id: String,
        balances: ::Array[WhopSDK::Models::LedgerAccountRetrieveResponse::Balance],
        ledger_account_audit_status: WhopSDK::Models::LedgerAccountRetrieveResponse::ledger_account_audit_status?,
        ledger_type: WhopSDK::Models::LedgerAccountRetrieveResponse::ledger_type,
        owner: WhopSDK::Models::LedgerAccountRetrieveResponse::owner?,
        payments_approval_status: WhopSDK::Models::LedgerAccountRetrieveResponse::payments_approval_status?,
        payout_account_details: WhopSDK::Models::LedgerAccountRetrieveResponse::PayoutAccountDetails?,
        transfer_fee: Float?
      }

      type balance =
        {
          balance: Float,
          currency: WhopSDK::Models::currency,
          pending_balance: Float,
          reserve_balance: Float
        }

      class Balance < WhopSDK::Internal::Type::BaseModel
        attr_accessor balance: Float

        attr_accessor currency: WhopSDK::Models::currency

        attr_accessor pending_balance: Float

        attr_accessor reserve_balance: Float

        def initialize: (
          balance: Float,
          currency: WhopSDK::Models::currency,
          pending_balance: Float,
          reserve_balance: Float
        ) -> void

        def to_hash: -> {
          balance: Float,
          currency: WhopSDK::Models::currency,
          pending_balance: Float,
          reserve_balance: Float
        }
      end

      type ledger_account_audit_status =
        :pending
        | :pending_ai_review
        | :approved
        | :reserves_imposed
        | :suspended
        | :ignored
        | :rejected
        | :requested_more_information
        | :information_submitted
        | :requested_tos_violation_correction
        | :clawback_attempted
        | :awaiting_sales_review

      module LedgerAccountAuditStatus
        extend WhopSDK::Internal::Type::Enum

        PENDING: :pending
        PENDING_AI_REVIEW: :pending_ai_review
        APPROVED: :approved
        RESERVES_IMPOSED: :reserves_imposed
        SUSPENDED: :suspended
        IGNORED: :ignored
        REJECTED: :rejected
        REQUESTED_MORE_INFORMATION: :requested_more_information
        INFORMATION_SUBMITTED: :information_submitted
        REQUESTED_TOS_VIOLATION_CORRECTION: :requested_tos_violation_correction
        CLAWBACK_ATTEMPTED: :clawback_attempted
        AWAITING_SALES_REVIEW: :awaiting_sales_review

        def self?.values: -> ::Array[WhopSDK::Models::LedgerAccountRetrieveResponse::ledger_account_audit_status]
      end

      type ledger_type = :primary | :pool

      module LedgerType
        extend WhopSDK::Internal::Type::Enum

        PRIMARY: :primary
        POOL: :pool

        def self?.values: -> ::Array[WhopSDK::Models::LedgerAccountRetrieveResponse::ledger_type]
      end

      type owner =
        (WhopSDK::Models::LedgerAccountRetrieveResponse::Owner::User
        | WhopSDK::Models::LedgerAccountRetrieveResponse::Owner::Company)?

      module Owner
        extend WhopSDK::Internal::Type::Union

        type user =
          { id: String, name: String?, typename: :User, username: String }

        class User < WhopSDK::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor name: String?

          attr_accessor typename: :User

          attr_accessor username: String

          def initialize: (
            id: String,
            name: String?,
            username: String,
            ?typename: :User
          ) -> void

          def to_hash: -> {
            id: String,
            name: String?,
            typename: :User,
            username: String
          }
        end

        type company =
          { id: String, route: String, title: String, typename: :Company }

        class Company < WhopSDK::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor route: String

          attr_accessor title: String

          attr_accessor typename: :Company

          def initialize: (
            id: String,
            route: String,
            title: String,
            ?typename: :Company
          ) -> void

          def to_hash: -> {
            id: String,
            route: String,
            title: String,
            typename: :Company
          }
        end

        def self?.variants: -> ::Array[WhopSDK::Models::LedgerAccountRetrieveResponse::owner]
      end

      type payments_approval_status =
        :pending | :approved | :monitoring | :rejected

      module PaymentsApprovalStatus
        extend WhopSDK::Internal::Type::Enum

        PENDING: :pending
        APPROVED: :approved
        MONITORING: :monitoring
        REJECTED: :rejected

        def self?.values: -> ::Array[WhopSDK::Models::LedgerAccountRetrieveResponse::payments_approval_status]
      end

      type payout_account_details =
        {
          id: String,
          address: WhopSDK::Models::LedgerAccountRetrieveResponse::PayoutAccountDetails::Address?,
          business_name: String?,
          business_representative: WhopSDK::Models::LedgerAccountRetrieveResponse::PayoutAccountDetails::BusinessRepresentative?,
          email: String?,
          latest_verification: WhopSDK::Models::LedgerAccountRetrieveResponse::PayoutAccountDetails::LatestVerification?,
          phone: String?
        }

      class PayoutAccountDetails < WhopSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor address: WhopSDK::Models::LedgerAccountRetrieveResponse::PayoutAccountDetails::Address?

        attr_accessor business_name: String?

        attr_accessor business_representative: WhopSDK::Models::LedgerAccountRetrieveResponse::PayoutAccountDetails::BusinessRepresentative?

        attr_accessor email: String?

        attr_accessor latest_verification: WhopSDK::Models::LedgerAccountRetrieveResponse::PayoutAccountDetails::LatestVerification?

        attr_accessor phone: String?

        def initialize: (
          id: String,
          address: WhopSDK::Models::LedgerAccountRetrieveResponse::PayoutAccountDetails::Address?,
          business_name: String?,
          business_representative: WhopSDK::Models::LedgerAccountRetrieveResponse::PayoutAccountDetails::BusinessRepresentative?,
          email: String?,
          latest_verification: WhopSDK::Models::LedgerAccountRetrieveResponse::PayoutAccountDetails::LatestVerification?,
          phone: String?
        ) -> void

        def to_hash: -> {
          id: String,
          address: WhopSDK::Models::LedgerAccountRetrieveResponse::PayoutAccountDetails::Address?,
          business_name: String?,
          business_representative: WhopSDK::Models::LedgerAccountRetrieveResponse::PayoutAccountDetails::BusinessRepresentative?,
          email: String?,
          latest_verification: WhopSDK::Models::LedgerAccountRetrieveResponse::PayoutAccountDetails::LatestVerification?,
          phone: String?
        }

        type address =
          {
            city: String?,
            country: String?,
            :line1 => String?,
            :line2 => String?,
            postal_code: String?,
            state: String?
          }

        class Address < WhopSDK::Internal::Type::BaseModel
          attr_accessor city: String?

          attr_accessor country: String?

          attr_accessor line1: String?

          attr_accessor line2: String?

          attr_accessor postal_code: String?

          attr_accessor state: String?

          def initialize: (
            city: String?,
            country: String?,
            line1: String?,
            line2: String?,
            postal_code: String?,
            state: String?
          ) -> void

          def to_hash: -> {
            city: String?,
            country: String?,
            :line1 => String?,
            :line2 => String?,
            postal_code: String?,
            state: String?
          }
        end

        type business_representative =
          {
            date_of_birth: String?,
            first_name: String?,
            last_name: String?,
            middle_name: String?
          }

        class BusinessRepresentative < WhopSDK::Internal::Type::BaseModel
          attr_accessor date_of_birth: String?

          attr_accessor first_name: String?

          attr_accessor last_name: String?

          attr_accessor middle_name: String?

          def initialize: (
            date_of_birth: String?,
            first_name: String?,
            last_name: String?,
            middle_name: String?
          ) -> void

          def to_hash: -> {
            date_of_birth: String?,
            first_name: String?,
            last_name: String?,
            middle_name: String?
          }
        end

        type latest_verification =
          {
            id: String,
            last_error_code: WhopSDK::Models::LedgerAccountRetrieveResponse::PayoutAccountDetails::LatestVerification::last_error_code?,
            last_error_reason: String?,
            status: WhopSDK::Models::LedgerAccountRetrieveResponse::PayoutAccountDetails::LatestVerification::status
          }

        class LatestVerification < WhopSDK::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor last_error_code: WhopSDK::Models::LedgerAccountRetrieveResponse::PayoutAccountDetails::LatestVerification::last_error_code?

          attr_accessor last_error_reason: String?

          attr_accessor status: WhopSDK::Models::LedgerAccountRetrieveResponse::PayoutAccountDetails::LatestVerification::status

          def initialize: (
            id: String,
            last_error_code: WhopSDK::Models::LedgerAccountRetrieveResponse::PayoutAccountDetails::LatestVerification::last_error_code?,
            last_error_reason: String?,
            status: WhopSDK::Models::LedgerAccountRetrieveResponse::PayoutAccountDetails::LatestVerification::status
          ) -> void

          def to_hash: -> {
            id: String,
            last_error_code: WhopSDK::Models::LedgerAccountRetrieveResponse::PayoutAccountDetails::LatestVerification::last_error_code?,
            last_error_reason: String?,
            status: WhopSDK::Models::LedgerAccountRetrieveResponse::PayoutAccountDetails::LatestVerification::status
          }

          type last_error_code =
            :abandoned
            | :consent_declined
            | :country_not_supported
            | :device_not_supported
            | :document_expired
            | :document_type_not_supported
            | :document_unverified_other
            | :email_unverified_other
            | :email_verification_declined
            | :id_number_insufficient_document_data
            | :id_number_mismatch
            | :id_number_unverified_other
            | :phone_unverified_other
            | :phone_verification_declined
            | :selfie_document_missing_photo
            | :selfie_face_mismatch
            | :selfie_manipulated
            | :selfie_unverified_other
            | :under_supported_age

          module LastErrorCode
            extend WhopSDK::Internal::Type::Enum

            ABANDONED: :abandoned
            CONSENT_DECLINED: :consent_declined
            COUNTRY_NOT_SUPPORTED: :country_not_supported
            DEVICE_NOT_SUPPORTED: :device_not_supported
            DOCUMENT_EXPIRED: :document_expired
            DOCUMENT_TYPE_NOT_SUPPORTED: :document_type_not_supported
            DOCUMENT_UNVERIFIED_OTHER: :document_unverified_other
            EMAIL_UNVERIFIED_OTHER: :email_unverified_other
            EMAIL_VERIFICATION_DECLINED: :email_verification_declined
            ID_NUMBER_INSUFFICIENT_DOCUMENT_DATA: :id_number_insufficient_document_data
            ID_NUMBER_MISMATCH: :id_number_mismatch
            ID_NUMBER_UNVERIFIED_OTHER: :id_number_unverified_other
            PHONE_UNVERIFIED_OTHER: :phone_unverified_other
            PHONE_VERIFICATION_DECLINED: :phone_verification_declined
            SELFIE_DOCUMENT_MISSING_PHOTO: :selfie_document_missing_photo
            SELFIE_FACE_MISMATCH: :selfie_face_mismatch
            SELFIE_MANIPULATED: :selfie_manipulated
            SELFIE_UNVERIFIED_OTHER: :selfie_unverified_other
            UNDER_SUPPORTED_AGE: :under_supported_age

            def self?.values: -> ::Array[WhopSDK::Models::LedgerAccountRetrieveResponse::PayoutAccountDetails::LatestVerification::last_error_code]
          end

          type status =
            :requires_input
            | :processing
            | :verified
            | :canceled
            | :created
            | :started
            | :submitted
            | :approved
            | :declined
            | :resubmission_requested
            | :expired
            | :abandoned
            | :review

          module Status
            extend WhopSDK::Internal::Type::Enum

            REQUIRES_INPUT: :requires_input
            PROCESSING: :processing
            VERIFIED: :verified
            CANCELED: :canceled
            CREATED: :created
            STARTED: :started
            SUBMITTED: :submitted
            APPROVED: :approved
            DECLINED: :declined
            RESUBMISSION_REQUESTED: :resubmission_requested
            EXPIRED: :expired
            ABANDONED: :abandoned
            REVIEW: :review

            def self?.values: -> ::Array[WhopSDK::Models::LedgerAccountRetrieveResponse::PayoutAccountDetails::LatestVerification::status]
          end
        end
      end
    end
  end
end
