module WhopSDK
  module Models
    type ledger_account_retrieve_response =
      {
        id: String,
        balances: ::Array[WhopSDK::Models::LedgerAccountRetrieveResponse::Balance],
        ledger_account_audit_status: WhopSDK::Models::LedgerAccountRetrieveResponse::ledger_account_audit_status?,
        ledger_type: WhopSDK::Models::LedgerAccountRetrieveResponse::ledger_type,
        owner: WhopSDK::Models::LedgerAccountRetrieveResponse::owner?,
        payments_approval_status: WhopSDK::Models::LedgerAccountRetrieveResponse::payments_approval_status?,
        transfer_fee: Float?
      }

    class LedgerAccountRetrieveResponse < WhopSDK::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor balances: ::Array[WhopSDK::Models::LedgerAccountRetrieveResponse::Balance]

      attr_accessor ledger_account_audit_status: WhopSDK::Models::LedgerAccountRetrieveResponse::ledger_account_audit_status?

      attr_accessor ledger_type: WhopSDK::Models::LedgerAccountRetrieveResponse::ledger_type

      attr_accessor owner: WhopSDK::Models::LedgerAccountRetrieveResponse::owner?

      attr_accessor payments_approval_status: WhopSDK::Models::LedgerAccountRetrieveResponse::payments_approval_status?

      attr_accessor transfer_fee: Float?

      def initialize: (
        id: String,
        balances: ::Array[WhopSDK::Models::LedgerAccountRetrieveResponse::Balance],
        ledger_account_audit_status: WhopSDK::Models::LedgerAccountRetrieveResponse::ledger_account_audit_status?,
        ledger_type: WhopSDK::Models::LedgerAccountRetrieveResponse::ledger_type,
        owner: WhopSDK::Models::LedgerAccountRetrieveResponse::owner?,
        payments_approval_status: WhopSDK::Models::LedgerAccountRetrieveResponse::payments_approval_status?,
        transfer_fee: Float?
      ) -> void

      def to_hash: -> {
        id: String,
        balances: ::Array[WhopSDK::Models::LedgerAccountRetrieveResponse::Balance],
        ledger_account_audit_status: WhopSDK::Models::LedgerAccountRetrieveResponse::ledger_account_audit_status?,
        ledger_type: WhopSDK::Models::LedgerAccountRetrieveResponse::ledger_type,
        owner: WhopSDK::Models::LedgerAccountRetrieveResponse::owner?,
        payments_approval_status: WhopSDK::Models::LedgerAccountRetrieveResponse::payments_approval_status?,
        transfer_fee: Float?
      }

      type balance =
        {
          balance: Float,
          currency: WhopSDK::Models::currency,
          pending_balance: Float,
          reserve_balance: Float
        }

      class Balance < WhopSDK::Internal::Type::BaseModel
        attr_accessor balance: Float

        attr_accessor currency: WhopSDK::Models::currency

        attr_accessor pending_balance: Float

        attr_accessor reserve_balance: Float

        def initialize: (
          balance: Float,
          currency: WhopSDK::Models::currency,
          pending_balance: Float,
          reserve_balance: Float
        ) -> void

        def to_hash: -> {
          balance: Float,
          currency: WhopSDK::Models::currency,
          pending_balance: Float,
          reserve_balance: Float
        }
      end

      type ledger_account_audit_status =
        :reserves_imposed | :requested_more_information

      module LedgerAccountAuditStatus
        extend WhopSDK::Internal::Type::Enum

        RESERVES_IMPOSED: :reserves_imposed
        REQUESTED_MORE_INFORMATION: :requested_more_information

        def self?.values: -> ::Array[WhopSDK::Models::LedgerAccountRetrieveResponse::ledger_account_audit_status]
      end

      type ledger_type = :primary | :pool

      module LedgerType
        extend WhopSDK::Internal::Type::Enum

        PRIMARY: :primary
        POOL: :pool

        def self?.values: -> ::Array[WhopSDK::Models::LedgerAccountRetrieveResponse::ledger_type]
      end

      type owner =
        (WhopSDK::Models::LedgerAccountRetrieveResponse::Owner::User
        | WhopSDK::Models::LedgerAccountRetrieveResponse::Owner::Company)?

      module Owner
        extend WhopSDK::Internal::Type::Union

        type user =
          { id: String, name: String?, typename: :User, username: String }

        class User < WhopSDK::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor name: String?

          attr_accessor typename: :User

          attr_accessor username: String

          def initialize: (
            id: String,
            name: String?,
            username: String,
            ?typename: :User
          ) -> void

          def to_hash: -> {
            id: String,
            name: String?,
            typename: :User,
            username: String
          }
        end

        type company =
          { id: String, route: String, title: String, typename: :Company }

        class Company < WhopSDK::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor route: String

          attr_accessor title: String

          attr_accessor typename: :Company

          def initialize: (
            id: String,
            route: String,
            title: String,
            ?typename: :Company
          ) -> void

          def to_hash: -> {
            id: String,
            route: String,
            title: String,
            typename: :Company
          }
        end

        def self?.variants: -> ::Array[WhopSDK::Models::LedgerAccountRetrieveResponse::owner]
      end

      type payments_approval_status =
        :pending | :approved | :monitoring | :rejected

      module PaymentsApprovalStatus
        extend WhopSDK::Internal::Type::Enum

        PENDING: :pending
        APPROVED: :approved
        MONITORING: :monitoring
        REJECTED: :rejected

        def self?.values: -> ::Array[WhopSDK::Models::LedgerAccountRetrieveResponse::payments_approval_status]
      end
    end
  end
end
