module WhopSDK
  module Models
    type member_most_recent_actions =
      :canceling
      | :churned
      | :finished_split_pay
      | :paused
      | :paid_subscriber
      | :paid_once
      | :expiring
      | :joined
      | :drafted
      | :left
      | :trialing
      | :pending_entry
      | :renewing
      | :past_due

    module MemberMostRecentActions
      extend WhopSDK::Internal::Type::Enum

      CANCELING: :canceling
      CHURNED: :churned
      FINISHED_SPLIT_PAY: :finished_split_pay
      PAUSED: :paused
      PAID_SUBSCRIBER: :paid_subscriber
      PAID_ONCE: :paid_once
      EXPIRING: :expiring
      JOINED: :joined
      DRAFTED: :drafted
      LEFT: :left
      TRIALING: :trialing
      PENDING_ENTRY: :pending_entry
      RENEWING: :renewing
      PAST_DUE: :past_due

      def self?.values: -> ::Array[WhopSDK::Models::member_most_recent_actions]
    end
  end
end
