module WhopSDK
  module Models
    type membership_deactivated_webhook_event =
      {
        id: String,
        api_version: :v1,
        data: WhopSDK::Membership,
        timestamp: Time,
        type: :"membership.deactivated",
        company_id: String?
      }

    class MembershipDeactivatedWebhookEvent < WhopSDK::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor api_version: :v1

      attr_accessor data: WhopSDK::Membership

      attr_accessor timestamp: Time

      attr_accessor type: :"membership.deactivated"

      attr_accessor company_id: String?

      def initialize: (
        id: String,
        data: WhopSDK::Membership,
        timestamp: Time,
        ?company_id: String?,
        ?api_version: :v1,
        ?type: :"membership.deactivated"
      ) -> void

      def to_hash: -> {
        id: String,
        api_version: :v1,
        data: WhopSDK::Membership,
        timestamp: Time,
        type: :"membership.deactivated",
        company_id: String?
      }
    end
  end
end
