module WhopSDK
  module Models
    type membership_add_free_days_response =
      {
        id: String,
        cancel_at_period_end: bool,
        cancel_option: WhopSDK::Models::cancel_options?,
        cancelation_status: WhopSDK::Models::MembershipAddFreeDaysResponse::cancelation_status?,
        canceled_at: Time?,
        cancellation_reason: String?,
        checkout_configuration_id: String?,
        company: WhopSDK::Models::MembershipAddFreeDaysResponse::Company,
        created_at: Time,
        currency: WhopSDK::Models::currency?,
        custom_field_responses: ::Array[WhopSDK::Models::MembershipAddFreeDaysResponse::CustomFieldResponse],
        formatted_renewal_price: String?,
        initial_price_paid: String,
        joined_at: Time?,
        license_key: String?,
        manage_url: String?,
        member: WhopSDK::Models::MembershipAddFreeDaysResponse::Member?,
        metadata: ::Hash[Symbol, top]?,
        payment_collection_paused: bool,
        plan: WhopSDK::Models::MembershipAddFreeDaysResponse::Plan,
        product: WhopSDK::Models::MembershipAddFreeDaysResponse::Product,
        promo_code: WhopSDK::Models::MembershipAddFreeDaysResponse::PromoCode?,
        renewal_period_end: Time?,
        renewal_period_start: Time?,
        status: WhopSDK::Models::membership_status,
        updated_at: Time,
        user: WhopSDK::Models::MembershipAddFreeDaysResponse::User?
      }

    class MembershipAddFreeDaysResponse < WhopSDK::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor cancel_at_period_end: bool

      attr_accessor cancel_option: WhopSDK::Models::cancel_options?

      attr_accessor cancelation_status: WhopSDK::Models::MembershipAddFreeDaysResponse::cancelation_status?

      attr_accessor canceled_at: Time?

      attr_accessor cancellation_reason: String?

      attr_accessor checkout_configuration_id: String?

      attr_accessor company: WhopSDK::Models::MembershipAddFreeDaysResponse::Company

      attr_accessor created_at: Time

      attr_accessor currency: WhopSDK::Models::currency?

      attr_accessor custom_field_responses: ::Array[WhopSDK::Models::MembershipAddFreeDaysResponse::CustomFieldResponse]

      attr_accessor formatted_renewal_price: String?

      attr_accessor initial_price_paid: String

      attr_accessor joined_at: Time?

      attr_accessor license_key: String?

      attr_accessor manage_url: String?

      attr_accessor member: WhopSDK::Models::MembershipAddFreeDaysResponse::Member?

      attr_accessor metadata: ::Hash[Symbol, top]?

      attr_accessor payment_collection_paused: bool

      attr_accessor plan: WhopSDK::Models::MembershipAddFreeDaysResponse::Plan

      attr_accessor product: WhopSDK::Models::MembershipAddFreeDaysResponse::Product

      attr_accessor promo_code: WhopSDK::Models::MembershipAddFreeDaysResponse::PromoCode?

      attr_accessor renewal_period_end: Time?

      attr_accessor renewal_period_start: Time?

      attr_accessor status: WhopSDK::Models::membership_status

      attr_accessor updated_at: Time

      attr_accessor user: WhopSDK::Models::MembershipAddFreeDaysResponse::User?

      def initialize: (
        id: String,
        cancel_at_period_end: bool,
        cancel_option: WhopSDK::Models::cancel_options?,
        cancelation_status: WhopSDK::Models::MembershipAddFreeDaysResponse::cancelation_status?,
        canceled_at: Time?,
        cancellation_reason: String?,
        checkout_configuration_id: String?,
        company: WhopSDK::Models::MembershipAddFreeDaysResponse::Company,
        created_at: Time,
        currency: WhopSDK::Models::currency?,
        custom_field_responses: ::Array[WhopSDK::Models::MembershipAddFreeDaysResponse::CustomFieldResponse],
        formatted_renewal_price: String?,
        initial_price_paid: String,
        joined_at: Time?,
        license_key: String?,
        manage_url: String?,
        member: WhopSDK::Models::MembershipAddFreeDaysResponse::Member?,
        metadata: ::Hash[Symbol, top]?,
        payment_collection_paused: bool,
        plan: WhopSDK::Models::MembershipAddFreeDaysResponse::Plan,
        product: WhopSDK::Models::MembershipAddFreeDaysResponse::Product,
        promo_code: WhopSDK::Models::MembershipAddFreeDaysResponse::PromoCode?,
        renewal_period_end: Time?,
        renewal_period_start: Time?,
        status: WhopSDK::Models::membership_status,
        updated_at: Time,
        user: WhopSDK::Models::MembershipAddFreeDaysResponse::User?
      ) -> void

      def to_hash: -> {
        id: String,
        cancel_at_period_end: bool,
        cancel_option: WhopSDK::Models::cancel_options?,
        cancelation_status: WhopSDK::Models::MembershipAddFreeDaysResponse::cancelation_status?,
        canceled_at: Time?,
        cancellation_reason: String?,
        checkout_configuration_id: String?,
        company: WhopSDK::Models::MembershipAddFreeDaysResponse::Company,
        created_at: Time,
        currency: WhopSDK::Models::currency?,
        custom_field_responses: ::Array[WhopSDK::Models::MembershipAddFreeDaysResponse::CustomFieldResponse],
        formatted_renewal_price: String?,
        initial_price_paid: String,
        joined_at: Time?,
        license_key: String?,
        manage_url: String?,
        member: WhopSDK::Models::MembershipAddFreeDaysResponse::Member?,
        metadata: ::Hash[Symbol, top]?,
        payment_collection_paused: bool,
        plan: WhopSDK::Models::MembershipAddFreeDaysResponse::Plan,
        product: WhopSDK::Models::MembershipAddFreeDaysResponse::Product,
        promo_code: WhopSDK::Models::MembershipAddFreeDaysResponse::PromoCode?,
        renewal_period_end: Time?,
        renewal_period_start: Time?,
        status: WhopSDK::Models::membership_status,
        updated_at: Time,
        user: WhopSDK::Models::MembershipAddFreeDaysResponse::User?
      }

      type cancelation_status = :won_back | :left | :canceling

      module CancelationStatus
        extend WhopSDK::Internal::Type::Enum

        WON_BACK: :won_back
        LEFT: :left
        CANCELING: :canceling

        def self?.values: -> ::Array[WhopSDK::Models::MembershipAddFreeDaysResponse::cancelation_status]
      end

      type company = { id: String, title: String }

      class Company < WhopSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor title: String

        def initialize: (id: String, title: String) -> void

        def to_hash: -> { id: String, title: String }
      end

      type custom_field_response =
        { id: String, answer: String, question: String }

      class CustomFieldResponse < WhopSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor answer: String

        attr_accessor question: String

        def initialize: (id: String, answer: String, question: String) -> void

        def to_hash: -> { id: String, answer: String, question: String }
      end

      type member = { id: String }

      class Member < WhopSDK::Internal::Type::BaseModel
        attr_accessor id: String

        def initialize: (id: String) -> void

        def to_hash: -> { id: String }
      end

      type plan = { id: String, metadata: ::Hash[Symbol, top]? }

      class Plan < WhopSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor metadata: ::Hash[Symbol, top]?

        def initialize: (id: String, metadata: ::Hash[Symbol, top]?) -> void

        def to_hash: -> { id: String, metadata: ::Hash[Symbol, top]? }
      end

      type product =
        { id: String, metadata: ::Hash[Symbol, top]?, title: String }

      class Product < WhopSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor metadata: ::Hash[Symbol, top]?

        attr_accessor title: String

        def initialize: (
          id: String,
          metadata: ::Hash[Symbol, top]?,
          title: String
        ) -> void

        def to_hash: -> {
          id: String,
          metadata: ::Hash[Symbol, top]?,
          title: String
        }
      end

      type promo_code = { id: String }

      class PromoCode < WhopSDK::Internal::Type::BaseModel
        attr_accessor id: String

        def initialize: (id: String) -> void

        def to_hash: -> { id: String }
      end

      type user =
        {
          id: String,
          email: String?,
          name: String?,
          profile_pic: String,
          username: String
        }

      class User < WhopSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor email: String?

        attr_accessor name: String?

        attr_accessor profile_pic: String

        attr_accessor username: String

        def initialize: (
          id: String,
          email: String?,
          name: String?,
          profile_pic: String,
          username: String
        ) -> void

        def to_hash: -> {
          id: String,
          email: String?,
          name: String?,
          profile_pic: String,
          username: String
        }
      end
    end
  end
end
