module WhopSDK
  module Models
    type member_list_params =
      {
        access_level: WhopSDK::Models::access_level,
        after: String,
        before: String,
        company_id: String,
        created_after: Time,
        created_before: Time,
        direction: WhopSDK::Models::direction,
        first: Integer,
        last: Integer,
        most_recent_actions: ::Array[WhopSDK::Models::member_most_recent_actions],
        order: WhopSDK::Models::MemberListParams::order,
        plan_ids: ::Array[String],
        product_ids: ::Array[String],
        promo_code_ids: ::Array[String],
        query: String,
        statuses: ::Array[WhopSDK::Models::member_statuses],
        user_ids: ::Array[String]
      }
      & WhopSDK::Internal::Type::request_parameters

    class MemberListParams < WhopSDK::Internal::Type::BaseModel
      extend WhopSDK::Internal::Type::RequestParameters::Converter
      include WhopSDK::Internal::Type::RequestParameters

      attr_reader access_level: WhopSDK::Models::access_level?

      def access_level=: (
        WhopSDK::Models::access_level
      ) -> WhopSDK::Models::access_level

      attr_reader after: String?

      def after=: (String) -> String

      attr_reader before: String?

      def before=: (String) -> String

      attr_reader company_id: String?

      def company_id=: (String) -> String

      attr_reader created_after: Time?

      def created_after=: (Time) -> Time

      attr_reader created_before: Time?

      def created_before=: (Time) -> Time

      attr_reader direction: WhopSDK::Models::direction?

      def direction=: (WhopSDK::Models::direction) -> WhopSDK::Models::direction

      attr_reader first: Integer?

      def first=: (Integer) -> Integer

      attr_reader last: Integer?

      def last=: (Integer) -> Integer

      attr_reader most_recent_actions: ::Array[WhopSDK::Models::member_most_recent_actions]?

      def most_recent_actions=: (
        ::Array[WhopSDK::Models::member_most_recent_actions]
      ) -> ::Array[WhopSDK::Models::member_most_recent_actions]

      attr_reader order: WhopSDK::Models::MemberListParams::order?

      def order=: (
        WhopSDK::Models::MemberListParams::order
      ) -> WhopSDK::Models::MemberListParams::order

      attr_reader plan_ids: ::Array[String]?

      def plan_ids=: (::Array[String]) -> ::Array[String]

      attr_reader product_ids: ::Array[String]?

      def product_ids=: (::Array[String]) -> ::Array[String]

      attr_reader promo_code_ids: ::Array[String]?

      def promo_code_ids=: (::Array[String]) -> ::Array[String]

      attr_reader query: String?

      def query=: (String) -> String

      attr_reader statuses: ::Array[WhopSDK::Models::member_statuses]?

      def statuses=: (
        ::Array[WhopSDK::Models::member_statuses]
      ) -> ::Array[WhopSDK::Models::member_statuses]

      attr_reader user_ids: ::Array[String]?

      def user_ids=: (::Array[String]) -> ::Array[String]

      def initialize: (
        ?access_level: WhopSDK::Models::access_level,
        ?after: String,
        ?before: String,
        ?company_id: String,
        ?created_after: Time,
        ?created_before: Time,
        ?direction: WhopSDK::Models::direction,
        ?first: Integer,
        ?last: Integer,
        ?most_recent_actions: ::Array[WhopSDK::Models::member_most_recent_actions],
        ?order: WhopSDK::Models::MemberListParams::order,
        ?plan_ids: ::Array[String],
        ?product_ids: ::Array[String],
        ?promo_code_ids: ::Array[String],
        ?query: String,
        ?statuses: ::Array[WhopSDK::Models::member_statuses],
        ?user_ids: ::Array[String],
        ?request_options: WhopSDK::request_opts
      ) -> void

      def to_hash: -> {
        access_level: WhopSDK::Models::access_level,
        after: String,
        before: String,
        company_id: String,
        created_after: Time,
        created_before: Time,
        direction: WhopSDK::Models::direction,
        first: Integer,
        last: Integer,
        most_recent_actions: ::Array[WhopSDK::Models::member_most_recent_actions],
        order: WhopSDK::Models::MemberListParams::order,
        plan_ids: ::Array[String],
        product_ids: ::Array[String],
        promo_code_ids: ::Array[String],
        query: String,
        statuses: ::Array[WhopSDK::Models::member_statuses],
        user_ids: ::Array[String],
        request_options: WhopSDK::RequestOptions
      }

      type order =
        :id | :usd_total_spent | :created_at | :joined_at | :most_recent_action

      module Order
        extend WhopSDK::Internal::Type::Enum

        ID: :id
        USD_TOTAL_SPENT: :usd_total_spent
        CREATED_AT: :created_at
        JOINED_AT: :joined_at
        MOST_RECENT_ACTION: :most_recent_action

        def self?.values: -> ::Array[WhopSDK::Models::MemberListParams::order]
      end
    end
  end
end
