module WhopSDK
  module Models
    type member_list_params =
      {
        access_level: WhopSDK::Models::MemberListParams::access_level,
        account_id: String,
        after: String,
        before: String,
        created_after: String,
        created_before: String,
        direction: WhopSDK::Models::MemberListParams::direction,
        first: Integer,
        last: Integer,
        order: WhopSDK::Models::MemberListParams::order,
        query: String,
        status: WhopSDK::Models::MemberListParams::status,
        user_ids: ::Array[String],
        api_version_date: String
      }
      & WhopSDK::Internal::Type::request_parameters

    class MemberListParams < WhopSDK::Internal::Type::BaseModel
      extend WhopSDK::Internal::Type::RequestParameters::Converter
      include WhopSDK::Internal::Type::RequestParameters

      attr_reader access_level: WhopSDK::Models::MemberListParams::access_level?

      def access_level=: (
        WhopSDK::Models::MemberListParams::access_level
      ) -> WhopSDK::Models::MemberListParams::access_level

      attr_reader account_id: String?

      def account_id=: (String) -> String

      attr_reader after: String?

      def after=: (String) -> String

      attr_reader before: String?

      def before=: (String) -> String

      attr_reader created_after: String?

      def created_after=: (String) -> String

      attr_reader created_before: String?

      def created_before=: (String) -> String

      attr_reader direction: WhopSDK::Models::MemberListParams::direction?

      def direction=: (
        WhopSDK::Models::MemberListParams::direction
      ) -> WhopSDK::Models::MemberListParams::direction

      attr_reader first: Integer?

      def first=: (Integer) -> Integer

      attr_reader last: Integer?

      def last=: (Integer) -> Integer

      attr_reader order: WhopSDK::Models::MemberListParams::order?

      def order=: (
        WhopSDK::Models::MemberListParams::order
      ) -> WhopSDK::Models::MemberListParams::order

      attr_reader query: String?

      def query=: (String) -> String

      attr_reader status: WhopSDK::Models::MemberListParams::status?

      def status=: (
        WhopSDK::Models::MemberListParams::status
      ) -> WhopSDK::Models::MemberListParams::status

      attr_reader user_ids: ::Array[String]?

      def user_ids=: (::Array[String]) -> ::Array[String]

      attr_reader api_version_date: String?

      def api_version_date=: (String) -> String

      def initialize: (
        ?access_level: WhopSDK::Models::MemberListParams::access_level,
        ?account_id: String,
        ?after: String,
        ?before: String,
        ?created_after: String,
        ?created_before: String,
        ?direction: WhopSDK::Models::MemberListParams::direction,
        ?first: Integer,
        ?last: Integer,
        ?order: WhopSDK::Models::MemberListParams::order,
        ?query: String,
        ?status: WhopSDK::Models::MemberListParams::status,
        ?user_ids: ::Array[String],
        ?api_version_date: String,
        ?request_options: WhopSDK::request_opts
      ) -> void

      def to_hash: -> {
        access_level: WhopSDK::Models::MemberListParams::access_level,
        account_id: String,
        after: String,
        before: String,
        created_after: String,
        created_before: String,
        direction: WhopSDK::Models::MemberListParams::direction,
        first: Integer,
        last: Integer,
        order: WhopSDK::Models::MemberListParams::order,
        query: String,
        status: WhopSDK::Models::MemberListParams::status,
        user_ids: ::Array[String],
        api_version_date: String,
        request_options: WhopSDK::RequestOptions
      }

      type access_level = :no_access | :admin | :customer

      module AccessLevel
        extend WhopSDK::Internal::Type::Enum

        NO_ACCESS: :no_access
        ADMIN: :admin
        CUSTOMER: :customer

        def self?.values: -> ::Array[WhopSDK::Models::MemberListParams::access_level]
      end

      type direction = :asc | :desc

      module Direction
        extend WhopSDK::Internal::Type::Enum

        ASC: :asc
        DESC: :desc

        def self?.values: -> ::Array[WhopSDK::Models::MemberListParams::direction]
      end

      type order =
        :created_at | :joined_at | :last_accessed_at | :usd_total_spent

      module Order
        extend WhopSDK::Internal::Type::Enum

        CREATED_AT: :created_at
        JOINED_AT: :joined_at
        LAST_ACCESSED_AT: :last_accessed_at
        USD_TOTAL_SPENT: :usd_total_spent

        def self?.values: -> ::Array[WhopSDK::Models::MemberListParams::order]
      end

      type status = :joined | :left

      module Status
        extend WhopSDK::Internal::Type::Enum

        JOINED: :joined
        LEFT: :left

        def self?.values: -> ::Array[WhopSDK::Models::MemberListParams::status]
      end
    end
  end
end
