module WhopSDK
  module Models
    type membership_list_params =
      {
        after: String,
        before: String,
        cancel_options: ::Array[WhopSDK::Models::cancel_options],
        cancelation_status: WhopSDK::Models::MembershipListParams::cancelation_status,
        company_id: String,
        created_after: Time,
        created_before: Time,
        direction: WhopSDK::Models::direction,
        first: Integer,
        has_cancelation_reason: bool,
        include_text_only_cancelation_reasons: bool,
        last: Integer,
        order: WhopSDK::Models::MembershipListParams::order,
        plan_ids: ::Array[String],
        product_ids: ::Array[String],
        promo_code_ids: ::Array[String],
        statuses: ::Array[WhopSDK::Models::membership_status],
        user_ids: ::Array[String]
      }
      & WhopSDK::Internal::Type::request_parameters

    class MembershipListParams < WhopSDK::Internal::Type::BaseModel
      extend WhopSDK::Internal::Type::RequestParameters::Converter
      include WhopSDK::Internal::Type::RequestParameters

      attr_reader after: String?

      def after=: (String) -> String

      attr_reader before: String?

      def before=: (String) -> String

      attr_reader cancel_options: ::Array[WhopSDK::Models::cancel_options]?

      def cancel_options=: (
        ::Array[WhopSDK::Models::cancel_options]
      ) -> ::Array[WhopSDK::Models::cancel_options]

      attr_reader cancelation_status: WhopSDK::Models::MembershipListParams::cancelation_status?

      def cancelation_status=: (
        WhopSDK::Models::MembershipListParams::cancelation_status
      ) -> WhopSDK::Models::MembershipListParams::cancelation_status

      attr_reader company_id: String?

      def company_id=: (String) -> String

      attr_reader created_after: Time?

      def created_after=: (Time) -> Time

      attr_reader created_before: Time?

      def created_before=: (Time) -> Time

      attr_reader direction: WhopSDK::Models::direction?

      def direction=: (WhopSDK::Models::direction) -> WhopSDK::Models::direction

      attr_reader first: Integer?

      def first=: (Integer) -> Integer

      attr_reader has_cancelation_reason: bool?

      def has_cancelation_reason=: (bool) -> bool

      attr_reader include_text_only_cancelation_reasons: bool?

      def include_text_only_cancelation_reasons=: (bool) -> bool

      attr_reader last: Integer?

      def last=: (Integer) -> Integer

      attr_reader order: WhopSDK::Models::MembershipListParams::order?

      def order=: (
        WhopSDK::Models::MembershipListParams::order
      ) -> WhopSDK::Models::MembershipListParams::order

      attr_reader plan_ids: ::Array[String]?

      def plan_ids=: (::Array[String]) -> ::Array[String]

      attr_reader product_ids: ::Array[String]?

      def product_ids=: (::Array[String]) -> ::Array[String]

      attr_reader promo_code_ids: ::Array[String]?

      def promo_code_ids=: (::Array[String]) -> ::Array[String]

      attr_reader statuses: ::Array[WhopSDK::Models::membership_status]?

      def statuses=: (
        ::Array[WhopSDK::Models::membership_status]
      ) -> ::Array[WhopSDK::Models::membership_status]

      attr_reader user_ids: ::Array[String]?

      def user_ids=: (::Array[String]) -> ::Array[String]

      def initialize: (
        ?after: String,
        ?before: String,
        ?cancel_options: ::Array[WhopSDK::Models::cancel_options],
        ?cancelation_status: WhopSDK::Models::MembershipListParams::cancelation_status,
        ?company_id: String,
        ?created_after: Time,
        ?created_before: Time,
        ?direction: WhopSDK::Models::direction,
        ?first: Integer,
        ?has_cancelation_reason: bool,
        ?include_text_only_cancelation_reasons: bool,
        ?last: Integer,
        ?order: WhopSDK::Models::MembershipListParams::order,
        ?plan_ids: ::Array[String],
        ?product_ids: ::Array[String],
        ?promo_code_ids: ::Array[String],
        ?statuses: ::Array[WhopSDK::Models::membership_status],
        ?user_ids: ::Array[String],
        ?request_options: WhopSDK::request_opts
      ) -> void

      def to_hash: -> {
        after: String,
        before: String,
        cancel_options: ::Array[WhopSDK::Models::cancel_options],
        cancelation_status: WhopSDK::Models::MembershipListParams::cancelation_status,
        company_id: String,
        created_after: Time,
        created_before: Time,
        direction: WhopSDK::Models::direction,
        first: Integer,
        has_cancelation_reason: bool,
        include_text_only_cancelation_reasons: bool,
        last: Integer,
        order: WhopSDK::Models::MembershipListParams::order,
        plan_ids: ::Array[String],
        product_ids: ::Array[String],
        promo_code_ids: ::Array[String],
        statuses: ::Array[WhopSDK::Models::membership_status],
        user_ids: ::Array[String],
        request_options: WhopSDK::RequestOptions
      }

      type cancelation_status = :won_back | :left | :canceling

      module CancelationStatus
        extend WhopSDK::Internal::Type::Enum

        WON_BACK: :won_back
        LEFT: :left
        CANCELING: :canceling

        def self?.values: -> ::Array[WhopSDK::Models::MembershipListParams::cancelation_status]
      end

      type order =
        :id | :created_at | :status | :canceled_at | :date_joined | :total_spend

      module Order
        extend WhopSDK::Internal::Type::Enum

        ID: :id
        CREATED_AT: :created_at
        STATUS: :status
        CANCELED_AT: :canceled_at
        DATE_JOINED: :date_joined
        TOTAL_SPEND: :total_spend

        def self?.values: -> ::Array[WhopSDK::Models::MembershipListParams::order]
      end
    end
  end
end
