module WhopSDK
  module Models
    type member_retrieve_response =
      {
        id: String,
        access_level: WhopSDK::Models::MemberRetrieveResponse::access_level,
        account_id: String,
        created_at: String,
        joined_at: String,
        last_accessed_at: String?,
        phone_number: String?,
        status: WhopSDK::Models::MemberRetrieveResponse::status,
        token_balance: Float,
        user: WhopSDK::Models::MemberRetrieveResponse::User?
      }

    class MemberRetrieveResponse < WhopSDK::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor access_level: WhopSDK::Models::MemberRetrieveResponse::access_level

      attr_accessor account_id: String

      attr_accessor created_at: String

      attr_accessor joined_at: String

      attr_accessor last_accessed_at: String?

      attr_accessor phone_number: String?

      attr_accessor status: WhopSDK::Models::MemberRetrieveResponse::status

      attr_accessor token_balance: Float

      attr_accessor user: WhopSDK::Models::MemberRetrieveResponse::User?

      def initialize: (
        id: String,
        access_level: WhopSDK::Models::MemberRetrieveResponse::access_level,
        account_id: String,
        created_at: String,
        joined_at: String,
        last_accessed_at: String?,
        phone_number: String?,
        status: WhopSDK::Models::MemberRetrieveResponse::status,
        token_balance: Float,
        user: WhopSDK::Models::MemberRetrieveResponse::User?
      ) -> void

      def to_hash: -> {
        id: String,
        access_level: WhopSDK::Models::MemberRetrieveResponse::access_level,
        account_id: String,
        created_at: String,
        joined_at: String,
        last_accessed_at: String?,
        phone_number: String?,
        status: WhopSDK::Models::MemberRetrieveResponse::status,
        token_balance: Float,
        user: WhopSDK::Models::MemberRetrieveResponse::User?
      }

      type access_level = :no_access | :admin | :customer

      module AccessLevel
        extend WhopSDK::Internal::Type::Enum

        NO_ACCESS: :no_access
        ADMIN: :admin
        CUSTOMER: :customer

        def self?.values: -> ::Array[WhopSDK::Models::MemberRetrieveResponse::access_level]
      end

      type status = :joined | :left

      module Status
        extend WhopSDK::Internal::Type::Enum

        JOINED: :joined
        LEFT: :left

        def self?.values: -> ::Array[WhopSDK::Models::MemberRetrieveResponse::status]
      end

      type user =
        {
          id: String,
          name: String?,
          profile_picture: WhopSDK::Models::MemberRetrieveResponse::User::ProfilePicture,
          username: String
        }

      class User < WhopSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor name: String?

        attr_accessor profile_picture: WhopSDK::Models::MemberRetrieveResponse::User::ProfilePicture

        attr_accessor username: String

        def initialize: (
          id: String,
          name: String?,
          profile_picture: WhopSDK::Models::MemberRetrieveResponse::User::ProfilePicture,
          username: String
        ) -> void

        def to_hash: -> {
          id: String,
          name: String?,
          profile_picture: WhopSDK::Models::MemberRetrieveResponse::User::ProfilePicture,
          username: String
        }

        type profile_picture = { url: String }

        class ProfilePicture < WhopSDK::Internal::Type::BaseModel
          attr_accessor url: String

          def initialize: (url: String) -> void

          def to_hash: -> { url: String }
        end
      end
    end
  end
end
