module WhopSDK
  module Models
    type notification_create_params =
      {
        content: String,
        title: String,
        account_id: String,
        experience_id: String,
        icon_user_id: String?,
        rest_path: String?,
        subtitle: String?,
        user_ids: ::Array[String],
        api_version_date: String,
        idempotency_key: String
      }
      & WhopSDK::Internal::Type::request_parameters

    class NotificationCreateParams < WhopSDK::Internal::Type::BaseModel
      extend WhopSDK::Internal::Type::RequestParameters::Converter
      include WhopSDK::Internal::Type::RequestParameters

      attr_accessor content: String

      attr_accessor title: String

      attr_reader account_id: String?

      def account_id=: (String) -> String

      attr_reader experience_id: String?

      def experience_id=: (String) -> String

      attr_accessor icon_user_id: String?

      attr_accessor rest_path: String?

      attr_accessor subtitle: String?

      attr_reader user_ids: ::Array[String]?

      def user_ids=: (::Array[String]) -> ::Array[String]

      attr_reader api_version_date: String?

      def api_version_date=: (String) -> String

      attr_reader idempotency_key: String?

      def idempotency_key=: (String) -> String

      def initialize: (
        content: String,
        title: String,
        ?account_id: String,
        ?experience_id: String,
        ?icon_user_id: String?,
        ?rest_path: String?,
        ?subtitle: String?,
        ?user_ids: ::Array[String],
        ?api_version_date: String,
        ?idempotency_key: String,
        ?request_options: WhopSDK::request_opts
      ) -> void

      def to_hash: -> {
        content: String,
        title: String,
        account_id: String,
        experience_id: String,
        icon_user_id: String?,
        rest_path: String?,
        subtitle: String?,
        user_ids: ::Array[String],
        api_version_date: String,
        idempotency_key: String,
        request_options: WhopSDK::RequestOptions
      }
    end
  end
end
