module WhopSDK
  module Models
    type notification_create_response = { success: bool }

    class NotificationCreateResponse < WhopSDK::Internal::Type::BaseModel
      attr_accessor success: bool

      def initialize: (success: bool) -> void

      def to_hash: -> { success: bool }
    end
  end
end
