module WhopSDK
  module Models
    type payment =
      {
        id: String,
        amount_after_fees: Float,
        application_fee: WhopSDK::Payment::ApplicationFee?,
        auto_refunded: bool,
        billing_address: WhopSDK::Payment::BillingAddress?,
        billing_reason: WhopSDK::Models::billing_reasons?,
        card_brand: WhopSDK::Models::card_brands?,
        :card_last4 => String?,
        company: WhopSDK::Payment::Company?,
        created_at: Time,
        currency: WhopSDK::Models::currency?,
        dispute_alerted_at: Time?,
        disputes: ::Array[WhopSDK::Payment::Dispute]?,
        failure_message: String?,
        financing_installments_count: Integer?,
        financing_transactions: ::Array[WhopSDK::Payment::FinancingTransaction],
        last_payment_attempt: Time?,
        member: WhopSDK::Payment::Member?,
        membership: WhopSDK::Payment::Membership?,
        metadata: ::Hash[Symbol, top]?,
        next_payment_attempt: Time?,
        paid_at: Time?,
        payment_method: WhopSDK::Payment::PaymentMethod?,
        payment_method_type: WhopSDK::Models::payment_method_types?,
        payments_failed: Integer?,
        plan: WhopSDK::Payment::Plan?,
        product: WhopSDK::Payment::Product?,
        promo_code: WhopSDK::Payment::PromoCode?,
        refundable: bool,
        refunded_amount: Float?,
        refunded_at: Time?,
        resolutions: ::Array[WhopSDK::Payment::Resolution]?,
        retryable: bool,
        status: WhopSDK::Models::receipt_status?,
        substatus: WhopSDK::Models::friendly_receipt_status,
        subtotal: Float?,
        tax_amount: Float?,
        tax_behavior: WhopSDK::Models::Payment::tax_behavior?,
        tax_refunded_amount: Float?,
        total: Float?,
        usd_total: Float?,
        user: WhopSDK::Payment::User?,
        voidable: bool
      }

    class Payment < WhopSDK::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor amount_after_fees: Float

      attr_accessor application_fee: WhopSDK::Payment::ApplicationFee?

      attr_accessor auto_refunded: bool

      attr_accessor billing_address: WhopSDK::Payment::BillingAddress?

      attr_accessor billing_reason: WhopSDK::Models::billing_reasons?

      attr_accessor card_brand: WhopSDK::Models::card_brands?

      attr_accessor card_last4: String?

      attr_accessor company: WhopSDK::Payment::Company?

      attr_accessor created_at: Time

      attr_accessor currency: WhopSDK::Models::currency?

      attr_accessor dispute_alerted_at: Time?

      attr_accessor disputes: ::Array[WhopSDK::Payment::Dispute]?

      attr_accessor failure_message: String?

      attr_accessor financing_installments_count: Integer?

      attr_accessor financing_transactions: ::Array[WhopSDK::Payment::FinancingTransaction]

      attr_accessor last_payment_attempt: Time?

      attr_accessor member: WhopSDK::Payment::Member?

      attr_accessor membership: WhopSDK::Payment::Membership?

      attr_accessor metadata: ::Hash[Symbol, top]?

      attr_accessor next_payment_attempt: Time?

      attr_accessor paid_at: Time?

      attr_accessor payment_method: WhopSDK::Payment::PaymentMethod?

      attr_accessor payment_method_type: WhopSDK::Models::payment_method_types?

      attr_accessor payments_failed: Integer?

      attr_accessor plan: WhopSDK::Payment::Plan?

      attr_accessor product: WhopSDK::Payment::Product?

      attr_accessor promo_code: WhopSDK::Payment::PromoCode?

      attr_accessor refundable: bool

      attr_accessor refunded_amount: Float?

      attr_accessor refunded_at: Time?

      attr_accessor resolutions: ::Array[WhopSDK::Payment::Resolution]?

      attr_accessor retryable: bool

      attr_accessor status: WhopSDK::Models::receipt_status?

      attr_accessor substatus: WhopSDK::Models::friendly_receipt_status

      attr_accessor subtotal: Float?

      attr_accessor tax_amount: Float?

      attr_accessor tax_behavior: WhopSDK::Models::Payment::tax_behavior?

      attr_accessor tax_refunded_amount: Float?

      attr_accessor total: Float?

      attr_accessor usd_total: Float?

      attr_accessor user: WhopSDK::Payment::User?

      attr_accessor voidable: bool

      def initialize: (
        id: String,
        amount_after_fees: Float,
        application_fee: WhopSDK::Payment::ApplicationFee?,
        auto_refunded: bool,
        billing_address: WhopSDK::Payment::BillingAddress?,
        billing_reason: WhopSDK::Models::billing_reasons?,
        card_brand: WhopSDK::Models::card_brands?,
        card_last4: String?,
        company: WhopSDK::Payment::Company?,
        created_at: Time,
        currency: WhopSDK::Models::currency?,
        dispute_alerted_at: Time?,
        disputes: ::Array[WhopSDK::Payment::Dispute]?,
        failure_message: String?,
        financing_installments_count: Integer?,
        financing_transactions: ::Array[WhopSDK::Payment::FinancingTransaction],
        last_payment_attempt: Time?,
        member: WhopSDK::Payment::Member?,
        membership: WhopSDK::Payment::Membership?,
        metadata: ::Hash[Symbol, top]?,
        next_payment_attempt: Time?,
        paid_at: Time?,
        payment_method: WhopSDK::Payment::PaymentMethod?,
        payment_method_type: WhopSDK::Models::payment_method_types?,
        payments_failed: Integer?,
        plan: WhopSDK::Payment::Plan?,
        product: WhopSDK::Payment::Product?,
        promo_code: WhopSDK::Payment::PromoCode?,
        refundable: bool,
        refunded_amount: Float?,
        refunded_at: Time?,
        resolutions: ::Array[WhopSDK::Payment::Resolution]?,
        retryable: bool,
        status: WhopSDK::Models::receipt_status?,
        substatus: WhopSDK::Models::friendly_receipt_status,
        subtotal: Float?,
        tax_amount: Float?,
        tax_behavior: WhopSDK::Models::Payment::tax_behavior?,
        tax_refunded_amount: Float?,
        total: Float?,
        usd_total: Float?,
        user: WhopSDK::Payment::User?,
        voidable: bool
      ) -> void

      def to_hash: -> {
        id: String,
        amount_after_fees: Float,
        application_fee: WhopSDK::Payment::ApplicationFee?,
        auto_refunded: bool,
        billing_address: WhopSDK::Payment::BillingAddress?,
        billing_reason: WhopSDK::Models::billing_reasons?,
        card_brand: WhopSDK::Models::card_brands?,
        :card_last4 => String?,
        company: WhopSDK::Payment::Company?,
        created_at: Time,
        currency: WhopSDK::Models::currency?,
        dispute_alerted_at: Time?,
        disputes: ::Array[WhopSDK::Payment::Dispute]?,
        failure_message: String?,
        financing_installments_count: Integer?,
        financing_transactions: ::Array[WhopSDK::Payment::FinancingTransaction],
        last_payment_attempt: Time?,
        member: WhopSDK::Payment::Member?,
        membership: WhopSDK::Payment::Membership?,
        metadata: ::Hash[Symbol, top]?,
        next_payment_attempt: Time?,
        paid_at: Time?,
        payment_method: WhopSDK::Payment::PaymentMethod?,
        payment_method_type: WhopSDK::Models::payment_method_types?,
        payments_failed: Integer?,
        plan: WhopSDK::Payment::Plan?,
        product: WhopSDK::Payment::Product?,
        promo_code: WhopSDK::Payment::PromoCode?,
        refundable: bool,
        refunded_amount: Float?,
        refunded_at: Time?,
        resolutions: ::Array[WhopSDK::Payment::Resolution]?,
        retryable: bool,
        status: WhopSDK::Models::receipt_status?,
        substatus: WhopSDK::Models::friendly_receipt_status,
        subtotal: Float?,
        tax_amount: Float?,
        tax_behavior: WhopSDK::Models::Payment::tax_behavior?,
        tax_refunded_amount: Float?,
        total: Float?,
        usd_total: Float?,
        user: WhopSDK::Payment::User?,
        voidable: bool
      }

      type application_fee =
        {
          id: String,
          amount: Float,
          amount_captured: Float,
          amount_refunded: Float,
          created_at: Time,
          currency: WhopSDK::Models::currency
        }

      class ApplicationFee < WhopSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor amount: Float

        attr_accessor amount_captured: Float

        attr_accessor amount_refunded: Float

        attr_accessor created_at: Time

        attr_accessor currency: WhopSDK::Models::currency

        def initialize: (
          id: String,
          amount: Float,
          amount_captured: Float,
          amount_refunded: Float,
          created_at: Time,
          currency: WhopSDK::Models::currency
        ) -> void

        def to_hash: -> {
          id: String,
          amount: Float,
          amount_captured: Float,
          amount_refunded: Float,
          created_at: Time,
          currency: WhopSDK::Models::currency
        }
      end

      type billing_address =
        {
          city: String?,
          country: String?,
          :line1 => String?,
          :line2 => String?,
          name: String?,
          postal_code: String?,
          state: String?
        }

      class BillingAddress < WhopSDK::Internal::Type::BaseModel
        attr_accessor city: String?

        attr_accessor country: String?

        attr_accessor line1: String?

        attr_accessor line2: String?

        attr_accessor name: String?

        attr_accessor postal_code: String?

        attr_accessor state: String?

        def initialize: (
          city: String?,
          country: String?,
          line1: String?,
          line2: String?,
          name: String?,
          postal_code: String?,
          state: String?
        ) -> void

        def to_hash: -> {
          city: String?,
          country: String?,
          :line1 => String?,
          :line2 => String?,
          name: String?,
          postal_code: String?,
          state: String?
        }
      end

      type company = { id: String, route: String, title: String }

      class Company < WhopSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor route: String

        attr_accessor title: String

        def initialize: (id: String, route: String, title: String) -> void

        def to_hash: -> { id: String, route: String, title: String }
      end

      type dispute =
        {
          id: String,
          amount: Float,
          currency: WhopSDK::Models::currency,
          editable: bool?,
          needs_response_by: Time?,
          notes: String?,
          reason: String?,
          status: WhopSDK::Models::dispute_statuses
        }

      class Dispute < WhopSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor amount: Float

        attr_accessor currency: WhopSDK::Models::currency

        attr_accessor editable: bool?

        attr_accessor needs_response_by: Time?

        attr_accessor notes: String?

        attr_accessor reason: String?

        attr_accessor status: WhopSDK::Models::dispute_statuses

        def initialize: (
          id: String,
          amount: Float,
          currency: WhopSDK::Models::currency,
          editable: bool?,
          needs_response_by: Time?,
          notes: String?,
          reason: String?,
          status: WhopSDK::Models::dispute_statuses
        ) -> void

        def to_hash: -> {
          id: String,
          amount: Float,
          currency: WhopSDK::Models::currency,
          editable: bool?,
          needs_response_by: Time?,
          notes: String?,
          reason: String?,
          status: WhopSDK::Models::dispute_statuses
        }
      end

      type financing_transaction =
        {
          id: String,
          amount: Float,
          created_at: Time,
          status: WhopSDK::Models::Payment::FinancingTransaction::status,
          transaction_type: WhopSDK::Models::Payment::FinancingTransaction::transaction_type
        }

      class FinancingTransaction < WhopSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor amount: Float

        attr_accessor created_at: Time

        attr_accessor status: WhopSDK::Models::Payment::FinancingTransaction::status

        attr_accessor transaction_type: WhopSDK::Models::Payment::FinancingTransaction::transaction_type

        def initialize: (
          id: String,
          amount: Float,
          created_at: Time,
          status: WhopSDK::Models::Payment::FinancingTransaction::status,
          transaction_type: WhopSDK::Models::Payment::FinancingTransaction::transaction_type
        ) -> void

        def to_hash: -> {
          id: String,
          amount: Float,
          created_at: Time,
          status: WhopSDK::Models::Payment::FinancingTransaction::status,
          transaction_type: WhopSDK::Models::Payment::FinancingTransaction::transaction_type
        }

        type status =
          :succeeded
          | :declined
          | :error
          | :pending
          | :created
          | :expired
          | :won
          | :rejected
          | :lost
          | :prevented

        module Status
          extend WhopSDK::Internal::Type::Enum

          SUCCEEDED: :succeeded
          DECLINED: :declined
          ERROR: :error
          PENDING: :pending
          CREATED: :created
          EXPIRED: :expired
          WON: :won
          REJECTED: :rejected
          LOST: :lost
          PREVENTED: :prevented

          def self?.values: -> ::Array[WhopSDK::Models::Payment::FinancingTransaction::status]
        end

        type transaction_type =
          :purchase
          | :authorize
          | :capture
          | :refund
          | :cancel
          | :verify
          | :chargeback
          | :three_d_secure
          | :fraud_screening
          | :authorization
          | :installment

        module TransactionType
          extend WhopSDK::Internal::Type::Enum

          PURCHASE: :purchase
          AUTHORIZE: :authorize
          CAPTURE: :capture
          REFUND: :refund
          CANCEL: :cancel
          VERIFY: :verify
          CHARGEBACK: :chargeback
          THREE_D_SECURE: :three_d_secure
          FRAUD_SCREENING: :fraud_screening
          AUTHORIZATION: :authorization
          INSTALLMENT: :installment

          def self?.values: -> ::Array[WhopSDK::Models::Payment::FinancingTransaction::transaction_type]
        end
      end

      type member = { id: String, phone: String? }

      class Member < WhopSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor phone: String?

        def initialize: (id: String, phone: String?) -> void

        def to_hash: -> { id: String, phone: String? }
      end

      type membership =
        { id: String, status: WhopSDK::Models::membership_status }

      class Membership < WhopSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor status: WhopSDK::Models::membership_status

        def initialize: (
          id: String,
          status: WhopSDK::Models::membership_status
        ) -> void

        def to_hash: -> {
          id: String,
          status: WhopSDK::Models::membership_status
        }
      end

      type payment_method =
        {
          id: String,
          card: WhopSDK::Payment::PaymentMethod::Card?,
          created_at: Time,
          payment_method_type: WhopSDK::Models::payment_method_types
        }

      class PaymentMethod < WhopSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor card: WhopSDK::Payment::PaymentMethod::Card?

        attr_accessor created_at: Time

        attr_accessor payment_method_type: WhopSDK::Models::payment_method_types

        def initialize: (
          id: String,
          card: WhopSDK::Payment::PaymentMethod::Card?,
          created_at: Time,
          payment_method_type: WhopSDK::Models::payment_method_types
        ) -> void

        def to_hash: -> {
          id: String,
          card: WhopSDK::Payment::PaymentMethod::Card?,
          created_at: Time,
          payment_method_type: WhopSDK::Models::payment_method_types
        }

        type card =
          {
            brand: WhopSDK::Models::card_brands?,
            exp_month: Integer?,
            exp_year: Integer?,
            :last4 => String?
          }

        class Card < WhopSDK::Internal::Type::BaseModel
          attr_accessor brand: WhopSDK::Models::card_brands?

          attr_accessor exp_month: Integer?

          attr_accessor exp_year: Integer?

          attr_accessor last4: String?

          def initialize: (
            brand: WhopSDK::Models::card_brands?,
            exp_month: Integer?,
            exp_year: Integer?,
            last4: String?
          ) -> void

          def to_hash: -> {
            brand: WhopSDK::Models::card_brands?,
            exp_month: Integer?,
            exp_year: Integer?,
            :last4 => String?
          }
        end
      end

      type plan = { id: String }

      class Plan < WhopSDK::Internal::Type::BaseModel
        attr_accessor id: String

        def initialize: (id: String) -> void

        def to_hash: -> { id: String }
      end

      type product = { id: String, route: String, title: String }

      class Product < WhopSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor route: String

        attr_accessor title: String

        def initialize: (id: String, route: String, title: String) -> void

        def to_hash: -> { id: String, route: String, title: String }
      end

      type promo_code =
        {
          id: String,
          amount_off: Float,
          base_currency: WhopSDK::Models::currency,
          code: String?,
          number_of_intervals: Integer?,
          promo_type: WhopSDK::Models::promo_type
        }

      class PromoCode < WhopSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor amount_off: Float

        attr_accessor base_currency: WhopSDK::Models::currency

        attr_accessor code: String?

        attr_accessor number_of_intervals: Integer?

        attr_accessor promo_type: WhopSDK::Models::promo_type

        def initialize: (
          id: String,
          amount_off: Float,
          base_currency: WhopSDK::Models::currency,
          code: String?,
          number_of_intervals: Integer?,
          promo_type: WhopSDK::Models::promo_type
        ) -> void

        def to_hash: -> {
          id: String,
          amount_off: Float,
          base_currency: WhopSDK::Models::currency,
          code: String?,
          number_of_intervals: Integer?,
          promo_type: WhopSDK::Models::promo_type
        }
      end

      type resolution =
        {
          id: String,
          customer_appealed: bool,
          customer_response_actions: ::Array[WhopSDK::Models::Payment::Resolution::customer_response_action],
          due_date: Time?,
          issue: WhopSDK::Models::Payment::Resolution::issue,
          merchant_appealed: bool,
          merchant_response_actions: ::Array[WhopSDK::Models::Payment::Resolution::merchant_response_action],
          platform_response_actions: ::Array[WhopSDK::Models::Payment::Resolution::platform_response_action],
          status: WhopSDK::Models::Payment::Resolution::status
        }

      class Resolution < WhopSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor customer_appealed: bool

        attr_accessor customer_response_actions: ::Array[WhopSDK::Models::Payment::Resolution::customer_response_action]

        attr_accessor due_date: Time?

        attr_accessor issue: WhopSDK::Models::Payment::Resolution::issue

        attr_accessor merchant_appealed: bool

        attr_accessor merchant_response_actions: ::Array[WhopSDK::Models::Payment::Resolution::merchant_response_action]

        attr_accessor platform_response_actions: ::Array[WhopSDK::Models::Payment::Resolution::platform_response_action]

        attr_accessor status: WhopSDK::Models::Payment::Resolution::status

        def initialize: (
          id: String,
          customer_appealed: bool,
          customer_response_actions: ::Array[WhopSDK::Models::Payment::Resolution::customer_response_action],
          due_date: Time?,
          issue: WhopSDK::Models::Payment::Resolution::issue,
          merchant_appealed: bool,
          merchant_response_actions: ::Array[WhopSDK::Models::Payment::Resolution::merchant_response_action],
          platform_response_actions: ::Array[WhopSDK::Models::Payment::Resolution::platform_response_action],
          status: WhopSDK::Models::Payment::Resolution::status
        ) -> void

        def to_hash: -> {
          id: String,
          customer_appealed: bool,
          customer_response_actions: ::Array[WhopSDK::Models::Payment::Resolution::customer_response_action],
          due_date: Time?,
          issue: WhopSDK::Models::Payment::Resolution::issue,
          merchant_appealed: bool,
          merchant_response_actions: ::Array[WhopSDK::Models::Payment::Resolution::merchant_response_action],
          platform_response_actions: ::Array[WhopSDK::Models::Payment::Resolution::platform_response_action],
          status: WhopSDK::Models::Payment::Resolution::status
        }

        type customer_response_action = :respond | :appeal | :withdraw

        module CustomerResponseAction
          extend WhopSDK::Internal::Type::Enum

          RESPOND: :respond
          APPEAL: :appeal
          WITHDRAW: :withdraw

          def self?.values: -> ::Array[WhopSDK::Models::Payment::Resolution::customer_response_action]
        end

        type issue =
          :forgot_to_cancel
          | :item_not_received
          | :significantly_not_as_described
          | :unauthorized_transaction
          | :product_unacceptable

        module Issue
          extend WhopSDK::Internal::Type::Enum

          FORGOT_TO_CANCEL: :forgot_to_cancel
          ITEM_NOT_RECEIVED: :item_not_received
          SIGNIFICANTLY_NOT_AS_DESCRIBED: :significantly_not_as_described
          UNAUTHORIZED_TRANSACTION: :unauthorized_transaction
          PRODUCT_UNACCEPTABLE: :product_unacceptable

          def self?.values: -> ::Array[WhopSDK::Models::Payment::Resolution::issue]
        end

        type merchant_response_action =
          :accept | :deny | :request_more_info | :appeal | :respond

        module MerchantResponseAction
          extend WhopSDK::Internal::Type::Enum

          ACCEPT: :accept
          DENY: :deny
          REQUEST_MORE_INFO: :request_more_info
          APPEAL: :appeal
          RESPOND: :respond

          def self?.values: -> ::Array[WhopSDK::Models::Payment::Resolution::merchant_response_action]
        end

        type platform_response_action =
          :request_buyer_info
          | :request_merchant_info
          | :merchant_wins
          | :platform_refund
          | :merchant_refund

        module PlatformResponseAction
          extend WhopSDK::Internal::Type::Enum

          REQUEST_BUYER_INFO: :request_buyer_info
          REQUEST_MERCHANT_INFO: :request_merchant_info
          MERCHANT_WINS: :merchant_wins
          PLATFORM_REFUND: :platform_refund
          MERCHANT_REFUND: :merchant_refund

          def self?.values: -> ::Array[WhopSDK::Models::Payment::Resolution::platform_response_action]
        end

        type status =
          :merchant_response_needed
          | :customer_response_needed
          | :merchant_info_needed
          | :customer_info_needed
          | :under_platform_review
          | :customer_won
          | :merchant_won
          | :customer_withdrew

        module Status
          extend WhopSDK::Internal::Type::Enum

          MERCHANT_RESPONSE_NEEDED: :merchant_response_needed
          CUSTOMER_RESPONSE_NEEDED: :customer_response_needed
          MERCHANT_INFO_NEEDED: :merchant_info_needed
          CUSTOMER_INFO_NEEDED: :customer_info_needed
          UNDER_PLATFORM_REVIEW: :under_platform_review
          CUSTOMER_WON: :customer_won
          MERCHANT_WON: :merchant_won
          CUSTOMER_WITHDREW: :customer_withdrew

          def self?.values: -> ::Array[WhopSDK::Models::Payment::Resolution::status]
        end
      end

      type tax_behavior =
        :exclusive | :inclusive | :unspecified | :unable_to_collect

      module TaxBehavior
        extend WhopSDK::Internal::Type::Enum

        EXCLUSIVE: :exclusive
        INCLUSIVE: :inclusive
        UNSPECIFIED: :unspecified
        UNABLE_TO_COLLECT: :unable_to_collect

        def self?.values: -> ::Array[WhopSDK::Models::Payment::tax_behavior]
      end

      type user =
        { id: String, email: String?, name: String?, username: String }

      class User < WhopSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor email: String?

        attr_accessor name: String?

        attr_accessor username: String

        def initialize: (
          id: String,
          email: String?,
          name: String?,
          username: String
        ) -> void

        def to_hash: -> {
          id: String,
          email: String?,
          name: String?,
          username: String
        }
      end
    end
  end
end
