module WhopSDK
  module Models
    type payment_provider =
      :stripe
      | :coinbase
      | :paypal
      | :apple
      | :sezzle
      | :splitit
      | :platform_balance
      | :multi_psp
      | :adyen
      | :claritypay
      | :flex_pay
      | :checkout_dot_com
      | :airwallex
      | :coinflow
      | :sequra
      | :dlocal
      | :masspay
      | :braintree

    module PaymentProvider
      extend WhopSDK::Internal::Type::Enum

      STRIPE: :stripe
      COINBASE: :coinbase
      PAYPAL: :paypal
      APPLE: :apple
      SEZZLE: :sezzle
      SPLITIT: :splitit
      PLATFORM_BALANCE: :platform_balance
      MULTI_PSP: :multi_psp
      ADYEN: :adyen
      CLARITYPAY: :claritypay
      FLEX_PAY: :flex_pay
      CHECKOUT_DOT_COM: :checkout_dot_com
      AIRWALLEX: :airwallex
      COINFLOW: :coinflow
      SEQURA: :sequra
      DLOCAL: :dlocal
      MASSPAY: :masspay
      BRAINTREE: :braintree

      def self?.values: -> ::Array[WhopSDK::Models::payment_provider]
    end
  end
end
