module WhopSDK
  module Models
    type payment_create_params =
      {
        account_id: String,
        plan_id: String,
        capture: bool?,
        confirmation_token: String?,
        email: String?,
        member_id: String?,
        metadata: ::Hash[Symbol, String]?,
        payment_method_id: String?,
        promo_code_id: String?,
        return_url: String?,
        api_version_date: String,
        idempotency_key: String
      }
      & WhopSDK::Internal::Type::request_parameters

    class PaymentCreateParams < WhopSDK::Internal::Type::BaseModel
      extend WhopSDK::Internal::Type::RequestParameters::Converter
      include WhopSDK::Internal::Type::RequestParameters

      attr_accessor account_id: String

      attr_accessor plan_id: String

      attr_accessor capture: bool?

      attr_accessor confirmation_token: String?

      attr_accessor email: String?

      attr_accessor member_id: String?

      attr_accessor metadata: ::Hash[Symbol, String]?

      attr_accessor payment_method_id: String?

      attr_accessor promo_code_id: String?

      attr_accessor return_url: String?

      attr_reader api_version_date: String?

      def api_version_date=: (String) -> String

      attr_reader idempotency_key: String?

      def idempotency_key=: (String) -> String

      def initialize: (
        account_id: String,
        plan_id: String,
        ?capture: bool?,
        ?confirmation_token: String?,
        ?email: String?,
        ?member_id: String?,
        ?metadata: ::Hash[Symbol, String]?,
        ?payment_method_id: String?,
        ?promo_code_id: String?,
        ?return_url: String?,
        ?api_version_date: String,
        ?idempotency_key: String,
        ?request_options: WhopSDK::request_opts
      ) -> void

      def to_hash: -> {
        account_id: String,
        plan_id: String,
        capture: bool?,
        confirmation_token: String?,
        email: String?,
        member_id: String?,
        metadata: ::Hash[Symbol, String]?,
        payment_method_id: String?,
        promo_code_id: String?,
        return_url: String?,
        api_version_date: String,
        idempotency_key: String,
        request_options: WhopSDK::RequestOptions
      }
    end
  end
end
