module WhopSDK
  module Models
    type payment_list_params =
      {
        account_id: String,
        after: String,
        before: String,
        billing_reason: WhopSDK::Models::PaymentListParams::billing_reason,
        created_after: Time,
        created_before: Time,
        currency: String,
        direction: WhopSDK::Models::PaymentListParams::direction,
        first: Integer,
        last: Integer,
        member_id: String,
        membership_id: String,
        order: WhopSDK::Models::PaymentListParams::order,
        plan_id: String,
        product_id: String,
        query: String,
        status: WhopSDK::Models::PaymentListParams::status,
        user_id: String,
        api_version_date: String
      }
      & WhopSDK::Internal::Type::request_parameters

    class PaymentListParams < WhopSDK::Internal::Type::BaseModel
      extend WhopSDK::Internal::Type::RequestParameters::Converter
      include WhopSDK::Internal::Type::RequestParameters

      attr_reader account_id: String?

      def account_id=: (String) -> String

      attr_reader after: String?

      def after=: (String) -> String

      attr_reader before: String?

      def before=: (String) -> String

      attr_reader billing_reason: WhopSDK::Models::PaymentListParams::billing_reason?

      def billing_reason=: (
        WhopSDK::Models::PaymentListParams::billing_reason
      ) -> WhopSDK::Models::PaymentListParams::billing_reason

      attr_reader created_after: Time?

      def created_after=: (Time) -> Time

      attr_reader created_before: Time?

      def created_before=: (Time) -> Time

      attr_reader currency: String?

      def currency=: (String) -> String

      attr_reader direction: WhopSDK::Models::PaymentListParams::direction?

      def direction=: (
        WhopSDK::Models::PaymentListParams::direction
      ) -> WhopSDK::Models::PaymentListParams::direction

      attr_reader first: Integer?

      def first=: (Integer) -> Integer

      attr_reader last: Integer?

      def last=: (Integer) -> Integer

      attr_reader member_id: String?

      def member_id=: (String) -> String

      attr_reader membership_id: String?

      def membership_id=: (String) -> String

      attr_reader order: WhopSDK::Models::PaymentListParams::order?

      def order=: (
        WhopSDK::Models::PaymentListParams::order
      ) -> WhopSDK::Models::PaymentListParams::order

      attr_reader plan_id: String?

      def plan_id=: (String) -> String

      attr_reader product_id: String?

      def product_id=: (String) -> String

      attr_reader query: String?

      def query=: (String) -> String

      attr_reader status: WhopSDK::Models::PaymentListParams::status?

      def status=: (
        WhopSDK::Models::PaymentListParams::status
      ) -> WhopSDK::Models::PaymentListParams::status

      attr_reader user_id: String?

      def user_id=: (String) -> String

      attr_reader api_version_date: String?

      def api_version_date=: (String) -> String

      def initialize: (
        ?account_id: String,
        ?after: String,
        ?before: String,
        ?billing_reason: WhopSDK::Models::PaymentListParams::billing_reason,
        ?created_after: Time,
        ?created_before: Time,
        ?currency: String,
        ?direction: WhopSDK::Models::PaymentListParams::direction,
        ?first: Integer,
        ?last: Integer,
        ?member_id: String,
        ?membership_id: String,
        ?order: WhopSDK::Models::PaymentListParams::order,
        ?plan_id: String,
        ?product_id: String,
        ?query: String,
        ?status: WhopSDK::Models::PaymentListParams::status,
        ?user_id: String,
        ?api_version_date: String,
        ?request_options: WhopSDK::request_opts
      ) -> void

      def to_hash: -> {
        account_id: String,
        after: String,
        before: String,
        billing_reason: WhopSDK::Models::PaymentListParams::billing_reason,
        created_after: Time,
        created_before: Time,
        currency: String,
        direction: WhopSDK::Models::PaymentListParams::direction,
        first: Integer,
        last: Integer,
        member_id: String,
        membership_id: String,
        order: WhopSDK::Models::PaymentListParams::order,
        plan_id: String,
        product_id: String,
        query: String,
        status: WhopSDK::Models::PaymentListParams::status,
        user_id: String,
        api_version_date: String,
        request_options: WhopSDK::RequestOptions
      }

      type billing_reason =
        :subscription_create
        | :subscription_cycle
        | :subscription_update
        | :one_time
        | :manual
        | :subscription

      module BillingReason
        extend WhopSDK::Internal::Type::Enum

        SUBSCRIPTION_CREATE: :subscription_create
        SUBSCRIPTION_CYCLE: :subscription_cycle
        SUBSCRIPTION_UPDATE: :subscription_update
        ONE_TIME: :one_time
        MANUAL: :manual
        SUBSCRIPTION: :subscription

        def self?.values: -> ::Array[WhopSDK::Models::PaymentListParams::billing_reason]
      end

      type direction = :asc | :desc

      module Direction
        extend WhopSDK::Internal::Type::Enum

        ASC: :asc
        DESC: :desc

        def self?.values: -> ::Array[WhopSDK::Models::PaymentListParams::direction]
      end

      type order = :created_at | :paid_at

      module Order
        extend WhopSDK::Internal::Type::Enum

        CREATED_AT: :created_at
        PAID_AT: :paid_at

        def self?.values: -> ::Array[WhopSDK::Models::PaymentListParams::order]
      end

      type status =
        :open
        | :authorized
        | :paid
        | :pending
        | :uncollectible
        | :unresolved
        | :void

      module Status
        extend WhopSDK::Internal::Type::Enum

        OPEN: :open
        AUTHORIZED: :authorized
        PAID: :paid
        PENDING: :pending
        UNCOLLECTIBLE: :uncollectible
        UNRESOLVED: :unresolved
        VOID: :void

        def self?.values: -> ::Array[WhopSDK::Models::PaymentListParams::status]
      end
    end
  end
end
