module WhopSDK
  module Models
    type payment_created_webhook_event =
      {
        id: String,
        api_version: :v1,
        data: WhopSDK::Payment,
        timestamp: Time,
        type: :"payment.created",
        company_id: String?
      }

    class PaymentCreatedWebhookEvent < WhopSDK::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor api_version: :v1

      attr_accessor data: WhopSDK::Payment

      attr_accessor timestamp: Time

      attr_accessor type: :"payment.created"

      attr_accessor company_id: String?

      def initialize: (
        id: String,
        data: WhopSDK::Payment,
        timestamp: Time,
        ?company_id: String?,
        ?api_version: :v1,
        ?type: :"payment.created"
      ) -> void

      def to_hash: -> {
        id: String,
        api_version: :v1,
        data: WhopSDK::Payment,
        timestamp: Time,
        type: :"payment.created",
        company_id: String?
      }
    end
  end
end
