module WhopSDK
  module Models
    type payment_create_response = { client_secret: String? }

    class PaymentCreateResponse < WhopSDK::Models::Payment
      def client_secret: -> String?

      def client_secret=: (String? _) -> String?

      def initialize: (client_secret: String?) -> void

      def to_hash: -> { client_secret: String? }
    end
  end
end
