module WhopSDK
  module Models
    type payment_method_list_response =
      WhopSDK::Models::PaymentMethodListResponse::BasePaymentMethod
      | WhopSDK::Models::PaymentMethodListResponse::CardPaymentMethod
      | WhopSDK::Models::PaymentMethodListResponse::UsBankAccountPaymentMethod
      | WhopSDK::Models::PaymentMethodListResponse::CashappPaymentMethod
      | WhopSDK::Models::PaymentMethodListResponse::IdealPaymentMethod
      | WhopSDK::Models::PaymentMethodListResponse::SepaDebitPaymentMethod
      | WhopSDK::Models::PaymentMethodListResponse::PlatformBalancePaymentMethod

    module PaymentMethodListResponse
      extend WhopSDK::Internal::Type::Union

      type base_payment_method =
        {
          id: String,
          created_at: Time,
          icons: WhopSDK::Models::PaymentMethodListResponse::BasePaymentMethod::Icons,
          payment_method_type: WhopSDK::Models::payment_method_types,
          typename: :BasePaymentMethod
        }

      class BasePaymentMethod < WhopSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor created_at: Time

        attr_accessor icons: WhopSDK::Models::PaymentMethodListResponse::BasePaymentMethod::Icons

        attr_accessor payment_method_type: WhopSDK::Models::payment_method_types

        attr_accessor typename: :BasePaymentMethod

        def initialize: (
          id: String,
          created_at: Time,
          icons: WhopSDK::Models::PaymentMethodListResponse::BasePaymentMethod::Icons,
          payment_method_type: WhopSDK::Models::payment_method_types,
          ?typename: :BasePaymentMethod
        ) -> void

        def to_hash: -> {
          id: String,
          created_at: Time,
          icons: WhopSDK::Models::PaymentMethodListResponse::BasePaymentMethod::Icons,
          payment_method_type: WhopSDK::Models::payment_method_types,
          typename: :BasePaymentMethod
        }

        type icons =
          {
            card: WhopSDK::Models::PaymentMethodListResponse::BasePaymentMethod::Icons::Card,
            square: WhopSDK::Models::PaymentMethodListResponse::BasePaymentMethod::Icons::Square
          }

        class Icons < WhopSDK::Internal::Type::BaseModel
          attr_accessor card: WhopSDK::Models::PaymentMethodListResponse::BasePaymentMethod::Icons::Card

          attr_accessor square: WhopSDK::Models::PaymentMethodListResponse::BasePaymentMethod::Icons::Square

          def initialize: (
            card: WhopSDK::Models::PaymentMethodListResponse::BasePaymentMethod::Icons::Card,
            square: WhopSDK::Models::PaymentMethodListResponse::BasePaymentMethod::Icons::Square
          ) -> void

          def to_hash: -> {
            card: WhopSDK::Models::PaymentMethodListResponse::BasePaymentMethod::Icons::Card,
            square: WhopSDK::Models::PaymentMethodListResponse::BasePaymentMethod::Icons::Square
          }

          type card =
            {
              dark: WhopSDK::Models::PaymentMethodListResponse::BasePaymentMethod::Icons::Card::Dark,
              light: WhopSDK::Models::PaymentMethodListResponse::BasePaymentMethod::Icons::Card::Light
            }

          class Card < WhopSDK::Internal::Type::BaseModel
            attr_accessor dark: WhopSDK::Models::PaymentMethodListResponse::BasePaymentMethod::Icons::Card::Dark

            attr_accessor light: WhopSDK::Models::PaymentMethodListResponse::BasePaymentMethod::Icons::Card::Light

            def initialize: (
              dark: WhopSDK::Models::PaymentMethodListResponse::BasePaymentMethod::Icons::Card::Dark,
              light: WhopSDK::Models::PaymentMethodListResponse::BasePaymentMethod::Icons::Card::Light
            ) -> void

            def to_hash: -> {
              dark: WhopSDK::Models::PaymentMethodListResponse::BasePaymentMethod::Icons::Card::Dark,
              light: WhopSDK::Models::PaymentMethodListResponse::BasePaymentMethod::Icons::Card::Light
            }

            type dark =
              {
                :png_1x => String,
                :png_2x => String,
                :png_4x => String,
                svg: String
              }

            class Dark < WhopSDK::Internal::Type::BaseModel
              attr_accessor png_1x: String

              attr_accessor png_2x: String

              attr_accessor png_4x: String

              attr_accessor svg: String

              def initialize: (
                png_1x: String,
                png_2x: String,
                png_4x: String,
                svg: String
              ) -> void

              def to_hash: -> {
                :png_1x => String,
                :png_2x => String,
                :png_4x => String,
                svg: String
              }
            end

            type light =
              {
                :png_1x => String,
                :png_2x => String,
                :png_4x => String,
                svg: String
              }

            class Light < WhopSDK::Internal::Type::BaseModel
              attr_accessor png_1x: String

              attr_accessor png_2x: String

              attr_accessor png_4x: String

              attr_accessor svg: String

              def initialize: (
                png_1x: String,
                png_2x: String,
                png_4x: String,
                svg: String
              ) -> void

              def to_hash: -> {
                :png_1x => String,
                :png_2x => String,
                :png_4x => String,
                svg: String
              }
            end
          end

          type square =
            {
              dark: WhopSDK::Models::PaymentMethodListResponse::BasePaymentMethod::Icons::Square::Dark,
              light: WhopSDK::Models::PaymentMethodListResponse::BasePaymentMethod::Icons::Square::Light
            }

          class Square < WhopSDK::Internal::Type::BaseModel
            attr_accessor dark: WhopSDK::Models::PaymentMethodListResponse::BasePaymentMethod::Icons::Square::Dark

            attr_accessor light: WhopSDK::Models::PaymentMethodListResponse::BasePaymentMethod::Icons::Square::Light

            def initialize: (
              dark: WhopSDK::Models::PaymentMethodListResponse::BasePaymentMethod::Icons::Square::Dark,
              light: WhopSDK::Models::PaymentMethodListResponse::BasePaymentMethod::Icons::Square::Light
            ) -> void

            def to_hash: -> {
              dark: WhopSDK::Models::PaymentMethodListResponse::BasePaymentMethod::Icons::Square::Dark,
              light: WhopSDK::Models::PaymentMethodListResponse::BasePaymentMethod::Icons::Square::Light
            }

            type dark =
              {
                :png_1x => String,
                :png_2x => String,
                :png_4x => String,
                svg: String
              }

            class Dark < WhopSDK::Internal::Type::BaseModel
              attr_accessor png_1x: String

              attr_accessor png_2x: String

              attr_accessor png_4x: String

              attr_accessor svg: String

              def initialize: (
                png_1x: String,
                png_2x: String,
                png_4x: String,
                svg: String
              ) -> void

              def to_hash: -> {
                :png_1x => String,
                :png_2x => String,
                :png_4x => String,
                svg: String
              }
            end

            type light =
              {
                :png_1x => String,
                :png_2x => String,
                :png_4x => String,
                svg: String
              }

            class Light < WhopSDK::Internal::Type::BaseModel
              attr_accessor png_1x: String

              attr_accessor png_2x: String

              attr_accessor png_4x: String

              attr_accessor svg: String

              def initialize: (
                png_1x: String,
                png_2x: String,
                png_4x: String,
                svg: String
              ) -> void

              def to_hash: -> {
                :png_1x => String,
                :png_2x => String,
                :png_4x => String,
                svg: String
              }
            end
          end
        end
      end

      type card_payment_method =
        {
          id: String,
          card: WhopSDK::Models::PaymentMethodListResponse::CardPaymentMethod::Card,
          created_at: Time,
          has_payer_document: bool,
          icons: WhopSDK::Models::PaymentMethodListResponse::CardPaymentMethod::Icons,
          payment_method_type: WhopSDK::Models::payment_method_types,
          typename: :CardPaymentMethod
        }

      class CardPaymentMethod < WhopSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor card: WhopSDK::Models::PaymentMethodListResponse::CardPaymentMethod::Card

        attr_accessor created_at: Time

        attr_accessor has_payer_document: bool

        attr_accessor icons: WhopSDK::Models::PaymentMethodListResponse::CardPaymentMethod::Icons

        attr_accessor payment_method_type: WhopSDK::Models::payment_method_types

        attr_accessor typename: :CardPaymentMethod

        def initialize: (
          id: String,
          card: WhopSDK::Models::PaymentMethodListResponse::CardPaymentMethod::Card,
          created_at: Time,
          has_payer_document: bool,
          icons: WhopSDK::Models::PaymentMethodListResponse::CardPaymentMethod::Icons,
          payment_method_type: WhopSDK::Models::payment_method_types,
          ?typename: :CardPaymentMethod
        ) -> void

        def to_hash: -> {
          id: String,
          card: WhopSDK::Models::PaymentMethodListResponse::CardPaymentMethod::Card,
          created_at: Time,
          has_payer_document: bool,
          icons: WhopSDK::Models::PaymentMethodListResponse::CardPaymentMethod::Icons,
          payment_method_type: WhopSDK::Models::payment_method_types,
          typename: :CardPaymentMethod
        }

        type card =
          {
            brand: WhopSDK::Models::card_brands?,
            exp_month: Integer?,
            exp_year: Integer?,
            expired: bool,
            fingerprint: String?,
            funding_type: WhopSDK::Models::PaymentMethodListResponse::CardPaymentMethod::Card::funding_type?,
            :last4 => String?,
            three_ds_verified: bool
          }

        class Card < WhopSDK::Internal::Type::BaseModel
          attr_accessor brand: WhopSDK::Models::card_brands?

          attr_accessor exp_month: Integer?

          attr_accessor exp_year: Integer?

          attr_accessor expired: bool

          attr_accessor fingerprint: String?

          attr_accessor funding_type: WhopSDK::Models::PaymentMethodListResponse::CardPaymentMethod::Card::funding_type?

          attr_accessor last4: String?

          attr_accessor three_ds_verified: bool

          def initialize: (
            brand: WhopSDK::Models::card_brands?,
            exp_month: Integer?,
            exp_year: Integer?,
            expired: bool,
            fingerprint: String?,
            funding_type: WhopSDK::Models::PaymentMethodListResponse::CardPaymentMethod::Card::funding_type?,
            last4: String?,
            three_ds_verified: bool
          ) -> void

          def to_hash: -> {
            brand: WhopSDK::Models::card_brands?,
            exp_month: Integer?,
            exp_year: Integer?,
            expired: bool,
            fingerprint: String?,
            funding_type: WhopSDK::Models::PaymentMethodListResponse::CardPaymentMethod::Card::funding_type?,
            :last4 => String?,
            three_ds_verified: bool
          }

          type funding_type = :credit | :debit | :prepaid

          module FundingType
            extend WhopSDK::Internal::Type::Enum

            CREDIT: :credit
            DEBIT: :debit
            PREPAID: :prepaid

            def self?.values: -> ::Array[WhopSDK::Models::PaymentMethodListResponse::CardPaymentMethod::Card::funding_type]
          end
        end

        type icons =
          {
            card: WhopSDK::Models::PaymentMethodListResponse::CardPaymentMethod::Icons::Card,
            square: WhopSDK::Models::PaymentMethodListResponse::CardPaymentMethod::Icons::Square
          }

        class Icons < WhopSDK::Internal::Type::BaseModel
          attr_accessor card: WhopSDK::Models::PaymentMethodListResponse::CardPaymentMethod::Icons::Card

          attr_accessor square: WhopSDK::Models::PaymentMethodListResponse::CardPaymentMethod::Icons::Square

          def initialize: (
            card: WhopSDK::Models::PaymentMethodListResponse::CardPaymentMethod::Icons::Card,
            square: WhopSDK::Models::PaymentMethodListResponse::CardPaymentMethod::Icons::Square
          ) -> void

          def to_hash: -> {
            card: WhopSDK::Models::PaymentMethodListResponse::CardPaymentMethod::Icons::Card,
            square: WhopSDK::Models::PaymentMethodListResponse::CardPaymentMethod::Icons::Square
          }

          type card =
            {
              dark: WhopSDK::Models::PaymentMethodListResponse::CardPaymentMethod::Icons::Card::Dark,
              light: WhopSDK::Models::PaymentMethodListResponse::CardPaymentMethod::Icons::Card::Light
            }

          class Card < WhopSDK::Internal::Type::BaseModel
            attr_accessor dark: WhopSDK::Models::PaymentMethodListResponse::CardPaymentMethod::Icons::Card::Dark

            attr_accessor light: WhopSDK::Models::PaymentMethodListResponse::CardPaymentMethod::Icons::Card::Light

            def initialize: (
              dark: WhopSDK::Models::PaymentMethodListResponse::CardPaymentMethod::Icons::Card::Dark,
              light: WhopSDK::Models::PaymentMethodListResponse::CardPaymentMethod::Icons::Card::Light
            ) -> void

            def to_hash: -> {
              dark: WhopSDK::Models::PaymentMethodListResponse::CardPaymentMethod::Icons::Card::Dark,
              light: WhopSDK::Models::PaymentMethodListResponse::CardPaymentMethod::Icons::Card::Light
            }

            type dark =
              {
                :png_1x => String,
                :png_2x => String,
                :png_4x => String,
                svg: String
              }

            class Dark < WhopSDK::Internal::Type::BaseModel
              attr_accessor png_1x: String

              attr_accessor png_2x: String

              attr_accessor png_4x: String

              attr_accessor svg: String

              def initialize: (
                png_1x: String,
                png_2x: String,
                png_4x: String,
                svg: String
              ) -> void

              def to_hash: -> {
                :png_1x => String,
                :png_2x => String,
                :png_4x => String,
                svg: String
              }
            end

            type light =
              {
                :png_1x => String,
                :png_2x => String,
                :png_4x => String,
                svg: String
              }

            class Light < WhopSDK::Internal::Type::BaseModel
              attr_accessor png_1x: String

              attr_accessor png_2x: String

              attr_accessor png_4x: String

              attr_accessor svg: String

              def initialize: (
                png_1x: String,
                png_2x: String,
                png_4x: String,
                svg: String
              ) -> void

              def to_hash: -> {
                :png_1x => String,
                :png_2x => String,
                :png_4x => String,
                svg: String
              }
            end
          end

          type square =
            {
              dark: WhopSDK::Models::PaymentMethodListResponse::CardPaymentMethod::Icons::Square::Dark,
              light: WhopSDK::Models::PaymentMethodListResponse::CardPaymentMethod::Icons::Square::Light
            }

          class Square < WhopSDK::Internal::Type::BaseModel
            attr_accessor dark: WhopSDK::Models::PaymentMethodListResponse::CardPaymentMethod::Icons::Square::Dark

            attr_accessor light: WhopSDK::Models::PaymentMethodListResponse::CardPaymentMethod::Icons::Square::Light

            def initialize: (
              dark: WhopSDK::Models::PaymentMethodListResponse::CardPaymentMethod::Icons::Square::Dark,
              light: WhopSDK::Models::PaymentMethodListResponse::CardPaymentMethod::Icons::Square::Light
            ) -> void

            def to_hash: -> {
              dark: WhopSDK::Models::PaymentMethodListResponse::CardPaymentMethod::Icons::Square::Dark,
              light: WhopSDK::Models::PaymentMethodListResponse::CardPaymentMethod::Icons::Square::Light
            }

            type dark =
              {
                :png_1x => String,
                :png_2x => String,
                :png_4x => String,
                svg: String
              }

            class Dark < WhopSDK::Internal::Type::BaseModel
              attr_accessor png_1x: String

              attr_accessor png_2x: String

              attr_accessor png_4x: String

              attr_accessor svg: String

              def initialize: (
                png_1x: String,
                png_2x: String,
                png_4x: String,
                svg: String
              ) -> void

              def to_hash: -> {
                :png_1x => String,
                :png_2x => String,
                :png_4x => String,
                svg: String
              }
            end

            type light =
              {
                :png_1x => String,
                :png_2x => String,
                :png_4x => String,
                svg: String
              }

            class Light < WhopSDK::Internal::Type::BaseModel
              attr_accessor png_1x: String

              attr_accessor png_2x: String

              attr_accessor png_4x: String

              attr_accessor svg: String

              def initialize: (
                png_1x: String,
                png_2x: String,
                png_4x: String,
                svg: String
              ) -> void

              def to_hash: -> {
                :png_1x => String,
                :png_2x => String,
                :png_4x => String,
                svg: String
              }
            end
          end
        end
      end

      type us_bank_account_payment_method =
        {
          id: String,
          created_at: Time,
          icons: WhopSDK::Models::PaymentMethodListResponse::UsBankAccountPaymentMethod::Icons,
          payment_method_type: WhopSDK::Models::payment_method_types,
          typename: :UsBankAccountPaymentMethod,
          us_bank_account: WhopSDK::Models::PaymentMethodListResponse::UsBankAccountPaymentMethod::UsBankAccount
        }

      class UsBankAccountPaymentMethod < WhopSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor created_at: Time

        attr_accessor icons: WhopSDK::Models::PaymentMethodListResponse::UsBankAccountPaymentMethod::Icons

        attr_accessor payment_method_type: WhopSDK::Models::payment_method_types

        attr_accessor typename: :UsBankAccountPaymentMethod

        attr_accessor us_bank_account: WhopSDK::Models::PaymentMethodListResponse::UsBankAccountPaymentMethod::UsBankAccount

        def initialize: (
          id: String,
          created_at: Time,
          icons: WhopSDK::Models::PaymentMethodListResponse::UsBankAccountPaymentMethod::Icons,
          payment_method_type: WhopSDK::Models::payment_method_types,
          us_bank_account: WhopSDK::Models::PaymentMethodListResponse::UsBankAccountPaymentMethod::UsBankAccount,
          ?typename: :UsBankAccountPaymentMethod
        ) -> void

        def to_hash: -> {
          id: String,
          created_at: Time,
          icons: WhopSDK::Models::PaymentMethodListResponse::UsBankAccountPaymentMethod::Icons,
          payment_method_type: WhopSDK::Models::payment_method_types,
          typename: :UsBankAccountPaymentMethod,
          us_bank_account: WhopSDK::Models::PaymentMethodListResponse::UsBankAccountPaymentMethod::UsBankAccount
        }

        type icons =
          {
            card: WhopSDK::Models::PaymentMethodListResponse::UsBankAccountPaymentMethod::Icons::Card,
            square: WhopSDK::Models::PaymentMethodListResponse::UsBankAccountPaymentMethod::Icons::Square
          }

        class Icons < WhopSDK::Internal::Type::BaseModel
          attr_accessor card: WhopSDK::Models::PaymentMethodListResponse::UsBankAccountPaymentMethod::Icons::Card

          attr_accessor square: WhopSDK::Models::PaymentMethodListResponse::UsBankAccountPaymentMethod::Icons::Square

          def initialize: (
            card: WhopSDK::Models::PaymentMethodListResponse::UsBankAccountPaymentMethod::Icons::Card,
            square: WhopSDK::Models::PaymentMethodListResponse::UsBankAccountPaymentMethod::Icons::Square
          ) -> void

          def to_hash: -> {
            card: WhopSDK::Models::PaymentMethodListResponse::UsBankAccountPaymentMethod::Icons::Card,
            square: WhopSDK::Models::PaymentMethodListResponse::UsBankAccountPaymentMethod::Icons::Square
          }

          type card =
            {
              dark: WhopSDK::Models::PaymentMethodListResponse::UsBankAccountPaymentMethod::Icons::Card::Dark,
              light: WhopSDK::Models::PaymentMethodListResponse::UsBankAccountPaymentMethod::Icons::Card::Light
            }

          class Card < WhopSDK::Internal::Type::BaseModel
            attr_accessor dark: WhopSDK::Models::PaymentMethodListResponse::UsBankAccountPaymentMethod::Icons::Card::Dark

            attr_accessor light: WhopSDK::Models::PaymentMethodListResponse::UsBankAccountPaymentMethod::Icons::Card::Light

            def initialize: (
              dark: WhopSDK::Models::PaymentMethodListResponse::UsBankAccountPaymentMethod::Icons::Card::Dark,
              light: WhopSDK::Models::PaymentMethodListResponse::UsBankAccountPaymentMethod::Icons::Card::Light
            ) -> void

            def to_hash: -> {
              dark: WhopSDK::Models::PaymentMethodListResponse::UsBankAccountPaymentMethod::Icons::Card::Dark,
              light: WhopSDK::Models::PaymentMethodListResponse::UsBankAccountPaymentMethod::Icons::Card::Light
            }

            type dark =
              {
                :png_1x => String,
                :png_2x => String,
                :png_4x => String,
                svg: String
              }

            class Dark < WhopSDK::Internal::Type::BaseModel
              attr_accessor png_1x: String

              attr_accessor png_2x: String

              attr_accessor png_4x: String

              attr_accessor svg: String

              def initialize: (
                png_1x: String,
                png_2x: String,
                png_4x: String,
                svg: String
              ) -> void

              def to_hash: -> {
                :png_1x => String,
                :png_2x => String,
                :png_4x => String,
                svg: String
              }
            end

            type light =
              {
                :png_1x => String,
                :png_2x => String,
                :png_4x => String,
                svg: String
              }

            class Light < WhopSDK::Internal::Type::BaseModel
              attr_accessor png_1x: String

              attr_accessor png_2x: String

              attr_accessor png_4x: String

              attr_accessor svg: String

              def initialize: (
                png_1x: String,
                png_2x: String,
                png_4x: String,
                svg: String
              ) -> void

              def to_hash: -> {
                :png_1x => String,
                :png_2x => String,
                :png_4x => String,
                svg: String
              }
            end
          end

          type square =
            {
              dark: WhopSDK::Models::PaymentMethodListResponse::UsBankAccountPaymentMethod::Icons::Square::Dark,
              light: WhopSDK::Models::PaymentMethodListResponse::UsBankAccountPaymentMethod::Icons::Square::Light
            }

          class Square < WhopSDK::Internal::Type::BaseModel
            attr_accessor dark: WhopSDK::Models::PaymentMethodListResponse::UsBankAccountPaymentMethod::Icons::Square::Dark

            attr_accessor light: WhopSDK::Models::PaymentMethodListResponse::UsBankAccountPaymentMethod::Icons::Square::Light

            def initialize: (
              dark: WhopSDK::Models::PaymentMethodListResponse::UsBankAccountPaymentMethod::Icons::Square::Dark,
              light: WhopSDK::Models::PaymentMethodListResponse::UsBankAccountPaymentMethod::Icons::Square::Light
            ) -> void

            def to_hash: -> {
              dark: WhopSDK::Models::PaymentMethodListResponse::UsBankAccountPaymentMethod::Icons::Square::Dark,
              light: WhopSDK::Models::PaymentMethodListResponse::UsBankAccountPaymentMethod::Icons::Square::Light
            }

            type dark =
              {
                :png_1x => String,
                :png_2x => String,
                :png_4x => String,
                svg: String
              }

            class Dark < WhopSDK::Internal::Type::BaseModel
              attr_accessor png_1x: String

              attr_accessor png_2x: String

              attr_accessor png_4x: String

              attr_accessor svg: String

              def initialize: (
                png_1x: String,
                png_2x: String,
                png_4x: String,
                svg: String
              ) -> void

              def to_hash: -> {
                :png_1x => String,
                :png_2x => String,
                :png_4x => String,
                svg: String
              }
            end

            type light =
              {
                :png_1x => String,
                :png_2x => String,
                :png_4x => String,
                svg: String
              }

            class Light < WhopSDK::Internal::Type::BaseModel
              attr_accessor png_1x: String

              attr_accessor png_2x: String

              attr_accessor png_4x: String

              attr_accessor svg: String

              def initialize: (
                png_1x: String,
                png_2x: String,
                png_4x: String,
                svg: String
              ) -> void

              def to_hash: -> {
                :png_1x => String,
                :png_2x => String,
                :png_4x => String,
                svg: String
              }
            end
          end
        end

        type us_bank_account =
          { account_type: String, bank_name: String, :last4 => String }

        class UsBankAccount < WhopSDK::Internal::Type::BaseModel
          attr_accessor account_type: String

          attr_accessor bank_name: String

          attr_accessor last4: String

          def initialize: (
            account_type: String,
            bank_name: String,
            last4: String
          ) -> void

          def to_hash: -> {
            account_type: String,
            bank_name: String,
            :last4 => String
          }
        end
      end

      type cashapp_payment_method =
        {
          id: String,
          cashapp: WhopSDK::Models::PaymentMethodListResponse::CashappPaymentMethod::Cashapp,
          created_at: Time,
          icons: WhopSDK::Models::PaymentMethodListResponse::CashappPaymentMethod::Icons,
          payment_method_type: WhopSDK::Models::payment_method_types,
          typename: :CashappPaymentMethod
        }

      class CashappPaymentMethod < WhopSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor cashapp: WhopSDK::Models::PaymentMethodListResponse::CashappPaymentMethod::Cashapp

        attr_accessor created_at: Time

        attr_accessor icons: WhopSDK::Models::PaymentMethodListResponse::CashappPaymentMethod::Icons

        attr_accessor payment_method_type: WhopSDK::Models::payment_method_types

        attr_accessor typename: :CashappPaymentMethod

        def initialize: (
          id: String,
          cashapp: WhopSDK::Models::PaymentMethodListResponse::CashappPaymentMethod::Cashapp,
          created_at: Time,
          icons: WhopSDK::Models::PaymentMethodListResponse::CashappPaymentMethod::Icons,
          payment_method_type: WhopSDK::Models::payment_method_types,
          ?typename: :CashappPaymentMethod
        ) -> void

        def to_hash: -> {
          id: String,
          cashapp: WhopSDK::Models::PaymentMethodListResponse::CashappPaymentMethod::Cashapp,
          created_at: Time,
          icons: WhopSDK::Models::PaymentMethodListResponse::CashappPaymentMethod::Icons,
          payment_method_type: WhopSDK::Models::payment_method_types,
          typename: :CashappPaymentMethod
        }

        type cashapp = { buyer_id: String?, cashtag: String? }

        class Cashapp < WhopSDK::Internal::Type::BaseModel
          attr_accessor buyer_id: String?

          attr_accessor cashtag: String?

          def initialize: (buyer_id: String?, cashtag: String?) -> void

          def to_hash: -> { buyer_id: String?, cashtag: String? }
        end

        type icons =
          {
            card: WhopSDK::Models::PaymentMethodListResponse::CashappPaymentMethod::Icons::Card,
            square: WhopSDK::Models::PaymentMethodListResponse::CashappPaymentMethod::Icons::Square
          }

        class Icons < WhopSDK::Internal::Type::BaseModel
          attr_accessor card: WhopSDK::Models::PaymentMethodListResponse::CashappPaymentMethod::Icons::Card

          attr_accessor square: WhopSDK::Models::PaymentMethodListResponse::CashappPaymentMethod::Icons::Square

          def initialize: (
            card: WhopSDK::Models::PaymentMethodListResponse::CashappPaymentMethod::Icons::Card,
            square: WhopSDK::Models::PaymentMethodListResponse::CashappPaymentMethod::Icons::Square
          ) -> void

          def to_hash: -> {
            card: WhopSDK::Models::PaymentMethodListResponse::CashappPaymentMethod::Icons::Card,
            square: WhopSDK::Models::PaymentMethodListResponse::CashappPaymentMethod::Icons::Square
          }

          type card =
            {
              dark: WhopSDK::Models::PaymentMethodListResponse::CashappPaymentMethod::Icons::Card::Dark,
              light: WhopSDK::Models::PaymentMethodListResponse::CashappPaymentMethod::Icons::Card::Light
            }

          class Card < WhopSDK::Internal::Type::BaseModel
            attr_accessor dark: WhopSDK::Models::PaymentMethodListResponse::CashappPaymentMethod::Icons::Card::Dark

            attr_accessor light: WhopSDK::Models::PaymentMethodListResponse::CashappPaymentMethod::Icons::Card::Light

            def initialize: (
              dark: WhopSDK::Models::PaymentMethodListResponse::CashappPaymentMethod::Icons::Card::Dark,
              light: WhopSDK::Models::PaymentMethodListResponse::CashappPaymentMethod::Icons::Card::Light
            ) -> void

            def to_hash: -> {
              dark: WhopSDK::Models::PaymentMethodListResponse::CashappPaymentMethod::Icons::Card::Dark,
              light: WhopSDK::Models::PaymentMethodListResponse::CashappPaymentMethod::Icons::Card::Light
            }

            type dark =
              {
                :png_1x => String,
                :png_2x => String,
                :png_4x => String,
                svg: String
              }

            class Dark < WhopSDK::Internal::Type::BaseModel
              attr_accessor png_1x: String

              attr_accessor png_2x: String

              attr_accessor png_4x: String

              attr_accessor svg: String

              def initialize: (
                png_1x: String,
                png_2x: String,
                png_4x: String,
                svg: String
              ) -> void

              def to_hash: -> {
                :png_1x => String,
                :png_2x => String,
                :png_4x => String,
                svg: String
              }
            end

            type light =
              {
                :png_1x => String,
                :png_2x => String,
                :png_4x => String,
                svg: String
              }

            class Light < WhopSDK::Internal::Type::BaseModel
              attr_accessor png_1x: String

              attr_accessor png_2x: String

              attr_accessor png_4x: String

              attr_accessor svg: String

              def initialize: (
                png_1x: String,
                png_2x: String,
                png_4x: String,
                svg: String
              ) -> void

              def to_hash: -> {
                :png_1x => String,
                :png_2x => String,
                :png_4x => String,
                svg: String
              }
            end
          end

          type square =
            {
              dark: WhopSDK::Models::PaymentMethodListResponse::CashappPaymentMethod::Icons::Square::Dark,
              light: WhopSDK::Models::PaymentMethodListResponse::CashappPaymentMethod::Icons::Square::Light
            }

          class Square < WhopSDK::Internal::Type::BaseModel
            attr_accessor dark: WhopSDK::Models::PaymentMethodListResponse::CashappPaymentMethod::Icons::Square::Dark

            attr_accessor light: WhopSDK::Models::PaymentMethodListResponse::CashappPaymentMethod::Icons::Square::Light

            def initialize: (
              dark: WhopSDK::Models::PaymentMethodListResponse::CashappPaymentMethod::Icons::Square::Dark,
              light: WhopSDK::Models::PaymentMethodListResponse::CashappPaymentMethod::Icons::Square::Light
            ) -> void

            def to_hash: -> {
              dark: WhopSDK::Models::PaymentMethodListResponse::CashappPaymentMethod::Icons::Square::Dark,
              light: WhopSDK::Models::PaymentMethodListResponse::CashappPaymentMethod::Icons::Square::Light
            }

            type dark =
              {
                :png_1x => String,
                :png_2x => String,
                :png_4x => String,
                svg: String
              }

            class Dark < WhopSDK::Internal::Type::BaseModel
              attr_accessor png_1x: String

              attr_accessor png_2x: String

              attr_accessor png_4x: String

              attr_accessor svg: String

              def initialize: (
                png_1x: String,
                png_2x: String,
                png_4x: String,
                svg: String
              ) -> void

              def to_hash: -> {
                :png_1x => String,
                :png_2x => String,
                :png_4x => String,
                svg: String
              }
            end

            type light =
              {
                :png_1x => String,
                :png_2x => String,
                :png_4x => String,
                svg: String
              }

            class Light < WhopSDK::Internal::Type::BaseModel
              attr_accessor png_1x: String

              attr_accessor png_2x: String

              attr_accessor png_4x: String

              attr_accessor svg: String

              def initialize: (
                png_1x: String,
                png_2x: String,
                png_4x: String,
                svg: String
              ) -> void

              def to_hash: -> {
                :png_1x => String,
                :png_2x => String,
                :png_4x => String,
                svg: String
              }
            end
          end
        end
      end

      type ideal_payment_method =
        {
          id: String,
          created_at: Time,
          icons: WhopSDK::Models::PaymentMethodListResponse::IdealPaymentMethod::Icons,
          ideal: WhopSDK::Models::PaymentMethodListResponse::IdealPaymentMethod::Ideal,
          payment_method_type: WhopSDK::Models::payment_method_types,
          typename: :IdealPaymentMethod
        }

      class IdealPaymentMethod < WhopSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor created_at: Time

        attr_accessor icons: WhopSDK::Models::PaymentMethodListResponse::IdealPaymentMethod::Icons

        attr_accessor ideal: WhopSDK::Models::PaymentMethodListResponse::IdealPaymentMethod::Ideal

        attr_accessor payment_method_type: WhopSDK::Models::payment_method_types

        attr_accessor typename: :IdealPaymentMethod

        def initialize: (
          id: String,
          created_at: Time,
          icons: WhopSDK::Models::PaymentMethodListResponse::IdealPaymentMethod::Icons,
          ideal: WhopSDK::Models::PaymentMethodListResponse::IdealPaymentMethod::Ideal,
          payment_method_type: WhopSDK::Models::payment_method_types,
          ?typename: :IdealPaymentMethod
        ) -> void

        def to_hash: -> {
          id: String,
          created_at: Time,
          icons: WhopSDK::Models::PaymentMethodListResponse::IdealPaymentMethod::Icons,
          ideal: WhopSDK::Models::PaymentMethodListResponse::IdealPaymentMethod::Ideal,
          payment_method_type: WhopSDK::Models::payment_method_types,
          typename: :IdealPaymentMethod
        }

        type icons =
          {
            card: WhopSDK::Models::PaymentMethodListResponse::IdealPaymentMethod::Icons::Card,
            square: WhopSDK::Models::PaymentMethodListResponse::IdealPaymentMethod::Icons::Square
          }

        class Icons < WhopSDK::Internal::Type::BaseModel
          attr_accessor card: WhopSDK::Models::PaymentMethodListResponse::IdealPaymentMethod::Icons::Card

          attr_accessor square: WhopSDK::Models::PaymentMethodListResponse::IdealPaymentMethod::Icons::Square

          def initialize: (
            card: WhopSDK::Models::PaymentMethodListResponse::IdealPaymentMethod::Icons::Card,
            square: WhopSDK::Models::PaymentMethodListResponse::IdealPaymentMethod::Icons::Square
          ) -> void

          def to_hash: -> {
            card: WhopSDK::Models::PaymentMethodListResponse::IdealPaymentMethod::Icons::Card,
            square: WhopSDK::Models::PaymentMethodListResponse::IdealPaymentMethod::Icons::Square
          }

          type card =
            {
              dark: WhopSDK::Models::PaymentMethodListResponse::IdealPaymentMethod::Icons::Card::Dark,
              light: WhopSDK::Models::PaymentMethodListResponse::IdealPaymentMethod::Icons::Card::Light
            }

          class Card < WhopSDK::Internal::Type::BaseModel
            attr_accessor dark: WhopSDK::Models::PaymentMethodListResponse::IdealPaymentMethod::Icons::Card::Dark

            attr_accessor light: WhopSDK::Models::PaymentMethodListResponse::IdealPaymentMethod::Icons::Card::Light

            def initialize: (
              dark: WhopSDK::Models::PaymentMethodListResponse::IdealPaymentMethod::Icons::Card::Dark,
              light: WhopSDK::Models::PaymentMethodListResponse::IdealPaymentMethod::Icons::Card::Light
            ) -> void

            def to_hash: -> {
              dark: WhopSDK::Models::PaymentMethodListResponse::IdealPaymentMethod::Icons::Card::Dark,
              light: WhopSDK::Models::PaymentMethodListResponse::IdealPaymentMethod::Icons::Card::Light
            }

            type dark =
              {
                :png_1x => String,
                :png_2x => String,
                :png_4x => String,
                svg: String
              }

            class Dark < WhopSDK::Internal::Type::BaseModel
              attr_accessor png_1x: String

              attr_accessor png_2x: String

              attr_accessor png_4x: String

              attr_accessor svg: String

              def initialize: (
                png_1x: String,
                png_2x: String,
                png_4x: String,
                svg: String
              ) -> void

              def to_hash: -> {
                :png_1x => String,
                :png_2x => String,
                :png_4x => String,
                svg: String
              }
            end

            type light =
              {
                :png_1x => String,
                :png_2x => String,
                :png_4x => String,
                svg: String
              }

            class Light < WhopSDK::Internal::Type::BaseModel
              attr_accessor png_1x: String

              attr_accessor png_2x: String

              attr_accessor png_4x: String

              attr_accessor svg: String

              def initialize: (
                png_1x: String,
                png_2x: String,
                png_4x: String,
                svg: String
              ) -> void

              def to_hash: -> {
                :png_1x => String,
                :png_2x => String,
                :png_4x => String,
                svg: String
              }
            end
          end

          type square =
            {
              dark: WhopSDK::Models::PaymentMethodListResponse::IdealPaymentMethod::Icons::Square::Dark,
              light: WhopSDK::Models::PaymentMethodListResponse::IdealPaymentMethod::Icons::Square::Light
            }

          class Square < WhopSDK::Internal::Type::BaseModel
            attr_accessor dark: WhopSDK::Models::PaymentMethodListResponse::IdealPaymentMethod::Icons::Square::Dark

            attr_accessor light: WhopSDK::Models::PaymentMethodListResponse::IdealPaymentMethod::Icons::Square::Light

            def initialize: (
              dark: WhopSDK::Models::PaymentMethodListResponse::IdealPaymentMethod::Icons::Square::Dark,
              light: WhopSDK::Models::PaymentMethodListResponse::IdealPaymentMethod::Icons::Square::Light
            ) -> void

            def to_hash: -> {
              dark: WhopSDK::Models::PaymentMethodListResponse::IdealPaymentMethod::Icons::Square::Dark,
              light: WhopSDK::Models::PaymentMethodListResponse::IdealPaymentMethod::Icons::Square::Light
            }

            type dark =
              {
                :png_1x => String,
                :png_2x => String,
                :png_4x => String,
                svg: String
              }

            class Dark < WhopSDK::Internal::Type::BaseModel
              attr_accessor png_1x: String

              attr_accessor png_2x: String

              attr_accessor png_4x: String

              attr_accessor svg: String

              def initialize: (
                png_1x: String,
                png_2x: String,
                png_4x: String,
                svg: String
              ) -> void

              def to_hash: -> {
                :png_1x => String,
                :png_2x => String,
                :png_4x => String,
                svg: String
              }
            end

            type light =
              {
                :png_1x => String,
                :png_2x => String,
                :png_4x => String,
                svg: String
              }

            class Light < WhopSDK::Internal::Type::BaseModel
              attr_accessor png_1x: String

              attr_accessor png_2x: String

              attr_accessor png_4x: String

              attr_accessor svg: String

              def initialize: (
                png_1x: String,
                png_2x: String,
                png_4x: String,
                svg: String
              ) -> void

              def to_hash: -> {
                :png_1x => String,
                :png_2x => String,
                :png_4x => String,
                svg: String
              }
            end
          end
        end

        type ideal = { bank: String?, bic: String? }

        class Ideal < WhopSDK::Internal::Type::BaseModel
          attr_accessor bank: String?

          attr_accessor bic: String?

          def initialize: (bank: String?, bic: String?) -> void

          def to_hash: -> { bank: String?, bic: String? }
        end
      end

      type sepa_debit_payment_method =
        {
          id: String,
          created_at: Time,
          icons: WhopSDK::Models::PaymentMethodListResponse::SepaDebitPaymentMethod::Icons,
          payment_method_type: WhopSDK::Models::payment_method_types,
          sepa_debit: WhopSDK::Models::PaymentMethodListResponse::SepaDebitPaymentMethod::SepaDebit,
          typename: :SepaDebitPaymentMethod
        }

      class SepaDebitPaymentMethod < WhopSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor created_at: Time

        attr_accessor icons: WhopSDK::Models::PaymentMethodListResponse::SepaDebitPaymentMethod::Icons

        attr_accessor payment_method_type: WhopSDK::Models::payment_method_types

        attr_accessor sepa_debit: WhopSDK::Models::PaymentMethodListResponse::SepaDebitPaymentMethod::SepaDebit

        attr_accessor typename: :SepaDebitPaymentMethod

        def initialize: (
          id: String,
          created_at: Time,
          icons: WhopSDK::Models::PaymentMethodListResponse::SepaDebitPaymentMethod::Icons,
          payment_method_type: WhopSDK::Models::payment_method_types,
          sepa_debit: WhopSDK::Models::PaymentMethodListResponse::SepaDebitPaymentMethod::SepaDebit,
          ?typename: :SepaDebitPaymentMethod
        ) -> void

        def to_hash: -> {
          id: String,
          created_at: Time,
          icons: WhopSDK::Models::PaymentMethodListResponse::SepaDebitPaymentMethod::Icons,
          payment_method_type: WhopSDK::Models::payment_method_types,
          sepa_debit: WhopSDK::Models::PaymentMethodListResponse::SepaDebitPaymentMethod::SepaDebit,
          typename: :SepaDebitPaymentMethod
        }

        type icons =
          {
            card: WhopSDK::Models::PaymentMethodListResponse::SepaDebitPaymentMethod::Icons::Card,
            square: WhopSDK::Models::PaymentMethodListResponse::SepaDebitPaymentMethod::Icons::Square
          }

        class Icons < WhopSDK::Internal::Type::BaseModel
          attr_accessor card: WhopSDK::Models::PaymentMethodListResponse::SepaDebitPaymentMethod::Icons::Card

          attr_accessor square: WhopSDK::Models::PaymentMethodListResponse::SepaDebitPaymentMethod::Icons::Square

          def initialize: (
            card: WhopSDK::Models::PaymentMethodListResponse::SepaDebitPaymentMethod::Icons::Card,
            square: WhopSDK::Models::PaymentMethodListResponse::SepaDebitPaymentMethod::Icons::Square
          ) -> void

          def to_hash: -> {
            card: WhopSDK::Models::PaymentMethodListResponse::SepaDebitPaymentMethod::Icons::Card,
            square: WhopSDK::Models::PaymentMethodListResponse::SepaDebitPaymentMethod::Icons::Square
          }

          type card =
            {
              dark: WhopSDK::Models::PaymentMethodListResponse::SepaDebitPaymentMethod::Icons::Card::Dark,
              light: WhopSDK::Models::PaymentMethodListResponse::SepaDebitPaymentMethod::Icons::Card::Light
            }

          class Card < WhopSDK::Internal::Type::BaseModel
            attr_accessor dark: WhopSDK::Models::PaymentMethodListResponse::SepaDebitPaymentMethod::Icons::Card::Dark

            attr_accessor light: WhopSDK::Models::PaymentMethodListResponse::SepaDebitPaymentMethod::Icons::Card::Light

            def initialize: (
              dark: WhopSDK::Models::PaymentMethodListResponse::SepaDebitPaymentMethod::Icons::Card::Dark,
              light: WhopSDK::Models::PaymentMethodListResponse::SepaDebitPaymentMethod::Icons::Card::Light
            ) -> void

            def to_hash: -> {
              dark: WhopSDK::Models::PaymentMethodListResponse::SepaDebitPaymentMethod::Icons::Card::Dark,
              light: WhopSDK::Models::PaymentMethodListResponse::SepaDebitPaymentMethod::Icons::Card::Light
            }

            type dark =
              {
                :png_1x => String,
                :png_2x => String,
                :png_4x => String,
                svg: String
              }

            class Dark < WhopSDK::Internal::Type::BaseModel
              attr_accessor png_1x: String

              attr_accessor png_2x: String

              attr_accessor png_4x: String

              attr_accessor svg: String

              def initialize: (
                png_1x: String,
                png_2x: String,
                png_4x: String,
                svg: String
              ) -> void

              def to_hash: -> {
                :png_1x => String,
                :png_2x => String,
                :png_4x => String,
                svg: String
              }
            end

            type light =
              {
                :png_1x => String,
                :png_2x => String,
                :png_4x => String,
                svg: String
              }

            class Light < WhopSDK::Internal::Type::BaseModel
              attr_accessor png_1x: String

              attr_accessor png_2x: String

              attr_accessor png_4x: String

              attr_accessor svg: String

              def initialize: (
                png_1x: String,
                png_2x: String,
                png_4x: String,
                svg: String
              ) -> void

              def to_hash: -> {
                :png_1x => String,
                :png_2x => String,
                :png_4x => String,
                svg: String
              }
            end
          end

          type square =
            {
              dark: WhopSDK::Models::PaymentMethodListResponse::SepaDebitPaymentMethod::Icons::Square::Dark,
              light: WhopSDK::Models::PaymentMethodListResponse::SepaDebitPaymentMethod::Icons::Square::Light
            }

          class Square < WhopSDK::Internal::Type::BaseModel
            attr_accessor dark: WhopSDK::Models::PaymentMethodListResponse::SepaDebitPaymentMethod::Icons::Square::Dark

            attr_accessor light: WhopSDK::Models::PaymentMethodListResponse::SepaDebitPaymentMethod::Icons::Square::Light

            def initialize: (
              dark: WhopSDK::Models::PaymentMethodListResponse::SepaDebitPaymentMethod::Icons::Square::Dark,
              light: WhopSDK::Models::PaymentMethodListResponse::SepaDebitPaymentMethod::Icons::Square::Light
            ) -> void

            def to_hash: -> {
              dark: WhopSDK::Models::PaymentMethodListResponse::SepaDebitPaymentMethod::Icons::Square::Dark,
              light: WhopSDK::Models::PaymentMethodListResponse::SepaDebitPaymentMethod::Icons::Square::Light
            }

            type dark =
              {
                :png_1x => String,
                :png_2x => String,
                :png_4x => String,
                svg: String
              }

            class Dark < WhopSDK::Internal::Type::BaseModel
              attr_accessor png_1x: String

              attr_accessor png_2x: String

              attr_accessor png_4x: String

              attr_accessor svg: String

              def initialize: (
                png_1x: String,
                png_2x: String,
                png_4x: String,
                svg: String
              ) -> void

              def to_hash: -> {
                :png_1x => String,
                :png_2x => String,
                :png_4x => String,
                svg: String
              }
            end

            type light =
              {
                :png_1x => String,
                :png_2x => String,
                :png_4x => String,
                svg: String
              }

            class Light < WhopSDK::Internal::Type::BaseModel
              attr_accessor png_1x: String

              attr_accessor png_2x: String

              attr_accessor png_4x: String

              attr_accessor svg: String

              def initialize: (
                png_1x: String,
                png_2x: String,
                png_4x: String,
                svg: String
              ) -> void

              def to_hash: -> {
                :png_1x => String,
                :png_2x => String,
                :png_4x => String,
                svg: String
              }
            end
          end
        end

        type sepa_debit =
          {
            bank_code: String?,
            branch_code: String?,
            country: String?,
            :last4 => String?
          }

        class SepaDebit < WhopSDK::Internal::Type::BaseModel
          attr_accessor bank_code: String?

          attr_accessor branch_code: String?

          attr_accessor country: String?

          attr_accessor last4: String?

          def initialize: (
            bank_code: String?,
            branch_code: String?,
            country: String?,
            last4: String?
          ) -> void

          def to_hash: -> {
            bank_code: String?,
            branch_code: String?,
            country: String?,
            :last4 => String?
          }
        end
      end

      type platform_balance_payment_method =
        {
          id: String,
          created_at: Time,
          icons: WhopSDK::Models::PaymentMethodListResponse::PlatformBalancePaymentMethod::Icons,
          payment_method_type: WhopSDK::Models::payment_method_types,
          platform_balance: WhopSDK::Models::PaymentMethodListResponse::PlatformBalancePaymentMethod::PlatformBalance,
          typename: :PlatformBalancePaymentMethod
        }

      class PlatformBalancePaymentMethod < WhopSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor created_at: Time

        attr_accessor icons: WhopSDK::Models::PaymentMethodListResponse::PlatformBalancePaymentMethod::Icons

        attr_accessor payment_method_type: WhopSDK::Models::payment_method_types

        attr_accessor platform_balance: WhopSDK::Models::PaymentMethodListResponse::PlatformBalancePaymentMethod::PlatformBalance

        attr_accessor typename: :PlatformBalancePaymentMethod

        def initialize: (
          id: String,
          created_at: Time,
          icons: WhopSDK::Models::PaymentMethodListResponse::PlatformBalancePaymentMethod::Icons,
          payment_method_type: WhopSDK::Models::payment_method_types,
          platform_balance: WhopSDK::Models::PaymentMethodListResponse::PlatformBalancePaymentMethod::PlatformBalance,
          ?typename: :PlatformBalancePaymentMethod
        ) -> void

        def to_hash: -> {
          id: String,
          created_at: Time,
          icons: WhopSDK::Models::PaymentMethodListResponse::PlatformBalancePaymentMethod::Icons,
          payment_method_type: WhopSDK::Models::payment_method_types,
          platform_balance: WhopSDK::Models::PaymentMethodListResponse::PlatformBalancePaymentMethod::PlatformBalance,
          typename: :PlatformBalancePaymentMethod
        }

        type icons =
          {
            card: WhopSDK::Models::PaymentMethodListResponse::PlatformBalancePaymentMethod::Icons::Card,
            square: WhopSDK::Models::PaymentMethodListResponse::PlatformBalancePaymentMethod::Icons::Square
          }

        class Icons < WhopSDK::Internal::Type::BaseModel
          attr_accessor card: WhopSDK::Models::PaymentMethodListResponse::PlatformBalancePaymentMethod::Icons::Card

          attr_accessor square: WhopSDK::Models::PaymentMethodListResponse::PlatformBalancePaymentMethod::Icons::Square

          def initialize: (
            card: WhopSDK::Models::PaymentMethodListResponse::PlatformBalancePaymentMethod::Icons::Card,
            square: WhopSDK::Models::PaymentMethodListResponse::PlatformBalancePaymentMethod::Icons::Square
          ) -> void

          def to_hash: -> {
            card: WhopSDK::Models::PaymentMethodListResponse::PlatformBalancePaymentMethod::Icons::Card,
            square: WhopSDK::Models::PaymentMethodListResponse::PlatformBalancePaymentMethod::Icons::Square
          }

          type card =
            {
              dark: WhopSDK::Models::PaymentMethodListResponse::PlatformBalancePaymentMethod::Icons::Card::Dark,
              light: WhopSDK::Models::PaymentMethodListResponse::PlatformBalancePaymentMethod::Icons::Card::Light
            }

          class Card < WhopSDK::Internal::Type::BaseModel
            attr_accessor dark: WhopSDK::Models::PaymentMethodListResponse::PlatformBalancePaymentMethod::Icons::Card::Dark

            attr_accessor light: WhopSDK::Models::PaymentMethodListResponse::PlatformBalancePaymentMethod::Icons::Card::Light

            def initialize: (
              dark: WhopSDK::Models::PaymentMethodListResponse::PlatformBalancePaymentMethod::Icons::Card::Dark,
              light: WhopSDK::Models::PaymentMethodListResponse::PlatformBalancePaymentMethod::Icons::Card::Light
            ) -> void

            def to_hash: -> {
              dark: WhopSDK::Models::PaymentMethodListResponse::PlatformBalancePaymentMethod::Icons::Card::Dark,
              light: WhopSDK::Models::PaymentMethodListResponse::PlatformBalancePaymentMethod::Icons::Card::Light
            }

            type dark =
              {
                :png_1x => String,
                :png_2x => String,
                :png_4x => String,
                svg: String
              }

            class Dark < WhopSDK::Internal::Type::BaseModel
              attr_accessor png_1x: String

              attr_accessor png_2x: String

              attr_accessor png_4x: String

              attr_accessor svg: String

              def initialize: (
                png_1x: String,
                png_2x: String,
                png_4x: String,
                svg: String
              ) -> void

              def to_hash: -> {
                :png_1x => String,
                :png_2x => String,
                :png_4x => String,
                svg: String
              }
            end

            type light =
              {
                :png_1x => String,
                :png_2x => String,
                :png_4x => String,
                svg: String
              }

            class Light < WhopSDK::Internal::Type::BaseModel
              attr_accessor png_1x: String

              attr_accessor png_2x: String

              attr_accessor png_4x: String

              attr_accessor svg: String

              def initialize: (
                png_1x: String,
                png_2x: String,
                png_4x: String,
                svg: String
              ) -> void

              def to_hash: -> {
                :png_1x => String,
                :png_2x => String,
                :png_4x => String,
                svg: String
              }
            end
          end

          type square =
            {
              dark: WhopSDK::Models::PaymentMethodListResponse::PlatformBalancePaymentMethod::Icons::Square::Dark,
              light: WhopSDK::Models::PaymentMethodListResponse::PlatformBalancePaymentMethod::Icons::Square::Light
            }

          class Square < WhopSDK::Internal::Type::BaseModel
            attr_accessor dark: WhopSDK::Models::PaymentMethodListResponse::PlatformBalancePaymentMethod::Icons::Square::Dark

            attr_accessor light: WhopSDK::Models::PaymentMethodListResponse::PlatformBalancePaymentMethod::Icons::Square::Light

            def initialize: (
              dark: WhopSDK::Models::PaymentMethodListResponse::PlatformBalancePaymentMethod::Icons::Square::Dark,
              light: WhopSDK::Models::PaymentMethodListResponse::PlatformBalancePaymentMethod::Icons::Square::Light
            ) -> void

            def to_hash: -> {
              dark: WhopSDK::Models::PaymentMethodListResponse::PlatformBalancePaymentMethod::Icons::Square::Dark,
              light: WhopSDK::Models::PaymentMethodListResponse::PlatformBalancePaymentMethod::Icons::Square::Light
            }

            type dark =
              {
                :png_1x => String,
                :png_2x => String,
                :png_4x => String,
                svg: String
              }

            class Dark < WhopSDK::Internal::Type::BaseModel
              attr_accessor png_1x: String

              attr_accessor png_2x: String

              attr_accessor png_4x: String

              attr_accessor svg: String

              def initialize: (
                png_1x: String,
                png_2x: String,
                png_4x: String,
                svg: String
              ) -> void

              def to_hash: -> {
                :png_1x => String,
                :png_2x => String,
                :png_4x => String,
                svg: String
              }
            end

            type light =
              {
                :png_1x => String,
                :png_2x => String,
                :png_4x => String,
                svg: String
              }

            class Light < WhopSDK::Internal::Type::BaseModel
              attr_accessor png_1x: String

              attr_accessor png_2x: String

              attr_accessor png_4x: String

              attr_accessor svg: String

              def initialize: (
                png_1x: String,
                png_2x: String,
                png_4x: String,
                svg: String
              ) -> void

              def to_hash: -> {
                :png_1x => String,
                :png_2x => String,
                :png_4x => String,
                svg: String
              }
            end
          end
        end

        type platform_balance =
          {
            account: WhopSDK::Models::PaymentMethodListResponse::PlatformBalancePaymentMethod::PlatformBalance::Account?,
            balances: ::Array[WhopSDK::Models::PaymentMethodListResponse::PlatformBalancePaymentMethod::PlatformBalance::Balance],
            spendable: bool
          }

        class PlatformBalance < WhopSDK::Internal::Type::BaseModel
          attr_accessor account: WhopSDK::Models::PaymentMethodListResponse::PlatformBalancePaymentMethod::PlatformBalance::Account?

          attr_accessor balances: ::Array[WhopSDK::Models::PaymentMethodListResponse::PlatformBalancePaymentMethod::PlatformBalance::Balance]

          attr_accessor spendable: bool

          def initialize: (
            account: WhopSDK::Models::PaymentMethodListResponse::PlatformBalancePaymentMethod::PlatformBalance::Account?,
            balances: ::Array[WhopSDK::Models::PaymentMethodListResponse::PlatformBalancePaymentMethod::PlatformBalance::Balance],
            spendable: bool
          ) -> void

          def to_hash: -> {
            account: WhopSDK::Models::PaymentMethodListResponse::PlatformBalancePaymentMethod::PlatformBalance::Account?,
            balances: ::Array[WhopSDK::Models::PaymentMethodListResponse::PlatformBalancePaymentMethod::PlatformBalance::Balance],
            spendable: bool
          }

          type account =
            {
              id: String,
              logo: WhopSDK::Models::PaymentMethodListResponse::PlatformBalancePaymentMethod::PlatformBalance::Account::Logo?,
              title: String
            }

          class Account < WhopSDK::Internal::Type::BaseModel
            attr_accessor id: String

            attr_accessor logo: WhopSDK::Models::PaymentMethodListResponse::PlatformBalancePaymentMethod::PlatformBalance::Account::Logo?

            attr_accessor title: String

            def initialize: (
              id: String,
              logo: WhopSDK::Models::PaymentMethodListResponse::PlatformBalancePaymentMethod::PlatformBalance::Account::Logo?,
              title: String
            ) -> void

            def to_hash: -> {
              id: String,
              logo: WhopSDK::Models::PaymentMethodListResponse::PlatformBalancePaymentMethod::PlatformBalance::Account::Logo?,
              title: String
            }

            type logo = { url: String? }

            class Logo < WhopSDK::Internal::Type::BaseModel
              attr_accessor url: String?

              def initialize: (url: String?) -> void

              def to_hash: -> { url: String? }
            end
          end

          type balance =
            {
              amount: String,
              currency: WhopSDK::Models::currency,
              decimals: Integer,
              display_decimals: Integer
            }

          class Balance < WhopSDK::Internal::Type::BaseModel
            attr_accessor amount: String

            attr_accessor currency: WhopSDK::Models::currency

            attr_accessor decimals: Integer

            attr_accessor display_decimals: Integer

            def initialize: (
              amount: String,
              currency: WhopSDK::Models::currency,
              decimals: Integer,
              display_decimals: Integer
            ) -> void

            def to_hash: -> {
              amount: String,
              currency: WhopSDK::Models::currency,
              decimals: Integer,
              display_decimals: Integer
            }
          end
        end
      end

      def self?.variants: -> ::Array[WhopSDK::Models::payment_method_list_response]
    end
  end
end
