module WhopSDK
  module Models
    type payout_account_status_updated_webhook_event =
      {
        id: String,
        api_version: :v1,
        data: WhopSDK::PayoutAccountStatusUpdatedWebhookEvent::Data,
        timestamp: Time,
        type: :"payout_account.status_updated",
        company_id: String?
      }

    class PayoutAccountStatusUpdatedWebhookEvent < WhopSDK::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor api_version: :v1

      attr_accessor data: WhopSDK::PayoutAccountStatusUpdatedWebhookEvent::Data

      attr_accessor timestamp: Time

      attr_accessor type: :"payout_account.status_updated"

      attr_accessor company_id: String?

      def initialize: (
        id: String,
        data: WhopSDK::PayoutAccountStatusUpdatedWebhookEvent::Data,
        timestamp: Time,
        ?company_id: String?,
        ?api_version: :v1,
        ?type: :"payout_account.status_updated"
      ) -> void

      def to_hash: -> {
        id: String,
        api_version: :v1,
        data: WhopSDK::PayoutAccountStatusUpdatedWebhookEvent::Data,
        timestamp: Time,
        type: :"payout_account.status_updated",
        company_id: String?
      }

      type data =
        {
          id: String,
          address: WhopSDK::PayoutAccountStatusUpdatedWebhookEvent::Data::Address?,
          business_name: String?,
          business_representative: WhopSDK::PayoutAccountStatusUpdatedWebhookEvent::Data::BusinessRepresentative?,
          email: String?,
          latest_verification: WhopSDK::PayoutAccountStatusUpdatedWebhookEvent::Data::LatestVerification?,
          phone: String?,
          status: WhopSDK::Models::payout_account_calculated_statuses?
        }

      class Data < WhopSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor address: WhopSDK::PayoutAccountStatusUpdatedWebhookEvent::Data::Address?

        attr_accessor business_name: String?

        attr_accessor business_representative: WhopSDK::PayoutAccountStatusUpdatedWebhookEvent::Data::BusinessRepresentative?

        attr_accessor email: String?

        attr_accessor latest_verification: WhopSDK::PayoutAccountStatusUpdatedWebhookEvent::Data::LatestVerification?

        attr_accessor phone: String?

        attr_accessor status: WhopSDK::Models::payout_account_calculated_statuses?

        def initialize: (
          id: String,
          address: WhopSDK::PayoutAccountStatusUpdatedWebhookEvent::Data::Address?,
          business_name: String?,
          business_representative: WhopSDK::PayoutAccountStatusUpdatedWebhookEvent::Data::BusinessRepresentative?,
          email: String?,
          latest_verification: WhopSDK::PayoutAccountStatusUpdatedWebhookEvent::Data::LatestVerification?,
          phone: String?,
          status: WhopSDK::Models::payout_account_calculated_statuses?
        ) -> void

        def to_hash: -> {
          id: String,
          address: WhopSDK::PayoutAccountStatusUpdatedWebhookEvent::Data::Address?,
          business_name: String?,
          business_representative: WhopSDK::PayoutAccountStatusUpdatedWebhookEvent::Data::BusinessRepresentative?,
          email: String?,
          latest_verification: WhopSDK::PayoutAccountStatusUpdatedWebhookEvent::Data::LatestVerification?,
          phone: String?,
          status: WhopSDK::Models::payout_account_calculated_statuses?
        }

        type address =
          {
            city: String?,
            country: String?,
            :line1 => String?,
            :line2 => String?,
            postal_code: String?,
            state: String?
          }

        class Address < WhopSDK::Internal::Type::BaseModel
          attr_accessor city: String?

          attr_accessor country: String?

          attr_accessor line1: String?

          attr_accessor line2: String?

          attr_accessor postal_code: String?

          attr_accessor state: String?

          def initialize: (
            city: String?,
            country: String?,
            line1: String?,
            line2: String?,
            postal_code: String?,
            state: String?
          ) -> void

          def to_hash: -> {
            city: String?,
            country: String?,
            :line1 => String?,
            :line2 => String?,
            postal_code: String?,
            state: String?
          }
        end

        type business_representative =
          {
            date_of_birth: String?,
            first_name: String?,
            last_name: String?,
            middle_name: String?
          }

        class BusinessRepresentative < WhopSDK::Internal::Type::BaseModel
          attr_accessor date_of_birth: String?

          attr_accessor first_name: String?

          attr_accessor last_name: String?

          attr_accessor middle_name: String?

          def initialize: (
            date_of_birth: String?,
            first_name: String?,
            last_name: String?,
            middle_name: String?
          ) -> void

          def to_hash: -> {
            date_of_birth: String?,
            first_name: String?,
            last_name: String?,
            middle_name: String?
          }
        end

        type latest_verification =
          {
            id: String,
            last_error_code: WhopSDK::Models::PayoutAccountStatusUpdatedWebhookEvent::Data::LatestVerification::last_error_code?,
            last_error_reason: String?,
            status: WhopSDK::Models::PayoutAccountStatusUpdatedWebhookEvent::Data::LatestVerification::status
          }

        class LatestVerification < WhopSDK::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor last_error_code: WhopSDK::Models::PayoutAccountStatusUpdatedWebhookEvent::Data::LatestVerification::last_error_code?

          attr_accessor last_error_reason: String?

          attr_accessor status: WhopSDK::Models::PayoutAccountStatusUpdatedWebhookEvent::Data::LatestVerification::status

          def initialize: (
            id: String,
            last_error_code: WhopSDK::Models::PayoutAccountStatusUpdatedWebhookEvent::Data::LatestVerification::last_error_code?,
            last_error_reason: String?,
            status: WhopSDK::Models::PayoutAccountStatusUpdatedWebhookEvent::Data::LatestVerification::status
          ) -> void

          def to_hash: -> {
            id: String,
            last_error_code: WhopSDK::Models::PayoutAccountStatusUpdatedWebhookEvent::Data::LatestVerification::last_error_code?,
            last_error_reason: String?,
            status: WhopSDK::Models::PayoutAccountStatusUpdatedWebhookEvent::Data::LatestVerification::status
          }

          type last_error_code =
            :abandoned
            | :consent_declined
            | :country_not_supported
            | :device_not_supported
            | :document_expired
            | :document_type_not_supported
            | :document_unverified_other
            | :email_unverified_other
            | :email_verification_declined
            | :id_number_insufficient_document_data
            | :id_number_mismatch
            | :id_number_unverified_other
            | :phone_unverified_other
            | :phone_verification_declined
            | :selfie_document_missing_photo
            | :selfie_face_mismatch
            | :selfie_manipulated
            | :selfie_unverified_other
            | :under_supported_age

          module LastErrorCode
            extend WhopSDK::Internal::Type::Enum

            ABANDONED: :abandoned
            CONSENT_DECLINED: :consent_declined
            COUNTRY_NOT_SUPPORTED: :country_not_supported
            DEVICE_NOT_SUPPORTED: :device_not_supported
            DOCUMENT_EXPIRED: :document_expired
            DOCUMENT_TYPE_NOT_SUPPORTED: :document_type_not_supported
            DOCUMENT_UNVERIFIED_OTHER: :document_unverified_other
            EMAIL_UNVERIFIED_OTHER: :email_unverified_other
            EMAIL_VERIFICATION_DECLINED: :email_verification_declined
            ID_NUMBER_INSUFFICIENT_DOCUMENT_DATA: :id_number_insufficient_document_data
            ID_NUMBER_MISMATCH: :id_number_mismatch
            ID_NUMBER_UNVERIFIED_OTHER: :id_number_unverified_other
            PHONE_UNVERIFIED_OTHER: :phone_unverified_other
            PHONE_VERIFICATION_DECLINED: :phone_verification_declined
            SELFIE_DOCUMENT_MISSING_PHOTO: :selfie_document_missing_photo
            SELFIE_FACE_MISMATCH: :selfie_face_mismatch
            SELFIE_MANIPULATED: :selfie_manipulated
            SELFIE_UNVERIFIED_OTHER: :selfie_unverified_other
            UNDER_SUPPORTED_AGE: :under_supported_age

            def self?.values: -> ::Array[WhopSDK::Models::PayoutAccountStatusUpdatedWebhookEvent::Data::LatestVerification::last_error_code]
          end

          type status =
            :requires_input
            | :processing
            | :verified
            | :canceled
            | :created
            | :started
            | :submitted
            | :approved
            | :declined
            | :resubmission_requested
            | :expired
            | :abandoned
            | :review
            | :action_required

          module Status
            extend WhopSDK::Internal::Type::Enum

            REQUIRES_INPUT: :requires_input
            PROCESSING: :processing
            VERIFIED: :verified
            CANCELED: :canceled
            CREATED: :created
            STARTED: :started
            SUBMITTED: :submitted
            APPROVED: :approved
            DECLINED: :declined
            RESUBMISSION_REQUESTED: :resubmission_requested
            EXPIRED: :expired
            ABANDONED: :abandoned
            REVIEW: :review
            ACTION_REQUIRED: :action_required

            def self?.values: -> ::Array[WhopSDK::Models::PayoutAccountStatusUpdatedWebhookEvent::Data::LatestVerification::status]
          end
        end
      end
    end
  end
end
