module WhopSDK
  module Models
    type payout_method_created_webhook_event =
      {
        id: String,
        api_version: :v1,
        data: WhopSDK::PayoutMethodCreatedWebhookEvent::Data,
        timestamp: Time,
        type: :"payout_method.created",
        company_id: String?
      }

    class PayoutMethodCreatedWebhookEvent < WhopSDK::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor api_version: :v1

      attr_accessor data: WhopSDK::PayoutMethodCreatedWebhookEvent::Data

      attr_accessor timestamp: Time

      attr_accessor type: :"payout_method.created"

      attr_accessor company_id: String?

      def initialize: (
        id: String,
        data: WhopSDK::PayoutMethodCreatedWebhookEvent::Data,
        timestamp: Time,
        ?company_id: String?,
        ?api_version: :v1,
        ?type: :"payout_method.created"
      ) -> void

      def to_hash: -> {
        id: String,
        api_version: :v1,
        data: WhopSDK::PayoutMethodCreatedWebhookEvent::Data,
        timestamp: Time,
        type: :"payout_method.created",
        company_id: String?
      }

      type data =
        {
          id: String,
          account_reference: String?,
          company: WhopSDK::PayoutMethodCreatedWebhookEvent::Data::Company?,
          created_at: Time,
          currency: String,
          destination: WhopSDK::PayoutMethodCreatedWebhookEvent::Data::Destination?,
          institution_name: String?,
          is_default: bool,
          nickname: String?
        }

      class Data < WhopSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor account_reference: String?

        attr_accessor company: WhopSDK::PayoutMethodCreatedWebhookEvent::Data::Company?

        attr_accessor created_at: Time

        attr_accessor currency: String

        attr_accessor destination: WhopSDK::PayoutMethodCreatedWebhookEvent::Data::Destination?

        attr_accessor institution_name: String?

        attr_accessor is_default: bool

        attr_accessor nickname: String?

        def initialize: (
          id: String,
          account_reference: String?,
          company: WhopSDK::PayoutMethodCreatedWebhookEvent::Data::Company?,
          created_at: Time,
          currency: String,
          destination: WhopSDK::PayoutMethodCreatedWebhookEvent::Data::Destination?,
          institution_name: String?,
          is_default: bool,
          nickname: String?
        ) -> void

        def to_hash: -> {
          id: String,
          account_reference: String?,
          company: WhopSDK::PayoutMethodCreatedWebhookEvent::Data::Company?,
          created_at: Time,
          currency: String,
          destination: WhopSDK::PayoutMethodCreatedWebhookEvent::Data::Destination?,
          institution_name: String?,
          is_default: bool,
          nickname: String?
        }

        type company = { id: String }

        class Company < WhopSDK::Internal::Type::BaseModel
          attr_accessor id: String

          def initialize: (id: String) -> void

          def to_hash: -> { id: String }
        end

        type destination =
          {
            category: WhopSDK::Models::payout_destination_category,
            country_code: String,
            name: String
          }

        class Destination < WhopSDK::Internal::Type::BaseModel
          attr_accessor category: WhopSDK::Models::payout_destination_category

          attr_accessor country_code: String

          attr_accessor name: String

          def initialize: (
            category: WhopSDK::Models::payout_destination_category,
            country_code: String,
            name: String
          ) -> void

          def to_hash: -> {
            category: WhopSDK::Models::payout_destination_category,
            country_code: String,
            name: String
          }
        end
      end
    end
  end
end
