module WhopSDK
  module Models
    type payout_method_created_webhook_event =
      {
        id: String,
        api_version: :v1,
        data: WhopSDK::PayoutMethodCreatedWebhookEvent::Data,
        timestamp: Time,
        type: :"payout_method.created"
      }

    class PayoutMethodCreatedWebhookEvent < WhopSDK::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor api_version: :v1

      attr_accessor data: WhopSDK::PayoutMethodCreatedWebhookEvent::Data

      attr_accessor timestamp: Time

      attr_accessor type: :"payout_method.created"

      def initialize: (
        id: String,
        data: WhopSDK::PayoutMethodCreatedWebhookEvent::Data,
        timestamp: Time,
        ?api_version: :v1,
        ?type: :"payout_method.created"
      ) -> void

      def to_hash: -> {
        id: String,
        api_version: :v1,
        data: WhopSDK::PayoutMethodCreatedWebhookEvent::Data,
        timestamp: Time,
        type: :"payout_method.created"
      }

      type data =
        {
          id: String,
          currency: String,
          destination: WhopSDK::PayoutMethodCreatedWebhookEvent::Data::Destination?,
          nickname: String?
        }

      class Data < WhopSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor currency: String

        attr_accessor destination: WhopSDK::PayoutMethodCreatedWebhookEvent::Data::Destination?

        attr_accessor nickname: String?

        def initialize: (
          id: String,
          currency: String,
          destination: WhopSDK::PayoutMethodCreatedWebhookEvent::Data::Destination?,
          nickname: String?
        ) -> void

        def to_hash: -> {
          id: String,
          currency: String,
          destination: WhopSDK::PayoutMethodCreatedWebhookEvent::Data::Destination?,
          nickname: String?
        }

        type destination =
          {
            category: WhopSDK::Models::PayoutMethodCreatedWebhookEvent::Data::Destination::category,
            country_code: String,
            name: String
          }

        class Destination < WhopSDK::Internal::Type::BaseModel
          attr_accessor category: WhopSDK::Models::PayoutMethodCreatedWebhookEvent::Data::Destination::category

          attr_accessor country_code: String

          attr_accessor name: String

          def initialize: (
            category: WhopSDK::Models::PayoutMethodCreatedWebhookEvent::Data::Destination::category,
            country_code: String,
            name: String
          ) -> void

          def to_hash: -> {
            category: WhopSDK::Models::PayoutMethodCreatedWebhookEvent::Data::Destination::category,
            country_code: String,
            name: String
          }

          type category =
            :crypto
            | :rtp
            | :next_day_bank
            | :bank_wire
            | :digital_wallet
            | :unknown

          module Category
            extend WhopSDK::Internal::Type::Enum

            CRYPTO: :crypto
            RTP: :rtp
            NEXT_DAY_BANK: :next_day_bank
            BANK_WIRE: :bank_wire
            DIGITAL_WALLET: :digital_wallet
            UNKNOWN: :unknown

            def self?.values: -> ::Array[WhopSDK::Models::PayoutMethodCreatedWebhookEvent::Data::Destination::category]
          end
        end
      end
    end
  end
end
