module WhopSDK
  module Models
    type payout_method_list_response =
      {
        id: String,
        account_reference: String?,
        company: WhopSDK::Models::PayoutMethodListResponse::Company?,
        created_at: Time,
        currency: String,
        destination: WhopSDK::Models::PayoutMethodListResponse::Destination?,
        institution_name: String?,
        is_default: bool,
        nickname: String?
      }

    class PayoutMethodListResponse < WhopSDK::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor account_reference: String?

      attr_accessor company: WhopSDK::Models::PayoutMethodListResponse::Company?

      attr_accessor created_at: Time

      attr_accessor currency: String

      attr_accessor destination: WhopSDK::Models::PayoutMethodListResponse::Destination?

      attr_accessor institution_name: String?

      attr_accessor is_default: bool

      attr_accessor nickname: String?

      def initialize: (
        id: String,
        account_reference: String?,
        company: WhopSDK::Models::PayoutMethodListResponse::Company?,
        created_at: Time,
        currency: String,
        destination: WhopSDK::Models::PayoutMethodListResponse::Destination?,
        institution_name: String?,
        is_default: bool,
        nickname: String?
      ) -> void

      def to_hash: -> {
        id: String,
        account_reference: String?,
        company: WhopSDK::Models::PayoutMethodListResponse::Company?,
        created_at: Time,
        currency: String,
        destination: WhopSDK::Models::PayoutMethodListResponse::Destination?,
        institution_name: String?,
        is_default: bool,
        nickname: String?
      }

      type company = { id: String }

      class Company < WhopSDK::Internal::Type::BaseModel
        attr_accessor id: String

        def initialize: (id: String) -> void

        def to_hash: -> { id: String }
      end

      type destination =
        {
          category: WhopSDK::Models::PayoutMethodListResponse::Destination::category,
          country_code: String,
          name: String
        }

      class Destination < WhopSDK::Internal::Type::BaseModel
        attr_accessor category: WhopSDK::Models::PayoutMethodListResponse::Destination::category

        attr_accessor country_code: String

        attr_accessor name: String

        def initialize: (
          category: WhopSDK::Models::PayoutMethodListResponse::Destination::category,
          country_code: String,
          name: String
        ) -> void

        def to_hash: -> {
          category: WhopSDK::Models::PayoutMethodListResponse::Destination::category,
          country_code: String,
          name: String
        }

        type category =
          :crypto
          | :rtp
          | :next_day_bank
          | :bank_wire
          | :digital_wallet
          | :unknown

        module Category
          extend WhopSDK::Internal::Type::Enum

          CRYPTO: :crypto
          RTP: :rtp
          NEXT_DAY_BANK: :next_day_bank
          BANK_WIRE: :bank_wire
          DIGITAL_WALLET: :digital_wallet
          UNKNOWN: :unknown

          def self?.values: -> ::Array[WhopSDK::Models::PayoutMethodListResponse::Destination::category]
        end
      end
    end
  end
end
