module WhopSDK
  module Models
    type person_retrieve_params =
      { person_id: String, account_id: String, from: Integer, to: Integer }
      & WhopSDK::Internal::Type::request_parameters

    class PersonRetrieveParams < WhopSDK::Internal::Type::BaseModel
      extend WhopSDK::Internal::Type::RequestParameters::Converter
      include WhopSDK::Internal::Type::RequestParameters

      attr_accessor person_id: String

      attr_reader account_id: String?

      def account_id=: (String) -> String

      attr_reader from: Integer?

      def from=: (Integer) -> Integer

      attr_reader to: Integer?

      def to=: (Integer) -> Integer

      def initialize: (
        person_id: String,
        ?account_id: String,
        ?from: Integer,
        ?to: Integer,
        ?request_options: WhopSDK::request_opts
      ) -> void

      def to_hash: -> {
        person_id: String,
        account_id: String,
        from: Integer,
        to: Integer,
        request_options: WhopSDK::RequestOptions
      }
    end
  end
end
