module WhopSDK
  module Models
    type plan_calculate_tax_response =
      {
        currency: String,
        status: WhopSDK::Models::PlanCalculateTaxResponse::status,
        subtotal: Integer,
        tax_amount: Integer,
        tax_behavior: WhopSDK::Models::PlanCalculateTaxResponse::tax_behavior,
        total: Integer
      }

    class PlanCalculateTaxResponse < WhopSDK::Internal::Type::BaseModel
      attr_accessor currency: String

      attr_accessor status: WhopSDK::Models::PlanCalculateTaxResponse::status

      attr_accessor subtotal: Integer

      attr_accessor tax_amount: Integer

      attr_accessor tax_behavior: WhopSDK::Models::PlanCalculateTaxResponse::tax_behavior

      attr_accessor total: Integer

      def initialize: (
        currency: String,
        status: WhopSDK::Models::PlanCalculateTaxResponse::status,
        subtotal: Integer,
        tax_amount: Integer,
        tax_behavior: WhopSDK::Models::PlanCalculateTaxResponse::tax_behavior,
        total: Integer
      ) -> void

      def to_hash: -> {
        currency: String,
        status: WhopSDK::Models::PlanCalculateTaxResponse::status,
        subtotal: Integer,
        tax_amount: Integer,
        tax_behavior: WhopSDK::Models::PlanCalculateTaxResponse::tax_behavior,
        total: Integer
      }

      type status = :calculated | :not_calculated

      module Status
        extend WhopSDK::Internal::Type::Enum

        CALCULATED: :calculated
        NOT_CALCULATED: :not_calculated

        def self?.values: -> ::Array[WhopSDK::Models::PlanCalculateTaxResponse::status]
      end

      type tax_behavior = :exclusive | :inclusive

      module TaxBehavior
        extend WhopSDK::Internal::Type::Enum

        EXCLUSIVE: :exclusive
        INCLUSIVE: :inclusive

        def self?.values: -> ::Array[WhopSDK::Models::PlanCalculateTaxResponse::tax_behavior]
      end
    end
  end
end
