module WhopSDK
  module Models
    type plan_list_response =
      {
        id: String,
        adaptive_pricing_enabled: bool,
        billing_period: Float?,
        company: top?,
        created_at: String,
        currency: String,
        description: String?,
        expiration_days: Float?,
        initial_price: Float,
        internal_notes: String?,
        invoice: top?,
        member_count: Float?,
        metadata: top?,
        payment_method_configuration: top?,
        plan_type: String,
        product: top?,
        purchase_url: String,
        release_method: String,
        renewal_price: Float,
        split_pay_required_payments: Float?,
        stock: Float?,
        three_ds_level: String?,
        title: String?,
        trial_period_days: Float?,
        unlimited_stock: bool,
        updated_at: String,
        visibility: String
      }

    class PlanListResponse < WhopSDK::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor adaptive_pricing_enabled: bool

      attr_accessor billing_period: Float?

      attr_accessor company: top?

      attr_accessor created_at: String

      attr_accessor currency: String

      attr_accessor description: String?

      attr_accessor expiration_days: Float?

      attr_accessor initial_price: Float

      attr_accessor internal_notes: String?

      attr_accessor invoice: top?

      attr_accessor member_count: Float?

      attr_accessor metadata: top?

      attr_accessor payment_method_configuration: top?

      attr_accessor plan_type: String

      attr_accessor product: top?

      attr_accessor purchase_url: String

      attr_accessor release_method: String

      attr_accessor renewal_price: Float

      attr_accessor split_pay_required_payments: Float?

      attr_accessor stock: Float?

      attr_accessor three_ds_level: String?

      attr_accessor title: String?

      attr_accessor trial_period_days: Float?

      attr_accessor unlimited_stock: bool

      attr_accessor updated_at: String

      attr_accessor visibility: String

      def initialize: (
        id: String,
        adaptive_pricing_enabled: bool,
        billing_period: Float?,
        company: top?,
        created_at: String,
        currency: String,
        description: String?,
        expiration_days: Float?,
        initial_price: Float,
        internal_notes: String?,
        invoice: top?,
        member_count: Float?,
        metadata: top?,
        payment_method_configuration: top?,
        plan_type: String,
        product: top?,
        purchase_url: String,
        release_method: String,
        renewal_price: Float,
        split_pay_required_payments: Float?,
        stock: Float?,
        three_ds_level: String?,
        title: String?,
        trial_period_days: Float?,
        unlimited_stock: bool,
        updated_at: String,
        visibility: String
      ) -> void

      def to_hash: -> {
        id: String,
        adaptive_pricing_enabled: bool,
        billing_period: Float?,
        company: top?,
        created_at: String,
        currency: String,
        description: String?,
        expiration_days: Float?,
        initial_price: Float,
        internal_notes: String?,
        invoice: top?,
        member_count: Float?,
        metadata: top?,
        payment_method_configuration: top?,
        plan_type: String,
        product: top?,
        purchase_url: String,
        release_method: String,
        renewal_price: Float,
        split_pay_required_payments: Float?,
        stock: Float?,
        three_ds_level: String?,
        title: String?,
        trial_period_days: Float?,
        unlimited_stock: bool,
        updated_at: String,
        visibility: String
      }
    end
  end
end
