module WhopSDK
  module Models
    type product_list_params =
      {
        company_id: String,
        access_pass_types: ::Array[String],
        after: String,
        before: String,
        direction: WhopSDK::Models::ProductListParams::direction,
        first: Integer,
        last: Integer,
        order: String,
        visibilities: ::Array[String]
      }
      & WhopSDK::Internal::Type::request_parameters

    class ProductListParams < WhopSDK::Internal::Type::BaseModel
      extend WhopSDK::Internal::Type::RequestParameters::Converter
      include WhopSDK::Internal::Type::RequestParameters

      attr_accessor company_id: String

      attr_reader access_pass_types: ::Array[String]?

      def access_pass_types=: (::Array[String]) -> ::Array[String]

      attr_reader after: String?

      def after=: (String) -> String

      attr_reader before: String?

      def before=: (String) -> String

      attr_reader direction: WhopSDK::Models::ProductListParams::direction?

      def direction=: (
        WhopSDK::Models::ProductListParams::direction
      ) -> WhopSDK::Models::ProductListParams::direction

      attr_reader first: Integer?

      def first=: (Integer) -> Integer

      attr_reader last: Integer?

      def last=: (Integer) -> Integer

      attr_reader order: String?

      def order=: (String) -> String

      attr_reader visibilities: ::Array[String]?

      def visibilities=: (::Array[String]) -> ::Array[String]

      def initialize: (
        company_id: String,
        ?access_pass_types: ::Array[String],
        ?after: String,
        ?before: String,
        ?direction: WhopSDK::Models::ProductListParams::direction,
        ?first: Integer,
        ?last: Integer,
        ?order: String,
        ?visibilities: ::Array[String],
        ?request_options: WhopSDK::request_opts
      ) -> void

      def to_hash: -> {
        company_id: String,
        access_pass_types: ::Array[String],
        after: String,
        before: String,
        direction: WhopSDK::Models::ProductListParams::direction,
        first: Integer,
        last: Integer,
        order: String,
        visibilities: ::Array[String],
        request_options: WhopSDK::RequestOptions
      }

      type direction = :asc | :desc

      module Direction
        extend WhopSDK::Internal::Type::Enum

        ASC: :asc
        DESC: :desc

        def self?.values: -> ::Array[WhopSDK::Models::ProductListParams::direction]
      end
    end
  end
end
