module WhopSDK
  module Models
    type product_create_params =
      {
        company_id: String,
        title: String,
        business_type: WhopSDK::Models::business_types?,
        collect_shipping_address: bool?,
        custom_cta: WhopSDK::Models::custom_cta?,
        custom_cta_url: String?,
        custom_statement_descriptor: String?,
        description: String?,
        experience_ids: ::Array[String]?,
        global_affiliate_percentage: Float?,
        global_affiliate_status: WhopSDK::Models::global_affiliate_status?,
        headline: String?,
        industry_type: WhopSDK::Models::industry_types?,
        member_affiliate_percentage: Float?,
        member_affiliate_status: WhopSDK::Models::global_affiliate_status?,
        plan_options: WhopSDK::ProductCreateParams::PlanOptions?,
        product_highlights: ::Array[WhopSDK::ProductCreateParams::ProductHighlight]?,
        product_tax_code_id: String?,
        redirect_purchase_url: String?,
        route: String?,
        visibility: WhopSDK::Models::visibility?
      }
      & WhopSDK::Internal::Type::request_parameters

    class ProductCreateParams < WhopSDK::Internal::Type::BaseModel
      extend WhopSDK::Internal::Type::RequestParameters::Converter
      include WhopSDK::Internal::Type::RequestParameters

      attr_accessor company_id: String

      attr_accessor title: String

      attr_accessor business_type: WhopSDK::Models::business_types?

      attr_accessor collect_shipping_address: bool?

      attr_accessor custom_cta: WhopSDK::Models::custom_cta?

      attr_accessor custom_cta_url: String?

      attr_accessor custom_statement_descriptor: String?

      attr_accessor description: String?

      attr_accessor experience_ids: ::Array[String]?

      attr_accessor global_affiliate_percentage: Float?

      attr_accessor global_affiliate_status: WhopSDK::Models::global_affiliate_status?

      attr_accessor headline: String?

      attr_accessor industry_type: WhopSDK::Models::industry_types?

      attr_accessor member_affiliate_percentage: Float?

      attr_accessor member_affiliate_status: WhopSDK::Models::global_affiliate_status?

      attr_accessor plan_options: WhopSDK::ProductCreateParams::PlanOptions?

      attr_accessor product_highlights: ::Array[WhopSDK::ProductCreateParams::ProductHighlight]?

      attr_accessor product_tax_code_id: String?

      attr_accessor redirect_purchase_url: String?

      attr_accessor route: String?

      attr_accessor visibility: WhopSDK::Models::visibility?

      def initialize: (
        company_id: String,
        title: String,
        ?business_type: WhopSDK::Models::business_types?,
        ?collect_shipping_address: bool?,
        ?custom_cta: WhopSDK::Models::custom_cta?,
        ?custom_cta_url: String?,
        ?custom_statement_descriptor: String?,
        ?description: String?,
        ?experience_ids: ::Array[String]?,
        ?global_affiliate_percentage: Float?,
        ?global_affiliate_status: WhopSDK::Models::global_affiliate_status?,
        ?headline: String?,
        ?industry_type: WhopSDK::Models::industry_types?,
        ?member_affiliate_percentage: Float?,
        ?member_affiliate_status: WhopSDK::Models::global_affiliate_status?,
        ?plan_options: WhopSDK::ProductCreateParams::PlanOptions?,
        ?product_highlights: ::Array[WhopSDK::ProductCreateParams::ProductHighlight]?,
        ?product_tax_code_id: String?,
        ?redirect_purchase_url: String?,
        ?route: String?,
        ?visibility: WhopSDK::Models::visibility?,
        ?request_options: WhopSDK::request_opts
      ) -> void

      def to_hash: -> {
        company_id: String,
        title: String,
        business_type: WhopSDK::Models::business_types?,
        collect_shipping_address: bool?,
        custom_cta: WhopSDK::Models::custom_cta?,
        custom_cta_url: String?,
        custom_statement_descriptor: String?,
        description: String?,
        experience_ids: ::Array[String]?,
        global_affiliate_percentage: Float?,
        global_affiliate_status: WhopSDK::Models::global_affiliate_status?,
        headline: String?,
        industry_type: WhopSDK::Models::industry_types?,
        member_affiliate_percentage: Float?,
        member_affiliate_status: WhopSDK::Models::global_affiliate_status?,
        plan_options: WhopSDK::ProductCreateParams::PlanOptions?,
        product_highlights: ::Array[WhopSDK::ProductCreateParams::ProductHighlight]?,
        product_tax_code_id: String?,
        redirect_purchase_url: String?,
        route: String?,
        visibility: WhopSDK::Models::visibility?,
        request_options: WhopSDK::RequestOptions
      }

      type plan_options =
        {
          base_currency: WhopSDK::Models::currency?,
          billing_period: Integer?,
          custom_fields: ::Array[WhopSDK::ProductCreateParams::PlanOptions::CustomField]?,
          initial_price: Float?,
          plan_type: WhopSDK::Models::plan_type?,
          release_method: WhopSDK::Models::release_method?,
          renewal_price: Float?,
          visibility: WhopSDK::Models::visibility?
        }

      class PlanOptions < WhopSDK::Internal::Type::BaseModel
        attr_accessor base_currency: WhopSDK::Models::currency?

        attr_accessor billing_period: Integer?

        attr_accessor custom_fields: ::Array[WhopSDK::ProductCreateParams::PlanOptions::CustomField]?

        attr_accessor initial_price: Float?

        attr_accessor plan_type: WhopSDK::Models::plan_type?

        attr_accessor release_method: WhopSDK::Models::release_method?

        attr_accessor renewal_price: Float?

        attr_accessor visibility: WhopSDK::Models::visibility?

        def initialize: (
          ?base_currency: WhopSDK::Models::currency?,
          ?billing_period: Integer?,
          ?custom_fields: ::Array[WhopSDK::ProductCreateParams::PlanOptions::CustomField]?,
          ?initial_price: Float?,
          ?plan_type: WhopSDK::Models::plan_type?,
          ?release_method: WhopSDK::Models::release_method?,
          ?renewal_price: Float?,
          ?visibility: WhopSDK::Models::visibility?
        ) -> void

        def to_hash: -> {
          base_currency: WhopSDK::Models::currency?,
          billing_period: Integer?,
          custom_fields: ::Array[WhopSDK::ProductCreateParams::PlanOptions::CustomField]?,
          initial_price: Float?,
          plan_type: WhopSDK::Models::plan_type?,
          release_method: WhopSDK::Models::release_method?,
          renewal_price: Float?,
          visibility: WhopSDK::Models::visibility?
        }

        type custom_field =
          {
            field_type: :text,
            name: String,
            id: String?,
            order: Integer?,
            placeholder: String?,
            required: bool?
          }

        class CustomField < WhopSDK::Internal::Type::BaseModel
          attr_accessor field_type: :text

          attr_accessor name: String

          attr_accessor id: String?

          attr_accessor order: Integer?

          attr_accessor placeholder: String?

          attr_accessor required: bool?

          def initialize: (
            name: String,
            ?id: String?,
            ?order: Integer?,
            ?placeholder: String?,
            ?required: bool?,
            ?field_type: :text
          ) -> void

          def to_hash: -> {
            field_type: :text,
            name: String,
            id: String?,
            order: Integer?,
            placeholder: String?,
            required: bool?
          }
        end
      end

      type product_highlight =
        {
          content: String,
          highlight_type: WhopSDK::Models::ProductCreateParams::ProductHighlight::highlight_type,
          title: String?
        }

      class ProductHighlight < WhopSDK::Internal::Type::BaseModel
        attr_accessor content: String

        attr_accessor highlight_type: WhopSDK::Models::ProductCreateParams::ProductHighlight::highlight_type

        attr_accessor title: String?

        def initialize: (
          content: String,
          highlight_type: WhopSDK::Models::ProductCreateParams::ProductHighlight::highlight_type,
          ?title: String?
        ) -> void

        def to_hash: -> {
          content: String,
          highlight_type: WhopSDK::Models::ProductCreateParams::ProductHighlight::highlight_type,
          title: String?
        }

        type highlight_type =
          :qualification | :benefit | :who_this_is_for | :pricing_feature

        module HighlightType
          extend WhopSDK::Internal::Type::Enum

          QUALIFICATION: :qualification
          BENEFIT: :benefit
          WHO_THIS_IS_FOR: :who_this_is_for
          PRICING_FEATURE: :pricing_feature

          def self?.values: -> ::Array[WhopSDK::Models::ProductCreateParams::ProductHighlight::highlight_type]
        end
      end
    end
  end
end
