module WhopSDK
  module Models
    type product =
      {
        id: String,
        business_type: WhopSDK::Models::business_types?,
        company: WhopSDK::Product::Company,
        created_at: Time,
        custom_cta: WhopSDK::Models::custom_cta,
        custom_cta_url: String?,
        custom_statement_descriptor: String?,
        description: String?,
        external_identifier: String?,
        global_affiliate_percentage: Float?,
        global_affiliate_status: WhopSDK::Models::global_affiliate_status,
        headline: String?,
        industry_type: WhopSDK::Models::industry_types?,
        member_affiliate_percentage: Float?,
        member_affiliate_status: WhopSDK::Models::global_affiliate_status,
        member_count: Integer,
        owner_user: WhopSDK::Product::OwnerUser,
        product_tax_code: WhopSDK::Product::ProductTaxCode?,
        published_reviews_count: Integer,
        route: String,
        title: String,
        updated_at: Time,
        verified: bool,
        visibility: WhopSDK::Models::visibility
      }

    class Product < WhopSDK::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor business_type: WhopSDK::Models::business_types?

      attr_accessor company: WhopSDK::Product::Company

      attr_accessor created_at: Time

      attr_accessor custom_cta: WhopSDK::Models::custom_cta

      attr_accessor custom_cta_url: String?

      attr_accessor custom_statement_descriptor: String?

      attr_accessor description: String?

      attr_accessor external_identifier: String?

      attr_accessor global_affiliate_percentage: Float?

      attr_accessor global_affiliate_status: WhopSDK::Models::global_affiliate_status

      attr_accessor headline: String?

      attr_accessor industry_type: WhopSDK::Models::industry_types?

      attr_accessor member_affiliate_percentage: Float?

      attr_accessor member_affiliate_status: WhopSDK::Models::global_affiliate_status

      attr_accessor member_count: Integer

      attr_accessor owner_user: WhopSDK::Product::OwnerUser

      attr_accessor product_tax_code: WhopSDK::Product::ProductTaxCode?

      attr_accessor published_reviews_count: Integer

      attr_accessor route: String

      attr_accessor title: String

      attr_accessor updated_at: Time

      attr_accessor verified: bool

      attr_accessor visibility: WhopSDK::Models::visibility

      def initialize: (
        id: String,
        business_type: WhopSDK::Models::business_types?,
        company: WhopSDK::Product::Company,
        created_at: Time,
        custom_cta: WhopSDK::Models::custom_cta,
        custom_cta_url: String?,
        custom_statement_descriptor: String?,
        description: String?,
        external_identifier: String?,
        global_affiliate_percentage: Float?,
        global_affiliate_status: WhopSDK::Models::global_affiliate_status,
        headline: String?,
        industry_type: WhopSDK::Models::industry_types?,
        member_affiliate_percentage: Float?,
        member_affiliate_status: WhopSDK::Models::global_affiliate_status,
        member_count: Integer,
        owner_user: WhopSDK::Product::OwnerUser,
        product_tax_code: WhopSDK::Product::ProductTaxCode?,
        published_reviews_count: Integer,
        route: String,
        title: String,
        updated_at: Time,
        verified: bool,
        visibility: WhopSDK::Models::visibility
      ) -> void

      def to_hash: -> {
        id: String,
        business_type: WhopSDK::Models::business_types?,
        company: WhopSDK::Product::Company,
        created_at: Time,
        custom_cta: WhopSDK::Models::custom_cta,
        custom_cta_url: String?,
        custom_statement_descriptor: String?,
        description: String?,
        external_identifier: String?,
        global_affiliate_percentage: Float?,
        global_affiliate_status: WhopSDK::Models::global_affiliate_status,
        headline: String?,
        industry_type: WhopSDK::Models::industry_types?,
        member_affiliate_percentage: Float?,
        member_affiliate_status: WhopSDK::Models::global_affiliate_status,
        member_count: Integer,
        owner_user: WhopSDK::Product::OwnerUser,
        product_tax_code: WhopSDK::Product::ProductTaxCode?,
        published_reviews_count: Integer,
        route: String,
        title: String,
        updated_at: Time,
        verified: bool,
        visibility: WhopSDK::Models::visibility
      }

      type company = { id: String, route: String, title: String }

      class Company < WhopSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor route: String

        attr_accessor title: String

        def initialize: (id: String, route: String, title: String) -> void

        def to_hash: -> { id: String, route: String, title: String }
      end

      type owner_user = { id: String, name: String?, username: String }

      class OwnerUser < WhopSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor name: String?

        attr_accessor username: String

        def initialize: (id: String, name: String?, username: String) -> void

        def to_hash: -> { id: String, name: String?, username: String }
      end

      type product_tax_code =
        {
          id: String,
          name: String,
          product_type: WhopSDK::Models::Product::ProductTaxCode::product_type
        }

      class ProductTaxCode < WhopSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor name: String

        attr_accessor product_type: WhopSDK::Models::Product::ProductTaxCode::product_type

        def initialize: (
          id: String,
          name: String,
          product_type: WhopSDK::Models::Product::ProductTaxCode::product_type
        ) -> void

        def to_hash: -> {
          id: String,
          name: String,
          product_type: WhopSDK::Models::Product::ProductTaxCode::product_type
        }

        type product_type = :physical | :digital | :services

        module ProductType
          extend WhopSDK::Internal::Type::Enum

          PHYSICAL: :physical
          DIGITAL: :digital
          SERVICES: :services

          def self?.values: -> ::Array[WhopSDK::Models::Product::ProductTaxCode::product_type]
        end
      end
    end
  end
end
