module WhopSDK
  module Models
    type product_list_params =
      {
        access_pass_types: ::Array[String],
        account_id: String,
        after: String,
        before: String,
        created_after: String,
        created_before: String,
        direction: WhopSDK::Models::ProductListParams::direction,
        first: Integer,
        labels: ::Array[String],
        last: Integer,
        marketplace_category_route: String,
        order: String,
        plan_types: ::Array[WhopSDK::Models::ProductListParams::plan_type],
        price_maximum: Float,
        price_minimum: Float,
        query: String,
        visibilities: ::Array[String],
        api_version_date: String
      }
      & WhopSDK::Internal::Type::request_parameters

    class ProductListParams < WhopSDK::Internal::Type::BaseModel
      extend WhopSDK::Internal::Type::RequestParameters::Converter
      include WhopSDK::Internal::Type::RequestParameters

      attr_reader access_pass_types: ::Array[String]?

      def access_pass_types=: (::Array[String]) -> ::Array[String]

      attr_reader account_id: String?

      def account_id=: (String) -> String

      attr_reader after: String?

      def after=: (String) -> String

      attr_reader before: String?

      def before=: (String) -> String

      attr_reader created_after: String?

      def created_after=: (String) -> String

      attr_reader created_before: String?

      def created_before=: (String) -> String

      attr_reader direction: WhopSDK::Models::ProductListParams::direction?

      def direction=: (
        WhopSDK::Models::ProductListParams::direction
      ) -> WhopSDK::Models::ProductListParams::direction

      attr_reader first: Integer?

      def first=: (Integer) -> Integer

      attr_reader labels: ::Array[String]?

      def labels=: (::Array[String]) -> ::Array[String]

      attr_reader last: Integer?

      def last=: (Integer) -> Integer

      attr_reader marketplace_category_route: String?

      def marketplace_category_route=: (String) -> String

      attr_reader order: String?

      def order=: (String) -> String

      attr_reader plan_types: ::Array[WhopSDK::Models::ProductListParams::plan_type]?

      def plan_types=: (
        ::Array[WhopSDK::Models::ProductListParams::plan_type]
      ) -> ::Array[WhopSDK::Models::ProductListParams::plan_type]

      attr_reader price_maximum: Float?

      def price_maximum=: (Float) -> Float

      attr_reader price_minimum: Float?

      def price_minimum=: (Float) -> Float

      attr_reader query: String?

      def query=: (String) -> String

      attr_reader visibilities: ::Array[String]?

      def visibilities=: (::Array[String]) -> ::Array[String]

      attr_reader api_version_date: String?

      def api_version_date=: (String) -> String

      def initialize: (
        ?access_pass_types: ::Array[String],
        ?account_id: String,
        ?after: String,
        ?before: String,
        ?created_after: String,
        ?created_before: String,
        ?direction: WhopSDK::Models::ProductListParams::direction,
        ?first: Integer,
        ?labels: ::Array[String],
        ?last: Integer,
        ?marketplace_category_route: String,
        ?order: String,
        ?plan_types: ::Array[WhopSDK::Models::ProductListParams::plan_type],
        ?price_maximum: Float,
        ?price_minimum: Float,
        ?query: String,
        ?visibilities: ::Array[String],
        ?api_version_date: String,
        ?request_options: WhopSDK::request_opts
      ) -> void

      def to_hash: -> {
        access_pass_types: ::Array[String],
        account_id: String,
        after: String,
        before: String,
        created_after: String,
        created_before: String,
        direction: WhopSDK::Models::ProductListParams::direction,
        first: Integer,
        labels: ::Array[String],
        last: Integer,
        marketplace_category_route: String,
        order: String,
        plan_types: ::Array[WhopSDK::Models::ProductListParams::plan_type],
        price_maximum: Float,
        price_minimum: Float,
        query: String,
        visibilities: ::Array[String],
        api_version_date: String,
        request_options: WhopSDK::RequestOptions
      }

      type direction = :asc | :desc

      module Direction
        extend WhopSDK::Internal::Type::Enum

        ASC: :asc
        DESC: :desc

        def self?.values: -> ::Array[WhopSDK::Models::ProductListParams::direction]
      end

      type plan_type = :renewal | :one_time

      module PlanType
        extend WhopSDK::Internal::Type::Enum

        RENEWAL: :renewal
        ONE_TIME: :one_time

        def self?.values: -> ::Array[WhopSDK::Models::ProductListParams::plan_type]
      end
    end
  end
end
