module WhopSDK
  module Models
    type product_update_params =
      {
        banner_image: WhopSDK::ProductUpdateParams::BannerImage?,
        business_type: WhopSDK::Models::business_types?,
        collect_shipping_address: bool?,
        custom_cta: WhopSDK::Models::custom_cta?,
        custom_cta_url: String?,
        custom_statement_descriptor: String?,
        description: String?,
        global_affiliate_percentage: Float?,
        global_affiliate_status: WhopSDK::Models::global_affiliate_status?,
        headline: String?,
        industry_type: WhopSDK::Models::industry_types?,
        member_affiliate_percentage: Float?,
        member_affiliate_status: WhopSDK::Models::global_affiliate_status?,
        product_tax_code_id: String?,
        redirect_purchase_url: String?,
        route: String?,
        store_page_config: WhopSDK::ProductUpdateParams::StorePageConfig?,
        title: String?,
        visibility: WhopSDK::Models::visibility?
      }
      & WhopSDK::Internal::Type::request_parameters

    class ProductUpdateParams < WhopSDK::Internal::Type::BaseModel
      extend WhopSDK::Internal::Type::RequestParameters::Converter
      include WhopSDK::Internal::Type::RequestParameters

      attr_accessor banner_image: WhopSDK::ProductUpdateParams::BannerImage?

      attr_accessor business_type: WhopSDK::Models::business_types?

      attr_accessor collect_shipping_address: bool?

      attr_accessor custom_cta: WhopSDK::Models::custom_cta?

      attr_accessor custom_cta_url: String?

      attr_accessor custom_statement_descriptor: String?

      attr_accessor description: String?

      attr_accessor global_affiliate_percentage: Float?

      attr_accessor global_affiliate_status: WhopSDK::Models::global_affiliate_status?

      attr_accessor headline: String?

      attr_accessor industry_type: WhopSDK::Models::industry_types?

      attr_accessor member_affiliate_percentage: Float?

      attr_accessor member_affiliate_status: WhopSDK::Models::global_affiliate_status?

      attr_accessor product_tax_code_id: String?

      attr_accessor redirect_purchase_url: String?

      attr_accessor route: String?

      attr_accessor store_page_config: WhopSDK::ProductUpdateParams::StorePageConfig?

      attr_accessor title: String?

      attr_accessor visibility: WhopSDK::Models::visibility?

      def initialize: (
        ?banner_image: WhopSDK::ProductUpdateParams::BannerImage?,
        ?business_type: WhopSDK::Models::business_types?,
        ?collect_shipping_address: bool?,
        ?custom_cta: WhopSDK::Models::custom_cta?,
        ?custom_cta_url: String?,
        ?custom_statement_descriptor: String?,
        ?description: String?,
        ?global_affiliate_percentage: Float?,
        ?global_affiliate_status: WhopSDK::Models::global_affiliate_status?,
        ?headline: String?,
        ?industry_type: WhopSDK::Models::industry_types?,
        ?member_affiliate_percentage: Float?,
        ?member_affiliate_status: WhopSDK::Models::global_affiliate_status?,
        ?product_tax_code_id: String?,
        ?redirect_purchase_url: String?,
        ?route: String?,
        ?store_page_config: WhopSDK::ProductUpdateParams::StorePageConfig?,
        ?title: String?,
        ?visibility: WhopSDK::Models::visibility?,
        ?request_options: WhopSDK::request_opts
      ) -> void

      def to_hash: -> {
        banner_image: WhopSDK::ProductUpdateParams::BannerImage?,
        business_type: WhopSDK::Models::business_types?,
        collect_shipping_address: bool?,
        custom_cta: WhopSDK::Models::custom_cta?,
        custom_cta_url: String?,
        custom_statement_descriptor: String?,
        description: String?,
        global_affiliate_percentage: Float?,
        global_affiliate_status: WhopSDK::Models::global_affiliate_status?,
        headline: String?,
        industry_type: WhopSDK::Models::industry_types?,
        member_affiliate_percentage: Float?,
        member_affiliate_status: WhopSDK::Models::global_affiliate_status?,
        product_tax_code_id: String?,
        redirect_purchase_url: String?,
        route: String?,
        store_page_config: WhopSDK::ProductUpdateParams::StorePageConfig?,
        title: String?,
        visibility: WhopSDK::Models::visibility?,
        request_options: WhopSDK::RequestOptions
      }

      type banner_image = { id: String?, direct_upload_id: String? }

      class BannerImage < WhopSDK::Internal::Type::BaseModel
        attr_accessor id: String?

        attr_accessor direct_upload_id: String?

        def initialize: (?id: String?, ?direct_upload_id: String?) -> void

        def to_hash: -> { id: String?, direct_upload_id: String? }
      end

      type store_page_config = { custom_cta: String?, show_price: bool? }

      class StorePageConfig < WhopSDK::Internal::Type::BaseModel
        attr_accessor custom_cta: String?

        attr_accessor show_price: bool?

        def initialize: (?custom_cta: String?, ?show_price: bool?) -> void

        def to_hash: -> { custom_cta: String?, show_price: bool? }
      end
    end
  end
end
