module WhopSDK
  module Models
    type product_published_webhook_event =
      {
        id: String,
        api_version: :v1,
        api_version_date: String?,
        data: WhopSDK::Product,
        timestamp: Time,
        type: :"product.published",
        company_id: String?
      }

    class ProductPublishedWebhookEvent < WhopSDK::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor api_version: :v1

      attr_accessor api_version_date: String?

      attr_accessor data: WhopSDK::Product

      attr_accessor timestamp: Time

      attr_accessor type: :"product.published"

      attr_accessor company_id: String?

      def initialize: (
        id: String,
        api_version_date: String?,
        data: WhopSDK::Product,
        timestamp: Time,
        ?company_id: String?,
        ?api_version: :v1,
        ?type: :"product.published"
      ) -> void

      def to_hash: -> {
        id: String,
        api_version: :v1,
        api_version_date: String?,
        data: WhopSDK::Product,
        timestamp: Time,
        type: :"product.published",
        company_id: String?
      }
    end
  end
end
