module WhopSDK
  module Models
    type product_update_params =
      {
        id: String,
        banner_image: WhopSDK::ProductUpdateParams::BannerImage?,
        description: String?,
        headline: String?,
        labels: ::Array[String]?,
        metadata: top?,
        product_tax_code_id: String?,
        send_welcome_message: bool?,
        title: String,
        visibility: String,
        api_version_date: String
      }
      & WhopSDK::Internal::Type::request_parameters

    class ProductUpdateParams < WhopSDK::Internal::Type::BaseModel
      extend WhopSDK::Internal::Type::RequestParameters::Converter
      include WhopSDK::Internal::Type::RequestParameters

      attr_accessor id: String

      attr_accessor banner_image: WhopSDK::ProductUpdateParams::BannerImage?

      attr_accessor description: String?

      attr_accessor headline: String?

      attr_accessor labels: ::Array[String]?

      attr_accessor metadata: top?

      attr_accessor product_tax_code_id: String?

      attr_accessor send_welcome_message: bool?

      attr_reader title: String?

      def title=: (String) -> String

      attr_reader visibility: String?

      def visibility=: (String) -> String

      attr_reader api_version_date: String?

      def api_version_date=: (String) -> String

      def initialize: (
        id: String,
        ?banner_image: WhopSDK::ProductUpdateParams::BannerImage?,
        ?description: String?,
        ?headline: String?,
        ?labels: ::Array[String]?,
        ?metadata: top?,
        ?product_tax_code_id: String?,
        ?send_welcome_message: bool?,
        ?title: String,
        ?visibility: String,
        ?api_version_date: String,
        ?request_options: WhopSDK::request_opts
      ) -> void

      def to_hash: -> {
        id: String,
        banner_image: WhopSDK::ProductUpdateParams::BannerImage?,
        description: String?,
        headline: String?,
        labels: ::Array[String]?,
        metadata: top?,
        product_tax_code_id: String?,
        send_welcome_message: bool?,
        title: String,
        visibility: String,
        api_version_date: String,
        request_options: WhopSDK::RequestOptions
      }

      type banner_image = { id: String, direct_upload_id: String }

      class BannerImage < WhopSDK::Internal::Type::BaseModel
        attr_reader id: String?

        def id=: (String) -> String

        attr_reader direct_upload_id: String?

        def direct_upload_id=: (String) -> String

        def initialize: (?id: String, ?direct_upload_id: String) -> void

        def to_hash: -> { id: String, direct_upload_id: String }
      end
    end
  end
end
