module WhopSDK
  module Models
    type product_list_item =
      {
        id: String,
        created_at: Time,
        external_identifier: String?,
        headline: String?,
        member_count: Integer,
        published_reviews_count: Integer,
        route: String,
        title: String,
        updated_at: Time,
        verified: bool,
        visibility: WhopSDK::Models::visibility
      }

    class ProductListItem < WhopSDK::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor created_at: Time

      attr_accessor external_identifier: String?

      attr_accessor headline: String?

      attr_accessor member_count: Integer

      attr_accessor published_reviews_count: Integer

      attr_accessor route: String

      attr_accessor title: String

      attr_accessor updated_at: Time

      attr_accessor verified: bool

      attr_accessor visibility: WhopSDK::Models::visibility

      def initialize: (
        id: String,
        created_at: Time,
        external_identifier: String?,
        headline: String?,
        member_count: Integer,
        published_reviews_count: Integer,
        route: String,
        title: String,
        updated_at: Time,
        verified: bool,
        visibility: WhopSDK::Models::visibility
      ) -> void

      def to_hash: -> {
        id: String,
        created_at: Time,
        external_identifier: String?,
        headline: String?,
        member_count: Integer,
        published_reviews_count: Integer,
        route: String,
        title: String,
        updated_at: Time,
        verified: bool,
        visibility: WhopSDK::Models::visibility
      }
    end
  end
end
