module WhopSDK
  module Models
    type promo_code_list_params =
      {
        company_id: String,
        after: String,
        before: String,
        created_after: Time,
        created_before: Time,
        first: Integer,
        last: Integer,
        plan_ids: ::Array[String],
        product_ids: ::Array[String],
        status: WhopSDK::Models::promo_code_status
      }
      & WhopSDK::Internal::Type::request_parameters

    class PromoCodeListParams < WhopSDK::Internal::Type::BaseModel
      extend WhopSDK::Internal::Type::RequestParameters::Converter
      include WhopSDK::Internal::Type::RequestParameters

      attr_accessor company_id: String

      attr_reader after: String?

      def after=: (String) -> String

      attr_reader before: String?

      def before=: (String) -> String

      attr_reader created_after: Time?

      def created_after=: (Time) -> Time

      attr_reader created_before: Time?

      def created_before=: (Time) -> Time

      attr_reader first: Integer?

      def first=: (Integer) -> Integer

      attr_reader last: Integer?

      def last=: (Integer) -> Integer

      attr_reader plan_ids: ::Array[String]?

      def plan_ids=: (::Array[String]) -> ::Array[String]

      attr_reader product_ids: ::Array[String]?

      def product_ids=: (::Array[String]) -> ::Array[String]

      attr_reader status: WhopSDK::Models::promo_code_status?

      def status=: (
        WhopSDK::Models::promo_code_status
      ) -> WhopSDK::Models::promo_code_status

      def initialize: (
        company_id: String,
        ?after: String,
        ?before: String,
        ?created_after: Time,
        ?created_before: Time,
        ?first: Integer,
        ?last: Integer,
        ?plan_ids: ::Array[String],
        ?product_ids: ::Array[String],
        ?status: WhopSDK::Models::promo_code_status,
        ?request_options: WhopSDK::request_opts
      ) -> void

      def to_hash: -> {
        company_id: String,
        after: String,
        before: String,
        created_after: Time,
        created_before: Time,
        first: Integer,
        last: Integer,
        plan_ids: ::Array[String],
        product_ids: ::Array[String],
        status: WhopSDK::Models::promo_code_status,
        request_options: WhopSDK::RequestOptions
      }
    end
  end
end
