module WhopSDK
  module Models
    type promo_code_list_params =
      {
        account_id: String,
        after: String,
        before: String,
        created_after: Time,
        created_before: Time,
        direction: WhopSDK::Models::PromoCodeListParams::direction,
        first: Integer,
        last: Integer,
        order: WhopSDK::Models::PromoCodeListParams::order,
        plan_ids: ::Array[String],
        product_ids: ::Array[String],
        status: WhopSDK::Models::PromoCodeListParams::status,
        api_version_date: String
      }
      & WhopSDK::Internal::Type::request_parameters

    class PromoCodeListParams < WhopSDK::Internal::Type::BaseModel
      extend WhopSDK::Internal::Type::RequestParameters::Converter
      include WhopSDK::Internal::Type::RequestParameters

      attr_accessor account_id: String

      attr_reader after: String?

      def after=: (String) -> String

      attr_reader before: String?

      def before=: (String) -> String

      attr_reader created_after: Time?

      def created_after=: (Time) -> Time

      attr_reader created_before: Time?

      def created_before=: (Time) -> Time

      attr_reader direction: WhopSDK::Models::PromoCodeListParams::direction?

      def direction=: (
        WhopSDK::Models::PromoCodeListParams::direction
      ) -> WhopSDK::Models::PromoCodeListParams::direction

      attr_reader first: Integer?

      def first=: (Integer) -> Integer

      attr_reader last: Integer?

      def last=: (Integer) -> Integer

      attr_reader order: WhopSDK::Models::PromoCodeListParams::order?

      def order=: (
        WhopSDK::Models::PromoCodeListParams::order
      ) -> WhopSDK::Models::PromoCodeListParams::order

      attr_reader plan_ids: ::Array[String]?

      def plan_ids=: (::Array[String]) -> ::Array[String]

      attr_reader product_ids: ::Array[String]?

      def product_ids=: (::Array[String]) -> ::Array[String]

      attr_reader status: WhopSDK::Models::PromoCodeListParams::status?

      def status=: (
        WhopSDK::Models::PromoCodeListParams::status
      ) -> WhopSDK::Models::PromoCodeListParams::status

      attr_reader api_version_date: String?

      def api_version_date=: (String) -> String

      def initialize: (
        account_id: String,
        ?after: String,
        ?before: String,
        ?created_after: Time,
        ?created_before: Time,
        ?direction: WhopSDK::Models::PromoCodeListParams::direction,
        ?first: Integer,
        ?last: Integer,
        ?order: WhopSDK::Models::PromoCodeListParams::order,
        ?plan_ids: ::Array[String],
        ?product_ids: ::Array[String],
        ?status: WhopSDK::Models::PromoCodeListParams::status,
        ?api_version_date: String,
        ?request_options: WhopSDK::request_opts
      ) -> void

      def to_hash: -> {
        account_id: String,
        after: String,
        before: String,
        created_after: Time,
        created_before: Time,
        direction: WhopSDK::Models::PromoCodeListParams::direction,
        first: Integer,
        last: Integer,
        order: WhopSDK::Models::PromoCodeListParams::order,
        plan_ids: ::Array[String],
        product_ids: ::Array[String],
        status: WhopSDK::Models::PromoCodeListParams::status,
        api_version_date: String,
        request_options: WhopSDK::RequestOptions
      }

      type direction = :asc | :desc

      module Direction
        extend WhopSDK::Internal::Type::Enum

        ASC: :asc
        DESC: :desc

        def self?.values: -> ::Array[WhopSDK::Models::PromoCodeListParams::direction]
      end

      type order = :created_at

      module Order
        extend WhopSDK::Internal::Type::Enum

        CREATED_AT: :created_at

        def self?.values: -> ::Array[WhopSDK::Models::PromoCodeListParams::order]
      end

      type status = :active | :inactive | :archived | :expired

      module Status
        extend WhopSDK::Internal::Type::Enum

        ACTIVE: :active
        INACTIVE: :inactive
        ARCHIVED: :archived
        EXPIRED: :expired

        def self?.values: -> ::Array[WhopSDK::Models::PromoCodeListParams::status]
      end
    end
  end
end
