module WhopSDK
  module Models
    type refund_created_webhook_event =
      {
        id: String,
        api_version: :v1,
        data: WhopSDK::RefundCreatedWebhookEvent::Data,
        timestamp: Time,
        type: :"refund.created"
      }

    class RefundCreatedWebhookEvent < WhopSDK::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor api_version: :v1

      attr_accessor data: WhopSDK::RefundCreatedWebhookEvent::Data

      attr_accessor timestamp: Time

      attr_accessor type: :"refund.created"

      def initialize: (
        id: String,
        data: WhopSDK::RefundCreatedWebhookEvent::Data,
        timestamp: Time,
        ?api_version: :v1,
        ?type: :"refund.created"
      ) -> void

      def to_hash: -> {
        id: String,
        api_version: :v1,
        data: WhopSDK::RefundCreatedWebhookEvent::Data,
        timestamp: Time,
        type: :"refund.created"
      }

      type data =
        {
          id: String,
          amount: Float,
          created_at: Time,
          currency: WhopSDK::Models::currency,
          payment: WhopSDK::RefundCreatedWebhookEvent::Data::Payment?,
          provider: WhopSDK::Models::RefundCreatedWebhookEvent::Data::provider,
          provider_created_at: Time?,
          reference_status: WhopSDK::Models::RefundCreatedWebhookEvent::Data::reference_status?,
          reference_type: WhopSDK::Models::RefundCreatedWebhookEvent::Data::reference_type?,
          reference_value: String?,
          status: WhopSDK::Models::RefundCreatedWebhookEvent::Data::status
        }

      class Data < WhopSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor amount: Float

        attr_accessor created_at: Time

        attr_accessor currency: WhopSDK::Models::currency

        attr_accessor payment: WhopSDK::RefundCreatedWebhookEvent::Data::Payment?

        attr_accessor provider: WhopSDK::Models::RefundCreatedWebhookEvent::Data::provider

        attr_accessor provider_created_at: Time?

        attr_accessor reference_status: WhopSDK::Models::RefundCreatedWebhookEvent::Data::reference_status?

        attr_accessor reference_type: WhopSDK::Models::RefundCreatedWebhookEvent::Data::reference_type?

        attr_accessor reference_value: String?

        attr_accessor status: WhopSDK::Models::RefundCreatedWebhookEvent::Data::status

        def initialize: (
          id: String,
          amount: Float,
          created_at: Time,
          currency: WhopSDK::Models::currency,
          payment: WhopSDK::RefundCreatedWebhookEvent::Data::Payment?,
          provider: WhopSDK::Models::RefundCreatedWebhookEvent::Data::provider,
          provider_created_at: Time?,
          reference_status: WhopSDK::Models::RefundCreatedWebhookEvent::Data::reference_status?,
          reference_type: WhopSDK::Models::RefundCreatedWebhookEvent::Data::reference_type?,
          reference_value: String?,
          status: WhopSDK::Models::RefundCreatedWebhookEvent::Data::status
        ) -> void

        def to_hash: -> {
          id: String,
          amount: Float,
          created_at: Time,
          currency: WhopSDK::Models::currency,
          payment: WhopSDK::RefundCreatedWebhookEvent::Data::Payment?,
          provider: WhopSDK::Models::RefundCreatedWebhookEvent::Data::provider,
          provider_created_at: Time?,
          reference_status: WhopSDK::Models::RefundCreatedWebhookEvent::Data::reference_status?,
          reference_type: WhopSDK::Models::RefundCreatedWebhookEvent::Data::reference_type?,
          reference_value: String?,
          status: WhopSDK::Models::RefundCreatedWebhookEvent::Data::status
        }

        type payment =
          {
            id: String,
            billing_reason: WhopSDK::Models::billing_reasons?,
            card_brand: WhopSDK::Models::card_brands?,
            :card_last4 => String?,
            created_at: Time,
            currency: WhopSDK::Models::currency?,
            dispute_alerted_at: Time?,
            member: WhopSDK::RefundCreatedWebhookEvent::Data::Payment::Member?,
            membership: WhopSDK::RefundCreatedWebhookEvent::Data::Payment::Membership?,
            paid_at: Time?,
            payment_method_type: WhopSDK::Models::payment_method_types?,
            subtotal: Float?,
            total: Float?,
            usd_total: Float?,
            user: WhopSDK::RefundCreatedWebhookEvent::Data::Payment::User?
          }

        class Payment < WhopSDK::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor billing_reason: WhopSDK::Models::billing_reasons?

          attr_accessor card_brand: WhopSDK::Models::card_brands?

          attr_accessor card_last4: String?

          attr_accessor created_at: Time

          attr_accessor currency: WhopSDK::Models::currency?

          attr_accessor dispute_alerted_at: Time?

          attr_accessor member: WhopSDK::RefundCreatedWebhookEvent::Data::Payment::Member?

          attr_accessor membership: WhopSDK::RefundCreatedWebhookEvent::Data::Payment::Membership?

          attr_accessor paid_at: Time?

          attr_accessor payment_method_type: WhopSDK::Models::payment_method_types?

          attr_accessor subtotal: Float?

          attr_accessor total: Float?

          attr_accessor usd_total: Float?

          attr_accessor user: WhopSDK::RefundCreatedWebhookEvent::Data::Payment::User?

          def initialize: (
            id: String,
            billing_reason: WhopSDK::Models::billing_reasons?,
            card_brand: WhopSDK::Models::card_brands?,
            card_last4: String?,
            created_at: Time,
            currency: WhopSDK::Models::currency?,
            dispute_alerted_at: Time?,
            member: WhopSDK::RefundCreatedWebhookEvent::Data::Payment::Member?,
            membership: WhopSDK::RefundCreatedWebhookEvent::Data::Payment::Membership?,
            paid_at: Time?,
            payment_method_type: WhopSDK::Models::payment_method_types?,
            subtotal: Float?,
            total: Float?,
            usd_total: Float?,
            user: WhopSDK::RefundCreatedWebhookEvent::Data::Payment::User?
          ) -> void

          def to_hash: -> {
            id: String,
            billing_reason: WhopSDK::Models::billing_reasons?,
            card_brand: WhopSDK::Models::card_brands?,
            :card_last4 => String?,
            created_at: Time,
            currency: WhopSDK::Models::currency?,
            dispute_alerted_at: Time?,
            member: WhopSDK::RefundCreatedWebhookEvent::Data::Payment::Member?,
            membership: WhopSDK::RefundCreatedWebhookEvent::Data::Payment::Membership?,
            paid_at: Time?,
            payment_method_type: WhopSDK::Models::payment_method_types?,
            subtotal: Float?,
            total: Float?,
            usd_total: Float?,
            user: WhopSDK::RefundCreatedWebhookEvent::Data::Payment::User?
          }

          type member = { id: String, phone: String? }

          class Member < WhopSDK::Internal::Type::BaseModel
            attr_accessor id: String

            attr_accessor phone: String?

            def initialize: (id: String, phone: String?) -> void

            def to_hash: -> { id: String, phone: String? }
          end

          type membership =
            { id: String, status: WhopSDK::Models::membership_status }

          class Membership < WhopSDK::Internal::Type::BaseModel
            attr_accessor id: String

            attr_accessor status: WhopSDK::Models::membership_status

            def initialize: (
              id: String,
              status: WhopSDK::Models::membership_status
            ) -> void

            def to_hash: -> {
              id: String,
              status: WhopSDK::Models::membership_status
            }
          end

          type user =
            { id: String, email: String?, name: String?, username: String }

          class User < WhopSDK::Internal::Type::BaseModel
            attr_accessor id: String

            attr_accessor email: String?

            attr_accessor name: String?

            attr_accessor username: String

            def initialize: (
              id: String,
              email: String?,
              name: String?,
              username: String
            ) -> void

            def to_hash: -> {
              id: String,
              email: String?,
              name: String?,
              username: String
            }
          end
        end

        type provider =
          :stripe
          | :coinbase
          | :paypal
          | :apple
          | :sezzle
          | :splitit
          | :platform_balance
          | :multi_psp

        module Provider
          extend WhopSDK::Internal::Type::Enum

          STRIPE: :stripe
          COINBASE: :coinbase
          PAYPAL: :paypal
          APPLE: :apple
          SEZZLE: :sezzle
          SPLITIT: :splitit
          PLATFORM_BALANCE: :platform_balance
          MULTI_PSP: :multi_psp

          def self?.values: -> ::Array[WhopSDK::Models::RefundCreatedWebhookEvent::Data::provider]
        end

        type reference_status = :available | :pending | :unavailable

        module ReferenceStatus
          extend WhopSDK::Internal::Type::Enum

          AVAILABLE: :available
          PENDING: :pending
          UNAVAILABLE: :unavailable

          def self?.values: -> ::Array[WhopSDK::Models::RefundCreatedWebhookEvent::Data::reference_status]
        end

        type reference_type =
          :acquirer_reference_number
          | :retrieval_reference_number
          | :system_trace_audit_number

        module ReferenceType
          extend WhopSDK::Internal::Type::Enum

          ACQUIRER_REFERENCE_NUMBER: :acquirer_reference_number
          RETRIEVAL_REFERENCE_NUMBER: :retrieval_reference_number
          SYSTEM_TRACE_AUDIT_NUMBER: :system_trace_audit_number

          def self?.values: -> ::Array[WhopSDK::Models::RefundCreatedWebhookEvent::Data::reference_type]
        end

        type status =
          :pending | :requires_action | :succeeded | :failed | :canceled

        module Status
          extend WhopSDK::Internal::Type::Enum

          PENDING: :pending
          REQUIRES_ACTION: :requires_action
          SUCCEEDED: :succeeded
          FAILED: :failed
          CANCELED: :canceled

          def self?.values: -> ::Array[WhopSDK::Models::RefundCreatedWebhookEvent::Data::status]
        end
      end
    end
  end
end
