module WhopSDK
  module Models
    type refund_list_params =
      {
        account_id: String,
        after: String,
        before: String,
        created_after: Time,
        created_before: Time,
        direction: WhopSDK::Models::RefundListParams::direction,
        first: Integer,
        last: Integer,
        order: WhopSDK::Models::RefundListParams::order,
        payment_id: String,
        user_id: String,
        api_version_date: String
      }
      & WhopSDK::Internal::Type::request_parameters

    class RefundListParams < WhopSDK::Internal::Type::BaseModel
      extend WhopSDK::Internal::Type::RequestParameters::Converter
      include WhopSDK::Internal::Type::RequestParameters

      attr_reader account_id: String?

      def account_id=: (String) -> String

      attr_reader after: String?

      def after=: (String) -> String

      attr_reader before: String?

      def before=: (String) -> String

      attr_reader created_after: Time?

      def created_after=: (Time) -> Time

      attr_reader created_before: Time?

      def created_before=: (Time) -> Time

      attr_reader direction: WhopSDK::Models::RefundListParams::direction?

      def direction=: (
        WhopSDK::Models::RefundListParams::direction
      ) -> WhopSDK::Models::RefundListParams::direction

      attr_reader first: Integer?

      def first=: (Integer) -> Integer

      attr_reader last: Integer?

      def last=: (Integer) -> Integer

      attr_reader order: WhopSDK::Models::RefundListParams::order?

      def order=: (
        WhopSDK::Models::RefundListParams::order
      ) -> WhopSDK::Models::RefundListParams::order

      attr_reader payment_id: String?

      def payment_id=: (String) -> String

      attr_reader user_id: String?

      def user_id=: (String) -> String

      attr_reader api_version_date: String?

      def api_version_date=: (String) -> String

      def initialize: (
        ?account_id: String,
        ?after: String,
        ?before: String,
        ?created_after: Time,
        ?created_before: Time,
        ?direction: WhopSDK::Models::RefundListParams::direction,
        ?first: Integer,
        ?last: Integer,
        ?order: WhopSDK::Models::RefundListParams::order,
        ?payment_id: String,
        ?user_id: String,
        ?api_version_date: String,
        ?request_options: WhopSDK::request_opts
      ) -> void

      def to_hash: -> {
        account_id: String,
        after: String,
        before: String,
        created_after: Time,
        created_before: Time,
        direction: WhopSDK::Models::RefundListParams::direction,
        first: Integer,
        last: Integer,
        order: WhopSDK::Models::RefundListParams::order,
        payment_id: String,
        user_id: String,
        api_version_date: String,
        request_options: WhopSDK::RequestOptions
      }

      type direction = :asc | :desc

      module Direction
        extend WhopSDK::Internal::Type::Enum

        ASC: :asc
        DESC: :desc

        def self?.values: -> ::Array[WhopSDK::Models::RefundListParams::direction]
      end

      type order = :created_at

      module Order
        extend WhopSDK::Internal::Type::Enum

        CREATED_AT: :created_at

        def self?.values: -> ::Array[WhopSDK::Models::RefundListParams::order]
      end
    end
  end
end
