module WhopSDK
  module Models
    type resolution_center_case_status =
      :merchant_response_needed
      | :customer_response_needed
      | :merchant_info_needed
      | :customer_info_needed
      | :under_platform_review
      | :customer_won
      | :merchant_won
      | :customer_withdrew

    module ResolutionCenterCaseStatus
      extend WhopSDK::Internal::Type::Enum

      MERCHANT_RESPONSE_NEEDED: :merchant_response_needed
      CUSTOMER_RESPONSE_NEEDED: :customer_response_needed
      MERCHANT_INFO_NEEDED: :merchant_info_needed
      CUSTOMER_INFO_NEEDED: :customer_info_needed
      UNDER_PLATFORM_REVIEW: :under_platform_review
      CUSTOMER_WON: :customer_won
      MERCHANT_WON: :merchant_won
      CUSTOMER_WITHDREW: :customer_withdrew

      def self?.values: -> ::Array[WhopSDK::Models::resolution_center_case_status]
    end
  end
end
