module WhopSDK
  module Models
    type resolution_center_case_created_webhook_event =
      {
        id: String,
        api_version: :v1,
        api_version_date: String?,
        data: WhopSDK::ResolutionCenterCaseCreatedWebhookEvent::Data,
        timestamp: Time,
        type: :"resolution_center_case.created",
        account_id: String?,
        previous_attributes: top
      }

    class ResolutionCenterCaseCreatedWebhookEvent < WhopSDK::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor api_version: :v1

      attr_accessor api_version_date: String?

      attr_accessor data: WhopSDK::ResolutionCenterCaseCreatedWebhookEvent::Data

      attr_accessor timestamp: Time

      attr_accessor type: :"resolution_center_case.created"

      attr_accessor account_id: String?

      attr_reader previous_attributes: top?

      def previous_attributes=: (top) -> top

      def initialize: (
        id: String,
        api_version_date: String?,
        data: WhopSDK::ResolutionCenterCaseCreatedWebhookEvent::Data,
        timestamp: Time,
        ?account_id: String?,
        ?previous_attributes: top,
        ?api_version: :v1,
        ?type: :"resolution_center_case.created"
      ) -> void

      def to_hash: -> {
        id: String,
        api_version: :v1,
        api_version_date: String?,
        data: WhopSDK::ResolutionCenterCaseCreatedWebhookEvent::Data,
        timestamp: Time,
        type: :"resolution_center_case.created",
        account_id: String?,
        previous_attributes: top
      }

      type data =
        {
          id: String,
          account: WhopSDK::ResolutionCenterCaseCreatedWebhookEvent::Data::Account?,
          amount: Float,
          available_actions: ::Array[WhopSDK::Models::ResolutionCenterCaseCreatedWebhookEvent::Data::available_action],
          buyer: WhopSDK::ResolutionCenterCaseCreatedWebhookEvent::Data::Buyer,
          created_at: String,
          currency: String?,
          customer_appealed: bool,
          escalated: bool,
          line_items: ::Array[WhopSDK::ResolutionCenterCaseCreatedWebhookEvent::Data::LineItem],
          outcome: WhopSDK::Models::ResolutionCenterCaseCreatedWebhookEvent::Data::outcome?,
          payment: WhopSDK::ResolutionCenterCaseCreatedWebhookEvent::Data::Payment,
          plan_id: String?,
          product_id: String?,
          reason: WhopSDK::Models::ResolutionCenterCaseCreatedWebhookEvent::Data::reason,
          refund: WhopSDK::Models::ResolutionCenterCaseCreatedWebhookEvent::Data::refund?,
          response_due_at: String?,
          status: WhopSDK::Models::ResolutionCenterCaseCreatedWebhookEvent::Data::status,
          updated_at: String
        }

      class Data < WhopSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor account: WhopSDK::ResolutionCenterCaseCreatedWebhookEvent::Data::Account?

        attr_accessor amount: Float

        attr_accessor available_actions: ::Array[WhopSDK::Models::ResolutionCenterCaseCreatedWebhookEvent::Data::available_action]

        attr_accessor buyer: WhopSDK::ResolutionCenterCaseCreatedWebhookEvent::Data::Buyer

        attr_accessor created_at: String

        attr_accessor currency: String?

        attr_accessor customer_appealed: bool

        attr_accessor escalated: bool

        attr_accessor line_items: ::Array[WhopSDK::ResolutionCenterCaseCreatedWebhookEvent::Data::LineItem]

        attr_accessor outcome: WhopSDK::Models::ResolutionCenterCaseCreatedWebhookEvent::Data::outcome?

        attr_accessor payment: WhopSDK::ResolutionCenterCaseCreatedWebhookEvent::Data::Payment

        attr_accessor plan_id: String?

        attr_accessor product_id: String?

        attr_accessor reason: WhopSDK::Models::ResolutionCenterCaseCreatedWebhookEvent::Data::reason

        attr_accessor refund: WhopSDK::Models::ResolutionCenterCaseCreatedWebhookEvent::Data::refund?

        attr_accessor response_due_at: String?

        attr_accessor status: WhopSDK::Models::ResolutionCenterCaseCreatedWebhookEvent::Data::status

        attr_accessor updated_at: String

        def initialize: (
          id: String,
          account: WhopSDK::ResolutionCenterCaseCreatedWebhookEvent::Data::Account?,
          amount: Float,
          available_actions: ::Array[WhopSDK::Models::ResolutionCenterCaseCreatedWebhookEvent::Data::available_action],
          buyer: WhopSDK::ResolutionCenterCaseCreatedWebhookEvent::Data::Buyer,
          created_at: String,
          currency: String?,
          customer_appealed: bool,
          escalated: bool,
          line_items: ::Array[WhopSDK::ResolutionCenterCaseCreatedWebhookEvent::Data::LineItem],
          outcome: WhopSDK::Models::ResolutionCenterCaseCreatedWebhookEvent::Data::outcome?,
          payment: WhopSDK::ResolutionCenterCaseCreatedWebhookEvent::Data::Payment,
          plan_id: String?,
          product_id: String?,
          reason: WhopSDK::Models::ResolutionCenterCaseCreatedWebhookEvent::Data::reason,
          refund: WhopSDK::Models::ResolutionCenterCaseCreatedWebhookEvent::Data::refund?,
          response_due_at: String?,
          status: WhopSDK::Models::ResolutionCenterCaseCreatedWebhookEvent::Data::status,
          updated_at: String
        ) -> void

        def to_hash: -> {
          id: String,
          account: WhopSDK::ResolutionCenterCaseCreatedWebhookEvent::Data::Account?,
          amount: Float,
          available_actions: ::Array[WhopSDK::Models::ResolutionCenterCaseCreatedWebhookEvent::Data::available_action],
          buyer: WhopSDK::ResolutionCenterCaseCreatedWebhookEvent::Data::Buyer,
          created_at: String,
          currency: String?,
          customer_appealed: bool,
          escalated: bool,
          line_items: ::Array[WhopSDK::ResolutionCenterCaseCreatedWebhookEvent::Data::LineItem],
          outcome: WhopSDK::Models::ResolutionCenterCaseCreatedWebhookEvent::Data::outcome?,
          payment: WhopSDK::ResolutionCenterCaseCreatedWebhookEvent::Data::Payment,
          plan_id: String?,
          product_id: String?,
          reason: WhopSDK::Models::ResolutionCenterCaseCreatedWebhookEvent::Data::reason,
          refund: WhopSDK::Models::ResolutionCenterCaseCreatedWebhookEvent::Data::refund?,
          response_due_at: String?,
          status: WhopSDK::Models::ResolutionCenterCaseCreatedWebhookEvent::Data::status,
          updated_at: String
        }

        type account = { id: String, title: String }

        class Account < WhopSDK::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor title: String

          def initialize: (id: String, title: String) -> void

          def to_hash: -> { id: String, title: String }
        end

        type available_action =
          :accept | :deny | :request_info | :reply | :appeal | :withdraw

        module AvailableAction
          extend WhopSDK::Internal::Type::Enum

          ACCEPT: :accept
          DENY: :deny
          REQUEST_INFO: :request_info
          REPLY: :reply
          APPEAL: :appeal
          WITHDRAW: :withdraw

          def self?.values: -> ::Array[WhopSDK::Models::ResolutionCenterCaseCreatedWebhookEvent::Data::available_action]
        end

        type buyer =
          {
            email: String?,
            member_id: String?,
            name: String?,
            user_id: String?,
            username: String?
          }

        class Buyer < WhopSDK::Internal::Type::BaseModel
          attr_accessor email: String?

          attr_accessor member_id: String?

          attr_accessor name: String?

          attr_accessor user_id: String?

          attr_accessor username: String?

          def initialize: (
            email: String?,
            member_id: String?,
            name: String?,
            user_id: String?,
            username: String?
          ) -> void

          def to_hash: -> {
            email: String?,
            member_id: String?,
            name: String?,
            user_id: String?,
            username: String?
          }
        end

        type line_item =
          {
            id: String?,
            label: String?,
            plan_id: String?,
            product_id: String?,
            quantity: Float
          }

        class LineItem < WhopSDK::Internal::Type::BaseModel
          attr_accessor id: String?

          attr_accessor label: String?

          attr_accessor plan_id: String?

          attr_accessor product_id: String?

          attr_accessor quantity: Float

          def initialize: (
            id: String?,
            label: String?,
            plan_id: String?,
            product_id: String?,
            quantity: Float
          ) -> void

          def to_hash: -> {
            id: String?,
            label: String?,
            plan_id: String?,
            product_id: String?,
            quantity: Float
          }
        end

        type outcome = :customer_won | :merchant_won | :withdrawn

        module Outcome
          extend WhopSDK::Internal::Type::Enum

          CUSTOMER_WON: :customer_won
          MERCHANT_WON: :merchant_won
          WITHDRAWN: :withdrawn

          def self?.values: -> ::Array[WhopSDK::Models::ResolutionCenterCaseCreatedWebhookEvent::Data::outcome]
        end

        type payment =
          {
            id: String,
            card_brand: String?,
            :card_last4 => String?,
            created_at: String,
            payment_method_type: String?
          }

        class Payment < WhopSDK::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor card_brand: String?

          attr_accessor card_last4: String?

          attr_accessor created_at: String

          attr_accessor payment_method_type: String?

          def initialize: (
            id: String,
            card_brand: String?,
            card_last4: String?,
            created_at: String,
            payment_method_type: String?
          ) -> void

          def to_hash: -> {
            id: String,
            card_brand: String?,
            :card_last4 => String?,
            created_at: String,
            payment_method_type: String?
          }
        end

        type reason =
          :fraudulent
          | :product_not_received
          | :not_as_described
          | :product_unacceptable
          | :subscription_canceled

        module Reason
          extend WhopSDK::Internal::Type::Enum

          FRAUDULENT: :fraudulent
          PRODUCT_NOT_RECEIVED: :product_not_received
          NOT_AS_DESCRIBED: :not_as_described
          PRODUCT_UNACCEPTABLE: :product_unacceptable
          SUBSCRIPTION_CANCELED: :subscription_canceled

          def self?.values: -> ::Array[WhopSDK::Models::ResolutionCenterCaseCreatedWebhookEvent::Data::reason]
        end

        type refund = :none | :merchant | :platform

        module Refund
          extend WhopSDK::Internal::Type::Enum

          NONE: :none
          MERCHANT: :merchant
          PLATFORM: :platform

          def self?.values: -> ::Array[WhopSDK::Models::ResolutionCenterCaseCreatedWebhookEvent::Data::refund]
        end

        type status =
          :awaiting_merchant | :awaiting_customer | :under_review | :closed

        module Status
          extend WhopSDK::Internal::Type::Enum

          AWAITING_MERCHANT: :awaiting_merchant
          AWAITING_CUSTOMER: :awaiting_customer
          UNDER_REVIEW: :under_review
          CLOSED: :closed

          def self?.values: -> ::Array[WhopSDK::Models::ResolutionCenterCaseCreatedWebhookEvent::Data::status]
        end
      end
    end
  end
end
