module WhopSDK
  module Models
    type setup_intent_canceled_webhook_event =
      {
        id: String,
        api_version: :v1,
        data: WhopSDK::SetupIntent,
        timestamp: Time,
        type: :"setup_intent.canceled",
        company_id: String?
      }

    class SetupIntentCanceledWebhookEvent < WhopSDK::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor api_version: :v1

      attr_accessor data: WhopSDK::SetupIntent

      attr_accessor timestamp: Time

      attr_accessor type: :"setup_intent.canceled"

      attr_accessor company_id: String?

      def initialize: (
        id: String,
        data: WhopSDK::SetupIntent,
        timestamp: Time,
        ?company_id: String?,
        ?api_version: :v1,
        ?type: :"setup_intent.canceled"
      ) -> void

      def to_hash: -> {
        id: String,
        api_version: :v1,
        data: WhopSDK::SetupIntent,
        timestamp: Time,
        type: :"setup_intent.canceled",
        company_id: String?
      }
    end
  end
end
