module WhopSDK
  module Models
    type setup_intent =
      {
        id: String,
        account_id: String?,
        checkout_configuration_id: String?,
        client_secret: String?,
        created_at: String,
        last_setup_error: WhopSDK::SetupIntent::LastSetupError?,
        member_id: String?,
        metadata: top?,
        payment_instrument: WhopSDK::SetupIntent::PaymentInstrument?,
        payment_method_id: String?,
        payment_method_type: WhopSDK::Models::payment_method_types?,
        return_url: String?,
        status: WhopSDK::Models::SetupIntent::status,
        three_ds_verified: bool,
        updated_at: String,
        user: WhopSDK::SetupIntent::User?
      }

    class SetupIntent < WhopSDK::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor account_id: String?

      attr_accessor checkout_configuration_id: String?

      attr_accessor client_secret: String?

      attr_accessor created_at: String

      attr_accessor last_setup_error: WhopSDK::SetupIntent::LastSetupError?

      attr_accessor member_id: String?

      attr_accessor metadata: top?

      attr_accessor payment_instrument: WhopSDK::SetupIntent::PaymentInstrument?

      attr_accessor payment_method_id: String?

      attr_accessor payment_method_type: WhopSDK::Models::payment_method_types?

      attr_accessor return_url: String?

      attr_accessor status: WhopSDK::Models::SetupIntent::status

      attr_accessor three_ds_verified: bool

      attr_accessor updated_at: String

      attr_accessor user: WhopSDK::SetupIntent::User?

      def initialize: (
        id: String,
        account_id: String?,
        checkout_configuration_id: String?,
        client_secret: String?,
        created_at: String,
        last_setup_error: WhopSDK::SetupIntent::LastSetupError?,
        member_id: String?,
        metadata: top?,
        payment_instrument: WhopSDK::SetupIntent::PaymentInstrument?,
        payment_method_id: String?,
        payment_method_type: WhopSDK::Models::payment_method_types?,
        return_url: String?,
        status: WhopSDK::Models::SetupIntent::status,
        three_ds_verified: bool,
        updated_at: String,
        user: WhopSDK::SetupIntent::User?
      ) -> void

      def to_hash: -> {
        id: String,
        account_id: String?,
        checkout_configuration_id: String?,
        client_secret: String?,
        created_at: String,
        last_setup_error: WhopSDK::SetupIntent::LastSetupError?,
        member_id: String?,
        metadata: top?,
        payment_instrument: WhopSDK::SetupIntent::PaymentInstrument?,
        payment_method_id: String?,
        payment_method_type: WhopSDK::Models::payment_method_types?,
        return_url: String?,
        status: WhopSDK::Models::SetupIntent::status,
        three_ds_verified: bool,
        updated_at: String,
        user: WhopSDK::SetupIntent::User?
      }

      type last_setup_error = { code: String?, message: String? }

      class LastSetupError < WhopSDK::Internal::Type::BaseModel
        attr_accessor code: String?

        attr_accessor message: String?

        def initialize: (code: String?, message: String?) -> void

        def to_hash: -> { code: String?, message: String? }
      end

      type payment_instrument =
        {
          card: WhopSDK::SetupIntent::PaymentInstrument::Card?,
          display_name: String,
          icons: WhopSDK::SetupIntent::PaymentInstrument::Icons,
          installment_count: Float?,
          payment_method_type: String
        }

      class PaymentInstrument < WhopSDK::Internal::Type::BaseModel
        attr_accessor card: WhopSDK::SetupIntent::PaymentInstrument::Card?

        attr_accessor display_name: String

        attr_accessor icons: WhopSDK::SetupIntent::PaymentInstrument::Icons

        attr_accessor installment_count: Float?

        attr_accessor payment_method_type: String

        def initialize: (
          card: WhopSDK::SetupIntent::PaymentInstrument::Card?,
          display_name: String,
          icons: WhopSDK::SetupIntent::PaymentInstrument::Icons,
          installment_count: Float?,
          payment_method_type: String
        ) -> void

        def to_hash: -> {
          card: WhopSDK::SetupIntent::PaymentInstrument::Card?,
          display_name: String,
          icons: WhopSDK::SetupIntent::PaymentInstrument::Icons,
          installment_count: Float?,
          payment_method_type: String
        }

        type card =
          {
            brand: String?,
            exp_month: Float?,
            exp_year: Float?,
            issuer_identification_number: String?,
            :last4 => String?
          }

        class Card < WhopSDK::Internal::Type::BaseModel
          attr_accessor brand: String?

          attr_accessor exp_month: Float?

          attr_accessor exp_year: Float?

          attr_accessor issuer_identification_number: String?

          attr_accessor last4: String?

          def initialize: (
            brand: String?,
            exp_month: Float?,
            exp_year: Float?,
            issuer_identification_number: String?,
            last4: String?
          ) -> void

          def to_hash: -> {
            brand: String?,
            exp_month: Float?,
            exp_year: Float?,
            issuer_identification_number: String?,
            :last4 => String?
          }
        end

        type icons =
          {
            card: WhopSDK::SetupIntent::PaymentInstrument::Icons::Card,
            square: WhopSDK::SetupIntent::PaymentInstrument::Icons::Square
          }

        class Icons < WhopSDK::Internal::Type::BaseModel
          attr_accessor card: WhopSDK::SetupIntent::PaymentInstrument::Icons::Card

          attr_accessor square: WhopSDK::SetupIntent::PaymentInstrument::Icons::Square

          def initialize: (
            card: WhopSDK::SetupIntent::PaymentInstrument::Icons::Card,
            square: WhopSDK::SetupIntent::PaymentInstrument::Icons::Square
          ) -> void

          def to_hash: -> {
            card: WhopSDK::SetupIntent::PaymentInstrument::Icons::Card,
            square: WhopSDK::SetupIntent::PaymentInstrument::Icons::Square
          }

          type card =
            {
              dark: WhopSDK::SetupIntent::PaymentInstrument::Icons::Card::Dark,
              light: WhopSDK::SetupIntent::PaymentInstrument::Icons::Card::Light
            }

          class Card < WhopSDK::Internal::Type::BaseModel
            attr_accessor dark: WhopSDK::SetupIntent::PaymentInstrument::Icons::Card::Dark

            attr_accessor light: WhopSDK::SetupIntent::PaymentInstrument::Icons::Card::Light

            def initialize: (
              dark: WhopSDK::SetupIntent::PaymentInstrument::Icons::Card::Dark,
              light: WhopSDK::SetupIntent::PaymentInstrument::Icons::Card::Light
            ) -> void

            def to_hash: -> {
              dark: WhopSDK::SetupIntent::PaymentInstrument::Icons::Card::Dark,
              light: WhopSDK::SetupIntent::PaymentInstrument::Icons::Card::Light
            }

            type dark =
              {
                :png_1x => String,
                :png_2x => String,
                :png_4x => String,
                svg: String
              }

            class Dark < WhopSDK::Internal::Type::BaseModel
              attr_accessor png_1x: String

              attr_accessor png_2x: String

              attr_accessor png_4x: String

              attr_accessor svg: String

              def initialize: (
                png_1x: String,
                png_2x: String,
                png_4x: String,
                svg: String
              ) -> void

              def to_hash: -> {
                :png_1x => String,
                :png_2x => String,
                :png_4x => String,
                svg: String
              }
            end

            type light =
              {
                :png_1x => String,
                :png_2x => String,
                :png_4x => String,
                svg: String
              }

            class Light < WhopSDK::Internal::Type::BaseModel
              attr_accessor png_1x: String

              attr_accessor png_2x: String

              attr_accessor png_4x: String

              attr_accessor svg: String

              def initialize: (
                png_1x: String,
                png_2x: String,
                png_4x: String,
                svg: String
              ) -> void

              def to_hash: -> {
                :png_1x => String,
                :png_2x => String,
                :png_4x => String,
                svg: String
              }
            end
          end

          type square =
            {
              dark: WhopSDK::SetupIntent::PaymentInstrument::Icons::Square::Dark,
              light: WhopSDK::SetupIntent::PaymentInstrument::Icons::Square::Light
            }

          class Square < WhopSDK::Internal::Type::BaseModel
            attr_accessor dark: WhopSDK::SetupIntent::PaymentInstrument::Icons::Square::Dark

            attr_accessor light: WhopSDK::SetupIntent::PaymentInstrument::Icons::Square::Light

            def initialize: (
              dark: WhopSDK::SetupIntent::PaymentInstrument::Icons::Square::Dark,
              light: WhopSDK::SetupIntent::PaymentInstrument::Icons::Square::Light
            ) -> void

            def to_hash: -> {
              dark: WhopSDK::SetupIntent::PaymentInstrument::Icons::Square::Dark,
              light: WhopSDK::SetupIntent::PaymentInstrument::Icons::Square::Light
            }

            type dark =
              {
                :png_1x => String,
                :png_2x => String,
                :png_4x => String,
                svg: String
              }

            class Dark < WhopSDK::Internal::Type::BaseModel
              attr_accessor png_1x: String

              attr_accessor png_2x: String

              attr_accessor png_4x: String

              attr_accessor svg: String

              def initialize: (
                png_1x: String,
                png_2x: String,
                png_4x: String,
                svg: String
              ) -> void

              def to_hash: -> {
                :png_1x => String,
                :png_2x => String,
                :png_4x => String,
                svg: String
              }
            end

            type light =
              {
                :png_1x => String,
                :png_2x => String,
                :png_4x => String,
                svg: String
              }

            class Light < WhopSDK::Internal::Type::BaseModel
              attr_accessor png_1x: String

              attr_accessor png_2x: String

              attr_accessor png_4x: String

              attr_accessor svg: String

              def initialize: (
                png_1x: String,
                png_2x: String,
                png_4x: String,
                svg: String
              ) -> void

              def to_hash: -> {
                :png_1x => String,
                :png_2x => String,
                :png_4x => String,
                svg: String
              }
            end
          end
        end
      end

      type status = :processing | :succeeded | :canceled | :requires_action

      module Status
        extend WhopSDK::Internal::Type::Enum

        PROCESSING: :processing
        SUCCEEDED: :succeeded
        CANCELED: :canceled
        REQUIRES_ACTION: :requires_action

        def self?.values: -> ::Array[WhopSDK::Models::SetupIntent::status]
      end

      type user =
        {
          id: String,
          name: String?,
          profile_picture: WhopSDK::SetupIntent::User::ProfilePicture,
          username: String
        }

      class User < WhopSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor name: String?

        attr_accessor profile_picture: WhopSDK::SetupIntent::User::ProfilePicture

        attr_accessor username: String

        def initialize: (
          id: String,
          name: String?,
          profile_picture: WhopSDK::SetupIntent::User::ProfilePicture,
          username: String
        ) -> void

        def to_hash: -> {
          id: String,
          name: String?,
          profile_picture: WhopSDK::SetupIntent::User::ProfilePicture,
          username: String
        }

        type profile_picture = { url: String }

        class ProfilePicture < WhopSDK::Internal::Type::BaseModel
          attr_accessor url: String

          def initialize: (url: String) -> void

          def to_hash: -> { url: String }
        end
      end
    end
  end
end
