module WhopSDK
  module Models
    type setup_intent_list_params =
      {
        company_id: String,
        after: String,
        before: String,
        created_after: Time,
        created_before: Time,
        direction: WhopSDK::Models::direction,
        first: Integer,
        last: Integer
      }
      & WhopSDK::Internal::Type::request_parameters

    class SetupIntentListParams < WhopSDK::Internal::Type::BaseModel
      extend WhopSDK::Internal::Type::RequestParameters::Converter
      include WhopSDK::Internal::Type::RequestParameters

      attr_accessor company_id: String

      attr_reader after: String?

      def after=: (String) -> String

      attr_reader before: String?

      def before=: (String) -> String

      attr_reader created_after: Time?

      def created_after=: (Time) -> Time

      attr_reader created_before: Time?

      def created_before=: (Time) -> Time

      attr_reader direction: WhopSDK::Models::direction?

      def direction=: (WhopSDK::Models::direction) -> WhopSDK::Models::direction

      attr_reader first: Integer?

      def first=: (Integer) -> Integer

      attr_reader last: Integer?

      def last=: (Integer) -> Integer

      def initialize: (
        company_id: String,
        ?after: String,
        ?before: String,
        ?created_after: Time,
        ?created_before: Time,
        ?direction: WhopSDK::Models::direction,
        ?first: Integer,
        ?last: Integer,
        ?request_options: WhopSDK::request_opts
      ) -> void

      def to_hash: -> {
        company_id: String,
        after: String,
        before: String,
        created_after: Time,
        created_before: Time,
        direction: WhopSDK::Models::direction,
        first: Integer,
        last: Integer,
        request_options: WhopSDK::RequestOptions
      }
    end
  end
end
