module WhopSDK
  module Models
    type shipment_list_params =
      {
        after: String?,
        before: String?,
        company_id: String?,
        first: Integer?,
        last: Integer?,
        payment_id: String?,
        user_id: String?
      }
      & WhopSDK::Internal::Type::request_parameters

    class ShipmentListParams < WhopSDK::Internal::Type::BaseModel
      extend WhopSDK::Internal::Type::RequestParameters::Converter
      include WhopSDK::Internal::Type::RequestParameters

      attr_accessor after: String?

      attr_accessor before: String?

      attr_accessor company_id: String?

      attr_accessor first: Integer?

      attr_accessor last: Integer?

      attr_accessor payment_id: String?

      attr_accessor user_id: String?

      def initialize: (
        ?after: String?,
        ?before: String?,
        ?company_id: String?,
        ?first: Integer?,
        ?last: Integer?,
        ?payment_id: String?,
        ?user_id: String?,
        ?request_options: WhopSDK::request_opts
      ) -> void

      def to_hash: -> {
        after: String?,
        before: String?,
        company_id: String?,
        first: Integer?,
        last: Integer?,
        payment_id: String?,
        user_id: String?,
        request_options: WhopSDK::RequestOptions
      }
    end
  end
end
