module WhopSDK
  module Models
    type shipment =
      {
        id: String,
        account_id: String,
        carrier: String?,
        checkpoints: ::Array[WhopSDK::Shipment::Checkpoint],
        created_at: String,
        payment_id: String,
        status: WhopSDK::Models::Shipment::status,
        tracking_number: String,
        tracking_url: String,
        updated_at: String
      }

    class Shipment < WhopSDK::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor account_id: String

      attr_accessor carrier: String?

      attr_accessor checkpoints: ::Array[WhopSDK::Shipment::Checkpoint]

      attr_accessor created_at: String

      attr_accessor payment_id: String

      attr_accessor status: WhopSDK::Models::Shipment::status

      attr_accessor tracking_number: String

      attr_accessor tracking_url: String

      attr_accessor updated_at: String

      def initialize: (
        id: String,
        account_id: String,
        carrier: String?,
        checkpoints: ::Array[WhopSDK::Shipment::Checkpoint],
        created_at: String,
        payment_id: String,
        status: WhopSDK::Models::Shipment::status,
        tracking_number: String,
        tracking_url: String,
        updated_at: String
      ) -> void

      def to_hash: -> {
        id: String,
        account_id: String,
        carrier: String?,
        checkpoints: ::Array[WhopSDK::Shipment::Checkpoint],
        created_at: String,
        payment_id: String,
        status: WhopSDK::Models::Shipment::status,
        tracking_number: String,
        tracking_url: String,
        updated_at: String
      }

      type checkpoint =
        {
          location: String?,
          message: String?,
          status: WhopSDK::Models::Shipment::Checkpoint::status,
          timestamp: String?
        }

      class Checkpoint < WhopSDK::Internal::Type::BaseModel
        attr_accessor location: String?

        attr_accessor message: String?

        attr_accessor status: WhopSDK::Models::Shipment::Checkpoint::status

        attr_accessor timestamp: String?

        def initialize: (
          location: String?,
          message: String?,
          status: WhopSDK::Models::Shipment::Checkpoint::status,
          timestamp: String?
        ) -> void

        def to_hash: -> {
          location: String?,
          message: String?,
          status: WhopSDK::Models::Shipment::Checkpoint::status,
          timestamp: String?
        }

        type status =
          :unknown
          | :pre_transit
          | :in_transit
          | :out_for_delivery
          | :delivered
          | :available_for_pickup
          | :return_to_sender
          | :failure
          | :cancelled
          | :error

        module Status
          extend WhopSDK::Internal::Type::Enum

          UNKNOWN: :unknown
          PRE_TRANSIT: :pre_transit
          IN_TRANSIT: :in_transit
          OUT_FOR_DELIVERY: :out_for_delivery
          DELIVERED: :delivered
          AVAILABLE_FOR_PICKUP: :available_for_pickup
          RETURN_TO_SENDER: :return_to_sender
          FAILURE: :failure
          CANCELLED: :cancelled
          ERROR: :error

          def self?.values: -> ::Array[WhopSDK::Models::Shipment::Checkpoint::status]
        end
      end

      type status =
        :unknown
        | :pre_transit
        | :in_transit
        | :out_for_delivery
        | :delivered
        | :available_for_pickup
        | :return_to_sender
        | :failure
        | :cancelled
        | :error

      module Status
        extend WhopSDK::Internal::Type::Enum

        UNKNOWN: :unknown
        PRE_TRANSIT: :pre_transit
        IN_TRANSIT: :in_transit
        OUT_FOR_DELIVERY: :out_for_delivery
        DELIVERED: :delivered
        AVAILABLE_FOR_PICKUP: :available_for_pickup
        RETURN_TO_SENDER: :return_to_sender
        FAILURE: :failure
        CANCELLED: :cancelled
        ERROR: :error

        def self?.values: -> ::Array[WhopSDK::Models::Shipment::status]
      end
    end
  end
end
