module WhopSDK
  module Models
    type social_account_delete_params =
      { id: String, account_id: String, user_id: String }
      & WhopSDK::Internal::Type::request_parameters

    class SocialAccountDeleteParams < WhopSDK::Internal::Type::BaseModel
      extend WhopSDK::Internal::Type::RequestParameters::Converter
      include WhopSDK::Internal::Type::RequestParameters

      attr_accessor id: String

      attr_reader account_id: String?

      def account_id=: (String) -> String

      attr_reader user_id: String?

      def user_id=: (String) -> String

      def initialize: (
        id: String,
        ?account_id: String,
        ?user_id: String,
        ?request_options: WhopSDK::request_opts
      ) -> void

      def to_hash: -> {
        id: String,
        account_id: String,
        user_id: String,
        request_options: WhopSDK::RequestOptions
      }
    end
  end
end
