module WhopSDK
  module Models
    type social_account_post =
      {
        id: String,
        call_to_action: WhopSDK::Models::SocialAccountPost::call_to_action?,
        destination_url: String?,
        media_url: String?,
        thumbnail_url: String?
      }

    class SocialAccountPost < WhopSDK::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor call_to_action: WhopSDK::Models::SocialAccountPost::call_to_action?

      attr_accessor destination_url: String?

      attr_accessor media_url: String?

      attr_accessor thumbnail_url: String?

      def initialize: (
        id: String,
        call_to_action: WhopSDK::Models::SocialAccountPost::call_to_action?,
        destination_url: String?,
        media_url: String?,
        thumbnail_url: String?
      ) -> void

      def to_hash: -> {
        id: String,
        call_to_action: WhopSDK::Models::SocialAccountPost::call_to_action?,
        destination_url: String?,
        media_url: String?,
        thumbnail_url: String?
      }

      type call_to_action =
        :learn_more
        | :shop_now
        | :sign_up
        | :subscribe
        | :get_started
        | :book_now
        | :apply_now
        | :contact_us
        | :download
        | :order_now
        | :buy_now
        | :get_quote
        | :message_page
        | :whatsapp_message
        | :instagram_message
        | :call_now
        | :get_directions
        | :send_updates
        | :get_offer
        | :watch_more
        | :listen_now
        | :play_game
        | :open_link
        | :no_button
        | :get_offer_view
        | :get_event_tickets
        | :see_menu
        | :request_time
        | :event_rsvp
        | :see_details
        | :view_instagram_profile

      module CallToAction
        extend WhopSDK::Internal::Type::Enum

        LEARN_MORE: :learn_more
        SHOP_NOW: :shop_now
        SIGN_UP: :sign_up
        SUBSCRIBE: :subscribe
        GET_STARTED: :get_started
        BOOK_NOW: :book_now
        APPLY_NOW: :apply_now
        CONTACT_US: :contact_us
        DOWNLOAD: :download
        ORDER_NOW: :order_now
        BUY_NOW: :buy_now
        GET_QUOTE: :get_quote
        MESSAGE_PAGE: :message_page
        WHATSAPP_MESSAGE: :whatsapp_message
        INSTAGRAM_MESSAGE: :instagram_message
        CALL_NOW: :call_now
        GET_DIRECTIONS: :get_directions
        SEND_UPDATES: :send_updates
        GET_OFFER: :get_offer
        WATCH_MORE: :watch_more
        LISTEN_NOW: :listen_now
        PLAY_GAME: :play_game
        OPEN_LINK: :open_link
        NO_BUTTON: :no_button
        GET_OFFER_VIEW: :get_offer_view
        GET_EVENT_TICKETS: :get_event_tickets
        SEE_MENU: :see_menu
        REQUEST_TIME: :request_time
        EVENT_RSVP: :event_rsvp
        SEE_DETAILS: :see_details
        VIEW_INSTAGRAM_PROFILE: :view_instagram_profile

        def self?.values: -> ::Array[WhopSDK::Models::SocialAccountPost::call_to_action]
      end
    end
  end
end
