module WhopSDK
  module Models
    type stat_run_sql_params =
      {
        resource: String,
        sql: String,
        company_id: String?,
        cursor: String?,
        from: Time?,
        limit: Integer?,
        sort: String?,
        sort_direction: WhopSDK::Models::direction?,
        to: Time?,
        user_id: String?
      }
      & WhopSDK::Internal::Type::request_parameters

    class StatRunSqlParams < WhopSDK::Internal::Type::BaseModel
      extend WhopSDK::Internal::Type::RequestParameters::Converter
      include WhopSDK::Internal::Type::RequestParameters

      attr_accessor resource: String

      attr_accessor sql: String

      attr_accessor company_id: String?

      attr_accessor cursor: String?

      attr_accessor from: Time?

      attr_accessor limit: Integer?

      attr_accessor sort: String?

      attr_accessor sort_direction: WhopSDK::Models::direction?

      attr_accessor to: Time?

      attr_accessor user_id: String?

      def initialize: (
        resource: String,
        sql: String,
        ?company_id: String?,
        ?cursor: String?,
        ?from: Time?,
        ?limit: Integer?,
        ?sort: String?,
        ?sort_direction: WhopSDK::Models::direction?,
        ?to: Time?,
        ?user_id: String?,
        ?request_options: WhopSDK::request_opts
      ) -> void

      def to_hash: -> {
        resource: String,
        sql: String,
        company_id: String?,
        cursor: String?,
        from: Time?,
        limit: Integer?,
        sort: String?,
        sort_direction: WhopSDK::Models::direction?,
        to: Time?,
        user_id: String?,
        request_options: WhopSDK::RequestOptions
      }
    end
  end
end
