module WhopSDK
  module Models
    type stat_retrieve_response =
      { data: WhopSDK::Models::StatRetrieveResponse::Data }

    class StatRetrieveResponse < WhopSDK::Internal::Type::BaseModel
      attr_accessor data: WhopSDK::Models::StatRetrieveResponse::Data

      def initialize: (
        data: WhopSDK::Models::StatRetrieveResponse::Data
      ) -> void

      def to_hash: -> { data: WhopSDK::Models::StatRetrieveResponse::Data }

      type data =
        {
          points: ::Array[WhopSDK::Models::StatRetrieveResponse::Data::Point],
          currency: String?
        }

      class Data < WhopSDK::Internal::Type::BaseModel
        attr_accessor points: ::Array[WhopSDK::Models::StatRetrieveResponse::Data::Point]

        attr_accessor currency: String?

        def initialize: (
          points: ::Array[WhopSDK::Models::StatRetrieveResponse::Data::Point],
          ?currency: String?
        ) -> void

        def to_hash: -> {
          points: ::Array[WhopSDK::Models::StatRetrieveResponse::Data::Point],
          currency: String?
        }

        type point =
          {
            timestamp: Integer,
            value: Float?,
            breakdown: ::Array[WhopSDK::Models::StatRetrieveResponse::Data::Point::Breakdown]
          }

        class Point < WhopSDK::Internal::Type::BaseModel
          attr_accessor timestamp: Integer

          attr_accessor value: Float?

          attr_reader breakdown: ::Array[WhopSDK::Models::StatRetrieveResponse::Data::Point::Breakdown]?

          def breakdown=: (
            ::Array[WhopSDK::Models::StatRetrieveResponse::Data::Point::Breakdown]
          ) -> ::Array[WhopSDK::Models::StatRetrieveResponse::Data::Point::Breakdown]

          def initialize: (
            timestamp: Integer,
            value: Float?,
            ?breakdown: ::Array[WhopSDK::Models::StatRetrieveResponse::Data::Point::Breakdown]
          ) -> void

          def to_hash: -> {
            timestamp: Integer,
            value: Float?,
            breakdown: ::Array[WhopSDK::Models::StatRetrieveResponse::Data::Point::Breakdown]
          }

          type breakdown = { name: String, value: Float? }

          class Breakdown < WhopSDK::Internal::Type::BaseModel
            attr_accessor name: String

            attr_accessor value: Float?

            def initialize: (name: String, value: Float?) -> void

            def to_hash: -> { name: String, value: Float? }
          end
        end
      end
    end
  end
end
