module WhopSDK
  module Models
    type support_channel_list_params =
      {
        after: String?,
        before: String?,
        company_id: String?,
        direction: WhopSDK::Models::direction?,
        first: Integer?,
        last: Integer?,
        open_: bool?,
        order: WhopSDK::Models::SupportChannelListParams::order?,
        view: WhopSDK::Models::SupportChannelListParams::view?
      }
      & WhopSDK::Internal::Type::request_parameters

    class SupportChannelListParams < WhopSDK::Internal::Type::BaseModel
      extend WhopSDK::Internal::Type::RequestParameters::Converter
      include WhopSDK::Internal::Type::RequestParameters

      attr_accessor after: String?

      attr_accessor before: String?

      attr_accessor company_id: String?

      attr_accessor direction: WhopSDK::Models::direction?

      attr_accessor first: Integer?

      attr_accessor last: Integer?

      attr_accessor open_: bool?

      attr_accessor order: WhopSDK::Models::SupportChannelListParams::order?

      attr_accessor view: WhopSDK::Models::SupportChannelListParams::view?

      def initialize: (
        ?after: String?,
        ?before: String?,
        ?company_id: String?,
        ?direction: WhopSDK::Models::direction?,
        ?first: Integer?,
        ?last: Integer?,
        ?open_: bool?,
        ?order: WhopSDK::Models::SupportChannelListParams::order?,
        ?view: WhopSDK::Models::SupportChannelListParams::view?,
        ?request_options: WhopSDK::request_opts
      ) -> void

      def to_hash: -> {
        after: String?,
        before: String?,
        company_id: String?,
        direction: WhopSDK::Models::direction?,
        first: Integer?,
        last: Integer?,
        open_: bool?,
        order: WhopSDK::Models::SupportChannelListParams::order?,
        view: WhopSDK::Models::SupportChannelListParams::view?,
        request_options: WhopSDK::RequestOptions
      }

      type order = :created_at | :last_post_sent_at

      module Order
        extend WhopSDK::Internal::Type::Enum

        CREATED_AT: :created_at
        LAST_POST_SENT_AT: :last_post_sent_at

        def self?.values: -> ::Array[WhopSDK::Models::SupportChannelListParams::order]
      end

      type view = :all | :admin | :customer

      module View
        extend WhopSDK::Internal::Type::Enum

        ALL: :all
        ADMIN: :admin
        CUSTOMER: :customer

        def self?.values: -> ::Array[WhopSDK::Models::SupportChannelListParams::view]
      end
    end
  end
end
