module WhopSDK
  module Models
    type support_channel_create_params =
      {
        account_id: String,
        user_id: String,
        custom_name: String?,
        notifications_enabled: bool?
      }
      & WhopSDK::Internal::Type::request_parameters

    class SupportChannelCreateParams < WhopSDK::Internal::Type::BaseModel
      extend WhopSDK::Internal::Type::RequestParameters::Converter
      include WhopSDK::Internal::Type::RequestParameters

      attr_accessor account_id: String

      attr_accessor user_id: String

      attr_accessor custom_name: String?

      attr_accessor notifications_enabled: bool?

      def initialize: (
        account_id: String,
        user_id: String,
        ?custom_name: String?,
        ?notifications_enabled: bool?,
        ?request_options: WhopSDK::request_opts
      ) -> void

      def to_hash: -> {
        account_id: String,
        user_id: String,
        custom_name: String?,
        notifications_enabled: bool?,
        request_options: WhopSDK::RequestOptions
      }
    end
  end
end
