module WhopSDK
  module Models
    type support_channel_list_params =
      {
        account_id: String,
        after: String,
        before: String,
        direction: WhopSDK::Models::direction,
        first: Integer,
        last: Integer,
        open_: bool,
        order: WhopSDK::Models::SupportChannelListParams::order,
        view: WhopSDK::Models::SupportChannelListParams::view
      }
      & WhopSDK::Internal::Type::request_parameters

    class SupportChannelListParams < WhopSDK::Internal::Type::BaseModel
      extend WhopSDK::Internal::Type::RequestParameters::Converter
      include WhopSDK::Internal::Type::RequestParameters

      attr_reader account_id: String?

      def account_id=: (String) -> String

      attr_reader after: String?

      def after=: (String) -> String

      attr_reader before: String?

      def before=: (String) -> String

      attr_reader direction: WhopSDK::Models::direction?

      def direction=: (WhopSDK::Models::direction) -> WhopSDK::Models::direction

      attr_reader first: Integer?

      def first=: (Integer) -> Integer

      attr_reader last: Integer?

      def last=: (Integer) -> Integer

      attr_reader open_: bool?

      def open_=: (bool) -> bool

      attr_reader order: WhopSDK::Models::SupportChannelListParams::order?

      def order=: (
        WhopSDK::Models::SupportChannelListParams::order
      ) -> WhopSDK::Models::SupportChannelListParams::order

      attr_reader view: WhopSDK::Models::SupportChannelListParams::view?

      def view=: (
        WhopSDK::Models::SupportChannelListParams::view
      ) -> WhopSDK::Models::SupportChannelListParams::view

      def initialize: (
        ?account_id: String,
        ?after: String,
        ?before: String,
        ?direction: WhopSDK::Models::direction,
        ?first: Integer,
        ?last: Integer,
        ?open_: bool,
        ?order: WhopSDK::Models::SupportChannelListParams::order,
        ?view: WhopSDK::Models::SupportChannelListParams::view,
        ?request_options: WhopSDK::request_opts
      ) -> void

      def to_hash: -> {
        account_id: String,
        after: String,
        before: String,
        direction: WhopSDK::Models::direction,
        first: Integer,
        last: Integer,
        open_: bool,
        order: WhopSDK::Models::SupportChannelListParams::order,
        view: WhopSDK::Models::SupportChannelListParams::view,
        request_options: WhopSDK::RequestOptions
      }

      type order = :created_at | :last_post_sent_at

      module Order
        extend WhopSDK::Internal::Type::Enum

        CREATED_AT: :created_at
        LAST_POST_SENT_AT: :last_post_sent_at

        def self?.values: -> ::Array[WhopSDK::Models::SupportChannelListParams::order]
      end

      type view = :all | :admin | :customer

      module View
        extend WhopSDK::Internal::Type::Enum

        ALL: :all
        ADMIN: :admin
        CUSTOMER: :customer

        def self?.values: -> ::Array[WhopSDK::Models::SupportChannelListParams::view]
      end
    end
  end
end
