module WhopSDK
  module Models
    type support_channel_create_params =
      { company_id: String, user_id: String, custom_name: String? }
      & WhopSDK::Internal::Type::request_parameters

    class SupportChannelCreateParams < WhopSDK::Internal::Type::BaseModel
      extend WhopSDK::Internal::Type::RequestParameters::Converter
      include WhopSDK::Internal::Type::RequestParameters

      attr_accessor company_id: String

      attr_accessor user_id: String

      attr_accessor custom_name: String?

      def initialize: (
        company_id: String,
        user_id: String,
        ?custom_name: String?,
        ?request_options: WhopSDK::request_opts
      ) -> void

      def to_hash: -> {
        company_id: String,
        user_id: String,
        custom_name: String?,
        request_options: WhopSDK::RequestOptions
      }
    end
  end
end
