module WhopSDK
  module Models
    type tax_identifier_type =
      :ad_nrt
      | :ao_tin
      | :ar_cuit
      | :am_tin
      | :aw_tin
      | :au_abn
      | :au_arn
      | :eu_vat
      | :az_tin
      | :bs_tin
      | :bh_vat
      | :bd_bin
      | :bb_tin
      | :by_tin
      | :bj_ifu
      | :bo_tin
      | :ba_tin
      | :br_cnpj
      | :br_cpf
      | :bg_uic
      | :bf_ifu
      | :kh_tin
      | :cm_niu
      | :ca_bn
      | :ca_gst_hst
      | :ca_pst_bc
      | :ca_pst_mb
      | :ca_pst_sk
      | :ca_qst
      | :cv_nif
      | :cl_tin
      | :cn_tin
      | :co_nit
      | :cd_nif
      | :cr_tin
      | :hr_oib
      | :do_rcn
      | :ec_ruc
      | :eg_tin
      | :sv_nit
      | :et_tin
      | :eu_oss_vat
      | :ge_vat
      | :de_stn
      | :gb_vat
      | :gn_nif
      | :hk_br
      | :hu_tin
      | :is_vat
      | :in_gst
      | :id_npwp
      | :il_vat
      | :jp_cn
      | :jp_rn
      | :jp_trn
      | :kz_bin
      | :ke_pin
      | :kg_tin
      | :la_tin
      | :li_uid
      | :li_vat
      | :my_frp
      | :my_itn
      | :my_sst
      | :mr_nif
      | :mx_rfc
      | :md_vat
      | :me_pib
      | :ma_vat
      | :np_pan
      | :nz_gst
      | :ng_tin
      | :mk_vat
      | :no_vat
      | :no_voec
      | :om_vat
      | :pe_ruc
      | :ph_tin
      | :pl_nip
      | :ro_tin
      | :ru_inn
      | :ru_kpp
      | :sa_vat
      | :sn_ninea
      | :rs_pib
      | :sg_gst
      | :sg_uen
      | :si_tin
      | :za_vat
      | :kr_brn
      | :es_cif
      | :ch_uid
      | :ch_vat
      | :tw_vat
      | :tj_tin
      | :tz_vat
      | :th_vat
      | :tr_tin
      | :ug_tin
      | :ua_vat
      | :ae_trn
      | :us_ein
      | :uy_ruc
      | :uz_tin
      | :uz_vat
      | :ve_rif
      | :vn_tin
      | :zm_tin
      | :zw_tin
      | :sr_fin
      | :xi_vat

    module TaxIdentifierType
      extend WhopSDK::Internal::Type::Enum

      AD_NRT: :ad_nrt
      AO_TIN: :ao_tin
      AR_CUIT: :ar_cuit
      AM_TIN: :am_tin
      AW_TIN: :aw_tin
      AU_ABN: :au_abn
      AU_ARN: :au_arn
      EU_VAT: :eu_vat
      AZ_TIN: :az_tin
      BS_TIN: :bs_tin
      BH_VAT: :bh_vat
      BD_BIN: :bd_bin
      BB_TIN: :bb_tin
      BY_TIN: :by_tin
      BJ_IFU: :bj_ifu
      BO_TIN: :bo_tin
      BA_TIN: :ba_tin
      BR_CNPJ: :br_cnpj
      BR_CPF: :br_cpf
      BG_UIC: :bg_uic
      BF_IFU: :bf_ifu
      KH_TIN: :kh_tin
      CM_NIU: :cm_niu
      CA_BN: :ca_bn
      CA_GST_HST: :ca_gst_hst
      CA_PST_BC: :ca_pst_bc
      CA_PST_MB: :ca_pst_mb
      CA_PST_SK: :ca_pst_sk
      CA_QST: :ca_qst
      CV_NIF: :cv_nif
      CL_TIN: :cl_tin
      CN_TIN: :cn_tin
      CO_NIT: :co_nit
      CD_NIF: :cd_nif
      CR_TIN: :cr_tin
      HR_OIB: :hr_oib
      DO_RCN: :do_rcn
      EC_RUC: :ec_ruc
      EG_TIN: :eg_tin
      SV_NIT: :sv_nit
      ET_TIN: :et_tin
      EU_OSS_VAT: :eu_oss_vat
      GE_VAT: :ge_vat
      DE_STN: :de_stn
      GB_VAT: :gb_vat
      GN_NIF: :gn_nif
      HK_BR: :hk_br
      HU_TIN: :hu_tin
      IS_VAT: :is_vat
      IN_GST: :in_gst
      ID_NPWP: :id_npwp
      IL_VAT: :il_vat
      JP_CN: :jp_cn
      JP_RN: :jp_rn
      JP_TRN: :jp_trn
      KZ_BIN: :kz_bin
      KE_PIN: :ke_pin
      KG_TIN: :kg_tin
      LA_TIN: :la_tin
      LI_UID: :li_uid
      LI_VAT: :li_vat
      MY_FRP: :my_frp
      MY_ITN: :my_itn
      MY_SST: :my_sst
      MR_NIF: :mr_nif
      MX_RFC: :mx_rfc
      MD_VAT: :md_vat
      ME_PIB: :me_pib
      MA_VAT: :ma_vat
      NP_PAN: :np_pan
      NZ_GST: :nz_gst
      NG_TIN: :ng_tin
      MK_VAT: :mk_vat
      NO_VAT: :no_vat
      NO_VOEC: :no_voec
      OM_VAT: :om_vat
      PE_RUC: :pe_ruc
      PH_TIN: :ph_tin
      PL_NIP: :pl_nip
      RO_TIN: :ro_tin
      RU_INN: :ru_inn
      RU_KPP: :ru_kpp
      SA_VAT: :sa_vat
      SN_NINEA: :sn_ninea
      RS_PIB: :rs_pib
      SG_GST: :sg_gst
      SG_UEN: :sg_uen
      SI_TIN: :si_tin
      ZA_VAT: :za_vat
      KR_BRN: :kr_brn
      ES_CIF: :es_cif
      CH_UID: :ch_uid
      CH_VAT: :ch_vat
      TW_VAT: :tw_vat
      TJ_TIN: :tj_tin
      TZ_VAT: :tz_vat
      TH_VAT: :th_vat
      TR_TIN: :tr_tin
      UG_TIN: :ug_tin
      UA_VAT: :ua_vat
      AE_TRN: :ae_trn
      US_EIN: :us_ein
      UY_RUC: :uy_ruc
      UZ_TIN: :uz_tin
      UZ_VAT: :uz_vat
      VE_RIF: :ve_rif
      VN_TIN: :vn_tin
      ZM_TIN: :zm_tin
      ZW_TIN: :zw_tin
      SR_FIN: :sr_fin
      XI_VAT: :xi_vat

      def self?.values: -> ::Array[WhopSDK::Models::tax_identifier_type]
    end
  end
end
