module WhopSDK
  module Models
    type transfer_create_response =
      WhopSDK::Models::TransferCreateResponse::Transfer
      | WhopSDK::Models::TransferCreateResponse::Send
      | WhopSDK::Models::TransferCreateResponse::ClaimLink

    module TransferCreateResponse
      extend WhopSDK::Internal::Type::Union

      type transfer =
        {
          id: String,
          amount: Float,
          created_at: Time,
          created_by_user: WhopSDK::Models::TransferCreateResponse::Transfer::CreatedByUser?,
          currency: String,
          destination: WhopSDK::Models::TransferCreateResponse::Transfer::destination,
          destination_ledger_account_id: String,
          object: WhopSDK::Models::TransferCreateResponse::Transfer::object,
          origin: WhopSDK::Models::TransferCreateResponse::Transfer::origin,
          origin_ledger_account_id: String,
          status: WhopSDK::Models::TransferCreateResponse::Transfer::status,
          failed_at: Time?,
          failure_code: String?,
          failure_reason: String?,
          fee_amount: Float?,
          metadata: ::Hash[Symbol, top]?,
          notes: String?
        }

      class Transfer < WhopSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor amount: Float

        attr_accessor created_at: Time

        attr_accessor created_by_user: WhopSDK::Models::TransferCreateResponse::Transfer::CreatedByUser?

        attr_accessor currency: String

        attr_accessor destination: WhopSDK::Models::TransferCreateResponse::Transfer::destination

        attr_accessor destination_ledger_account_id: String

        attr_accessor object: WhopSDK::Models::TransferCreateResponse::Transfer::object

        attr_accessor origin: WhopSDK::Models::TransferCreateResponse::Transfer::origin

        attr_accessor origin_ledger_account_id: String

        attr_accessor status: WhopSDK::Models::TransferCreateResponse::Transfer::status

        attr_accessor failed_at: Time?

        attr_accessor failure_code: String?

        attr_accessor failure_reason: String?

        attr_accessor fee_amount: Float?

        attr_accessor metadata: ::Hash[Symbol, top]?

        attr_accessor notes: String?

        def initialize: (
          id: String,
          amount: Float,
          created_at: Time,
          created_by_user: WhopSDK::Models::TransferCreateResponse::Transfer::CreatedByUser?,
          currency: String,
          destination: WhopSDK::Models::TransferCreateResponse::Transfer::destination,
          destination_ledger_account_id: String,
          object: WhopSDK::Models::TransferCreateResponse::Transfer::object,
          origin: WhopSDK::Models::TransferCreateResponse::Transfer::origin,
          origin_ledger_account_id: String,
          status: WhopSDK::Models::TransferCreateResponse::Transfer::status,
          ?failed_at: Time?,
          ?failure_code: String?,
          ?failure_reason: String?,
          ?fee_amount: Float?,
          ?metadata: ::Hash[Symbol, top]?,
          ?notes: String?
        ) -> void

        def to_hash: -> {
          id: String,
          amount: Float,
          created_at: Time,
          created_by_user: WhopSDK::Models::TransferCreateResponse::Transfer::CreatedByUser?,
          currency: String,
          destination: WhopSDK::Models::TransferCreateResponse::Transfer::destination,
          destination_ledger_account_id: String,
          object: WhopSDK::Models::TransferCreateResponse::Transfer::object,
          origin: WhopSDK::Models::TransferCreateResponse::Transfer::origin,
          origin_ledger_account_id: String,
          status: WhopSDK::Models::TransferCreateResponse::Transfer::status,
          failed_at: Time?,
          failure_code: String?,
          failure_reason: String?,
          fee_amount: Float?,
          metadata: ::Hash[Symbol, top]?,
          notes: String?
        }

        type created_by_user = { id: String, username: String, name: String? }

        class CreatedByUser < WhopSDK::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor username: String

          attr_accessor name: String?

          def initialize: (id: String, username: String, ?name: String?) -> void

          def to_hash: -> { id: String, username: String, name: String? }
        end

        type destination =
          WhopSDK::Models::TransferCreateResponse::Transfer::Destination::Company
          | WhopSDK::Models::TransferCreateResponse::Transfer::Destination::User

        module Destination
          extend WhopSDK::Internal::Type::Union

          type company =
            { id: String, typename: :Company, route: String?, title: String? }

          class Company < WhopSDK::Internal::Type::BaseModel
            attr_accessor id: String

            attr_accessor typename: :Company

            attr_accessor route: String?

            attr_accessor title: String?

            def initialize: (
              id: String,
              ?route: String?,
              ?title: String?,
              ?typename: :Company
            ) -> void

            def to_hash: -> {
              id: String,
              typename: :Company,
              route: String?,
              title: String?
            }
          end

          type user =
            { id: String, typename: :User, name: String?, username: String }

          class User < WhopSDK::Internal::Type::BaseModel
            attr_accessor id: String

            attr_accessor typename: :User

            attr_accessor name: String?

            attr_reader username: String?

            def username=: (String) -> String

            def initialize: (
              id: String,
              ?name: String?,
              ?username: String,
              ?typename: :User
            ) -> void

            def to_hash: -> {
              id: String,
              typename: :User,
              name: String?,
              username: String
            }
          end

          def self?.variants: -> ::Array[WhopSDK::Models::TransferCreateResponse::Transfer::destination]
        end

        type object = :transfer

        module Object
          extend WhopSDK::Internal::Type::Enum

          TRANSFER: :transfer

          def self?.values: -> ::Array[WhopSDK::Models::TransferCreateResponse::Transfer::object]
        end

        type origin =
          WhopSDK::Models::TransferCreateResponse::Transfer::Origin::Company
          | WhopSDK::Models::TransferCreateResponse::Transfer::Origin::User

        module Origin
          extend WhopSDK::Internal::Type::Union

          type company =
            { id: String, typename: :Company, route: String?, title: String? }

          class Company < WhopSDK::Internal::Type::BaseModel
            attr_accessor id: String

            attr_accessor typename: :Company

            attr_accessor route: String?

            attr_accessor title: String?

            def initialize: (
              id: String,
              ?route: String?,
              ?title: String?,
              ?typename: :Company
            ) -> void

            def to_hash: -> {
              id: String,
              typename: :Company,
              route: String?,
              title: String?
            }
          end

          type user =
            { id: String, typename: :User, name: String?, username: String }

          class User < WhopSDK::Internal::Type::BaseModel
            attr_accessor id: String

            attr_accessor typename: :User

            attr_accessor name: String?

            attr_reader username: String?

            def username=: (String) -> String

            def initialize: (
              id: String,
              ?name: String?,
              ?username: String,
              ?typename: :User
            ) -> void

            def to_hash: -> {
              id: String,
              typename: :User,
              name: String?,
              username: String
            }
          end

          def self?.variants: -> ::Array[WhopSDK::Models::TransferCreateResponse::Transfer::origin]
        end

        type status = :processing | :succeeded | :failed

        module Status
          extend WhopSDK::Internal::Type::Enum

          PROCESSING: :processing
          SUCCEEDED: :succeeded
          FAILED: :failed

          def self?.values: -> ::Array[WhopSDK::Models::TransferCreateResponse::Transfer::status]
        end
      end

      type send_ =
        {
          amount: String,
          currency: String,
          destination: WhopSDK::Models::TransferCreateResponse::Send::Destination,
          object: WhopSDK::Models::TransferCreateResponse::Send::object,
          source: WhopSDK::Models::TransferCreateResponse::Send::Source,
          tx_hash: String
        }

      class Send < WhopSDK::Internal::Type::BaseModel
        attr_accessor amount: String

        attr_accessor currency: String

        attr_accessor destination: WhopSDK::Models::TransferCreateResponse::Send::Destination

        attr_accessor object: WhopSDK::Models::TransferCreateResponse::Send::object

        attr_accessor source: WhopSDK::Models::TransferCreateResponse::Send::Source

        attr_accessor tx_hash: String

        def initialize: (
          amount: String,
          currency: String,
          destination: WhopSDK::Models::TransferCreateResponse::Send::Destination,
          object: WhopSDK::Models::TransferCreateResponse::Send::object,
          source: WhopSDK::Models::TransferCreateResponse::Send::Source,
          tx_hash: String
        ) -> void

        def to_hash: -> {
          amount: String,
          currency: String,
          destination: WhopSDK::Models::TransferCreateResponse::Send::Destination,
          object: WhopSDK::Models::TransferCreateResponse::Send::object,
          source: WhopSDK::Models::TransferCreateResponse::Send::Source,
          tx_hash: String
        }

        type destination = { account_id: String, address: String }

        class Destination < WhopSDK::Internal::Type::BaseModel
          attr_accessor account_id: String

          attr_accessor address: String

          def initialize: (account_id: String, address: String) -> void

          def to_hash: -> { account_id: String, address: String }
        end

        type object = :send

        module Object
          extend WhopSDK::Internal::Type::Enum

          SEND: :send

          def self?.values: -> ::Array[WhopSDK::Models::TransferCreateResponse::Send::object]
        end

        type source = { account_id: String, address: String }

        class Source < WhopSDK::Internal::Type::BaseModel
          attr_accessor account_id: String

          attr_accessor address: String

          def initialize: (account_id: String, address: String) -> void

          def to_hash: -> { account_id: String, address: String }
        end
      end

      type claim_link =
        {
          id: String,
          amount: String,
          claim_url: String,
          currency: String,
          expires_at: Time?,
          object: WhopSDK::Models::TransferCreateResponse::ClaimLink::object,
          redeemable_count: Integer,
          source: WhopSDK::Models::TransferCreateResponse::ClaimLink::Source,
          status: WhopSDK::Models::TransferCreateResponse::ClaimLink::status
        }

      class ClaimLink < WhopSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor amount: String

        attr_accessor claim_url: String

        attr_accessor currency: String

        attr_accessor expires_at: Time?

        attr_accessor object: WhopSDK::Models::TransferCreateResponse::ClaimLink::object

        attr_accessor redeemable_count: Integer

        attr_accessor source: WhopSDK::Models::TransferCreateResponse::ClaimLink::Source

        attr_accessor status: WhopSDK::Models::TransferCreateResponse::ClaimLink::status

        def initialize: (
          id: String,
          amount: String,
          claim_url: String,
          currency: String,
          expires_at: Time?,
          object: WhopSDK::Models::TransferCreateResponse::ClaimLink::object,
          redeemable_count: Integer,
          source: WhopSDK::Models::TransferCreateResponse::ClaimLink::Source,
          status: WhopSDK::Models::TransferCreateResponse::ClaimLink::status
        ) -> void

        def to_hash: -> {
          id: String,
          amount: String,
          claim_url: String,
          currency: String,
          expires_at: Time?,
          object: WhopSDK::Models::TransferCreateResponse::ClaimLink::object,
          redeemable_count: Integer,
          source: WhopSDK::Models::TransferCreateResponse::ClaimLink::Source,
          status: WhopSDK::Models::TransferCreateResponse::ClaimLink::status
        }

        type object = :claim_link

        module Object
          extend WhopSDK::Internal::Type::Enum

          CLAIM_LINK: :claim_link

          def self?.values: -> ::Array[WhopSDK::Models::TransferCreateResponse::ClaimLink::object]
        end

        type source = { account_id: String }

        class Source < WhopSDK::Internal::Type::BaseModel
          attr_accessor account_id: String

          def initialize: (account_id: String) -> void

          def to_hash: -> { account_id: String }
        end

        type status = :pending

        module Status
          extend WhopSDK::Internal::Type::Enum

          PENDING: :pending

          def self?.values: -> ::Array[WhopSDK::Models::TransferCreateResponse::ClaimLink::status]
        end
      end

      def self?.variants: -> ::Array[WhopSDK::Models::transfer_create_response]
    end
  end
end
