module WhopSDK
  module Models
    type transfer_list_params =
      {
        after: String,
        before: String,
        created_after: String,
        created_before: String,
        destination_id: String,
        direction: WhopSDK::Models::TransferListParams::direction,
        first: Integer,
        last: Integer,
        order: WhopSDK::Models::TransferListParams::order,
        origin_id: String,
        api_version_date: String
      }
      & WhopSDK::Internal::Type::request_parameters

    class TransferListParams < WhopSDK::Internal::Type::BaseModel
      extend WhopSDK::Internal::Type::RequestParameters::Converter
      include WhopSDK::Internal::Type::RequestParameters

      attr_reader after: String?

      def after=: (String) -> String

      attr_reader before: String?

      def before=: (String) -> String

      attr_reader created_after: String?

      def created_after=: (String) -> String

      attr_reader created_before: String?

      def created_before=: (String) -> String

      attr_reader destination_id: String?

      def destination_id=: (String) -> String

      attr_reader direction: WhopSDK::Models::TransferListParams::direction?

      def direction=: (
        WhopSDK::Models::TransferListParams::direction
      ) -> WhopSDK::Models::TransferListParams::direction

      attr_reader first: Integer?

      def first=: (Integer) -> Integer

      attr_reader last: Integer?

      def last=: (Integer) -> Integer

      attr_reader order: WhopSDK::Models::TransferListParams::order?

      def order=: (
        WhopSDK::Models::TransferListParams::order
      ) -> WhopSDK::Models::TransferListParams::order

      attr_reader origin_id: String?

      def origin_id=: (String) -> String

      attr_reader api_version_date: String?

      def api_version_date=: (String) -> String

      def initialize: (
        ?after: String,
        ?before: String,
        ?created_after: String,
        ?created_before: String,
        ?destination_id: String,
        ?direction: WhopSDK::Models::TransferListParams::direction,
        ?first: Integer,
        ?last: Integer,
        ?order: WhopSDK::Models::TransferListParams::order,
        ?origin_id: String,
        ?api_version_date: String,
        ?request_options: WhopSDK::request_opts
      ) -> void

      def to_hash: -> {
        after: String,
        before: String,
        created_after: String,
        created_before: String,
        destination_id: String,
        direction: WhopSDK::Models::TransferListParams::direction,
        first: Integer,
        last: Integer,
        order: WhopSDK::Models::TransferListParams::order,
        origin_id: String,
        api_version_date: String,
        request_options: WhopSDK::RequestOptions
      }

      type direction = :asc | :desc

      module Direction
        extend WhopSDK::Internal::Type::Enum

        ASC: :asc
        DESC: :desc

        def self?.values: -> ::Array[WhopSDK::Models::TransferListParams::direction]
      end

      type order = :created_at | :amount

      module Order
        extend WhopSDK::Internal::Type::Enum

        CREATED_AT: :created_at
        AMOUNT: :amount

        def self?.values: -> ::Array[WhopSDK::Models::TransferListParams::order]
      end
    end
  end
end
