module WhopSDK
  module Models
    type unwrap_webhook_event =
      WhopSDK::CourseLessonInteractionCompletedWebhookEvent
      | WhopSDK::DisputeCreatedWebhookEvent
      | WhopSDK::DisputeUpdatedWebhookEvent
      | WhopSDK::DisputeAlertCreatedWebhookEvent
      | WhopSDK::EntryApprovedWebhookEvent
      | WhopSDK::EntryCreatedWebhookEvent
      | WhopSDK::EntryDeletedWebhookEvent
      | WhopSDK::EntryDeniedWebhookEvent
      | WhopSDK::IdentityProfileApprovedWebhookEvent
      | WhopSDK::IdentityProfileNeedsActionWebhookEvent
      | WhopSDK::IdentityProfileRejectedWebhookEvent
      | WhopSDK::IdentityProfileUpdatedWebhookEvent
      | WhopSDK::InvoiceCreatedWebhookEvent
      | WhopSDK::InvoiceMarkedUncollectibleWebhookEvent
      | WhopSDK::InvoicePaidWebhookEvent
      | WhopSDK::InvoicePastDueWebhookEvent
      | WhopSDK::InvoiceVoidedWebhookEvent
      | WhopSDK::MembershipActivatedWebhookEvent
      | WhopSDK::MembershipCancelAtPeriodEndChangedWebhookEvent
      | WhopSDK::MembershipDeactivatedWebhookEvent
      | WhopSDK::PaymentCreatedWebhookEvent
      | WhopSDK::PaymentFailedWebhookEvent
      | WhopSDK::PaymentPendingWebhookEvent
      | WhopSDK::PaymentSucceededWebhookEvent
      | WhopSDK::PayoutAccountStatusUpdatedWebhookEvent
      | WhopSDK::PayoutMethodCreatedWebhookEvent
      | WhopSDK::RefundCreatedWebhookEvent
      | WhopSDK::RefundUpdatedWebhookEvent
      | WhopSDK::ResolutionCenterCaseCreatedWebhookEvent
      | WhopSDK::ResolutionCenterCaseDecidedWebhookEvent
      | WhopSDK::ResolutionCenterCaseUpdatedWebhookEvent
      | WhopSDK::SetupIntentCanceledWebhookEvent
      | WhopSDK::SetupIntentRequiresActionWebhookEvent
      | WhopSDK::SetupIntentSucceededWebhookEvent
      | WhopSDK::VerificationSucceededWebhookEvent
      | WhopSDK::WithdrawalCreatedWebhookEvent
      | WhopSDK::WithdrawalUpdatedWebhookEvent

    module UnwrapWebhookEvent
      extend WhopSDK::Internal::Type::Union

      def self?.variants: -> ::Array[WhopSDK::Models::unwrap_webhook_event]
    end
  end
end
