module WhopSDK
  module Models
    type unwrap_webhook_event =
      WhopSDK::AccountUpdatedWebhookEvent
      | WhopSDK::AdCampaignPaymentFailedWebhookEvent
      | WhopSDK::CardCanceledWebhookEvent
      | WhopSDK::CardCreatedWebhookEvent
      | WhopSDK::CardFrozenWebhookEvent
      | WhopSDK::CardUpdatedWebhookEvent
      | WhopSDK::CardApplicationApprovedWebhookEvent
      | WhopSDK::CardApplicationCreatedWebhookEvent
      | WhopSDK::CardApplicationDeniedWebhookEvent
      | WhopSDK::CardApplicationUpdatedWebhookEvent
      | WhopSDK::CardTransactionCompletedWebhookEvent
      | WhopSDK::CardTransactionCreatedWebhookEvent
      | WhopSDK::CardTransactionDeclinedWebhookEvent
      | WhopSDK::CardTransactionReversedWebhookEvent
      | WhopSDK::CardTransactionUpdatedWebhookEvent
      | WhopSDK::ChatMessageCreatedWebhookEvent
      | WhopSDK::ChatReactionCreatedWebhookEvent
      | WhopSDK::CourseLessonInteractionCompletedWebhookEvent
      | WhopSDK::DepositSucceededWebhookEvent
      | WhopSDK::DisputeCreatedWebhookEvent
      | WhopSDK::DisputeUpdatedWebhookEvent
      | WhopSDK::DisputeAlertCreatedWebhookEvent
      | WhopSDK::EntryApprovedWebhookEvent
      | WhopSDK::EntryCreatedWebhookEvent
      | WhopSDK::EntryDeletedWebhookEvent
      | WhopSDK::EntryDeniedWebhookEvent
      | WhopSDK::ExportCompletedWebhookEvent
      | WhopSDK::ExportFailedWebhookEvent
      | WhopSDK::IdentityProfileUpdatedWebhookEvent
      | WhopSDK::InvoiceCreatedWebhookEvent
      | WhopSDK::InvoiceMarkedUncollectibleWebhookEvent
      | WhopSDK::InvoicePaidWebhookEvent
      | WhopSDK::InvoicePastDueWebhookEvent
      | WhopSDK::InvoiceVoidedWebhookEvent
      | WhopSDK::LedgerAccountFundsAvailableWebhookEvent
      | WhopSDK::MemberCreatedWebhookEvent
      | WhopSDK::MembershipActivatedWebhookEvent
      | WhopSDK::MembershipCancelAtPeriodEndChangedWebhookEvent
      | WhopSDK::MembershipDeactivatedWebhookEvent
      | WhopSDK::MembershipTrialEndingSoonWebhookEvent
      | WhopSDK::PaymentAuthorizedWebhookEvent
      | WhopSDK::PaymentCanceledWebhookEvent
      | WhopSDK::PaymentCreatedWebhookEvent
      | WhopSDK::PaymentFailedWebhookEvent
      | WhopSDK::PaymentPendingWebhookEvent
      | WhopSDK::PaymentSucceededWebhookEvent
      | WhopSDK::PayoutCreatedWebhookEvent
      | WhopSDK::PayoutReversedWebhookEvent
      | WhopSDK::PayoutUpdatedWebhookEvent
      | WhopSDK::PayoutAccountStatusUpdatedWebhookEvent
      | WhopSDK::PayoutMethodCreatedWebhookEvent
      | WhopSDK::PlanCreatedWebhookEvent
      | WhopSDK::PlanDeletedWebhookEvent
      | WhopSDK::PlanUpdatedWebhookEvent
      | WhopSDK::ProductCreatedWebhookEvent
      | WhopSDK::ProductDeletedWebhookEvent
      | WhopSDK::ProductPublishedWebhookEvent
      | WhopSDK::ProductUnpublishedWebhookEvent
      | WhopSDK::ProductUpdatedWebhookEvent
      | WhopSDK::RefundCreatedWebhookEvent
      | WhopSDK::RefundUpdatedWebhookEvent
      | WhopSDK::ResolutionCenterCaseCreatedWebhookEvent
      | WhopSDK::ResolutionCenterCaseDecidedWebhookEvent
      | WhopSDK::ResolutionCenterCaseUpdatedWebhookEvent
      | WhopSDK::SetupIntentCanceledWebhookEvent
      | WhopSDK::SetupIntentRequiresActionWebhookEvent
      | WhopSDK::SetupIntentSucceededWebhookEvent
      | WhopSDK::ShipmentCreatedWebhookEvent
      | WhopSDK::ShipmentUpdatedWebhookEvent
      | WhopSDK::SwapCompletedWebhookEvent
      | WhopSDK::TransferCompletedWebhookEvent
      | WhopSDK::TransferCreatedWebhookEvent
      | WhopSDK::TransferFailedWebhookEvent
      | WhopSDK::VerificationSucceededWebhookEvent

    module UnwrapWebhookEvent
      extend WhopSDK::Internal::Type::Union

      def self?.variants: -> ::Array[WhopSDK::Models::unwrap_webhook_event]
    end
  end
end
