module WhopSDK
  module Models
    type unwrap_webhook_event =
      WhopSDK::InvoiceCreatedWebhookEvent
      | WhopSDK::InvoicePaidWebhookEvent
      | WhopSDK::InvoicePastDueWebhookEvent
      | WhopSDK::InvoiceVoidedWebhookEvent
      | WhopSDK::MembershipActivatedWebhookEvent
      | WhopSDK::MembershipDeactivatedWebhookEvent
      | WhopSDK::EntryCreatedWebhookEvent
      | WhopSDK::EntryApprovedWebhookEvent
      | WhopSDK::EntryDeniedWebhookEvent
      | WhopSDK::EntryDeletedWebhookEvent
      | WhopSDK::CourseLessonInteractionCompletedWebhookEvent
      | WhopSDK::PaymentSucceededWebhookEvent
      | WhopSDK::PaymentFailedWebhookEvent
      | WhopSDK::PaymentPendingWebhookEvent
      | WhopSDK::DisputeCreatedWebhookEvent
      | WhopSDK::DisputeUpdatedWebhookEvent

    module UnwrapWebhookEvent
      extend WhopSDK::Internal::Type::Union

      def self?.variants: -> ::Array[WhopSDK::Models::unwrap_webhook_event]
    end
  end
end
