module WhopSDK
  module Models
    type user =
      {
        id: String,
        bio: String?,
        created_at: String,
        name: String?,
        profile_picture: top?,
        username: String
      }

    class User < WhopSDK::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor bio: String?

      attr_accessor created_at: String

      attr_accessor name: String?

      attr_accessor profile_picture: top?

      attr_accessor username: String

      def initialize: (
        id: String,
        bio: String?,
        created_at: String,
        name: String?,
        profile_picture: top?,
        username: String
      ) -> void

      def to_hash: -> {
        id: String,
        bio: String?,
        created_at: String,
        name: String?,
        profile_picture: top?,
        username: String
      }
    end
  end
end
