module WhopSDK
  module Models
    type user =
      {
        id: String,
        balance: WhopSDK::UserBalance?,
        balance_history: WhopSDK::User::BalanceHistory?,
        bio: String?,
        created_at: String,
        earnings_usd: WhopSDK::User::EarningsUsd?,
        name: String?,
        profile_picture: top?,
        username: String,
        verification: top,
        whop_partner_enabled_at: String?
      }

    class User < WhopSDK::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor balance: WhopSDK::UserBalance?

      attr_accessor balance_history: WhopSDK::User::BalanceHistory?

      attr_accessor bio: String?

      attr_accessor created_at: String

      attr_accessor earnings_usd: WhopSDK::User::EarningsUsd?

      attr_accessor name: String?

      attr_accessor profile_picture: top?

      attr_accessor username: String

      attr_accessor verification: top

      attr_accessor whop_partner_enabled_at: String?

      def initialize: (
        id: String,
        balance: WhopSDK::UserBalance?,
        balance_history: WhopSDK::User::BalanceHistory?,
        bio: String?,
        created_at: String,
        earnings_usd: WhopSDK::User::EarningsUsd?,
        name: String?,
        profile_picture: top?,
        username: String,
        verification: top,
        whop_partner_enabled_at: String?
      ) -> void

      def to_hash: -> {
        id: String,
        balance: WhopSDK::UserBalance?,
        balance_history: WhopSDK::User::BalanceHistory?,
        bio: String?,
        created_at: String,
        earnings_usd: WhopSDK::User::EarningsUsd?,
        name: String?,
        profile_picture: top?,
        username: String,
        verification: top,
        whop_partner_enabled_at: String?
      }

      type balance_history =
        {
          data: ::Array[WhopSDK::User::BalanceHistory::Data],
          last: Float,
          max: Float,
          min: Float
        }

      class BalanceHistory < WhopSDK::Internal::Type::BaseModel
        attr_accessor data: ::Array[WhopSDK::User::BalanceHistory::Data]

        attr_accessor last: Float

        attr_accessor max: Float

        attr_accessor min: Float

        def initialize: (
          data: ::Array[WhopSDK::User::BalanceHistory::Data],
          last: Float,
          max: Float,
          min: Float
        ) -> void

        def to_hash: -> {
          data: ::Array[WhopSDK::User::BalanceHistory::Data],
          last: Float,
          max: Float,
          min: Float
        }

        type data = { t: Integer, v: Float }

        class Data < WhopSDK::Internal::Type::BaseModel
          attr_accessor t: Integer

          attr_accessor v: Float

          def initialize: (t: Integer, v: Float) -> void

          def to_hash: -> { t: Integer, v: Float }
        end
      end

      type earnings_usd =
        {
          first_earned_at: String?,
          owned_accounts: WhopSDK::User::EarningsUsd::OwnedAccounts,
          personal: WhopSDK::User::EarningsUsd::Personal,
          total: WhopSDK::User::EarningsUsd::Total
        }

      class EarningsUsd < WhopSDK::Internal::Type::BaseModel
        attr_accessor first_earned_at: String?

        attr_accessor owned_accounts: WhopSDK::User::EarningsUsd::OwnedAccounts

        attr_accessor personal: WhopSDK::User::EarningsUsd::Personal

        attr_accessor total: WhopSDK::User::EarningsUsd::Total

        def initialize: (
          first_earned_at: String?,
          owned_accounts: WhopSDK::User::EarningsUsd::OwnedAccounts,
          personal: WhopSDK::User::EarningsUsd::Personal,
          total: WhopSDK::User::EarningsUsd::Total
        ) -> void

        def to_hash: -> {
          first_earned_at: String?,
          owned_accounts: WhopSDK::User::EarningsUsd::OwnedAccounts,
          personal: WhopSDK::User::EarningsUsd::Personal,
          total: WhopSDK::User::EarningsUsd::Total
        }

        type owned_accounts =
          {
            :last_24_hours => String,
            :last_30_days => String,
            :last_7_days => String,
            lifetime: String
          }

        class OwnedAccounts < WhopSDK::Internal::Type::BaseModel
          attr_accessor last_24_hours: String

          attr_accessor last_30_days: String

          attr_accessor last_7_days: String

          attr_accessor lifetime: String

          def initialize: (
            last_24_hours: String,
            last_30_days: String,
            last_7_days: String,
            lifetime: String
          ) -> void

          def to_hash: -> {
            :last_24_hours => String,
            :last_30_days => String,
            :last_7_days => String,
            lifetime: String
          }
        end

        type personal =
          {
            :last_24_hours => String,
            :last_30_days => String,
            :last_7_days => String,
            lifetime: String
          }

        class Personal < WhopSDK::Internal::Type::BaseModel
          attr_accessor last_24_hours: String

          attr_accessor last_30_days: String

          attr_accessor last_7_days: String

          attr_accessor lifetime: String

          def initialize: (
            last_24_hours: String,
            last_30_days: String,
            last_7_days: String,
            lifetime: String
          ) -> void

          def to_hash: -> {
            :last_24_hours => String,
            :last_30_days => String,
            :last_7_days => String,
            lifetime: String
          }
        end

        type total =
          {
            :last_24_hours => String,
            :last_30_days => String,
            :last_7_days => String,
            lifetime: String
          }

        class Total < WhopSDK::Internal::Type::BaseModel
          attr_accessor last_24_hours: String

          attr_accessor last_30_days: String

          attr_accessor last_7_days: String

          attr_accessor lifetime: String

          def initialize: (
            last_24_hours: String,
            last_30_days: String,
            last_7_days: String,
            lifetime: String
          ) -> void

          def to_hash: -> {
            :last_24_hours => String,
            :last_30_days => String,
            :last_7_days => String,
            lifetime: String
          }
        end
      end
    end
  end
end
