module WhopSDK
  module Models
    type user_list_params =
      {
        after: String,
        before: String,
        first: Integer,
        last: Integer,
        query: String
      }
      & WhopSDK::Internal::Type::request_parameters

    class UserListParams < WhopSDK::Internal::Type::BaseModel
      extend WhopSDK::Internal::Type::RequestParameters::Converter
      include WhopSDK::Internal::Type::RequestParameters

      attr_reader after: String?

      def after=: (String) -> String

      attr_reader before: String?

      def before=: (String) -> String

      attr_reader first: Integer?

      def first=: (Integer) -> Integer

      attr_reader last: Integer?

      def last=: (Integer) -> Integer

      attr_reader query: String?

      def query=: (String) -> String

      def initialize: (
        ?after: String,
        ?before: String,
        ?first: Integer,
        ?last: Integer,
        ?query: String,
        ?request_options: WhopSDK::request_opts
      ) -> void

      def to_hash: -> {
        after: String,
        before: String,
        first: Integer,
        last: Integer,
        query: String,
        request_options: WhopSDK::RequestOptions
      }
    end
  end
end
