module WhopSDK
  module Models
    type verification_succeeded_webhook_event =
      {
        id: String,
        api_version: :v1,
        api_version_date: String?,
        data: WhopSDK::VerificationSucceededWebhookEvent::Data,
        timestamp: Time,
        type: :"verification.succeeded",
        account_id: String?,
        previous_attributes: top
      }

    class VerificationSucceededWebhookEvent < WhopSDK::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor api_version: :v1

      attr_accessor api_version_date: String?

      attr_accessor data: WhopSDK::VerificationSucceededWebhookEvent::Data

      attr_accessor timestamp: Time

      attr_accessor type: :"verification.succeeded"

      attr_accessor account_id: String?

      attr_reader previous_attributes: top?

      def previous_attributes=: (top) -> top

      def initialize: (
        id: String,
        api_version_date: String?,
        data: WhopSDK::VerificationSucceededWebhookEvent::Data,
        timestamp: Time,
        ?account_id: String?,
        ?previous_attributes: top,
        ?api_version: :v1,
        ?type: :"verification.succeeded"
      ) -> void

      def to_hash: -> {
        id: String,
        api_version: :v1,
        api_version_date: String?,
        data: WhopSDK::VerificationSucceededWebhookEvent::Data,
        timestamp: Time,
        type: :"verification.succeeded",
        account_id: String?,
        previous_attributes: top
      }

      type data =
        {
          id: String,
          last_error_code: WhopSDK::Models::verification_error_code?,
          last_error_reason: String?,
          status: WhopSDK::Models::verification_status
        }

      class Data < WhopSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor last_error_code: WhopSDK::Models::verification_error_code?

        attr_accessor last_error_reason: String?

        attr_accessor status: WhopSDK::Models::verification_status

        def initialize: (
          id: String,
          last_error_code: WhopSDK::Models::verification_error_code?,
          last_error_reason: String?,
          status: WhopSDK::Models::verification_status
        ) -> void

        def to_hash: -> {
          id: String,
          last_error_code: WhopSDK::Models::verification_error_code?,
          last_error_reason: String?,
          status: WhopSDK::Models::verification_status
        }
      end
    end
  end
end
