module WhopSDK
  module Models
    type wallet_send_params =
      { account_id: String, amount: String, to: String }
      & WhopSDK::Internal::Type::request_parameters

    class WalletSendParams < WhopSDK::Internal::Type::BaseModel
      extend WhopSDK::Internal::Type::RequestParameters::Converter
      include WhopSDK::Internal::Type::RequestParameters

      attr_accessor account_id: String

      attr_accessor amount: String

      attr_accessor to: String

      def initialize: (
        account_id: String,
        amount: String,
        to: String,
        ?request_options: WhopSDK::request_opts
      ) -> void

      def to_hash: -> {
        account_id: String,
        amount: String,
        to: String,
        request_options: WhopSDK::RequestOptions
      }
    end
  end
end
