module WhopSDK
  module Models
    type wallet_ping_response =
      { status: WhopSDK::Models::WalletPingResponse::status }

    class WalletPingResponse < WhopSDK::Internal::Type::BaseModel
      attr_accessor status: WhopSDK::Models::WalletPingResponse::status

      def initialize: (
        status: WhopSDK::Models::WalletPingResponse::status
      ) -> void

      def to_hash: -> { status: WhopSDK::Models::WalletPingResponse::status }

      type status = :ok

      module Status
        extend WhopSDK::Internal::Type::Enum

        OK: :ok

        def self?.values: -> ::Array[WhopSDK::Models::WalletPingResponse::status]
      end
    end
  end
end
