module WhopSDK
  module Models
    type wallet_deposit_address_response =
      {
        address: String,
        object: WhopSDK::Models::WalletDepositAddressResponse::object,
        supported_networks: ::Array[WhopSDK::Models::WalletDepositAddressResponse::SupportedNetwork]
      }

    class WalletDepositAddressResponse < WhopSDK::Internal::Type::BaseModel
      attr_accessor address: String

      attr_accessor object: WhopSDK::Models::WalletDepositAddressResponse::object

      attr_accessor supported_networks: ::Array[WhopSDK::Models::WalletDepositAddressResponse::SupportedNetwork]

      def initialize: (
        address: String,
        object: WhopSDK::Models::WalletDepositAddressResponse::object,
        supported_networks: ::Array[WhopSDK::Models::WalletDepositAddressResponse::SupportedNetwork]
      ) -> void

      def to_hash: -> {
        address: String,
        object: WhopSDK::Models::WalletDepositAddressResponse::object,
        supported_networks: ::Array[WhopSDK::Models::WalletDepositAddressResponse::SupportedNetwork]
      }

      type object = :deposit_address

      module Object
        extend WhopSDK::Internal::Type::Enum

        DEPOSIT_ADDRESS: :deposit_address

        def self?.values: -> ::Array[WhopSDK::Models::WalletDepositAddressResponse::object]
      end

      type supported_network = { chain_id: Integer, name: String }

      class SupportedNetwork < WhopSDK::Internal::Type::BaseModel
        attr_accessor chain_id: Integer

        attr_accessor name: String

        def initialize: (chain_id: Integer, name: String) -> void

        def to_hash: -> { chain_id: Integer, name: String }
      end
    end
  end
end
