module WhopSDK
  module Models
    type webhook_delete_response = { id: String, deleted: bool }

    class WebhookDeleteResponse < WhopSDK::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor deleted: bool

      def initialize: (id: String, deleted: bool) -> void

      def to_hash: -> { id: String, deleted: bool }
    end
  end
end
