module WhopSDK
  module Models
    type webhook_create_response =
      {
        id: String,
        api_version: WhopSDK::Models::api_version,
        child_resource_events: bool,
        created_at: Time,
        enabled: bool,
        events: ::Array[WhopSDK::Models::webhook_event],
        resource_id: String,
        testable_events: ::Array[WhopSDK::Models::webhook_event],
        url: String,
        webhook_secret: String
      }

    class WebhookCreateResponse < WhopSDK::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor api_version: WhopSDK::Models::api_version

      attr_accessor child_resource_events: bool

      attr_accessor created_at: Time

      attr_accessor enabled: bool

      attr_accessor events: ::Array[WhopSDK::Models::webhook_event]

      attr_accessor resource_id: String

      attr_accessor testable_events: ::Array[WhopSDK::Models::webhook_event]

      attr_accessor url: String

      attr_accessor webhook_secret: String

      def initialize: (
        id: String,
        api_version: WhopSDK::Models::api_version,
        child_resource_events: bool,
        created_at: Time,
        enabled: bool,
        events: ::Array[WhopSDK::Models::webhook_event],
        resource_id: String,
        testable_events: ::Array[WhopSDK::Models::webhook_event],
        url: String,
        webhook_secret: String
      ) -> void

      def to_hash: -> {
        id: String,
        api_version: WhopSDK::Models::api_version,
        child_resource_events: bool,
        created_at: Time,
        enabled: bool,
        events: ::Array[WhopSDK::Models::webhook_event],
        resource_id: String,
        testable_events: ::Array[WhopSDK::Models::webhook_event],
        url: String,
        webhook_secret: String
      }
    end
  end
end
