module WhopSDK
  module Models
    type who_can_post = :everyone | :admins

    module WhoCanPost
      extend WhopSDK::Internal::Type::Enum

      EVERYONE: :everyone
      ADMINS: :admins

      def self?.values: -> ::Array[WhopSDK::Models::who_can_post]
    end
  end
end
