module WhopSDK
  module Models
    type withdrawal_create_params =
      {
        amount: Float,
        company_id: String,
        currency: WhopSDK::Models::currency,
        payout_method_id: String?,
        platform_covers_fees: bool?,
        statement_descriptor: String?
      }
      & WhopSDK::Internal::Type::request_parameters

    class WithdrawalCreateParams < WhopSDK::Internal::Type::BaseModel
      extend WhopSDK::Internal::Type::RequestParameters::Converter
      include WhopSDK::Internal::Type::RequestParameters

      attr_accessor amount: Float

      attr_accessor company_id: String

      attr_accessor currency: WhopSDK::Models::currency

      attr_accessor payout_method_id: String?

      attr_accessor platform_covers_fees: bool?

      attr_accessor statement_descriptor: String?

      def initialize: (
        amount: Float,
        company_id: String,
        currency: WhopSDK::Models::currency,
        ?payout_method_id: String?,
        ?platform_covers_fees: bool?,
        ?statement_descriptor: String?,
        ?request_options: WhopSDK::request_opts
      ) -> void

      def to_hash: -> {
        amount: Float,
        company_id: String,
        currency: WhopSDK::Models::currency,
        payout_method_id: String?,
        platform_covers_fees: bool?,
        statement_descriptor: String?,
        request_options: WhopSDK::RequestOptions
      }
    end
  end
end
